/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.nsd.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro;
import org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTroModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TaiNguyen2VaiTro service. Represents a row in the &quot;CMON_TAINGUYEN2VAITRO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTroModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaiNguyen2VaiTroImpl}.
 * </p>
 *
 * @author Liemnn
 * @see TaiNguyen2VaiTroImpl
 * @see org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro
 * @see org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTroModel
 * @generated
 */
public class TaiNguyen2VaiTroModelImpl extends BaseModelImpl<TaiNguyen2VaiTro>
	implements TaiNguyen2VaiTroModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tai nguyen2 vai tro model instance should use the {@link org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_TAINGUYEN2VAITRO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TAINGUYENID", Types.BIGINT },
			{ "VAITROID", Types.BIGINT },
			{ "HANHDONG", Types.INTEGER },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "DAXOA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_TAINGUYEN2VAITRO (ID LONG not null primary key,TAINGUYENID LONG null,VAITROID LONG null,HANHDONG INTEGER,NGAYTAO DATE null,NGUOITAO VARCHAR(75) null,NGAYSUA DATE null,NGUOISUA VARCHAR(75) null,DAXOA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_TAINGUYEN2VAITRO";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long VAITROID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro"));

	public TaiNguyen2VaiTroModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TaiNguyen2VaiTro.class;
	}

	public String getModelClassName() {
		return TaiNguyen2VaiTro.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public Long getTaiNguyenId() {
		return _taiNguyenId;
	}

	public void setTaiNguyenId(Long taiNguyenId) {
		_taiNguyenId = taiNguyenId;
	}

	public Long getVaiTroId() {
		return _vaiTroId;
	}

	public void setVaiTroId(Long vaiTroId) {
		_columnBitmask |= VAITROID_COLUMN_BITMASK;

		if (!_setOriginalVaiTroId) {
			_setOriginalVaiTroId = true;

			_originalVaiTroId = _vaiTroId;
		}

		_vaiTroId = vaiTroId;
	}

	public Long getOriginalVaiTroId() {
		return _originalVaiTroId;
	}

	public int getHanhDong() {
		return _hanhDong;
	}

	public void setHanhDong(int hanhDong) {
		_hanhDong = hanhDong;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TaiNguyen2VaiTro toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TaiNguyen2VaiTro)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TaiNguyen2VaiTro.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TaiNguyen2VaiTroImpl taiNguyen2VaiTroImpl = new TaiNguyen2VaiTroImpl();

		taiNguyen2VaiTroImpl.setId(getId());
		taiNguyen2VaiTroImpl.setTaiNguyenId(getTaiNguyenId());
		taiNguyen2VaiTroImpl.setVaiTroId(getVaiTroId());
		taiNguyen2VaiTroImpl.setHanhDong(getHanhDong());
		taiNguyen2VaiTroImpl.setNgayTao(getNgayTao());
		taiNguyen2VaiTroImpl.setNguoiTao(getNguoiTao());
		taiNguyen2VaiTroImpl.setNgaySua(getNgaySua());
		taiNguyen2VaiTroImpl.setNguoiSua(getNguoiSua());
		taiNguyen2VaiTroImpl.setDaXoa(getDaXoa());

		taiNguyen2VaiTroImpl.resetOriginalValues();

		return taiNguyen2VaiTroImpl;
	}

	public int compareTo(TaiNguyen2VaiTro taiNguyen2VaiTro) {
		long primaryKey = taiNguyen2VaiTro.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TaiNguyen2VaiTro taiNguyen2VaiTro = null;

		try {
			taiNguyen2VaiTro = (TaiNguyen2VaiTro)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = taiNguyen2VaiTro.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TaiNguyen2VaiTroModelImpl taiNguyen2VaiTroModelImpl = this;

		taiNguyen2VaiTroModelImpl._originalVaiTroId = taiNguyen2VaiTroModelImpl._vaiTroId;

		taiNguyen2VaiTroModelImpl._setOriginalVaiTroId = false;

		taiNguyen2VaiTroModelImpl._originalDaXoa = taiNguyen2VaiTroModelImpl._daXoa;

		taiNguyen2VaiTroModelImpl._setOriginalDaXoa = false;

		taiNguyen2VaiTroModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaiNguyen2VaiTro> toCacheModel() {
		TaiNguyen2VaiTroCacheModel taiNguyen2VaiTroCacheModel = new TaiNguyen2VaiTroCacheModel();

		taiNguyen2VaiTroCacheModel.id = getId();

		taiNguyen2VaiTroCacheModel.taiNguyenId = getTaiNguyenId();

		taiNguyen2VaiTroCacheModel.vaiTroId = getVaiTroId();

		taiNguyen2VaiTroCacheModel.hanhDong = getHanhDong();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			taiNguyen2VaiTroCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			taiNguyen2VaiTroCacheModel.ngayTao = Long.MIN_VALUE;
		}

		taiNguyen2VaiTroCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = taiNguyen2VaiTroCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			taiNguyen2VaiTroCacheModel.nguoiTao = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			taiNguyen2VaiTroCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			taiNguyen2VaiTroCacheModel.ngaySua = Long.MIN_VALUE;
		}

		taiNguyen2VaiTroCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = taiNguyen2VaiTroCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			taiNguyen2VaiTroCacheModel.nguoiSua = null;
		}

		taiNguyen2VaiTroCacheModel.daXoa = getDaXoa();

		return taiNguyen2VaiTroCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", taiNguyenId=");
		sb.append(getTaiNguyenId());
		sb.append(", vaiTroId=");
		sb.append(getVaiTroId());
		sb.append(", hanhDong=");
		sb.append(getHanhDong());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.nsd.model.TaiNguyen2VaiTro");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiNguyenId</column-name><column-value><![CDATA[");
		sb.append(getTaiNguyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vaiTroId</column-name><column-value><![CDATA[");
		sb.append(getVaiTroId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hanhDong</column-name><column-value><![CDATA[");
		sb.append(getHanhDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TaiNguyen2VaiTro.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TaiNguyen2VaiTro.class
		};
	private long _id;
	private Long _taiNguyenId;
	private Long _vaiTroId;
	private Long _originalVaiTroId;
	private boolean _setOriginalVaiTroId;
	private int _hanhDong;
	private Date _ngayTao;
	private String _nguoiTao;
	private Date _ngaySua;
	private String _nguoiSua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TaiNguyen2VaiTro _escapedModelProxy;
}