/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.tlct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.tlct.model.DanhMucGiayTo;
import org.oep.cmon.dao.tlct.model.DanhMucGiayToModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the DanhMucGiayTo service. Represents a row in the &quot;CMON_DANHMUCGIAYTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.tlct.model.DanhMucGiayToModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhMucGiayToImpl}.
 * </p>
 *
 * @author Liemnn
 * @see DanhMucGiayToImpl
 * @see org.oep.cmon.dao.tlct.model.DanhMucGiayTo
 * @see org.oep.cmon.dao.tlct.model.DanhMucGiayToModel
 * @generated
 */
public class DanhMucGiayToModelImpl extends BaseModelImpl<DanhMucGiayTo>
	implements DanhMucGiayToModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh muc giay to model instance should use the {@link org.oep.cmon.dao.tlct.model.DanhMucGiayTo} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_DANHMUCGIAYTO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "MOTA", Types.VARCHAR },
			{ "GIOIHANDUNGLUONG", Types.BIGINT },
			{ "KIEUTAILIEU", Types.VARCHAR },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "PHIENBAN", Types.BIGINT },
			{ "THAYTHETAILIEUID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_DANHMUCGIAYTO (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,MOTA VARCHAR(75) null,GIOIHANDUNGLUONG LONG,KIEUTAILIEU VARCHAR(75) null,NGUOITAO VARCHAR(75) null,NGAYTAO DATE null,NGUOISUA VARCHAR(75) null,NGAYSUA DATE null,DAXOA INTEGER,PHIENBAN LONG,THAYTHETAILIEUID LONG null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_DANHMUCGIAYTO";
	public static final String ORDER_BY_JPQL = " ORDER BY danhMucGiayTo.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_DANHMUCGIAYTO.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.tlct.model.DanhMucGiayTo"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.tlct.model.DanhMucGiayTo"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.tlct.model.DanhMucGiayTo"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long MA_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.tlct.model.DanhMucGiayTo"));

	public DanhMucGiayToModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DanhMucGiayTo.class;
	}

	public String getModelClassName() {
		return DanhMucGiayTo.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public String getMota() {
		if (_mota == null) {
			return StringPool.BLANK;
		}
		else {
			return _mota;
		}
	}

	public void setMota(String mota) {
		_mota = mota;
	}

	public long getGioiHanDungLuong() {
		return _gioiHanDungLuong;
	}

	public void setGioiHanDungLuong(long gioiHanDungLuong) {
		_gioiHanDungLuong = gioiHanDungLuong;
	}

	public String getKieuTaiLieu() {
		if (_kieuTaiLieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _kieuTaiLieu;
		}
	}

	public void setKieuTaiLieu(String kieuTaiLieu) {
		_kieuTaiLieu = kieuTaiLieu;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public long getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(long phienBan) {
		_phienBan = phienBan;
	}

	public Long getTailieuThayTheId() {
		return _tailieuThayTheId;
	}

	public void setTailieuThayTheId(Long tailieuThayTheId) {
		_tailieuThayTheId = tailieuThayTheId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DanhMucGiayTo toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DanhMucGiayTo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DanhMucGiayTo.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DanhMucGiayToImpl danhMucGiayToImpl = new DanhMucGiayToImpl();

		danhMucGiayToImpl.setId(getId());
		danhMucGiayToImpl.setMa(getMa());
		danhMucGiayToImpl.setTen(getTen());
		danhMucGiayToImpl.setMota(getMota());
		danhMucGiayToImpl.setGioiHanDungLuong(getGioiHanDungLuong());
		danhMucGiayToImpl.setKieuTaiLieu(getKieuTaiLieu());
		danhMucGiayToImpl.setNguoiTao(getNguoiTao());
		danhMucGiayToImpl.setNgayTao(getNgayTao());
		danhMucGiayToImpl.setNguoiSua(getNguoiSua());
		danhMucGiayToImpl.setNgaySua(getNgaySua());
		danhMucGiayToImpl.setDaXoa(getDaXoa());
		danhMucGiayToImpl.setPhienBan(getPhienBan());
		danhMucGiayToImpl.setTailieuThayTheId(getTailieuThayTheId());

		danhMucGiayToImpl.resetOriginalValues();

		return danhMucGiayToImpl;
	}

	public int compareTo(DanhMucGiayTo danhMucGiayTo) {
		int value = 0;

		if (getId() < danhMucGiayTo.getId()) {
			value = -1;
		}
		else if (getId() > danhMucGiayTo.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DanhMucGiayTo danhMucGiayTo = null;

		try {
			danhMucGiayTo = (DanhMucGiayTo)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = danhMucGiayTo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DanhMucGiayToModelImpl danhMucGiayToModelImpl = this;

		danhMucGiayToModelImpl._originalMa = danhMucGiayToModelImpl._ma;

		danhMucGiayToModelImpl._originalDaXoa = danhMucGiayToModelImpl._daXoa;

		danhMucGiayToModelImpl._setOriginalDaXoa = false;

		danhMucGiayToModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DanhMucGiayTo> toCacheModel() {
		DanhMucGiayToCacheModel danhMucGiayToCacheModel = new DanhMucGiayToCacheModel();

		danhMucGiayToCacheModel.id = getId();

		danhMucGiayToCacheModel.ma = getMa();

		String ma = danhMucGiayToCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			danhMucGiayToCacheModel.ma = null;
		}

		danhMucGiayToCacheModel.ten = getTen();

		String ten = danhMucGiayToCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			danhMucGiayToCacheModel.ten = null;
		}

		danhMucGiayToCacheModel.mota = getMota();

		String mota = danhMucGiayToCacheModel.mota;

		if ((mota != null) && (mota.length() == 0)) {
			danhMucGiayToCacheModel.mota = null;
		}

		danhMucGiayToCacheModel.gioiHanDungLuong = getGioiHanDungLuong();

		danhMucGiayToCacheModel.kieuTaiLieu = getKieuTaiLieu();

		String kieuTaiLieu = danhMucGiayToCacheModel.kieuTaiLieu;

		if ((kieuTaiLieu != null) && (kieuTaiLieu.length() == 0)) {
			danhMucGiayToCacheModel.kieuTaiLieu = null;
		}

		danhMucGiayToCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = danhMucGiayToCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			danhMucGiayToCacheModel.nguoiTao = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			danhMucGiayToCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			danhMucGiayToCacheModel.ngayTao = Long.MIN_VALUE;
		}

		danhMucGiayToCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = danhMucGiayToCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			danhMucGiayToCacheModel.nguoiSua = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			danhMucGiayToCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			danhMucGiayToCacheModel.ngaySua = Long.MIN_VALUE;
		}

		danhMucGiayToCacheModel.daXoa = getDaXoa();

		danhMucGiayToCacheModel.phienBan = getPhienBan();

		danhMucGiayToCacheModel.tailieuThayTheId = getTailieuThayTheId();

		return danhMucGiayToCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", mota=");
		sb.append(getMota());
		sb.append(", gioiHanDungLuong=");
		sb.append(getGioiHanDungLuong());
		sb.append(", kieuTaiLieu=");
		sb.append(getKieuTaiLieu());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", tailieuThayTheId=");
		sb.append(getTailieuThayTheId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.tlct.model.DanhMucGiayTo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mota</column-name><column-value><![CDATA[");
		sb.append(getMota());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiHanDungLuong</column-name><column-value><![CDATA[");
		sb.append(getGioiHanDungLuong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kieuTaiLieu</column-name><column-value><![CDATA[");
		sb.append(getKieuTaiLieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tailieuThayTheId</column-name><column-value><![CDATA[");
		sb.append(getTailieuThayTheId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanhMucGiayTo.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DanhMucGiayTo.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private String _mota;
	private long _gioiHanDungLuong;
	private String _kieuTaiLieu;
	private String _nguoiTao;
	private Date _ngayTao;
	private String _nguoiSua;
	private Date _ngaySua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private long _phienBan;
	private Long _tailieuThayTheId;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private DanhMucGiayTo _escapedModelProxy;
}