/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.tlct.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.oep.cmon.dao.tlct.model.DanhMucGiayTo;
import org.oep.cmon.dao.tlct.service.DanhMucGiayToLocalServiceUtil;

/**
 * The extended model base implementation for the DanhMucGiayTo service. Represents a row in the &quot;CMON_DANHMUCGIAYTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhMucGiayToImpl}.
 * </p>
 *
 * @author Liemnn
 * @see DanhMucGiayToImpl
 * @see org.oep.cmon.dao.tlct.model.DanhMucGiayTo
 * @generated
 */
public abstract class DanhMucGiayToBaseImpl extends DanhMucGiayToModelImpl
	implements DanhMucGiayTo {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh muc giay to model instance should use the {@link DanhMucGiayTo} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			DanhMucGiayToLocalServiceUtil.addDanhMucGiayTo(this);
		}
		else {
			DanhMucGiayToLocalServiceUtil.updateDanhMucGiayTo(this);
		}
	}
}