/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.tlct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem;
import org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKemModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the LichSuGiayToDinhKem service. Represents a row in the &quot;CMON_LICHSUGIAYTODINHKEM&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LichSuGiayToDinhKemImpl}.
 * </p>
 *
 * @author Liemnn
 * @see LichSuGiayToDinhKemImpl
 * @see org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem
 * @see org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKemModel
 * @generated
 */
public class LichSuGiayToDinhKemModelImpl extends BaseModelImpl<LichSuGiayToDinhKem>
	implements LichSuGiayToDinhKemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lich su giay to dinh kem model instance should use the {@link org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_LICHSUGIAYTODINHKEM";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "GIAYTODINHKEMHOSOID", Types.BIGINT },
			{ "HANHDONG", Types.INTEGER },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NOILUUTRUTAILIEUID", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "TENTAILIEU", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_LICHSUGIAYTODINHKEM (ID LONG not null primary key,GIAYTODINHKEMHOSOID LONG null,HANHDONG INTEGER,NGUOITAO VARCHAR(75) null,NOILUUTRUTAILIEUID LONG,NGAYTAO DATE null,TENTAILIEU VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_LICHSUGIAYTODINHKEM";
	public static final String ORDER_BY_JPQL = " ORDER BY lichSuGiayToDinhKem.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_LICHSUGIAYTODINHKEM.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem"),
			true);
	public static long GIAYTODINHKEMHOSOID_COLUMN_BITMASK = 1L;
	public static long NOILUUTRUTAILIEUID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem"));

	public LichSuGiayToDinhKemModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return LichSuGiayToDinhKem.class;
	}

	public String getModelClassName() {
		return LichSuGiayToDinhKem.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public Long getGiayToDinhKemHoSoId() {
		return _giayToDinhKemHoSoId;
	}

	public void setGiayToDinhKemHoSoId(Long giayToDinhKemHoSoId) {
		_columnBitmask |= GIAYTODINHKEMHOSOID_COLUMN_BITMASK;

		if (!_setOriginalGiayToDinhKemHoSoId) {
			_setOriginalGiayToDinhKemHoSoId = true;

			_originalGiayToDinhKemHoSoId = _giayToDinhKemHoSoId;
		}

		_giayToDinhKemHoSoId = giayToDinhKemHoSoId;
	}

	public Long getOriginalGiayToDinhKemHoSoId() {
		return _originalGiayToDinhKemHoSoId;
	}

	public int getHanhDong() {
		return _hanhDong;
	}

	public void setHanhDong(int hanhDong) {
		_hanhDong = hanhDong;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public long getNoiLuuTruTaiLieuId() {
		return _noiLuuTruTaiLieuId;
	}

	public void setNoiLuuTruTaiLieuId(long noiLuuTruTaiLieuId) {
		_columnBitmask |= NOILUUTRUTAILIEUID_COLUMN_BITMASK;

		if (!_setOriginalNoiLuuTruTaiLieuId) {
			_setOriginalNoiLuuTruTaiLieuId = true;

			_originalNoiLuuTruTaiLieuId = _noiLuuTruTaiLieuId;
		}

		_noiLuuTruTaiLieuId = noiLuuTruTaiLieuId;
	}

	public long getOriginalNoiLuuTruTaiLieuId() {
		return _originalNoiLuuTruTaiLieuId;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getTenTaiLieu() {
		if (_tenTaiLieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTaiLieu;
		}
	}

	public void setTenTaiLieu(String tenTaiLieu) {
		_tenTaiLieu = tenTaiLieu;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public LichSuGiayToDinhKem toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (LichSuGiayToDinhKem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					LichSuGiayToDinhKem.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		LichSuGiayToDinhKemImpl lichSuGiayToDinhKemImpl = new LichSuGiayToDinhKemImpl();

		lichSuGiayToDinhKemImpl.setId(getId());
		lichSuGiayToDinhKemImpl.setGiayToDinhKemHoSoId(getGiayToDinhKemHoSoId());
		lichSuGiayToDinhKemImpl.setHanhDong(getHanhDong());
		lichSuGiayToDinhKemImpl.setNguoiTao(getNguoiTao());
		lichSuGiayToDinhKemImpl.setNoiLuuTruTaiLieuId(getNoiLuuTruTaiLieuId());
		lichSuGiayToDinhKemImpl.setNgayTao(getNgayTao());
		lichSuGiayToDinhKemImpl.setTenTaiLieu(getTenTaiLieu());

		lichSuGiayToDinhKemImpl.resetOriginalValues();

		return lichSuGiayToDinhKemImpl;
	}

	public int compareTo(LichSuGiayToDinhKem lichSuGiayToDinhKem) {
		int value = 0;

		if (getId() < lichSuGiayToDinhKem.getId()) {
			value = -1;
		}
		else if (getId() > lichSuGiayToDinhKem.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		LichSuGiayToDinhKem lichSuGiayToDinhKem = null;

		try {
			lichSuGiayToDinhKem = (LichSuGiayToDinhKem)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = lichSuGiayToDinhKem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LichSuGiayToDinhKemModelImpl lichSuGiayToDinhKemModelImpl = this;

		lichSuGiayToDinhKemModelImpl._originalGiayToDinhKemHoSoId = lichSuGiayToDinhKemModelImpl._giayToDinhKemHoSoId;

		lichSuGiayToDinhKemModelImpl._setOriginalGiayToDinhKemHoSoId = false;

		lichSuGiayToDinhKemModelImpl._originalNoiLuuTruTaiLieuId = lichSuGiayToDinhKemModelImpl._noiLuuTruTaiLieuId;

		lichSuGiayToDinhKemModelImpl._setOriginalNoiLuuTruTaiLieuId = false;

		lichSuGiayToDinhKemModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LichSuGiayToDinhKem> toCacheModel() {
		LichSuGiayToDinhKemCacheModel lichSuGiayToDinhKemCacheModel = new LichSuGiayToDinhKemCacheModel();

		lichSuGiayToDinhKemCacheModel.id = getId();

		lichSuGiayToDinhKemCacheModel.giayToDinhKemHoSoId = getGiayToDinhKemHoSoId();

		lichSuGiayToDinhKemCacheModel.hanhDong = getHanhDong();

		lichSuGiayToDinhKemCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = lichSuGiayToDinhKemCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			lichSuGiayToDinhKemCacheModel.nguoiTao = null;
		}

		lichSuGiayToDinhKemCacheModel.noiLuuTruTaiLieuId = getNoiLuuTruTaiLieuId();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			lichSuGiayToDinhKemCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			lichSuGiayToDinhKemCacheModel.ngayTao = Long.MIN_VALUE;
		}

		lichSuGiayToDinhKemCacheModel.tenTaiLieu = getTenTaiLieu();

		String tenTaiLieu = lichSuGiayToDinhKemCacheModel.tenTaiLieu;

		if ((tenTaiLieu != null) && (tenTaiLieu.length() == 0)) {
			lichSuGiayToDinhKemCacheModel.tenTaiLieu = null;
		}

		return lichSuGiayToDinhKemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", giayToDinhKemHoSoId=");
		sb.append(getGiayToDinhKemHoSoId());
		sb.append(", hanhDong=");
		sb.append(getHanhDong());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", noiLuuTruTaiLieuId=");
		sb.append(getNoiLuuTruTaiLieuId());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", tenTaiLieu=");
		sb.append(getTenTaiLieu());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.tlct.model.LichSuGiayToDinhKem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>giayToDinhKemHoSoId</column-name><column-value><![CDATA[");
		sb.append(getGiayToDinhKemHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hanhDong</column-name><column-value><![CDATA[");
		sb.append(getHanhDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiLuuTruTaiLieuId</column-name><column-value><![CDATA[");
		sb.append(getNoiLuuTruTaiLieuId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTaiLieu</column-name><column-value><![CDATA[");
		sb.append(getTenTaiLieu());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LichSuGiayToDinhKem.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			LichSuGiayToDinhKem.class
		};
	private long _id;
	private Long _giayToDinhKemHoSoId;
	private Long _originalGiayToDinhKemHoSoId;
	private boolean _setOriginalGiayToDinhKemHoSoId;
	private int _hanhDong;
	private String _nguoiTao;
	private long _noiLuuTruTaiLieuId;
	private long _originalNoiLuuTruTaiLieuId;
	private boolean _setOriginalNoiLuuTruTaiLieuId;
	private Date _ngayTao;
	private String _tenTaiLieu;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private LichSuGiayToDinhKem _escapedModelProxy;
}