/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.tlct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.tlct.model.TaiLieuChungThuc;
import org.oep.cmon.dao.tlct.model.TaiLieuChungThucModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TaiLieuChungThuc service. Represents a row in the &quot;CMON_NOILUUTRUTAILIEU&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.tlct.model.TaiLieuChungThucModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaiLieuChungThucImpl}.
 * </p>
 *
 * @author Liemnn
 * @see TaiLieuChungThucImpl
 * @see org.oep.cmon.dao.tlct.model.TaiLieuChungThuc
 * @see org.oep.cmon.dao.tlct.model.TaiLieuChungThucModel
 * @generated
 */
public class TaiLieuChungThucModelImpl extends BaseModelImpl<TaiLieuChungThuc>
	implements TaiLieuChungThucModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tai lieu chung thuc model instance should use the {@link org.oep.cmon.dao.tlct.model.TaiLieuChungThuc} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_NOILUUTRUTAILIEU";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TENTAILIEU", Types.VARCHAR },
			{ "GHICHU", Types.VARCHAR },
			{ "NOILUUTRUID", Types.BIGINT },
			{ "NGAYUPLOAD", Types.TIMESTAMP },
			{ "PHIENBAN", Types.INTEGER },
			{ "NGAYDUYET", Types.TIMESTAMP },
			{ "HIEULUCTUNGAY", Types.TIMESTAMP },
			{ "HIEULUCDENNGAY", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "DANHMUCGIAYTOID", Types.BIGINT },
			{ "TRANGTHAI", Types.INTEGER },
			{ "CHUSOHUUID", Types.BIGINT },
			{ "NGUOIUPLOADID", Types.BIGINT },
			{ "NGUOIDUYETID", Types.BIGINT },
			{ "HOSOTTHCCONGID", Types.BIGINT },
			{ "MAUNGDUNG", Types.VARCHAR },
			{ "LOAI", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_NOILUUTRUTAILIEU (ID LONG not null primary key,TENTAILIEU VARCHAR(75) null,GHICHU VARCHAR(75) null,NOILUUTRUID LONG,NGAYUPLOAD DATE null,PHIENBAN INTEGER,NGAYDUYET DATE null,HIEULUCTUNGAY DATE null,HIEULUCDENNGAY DATE null,NGAYSUA DATE null,NGUOISUA VARCHAR(75) null,DANHMUCGIAYTOID LONG null,TRANGTHAI INTEGER,CHUSOHUUID LONG null,NGUOIUPLOADID LONG null,NGUOIDUYETID LONG null,HOSOTTHCCONGID LONG null,MAUNGDUNG VARCHAR(75) null,LOAI INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_NOILUUTRUTAILIEU";
	public static final String ORDER_BY_JPQL = " ORDER BY taiLieuChungThuc.phienBan DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_NOILUUTRUTAILIEU.PHIENBAN DESC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.tlct.model.TaiLieuChungThuc"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.tlct.model.TaiLieuChungThuc"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.tlct.model.TaiLieuChungThuc"),
			true);
	public static long HOSOTTHCCID_COLUMN_BITMASK = 1L;
	public static long LOAI_COLUMN_BITMASK = 2L;
	public static long NOILUUTRUID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.tlct.model.TaiLieuChungThuc"));

	public TaiLieuChungThucModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TaiLieuChungThuc.class;
	}

	public String getModelClassName() {
		return TaiLieuChungThuc.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public long getNoiLuuTruId() {
		return _noiLuuTruId;
	}

	public void setNoiLuuTruId(long noiLuuTruId) {
		_columnBitmask |= NOILUUTRUID_COLUMN_BITMASK;

		if (!_setOriginalNoiLuuTruId) {
			_setOriginalNoiLuuTruId = true;

			_originalNoiLuuTruId = _noiLuuTruId;
		}

		_noiLuuTruId = noiLuuTruId;
	}

	public long getOriginalNoiLuuTruId() {
		return _originalNoiLuuTruId;
	}

	public Date getNgayUpload() {
		return _ngayUpload;
	}

	public void setNgayUpload(Date ngayUpload) {
		_ngayUpload = ngayUpload;
	}

	public int getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(int phienBan) {
		_columnBitmask = -1L;

		_phienBan = phienBan;
	}

	public Date getNgayDuyet() {
		return _ngayDuyet;
	}

	public void setNgayDuyet(Date ngayDuyet) {
		_ngayDuyet = ngayDuyet;
	}

	public Date getHieuLucTuNgay() {
		return _hieuLucTuNgay;
	}

	public void setHieuLucTuNgay(Date hieuLucTuNgay) {
		_hieuLucTuNgay = hieuLucTuNgay;
	}

	public Date getHieuLucDenNgay() {
		return _hieuLucDenNgay;
	}

	public void setHieuLucDenNgay(Date hieuLucDenNgay) {
		_hieuLucDenNgay = hieuLucDenNgay;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public Long getDanhMucGiayToId() {
		return _danhMucGiayToId;
	}

	public void setDanhMucGiayToId(Long danhMucGiayToId) {
		_danhMucGiayToId = danhMucGiayToId;
	}

	public int getTrangThai() {
		return _trangThai;
	}

	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	public Long getChuSohuuId() {
		return _chuSohuuId;
	}

	public void setChuSohuuId(Long chuSohuuId) {
		_chuSohuuId = chuSohuuId;
	}

	public Long getNguoiUploadId() {
		return _nguoiUploadId;
	}

	public void setNguoiUploadId(Long nguoiUploadId) {
		_nguoiUploadId = nguoiUploadId;
	}

	public Long getNguoiduyetId() {
		return _nguoiduyetId;
	}

	public void setNguoiduyetId(Long nguoiduyetId) {
		_nguoiduyetId = nguoiduyetId;
	}

	public Long getHoSoTTHCCId() {
		return _hoSoTTHCCId;
	}

	public void setHoSoTTHCCId(Long hoSoTTHCCId) {
		_columnBitmask |= HOSOTTHCCID_COLUMN_BITMASK;

		if (!_setOriginalHoSoTTHCCId) {
			_setOriginalHoSoTTHCCId = true;

			_originalHoSoTTHCCId = _hoSoTTHCCId;
		}

		_hoSoTTHCCId = hoSoTTHCCId;
	}

	public Long getOriginalHoSoTTHCCId() {
		return _originalHoSoTTHCCId;
	}

	public String getMaUngDung() {
		if (_maUngDung == null) {
			return StringPool.BLANK;
		}
		else {
			return _maUngDung;
		}
	}

	public void setMaUngDung(String maUngDung) {
		_maUngDung = maUngDung;
	}

	public int getLoai() {
		return _loai;
	}

	public void setLoai(int loai) {
		_columnBitmask |= LOAI_COLUMN_BITMASK;

		if (!_setOriginalLoai) {
			_setOriginalLoai = true;

			_originalLoai = _loai;
		}

		_loai = loai;
	}

	public int getOriginalLoai() {
		return _originalLoai;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TaiLieuChungThuc toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TaiLieuChungThuc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TaiLieuChungThuc.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TaiLieuChungThucImpl taiLieuChungThucImpl = new TaiLieuChungThucImpl();

		taiLieuChungThucImpl.setId(getId());
		taiLieuChungThucImpl.setTen(getTen());
		taiLieuChungThucImpl.setGhiChu(getGhiChu());
		taiLieuChungThucImpl.setNoiLuuTruId(getNoiLuuTruId());
		taiLieuChungThucImpl.setNgayUpload(getNgayUpload());
		taiLieuChungThucImpl.setPhienBan(getPhienBan());
		taiLieuChungThucImpl.setNgayDuyet(getNgayDuyet());
		taiLieuChungThucImpl.setHieuLucTuNgay(getHieuLucTuNgay());
		taiLieuChungThucImpl.setHieuLucDenNgay(getHieuLucDenNgay());
		taiLieuChungThucImpl.setNgaySua(getNgaySua());
		taiLieuChungThucImpl.setNguoiSua(getNguoiSua());
		taiLieuChungThucImpl.setDanhMucGiayToId(getDanhMucGiayToId());
		taiLieuChungThucImpl.setTrangThai(getTrangThai());
		taiLieuChungThucImpl.setChuSohuuId(getChuSohuuId());
		taiLieuChungThucImpl.setNguoiUploadId(getNguoiUploadId());
		taiLieuChungThucImpl.setNguoiduyetId(getNguoiduyetId());
		taiLieuChungThucImpl.setHoSoTTHCCId(getHoSoTTHCCId());
		taiLieuChungThucImpl.setMaUngDung(getMaUngDung());
		taiLieuChungThucImpl.setLoai(getLoai());

		taiLieuChungThucImpl.resetOriginalValues();

		return taiLieuChungThucImpl;
	}

	public int compareTo(TaiLieuChungThuc taiLieuChungThuc) {
		int value = 0;

		if (getPhienBan() < taiLieuChungThuc.getPhienBan()) {
			value = -1;
		}
		else if (getPhienBan() > taiLieuChungThuc.getPhienBan()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TaiLieuChungThuc taiLieuChungThuc = null;

		try {
			taiLieuChungThuc = (TaiLieuChungThuc)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = taiLieuChungThuc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TaiLieuChungThucModelImpl taiLieuChungThucModelImpl = this;

		taiLieuChungThucModelImpl._originalNoiLuuTruId = taiLieuChungThucModelImpl._noiLuuTruId;

		taiLieuChungThucModelImpl._setOriginalNoiLuuTruId = false;

		taiLieuChungThucModelImpl._originalHoSoTTHCCId = taiLieuChungThucModelImpl._hoSoTTHCCId;

		taiLieuChungThucModelImpl._setOriginalHoSoTTHCCId = false;

		taiLieuChungThucModelImpl._originalLoai = taiLieuChungThucModelImpl._loai;

		taiLieuChungThucModelImpl._setOriginalLoai = false;

		taiLieuChungThucModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaiLieuChungThuc> toCacheModel() {
		TaiLieuChungThucCacheModel taiLieuChungThucCacheModel = new TaiLieuChungThucCacheModel();

		taiLieuChungThucCacheModel.id = getId();

		taiLieuChungThucCacheModel.ten = getTen();

		String ten = taiLieuChungThucCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			taiLieuChungThucCacheModel.ten = null;
		}

		taiLieuChungThucCacheModel.ghiChu = getGhiChu();

		String ghiChu = taiLieuChungThucCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			taiLieuChungThucCacheModel.ghiChu = null;
		}

		taiLieuChungThucCacheModel.noiLuuTruId = getNoiLuuTruId();

		Date ngayUpload = getNgayUpload();

		if (ngayUpload != null) {
			taiLieuChungThucCacheModel.ngayUpload = ngayUpload.getTime();
		}
		else {
			taiLieuChungThucCacheModel.ngayUpload = Long.MIN_VALUE;
		}

		taiLieuChungThucCacheModel.phienBan = getPhienBan();

		Date ngayDuyet = getNgayDuyet();

		if (ngayDuyet != null) {
			taiLieuChungThucCacheModel.ngayDuyet = ngayDuyet.getTime();
		}
		else {
			taiLieuChungThucCacheModel.ngayDuyet = Long.MIN_VALUE;
		}

		Date hieuLucTuNgay = getHieuLucTuNgay();

		if (hieuLucTuNgay != null) {
			taiLieuChungThucCacheModel.hieuLucTuNgay = hieuLucTuNgay.getTime();
		}
		else {
			taiLieuChungThucCacheModel.hieuLucTuNgay = Long.MIN_VALUE;
		}

		Date hieuLucDenNgay = getHieuLucDenNgay();

		if (hieuLucDenNgay != null) {
			taiLieuChungThucCacheModel.hieuLucDenNgay = hieuLucDenNgay.getTime();
		}
		else {
			taiLieuChungThucCacheModel.hieuLucDenNgay = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			taiLieuChungThucCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			taiLieuChungThucCacheModel.ngaySua = Long.MIN_VALUE;
		}

		taiLieuChungThucCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = taiLieuChungThucCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			taiLieuChungThucCacheModel.nguoiSua = null;
		}

		taiLieuChungThucCacheModel.danhMucGiayToId = getDanhMucGiayToId();

		taiLieuChungThucCacheModel.trangThai = getTrangThai();

		taiLieuChungThucCacheModel.chuSohuuId = getChuSohuuId();

		taiLieuChungThucCacheModel.nguoiUploadId = getNguoiUploadId();

		taiLieuChungThucCacheModel.nguoiduyetId = getNguoiduyetId();

		taiLieuChungThucCacheModel.hoSoTTHCCId = getHoSoTTHCCId();

		taiLieuChungThucCacheModel.maUngDung = getMaUngDung();

		String maUngDung = taiLieuChungThucCacheModel.maUngDung;

		if ((maUngDung != null) && (maUngDung.length() == 0)) {
			taiLieuChungThucCacheModel.maUngDung = null;
		}

		taiLieuChungThucCacheModel.loai = getLoai();

		return taiLieuChungThucCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", noiLuuTruId=");
		sb.append(getNoiLuuTruId());
		sb.append(", ngayUpload=");
		sb.append(getNgayUpload());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", ngayDuyet=");
		sb.append(getNgayDuyet());
		sb.append(", hieuLucTuNgay=");
		sb.append(getHieuLucTuNgay());
		sb.append(", hieuLucDenNgay=");
		sb.append(getHieuLucDenNgay());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", danhMucGiayToId=");
		sb.append(getDanhMucGiayToId());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", chuSohuuId=");
		sb.append(getChuSohuuId());
		sb.append(", nguoiUploadId=");
		sb.append(getNguoiUploadId());
		sb.append(", nguoiduyetId=");
		sb.append(getNguoiduyetId());
		sb.append(", hoSoTTHCCId=");
		sb.append(getHoSoTTHCCId());
		sb.append(", maUngDung=");
		sb.append(getMaUngDung());
		sb.append(", loai=");
		sb.append(getLoai());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.tlct.model.TaiLieuChungThuc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiLuuTruId</column-name><column-value><![CDATA[");
		sb.append(getNoiLuuTruId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayUpload</column-name><column-value><![CDATA[");
		sb.append(getNgayUpload());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDuyet</column-name><column-value><![CDATA[");
		sb.append(getNgayDuyet());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hieuLucTuNgay</column-name><column-value><![CDATA[");
		sb.append(getHieuLucTuNgay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hieuLucDenNgay</column-name><column-value><![CDATA[");
		sb.append(getHieuLucDenNgay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>danhMucGiayToId</column-name><column-value><![CDATA[");
		sb.append(getDanhMucGiayToId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chuSohuuId</column-name><column-value><![CDATA[");
		sb.append(getChuSohuuId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiUploadId</column-name><column-value><![CDATA[");
		sb.append(getNguoiUploadId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiduyetId</column-name><column-value><![CDATA[");
		sb.append(getNguoiduyetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoSoTTHCCId</column-name><column-value><![CDATA[");
		sb.append(getHoSoTTHCCId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maUngDung</column-name><column-value><![CDATA[");
		sb.append(getMaUngDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loai</column-name><column-value><![CDATA[");
		sb.append(getLoai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TaiLieuChungThuc.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TaiLieuChungThuc.class
		};
	private long _id;
	private String _ten;
	private String _ghiChu;
	private long _noiLuuTruId;
	private long _originalNoiLuuTruId;
	private boolean _setOriginalNoiLuuTruId;
	private Date _ngayUpload;
	private int _phienBan;
	private Date _ngayDuyet;
	private Date _hieuLucTuNgay;
	private Date _hieuLucDenNgay;
	private Date _ngaySua;
	private String _nguoiSua;
	private Long _danhMucGiayToId;
	private int _trangThai;
	private Long _chuSohuuId;
	private Long _nguoiUploadId;
	private Long _nguoiduyetId;
	private Long _hoSoTTHCCId;
	private Long _originalHoSoTTHCCId;
	private boolean _setOriginalHoSoTTHCCId;
	private String _maUngDung;
	private int _loai;
	private int _originalLoai;
	private boolean _setOriginalLoai;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TaiLieuChungThuc _escapedModelProxy;
}