
package org.oep.sharedservice.cmon.provider.form.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Sat Jul 05 10:22:09 ICT 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "getDSDoiTuongSuDung", namespace = "http://form.provider.cmon.sharedservice.dtt.vn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDSDoiTuongSuDung", namespace = "http://form.provider.cmon.sharedservice.dtt.vn/")

public class GetDSDoiTuongSuDung {


}

