/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DanhMucGiayTo2DoiTuongSuDung service. Represents a row in the &quot;CMON_DMGIAYTO2DOITUONGSUDUNG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.dvc.model.impl.DanhMucGiayTo2DoiTuongSuDungModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.dvc.model.impl.DanhMucGiayTo2DoiTuongSuDungImpl}.
 * </p>
 *
 * @author liemnn
 * @see DanhMucGiayTo2DoiTuongSuDung
 * @see org.oep.cmon.dao.dvc.model.impl.DanhMucGiayTo2DoiTuongSuDungImpl
 * @see org.oep.cmon.dao.dvc.model.impl.DanhMucGiayTo2DoiTuongSuDungModelImpl
 * @generated
 */
public interface DanhMucGiayTo2DoiTuongSuDungModel extends BaseModel<DanhMucGiayTo2DoiTuongSuDung> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danh muc giay to2 doi tuong su dung model instance should use the {@link DanhMucGiayTo2DoiTuongSuDung} interface instead.
	 */

	/**
	 * Returns the primary key of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the primary key of this danh muc giay to2 doi tuong su dung
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param primaryKey the primary key of this danh muc giay to2 doi tuong su dung
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the ID of this danh muc giay to2 doi tuong su dung
	 */
	public long getId();

	/**
	 * Sets the ID of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param id the ID of this danh muc giay to2 doi tuong su dung
	 */
	public void setId(long id);

	/**
	 * Returns the ngay tao of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the ngay tao of this danh muc giay to2 doi tuong su dung
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param ngayTao the ngay tao of this danh muc giay to2 doi tuong su dung
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the ngay sua of this danh muc giay to2 doi tuong su dung
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param ngaySua the ngay sua of this danh muc giay to2 doi tuong su dung
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the da xoa of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the da xoa of this danh muc giay to2 doi tuong su dung
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param daXoa the da xoa of this danh muc giay to2 doi tuong su dung
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the nguoi tao of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the nguoi tao of this danh muc giay to2 doi tuong su dung
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param nguoiTao the nguoi tao of this danh muc giay to2 doi tuong su dung
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the nguoi sua of this danh muc giay to2 doi tuong su dung
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param nguoiSua the nguoi sua of this danh muc giay to2 doi tuong su dung
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the loai doi tuong ID of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the loai doi tuong ID of this danh muc giay to2 doi tuong su dung
	 */
	public long getLoaiDoiTuongId();

	/**
	 * Sets the loai doi tuong ID of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param loaiDoiTuongId the loai doi tuong ID of this danh muc giay to2 doi tuong su dung
	 */
	public void setLoaiDoiTuongId(long loaiDoiTuongId);

	/**
	 * Returns the loai giay to ID of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the loai giay to ID of this danh muc giay to2 doi tuong su dung
	 */
	public long getLoaiGiayToId();

	/**
	 * Sets the loai giay to ID of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param loaiGiayToId the loai giay to ID of this danh muc giay to2 doi tuong su dung
	 */
	public void setLoaiGiayToId(long loaiGiayToId);

	/**
	 * Returns the trang thai of this danh muc giay to2 doi tuong su dung.
	 *
	 * @return the trang thai of this danh muc giay to2 doi tuong su dung
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this danh muc giay to2 doi tuong su dung.
	 *
	 * @param trangThai the trang thai of this danh muc giay to2 doi tuong su dung
	 */
	public void setTrangThai(int trangThai);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		DanhMucGiayTo2DoiTuongSuDung danhMucGiayTo2DoiTuongSuDung);

	public int hashCode();

	public CacheModel<DanhMucGiayTo2DoiTuongSuDung> toCacheModel();

	public DanhMucGiayTo2DoiTuongSuDung toEscapedModel();

	public String toString();

	public String toXmlString();
}