/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ThuTucHanhChinh service. Represents a row in the &quot;CMON_THUTUCHANHCHINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.dvc.model.impl.ThuTucHanhChinhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.dvc.model.impl.ThuTucHanhChinhImpl}.
 * </p>
 *
 * @author liemnn
 * @see ThuTucHanhChinh
 * @see org.oep.cmon.dao.dvc.model.impl.ThuTucHanhChinhImpl
 * @see org.oep.cmon.dao.dvc.model.impl.ThuTucHanhChinhModelImpl
 * @generated
 */
public interface ThuTucHanhChinhModel extends BaseModel<ThuTucHanhChinh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thu tuc hanh chinh model instance should use the {@link ThuTucHanhChinh} interface instead.
	 */

	/**
	 * Returns the primary key of this thu tuc hanh chinh.
	 *
	 * @return the primary key of this thu tuc hanh chinh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this thu tuc hanh chinh.
	 *
	 * @param primaryKey the primary key of this thu tuc hanh chinh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this thu tuc hanh chinh.
	 *
	 * @return the ID of this thu tuc hanh chinh
	 */
	public long getId();

	/**
	 * Sets the ID of this thu tuc hanh chinh.
	 *
	 * @param id the ID of this thu tuc hanh chinh
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this thu tuc hanh chinh.
	 *
	 * @return the ma of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this thu tuc hanh chinh.
	 *
	 * @param ma the ma of this thu tuc hanh chinh
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this thu tuc hanh chinh.
	 *
	 * @return the ten of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this thu tuc hanh chinh.
	 *
	 * @param ten the ten of this thu tuc hanh chinh
	 */
	public void setTen(String ten);

	/**
	 * Returns the so ngay xu ly of this thu tuc hanh chinh.
	 *
	 * @return the so ngay xu ly of this thu tuc hanh chinh
	 */
	public long getSoNgayXuLy();

	/**
	 * Sets the so ngay xu ly of this thu tuc hanh chinh.
	 *
	 * @param soNgayXuLy the so ngay xu ly of this thu tuc hanh chinh
	 */
	public void setSoNgayXuLy(long soNgayXuLy);

	/**
	 * Returns the ngay tao of this thu tuc hanh chinh.
	 *
	 * @return the ngay tao of this thu tuc hanh chinh
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this thu tuc hanh chinh.
	 *
	 * @param ngayTao the ngay tao of this thu tuc hanh chinh
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this thu tuc hanh chinh.
	 *
	 * @return the ngay sua of this thu tuc hanh chinh
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this thu tuc hanh chinh.
	 *
	 * @param ngaySua the ngay sua of this thu tuc hanh chinh
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the da xoa of this thu tuc hanh chinh.
	 *
	 * @return the da xoa of this thu tuc hanh chinh
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this thu tuc hanh chinh.
	 *
	 * @param daXoa the da xoa of this thu tuc hanh chinh
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the nguoi tao of this thu tuc hanh chinh.
	 *
	 * @return the nguoi tao of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this thu tuc hanh chinh.
	 *
	 * @param nguoiTao the nguoi tao of this thu tuc hanh chinh
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this thu tuc hanh chinh.
	 *
	 * @return the nguoi sua of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this thu tuc hanh chinh.
	 *
	 * @param nguoiSua the nguoi sua of this thu tuc hanh chinh
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the nhom thu tuc hanh chinh ID of this thu tuc hanh chinh.
	 *
	 * @return the nhom thu tuc hanh chinh ID of this thu tuc hanh chinh
	 */
	public long getNhomThuTucHanhChinhId();

	/**
	 * Sets the nhom thu tuc hanh chinh ID of this thu tuc hanh chinh.
	 *
	 * @param nhomThuTucHanhChinhId the nhom thu tuc hanh chinh ID of this thu tuc hanh chinh
	 */
	public void setNhomThuTucHanhChinhId(long nhomThuTucHanhChinhId);

	/**
	 * Returns the trang thai of this thu tuc hanh chinh.
	 *
	 * @return the trang thai of this thu tuc hanh chinh
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this thu tuc hanh chinh.
	 *
	 * @param trangThai the trang thai of this thu tuc hanh chinh
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the phien ban of this thu tuc hanh chinh.
	 *
	 * @return the phien ban of this thu tuc hanh chinh
	 */
	public long getPhienBan();

	/**
	 * Sets the phien ban of this thu tuc hanh chinh.
	 *
	 * @param phienBan the phien ban of this thu tuc hanh chinh
	 */
	public void setPhienBan(long phienBan);

	/**
	 * Returns the can tich hop of this thu tuc hanh chinh.
	 *
	 * @return the can tich hop of this thu tuc hanh chinh
	 */
	public int getCanTichHop();

	/**
	 * Sets the can tich hop of this thu tuc hanh chinh.
	 *
	 * @param canTichHop the can tich hop of this thu tuc hanh chinh
	 */
	public void setCanTichHop(int canTichHop);

	/**
	 * Returns the trinh tu thuc hien of this thu tuc hanh chinh.
	 *
	 * @return the trinh tu thuc hien of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getTrinhTuThucHien();

	/**
	 * Sets the trinh tu thuc hien of this thu tuc hanh chinh.
	 *
	 * @param trinhTuThucHien the trinh tu thuc hien of this thu tuc hanh chinh
	 */
	public void setTrinhTuThucHien(String trinhTuThucHien);

	/**
	 * Returns the cach thuc hien of this thu tuc hanh chinh.
	 *
	 * @return the cach thuc hien of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getCachThucHien();

	/**
	 * Sets the cach thuc hien of this thu tuc hanh chinh.
	 *
	 * @param cachThucHien the cach thuc hien of this thu tuc hanh chinh
	 */
	public void setCachThucHien(String cachThucHien);

	/**
	 * Returns the thanh phan ho so of this thu tuc hanh chinh.
	 *
	 * @return the thanh phan ho so of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getThanhPhanHoSo();

	/**
	 * Sets the thanh phan ho so of this thu tuc hanh chinh.
	 *
	 * @param thanhPhanHoSo the thanh phan ho so of this thu tuc hanh chinh
	 */
	public void setThanhPhanHoSo(String thanhPhanHoSo);

	/**
	 * Returns the le phi of this thu tuc hanh chinh.
	 *
	 * @return the le phi of this thu tuc hanh chinh
	 */
	public long getLePhi();

	/**
	 * Sets the le phi of this thu tuc hanh chinh.
	 *
	 * @param lePhi the le phi of this thu tuc hanh chinh
	 */
	public void setLePhi(long lePhi);

	/**
	 * Returns the don vi le phi of this thu tuc hanh chinh.
	 *
	 * @return the don vi le phi of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getDonViLePhi();

	/**
	 * Sets the don vi le phi of this thu tuc hanh chinh.
	 *
	 * @param donViLePhi the don vi le phi of this thu tuc hanh chinh
	 */
	public void setDonViLePhi(String donViLePhi);

	/**
	 * Returns the phi of this thu tuc hanh chinh.
	 *
	 * @return the phi of this thu tuc hanh chinh
	 */
	public long getPhi();

	/**
	 * Sets the phi of this thu tuc hanh chinh.
	 *
	 * @param phi the phi of this thu tuc hanh chinh
	 */
	public void setPhi(long phi);

	/**
	 * Returns the don vi phi of this thu tuc hanh chinh.
	 *
	 * @return the don vi phi of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getDonViPhi();

	/**
	 * Sets the don vi phi of this thu tuc hanh chinh.
	 *
	 * @param donViPhi the don vi phi of this thu tuc hanh chinh
	 */
	public void setDonViPhi(String donViPhi);

	/**
	 * Returns the ten mau don to khai of this thu tuc hanh chinh.
	 *
	 * @return the ten mau don to khai of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getTenMauDonToKhai();

	/**
	 * Sets the ten mau don to khai of this thu tuc hanh chinh.
	 *
	 * @param tenMauDonToKhai the ten mau don to khai of this thu tuc hanh chinh
	 */
	public void setTenMauDonToKhai(String tenMauDonToKhai);

	/**
	 * Returns the yeu cau dieu kien thuc hien of this thu tuc hanh chinh.
	 *
	 * @return the yeu cau dieu kien thuc hien of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getYeuCauDieuKienThucHien();

	/**
	 * Sets the yeu cau dieu kien thuc hien of this thu tuc hanh chinh.
	 *
	 * @param yeuCauDieuKienThucHien the yeu cau dieu kien thuc hien of this thu tuc hanh chinh
	 */
	public void setYeuCauDieuKienThucHien(String yeuCauDieuKienThucHien);

	/**
	 * Returns the can cu phap ly of this thu tuc hanh chinh.
	 *
	 * @return the can cu phap ly of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getCanCuPhapLy();

	/**
	 * Sets the can cu phap ly of this thu tuc hanh chinh.
	 *
	 * @param canCuPhapLy the can cu phap ly of this thu tuc hanh chinh
	 */
	public void setCanCuPhapLy(String canCuPhapLy);

	/**
	 * Returns the cap co quan quan ly ID of this thu tuc hanh chinh.
	 *
	 * @return the cap co quan quan ly ID of this thu tuc hanh chinh
	 */
	public Long getCapCoQuanQuanLyId();

	/**
	 * Sets the cap co quan quan ly ID of this thu tuc hanh chinh.
	 *
	 * @param capCoQuanQuanLyId the cap co quan quan ly ID of this thu tuc hanh chinh
	 */
	public void setCapCoQuanQuanLyId(Long capCoQuanQuanLyId);

	/**
	 * Returns the linh vuc thuc hien of this thu tuc hanh chinh.
	 *
	 * @return the linh vuc thuc hien of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getLinhVucThucHien();

	/**
	 * Sets the linh vuc thuc hien of this thu tuc hanh chinh.
	 *
	 * @param linhVucThucHien the linh vuc thuc hien of this thu tuc hanh chinh
	 */
	public void setLinhVucThucHien(String linhVucThucHien);

	/**
	 * Returns the ma d n g of this thu tuc hanh chinh.
	 *
	 * @return the ma d n g of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getMaDNG();

	/**
	 * Sets the ma d n g of this thu tuc hanh chinh.
	 *
	 * @param maDNG the ma d n g of this thu tuc hanh chinh
	 */
	public void setMaDNG(String maDNG);

	/**
	 * Returns the uengine process name of this thu tuc hanh chinh.
	 *
	 * @return the uengine process name of this thu tuc hanh chinh
	 */
	@AutoEscape
	public String getUengineProcessName();

	/**
	 * Sets the uengine process name of this thu tuc hanh chinh.
	 *
	 * @param uengineProcessName the uengine process name of this thu tuc hanh chinh
	 */
	public void setUengineProcessName(String uengineProcessName);

	/**
	 * Returns the thu tuc lien thong ID of this thu tuc hanh chinh.
	 *
	 * @return the thu tuc lien thong ID of this thu tuc hanh chinh
	 */
	public Long getThuTucLienThongId();

	/**
	 * Sets the thu tuc lien thong ID of this thu tuc hanh chinh.
	 *
	 * @param thuTucLienThongId the thu tuc lien thong ID of this thu tuc hanh chinh
	 */
	public void setThuTucLienThongId(Long thuTucLienThongId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ThuTucHanhChinh thuTucHanhChinh);

	public int hashCode();

	public CacheModel<ThuTucHanhChinh> toCacheModel();

	public ThuTucHanhChinh toEscapedModel();

	public String toString();

	public String toXmlString();
}