/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ThuTuc2GiayTo service. Represents a row in the &quot;CMON_THUTUC2GIAYTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.dvc.model.impl.ThuTuc2GiayToModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.dvc.model.impl.ThuTuc2GiayToImpl}.
 * </p>
 *
 * @author liemnn
 * @see ThuTuc2GiayTo
 * @see org.oep.cmon.dao.dvc.model.impl.ThuTuc2GiayToImpl
 * @see org.oep.cmon.dao.dvc.model.impl.ThuTuc2GiayToModelImpl
 * @generated
 */
public interface ThuTuc2GiayToModel extends BaseModel<ThuTuc2GiayTo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thu tuc2 giay to model instance should use the {@link ThuTuc2GiayTo} interface instead.
	 */

	/**
	 * Returns the primary key of this thu tuc2 giay to.
	 *
	 * @return the primary key of this thu tuc2 giay to
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this thu tuc2 giay to.
	 *
	 * @param primaryKey the primary key of this thu tuc2 giay to
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this thu tuc2 giay to.
	 *
	 * @return the ID of this thu tuc2 giay to
	 */
	public long getId();

	/**
	 * Sets the ID of this thu tuc2 giay to.
	 *
	 * @param id the ID of this thu tuc2 giay to
	 */
	public void setId(long id);

	/**
	 * Returns the ghi chu of this thu tuc2 giay to.
	 *
	 * @return the ghi chu of this thu tuc2 giay to
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this thu tuc2 giay to.
	 *
	 * @param ghiChu the ghi chu of this thu tuc2 giay to
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the bat buoc of this thu tuc2 giay to.
	 *
	 * @return the bat buoc of this thu tuc2 giay to
	 */
	public int getBatBuoc();

	/**
	 * Sets the bat buoc of this thu tuc2 giay to.
	 *
	 * @param batBuoc the bat buoc of this thu tuc2 giay to
	 */
	public void setBatBuoc(int batBuoc);

	/**
	 * Returns the thu tu hien thi of this thu tuc2 giay to.
	 *
	 * @return the thu tu hien thi of this thu tuc2 giay to
	 */
	public long getThuTuHienThi();

	/**
	 * Sets the thu tu hien thi of this thu tuc2 giay to.
	 *
	 * @param thuTuHienThi the thu tu hien thi of this thu tuc2 giay to
	 */
	public void setThuTuHienThi(long thuTuHienThi);

	/**
	 * Returns the ngay tao of this thu tuc2 giay to.
	 *
	 * @return the ngay tao of this thu tuc2 giay to
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this thu tuc2 giay to.
	 *
	 * @param ngayTao the ngay tao of this thu tuc2 giay to
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this thu tuc2 giay to.
	 *
	 * @return the ngay sua of this thu tuc2 giay to
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this thu tuc2 giay to.
	 *
	 * @param ngaySua the ngay sua of this thu tuc2 giay to
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the da xoa of this thu tuc2 giay to.
	 *
	 * @return the da xoa of this thu tuc2 giay to
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this thu tuc2 giay to.
	 *
	 * @param daXoa the da xoa of this thu tuc2 giay to
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the nguoi tao of this thu tuc2 giay to.
	 *
	 * @return the nguoi tao of this thu tuc2 giay to
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this thu tuc2 giay to.
	 *
	 * @param nguoiTao the nguoi tao of this thu tuc2 giay to
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this thu tuc2 giay to.
	 *
	 * @return the nguoi sua of this thu tuc2 giay to
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this thu tuc2 giay to.
	 *
	 * @param nguoiSua the nguoi sua of this thu tuc2 giay to
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the thu tuc hanh chinh ID of this thu tuc2 giay to.
	 *
	 * @return the thu tuc hanh chinh ID of this thu tuc2 giay to
	 */
	public long getThuTucHanhChinhId();

	/**
	 * Sets the thu tuc hanh chinh ID of this thu tuc2 giay to.
	 *
	 * @param thuTucHanhChinhId the thu tuc hanh chinh ID of this thu tuc2 giay to
	 */
	public void setThuTucHanhChinhId(long thuTucHanhChinhId);

	/**
	 * Returns the danh muc giay to ID of this thu tuc2 giay to.
	 *
	 * @return the danh muc giay to ID of this thu tuc2 giay to
	 */
	public long getDanhMucGiayToId();

	/**
	 * Sets the danh muc giay to ID of this thu tuc2 giay to.
	 *
	 * @param danhMucGiayToId the danh muc giay to ID of this thu tuc2 giay to
	 */
	public void setDanhMucGiayToId(long danhMucGiayToId);

	/**
	 * Returns the trang thai of this thu tuc2 giay to.
	 *
	 * @return the trang thai of this thu tuc2 giay to
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this thu tuc2 giay to.
	 *
	 * @param trangThai the trang thai of this thu tuc2 giay to
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the giaidoan of this thu tuc2 giay to.
	 *
	 * @return the giaidoan of this thu tuc2 giay to
	 */
	public int getGiaidoan();

	/**
	 * Sets the giaidoan of this thu tuc2 giay to.
	 *
	 * @param giaidoan the giaidoan of this thu tuc2 giay to
	 */
	public void setGiaidoan(int giaidoan);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ThuTuc2GiayTo thuTuc2GiayTo);

	public int hashCode();

	public CacheModel<ThuTuc2GiayTo> toCacheModel();

	public ThuTuc2GiayTo toEscapedModel();

	public String toString();

	public String toXmlString();
}