/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VanBanHuongDan service. Represents a row in the &quot;CMON_VANBANHUONGDAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.dvc.model.impl.VanBanHuongDanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.dvc.model.impl.VanBanHuongDanImpl}.
 * </p>
 *
 * @author liemnn
 * @see VanBanHuongDan
 * @see org.oep.cmon.dao.dvc.model.impl.VanBanHuongDanImpl
 * @see org.oep.cmon.dao.dvc.model.impl.VanBanHuongDanModelImpl
 * @generated
 */
public interface VanBanHuongDanModel extends BaseModel<VanBanHuongDan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a van ban huong dan model instance should use the {@link VanBanHuongDan} interface instead.
	 */

	/**
	 * Returns the primary key of this van ban huong dan.
	 *
	 * @return the primary key of this van ban huong dan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this van ban huong dan.
	 *
	 * @param primaryKey the primary key of this van ban huong dan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this van ban huong dan.
	 *
	 * @return the ID of this van ban huong dan
	 */
	public long getId();

	/**
	 * Sets the ID of this van ban huong dan.
	 *
	 * @param id the ID of this van ban huong dan
	 */
	public void setId(long id);

	/**
	 * Returns the noi luu tru ID of this van ban huong dan.
	 *
	 * @return the noi luu tru ID of this van ban huong dan
	 */
	public long getNoiLuuTruId();

	/**
	 * Sets the noi luu tru ID of this van ban huong dan.
	 *
	 * @param noiLuuTruId the noi luu tru ID of this van ban huong dan
	 */
	public void setNoiLuuTruId(long noiLuuTruId);

	/**
	 * Returns the ten tai lieu of this van ban huong dan.
	 *
	 * @return the ten tai lieu of this van ban huong dan
	 */
	@AutoEscape
	public String getTenTaiLieu();

	/**
	 * Sets the ten tai lieu of this van ban huong dan.
	 *
	 * @param tenTaiLieu the ten tai lieu of this van ban huong dan
	 */
	public void setTenTaiLieu(String tenTaiLieu);

	/**
	 * Returns the mo ta of this van ban huong dan.
	 *
	 * @return the mo ta of this van ban huong dan
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this van ban huong dan.
	 *
	 * @param moTa the mo ta of this van ban huong dan
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the loai tai lieu of this van ban huong dan.
	 *
	 * @return the loai tai lieu of this van ban huong dan
	 */
	public long getLoaiTaiLieu();

	/**
	 * Sets the loai tai lieu of this van ban huong dan.
	 *
	 * @param loaiTaiLieu the loai tai lieu of this van ban huong dan
	 */
	public void setLoaiTaiLieu(long loaiTaiLieu);

	/**
	 * Returns the ngay tao of this van ban huong dan.
	 *
	 * @return the ngay tao of this van ban huong dan
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this van ban huong dan.
	 *
	 * @param ngayTao the ngay tao of this van ban huong dan
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this van ban huong dan.
	 *
	 * @return the ngay sua of this van ban huong dan
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this van ban huong dan.
	 *
	 * @param ngaySua the ngay sua of this van ban huong dan
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the da xoa of this van ban huong dan.
	 *
	 * @return the da xoa of this van ban huong dan
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this van ban huong dan.
	 *
	 * @param daXoa the da xoa of this van ban huong dan
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the nguoi tao of this van ban huong dan.
	 *
	 * @return the nguoi tao of this van ban huong dan
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this van ban huong dan.
	 *
	 * @param nguoiTao the nguoi tao of this van ban huong dan
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this van ban huong dan.
	 *
	 * @return the nguoi sua of this van ban huong dan
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this van ban huong dan.
	 *
	 * @param nguoiSua the nguoi sua of this van ban huong dan
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the thu tuc hanh chinh ID of this van ban huong dan.
	 *
	 * @return the thu tuc hanh chinh ID of this van ban huong dan
	 */
	public long getThuTucHanhChinhId();

	/**
	 * Sets the thu tuc hanh chinh ID of this van ban huong dan.
	 *
	 * @param thuTucHanhChinhId the thu tuc hanh chinh ID of this van ban huong dan
	 */
	public void setThuTucHanhChinhId(long thuTucHanhChinhId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VanBanHuongDan vanBanHuongDan);

	public int hashCode();

	public CacheModel<VanBanHuongDan> toCacheModel();

	public VanBanHuongDan toEscapedModel();

	public String toString();

	public String toXmlString();
}