/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.qlhc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChucVu2VaiTro service. Represents a row in the &quot;CMON_CHUCVU2VAITRO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.qlhc.model.impl.ChucVu2VaiTroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.qlhc.model.impl.ChucVu2VaiTroImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see ChucVu2VaiTro
 * @see org.oep.cmon.dao.qlhc.model.impl.ChucVu2VaiTroImpl
 * @see org.oep.cmon.dao.qlhc.model.impl.ChucVu2VaiTroModelImpl
 * @generated
 */
public interface ChucVu2VaiTroModel extends BaseModel<ChucVu2VaiTro> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chuc vu2 vai tro model instance should use the {@link ChucVu2VaiTro} interface instead.
	 */

	/**
	 * Returns the primary key of this chuc vu2 vai tro.
	 *
	 * @return the primary key of this chuc vu2 vai tro
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chuc vu2 vai tro.
	 *
	 * @param primaryKey the primary key of this chuc vu2 vai tro
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chuc vu2 vai tro.
	 *
	 * @return the ID of this chuc vu2 vai tro
	 */
	public long getId();

	/**
	 * Sets the ID of this chuc vu2 vai tro.
	 *
	 * @param id the ID of this chuc vu2 vai tro
	 */
	public void setId(long id);

	/**
	 * Returns the ngay tao of this chuc vu2 vai tro.
	 *
	 * @return the ngay tao of this chuc vu2 vai tro
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this chuc vu2 vai tro.
	 *
	 * @param ngayTao the ngay tao of this chuc vu2 vai tro
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this chuc vu2 vai tro.
	 *
	 * @return the ngay sua of this chuc vu2 vai tro
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this chuc vu2 vai tro.
	 *
	 * @param ngaySua the ngay sua of this chuc vu2 vai tro
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the da xoa of this chuc vu2 vai tro.
	 *
	 * @return the da xoa of this chuc vu2 vai tro
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this chuc vu2 vai tro.
	 *
	 * @param daXoa the da xoa of this chuc vu2 vai tro
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the nguoi tao of this chuc vu2 vai tro.
	 *
	 * @return the nguoi tao of this chuc vu2 vai tro
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this chuc vu2 vai tro.
	 *
	 * @param nguoiTao the nguoi tao of this chuc vu2 vai tro
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this chuc vu2 vai tro.
	 *
	 * @return the nguoi sua of this chuc vu2 vai tro
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this chuc vu2 vai tro.
	 *
	 * @param nguoiSua the nguoi sua of this chuc vu2 vai tro
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the vai tro ID of this chuc vu2 vai tro.
	 *
	 * @return the vai tro ID of this chuc vu2 vai tro
	 */
	public Long getVaiTroId();

	/**
	 * Sets the vai tro ID of this chuc vu2 vai tro.
	 *
	 * @param vaiTroId the vai tro ID of this chuc vu2 vai tro
	 */
	public void setVaiTroId(Long vaiTroId);

	/**
	 * Returns the co quan quan ly ID of this chuc vu2 vai tro.
	 *
	 * @return the co quan quan ly ID of this chuc vu2 vai tro
	 */
	public Long getCoQuanQuanLyId();

	/**
	 * Sets the co quan quan ly ID of this chuc vu2 vai tro.
	 *
	 * @param coQuanQuanLyId the co quan quan ly ID of this chuc vu2 vai tro
	 */
	public void setCoQuanQuanLyId(Long coQuanQuanLyId);

	/**
	 * Returns the chuc vu ID of this chuc vu2 vai tro.
	 *
	 * @return the chuc vu ID of this chuc vu2 vai tro
	 */
	public Long getChucVuId();

	/**
	 * Sets the chuc vu ID of this chuc vu2 vai tro.
	 *
	 * @param chucVuId the chuc vu ID of this chuc vu2 vai tro
	 */
	public void setChucVuId(Long chucVuId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ChucVu2VaiTro chucVu2VaiTro);

	public int hashCode();

	public CacheModel<ChucVu2VaiTro> toCacheModel();

	public ChucVu2VaiTro toEscapedModel();

	public String toString();

	public String toXmlString();
}