/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.oep.cmon.dao.dvc.model.VanBanHuongDan;
import org.oep.cmon.dao.dvc.service.CapNhatKetQuaLocalService;
import org.oep.cmon.dao.dvc.service.CauHinhPortlet2ThuTucLocalService;
import org.oep.cmon.dao.dvc.service.DanhMucGiayTo2DoiTuongSuDungLocalService;
import org.oep.cmon.dao.dvc.service.DanhMucUngDungLocalService;
import org.oep.cmon.dao.dvc.service.DoiTuongSuDungLocalService;
import org.oep.cmon.dao.dvc.service.NhomThuTucHanhChinhLocalService;
import org.oep.cmon.dao.dvc.service.TTHC2CoQuanQuanLyLocalService;
import org.oep.cmon.dao.dvc.service.TTHC2DoiTuongSuDungLocalService;
import org.oep.cmon.dao.dvc.service.ThuTuc2GiayToLocalService;
import org.oep.cmon.dao.dvc.service.ThuTucHanhChinhLocalService;
import org.oep.cmon.dao.dvc.service.VanBanHuongDanLocalService;
import org.oep.cmon.dao.dvc.service.persistence.CapNhatKetQuaPersistence;
import org.oep.cmon.dao.dvc.service.persistence.CauHinhPortlet2ThuTucPersistence;
import org.oep.cmon.dao.dvc.service.persistence.DanhMucGiayTo2DoiTuongSuDungPersistence;
import org.oep.cmon.dao.dvc.service.persistence.DanhMucUngDungPersistence;
import org.oep.cmon.dao.dvc.service.persistence.DoiTuongSuDungPersistence;
import org.oep.cmon.dao.dvc.service.persistence.NhomThuTucHanhChinhPersistence;
import org.oep.cmon.dao.dvc.service.persistence.TTHC2CoQuanQuanLyPersistence;
import org.oep.cmon.dao.dvc.service.persistence.TTHC2DoiTuongSuDungPersistence;
import org.oep.cmon.dao.dvc.service.persistence.ThuTuc2GiayToFinder;
import org.oep.cmon.dao.dvc.service.persistence.ThuTuc2GiayToPersistence;
import org.oep.cmon.dao.dvc.service.persistence.ThuTucHanhChinhFinder;
import org.oep.cmon.dao.dvc.service.persistence.ThuTucHanhChinhPersistence;
import org.oep.cmon.dao.dvc.service.persistence.VanBanHuongDanPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the van ban huong dan local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.oep.cmon.dao.dvc.service.impl.VanBanHuongDanLocalServiceImpl}.
 * </p>
 *
 * @author liemnn
 * @see org.oep.cmon.dao.dvc.service.impl.VanBanHuongDanLocalServiceImpl
 * @see org.oep.cmon.dao.dvc.service.VanBanHuongDanLocalServiceUtil
 * @generated
 */
public abstract class VanBanHuongDanLocalServiceBaseImpl
	implements VanBanHuongDanLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.oep.cmon.dao.dvc.service.VanBanHuongDanLocalServiceUtil} to access the van ban huong dan local service.
	 */

	/**
	 * Adds the van ban huong dan to the database. Also notifies the appropriate model listeners.
	 *
	 * @param vanBanHuongDan the van ban huong dan
	 * @return the van ban huong dan that was added
	 * @throws SystemException if a system exception occurred
	 */
	public VanBanHuongDan addVanBanHuongDan(VanBanHuongDan vanBanHuongDan)
		throws SystemException {
		vanBanHuongDan.setNew(true);

		vanBanHuongDan = vanBanHuongDanPersistence.update(vanBanHuongDan, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(vanBanHuongDan);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return vanBanHuongDan;
	}

	/**
	 * Creates a new van ban huong dan with the primary key. Does not add the van ban huong dan to the database.
	 *
	 * @param id the primary key for the new van ban huong dan
	 * @return the new van ban huong dan
	 */
	public VanBanHuongDan createVanBanHuongDan(long id) {
		return vanBanHuongDanPersistence.create(id);
	}

	/**
	 * Deletes the van ban huong dan with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the van ban huong dan
	 * @throws PortalException if a van ban huong dan with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteVanBanHuongDan(long id)
		throws PortalException, SystemException {
		VanBanHuongDan vanBanHuongDan = vanBanHuongDanPersistence.remove(id);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(vanBanHuongDan);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the van ban huong dan from the database. Also notifies the appropriate model listeners.
	 *
	 * @param vanBanHuongDan the van ban huong dan
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteVanBanHuongDan(VanBanHuongDan vanBanHuongDan)
		throws SystemException {
		vanBanHuongDanPersistence.remove(vanBanHuongDan);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(vanBanHuongDan);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return vanBanHuongDanPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return vanBanHuongDanPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return vanBanHuongDanPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return vanBanHuongDanPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public VanBanHuongDan fetchVanBanHuongDan(long id)
		throws SystemException {
		return vanBanHuongDanPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the van ban huong dan with the primary key.
	 *
	 * @param id the primary key of the van ban huong dan
	 * @return the van ban huong dan
	 * @throws PortalException if a van ban huong dan with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public VanBanHuongDan getVanBanHuongDan(long id)
		throws PortalException, SystemException {
		return vanBanHuongDanPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return vanBanHuongDanPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the van ban huong dans.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of van ban huong dans
	 * @param end the upper bound of the range of van ban huong dans (not inclusive)
	 * @return the range of van ban huong dans
	 * @throws SystemException if a system exception occurred
	 */
	public List<VanBanHuongDan> getVanBanHuongDans(int start, int end)
		throws SystemException {
		return vanBanHuongDanPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of van ban huong dans.
	 *
	 * @return the number of van ban huong dans
	 * @throws SystemException if a system exception occurred
	 */
	public int getVanBanHuongDansCount() throws SystemException {
		return vanBanHuongDanPersistence.countAll();
	}

	/**
	 * Updates the van ban huong dan in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param vanBanHuongDan the van ban huong dan
	 * @return the van ban huong dan that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public VanBanHuongDan updateVanBanHuongDan(VanBanHuongDan vanBanHuongDan)
		throws SystemException {
		return updateVanBanHuongDan(vanBanHuongDan, true);
	}

	/**
	 * Updates the van ban huong dan in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param vanBanHuongDan the van ban huong dan
	 * @param merge whether to merge the van ban huong dan with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the van ban huong dan that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public VanBanHuongDan updateVanBanHuongDan(VanBanHuongDan vanBanHuongDan,
		boolean merge) throws SystemException {
		vanBanHuongDan.setNew(false);

		vanBanHuongDan = vanBanHuongDanPersistence.update(vanBanHuongDan, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(vanBanHuongDan);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return vanBanHuongDan;
	}

	/**
	 * Returns the cap nhat ket qua local service.
	 *
	 * @return the cap nhat ket qua local service
	 */
	public CapNhatKetQuaLocalService getCapNhatKetQuaLocalService() {
		return capNhatKetQuaLocalService;
	}

	/**
	 * Sets the cap nhat ket qua local service.
	 *
	 * @param capNhatKetQuaLocalService the cap nhat ket qua local service
	 */
	public void setCapNhatKetQuaLocalService(
		CapNhatKetQuaLocalService capNhatKetQuaLocalService) {
		this.capNhatKetQuaLocalService = capNhatKetQuaLocalService;
	}

	/**
	 * Returns the cap nhat ket qua persistence.
	 *
	 * @return the cap nhat ket qua persistence
	 */
	public CapNhatKetQuaPersistence getCapNhatKetQuaPersistence() {
		return capNhatKetQuaPersistence;
	}

	/**
	 * Sets the cap nhat ket qua persistence.
	 *
	 * @param capNhatKetQuaPersistence the cap nhat ket qua persistence
	 */
	public void setCapNhatKetQuaPersistence(
		CapNhatKetQuaPersistence capNhatKetQuaPersistence) {
		this.capNhatKetQuaPersistence = capNhatKetQuaPersistence;
	}

	/**
	 * Returns the cau hinh portlet2 thu tuc local service.
	 *
	 * @return the cau hinh portlet2 thu tuc local service
	 */
	public CauHinhPortlet2ThuTucLocalService getCauHinhPortlet2ThuTucLocalService() {
		return cauHinhPortlet2ThuTucLocalService;
	}

	/**
	 * Sets the cau hinh portlet2 thu tuc local service.
	 *
	 * @param cauHinhPortlet2ThuTucLocalService the cau hinh portlet2 thu tuc local service
	 */
	public void setCauHinhPortlet2ThuTucLocalService(
		CauHinhPortlet2ThuTucLocalService cauHinhPortlet2ThuTucLocalService) {
		this.cauHinhPortlet2ThuTucLocalService = cauHinhPortlet2ThuTucLocalService;
	}

	/**
	 * Returns the cau hinh portlet2 thu tuc persistence.
	 *
	 * @return the cau hinh portlet2 thu tuc persistence
	 */
	public CauHinhPortlet2ThuTucPersistence getCauHinhPortlet2ThuTucPersistence() {
		return cauHinhPortlet2ThuTucPersistence;
	}

	/**
	 * Sets the cau hinh portlet2 thu tuc persistence.
	 *
	 * @param cauHinhPortlet2ThuTucPersistence the cau hinh portlet2 thu tuc persistence
	 */
	public void setCauHinhPortlet2ThuTucPersistence(
		CauHinhPortlet2ThuTucPersistence cauHinhPortlet2ThuTucPersistence) {
		this.cauHinhPortlet2ThuTucPersistence = cauHinhPortlet2ThuTucPersistence;
	}

	/**
	 * Returns the danh muc giay to2 doi tuong su dung local service.
	 *
	 * @return the danh muc giay to2 doi tuong su dung local service
	 */
	public DanhMucGiayTo2DoiTuongSuDungLocalService getDanhMucGiayTo2DoiTuongSuDungLocalService() {
		return danhMucGiayTo2DoiTuongSuDungLocalService;
	}

	/**
	 * Sets the danh muc giay to2 doi tuong su dung local service.
	 *
	 * @param danhMucGiayTo2DoiTuongSuDungLocalService the danh muc giay to2 doi tuong su dung local service
	 */
	public void setDanhMucGiayTo2DoiTuongSuDungLocalService(
		DanhMucGiayTo2DoiTuongSuDungLocalService danhMucGiayTo2DoiTuongSuDungLocalService) {
		this.danhMucGiayTo2DoiTuongSuDungLocalService = danhMucGiayTo2DoiTuongSuDungLocalService;
	}

	/**
	 * Returns the danh muc giay to2 doi tuong su dung persistence.
	 *
	 * @return the danh muc giay to2 doi tuong su dung persistence
	 */
	public DanhMucGiayTo2DoiTuongSuDungPersistence getDanhMucGiayTo2DoiTuongSuDungPersistence() {
		return danhMucGiayTo2DoiTuongSuDungPersistence;
	}

	/**
	 * Sets the danh muc giay to2 doi tuong su dung persistence.
	 *
	 * @param danhMucGiayTo2DoiTuongSuDungPersistence the danh muc giay to2 doi tuong su dung persistence
	 */
	public void setDanhMucGiayTo2DoiTuongSuDungPersistence(
		DanhMucGiayTo2DoiTuongSuDungPersistence danhMucGiayTo2DoiTuongSuDungPersistence) {
		this.danhMucGiayTo2DoiTuongSuDungPersistence = danhMucGiayTo2DoiTuongSuDungPersistence;
	}

	/**
	 * Returns the danh muc ung dung local service.
	 *
	 * @return the danh muc ung dung local service
	 */
	public DanhMucUngDungLocalService getDanhMucUngDungLocalService() {
		return danhMucUngDungLocalService;
	}

	/**
	 * Sets the danh muc ung dung local service.
	 *
	 * @param danhMucUngDungLocalService the danh muc ung dung local service
	 */
	public void setDanhMucUngDungLocalService(
		DanhMucUngDungLocalService danhMucUngDungLocalService) {
		this.danhMucUngDungLocalService = danhMucUngDungLocalService;
	}

	/**
	 * Returns the danh muc ung dung persistence.
	 *
	 * @return the danh muc ung dung persistence
	 */
	public DanhMucUngDungPersistence getDanhMucUngDungPersistence() {
		return danhMucUngDungPersistence;
	}

	/**
	 * Sets the danh muc ung dung persistence.
	 *
	 * @param danhMucUngDungPersistence the danh muc ung dung persistence
	 */
	public void setDanhMucUngDungPersistence(
		DanhMucUngDungPersistence danhMucUngDungPersistence) {
		this.danhMucUngDungPersistence = danhMucUngDungPersistence;
	}

	/**
	 * Returns the doi tuong su dung local service.
	 *
	 * @return the doi tuong su dung local service
	 */
	public DoiTuongSuDungLocalService getDoiTuongSuDungLocalService() {
		return doiTuongSuDungLocalService;
	}

	/**
	 * Sets the doi tuong su dung local service.
	 *
	 * @param doiTuongSuDungLocalService the doi tuong su dung local service
	 */
	public void setDoiTuongSuDungLocalService(
		DoiTuongSuDungLocalService doiTuongSuDungLocalService) {
		this.doiTuongSuDungLocalService = doiTuongSuDungLocalService;
	}

	/**
	 * Returns the doi tuong su dung persistence.
	 *
	 * @return the doi tuong su dung persistence
	 */
	public DoiTuongSuDungPersistence getDoiTuongSuDungPersistence() {
		return doiTuongSuDungPersistence;
	}

	/**
	 * Sets the doi tuong su dung persistence.
	 *
	 * @param doiTuongSuDungPersistence the doi tuong su dung persistence
	 */
	public void setDoiTuongSuDungPersistence(
		DoiTuongSuDungPersistence doiTuongSuDungPersistence) {
		this.doiTuongSuDungPersistence = doiTuongSuDungPersistence;
	}

	/**
	 * Returns the nhom thu tuc hanh chinh local service.
	 *
	 * @return the nhom thu tuc hanh chinh local service
	 */
	public NhomThuTucHanhChinhLocalService getNhomThuTucHanhChinhLocalService() {
		return nhomThuTucHanhChinhLocalService;
	}

	/**
	 * Sets the nhom thu tuc hanh chinh local service.
	 *
	 * @param nhomThuTucHanhChinhLocalService the nhom thu tuc hanh chinh local service
	 */
	public void setNhomThuTucHanhChinhLocalService(
		NhomThuTucHanhChinhLocalService nhomThuTucHanhChinhLocalService) {
		this.nhomThuTucHanhChinhLocalService = nhomThuTucHanhChinhLocalService;
	}

	/**
	 * Returns the nhom thu tuc hanh chinh persistence.
	 *
	 * @return the nhom thu tuc hanh chinh persistence
	 */
	public NhomThuTucHanhChinhPersistence getNhomThuTucHanhChinhPersistence() {
		return nhomThuTucHanhChinhPersistence;
	}

	/**
	 * Sets the nhom thu tuc hanh chinh persistence.
	 *
	 * @param nhomThuTucHanhChinhPersistence the nhom thu tuc hanh chinh persistence
	 */
	public void setNhomThuTucHanhChinhPersistence(
		NhomThuTucHanhChinhPersistence nhomThuTucHanhChinhPersistence) {
		this.nhomThuTucHanhChinhPersistence = nhomThuTucHanhChinhPersistence;
	}

	/**
	 * Returns the thu tuc2 giay to local service.
	 *
	 * @return the thu tuc2 giay to local service
	 */
	public ThuTuc2GiayToLocalService getThuTuc2GiayToLocalService() {
		return thuTuc2GiayToLocalService;
	}

	/**
	 * Sets the thu tuc2 giay to local service.
	 *
	 * @param thuTuc2GiayToLocalService the thu tuc2 giay to local service
	 */
	public void setThuTuc2GiayToLocalService(
		ThuTuc2GiayToLocalService thuTuc2GiayToLocalService) {
		this.thuTuc2GiayToLocalService = thuTuc2GiayToLocalService;
	}

	/**
	 * Returns the thu tuc2 giay to persistence.
	 *
	 * @return the thu tuc2 giay to persistence
	 */
	public ThuTuc2GiayToPersistence getThuTuc2GiayToPersistence() {
		return thuTuc2GiayToPersistence;
	}

	/**
	 * Sets the thu tuc2 giay to persistence.
	 *
	 * @param thuTuc2GiayToPersistence the thu tuc2 giay to persistence
	 */
	public void setThuTuc2GiayToPersistence(
		ThuTuc2GiayToPersistence thuTuc2GiayToPersistence) {
		this.thuTuc2GiayToPersistence = thuTuc2GiayToPersistence;
	}

	/**
	 * Returns the thu tuc2 giay to finder.
	 *
	 * @return the thu tuc2 giay to finder
	 */
	public ThuTuc2GiayToFinder getThuTuc2GiayToFinder() {
		return thuTuc2GiayToFinder;
	}

	/**
	 * Sets the thu tuc2 giay to finder.
	 *
	 * @param thuTuc2GiayToFinder the thu tuc2 giay to finder
	 */
	public void setThuTuc2GiayToFinder(ThuTuc2GiayToFinder thuTuc2GiayToFinder) {
		this.thuTuc2GiayToFinder = thuTuc2GiayToFinder;
	}

	/**
	 * Returns the thu tuc hanh chinh local service.
	 *
	 * @return the thu tuc hanh chinh local service
	 */
	public ThuTucHanhChinhLocalService getThuTucHanhChinhLocalService() {
		return thuTucHanhChinhLocalService;
	}

	/**
	 * Sets the thu tuc hanh chinh local service.
	 *
	 * @param thuTucHanhChinhLocalService the thu tuc hanh chinh local service
	 */
	public void setThuTucHanhChinhLocalService(
		ThuTucHanhChinhLocalService thuTucHanhChinhLocalService) {
		this.thuTucHanhChinhLocalService = thuTucHanhChinhLocalService;
	}

	/**
	 * Returns the thu tuc hanh chinh persistence.
	 *
	 * @return the thu tuc hanh chinh persistence
	 */
	public ThuTucHanhChinhPersistence getThuTucHanhChinhPersistence() {
		return thuTucHanhChinhPersistence;
	}

	/**
	 * Sets the thu tuc hanh chinh persistence.
	 *
	 * @param thuTucHanhChinhPersistence the thu tuc hanh chinh persistence
	 */
	public void setThuTucHanhChinhPersistence(
		ThuTucHanhChinhPersistence thuTucHanhChinhPersistence) {
		this.thuTucHanhChinhPersistence = thuTucHanhChinhPersistence;
	}

	/**
	 * Returns the thu tuc hanh chinh finder.
	 *
	 * @return the thu tuc hanh chinh finder
	 */
	public ThuTucHanhChinhFinder getThuTucHanhChinhFinder() {
		return thuTucHanhChinhFinder;
	}

	/**
	 * Sets the thu tuc hanh chinh finder.
	 *
	 * @param thuTucHanhChinhFinder the thu tuc hanh chinh finder
	 */
	public void setThuTucHanhChinhFinder(
		ThuTucHanhChinhFinder thuTucHanhChinhFinder) {
		this.thuTucHanhChinhFinder = thuTucHanhChinhFinder;
	}

	/**
	 * Returns the t t h c2 co quan quan ly local service.
	 *
	 * @return the t t h c2 co quan quan ly local service
	 */
	public TTHC2CoQuanQuanLyLocalService getTTHC2CoQuanQuanLyLocalService() {
		return tthc2CoQuanQuanLyLocalService;
	}

	/**
	 * Sets the t t h c2 co quan quan ly local service.
	 *
	 * @param tthc2CoQuanQuanLyLocalService the t t h c2 co quan quan ly local service
	 */
	public void setTTHC2CoQuanQuanLyLocalService(
		TTHC2CoQuanQuanLyLocalService tthc2CoQuanQuanLyLocalService) {
		this.tthc2CoQuanQuanLyLocalService = tthc2CoQuanQuanLyLocalService;
	}

	/**
	 * Returns the t t h c2 co quan quan ly persistence.
	 *
	 * @return the t t h c2 co quan quan ly persistence
	 */
	public TTHC2CoQuanQuanLyPersistence getTTHC2CoQuanQuanLyPersistence() {
		return tthc2CoQuanQuanLyPersistence;
	}

	/**
	 * Sets the t t h c2 co quan quan ly persistence.
	 *
	 * @param tthc2CoQuanQuanLyPersistence the t t h c2 co quan quan ly persistence
	 */
	public void setTTHC2CoQuanQuanLyPersistence(
		TTHC2CoQuanQuanLyPersistence tthc2CoQuanQuanLyPersistence) {
		this.tthc2CoQuanQuanLyPersistence = tthc2CoQuanQuanLyPersistence;
	}

	/**
	 * Returns the t t h c2 doi tuong su dung local service.
	 *
	 * @return the t t h c2 doi tuong su dung local service
	 */
	public TTHC2DoiTuongSuDungLocalService getTTHC2DoiTuongSuDungLocalService() {
		return tthc2DoiTuongSuDungLocalService;
	}

	/**
	 * Sets the t t h c2 doi tuong su dung local service.
	 *
	 * @param tthc2DoiTuongSuDungLocalService the t t h c2 doi tuong su dung local service
	 */
	public void setTTHC2DoiTuongSuDungLocalService(
		TTHC2DoiTuongSuDungLocalService tthc2DoiTuongSuDungLocalService) {
		this.tthc2DoiTuongSuDungLocalService = tthc2DoiTuongSuDungLocalService;
	}

	/**
	 * Returns the t t h c2 doi tuong su dung persistence.
	 *
	 * @return the t t h c2 doi tuong su dung persistence
	 */
	public TTHC2DoiTuongSuDungPersistence getTTHC2DoiTuongSuDungPersistence() {
		return tthc2DoiTuongSuDungPersistence;
	}

	/**
	 * Sets the t t h c2 doi tuong su dung persistence.
	 *
	 * @param tthc2DoiTuongSuDungPersistence the t t h c2 doi tuong su dung persistence
	 */
	public void setTTHC2DoiTuongSuDungPersistence(
		TTHC2DoiTuongSuDungPersistence tthc2DoiTuongSuDungPersistence) {
		this.tthc2DoiTuongSuDungPersistence = tthc2DoiTuongSuDungPersistence;
	}

	/**
	 * Returns the van ban huong dan local service.
	 *
	 * @return the van ban huong dan local service
	 */
	public VanBanHuongDanLocalService getVanBanHuongDanLocalService() {
		return vanBanHuongDanLocalService;
	}

	/**
	 * Sets the van ban huong dan local service.
	 *
	 * @param vanBanHuongDanLocalService the van ban huong dan local service
	 */
	public void setVanBanHuongDanLocalService(
		VanBanHuongDanLocalService vanBanHuongDanLocalService) {
		this.vanBanHuongDanLocalService = vanBanHuongDanLocalService;
	}

	/**
	 * Returns the van ban huong dan persistence.
	 *
	 * @return the van ban huong dan persistence
	 */
	public VanBanHuongDanPersistence getVanBanHuongDanPersistence() {
		return vanBanHuongDanPersistence;
	}

	/**
	 * Sets the van ban huong dan persistence.
	 *
	 * @param vanBanHuongDanPersistence the van ban huong dan persistence
	 */
	public void setVanBanHuongDanPersistence(
		VanBanHuongDanPersistence vanBanHuongDanPersistence) {
		this.vanBanHuongDanPersistence = vanBanHuongDanPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.oep.cmon.dao.dvc.model.VanBanHuongDan",
			vanBanHuongDanLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.oep.cmon.dao.dvc.model.VanBanHuongDan");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return VanBanHuongDan.class;
	}

	protected String getModelClassName() {
		return VanBanHuongDan.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = vanBanHuongDanPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = CapNhatKetQuaLocalService.class)
	protected CapNhatKetQuaLocalService capNhatKetQuaLocalService;
	@BeanReference(type = CapNhatKetQuaPersistence.class)
	protected CapNhatKetQuaPersistence capNhatKetQuaPersistence;
	@BeanReference(type = CauHinhPortlet2ThuTucLocalService.class)
	protected CauHinhPortlet2ThuTucLocalService cauHinhPortlet2ThuTucLocalService;
	@BeanReference(type = CauHinhPortlet2ThuTucPersistence.class)
	protected CauHinhPortlet2ThuTucPersistence cauHinhPortlet2ThuTucPersistence;
	@BeanReference(type = DanhMucGiayTo2DoiTuongSuDungLocalService.class)
	protected DanhMucGiayTo2DoiTuongSuDungLocalService danhMucGiayTo2DoiTuongSuDungLocalService;
	@BeanReference(type = DanhMucGiayTo2DoiTuongSuDungPersistence.class)
	protected DanhMucGiayTo2DoiTuongSuDungPersistence danhMucGiayTo2DoiTuongSuDungPersistence;
	@BeanReference(type = DanhMucUngDungLocalService.class)
	protected DanhMucUngDungLocalService danhMucUngDungLocalService;
	@BeanReference(type = DanhMucUngDungPersistence.class)
	protected DanhMucUngDungPersistence danhMucUngDungPersistence;
	@BeanReference(type = DoiTuongSuDungLocalService.class)
	protected DoiTuongSuDungLocalService doiTuongSuDungLocalService;
	@BeanReference(type = DoiTuongSuDungPersistence.class)
	protected DoiTuongSuDungPersistence doiTuongSuDungPersistence;
	@BeanReference(type = NhomThuTucHanhChinhLocalService.class)
	protected NhomThuTucHanhChinhLocalService nhomThuTucHanhChinhLocalService;
	@BeanReference(type = NhomThuTucHanhChinhPersistence.class)
	protected NhomThuTucHanhChinhPersistence nhomThuTucHanhChinhPersistence;
	@BeanReference(type = ThuTuc2GiayToLocalService.class)
	protected ThuTuc2GiayToLocalService thuTuc2GiayToLocalService;
	@BeanReference(type = ThuTuc2GiayToPersistence.class)
	protected ThuTuc2GiayToPersistence thuTuc2GiayToPersistence;
	@BeanReference(type = ThuTuc2GiayToFinder.class)
	protected ThuTuc2GiayToFinder thuTuc2GiayToFinder;
	@BeanReference(type = ThuTucHanhChinhLocalService.class)
	protected ThuTucHanhChinhLocalService thuTucHanhChinhLocalService;
	@BeanReference(type = ThuTucHanhChinhPersistence.class)
	protected ThuTucHanhChinhPersistence thuTucHanhChinhPersistence;
	@BeanReference(type = ThuTucHanhChinhFinder.class)
	protected ThuTucHanhChinhFinder thuTucHanhChinhFinder;
	@BeanReference(type = TTHC2CoQuanQuanLyLocalService.class)
	protected TTHC2CoQuanQuanLyLocalService tthc2CoQuanQuanLyLocalService;
	@BeanReference(type = TTHC2CoQuanQuanLyPersistence.class)
	protected TTHC2CoQuanQuanLyPersistence tthc2CoQuanQuanLyPersistence;
	@BeanReference(type = TTHC2DoiTuongSuDungLocalService.class)
	protected TTHC2DoiTuongSuDungLocalService tthc2DoiTuongSuDungLocalService;
	@BeanReference(type = TTHC2DoiTuongSuDungPersistence.class)
	protected TTHC2DoiTuongSuDungPersistence tthc2DoiTuongSuDungPersistence;
	@BeanReference(type = VanBanHuongDanLocalService.class)
	protected VanBanHuongDanLocalService vanBanHuongDanLocalService;
	@BeanReference(type = VanBanHuongDanPersistence.class)
	protected VanBanHuongDanPersistence vanBanHuongDanPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(VanBanHuongDanLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}