/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dvc.model.CapNhatKetQua;
import org.oep.cmon.dao.dvc.model.CapNhatKetQuaModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the CapNhatKetQua service. Represents a row in the &quot;CMON_CAPNHATKETQUA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dvc.model.CapNhatKetQuaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CapNhatKetQuaImpl}.
 * </p>
 *
 * @author liemnn
 * @see CapNhatKetQuaImpl
 * @see org.oep.cmon.dao.dvc.model.CapNhatKetQua
 * @see org.oep.cmon.dao.dvc.model.CapNhatKetQuaModel
 * @generated
 */
public class CapNhatKetQuaModelImpl extends BaseModelImpl<CapNhatKetQua>
	implements CapNhatKetQuaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cap nhat ket qua model instance should use the {@link org.oep.cmon.dao.dvc.model.CapNhatKetQua} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_CAPNHATKETQUA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TENBANG", Types.VARCHAR },
			{ "BANGHIID", Types.BIGINT },
			{ "HANHDONG", Types.INTEGER },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "DAXOA", Types.INTEGER },
			{ "HOSOTTHCCONGID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_CAPNHATKETQUA (ID LONG not null primary key,TENBANG VARCHAR(75) null,BANGHIID LONG,HANHDONG INTEGER,NGAYTAO DATE null,NGUOITAO VARCHAR(75) null,NGAYSUA DATE null,NGUOISUA VARCHAR(75) null,DAXOA INTEGER,HOSOTTHCCONGID LONG)";
	public static final String TABLE_SQL_DROP = "drop table CMON_CAPNHATKETQUA";
	public static final String ORDER_BY_JPQL = " ORDER BY capNhatKetQua.id DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_CAPNHATKETQUA.ID DESC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dvc.model.CapNhatKetQua"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dvc.model.CapNhatKetQua"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dvc.model.CapNhatKetQua"));

	public CapNhatKetQuaModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CapNhatKetQua.class;
	}

	public String getModelClassName() {
		return CapNhatKetQua.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getTenBang() {
		if (_tenBang == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenBang;
		}
	}

	public void setTenBang(String tenBang) {
		_tenBang = tenBang;
	}

	public long getBanGhiId() {
		return _banGhiId;
	}

	public void setBanGhiId(long banGhiId) {
		_banGhiId = banGhiId;
	}

	public int getHanhDong() {
		return _hanhDong;
	}

	public void setHanhDong(int hanhDong) {
		_hanhDong = hanhDong;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_daXoa = daXoa;
	}

	public long getHosoTTHCCId() {
		return _hosoTTHCCId;
	}

	public void setHosoTTHCCId(long hosoTTHCCId) {
		_hosoTTHCCId = hosoTTHCCId;
	}

	@Override
	public CapNhatKetQua toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CapNhatKetQua)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CapNhatKetQua.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CapNhatKetQuaImpl capNhatKetQuaImpl = new CapNhatKetQuaImpl();

		capNhatKetQuaImpl.setId(getId());
		capNhatKetQuaImpl.setTenBang(getTenBang());
		capNhatKetQuaImpl.setBanGhiId(getBanGhiId());
		capNhatKetQuaImpl.setHanhDong(getHanhDong());
		capNhatKetQuaImpl.setNgayTao(getNgayTao());
		capNhatKetQuaImpl.setNguoiTao(getNguoiTao());
		capNhatKetQuaImpl.setNgaySua(getNgaySua());
		capNhatKetQuaImpl.setNguoiSua(getNguoiSua());
		capNhatKetQuaImpl.setDaXoa(getDaXoa());
		capNhatKetQuaImpl.setHosoTTHCCId(getHosoTTHCCId());

		capNhatKetQuaImpl.resetOriginalValues();

		return capNhatKetQuaImpl;
	}

	public int compareTo(CapNhatKetQua capNhatKetQua) {
		int value = 0;

		if (getId() < capNhatKetQua.getId()) {
			value = -1;
		}
		else if (getId() > capNhatKetQua.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CapNhatKetQua capNhatKetQua = null;

		try {
			capNhatKetQua = (CapNhatKetQua)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = capNhatKetQua.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CapNhatKetQua> toCacheModel() {
		CapNhatKetQuaCacheModel capNhatKetQuaCacheModel = new CapNhatKetQuaCacheModel();

		capNhatKetQuaCacheModel.id = getId();

		capNhatKetQuaCacheModel.tenBang = getTenBang();

		String tenBang = capNhatKetQuaCacheModel.tenBang;

		if ((tenBang != null) && (tenBang.length() == 0)) {
			capNhatKetQuaCacheModel.tenBang = null;
		}

		capNhatKetQuaCacheModel.banGhiId = getBanGhiId();

		capNhatKetQuaCacheModel.hanhDong = getHanhDong();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			capNhatKetQuaCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			capNhatKetQuaCacheModel.ngayTao = Long.MIN_VALUE;
		}

		capNhatKetQuaCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = capNhatKetQuaCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			capNhatKetQuaCacheModel.nguoiTao = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			capNhatKetQuaCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			capNhatKetQuaCacheModel.ngaySua = Long.MIN_VALUE;
		}

		capNhatKetQuaCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = capNhatKetQuaCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			capNhatKetQuaCacheModel.nguoiSua = null;
		}

		capNhatKetQuaCacheModel.daXoa = getDaXoa();

		capNhatKetQuaCacheModel.hosoTTHCCId = getHosoTTHCCId();

		return capNhatKetQuaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", tenBang=");
		sb.append(getTenBang());
		sb.append(", banGhiId=");
		sb.append(getBanGhiId());
		sb.append(", hanhDong=");
		sb.append(getHanhDong());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", hosoTTHCCId=");
		sb.append(getHosoTTHCCId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dvc.model.CapNhatKetQua");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenBang</column-name><column-value><![CDATA[");
		sb.append(getTenBang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>banGhiId</column-name><column-value><![CDATA[");
		sb.append(getBanGhiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hanhDong</column-name><column-value><![CDATA[");
		sb.append(getHanhDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hosoTTHCCId</column-name><column-value><![CDATA[");
		sb.append(getHosoTTHCCId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CapNhatKetQua.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CapNhatKetQua.class
		};
	private long _id;
	private String _tenBang;
	private long _banGhiId;
	private int _hanhDong;
	private Date _ngayTao;
	private String _nguoiTao;
	private Date _ngaySua;
	private String _nguoiSua;
	private int _daXoa;
	private long _hosoTTHCCId;
	private transient ExpandoBridge _expandoBridge;
	private CapNhatKetQua _escapedModelProxy;
}