/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.oep.cmon.dao.dvc.model.CapNhatKetQua;
import org.oep.cmon.dao.dvc.service.CapNhatKetQuaLocalServiceUtil;

/**
 * The extended model base implementation for the CapNhatKetQua service. Represents a row in the &quot;CMON_CAPNHATKETQUA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CapNhatKetQuaImpl}.
 * </p>
 *
 * @author liemnn
 * @see CapNhatKetQuaImpl
 * @see org.oep.cmon.dao.dvc.model.CapNhatKetQua
 * @generated
 */
public abstract class CapNhatKetQuaBaseImpl extends CapNhatKetQuaModelImpl
	implements CapNhatKetQua {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cap nhat ket qua model instance should use the {@link CapNhatKetQua} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			CapNhatKetQuaLocalServiceUtil.addCapNhatKetQua(this);
		}
		else {
			CapNhatKetQuaLocalServiceUtil.updateCapNhatKetQua(this);
		}
	}
}