/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dvc.model.DanhMucUngDung;
import org.oep.cmon.dao.dvc.model.DanhMucUngDungModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the DanhMucUngDung service. Represents a row in the &quot;CMON_DANHMUCUNGDUNG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dvc.model.DanhMucUngDungModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhMucUngDungImpl}.
 * </p>
 *
 * @author liemnn
 * @see DanhMucUngDungImpl
 * @see org.oep.cmon.dao.dvc.model.DanhMucUngDung
 * @see org.oep.cmon.dao.dvc.model.DanhMucUngDungModel
 * @generated
 */
public class DanhMucUngDungModelImpl extends BaseModelImpl<DanhMucUngDung>
	implements DanhMucUngDungModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh muc ung dung model instance should use the {@link org.oep.cmon.dao.dvc.model.DanhMucUngDung} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_DANHMUCUNGDUNG";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "NGUOISUA", Types.VARCHAR },
			{ "NGUOITAO", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_DANHMUCUNGDUNG (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,NGAYTAO DATE null,NGAYSUA DATE null,DAXOA INTEGER,NGUOISUA VARCHAR(75) null,NGUOITAO VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_DANHMUCUNGDUNG";
	public static final String ORDER_BY_JPQL = " ORDER BY danhMucUngDung.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_DANHMUCUNGDUNG.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dvc.model.DanhMucUngDung"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dvc.model.DanhMucUngDung"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.dvc.model.DanhMucUngDung"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long MA_COLUMN_BITMASK = 2L;
	public static long TEN_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dvc.model.DanhMucUngDung"));

	public DanhMucUngDungModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DanhMucUngDung.class;
	}

	public String getModelClassName() {
		return DanhMucUngDung.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DanhMucUngDung toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DanhMucUngDung)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DanhMucUngDung.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DanhMucUngDungImpl danhMucUngDungImpl = new DanhMucUngDungImpl();

		danhMucUngDungImpl.setId(getId());
		danhMucUngDungImpl.setMa(getMa());
		danhMucUngDungImpl.setTen(getTen());
		danhMucUngDungImpl.setNgayTao(getNgayTao());
		danhMucUngDungImpl.setNgaySua(getNgaySua());
		danhMucUngDungImpl.setDaXoa(getDaXoa());
		danhMucUngDungImpl.setNguoiSua(getNguoiSua());
		danhMucUngDungImpl.setNguoiTao(getNguoiTao());

		danhMucUngDungImpl.resetOriginalValues();

		return danhMucUngDungImpl;
	}

	public int compareTo(DanhMucUngDung danhMucUngDung) {
		int value = 0;

		if (getId() < danhMucUngDung.getId()) {
			value = -1;
		}
		else if (getId() > danhMucUngDung.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DanhMucUngDung danhMucUngDung = null;

		try {
			danhMucUngDung = (DanhMucUngDung)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = danhMucUngDung.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DanhMucUngDungModelImpl danhMucUngDungModelImpl = this;

		danhMucUngDungModelImpl._originalMa = danhMucUngDungModelImpl._ma;

		danhMucUngDungModelImpl._originalTen = danhMucUngDungModelImpl._ten;

		danhMucUngDungModelImpl._originalDaXoa = danhMucUngDungModelImpl._daXoa;

		danhMucUngDungModelImpl._setOriginalDaXoa = false;

		danhMucUngDungModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DanhMucUngDung> toCacheModel() {
		DanhMucUngDungCacheModel danhMucUngDungCacheModel = new DanhMucUngDungCacheModel();

		danhMucUngDungCacheModel.id = getId();

		danhMucUngDungCacheModel.ma = getMa();

		String ma = danhMucUngDungCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			danhMucUngDungCacheModel.ma = null;
		}

		danhMucUngDungCacheModel.ten = getTen();

		String ten = danhMucUngDungCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			danhMucUngDungCacheModel.ten = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			danhMucUngDungCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			danhMucUngDungCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			danhMucUngDungCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			danhMucUngDungCacheModel.ngaySua = Long.MIN_VALUE;
		}

		danhMucUngDungCacheModel.daXoa = getDaXoa();

		danhMucUngDungCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = danhMucUngDungCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			danhMucUngDungCacheModel.nguoiSua = null;
		}

		danhMucUngDungCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = danhMucUngDungCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			danhMucUngDungCacheModel.nguoiTao = null;
		}

		return danhMucUngDungCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dvc.model.DanhMucUngDung");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanhMucUngDung.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DanhMucUngDung.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private String _originalTen;
	private Date _ngayTao;
	private Date _ngaySua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private String _nguoiSua;
	private String _nguoiTao;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private DanhMucUngDung _escapedModelProxy;
}