/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dvc.model.DoiTuongSuDung;
import org.oep.cmon.dao.dvc.model.DoiTuongSuDungModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the DoiTuongSuDung service. Represents a row in the &quot;CMON_LOAIDOITUONG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dvc.model.DoiTuongSuDungModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DoiTuongSuDungImpl}.
 * </p>
 *
 * @author liemnn
 * @see DoiTuongSuDungImpl
 * @see org.oep.cmon.dao.dvc.model.DoiTuongSuDung
 * @see org.oep.cmon.dao.dvc.model.DoiTuongSuDungModel
 * @generated
 */
public class DoiTuongSuDungModelImpl extends BaseModelImpl<DoiTuongSuDung>
	implements DoiTuongSuDungModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a doi tuong su dung model instance should use the {@link org.oep.cmon.dao.dvc.model.DoiTuongSuDung} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_LOAIDOITUONG";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TEN", Types.VARCHAR },
			{ "MA", Types.VARCHAR },
			{ "MOTA", Types.VARCHAR },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "TRANGTHAI", Types.INTEGER },
			{ "DAXOA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_LOAIDOITUONG (ID LONG not null primary key,TEN VARCHAR(75) null,MA VARCHAR(75) null,MOTA VARCHAR(75) null,NGUOITAO VARCHAR(75) null,NGAYTAO DATE null,NGUOISUA VARCHAR(75) null,NGAYSUA DATE null,TRANGTHAI INTEGER,DAXOA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_LOAIDOITUONG";
	public static final String ORDER_BY_JPQL = " ORDER BY doiTuongSuDung.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_LOAIDOITUONG.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dvc.model.DoiTuongSuDung"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dvc.model.DoiTuongSuDung"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.dvc.model.DoiTuongSuDung"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long MA_COLUMN_BITMASK = 2L;
	public static long TEN_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dvc.model.DoiTuongSuDung"));

	public DoiTuongSuDungModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DoiTuongSuDung.class;
	}

	public String getModelClassName() {
		return DoiTuongSuDung.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getMota() {
		if (_mota == null) {
			return StringPool.BLANK;
		}
		else {
			return _mota;
		}
	}

	public void setMota(String mota) {
		_mota = mota;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getTrangThai() {
		return _trangThai;
	}

	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DoiTuongSuDung toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DoiTuongSuDung)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DoiTuongSuDung.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DoiTuongSuDungImpl doiTuongSuDungImpl = new DoiTuongSuDungImpl();

		doiTuongSuDungImpl.setId(getId());
		doiTuongSuDungImpl.setTen(getTen());
		doiTuongSuDungImpl.setMa(getMa());
		doiTuongSuDungImpl.setMota(getMota());
		doiTuongSuDungImpl.setNguoiTao(getNguoiTao());
		doiTuongSuDungImpl.setNgayTao(getNgayTao());
		doiTuongSuDungImpl.setNguoiSua(getNguoiSua());
		doiTuongSuDungImpl.setNgaySua(getNgaySua());
		doiTuongSuDungImpl.setTrangThai(getTrangThai());
		doiTuongSuDungImpl.setDaXoa(getDaXoa());

		doiTuongSuDungImpl.resetOriginalValues();

		return doiTuongSuDungImpl;
	}

	public int compareTo(DoiTuongSuDung doiTuongSuDung) {
		int value = 0;

		if (getId() < doiTuongSuDung.getId()) {
			value = -1;
		}
		else if (getId() > doiTuongSuDung.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DoiTuongSuDung doiTuongSuDung = null;

		try {
			doiTuongSuDung = (DoiTuongSuDung)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = doiTuongSuDung.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DoiTuongSuDungModelImpl doiTuongSuDungModelImpl = this;

		doiTuongSuDungModelImpl._originalTen = doiTuongSuDungModelImpl._ten;

		doiTuongSuDungModelImpl._originalMa = doiTuongSuDungModelImpl._ma;

		doiTuongSuDungModelImpl._originalDaXoa = doiTuongSuDungModelImpl._daXoa;

		doiTuongSuDungModelImpl._setOriginalDaXoa = false;

		doiTuongSuDungModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DoiTuongSuDung> toCacheModel() {
		DoiTuongSuDungCacheModel doiTuongSuDungCacheModel = new DoiTuongSuDungCacheModel();

		doiTuongSuDungCacheModel.id = getId();

		doiTuongSuDungCacheModel.ten = getTen();

		String ten = doiTuongSuDungCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			doiTuongSuDungCacheModel.ten = null;
		}

		doiTuongSuDungCacheModel.ma = getMa();

		String ma = doiTuongSuDungCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			doiTuongSuDungCacheModel.ma = null;
		}

		doiTuongSuDungCacheModel.mota = getMota();

		String mota = doiTuongSuDungCacheModel.mota;

		if ((mota != null) && (mota.length() == 0)) {
			doiTuongSuDungCacheModel.mota = null;
		}

		doiTuongSuDungCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = doiTuongSuDungCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			doiTuongSuDungCacheModel.nguoiTao = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			doiTuongSuDungCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			doiTuongSuDungCacheModel.ngayTao = Long.MIN_VALUE;
		}

		doiTuongSuDungCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = doiTuongSuDungCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			doiTuongSuDungCacheModel.nguoiSua = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			doiTuongSuDungCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			doiTuongSuDungCacheModel.ngaySua = Long.MIN_VALUE;
		}

		doiTuongSuDungCacheModel.trangThai = getTrangThai();

		doiTuongSuDungCacheModel.daXoa = getDaXoa();

		return doiTuongSuDungCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", mota=");
		sb.append(getMota());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dvc.model.DoiTuongSuDung");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mota</column-name><column-value><![CDATA[");
		sb.append(getMota());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DoiTuongSuDung.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DoiTuongSuDung.class
		};
	private long _id;
	private String _ten;
	private String _originalTen;
	private String _ma;
	private String _originalMa;
	private String _mota;
	private String _nguoiTao;
	private Date _ngayTao;
	private String _nguoiSua;
	private Date _ngaySua;
	private int _trangThai;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private DoiTuongSuDung _escapedModelProxy;
}