/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.oep.cmon.dao.dvc.model.ThuTuc2GiayTo;
import org.oep.cmon.dao.dvc.service.ThuTuc2GiayToLocalServiceUtil;

/**
 * The extended model base implementation for the ThuTuc2GiayTo service. Represents a row in the &quot;CMON_THUTUC2GIAYTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThuTuc2GiayToImpl}.
 * </p>
 *
 * @author liemnn
 * @see ThuTuc2GiayToImpl
 * @see org.oep.cmon.dao.dvc.model.ThuTuc2GiayTo
 * @generated
 */
public abstract class ThuTuc2GiayToBaseImpl extends ThuTuc2GiayToModelImpl
	implements ThuTuc2GiayTo {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thu tuc2 giay to model instance should use the {@link ThuTuc2GiayTo} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			ThuTuc2GiayToLocalServiceUtil.addThuTuc2GiayTo(this);
		}
		else {
			ThuTuc2GiayToLocalServiceUtil.updateThuTuc2GiayTo(this);
		}
	}
}