/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung;
import org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDungModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TTHC2DoiTuongSuDung service. Represents a row in the &quot;CMON_TTHC2DOITUONGSUDUNG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDungModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TTHC2DoiTuongSuDungImpl}.
 * </p>
 *
 * @author liemnn
 * @see TTHC2DoiTuongSuDungImpl
 * @see org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung
 * @see org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDungModel
 * @generated
 */
public class TTHC2DoiTuongSuDungModelImpl extends BaseModelImpl<TTHC2DoiTuongSuDung>
	implements TTHC2DoiTuongSuDungModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t t h c2 doi tuong su dung model instance should use the {@link org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_TTHC2DOITUONGSUDUNG";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "THUTUCHANHCHINHID", Types.BIGINT },
			{ "LOAIDOITUONGID", Types.BIGINT },
			{ "TRANGTHAI", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_TTHC2DOITUONGSUDUNG (ID LONG not null primary key,NGAYTAO DATE null,NGAYSUA DATE null,DAXOA INTEGER,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,THUTUCHANHCHINHID LONG,LOAIDOITUONGID LONG,TRANGTHAI INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_TTHC2DOITUONGSUDUNG";
	public static final String ORDER_BY_JPQL = " ORDER BY tthc2DoiTuongSuDung.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_TTHC2DOITUONGSUDUNG.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long LOAIDOITUONGID_COLUMN_BITMASK = 2L;
	public static long THUTUCHANHCHINHID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung"));

	public TTHC2DoiTuongSuDungModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TTHC2DoiTuongSuDung.class;
	}

	public String getModelClassName() {
		return TTHC2DoiTuongSuDung.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public long getThuTucHanhChinhId() {
		return _thuTucHanhChinhId;
	}

	public void setThuTucHanhChinhId(long thuTucHanhChinhId) {
		_columnBitmask |= THUTUCHANHCHINHID_COLUMN_BITMASK;

		if (!_setOriginalThuTucHanhChinhId) {
			_setOriginalThuTucHanhChinhId = true;

			_originalThuTucHanhChinhId = _thuTucHanhChinhId;
		}

		_thuTucHanhChinhId = thuTucHanhChinhId;
	}

	public long getOriginalThuTucHanhChinhId() {
		return _originalThuTucHanhChinhId;
	}

	public long getLoaiDoiTuongId() {
		return _loaiDoiTuongId;
	}

	public void setLoaiDoiTuongId(long loaiDoiTuongId) {
		_columnBitmask |= LOAIDOITUONGID_COLUMN_BITMASK;

		if (!_setOriginalLoaiDoiTuongId) {
			_setOriginalLoaiDoiTuongId = true;

			_originalLoaiDoiTuongId = _loaiDoiTuongId;
		}

		_loaiDoiTuongId = loaiDoiTuongId;
	}

	public long getOriginalLoaiDoiTuongId() {
		return _originalLoaiDoiTuongId;
	}

	public int getTrangThai() {
		return _trangThai;
	}

	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TTHC2DoiTuongSuDung toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TTHC2DoiTuongSuDung)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TTHC2DoiTuongSuDung.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TTHC2DoiTuongSuDungImpl tthc2DoiTuongSuDungImpl = new TTHC2DoiTuongSuDungImpl();

		tthc2DoiTuongSuDungImpl.setId(getId());
		tthc2DoiTuongSuDungImpl.setNgayTao(getNgayTao());
		tthc2DoiTuongSuDungImpl.setNgaySua(getNgaySua());
		tthc2DoiTuongSuDungImpl.setDaXoa(getDaXoa());
		tthc2DoiTuongSuDungImpl.setNguoiTao(getNguoiTao());
		tthc2DoiTuongSuDungImpl.setNguoiSua(getNguoiSua());
		tthc2DoiTuongSuDungImpl.setThuTucHanhChinhId(getThuTucHanhChinhId());
		tthc2DoiTuongSuDungImpl.setLoaiDoiTuongId(getLoaiDoiTuongId());
		tthc2DoiTuongSuDungImpl.setTrangThai(getTrangThai());

		tthc2DoiTuongSuDungImpl.resetOriginalValues();

		return tthc2DoiTuongSuDungImpl;
	}

	public int compareTo(TTHC2DoiTuongSuDung tthc2DoiTuongSuDung) {
		int value = 0;

		if (getId() < tthc2DoiTuongSuDung.getId()) {
			value = -1;
		}
		else if (getId() > tthc2DoiTuongSuDung.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TTHC2DoiTuongSuDung tthc2DoiTuongSuDung = null;

		try {
			tthc2DoiTuongSuDung = (TTHC2DoiTuongSuDung)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tthc2DoiTuongSuDung.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TTHC2DoiTuongSuDungModelImpl tthc2DoiTuongSuDungModelImpl = this;

		tthc2DoiTuongSuDungModelImpl._originalDaXoa = tthc2DoiTuongSuDungModelImpl._daXoa;

		tthc2DoiTuongSuDungModelImpl._setOriginalDaXoa = false;

		tthc2DoiTuongSuDungModelImpl._originalThuTucHanhChinhId = tthc2DoiTuongSuDungModelImpl._thuTucHanhChinhId;

		tthc2DoiTuongSuDungModelImpl._setOriginalThuTucHanhChinhId = false;

		tthc2DoiTuongSuDungModelImpl._originalLoaiDoiTuongId = tthc2DoiTuongSuDungModelImpl._loaiDoiTuongId;

		tthc2DoiTuongSuDungModelImpl._setOriginalLoaiDoiTuongId = false;

		tthc2DoiTuongSuDungModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TTHC2DoiTuongSuDung> toCacheModel() {
		TTHC2DoiTuongSuDungCacheModel tthc2DoiTuongSuDungCacheModel = new TTHC2DoiTuongSuDungCacheModel();

		tthc2DoiTuongSuDungCacheModel.id = getId();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			tthc2DoiTuongSuDungCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			tthc2DoiTuongSuDungCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			tthc2DoiTuongSuDungCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			tthc2DoiTuongSuDungCacheModel.ngaySua = Long.MIN_VALUE;
		}

		tthc2DoiTuongSuDungCacheModel.daXoa = getDaXoa();

		tthc2DoiTuongSuDungCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = tthc2DoiTuongSuDungCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			tthc2DoiTuongSuDungCacheModel.nguoiTao = null;
		}

		tthc2DoiTuongSuDungCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = tthc2DoiTuongSuDungCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			tthc2DoiTuongSuDungCacheModel.nguoiSua = null;
		}

		tthc2DoiTuongSuDungCacheModel.thuTucHanhChinhId = getThuTucHanhChinhId();

		tthc2DoiTuongSuDungCacheModel.loaiDoiTuongId = getLoaiDoiTuongId();

		tthc2DoiTuongSuDungCacheModel.trangThai = getTrangThai();

		return tthc2DoiTuongSuDungCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", thuTucHanhChinhId=");
		sb.append(getThuTucHanhChinhId());
		sb.append(", loaiDoiTuongId=");
		sb.append(getLoaiDoiTuongId());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dvc.model.TTHC2DoiTuongSuDung");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getThuTucHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiDoiTuongId</column-name><column-value><![CDATA[");
		sb.append(getLoaiDoiTuongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TTHC2DoiTuongSuDung.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TTHC2DoiTuongSuDung.class
		};
	private long _id;
	private Date _ngayTao;
	private Date _ngaySua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private String _nguoiTao;
	private String _nguoiSua;
	private long _thuTucHanhChinhId;
	private long _originalThuTucHanhChinhId;
	private boolean _setOriginalThuTucHanhChinhId;
	private long _loaiDoiTuongId;
	private long _originalLoaiDoiTuongId;
	private boolean _setOriginalLoaiDoiTuongId;
	private int _trangThai;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TTHC2DoiTuongSuDung _escapedModelProxy;
}