/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dvc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dvc.model.VanBanHuongDan;
import org.oep.cmon.dao.dvc.model.VanBanHuongDanModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the VanBanHuongDan service. Represents a row in the &quot;CMON_VANBANHUONGDAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dvc.model.VanBanHuongDanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VanBanHuongDanImpl}.
 * </p>
 *
 * @author liemnn
 * @see VanBanHuongDanImpl
 * @see org.oep.cmon.dao.dvc.model.VanBanHuongDan
 * @see org.oep.cmon.dao.dvc.model.VanBanHuongDanModel
 * @generated
 */
public class VanBanHuongDanModelImpl extends BaseModelImpl<VanBanHuongDan>
	implements VanBanHuongDanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a van ban huong dan model instance should use the {@link org.oep.cmon.dao.dvc.model.VanBanHuongDan} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_VANBANHUONGDAN";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NOILUUTRUID", Types.BIGINT },
			{ "TENTAILIEU", Types.VARCHAR },
			{ "MOTA", Types.VARCHAR },
			{ "LOAITAILIEU", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "THUTUCHANHCHINHID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_VANBANHUONGDAN (ID LONG not null primary key,NOILUUTRUID LONG,TENTAILIEU VARCHAR(75) null,MOTA VARCHAR(75) null,LOAITAILIEU LONG,NGAYTAO DATE null,NGAYSUA DATE null,DAXOA INTEGER,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,THUTUCHANHCHINHID LONG)";
	public static final String TABLE_SQL_DROP = "drop table CMON_VANBANHUONGDAN";
	public static final String ORDER_BY_JPQL = " ORDER BY vanBanHuongDan.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_VANBANHUONGDAN.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dvc.model.VanBanHuongDan"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dvc.model.VanBanHuongDan"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.dvc.model.VanBanHuongDan"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long LOAITAILIEU_COLUMN_BITMASK = 2L;
	public static long NOILUUTRUID_COLUMN_BITMASK = 4L;
	public static long TENTAILIEU_COLUMN_BITMASK = 8L;
	public static long THUTUCHANHCHINHID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dvc.model.VanBanHuongDan"));

	public VanBanHuongDanModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return VanBanHuongDan.class;
	}

	public String getModelClassName() {
		return VanBanHuongDan.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public long getNoiLuuTruId() {
		return _noiLuuTruId;
	}

	public void setNoiLuuTruId(long noiLuuTruId) {
		_columnBitmask |= NOILUUTRUID_COLUMN_BITMASK;

		if (!_setOriginalNoiLuuTruId) {
			_setOriginalNoiLuuTruId = true;

			_originalNoiLuuTruId = _noiLuuTruId;
		}

		_noiLuuTruId = noiLuuTruId;
	}

	public long getOriginalNoiLuuTruId() {
		return _originalNoiLuuTruId;
	}

	public String getTenTaiLieu() {
		if (_tenTaiLieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTaiLieu;
		}
	}

	public void setTenTaiLieu(String tenTaiLieu) {
		_columnBitmask |= TENTAILIEU_COLUMN_BITMASK;

		if (_originalTenTaiLieu == null) {
			_originalTenTaiLieu = _tenTaiLieu;
		}

		_tenTaiLieu = tenTaiLieu;
	}

	public String getOriginalTenTaiLieu() {
		return GetterUtil.getString(_originalTenTaiLieu);
	}

	public String getMoTa() {
		if (_moTa == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTa;
		}
	}

	public void setMoTa(String moTa) {
		_moTa = moTa;
	}

	public long getLoaiTaiLieu() {
		return _loaiTaiLieu;
	}

	public void setLoaiTaiLieu(long loaiTaiLieu) {
		_columnBitmask |= LOAITAILIEU_COLUMN_BITMASK;

		if (!_setOriginalLoaiTaiLieu) {
			_setOriginalLoaiTaiLieu = true;

			_originalLoaiTaiLieu = _loaiTaiLieu;
		}

		_loaiTaiLieu = loaiTaiLieu;
	}

	public long getOriginalLoaiTaiLieu() {
		return _originalLoaiTaiLieu;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public long getThuTucHanhChinhId() {
		return _thuTucHanhChinhId;
	}

	public void setThuTucHanhChinhId(long thuTucHanhChinhId) {
		_columnBitmask |= THUTUCHANHCHINHID_COLUMN_BITMASK;

		if (!_setOriginalThuTucHanhChinhId) {
			_setOriginalThuTucHanhChinhId = true;

			_originalThuTucHanhChinhId = _thuTucHanhChinhId;
		}

		_thuTucHanhChinhId = thuTucHanhChinhId;
	}

	public long getOriginalThuTucHanhChinhId() {
		return _originalThuTucHanhChinhId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VanBanHuongDan toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (VanBanHuongDan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					VanBanHuongDan.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		VanBanHuongDanImpl vanBanHuongDanImpl = new VanBanHuongDanImpl();

		vanBanHuongDanImpl.setId(getId());
		vanBanHuongDanImpl.setNoiLuuTruId(getNoiLuuTruId());
		vanBanHuongDanImpl.setTenTaiLieu(getTenTaiLieu());
		vanBanHuongDanImpl.setMoTa(getMoTa());
		vanBanHuongDanImpl.setLoaiTaiLieu(getLoaiTaiLieu());
		vanBanHuongDanImpl.setNgayTao(getNgayTao());
		vanBanHuongDanImpl.setNgaySua(getNgaySua());
		vanBanHuongDanImpl.setDaXoa(getDaXoa());
		vanBanHuongDanImpl.setNguoiTao(getNguoiTao());
		vanBanHuongDanImpl.setNguoiSua(getNguoiSua());
		vanBanHuongDanImpl.setThuTucHanhChinhId(getThuTucHanhChinhId());

		vanBanHuongDanImpl.resetOriginalValues();

		return vanBanHuongDanImpl;
	}

	public int compareTo(VanBanHuongDan vanBanHuongDan) {
		int value = 0;

		if (getId() < vanBanHuongDan.getId()) {
			value = -1;
		}
		else if (getId() > vanBanHuongDan.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VanBanHuongDan vanBanHuongDan = null;

		try {
			vanBanHuongDan = (VanBanHuongDan)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = vanBanHuongDan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VanBanHuongDanModelImpl vanBanHuongDanModelImpl = this;

		vanBanHuongDanModelImpl._originalNoiLuuTruId = vanBanHuongDanModelImpl._noiLuuTruId;

		vanBanHuongDanModelImpl._setOriginalNoiLuuTruId = false;

		vanBanHuongDanModelImpl._originalTenTaiLieu = vanBanHuongDanModelImpl._tenTaiLieu;

		vanBanHuongDanModelImpl._originalLoaiTaiLieu = vanBanHuongDanModelImpl._loaiTaiLieu;

		vanBanHuongDanModelImpl._setOriginalLoaiTaiLieu = false;

		vanBanHuongDanModelImpl._originalDaXoa = vanBanHuongDanModelImpl._daXoa;

		vanBanHuongDanModelImpl._setOriginalDaXoa = false;

		vanBanHuongDanModelImpl._originalThuTucHanhChinhId = vanBanHuongDanModelImpl._thuTucHanhChinhId;

		vanBanHuongDanModelImpl._setOriginalThuTucHanhChinhId = false;

		vanBanHuongDanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VanBanHuongDan> toCacheModel() {
		VanBanHuongDanCacheModel vanBanHuongDanCacheModel = new VanBanHuongDanCacheModel();

		vanBanHuongDanCacheModel.id = getId();

		vanBanHuongDanCacheModel.noiLuuTruId = getNoiLuuTruId();

		vanBanHuongDanCacheModel.tenTaiLieu = getTenTaiLieu();

		String tenTaiLieu = vanBanHuongDanCacheModel.tenTaiLieu;

		if ((tenTaiLieu != null) && (tenTaiLieu.length() == 0)) {
			vanBanHuongDanCacheModel.tenTaiLieu = null;
		}

		vanBanHuongDanCacheModel.moTa = getMoTa();

		String moTa = vanBanHuongDanCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			vanBanHuongDanCacheModel.moTa = null;
		}

		vanBanHuongDanCacheModel.loaiTaiLieu = getLoaiTaiLieu();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			vanBanHuongDanCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			vanBanHuongDanCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			vanBanHuongDanCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			vanBanHuongDanCacheModel.ngaySua = Long.MIN_VALUE;
		}

		vanBanHuongDanCacheModel.daXoa = getDaXoa();

		vanBanHuongDanCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = vanBanHuongDanCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			vanBanHuongDanCacheModel.nguoiTao = null;
		}

		vanBanHuongDanCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = vanBanHuongDanCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			vanBanHuongDanCacheModel.nguoiSua = null;
		}

		vanBanHuongDanCacheModel.thuTucHanhChinhId = getThuTucHanhChinhId();

		return vanBanHuongDanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", noiLuuTruId=");
		sb.append(getNoiLuuTruId());
		sb.append(", tenTaiLieu=");
		sb.append(getTenTaiLieu());
		sb.append(", moTa=");
		sb.append(getMoTa());
		sb.append(", loaiTaiLieu=");
		sb.append(getLoaiTaiLieu());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", thuTucHanhChinhId=");
		sb.append(getThuTucHanhChinhId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dvc.model.VanBanHuongDan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiLuuTruId</column-name><column-value><![CDATA[");
		sb.append(getNoiLuuTruId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTaiLieu</column-name><column-value><![CDATA[");
		sb.append(getTenTaiLieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTa</column-name><column-value><![CDATA[");
		sb.append(getMoTa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiTaiLieu</column-name><column-value><![CDATA[");
		sb.append(getLoaiTaiLieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getThuTucHanhChinhId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VanBanHuongDan.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			VanBanHuongDan.class
		};
	private long _id;
	private long _noiLuuTruId;
	private long _originalNoiLuuTruId;
	private boolean _setOriginalNoiLuuTruId;
	private String _tenTaiLieu;
	private String _originalTenTaiLieu;
	private String _moTa;
	private long _loaiTaiLieu;
	private long _originalLoaiTaiLieu;
	private boolean _setOriginalLoaiTaiLieu;
	private Date _ngayTao;
	private Date _ngaySua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private String _nguoiTao;
	private String _nguoiSua;
	private long _thuTucHanhChinhId;
	private long _originalThuTucHanhChinhId;
	private boolean _setOriginalThuTucHanhChinhId;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private VanBanHuongDan _escapedModelProxy;
}