create index IX_F86AF139 on CC_Foo (field2);

create index IX_2506565 on CMON_CAPCOQUANQUANLY (MA);
create index IX_48214630 on CMON_CAPCOQUANQUANLY (TEN);

create index IX_9C1A0C9F on CMON_CAPDONVIHANHCHINH (MA);
create index IX_E78C8636 on CMON_CAPDONVIHANHCHINH (TEN);

create index IX_81631CB6 on CMON_CHUCVU (MA);
create index IX_AB6578FF on CMON_CHUCVU (TEN);

create index IX_86F95796 on CMON_CMON_NHOMNGUOIDUNG (MA);
create index IX_58969A1F on CMON_CMON_NHOMNGUOIDUNG (TEN);

create index IX_D23B5555 on CMON_CONGCHUC (CHUCVUID);
create index IX_DACF1F63 on CMON_CONGCHUC (CONGDANID);
create index IX_A6C7353E on CMON_CONGCHUC (COQUANQUANLYID);
create index IX_773AD55C on CMON_CONGCHUC (MA);
create index IX_87F782F4 on CMON_CONGCHUC (TAIKHOANNGUOIDUNGID);

create index IX_870DD904 on CMON_CONGDAN (MA);
create index IX_891F77D9 on CMON_CONGDAN (MA, TEN, SOCMND);
create index IX_96E60A66 on CMON_CONGDAN (NGHENGHIEPID);
create index IX_FB25E558 on CMON_CONGDAN (QUANHECHUHOID);
create index IX_C4DC845D on CMON_CONGDAN (QUOCTICHID);
create index IX_AC10226C on CMON_CONGDAN (SOCMND);
create index IX_71B00B5 on CMON_CONGDAN (SODINHDANHMEID);
create index IX_59DCA4DE on CMON_CONGDAN (SODINHDANHVOHOACCHONGID);
create index IX_6DE7444C on CMON_CONGDAN (TAIKHOANNGUOIDUNGID);
create index IX_5B124671 on CMON_CONGDAN (TEN);
create index IX_A2A54D52 on CMON_CONGDAN (TONGIAOID);
create index IX_A17AC575 on CMON_CONGDAN (TRINHDOCHUYENMONID);

create index IX_61115871 on CMON_DANHMUCGIAYTO (MA);
create index IX_C17EB4A4 on CMON_DANHMUCGIAYTO (TEN);

create index IX_91DE1F98 on CMON_DANHMUCUNGDUNG (MA);
create index IX_AA4AD25D on CMON_DANHMUCUNGDUNG (TEN);

create index IX_1CC64D6B on CMON_DMGIAYTO2DOITUONGSUDUNG (DANHMUCGIAYTOID);
create index IX_281F449A on CMON_DMGIAYTO2DOITUONGSUDUNG (NHOMNGUOIDUNGID);

create index IX_6FF9DDA1 on CMON_DONVIHANHCHINH (CAPDONVIHANHCHINHID);
create index IX_7B390FD6 on CMON_DONVIHANHCHINH (CHAID);
create index IX_6BD71F19 on CMON_DONVIHANHCHINH (MA);
create index IX_24594501 on CMON_DONVIHANHCHINH (QUOCGIAID);
create index IX_F71C2FC on CMON_DONVIHANHCHINH (TEN);

create index IX_652C08B3 on CMON_NGUOIDUNG2NHOMVAITRO (NHOMVAITROID);
create index IX_962BF1AF on CMON_NGUOIDUNG2NHOMVAITRO (TAIKHOANNGUOIDUNGID);

create index IX_ECC523C7 on CMON_NGUOIDUNG2VAITRO (TAIKHOANNGUOIDUNGID);
create index IX_CD723C03 on CMON_NGUOIDUNG2VAITRO (VAITROID);

create index IX_8D9B4C62 on CMON_NHOMNGUOIDUNG2NHOMVAITRO (NHOMNGUOIDUNGID);
create index IX_B7839ECB on CMON_NHOMNGUOIDUNG2NHOMVAITRO (NHOMVAITROID);

create index IX_935EFE7A on CMON_NHOMNGUOIDUNG2VAITRO (NHOMNGUOIDUNGID);
create index IX_186D6A1B on CMON_NHOMNGUOIDUNG2VAITRO (VAITROID);

create index IX_1EABCE05 on CMON_NHOMTHUTUCHANHCHINH (DANHMUCUNGDUNGID);
create index IX_9FB91B2A on CMON_NHOMTHUTUCHANHCHINH (MA);
create index IX_57CF490B on CMON_NHOMTHUTUCHANHCHINH (TEN);

create index IX_390BD82F on CMON_NHOMVAITRO (MA);
create index IX_264F792A on CMON_NHOMVAITRO (MOTA);
create index IX_E8D42CA6 on CMON_NHOMVAITRO (TEN);

create index IX_D046B43F on CMON_QUOCGIA (MA);

create index IX_E85620BF on CMON_TAIKHOANNGUOIDUNG (EMAIL);
create index IX_3DE742DF on CMON_TAIKHOANNGUOIDUNG (TENDANGNHAP);
create index IX_4857FC84 on CMON_TAIKHOANNGUOIDUNG (TENNGUOIDUNG);

create index IX_702E7AA6 on CMON_TAILIEUCHUNGTHUC (DANHMUCGIAYTOID);
create index IX_7D586DA0 on CMON_TAILIEUCHUNGTHUC (NOILUUTRUID);

create index IX_3E2F0C8E on CMON_THUTUC2GIAYTO (DANHMUCGIAYTOID);
create index IX_9DD9231F on CMON_THUTUC2GIAYTO (THUTUCHANHCHINHID);

create index IX_95971E42 on CMON_THUTUCHANHCHINH (MA);
create index IX_CF4C5463 on CMON_THUTUCHANHCHINH (NHOMTHUTUCHANHCHINHID);
create index IX_1DB1A8F3 on CMON_THUTUCHANHCHINH (TEN);

create index IX_9F732217 on CMON_TRINHDOCHUYENMON (DAXOA);

create index IX_5541DEEC on CMON_TTHC2COQUANQUANLY (COQUANQUANLYID);
create index IX_46534BB3 on CMON_TTHC2COQUANQUANLY (THUTUCHANHCHINHID);

create index IX_6D65177 on CMON_TTHC2DOITUONGSUDUNG (NHOMNGUOIDUNGID);
create index IX_40CAEA59 on CMON_TTHC2DOITUONGSUDUNG (THUTUCHANHCHINHID);

create index IX_89817A17 on CMON_VAITRO (MA);
create index IX_2FE44112 on CMON_VAITRO (MOTA);
create index IX_FF196209 on CMON_VAITRO (NHOMVAITROID);
create index IX_A712C7BE on CMON_VAITRO (TEN);

create index IX_11D79410 on CMON_VANBANHUONGDAN (LOAITAILIEU);
create index IX_7587C620 on CMON_VANBANHUONGDAN (NOILUUTRUID);
create index IX_8D63FEBE on CMON_VANBANHUONGDAN (TENTAILIEU);
create index IX_BE2063B7 on CMON_VANBANHUONGDAN (THUTUCHANHCHINHID);

create index IX_724A58A0 on CMON_YKIENTRAODOI (HOSOTTHCCONGID);
create index IX_9C131C68 on CMON_YKIENTRAODOI (HOSOTTHCCONGID, NGUOINHANID);
create index IX_59EEB660 on CMON_YKIENTRAODOI (HOSOTTHCCONGID, NGUOINHANID, TRANGTHAI);
create index IX_CD11AF79 on CMON_YKIENTRAODOI (MAHOSO);
create index IX_33676E2F on CMON_YKIENTRAODOI (MAHOSO, NGUOINHANID);
create index IX_D6855239 on CMON_YKIENTRAODOI (MAHOSO, NGUOINHANID, TRANGTHAI);
create index IX_81EA407A on CMON_YKIENTRAODOI (TRANGTHAI);

create index IX_B66A5FE3 on DN_Foo (field2);