create table CC_Foo (
	fooId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	field1 VARCHAR(75) null,
	field2 BOOLEAN,
	field3 INTEGER,
	field4 DATE null,
	field5 VARCHAR(75) null
);

create table CMON_CAPCOQUANQUANLY (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	CAP LONG,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_CAPDONVIHANHCHINH (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	CAP LONG,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_CHUCVU (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGAYSUA DATE null,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_CMON_NHOMNGUOIDUNG (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	MOTA VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGAYSUA DATE null,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	TRANGTHAI INTEGER
);

create table CMON_CONGCHUC (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	TAIKHOANNGUOIDUNGID LONG,
	NGUOISUA VARCHAR(75) null,
	CHUCVUID LONG,
	CONGDANID LONG,
	COQUANQUANLYID LONG,
	NGUOITAO VARCHAR(75) null
);

create table CMON_CONGDAN (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	HO VARCHAR(75) null,
	DEM VARCHAR(75) null,
	TEN VARCHAR(75) null,
	ANH VARCHAR(75) null,
	NGAYSINH DATE null,
	GIOITINH LONG,
	SOCMND VARCHAR(75) null,
	NGAYCAPCMND DATE null,
	GHICHUCMND VARCHAR(75) null,
	SOHOCHIEU VARCHAR(75) null,
	NGAYCAPHOCHIEU DATE null,
	NGAYHETHANHOCHIEU DATE null,
	GHICHUHOCHIEU VARCHAR(75) null,
	SOBAOHIEMYTE VARCHAR(75) null,
	MASOTHUECANHAN VARCHAR(75) null,
	TINHTRANGHONNHAN INTEGER,
	DIACHITHUONGTRU VARCHAR(75) null,
	DIACHIHIENNAY VARCHAR(75) null,
	DIENTHOAICODINH VARCHAR(75) null,
	DIENTHOAIDIDONG VARCHAR(75) null,
	HOTENCHA VARCHAR(75) null,
	HOTENME VARCHAR(75) null,
	HOTENVOHOACCHONG VARCHAR(75) null,
	SOHOKHAU VARCHAR(75) null,
	LACHUHO INTEGER,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGAYSUA DATE null,
	QUOCTICHID LONG,
	TRINHDOCHUYENMONID LONG,
	SODINHDANHCHAID LONG,
	NOICAPHOCHIEUID LONG,
	TRINHDOHOCVANID LONG,
	DANTOCID LONG,
	TAIKHOANNGUOIDUNGID LONG,
	NOISINHID LONG,
	NOICAPCMNDID LONG,
	NGHENGHIEPID LONG,
	TONGIAOID LONG,
	SODINHDANHMEID LONG,
	SODINHDANHVOHOACCHONGID LONG,
	DIACHIHIENNAYID LONG,
	NGUOITAO VARCHAR(75) null,
	DIACHITHUONGTRUID LONG,
	QUANHECHUHOID INTEGER,
	NGUOISUA VARCHAR(75) null
);

create table CMON_DANHMUCGIAYTO (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	MOTA VARCHAR(75) null,
	GIOIHANDUNGLUONG LONG,
	KIEUTAILIEU VARCHAR(75) null,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_DANHMUCUNGDUNG (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null
);

create table CMON_DANTOC (
	ID INTEGER not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	LATHIEUSO LONG,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NGAYSUA DATE null
);

create table CMON_DMGIAYTO2DOITUONGSUDUNG (
	ID LONG not null primary key,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NHOMNGUOIDUNGID LONG,
	DANHMUCGIAYTOID LONG,
	TRANGTHAI INTEGER
);

create table CMON_DONVIHANHCHINH (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGAYSUA DATE null,
	CAPDONVIHANHCHINHID LONG,
	CHAID LONG,
	NGUOITAO VARCHAR(75) null,
	QUOCGIAID LONG,
	NGUOISUA VARCHAR(75) null
);

create table CMON_NGHENGHIEP (
	ID INTEGER not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NGAYSUA DATE null
);

create table CMON_NGUOIDUNG2NHOMVAITRO (
	ID LONG not null primary key,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	TAIKHOANNGUOIDUNGID LONG,
	NHOMVAITROID LONG,
	NGAYSUA DATE null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_NGUOIDUNG2VAITRO (
	ID LONG not null primary key,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	TAIKHOANNGUOIDUNGID LONG,
	VAITROID LONG,
	NGAYSUA DATE null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_NHOMNGUOIDUNG2NHOMVAITRO (
	ID LONG not null primary key,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NHOMNGUOIDUNGID LONG,
	NHOMVAITROID LONG,
	NGAYSUA DATE null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_NHOMNGUOIDUNG2VAITRO (
	ID LONG not null primary key,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NHOMNGUOIDUNGID LONG,
	VAITROID LONG,
	NGAYSUA DATE null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_NHOMTHUTUCHANHCHINH (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	DANHMUCUNGDUNGID LONG
);

create table CMON_NHOMVAITRO (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	MOTA VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGAYSUA DATE null,
	NGUOISUA VARCHAR(75) null,
	TRANGTHAI INTEGER
);

create table CMON_QUANHEGIADINH (
	ID INTEGER not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NGAYSUA DATE null
);

create table CMON_QUOCGIA (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_TAIKHOANNGUOIDUNG (
	ID LONG not null primary key,
	TENDANGNHAP VARCHAR(75) null,
	MATKHAU VARCHAR(75) null,
	TENNGUOIDUNG VARCHAR(75) null,
	CAUHOIMATKHAU VARCHAR(75) null,
	CAUTRALOIMATKHAU VARCHAR(75) null,
	EMAIL VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGAYSUA DATE null,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_TAILIEUCHUNGTHUC (
	ID LONG not null primary key,
	TENTAILIEU VARCHAR(75) null,
	GHICHU VARCHAR(75) null,
	NOILUUTRUID LONG,
	NGAYUPLOAD DATE null,
	PHIENBAN INTEGER,
	NGAYDUYET DATE null,
	HIEULUCTUNGAY DATE null,
	HIEULUCDENNGAY DATE null,
	TRANGTHAI INTEGER,
	NGUOITAO LONG,
	NGUOIDUYETID LONG,
	DANHMUCGIAYTOID LONG,
	NGAYSUA DATE null,
	NGUOISUA VARCHAR(75) null
);

create table CMON_THUTUC2GIAYTO (
	ID LONG not null primary key,
	GHICHU VARCHAR(75) null,
	BATBUOC INTEGER,
	THUTUHIENTHI LONG,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	THUTUCHANHCHINHID LONG,
	DANHMUCGIAYTOID LONG,
	TRANGTHAI INTEGER
);

create table CMON_THUTUCHANHCHINH (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	SONGAYXULY LONG,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NHOMTHUTUCHANHCHINHID LONG,
	TRANGTHAI INTEGER
);

create table CMON_TONGIAO (
	ID INTEGER not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NGAYSUA DATE null
);

create table CMON_TRINHDOCHUYENMON (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	CHUYENMONID INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NGAYSUA DATE null,
	PHIENBAN LONG
);

create table CMON_TRINHDOHOCVAN (
	ID INTEGER not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	NGAYSUA DATE null
);

create table CMON_TTHC2COQUANQUANLY (
	ID LONG not null primary key,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGUOISUA VARCHAR(75) null,
	THUTUCHANHCHINHID LONG,
	COQUANQUANLYID LONG,
	TRANGTHAI INTEGER
);

create table CMON_TTHC2DOITUONGSUDUNG (
	ID LONG not null primary key,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	THUTUCHANHCHINHID LONG,
	NHOMNGUOIDUNGID LONG
);

create table CMON_VAITRO (
	ID LONG not null primary key,
	MA VARCHAR(75) null,
	TEN VARCHAR(75) null,
	MOTA VARCHAR(75) null,
	NHOMVAITROID LONG,
	NGAYTAO DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	NGAYSUA DATE null,
	NGUOISUA VARCHAR(75) null,
	TRANGTHAI INTEGER
);

create table CMON_VANBANHUONGDAN (
	ID LONG not null primary key,
	NOILUUTRUID LONG,
	TENTAILIEU VARCHAR(75) null,
	MOTA VARCHAR(75) null,
	LOAITAILIEU LONG,
	NGAYTAO DATE null,
	NGAYSUA DATE null,
	DAXOA INTEGER,
	NGUOITAO VARCHAR(75) null,
	THUTUCHANHCHINHID LONG
);

create table CMON_YKIENTRAODOI (
	ID LONG not null primary key,
	TIEUDE VARCHAR(75) null,
	NOIDUNGYKIEN VARCHAR(75) null,
	HOSOTTHCCONGID LONG,
	THOIGIANGUIYKIEN DATE null,
	TRANGTHAI LONG,
	NGUOINHANID LONG,
	NGUOIGUIID LONG,
	CHAID LONG
);

create table DN_Foo (
	fooId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	field1 VARCHAR(75) null,
	field2 BOOLEAN,
	field3 INTEGER,
	field4 DATE null,
	field5 VARCHAR(75) null
);