
package org.oep.sharedservice.touchscreen.kios.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Fri Sep 05 15:13:06 ICT 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "getDanhSachCoQuanResponse", namespace = "http://kios.touchscreen.sharedservice.dtt.vn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDanhSachCoQuanResponse", namespace = "http://kios.touchscreen.sharedservice.dtt.vn/")

public class GetDanhSachCoQuanResponse {

    @XmlElement(name = "return")
    private java.util.List<vn.dtt.cmon.dao.kios.model.DanhSachCoQuanSoap> _return;

    public java.util.List<vn.dtt.cmon.dao.kios.model.DanhSachCoQuanSoap> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<vn.dtt.cmon.dao.kios.model.DanhSachCoQuanSoap> new_return)  {
        this._return = new_return;
    }

}

