/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.anhcongdan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AnhCongDan service. Represents a row in the &quot;CMON_VIEW_CONGDAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.anhcongdan.model.impl.AnhCongDanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.anhcongdan.model.impl.AnhCongDanImpl}.
 * </p>
 *
 * @author BinhNT
 * @see AnhCongDan
 * @see org.oep.cmon.anhcongdan.model.impl.AnhCongDanImpl
 * @see org.oep.cmon.anhcongdan.model.impl.AnhCongDanModelImpl
 * @generated
 */
public interface AnhCongDanModel extends BaseModel<AnhCongDan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a anh cong dan model instance should use the {@link AnhCongDan} interface instead.
	 */

	/**
	 * Returns the primary key of this anh cong dan.
	 *
	 * @return the primary key of this anh cong dan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this anh cong dan.
	 *
	 * @param primaryKey the primary key of this anh cong dan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this anh cong dan.
	 *
	 * @return the ID of this anh cong dan
	 */
	public long getId();

	/**
	 * Sets the ID of this anh cong dan.
	 *
	 * @param id the ID of this anh cong dan
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this anh cong dan.
	 *
	 * @return the ma of this anh cong dan
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this anh cong dan.
	 *
	 * @param ma the ma of this anh cong dan
	 */
	public void setMa(String ma);

	/**
	 * Returns the email of this anh cong dan.
	 *
	 * @return the email of this anh cong dan
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this anh cong dan.
	 *
	 * @param email the email of this anh cong dan
	 */
	public void setEmail(String email);

	/**
	 * Returns the anh of this anh cong dan.
	 *
	 * @return the anh of this anh cong dan
	 */
	@AutoEscape
	public String getAnh();

	/**
	 * Sets the anh of this anh cong dan.
	 *
	 * @param anh the anh of this anh cong dan
	 */
	public void setAnh(String anh);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AnhCongDan anhCongDan);

	public int hashCode();

	public CacheModel<AnhCongDan> toCacheModel();

	public AnhCongDan toEscapedModel();

	public String toString();

	public String toXmlString();
}