/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.hosohcc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong;
import org.oep.cmon.dao.hosohcc.model.HoSoTTHCCongModel;
import org.oep.cmon.dao.hosohcc.model.HoSoTTHCCongSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the HoSoTTHCCong service. Represents a row in the &quot;CMON_HOSOTTHCCONG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.hosohcc.model.HoSoTTHCCongModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HoSoTTHCCongImpl}.
 * </p>
 *
 * @author LIEMNn
 * @see HoSoTTHCCongImpl
 * @see org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong
 * @see org.oep.cmon.dao.hosohcc.model.HoSoTTHCCongModel
 * @generated
 */
@JSON(strict = true)
public class HoSoTTHCCongModelImpl extends BaseModelImpl<HoSoTTHCCong>
	implements HoSoTTHCCongModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ho so t t h c cong model instance should use the {@link org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_HOSOTTHCCONG";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MASOHOSO", Types.VARCHAR },
			{ "NGAYNOPHOSO", Types.TIMESTAMP },
			{ "NGAYNHANHOSO", Types.TIMESTAMP },
			{ "TENCOQUANTIEPNHAN", Types.VARCHAR },
			{ "TENTHUTUCHANHCHINH", Types.VARCHAR },
			{ "NGAYHENTRAKETQUA", Types.TIMESTAMP },
			{ "NGAYTRAKETQUA", Types.TIMESTAMP },
			{ "NGAYNOPHOSOGOC", Types.TIMESTAMP },
			{ "NGAYHENNOPHOSOGOC", Types.TIMESTAMP },
			{ "TENCANBOTIEPNHAN", Types.VARCHAR },
			{ "CHUCVUCANBOTIEPNHAN", Types.VARCHAR },
			{ "HOTENNGUOINOPHOSO", Types.VARCHAR },
			{ "DIACHITHUONGTRUNGUOINOP", Types.VARCHAR },
			{ "SODIENTHOAICODINHNGUOINOP", Types.VARCHAR },
			{ "TENCANBOTRAKETQUA", Types.VARCHAR },
			{ "CHUCVUCANBOTRAKETQUA", Types.VARCHAR },
			{ "HOTENNGUOINHANKETQUA", Types.VARCHAR },
			{ "DIACHITHUONGTRUNGUOINHANKQ", Types.VARCHAR },
			{ "SODIENTHOAINGUOINHAN", Types.VARCHAR },
			{ "NGAYCAP", Types.TIMESTAMP },
			{ "LANCAP", Types.BIGINT },
			{ "TENCOQUANCAP", Types.VARCHAR },
			{ "HIEULUCTUNGAY", Types.TIMESTAMP },
			{ "HIEULUCDENNGAY", Types.TIMESTAMP },
			{ "TRANGTHAIHOSO", Types.INTEGER },
			{ "DAXOA", Types.INTEGER },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "THUTUCHANHCHINHID", Types.BIGINT },
			{ "CONGDANNOPID", Types.BIGINT },
			{ "DIACHITHUONGTRUNGUOINHANKQID", Types.BIGINT },
			{ "COQUANTIEPNHANID", Types.BIGINT },
			{ "CANBOTRAKETQUAID", Types.BIGINT },
			{ "CANBOTIEPNHANID", Types.BIGINT },
			{ "DIACHITHUONGTRUNGUOINOPID", Types.BIGINT },
			{ "SODIENTHOAIDIDONGNGUOINOP", Types.VARCHAR },
			{ "PHONGBANXULYHIENTHOIID", Types.BIGINT },
			{ "TENPHONGBANXULYHIENTHOI", Types.VARCHAR },
			{ "CANBOXULYHIENTHOIID", Types.BIGINT },
			{ "TENCANBOXULYHIENTHOI", Types.VARCHAR },
			{ "DANHGIAKETQUA", Types.INTEGER },
			{ "GHICHU", Types.VARCHAR },
			{ "NGAYKETTHUCXULY", Types.TIMESTAMP },
			{ "LOAIHOSO", Types.INTEGER },
			{ "YEUCAUHUYHOSO", Types.INTEGER },
			{ "MASOBIENNHAN", Types.VARCHAR },
			{ "TENBANGCHUAHOSO", Types.VARCHAR },
			{ "CHUSOHUU", Types.VARCHAR },
			{ "SOBOHOSO", Types.INTEGER },
			{ "LEPHI", Types.INTEGER },
			{ "PHIHOSO", Types.INTEGER },
			{ "TRICHYEU", Types.VARCHAR },
			{ "NGAYHENTBTHUE", Types.TIMESTAMP },
			{ "EMAILNGUOINOP", Types.VARCHAR },
			{ "MAUNGDUNG", Types.VARCHAR },
			{ "DAGUIGIAYHEN", Types.INTEGER },
			{ "NGUOIDAIDIENPHAPLUAT", Types.VARCHAR },
			{ "NGUOIDAIDIENPHAPLUATID", Types.BIGINT },
			{ "CHUYENSANGMOTCUA", Types.INTEGER },
			{ "DOITUONGCANXULYID", Types.BIGINT },
			{ "LYDO", Types.VARCHAR },
			{ "MOTATHANHPHANHOSO", Types.VARCHAR },
			{ "LIENKETTHANHPHANHOSO", Types.VARCHAR },
			{ "SONGAYXULY", Types.BIGINT },
			{ "DATRAKETQUATRUCTUYEN", Types.BIGINT },
			{ "EMAILNGUOINHAN", Types.VARCHAR },
			{ "NGAYSINHNGUOINHAN", Types.TIMESTAMP },
			{ "DIENTHOAICODINHNGUOINHAN", Types.VARCHAR },
			{ "CMNDNGUOINHAN", Types.VARCHAR },
			{ "GIOITINHNGUOINHAN", Types.INTEGER },
			{ "DUNGXULY", Types.BOOLEAN },
			{ "NGAYBOSUNG", Types.TIMESTAMP },
			{ "GHICHUGIAYTODINHKEM", Types.VARCHAR },
			{ "DADANGKYNHANSMS", Types.INTEGER },
			{ "DADANGKYCHUYENPHATNHANH", Types.INTEGER },
			{ "DIACHICHUHOSO", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_HOSOTTHCCONG (ID LONG not null primary key,MASOHOSO VARCHAR(75) null,NGAYNOPHOSO DATE null,NGAYNHANHOSO DATE null,TENCOQUANTIEPNHAN VARCHAR(75) null,TENTHUTUCHANHCHINH VARCHAR(75) null,NGAYHENTRAKETQUA DATE null,NGAYTRAKETQUA DATE null,NGAYNOPHOSOGOC DATE null,NGAYHENNOPHOSOGOC DATE null,TENCANBOTIEPNHAN VARCHAR(75) null,CHUCVUCANBOTIEPNHAN VARCHAR(75) null,HOTENNGUOINOPHOSO VARCHAR(75) null,DIACHITHUONGTRUNGUOINOP VARCHAR(75) null,SODIENTHOAICODINHNGUOINOP VARCHAR(75) null,TENCANBOTRAKETQUA VARCHAR(75) null,CHUCVUCANBOTRAKETQUA VARCHAR(75) null,HOTENNGUOINHANKETQUA VARCHAR(75) null,DIACHITHUONGTRUNGUOINHANKQ VARCHAR(75) null,SODIENTHOAINGUOINHAN VARCHAR(75) null,NGAYCAP DATE null,LANCAP LONG,TENCOQUANCAP VARCHAR(75) null,HIEULUCTUNGAY DATE null,HIEULUCDENNGAY DATE null,TRANGTHAIHOSO INTEGER,DAXOA INTEGER,NGUOITAO VARCHAR(75) null,NGAYTAO DATE null,NGUOISUA VARCHAR(75) null,NGAYSUA DATE null,THUTUCHANHCHINHID LONG null,CONGDANNOPID LONG null,DIACHITHUONGTRUNGUOINHANKQID LONG null,COQUANTIEPNHANID LONG null,CANBOTRAKETQUAID LONG null,CANBOTIEPNHANID LONG null,DIACHITHUONGTRUNGUOINOPID LONG null,SODIENTHOAIDIDONGNGUOINOP VARCHAR(75) null,PHONGBANXULYHIENTHOIID LONG null,TENPHONGBANXULYHIENTHOI VARCHAR(75) null,CANBOXULYHIENTHOIID LONG null,TENCANBOXULYHIENTHOI VARCHAR(75) null,DANHGIAKETQUA INTEGER,GHICHU VARCHAR(75) null,NGAYKETTHUCXULY DATE null,LOAIHOSO INTEGER,YEUCAUHUYHOSO INTEGER,MASOBIENNHAN VARCHAR(75) null,TENBANGCHUAHOSO VARCHAR(75) null,CHUSOHUU VARCHAR(75) null,SOBOHOSO INTEGER,LEPHI INTEGER,PHIHOSO INTEGER,TRICHYEU VARCHAR(75) null,NGAYHENTBTHUE DATE null,EMAILNGUOINOP VARCHAR(75) null,MAUNGDUNG VARCHAR(75) null,DAGUIGIAYHEN INTEGER,NGUOIDAIDIENPHAPLUAT VARCHAR(75) null,NGUOIDAIDIENPHAPLUATID LONG null,CHUYENSANGMOTCUA INTEGER,DOITUONGCANXULYID LONG null,LYDO VARCHAR(75) null,MOTATHANHPHANHOSO VARCHAR(75) null,LIENKETTHANHPHANHOSO VARCHAR(75) null,SONGAYXULY LONG,DATRAKETQUATRUCTUYEN LONG,EMAILNGUOINHAN VARCHAR(75) null,NGAYSINHNGUOINHAN DATE null,DIENTHOAICODINHNGUOINHAN VARCHAR(75) null,CMNDNGUOINHAN VARCHAR(75) null,GIOITINHNGUOINHAN INTEGER,DUNGXULY BOOLEAN,NGAYBOSUNG DATE null,GHICHUGIAYTODINHKEM VARCHAR(75) null,DADANGKYNHANSMS INTEGER,DADANGKYCHUYENPHATNHANH INTEGER,DIACHICHUHOSO VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_HOSOTTHCCONG";
	public static final String ORDER_BY_JPQL = " ORDER BY hoSoTTHCCong.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_HOSOTTHCCONG.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong"),
			true);
	public static long COQUANTIEPNHANID_COLUMN_BITMASK = 1L;
	public static long CONGDANNOPID_COLUMN_BITMASK = 2L;
	public static long DAXOA_COLUMN_BITMASK = 4L;
	public static long HOTENNGUOINOPHOSO_COLUMN_BITMASK = 8L;
	public static long LOAIHOSO_COLUMN_BITMASK = 16L;
	public static long MASOBIENNHAN_COLUMN_BITMASK = 32L;
	public static long MASOHOSO_COLUMN_BITMASK = 64L;
	public static long SODIENTHOAICODINHNGUOINOP_COLUMN_BITMASK = 128L;
	public static long SODIENTHOAIDIDONGNGUOINOP_COLUMN_BITMASK = 256L;
	public static long TENCOQUANTIEPNHAN_COLUMN_BITMASK = 512L;
	public static long TENPHONGBANXULYHIENTHOI_COLUMN_BITMASK = 1024L;
	public static long TENTHUTUCHANHCHINH_COLUMN_BITMASK = 2048L;
	public static long THUTUCHANHCHINHID_COLUMN_BITMASK = 4096L;
	public static long TRANGTHAIHOSO_COLUMN_BITMASK = 8192L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static HoSoTTHCCong toModel(HoSoTTHCCongSoap soapModel) {
		HoSoTTHCCong model = new HoSoTTHCCongImpl();

		model.setId(soapModel.getId());
		model.setMaSoHoSo(soapModel.getMaSoHoSo());
		model.setNgayNopHoSo(soapModel.getNgayNopHoSo());
		model.setNgayNhanHoSo(soapModel.getNgayNhanHoSo());
		model.setTenCoQuanTiepNhan(soapModel.getTenCoQuanTiepNhan());
		model.setTenThuTucHanhChinh(soapModel.getTenThuTucHanhChinh());
		model.setNgayHenTraKetQua(soapModel.getNgayHenTraKetQua());
		model.setNgayTraKetQua(soapModel.getNgayTraKetQua());
		model.setNgayNopHoSoGoc(soapModel.getNgayNopHoSoGoc());
		model.setNgayHenNopHoSoGoc(soapModel.getNgayHenNopHoSoGoc());
		model.setTenCanBoTiepNhan(soapModel.getTenCanBoTiepNhan());
		model.setChucVuCanBoTiepNhan(soapModel.getChucVuCanBoTiepNhan());
		model.setHoTenNguoiNopHoSo(soapModel.getHoTenNguoiNopHoSo());
		model.setDiaChiThuongTruNguoiNop(soapModel.getDiaChiThuongTruNguoiNop());
		model.setSoDienThoaiCoDinhNguoiNop(soapModel.getSoDienThoaiCoDinhNguoiNop());
		model.setTenCanBoTraKetQua(soapModel.getTenCanBoTraKetQua());
		model.setChucVuCanBoTraKetQua(soapModel.getChucVuCanBoTraKetQua());
		model.setHoTenNguoiNhanKetQua(soapModel.getHoTenNguoiNhanKetQua());
		model.setDiaChiThuongTruNguoiNhanKQ(soapModel.getDiaChiThuongTruNguoiNhanKQ());
		model.setSoDienThoaiNguoiNhan(soapModel.getSoDienThoaiNguoiNhan());
		model.setNgayCap(soapModel.getNgayCap());
		model.setLanCap(soapModel.getLanCap());
		model.setTenCoQuanCap(soapModel.getTenCoQuanCap());
		model.setHieuLucTuNgay(soapModel.getHieuLucTuNgay());
		model.setHieuLucDenNgay(soapModel.getHieuLucDenNgay());
		model.setTrangThaiHoSo(soapModel.getTrangThaiHoSo());
		model.setDaXoa(soapModel.getDaXoa());
		model.setNguoiTao(soapModel.getNguoiTao());
		model.setNgayTao(soapModel.getNgayTao());
		model.setNguoiSua(soapModel.getNguoiSua());
		model.setNgaySua(soapModel.getNgaySua());
		model.setThuTucHanhChinhId(soapModel.getThuTucHanhChinhId());
		model.setCongDanNopId(soapModel.getCongDanNopId());
		model.setDiaChiThuongTruNguoiNhanKQId(soapModel.getDiaChiThuongTruNguoiNhanKQId());
		model.setCoQuanTiepNhanId(soapModel.getCoQuanTiepNhanId());
		model.setCanBoTraKetQuaId(soapModel.getCanBoTraKetQuaId());
		model.setCanBoTiepNhanId(soapModel.getCanBoTiepNhanId());
		model.setDiaChiThuongTruNguoiNopId(soapModel.getDiaChiThuongTruNguoiNopId());
		model.setSoDienThoaiDiDongNguoiNop(soapModel.getSoDienThoaiDiDongNguoiNop());
		model.setPhongBanXuLyHienThoiId(soapModel.getPhongBanXuLyHienThoiId());
		model.setTenPhongBanXuLyHienThoi(soapModel.getTenPhongBanXuLyHienThoi());
		model.setCanBoXuLyHienThoiId(soapModel.getCanBoXuLyHienThoiId());
		model.setTenCanBoXuLyHienThoi(soapModel.getTenCanBoXuLyHienThoi());
		model.setDanhGiaKetQua(soapModel.getDanhGiaKetQua());
		model.setGhiChu(soapModel.getGhiChu());
		model.setNgayKetThucXuLy(soapModel.getNgayKetThucXuLy());
		model.setLoaiHoSo(soapModel.getLoaiHoSo());
		model.setYeuCauHuyHoSo(soapModel.getYeuCauHuyHoSo());
		model.setMaSoBienNhan(soapModel.getMaSoBienNhan());
		model.setTenBangChuaHoSo(soapModel.getTenBangChuaHoSo());
		model.setChuSoHuu(soapModel.getChuSoHuu());
		model.setSoBoHoSo(soapModel.getSoBoHoSo());
		model.setLePhi(soapModel.getLePhi());
		model.setPhiHoSo(soapModel.getPhiHoSo());
		model.setTrichYeu(soapModel.getTrichYeu());
		model.setNgayHenTBThue(soapModel.getNgayHenTBThue());
		model.setEmailNguoiNop(soapModel.getEmailNguoiNop());
		model.setMaUngDung(soapModel.getMaUngDung());
		model.setDaGuiGiayHen(soapModel.getDaGuiGiayHen());
		model.setNguoiDaiDienPhapLuat(soapModel.getNguoiDaiDienPhapLuat());
		model.setNguoiDaiDienPhapLuatId(soapModel.getNguoiDaiDienPhapLuatId());
		model.setChuyenSangMotCua(soapModel.getChuyenSangMotCua());
		model.setDoiTuongCanXuLyId(soapModel.getDoiTuongCanXuLyId());
		model.setLyDo(soapModel.getLyDo());
		model.setMoTaThanhPhanHoSo(soapModel.getMoTaThanhPhanHoSo());
		model.setLienKetThanhPhanHoSo(soapModel.getLienKetThanhPhanHoSo());
		model.setSoNgayXuLy(soapModel.getSoNgayXuLy());
		model.setDaTraKetQuaTrucTuyen(soapModel.getDaTraKetQuaTrucTuyen());
		model.setEMailNguoiNhan(soapModel.getEMailNguoiNhan());
		model.setNgaySinhNguoiNhan(soapModel.getNgaySinhNguoiNhan());
		model.setDienThoiCoDinhNguoiNhan(soapModel.getDienThoiCoDinhNguoiNhan());
		model.setCmndNguoiNhan(soapModel.getCmndNguoiNhan());
		model.setGioiTinh(soapModel.getGioiTinh());
		model.setDungXuLy(soapModel.getDungXuLy());
		model.setNgayBoSung(soapModel.getNgayBoSung());
		model.setGhiChuGiayToDinhKem(soapModel.getGhiChuGiayToDinhKem());
		model.setDaDangKyNhanSMS(soapModel.getDaDangKyNhanSMS());
		model.setDaDangKyChuyenPhatNhanh(soapModel.getDaDangKyChuyenPhatNhanh());
		model.setDiaChiChuHoSo(soapModel.getDiaChiChuHoSo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<HoSoTTHCCong> toModels(HoSoTTHCCongSoap[] soapModels) {
		List<HoSoTTHCCong> models = new ArrayList<HoSoTTHCCong>(soapModels.length);

		for (HoSoTTHCCongSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong"));

	public HoSoTTHCCongModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return HoSoTTHCCong.class;
	}

	public String getModelClassName() {
		return HoSoTTHCCong.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getMaSoHoSo() {
		return _maSoHoSo;
	}

	public void setMaSoHoSo(String maSoHoSo) {
		_columnBitmask |= MASOHOSO_COLUMN_BITMASK;

		if (_originalMaSoHoSo == null) {
			_originalMaSoHoSo = _maSoHoSo;
		}

		_maSoHoSo = maSoHoSo;
	}

	public String getOriginalMaSoHoSo() {
		return _originalMaSoHoSo;
	}

	@JSON
	public Date getNgayNopHoSo() {
		return _ngayNopHoSo;
	}

	public void setNgayNopHoSo(Date ngayNopHoSo) {
		_ngayNopHoSo = ngayNopHoSo;
	}

	@JSON
	public Date getNgayNhanHoSo() {
		return _ngayNhanHoSo;
	}

	public void setNgayNhanHoSo(Date ngayNhanHoSo) {
		_ngayNhanHoSo = ngayNhanHoSo;
	}

	@JSON
	public String getTenCoQuanTiepNhan() {
		return _tenCoQuanTiepNhan;
	}

	public void setTenCoQuanTiepNhan(String tenCoQuanTiepNhan) {
		_columnBitmask |= TENCOQUANTIEPNHAN_COLUMN_BITMASK;

		if (_originalTenCoQuanTiepNhan == null) {
			_originalTenCoQuanTiepNhan = _tenCoQuanTiepNhan;
		}

		_tenCoQuanTiepNhan = tenCoQuanTiepNhan;
	}

	public String getOriginalTenCoQuanTiepNhan() {
		return _originalTenCoQuanTiepNhan;
	}

	@JSON
	public String getTenThuTucHanhChinh() {
		return _tenThuTucHanhChinh;
	}

	public void setTenThuTucHanhChinh(String tenThuTucHanhChinh) {
		_columnBitmask |= TENTHUTUCHANHCHINH_COLUMN_BITMASK;

		if (_originalTenThuTucHanhChinh == null) {
			_originalTenThuTucHanhChinh = _tenThuTucHanhChinh;
		}

		_tenThuTucHanhChinh = tenThuTucHanhChinh;
	}

	public String getOriginalTenThuTucHanhChinh() {
		return _originalTenThuTucHanhChinh;
	}

	@JSON
	public Date getNgayHenTraKetQua() {
		return _ngayHenTraKetQua;
	}

	public void setNgayHenTraKetQua(Date ngayHenTraKetQua) {
		_ngayHenTraKetQua = ngayHenTraKetQua;
	}

	@JSON
	public Date getNgayTraKetQua() {
		return _ngayTraKetQua;
	}

	public void setNgayTraKetQua(Date ngayTraKetQua) {
		_ngayTraKetQua = ngayTraKetQua;
	}

	@JSON
	public Date getNgayNopHoSoGoc() {
		return _ngayNopHoSoGoc;
	}

	public void setNgayNopHoSoGoc(Date ngayNopHoSoGoc) {
		_ngayNopHoSoGoc = ngayNopHoSoGoc;
	}

	@JSON
	public Date getNgayHenNopHoSoGoc() {
		return _ngayHenNopHoSoGoc;
	}

	public void setNgayHenNopHoSoGoc(Date ngayHenNopHoSoGoc) {
		_ngayHenNopHoSoGoc = ngayHenNopHoSoGoc;
	}

	@JSON
	public String getTenCanBoTiepNhan() {
		return _tenCanBoTiepNhan;
	}

	public void setTenCanBoTiepNhan(String tenCanBoTiepNhan) {
		_tenCanBoTiepNhan = tenCanBoTiepNhan;
	}

	@JSON
	public String getChucVuCanBoTiepNhan() {
		return _chucVuCanBoTiepNhan;
	}

	public void setChucVuCanBoTiepNhan(String chucVuCanBoTiepNhan) {
		_chucVuCanBoTiepNhan = chucVuCanBoTiepNhan;
	}

	@JSON
	public String getHoTenNguoiNopHoSo() {
		return _hoTenNguoiNopHoSo;
	}

	public void setHoTenNguoiNopHoSo(String hoTenNguoiNopHoSo) {
		_columnBitmask |= HOTENNGUOINOPHOSO_COLUMN_BITMASK;

		if (_originalHoTenNguoiNopHoSo == null) {
			_originalHoTenNguoiNopHoSo = _hoTenNguoiNopHoSo;
		}

		_hoTenNguoiNopHoSo = hoTenNguoiNopHoSo;
	}

	public String getOriginalHoTenNguoiNopHoSo() {
		return _originalHoTenNguoiNopHoSo;
	}

	@JSON
	public String getDiaChiThuongTruNguoiNop() {
		return _diaChiThuongTruNguoiNop;
	}

	public void setDiaChiThuongTruNguoiNop(String diaChiThuongTruNguoiNop) {
		_diaChiThuongTruNguoiNop = diaChiThuongTruNguoiNop;
	}

	@JSON
	public String getSoDienThoaiCoDinhNguoiNop() {
		return _soDienThoaiCoDinhNguoiNop;
	}

	public void setSoDienThoaiCoDinhNguoiNop(String soDienThoaiCoDinhNguoiNop) {
		_columnBitmask |= SODIENTHOAICODINHNGUOINOP_COLUMN_BITMASK;

		if (_originalSoDienThoaiCoDinhNguoiNop == null) {
			_originalSoDienThoaiCoDinhNguoiNop = _soDienThoaiCoDinhNguoiNop;
		}

		_soDienThoaiCoDinhNguoiNop = soDienThoaiCoDinhNguoiNop;
	}

	public String getOriginalSoDienThoaiCoDinhNguoiNop() {
		return _originalSoDienThoaiCoDinhNguoiNop;
	}

	@JSON
	public String getTenCanBoTraKetQua() {
		return _tenCanBoTraKetQua;
	}

	public void setTenCanBoTraKetQua(String tenCanBoTraKetQua) {
		_tenCanBoTraKetQua = tenCanBoTraKetQua;
	}

	@JSON
	public String getChucVuCanBoTraKetQua() {
		return _chucVuCanBoTraKetQua;
	}

	public void setChucVuCanBoTraKetQua(String chucVuCanBoTraKetQua) {
		_chucVuCanBoTraKetQua = chucVuCanBoTraKetQua;
	}

	@JSON
	public String getHoTenNguoiNhanKetQua() {
		return _hoTenNguoiNhanKetQua;
	}

	public void setHoTenNguoiNhanKetQua(String hoTenNguoiNhanKetQua) {
		_hoTenNguoiNhanKetQua = hoTenNguoiNhanKetQua;
	}

	@JSON
	public String getDiaChiThuongTruNguoiNhanKQ() {
		return _diaChiThuongTruNguoiNhanKQ;
	}

	public void setDiaChiThuongTruNguoiNhanKQ(String diaChiThuongTruNguoiNhanKQ) {
		_diaChiThuongTruNguoiNhanKQ = diaChiThuongTruNguoiNhanKQ;
	}

	@JSON
	public String getSoDienThoaiNguoiNhan() {
		return _soDienThoaiNguoiNhan;
	}

	public void setSoDienThoaiNguoiNhan(String soDienThoaiNguoiNhan) {
		_soDienThoaiNguoiNhan = soDienThoaiNguoiNhan;
	}

	@JSON
	public Date getNgayCap() {
		return _ngayCap;
	}

	public void setNgayCap(Date ngayCap) {
		_ngayCap = ngayCap;
	}

	@JSON
	public long getLanCap() {
		return _lanCap;
	}

	public void setLanCap(long lanCap) {
		_lanCap = lanCap;
	}

	@JSON
	public String getTenCoQuanCap() {
		return _tenCoQuanCap;
	}

	public void setTenCoQuanCap(String tenCoQuanCap) {
		_tenCoQuanCap = tenCoQuanCap;
	}

	@JSON
	public Date getHieuLucTuNgay() {
		return _hieuLucTuNgay;
	}

	public void setHieuLucTuNgay(Date hieuLucTuNgay) {
		_hieuLucTuNgay = hieuLucTuNgay;
	}

	@JSON
	public Date getHieuLucDenNgay() {
		return _hieuLucDenNgay;
	}

	public void setHieuLucDenNgay(Date hieuLucDenNgay) {
		_hieuLucDenNgay = hieuLucDenNgay;
	}

	@JSON
	public int getTrangThaiHoSo() {
		return _trangThaiHoSo;
	}

	public void setTrangThaiHoSo(int trangThaiHoSo) {
		_columnBitmask |= TRANGTHAIHOSO_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiHoSo) {
			_setOriginalTrangThaiHoSo = true;

			_originalTrangThaiHoSo = _trangThaiHoSo;
		}

		_trangThaiHoSo = trangThaiHoSo;
	}

	public int getOriginalTrangThaiHoSo() {
		return _originalTrangThaiHoSo;
	}

	@JSON
	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	@JSON
	public String getNguoiTao() {
		return _nguoiTao;
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	@JSON
	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	@JSON
	public String getNguoiSua() {
		return _nguoiSua;
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	@JSON
	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	@JSON
	public Long getThuTucHanhChinhId() {
		return _thuTucHanhChinhId;
	}

	public void setThuTucHanhChinhId(Long thuTucHanhChinhId) {
		_columnBitmask |= THUTUCHANHCHINHID_COLUMN_BITMASK;

		if (!_setOriginalThuTucHanhChinhId) {
			_setOriginalThuTucHanhChinhId = true;

			_originalThuTucHanhChinhId = _thuTucHanhChinhId;
		}

		_thuTucHanhChinhId = thuTucHanhChinhId;
	}

	public Long getOriginalThuTucHanhChinhId() {
		return _originalThuTucHanhChinhId;
	}

	@JSON
	public Long getCongDanNopId() {
		return _congDanNopId;
	}

	public void setCongDanNopId(Long congDanNopId) {
		_columnBitmask |= CONGDANNOPID_COLUMN_BITMASK;

		if (!_setOriginalCongDanNopId) {
			_setOriginalCongDanNopId = true;

			_originalCongDanNopId = _congDanNopId;
		}

		_congDanNopId = congDanNopId;
	}

	public Long getOriginalCongDanNopId() {
		return _originalCongDanNopId;
	}

	@JSON
	public Long getDiaChiThuongTruNguoiNhanKQId() {
		return _diaChiThuongTruNguoiNhanKQId;
	}

	public void setDiaChiThuongTruNguoiNhanKQId(
		Long diaChiThuongTruNguoiNhanKQId) {
		_diaChiThuongTruNguoiNhanKQId = diaChiThuongTruNguoiNhanKQId;
	}

	@JSON
	public Long getCoQuanTiepNhanId() {
		return _coQuanTiepNhanId;
	}

	public void setCoQuanTiepNhanId(Long coQuanTiepNhanId) {
		_columnBitmask |= COQUANTIEPNHANID_COLUMN_BITMASK;

		if (!_setOriginalCoQuanTiepNhanId) {
			_setOriginalCoQuanTiepNhanId = true;

			_originalCoQuanTiepNhanId = _coQuanTiepNhanId;
		}

		_coQuanTiepNhanId = coQuanTiepNhanId;
	}

	public Long getOriginalCoQuanTiepNhanId() {
		return _originalCoQuanTiepNhanId;
	}

	@JSON
	public Long getCanBoTraKetQuaId() {
		return _canBoTraKetQuaId;
	}

	public void setCanBoTraKetQuaId(Long canBoTraKetQuaId) {
		_canBoTraKetQuaId = canBoTraKetQuaId;
	}

	@JSON
	public Long getCanBoTiepNhanId() {
		return _canBoTiepNhanId;
	}

	public void setCanBoTiepNhanId(Long canBoTiepNhanId) {
		_canBoTiepNhanId = canBoTiepNhanId;
	}

	@JSON
	public Long getDiaChiThuongTruNguoiNopId() {
		return _diaChiThuongTruNguoiNopId;
	}

	public void setDiaChiThuongTruNguoiNopId(Long diaChiThuongTruNguoiNopId) {
		_diaChiThuongTruNguoiNopId = diaChiThuongTruNguoiNopId;
	}

	@JSON
	public String getSoDienThoaiDiDongNguoiNop() {
		return _soDienThoaiDiDongNguoiNop;
	}

	public void setSoDienThoaiDiDongNguoiNop(String soDienThoaiDiDongNguoiNop) {
		_columnBitmask |= SODIENTHOAIDIDONGNGUOINOP_COLUMN_BITMASK;

		if (_originalSoDienThoaiDiDongNguoiNop == null) {
			_originalSoDienThoaiDiDongNguoiNop = _soDienThoaiDiDongNguoiNop;
		}

		_soDienThoaiDiDongNguoiNop = soDienThoaiDiDongNguoiNop;
	}

	public String getOriginalSoDienThoaiDiDongNguoiNop() {
		return _originalSoDienThoaiDiDongNguoiNop;
	}

	@JSON
	public Long getPhongBanXuLyHienThoiId() {
		return _phongBanXuLyHienThoiId;
	}

	public void setPhongBanXuLyHienThoiId(Long phongBanXuLyHienThoiId) {
		_phongBanXuLyHienThoiId = phongBanXuLyHienThoiId;
	}

	@JSON
	public String getTenPhongBanXuLyHienThoi() {
		return _tenPhongBanXuLyHienThoi;
	}

	public void setTenPhongBanXuLyHienThoi(String tenPhongBanXuLyHienThoi) {
		_columnBitmask |= TENPHONGBANXULYHIENTHOI_COLUMN_BITMASK;

		if (_originalTenPhongBanXuLyHienThoi == null) {
			_originalTenPhongBanXuLyHienThoi = _tenPhongBanXuLyHienThoi;
		}

		_tenPhongBanXuLyHienThoi = tenPhongBanXuLyHienThoi;
	}

	public String getOriginalTenPhongBanXuLyHienThoi() {
		return _originalTenPhongBanXuLyHienThoi;
	}

	@JSON
	public Long getCanBoXuLyHienThoiId() {
		return _canBoXuLyHienThoiId;
	}

	public void setCanBoXuLyHienThoiId(Long canBoXuLyHienThoiId) {
		_canBoXuLyHienThoiId = canBoXuLyHienThoiId;
	}

	@JSON
	public String getTenCanBoXuLyHienThoi() {
		return _tenCanBoXuLyHienThoi;
	}

	public void setTenCanBoXuLyHienThoi(String tenCanBoXuLyHienThoi) {
		_tenCanBoXuLyHienThoi = tenCanBoXuLyHienThoi;
	}

	@JSON
	public int getDanhGiaKetQua() {
		return _danhGiaKetQua;
	}

	public void setDanhGiaKetQua(int danhGiaKetQua) {
		_danhGiaKetQua = danhGiaKetQua;
	}

	@JSON
	public String getGhiChu() {
		return _ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@JSON
	public Date getNgayKetThucXuLy() {
		return _ngayKetThucXuLy;
	}

	public void setNgayKetThucXuLy(Date ngayKetThucXuLy) {
		_ngayKetThucXuLy = ngayKetThucXuLy;
	}

	@JSON
	public int getLoaiHoSo() {
		return _loaiHoSo;
	}

	public void setLoaiHoSo(int loaiHoSo) {
		_columnBitmask |= LOAIHOSO_COLUMN_BITMASK;

		if (!_setOriginalLoaiHoSo) {
			_setOriginalLoaiHoSo = true;

			_originalLoaiHoSo = _loaiHoSo;
		}

		_loaiHoSo = loaiHoSo;
	}

	public int getOriginalLoaiHoSo() {
		return _originalLoaiHoSo;
	}

	@JSON
	public int getYeuCauHuyHoSo() {
		return _yeuCauHuyHoSo;
	}

	public void setYeuCauHuyHoSo(int yeuCauHuyHoSo) {
		_yeuCauHuyHoSo = yeuCauHuyHoSo;
	}

	@JSON
	public String getMaSoBienNhan() {
		return _maSoBienNhan;
	}

	public void setMaSoBienNhan(String maSoBienNhan) {
		_columnBitmask |= MASOBIENNHAN_COLUMN_BITMASK;

		if (_originalMaSoBienNhan == null) {
			_originalMaSoBienNhan = _maSoBienNhan;
		}

		_maSoBienNhan = maSoBienNhan;
	}

	public String getOriginalMaSoBienNhan() {
		return _originalMaSoBienNhan;
	}

	@JSON
	public String getTenBangChuaHoSo() {
		return _tenBangChuaHoSo;
	}

	public void setTenBangChuaHoSo(String tenBangChuaHoSo) {
		_tenBangChuaHoSo = tenBangChuaHoSo;
	}

	@JSON
	public String getChuSoHuu() {
		return _chuSoHuu;
	}

	public void setChuSoHuu(String chuSoHuu) {
		_chuSoHuu = chuSoHuu;
	}

	@JSON
	public int getSoBoHoSo() {
		return _soBoHoSo;
	}

	public void setSoBoHoSo(int soBoHoSo) {
		_soBoHoSo = soBoHoSo;
	}

	@JSON
	public int getLePhi() {
		return _lePhi;
	}

	public void setLePhi(int lePhi) {
		_lePhi = lePhi;
	}

	@JSON
	public int getPhiHoSo() {
		return _phiHoSo;
	}

	public void setPhiHoSo(int phiHoSo) {
		_phiHoSo = phiHoSo;
	}

	@JSON
	public String getTrichYeu() {
		return _trichYeu;
	}

	public void setTrichYeu(String trichYeu) {
		_trichYeu = trichYeu;
	}

	@JSON
	public Date getNgayHenTBThue() {
		return _ngayHenTBThue;
	}

	public void setNgayHenTBThue(Date ngayHenTBThue) {
		_ngayHenTBThue = ngayHenTBThue;
	}

	@JSON
	public String getEmailNguoiNop() {
		return _emailNguoiNop;
	}

	public void setEmailNguoiNop(String emailNguoiNop) {
		_emailNguoiNop = emailNguoiNop;
	}

	@JSON
	public String getMaUngDung() {
		return _maUngDung;
	}

	public void setMaUngDung(String maUngDung) {
		_maUngDung = maUngDung;
	}

	@JSON
	public int getDaGuiGiayHen() {
		return _daGuiGiayHen;
	}

	public void setDaGuiGiayHen(int daGuiGiayHen) {
		_daGuiGiayHen = daGuiGiayHen;
	}

	@JSON
	public String getNguoiDaiDienPhapLuat() {
		return _nguoiDaiDienPhapLuat;
	}

	public void setNguoiDaiDienPhapLuat(String nguoiDaiDienPhapLuat) {
		_nguoiDaiDienPhapLuat = nguoiDaiDienPhapLuat;
	}

	@JSON
	public Long getNguoiDaiDienPhapLuatId() {
		return _nguoiDaiDienPhapLuatId;
	}

	public void setNguoiDaiDienPhapLuatId(Long nguoiDaiDienPhapLuatId) {
		_nguoiDaiDienPhapLuatId = nguoiDaiDienPhapLuatId;
	}

	@JSON
	public int getChuyenSangMotCua() {
		return _chuyenSangMotCua;
	}

	public void setChuyenSangMotCua(int chuyenSangMotCua) {
		_chuyenSangMotCua = chuyenSangMotCua;
	}

	@JSON
	public Long getDoiTuongCanXuLyId() {
		return _doiTuongCanXuLyId;
	}

	public void setDoiTuongCanXuLyId(Long doiTuongCanXuLyId) {
		_doiTuongCanXuLyId = doiTuongCanXuLyId;
	}

	@JSON
	public String getLyDo() {
		if (_lyDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDo;
		}
	}

	public void setLyDo(String lyDo) {
		_lyDo = lyDo;
	}

	@JSON
	public String getMoTaThanhPhanHoSo() {
		if (_moTaThanhPhanHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTaThanhPhanHoSo;
		}
	}

	public void setMoTaThanhPhanHoSo(String moTaThanhPhanHoSo) {
		_moTaThanhPhanHoSo = moTaThanhPhanHoSo;
	}

	@JSON
	public String getLienKetThanhPhanHoSo() {
		if (_lienKetThanhPhanHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _lienKetThanhPhanHoSo;
		}
	}

	public void setLienKetThanhPhanHoSo(String lienKetThanhPhanHoSo) {
		_lienKetThanhPhanHoSo = lienKetThanhPhanHoSo;
	}

	@JSON
	public Long getSoNgayXuLy() {
		return _soNgayXuLy;
	}

	public void setSoNgayXuLy(Long soNgayXuLy) {
		_soNgayXuLy = soNgayXuLy;
	}

	@JSON
	public Long getDaTraKetQuaTrucTuyen() {
		return _daTraKetQuaTrucTuyen;
	}

	public void setDaTraKetQuaTrucTuyen(Long daTraKetQuaTrucTuyen) {
		_daTraKetQuaTrucTuyen = daTraKetQuaTrucTuyen;
	}

	@JSON
	public String getEMailNguoiNhan() {
		if (_eMailNguoiNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _eMailNguoiNhan;
		}
	}

	public void setEMailNguoiNhan(String eMailNguoiNhan) {
		_eMailNguoiNhan = eMailNguoiNhan;
	}

	@JSON
	public Date getNgaySinhNguoiNhan() {
		return _ngaySinhNguoiNhan;
	}

	public void setNgaySinhNguoiNhan(Date ngaySinhNguoiNhan) {
		_ngaySinhNguoiNhan = ngaySinhNguoiNhan;
	}

	@JSON
	public String getDienThoiCoDinhNguoiNhan() {
		if (_dienThoiCoDinhNguoiNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoiCoDinhNguoiNhan;
		}
	}

	public void setDienThoiCoDinhNguoiNhan(String dienThoiCoDinhNguoiNhan) {
		_dienThoiCoDinhNguoiNhan = dienThoiCoDinhNguoiNhan;
	}

	@JSON
	public String getCmndNguoiNhan() {
		if (_cmndNguoiNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _cmndNguoiNhan;
		}
	}

	public void setCmndNguoiNhan(String cmndNguoiNhan) {
		_cmndNguoiNhan = cmndNguoiNhan;
	}

	@JSON
	public int getGioiTinh() {
		return _gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		_gioiTinh = gioiTinh;
	}

	@JSON
	public boolean getDungXuLy() {
		return _dungXuLy;
	}

	public boolean isDungXuLy() {
		return _dungXuLy;
	}

	public void setDungXuLy(boolean dungXuLy) {
		_dungXuLy = dungXuLy;
	}

	@JSON
	public Date getNgayBoSung() {
		return _ngayBoSung;
	}

	public void setNgayBoSung(Date ngayBoSung) {
		_ngayBoSung = ngayBoSung;
	}

	@JSON
	public String getGhiChuGiayToDinhKem() {
		if (_ghiChuGiayToDinhKem == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChuGiayToDinhKem;
		}
	}

	public void setGhiChuGiayToDinhKem(String ghiChuGiayToDinhKem) {
		_ghiChuGiayToDinhKem = ghiChuGiayToDinhKem;
	}

	@JSON
	public int getDaDangKyNhanSMS() {
		return _daDangKyNhanSMS;
	}

	public void setDaDangKyNhanSMS(int daDangKyNhanSMS) {
		_daDangKyNhanSMS = daDangKyNhanSMS;
	}

	@JSON
	public int getDaDangKyChuyenPhatNhanh() {
		return _daDangKyChuyenPhatNhanh;
	}

	public void setDaDangKyChuyenPhatNhanh(int daDangKyChuyenPhatNhanh) {
		_daDangKyChuyenPhatNhanh = daDangKyChuyenPhatNhanh;
	}

	@JSON
	public String getDiaChiChuHoSo() {
		if (_diaChiChuHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiChuHoSo;
		}
	}

	public void setDiaChiChuHoSo(String diaChiChuHoSo) {
		_diaChiChuHoSo = diaChiChuHoSo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public HoSoTTHCCong toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (HoSoTTHCCong)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					HoSoTTHCCong.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		HoSoTTHCCongImpl hoSoTTHCCongImpl = new HoSoTTHCCongImpl();

		hoSoTTHCCongImpl.setId(getId());
		hoSoTTHCCongImpl.setMaSoHoSo(getMaSoHoSo());
		hoSoTTHCCongImpl.setNgayNopHoSo(getNgayNopHoSo());
		hoSoTTHCCongImpl.setNgayNhanHoSo(getNgayNhanHoSo());
		hoSoTTHCCongImpl.setTenCoQuanTiepNhan(getTenCoQuanTiepNhan());
		hoSoTTHCCongImpl.setTenThuTucHanhChinh(getTenThuTucHanhChinh());
		hoSoTTHCCongImpl.setNgayHenTraKetQua(getNgayHenTraKetQua());
		hoSoTTHCCongImpl.setNgayTraKetQua(getNgayTraKetQua());
		hoSoTTHCCongImpl.setNgayNopHoSoGoc(getNgayNopHoSoGoc());
		hoSoTTHCCongImpl.setNgayHenNopHoSoGoc(getNgayHenNopHoSoGoc());
		hoSoTTHCCongImpl.setTenCanBoTiepNhan(getTenCanBoTiepNhan());
		hoSoTTHCCongImpl.setChucVuCanBoTiepNhan(getChucVuCanBoTiepNhan());
		hoSoTTHCCongImpl.setHoTenNguoiNopHoSo(getHoTenNguoiNopHoSo());
		hoSoTTHCCongImpl.setDiaChiThuongTruNguoiNop(getDiaChiThuongTruNguoiNop());
		hoSoTTHCCongImpl.setSoDienThoaiCoDinhNguoiNop(getSoDienThoaiCoDinhNguoiNop());
		hoSoTTHCCongImpl.setTenCanBoTraKetQua(getTenCanBoTraKetQua());
		hoSoTTHCCongImpl.setChucVuCanBoTraKetQua(getChucVuCanBoTraKetQua());
		hoSoTTHCCongImpl.setHoTenNguoiNhanKetQua(getHoTenNguoiNhanKetQua());
		hoSoTTHCCongImpl.setDiaChiThuongTruNguoiNhanKQ(getDiaChiThuongTruNguoiNhanKQ());
		hoSoTTHCCongImpl.setSoDienThoaiNguoiNhan(getSoDienThoaiNguoiNhan());
		hoSoTTHCCongImpl.setNgayCap(getNgayCap());
		hoSoTTHCCongImpl.setLanCap(getLanCap());
		hoSoTTHCCongImpl.setTenCoQuanCap(getTenCoQuanCap());
		hoSoTTHCCongImpl.setHieuLucTuNgay(getHieuLucTuNgay());
		hoSoTTHCCongImpl.setHieuLucDenNgay(getHieuLucDenNgay());
		hoSoTTHCCongImpl.setTrangThaiHoSo(getTrangThaiHoSo());
		hoSoTTHCCongImpl.setDaXoa(getDaXoa());
		hoSoTTHCCongImpl.setNguoiTao(getNguoiTao());
		hoSoTTHCCongImpl.setNgayTao(getNgayTao());
		hoSoTTHCCongImpl.setNguoiSua(getNguoiSua());
		hoSoTTHCCongImpl.setNgaySua(getNgaySua());
		hoSoTTHCCongImpl.setThuTucHanhChinhId(getThuTucHanhChinhId());
		hoSoTTHCCongImpl.setCongDanNopId(getCongDanNopId());
		hoSoTTHCCongImpl.setDiaChiThuongTruNguoiNhanKQId(getDiaChiThuongTruNguoiNhanKQId());
		hoSoTTHCCongImpl.setCoQuanTiepNhanId(getCoQuanTiepNhanId());
		hoSoTTHCCongImpl.setCanBoTraKetQuaId(getCanBoTraKetQuaId());
		hoSoTTHCCongImpl.setCanBoTiepNhanId(getCanBoTiepNhanId());
		hoSoTTHCCongImpl.setDiaChiThuongTruNguoiNopId(getDiaChiThuongTruNguoiNopId());
		hoSoTTHCCongImpl.setSoDienThoaiDiDongNguoiNop(getSoDienThoaiDiDongNguoiNop());
		hoSoTTHCCongImpl.setPhongBanXuLyHienThoiId(getPhongBanXuLyHienThoiId());
		hoSoTTHCCongImpl.setTenPhongBanXuLyHienThoi(getTenPhongBanXuLyHienThoi());
		hoSoTTHCCongImpl.setCanBoXuLyHienThoiId(getCanBoXuLyHienThoiId());
		hoSoTTHCCongImpl.setTenCanBoXuLyHienThoi(getTenCanBoXuLyHienThoi());
		hoSoTTHCCongImpl.setDanhGiaKetQua(getDanhGiaKetQua());
		hoSoTTHCCongImpl.setGhiChu(getGhiChu());
		hoSoTTHCCongImpl.setNgayKetThucXuLy(getNgayKetThucXuLy());
		hoSoTTHCCongImpl.setLoaiHoSo(getLoaiHoSo());
		hoSoTTHCCongImpl.setYeuCauHuyHoSo(getYeuCauHuyHoSo());
		hoSoTTHCCongImpl.setMaSoBienNhan(getMaSoBienNhan());
		hoSoTTHCCongImpl.setTenBangChuaHoSo(getTenBangChuaHoSo());
		hoSoTTHCCongImpl.setChuSoHuu(getChuSoHuu());
		hoSoTTHCCongImpl.setSoBoHoSo(getSoBoHoSo());
		hoSoTTHCCongImpl.setLePhi(getLePhi());
		hoSoTTHCCongImpl.setPhiHoSo(getPhiHoSo());
		hoSoTTHCCongImpl.setTrichYeu(getTrichYeu());
		hoSoTTHCCongImpl.setNgayHenTBThue(getNgayHenTBThue());
		hoSoTTHCCongImpl.setEmailNguoiNop(getEmailNguoiNop());
		hoSoTTHCCongImpl.setMaUngDung(getMaUngDung());
		hoSoTTHCCongImpl.setDaGuiGiayHen(getDaGuiGiayHen());
		hoSoTTHCCongImpl.setNguoiDaiDienPhapLuat(getNguoiDaiDienPhapLuat());
		hoSoTTHCCongImpl.setNguoiDaiDienPhapLuatId(getNguoiDaiDienPhapLuatId());
		hoSoTTHCCongImpl.setChuyenSangMotCua(getChuyenSangMotCua());
		hoSoTTHCCongImpl.setDoiTuongCanXuLyId(getDoiTuongCanXuLyId());
		hoSoTTHCCongImpl.setLyDo(getLyDo());
		hoSoTTHCCongImpl.setMoTaThanhPhanHoSo(getMoTaThanhPhanHoSo());
		hoSoTTHCCongImpl.setLienKetThanhPhanHoSo(getLienKetThanhPhanHoSo());
		hoSoTTHCCongImpl.setSoNgayXuLy(getSoNgayXuLy());
		hoSoTTHCCongImpl.setDaTraKetQuaTrucTuyen(getDaTraKetQuaTrucTuyen());
		hoSoTTHCCongImpl.setEMailNguoiNhan(getEMailNguoiNhan());
		hoSoTTHCCongImpl.setNgaySinhNguoiNhan(getNgaySinhNguoiNhan());
		hoSoTTHCCongImpl.setDienThoiCoDinhNguoiNhan(getDienThoiCoDinhNguoiNhan());
		hoSoTTHCCongImpl.setCmndNguoiNhan(getCmndNguoiNhan());
		hoSoTTHCCongImpl.setGioiTinh(getGioiTinh());
		hoSoTTHCCongImpl.setDungXuLy(getDungXuLy());
		hoSoTTHCCongImpl.setNgayBoSung(getNgayBoSung());
		hoSoTTHCCongImpl.setGhiChuGiayToDinhKem(getGhiChuGiayToDinhKem());
		hoSoTTHCCongImpl.setDaDangKyNhanSMS(getDaDangKyNhanSMS());
		hoSoTTHCCongImpl.setDaDangKyChuyenPhatNhanh(getDaDangKyChuyenPhatNhanh());
		hoSoTTHCCongImpl.setDiaChiChuHoSo(getDiaChiChuHoSo());

		hoSoTTHCCongImpl.resetOriginalValues();

		return hoSoTTHCCongImpl;
	}

	public int compareTo(HoSoTTHCCong hoSoTTHCCong) {
		int value = 0;

		if (getId() < hoSoTTHCCong.getId()) {
			value = -1;
		}
		else if (getId() > hoSoTTHCCong.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		HoSoTTHCCong hoSoTTHCCong = null;

		try {
			hoSoTTHCCong = (HoSoTTHCCong)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = hoSoTTHCCong.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		HoSoTTHCCongModelImpl hoSoTTHCCongModelImpl = this;

		hoSoTTHCCongModelImpl._originalMaSoHoSo = hoSoTTHCCongModelImpl._maSoHoSo;

		hoSoTTHCCongModelImpl._originalTenCoQuanTiepNhan = hoSoTTHCCongModelImpl._tenCoQuanTiepNhan;

		hoSoTTHCCongModelImpl._originalTenThuTucHanhChinh = hoSoTTHCCongModelImpl._tenThuTucHanhChinh;

		hoSoTTHCCongModelImpl._originalHoTenNguoiNopHoSo = hoSoTTHCCongModelImpl._hoTenNguoiNopHoSo;

		hoSoTTHCCongModelImpl._originalSoDienThoaiCoDinhNguoiNop = hoSoTTHCCongModelImpl._soDienThoaiCoDinhNguoiNop;

		hoSoTTHCCongModelImpl._originalTrangThaiHoSo = hoSoTTHCCongModelImpl._trangThaiHoSo;

		hoSoTTHCCongModelImpl._setOriginalTrangThaiHoSo = false;

		hoSoTTHCCongModelImpl._originalDaXoa = hoSoTTHCCongModelImpl._daXoa;

		hoSoTTHCCongModelImpl._setOriginalDaXoa = false;

		hoSoTTHCCongModelImpl._originalThuTucHanhChinhId = hoSoTTHCCongModelImpl._thuTucHanhChinhId;

		hoSoTTHCCongModelImpl._setOriginalThuTucHanhChinhId = false;

		hoSoTTHCCongModelImpl._originalCongDanNopId = hoSoTTHCCongModelImpl._congDanNopId;

		hoSoTTHCCongModelImpl._setOriginalCongDanNopId = false;

		hoSoTTHCCongModelImpl._originalCoQuanTiepNhanId = hoSoTTHCCongModelImpl._coQuanTiepNhanId;

		hoSoTTHCCongModelImpl._setOriginalCoQuanTiepNhanId = false;

		hoSoTTHCCongModelImpl._originalSoDienThoaiDiDongNguoiNop = hoSoTTHCCongModelImpl._soDienThoaiDiDongNguoiNop;

		hoSoTTHCCongModelImpl._originalTenPhongBanXuLyHienThoi = hoSoTTHCCongModelImpl._tenPhongBanXuLyHienThoi;

		hoSoTTHCCongModelImpl._originalLoaiHoSo = hoSoTTHCCongModelImpl._loaiHoSo;

		hoSoTTHCCongModelImpl._setOriginalLoaiHoSo = false;

		hoSoTTHCCongModelImpl._originalMaSoBienNhan = hoSoTTHCCongModelImpl._maSoBienNhan;

		hoSoTTHCCongModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<HoSoTTHCCong> toCacheModel() {
		HoSoTTHCCongCacheModel hoSoTTHCCongCacheModel = new HoSoTTHCCongCacheModel();

		hoSoTTHCCongCacheModel.id = getId();

		hoSoTTHCCongCacheModel.maSoHoSo = getMaSoHoSo();

		String maSoHoSo = hoSoTTHCCongCacheModel.maSoHoSo;

		if ((maSoHoSo != null) && (maSoHoSo.length() == 0)) {
			hoSoTTHCCongCacheModel.maSoHoSo = null;
		}

		Date ngayNopHoSo = getNgayNopHoSo();

		if (ngayNopHoSo != null) {
			hoSoTTHCCongCacheModel.ngayNopHoSo = ngayNopHoSo.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayNopHoSo = Long.MIN_VALUE;
		}

		Date ngayNhanHoSo = getNgayNhanHoSo();

		if (ngayNhanHoSo != null) {
			hoSoTTHCCongCacheModel.ngayNhanHoSo = ngayNhanHoSo.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayNhanHoSo = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.tenCoQuanTiepNhan = getTenCoQuanTiepNhan();

		String tenCoQuanTiepNhan = hoSoTTHCCongCacheModel.tenCoQuanTiepNhan;

		if ((tenCoQuanTiepNhan != null) && (tenCoQuanTiepNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.tenCoQuanTiepNhan = null;
		}

		hoSoTTHCCongCacheModel.tenThuTucHanhChinh = getTenThuTucHanhChinh();

		String tenThuTucHanhChinh = hoSoTTHCCongCacheModel.tenThuTucHanhChinh;

		if ((tenThuTucHanhChinh != null) && (tenThuTucHanhChinh.length() == 0)) {
			hoSoTTHCCongCacheModel.tenThuTucHanhChinh = null;
		}

		Date ngayHenTraKetQua = getNgayHenTraKetQua();

		if (ngayHenTraKetQua != null) {
			hoSoTTHCCongCacheModel.ngayHenTraKetQua = ngayHenTraKetQua.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayHenTraKetQua = Long.MIN_VALUE;
		}

		Date ngayTraKetQua = getNgayTraKetQua();

		if (ngayTraKetQua != null) {
			hoSoTTHCCongCacheModel.ngayTraKetQua = ngayTraKetQua.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayTraKetQua = Long.MIN_VALUE;
		}

		Date ngayNopHoSoGoc = getNgayNopHoSoGoc();

		if (ngayNopHoSoGoc != null) {
			hoSoTTHCCongCacheModel.ngayNopHoSoGoc = ngayNopHoSoGoc.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayNopHoSoGoc = Long.MIN_VALUE;
		}

		Date ngayHenNopHoSoGoc = getNgayHenNopHoSoGoc();

		if (ngayHenNopHoSoGoc != null) {
			hoSoTTHCCongCacheModel.ngayHenNopHoSoGoc = ngayHenNopHoSoGoc.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayHenNopHoSoGoc = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.tenCanBoTiepNhan = getTenCanBoTiepNhan();

		String tenCanBoTiepNhan = hoSoTTHCCongCacheModel.tenCanBoTiepNhan;

		if ((tenCanBoTiepNhan != null) && (tenCanBoTiepNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.tenCanBoTiepNhan = null;
		}

		hoSoTTHCCongCacheModel.chucVuCanBoTiepNhan = getChucVuCanBoTiepNhan();

		String chucVuCanBoTiepNhan = hoSoTTHCCongCacheModel.chucVuCanBoTiepNhan;

		if ((chucVuCanBoTiepNhan != null) &&
				(chucVuCanBoTiepNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.chucVuCanBoTiepNhan = null;
		}

		hoSoTTHCCongCacheModel.hoTenNguoiNopHoSo = getHoTenNguoiNopHoSo();

		String hoTenNguoiNopHoSo = hoSoTTHCCongCacheModel.hoTenNguoiNopHoSo;

		if ((hoTenNguoiNopHoSo != null) && (hoTenNguoiNopHoSo.length() == 0)) {
			hoSoTTHCCongCacheModel.hoTenNguoiNopHoSo = null;
		}

		hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNop = getDiaChiThuongTruNguoiNop();

		String diaChiThuongTruNguoiNop = hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNop;

		if ((diaChiThuongTruNguoiNop != null) &&
				(diaChiThuongTruNguoiNop.length() == 0)) {
			hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNop = null;
		}

		hoSoTTHCCongCacheModel.soDienThoaiCoDinhNguoiNop = getSoDienThoaiCoDinhNguoiNop();

		String soDienThoaiCoDinhNguoiNop = hoSoTTHCCongCacheModel.soDienThoaiCoDinhNguoiNop;

		if ((soDienThoaiCoDinhNguoiNop != null) &&
				(soDienThoaiCoDinhNguoiNop.length() == 0)) {
			hoSoTTHCCongCacheModel.soDienThoaiCoDinhNguoiNop = null;
		}

		hoSoTTHCCongCacheModel.tenCanBoTraKetQua = getTenCanBoTraKetQua();

		String tenCanBoTraKetQua = hoSoTTHCCongCacheModel.tenCanBoTraKetQua;

		if ((tenCanBoTraKetQua != null) && (tenCanBoTraKetQua.length() == 0)) {
			hoSoTTHCCongCacheModel.tenCanBoTraKetQua = null;
		}

		hoSoTTHCCongCacheModel.chucVuCanBoTraKetQua = getChucVuCanBoTraKetQua();

		String chucVuCanBoTraKetQua = hoSoTTHCCongCacheModel.chucVuCanBoTraKetQua;

		if ((chucVuCanBoTraKetQua != null) &&
				(chucVuCanBoTraKetQua.length() == 0)) {
			hoSoTTHCCongCacheModel.chucVuCanBoTraKetQua = null;
		}

		hoSoTTHCCongCacheModel.hoTenNguoiNhanKetQua = getHoTenNguoiNhanKetQua();

		String hoTenNguoiNhanKetQua = hoSoTTHCCongCacheModel.hoTenNguoiNhanKetQua;

		if ((hoTenNguoiNhanKetQua != null) &&
				(hoTenNguoiNhanKetQua.length() == 0)) {
			hoSoTTHCCongCacheModel.hoTenNguoiNhanKetQua = null;
		}

		hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNhanKQ = getDiaChiThuongTruNguoiNhanKQ();

		String diaChiThuongTruNguoiNhanKQ = hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNhanKQ;

		if ((diaChiThuongTruNguoiNhanKQ != null) &&
				(diaChiThuongTruNguoiNhanKQ.length() == 0)) {
			hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNhanKQ = null;
		}

		hoSoTTHCCongCacheModel.soDienThoaiNguoiNhan = getSoDienThoaiNguoiNhan();

		String soDienThoaiNguoiNhan = hoSoTTHCCongCacheModel.soDienThoaiNguoiNhan;

		if ((soDienThoaiNguoiNhan != null) &&
				(soDienThoaiNguoiNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.soDienThoaiNguoiNhan = null;
		}

		Date ngayCap = getNgayCap();

		if (ngayCap != null) {
			hoSoTTHCCongCacheModel.ngayCap = ngayCap.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayCap = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.lanCap = getLanCap();

		hoSoTTHCCongCacheModel.tenCoQuanCap = getTenCoQuanCap();

		String tenCoQuanCap = hoSoTTHCCongCacheModel.tenCoQuanCap;

		if ((tenCoQuanCap != null) && (tenCoQuanCap.length() == 0)) {
			hoSoTTHCCongCacheModel.tenCoQuanCap = null;
		}

		Date hieuLucTuNgay = getHieuLucTuNgay();

		if (hieuLucTuNgay != null) {
			hoSoTTHCCongCacheModel.hieuLucTuNgay = hieuLucTuNgay.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.hieuLucTuNgay = Long.MIN_VALUE;
		}

		Date hieuLucDenNgay = getHieuLucDenNgay();

		if (hieuLucDenNgay != null) {
			hoSoTTHCCongCacheModel.hieuLucDenNgay = hieuLucDenNgay.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.hieuLucDenNgay = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.trangThaiHoSo = getTrangThaiHoSo();

		hoSoTTHCCongCacheModel.daXoa = getDaXoa();

		hoSoTTHCCongCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = hoSoTTHCCongCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			hoSoTTHCCongCacheModel.nguoiTao = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			hoSoTTHCCongCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayTao = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = hoSoTTHCCongCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			hoSoTTHCCongCacheModel.nguoiSua = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			hoSoTTHCCongCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngaySua = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.thuTucHanhChinhId = getThuTucHanhChinhId();

		hoSoTTHCCongCacheModel.congDanNopId = getCongDanNopId();

		hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNhanKQId = getDiaChiThuongTruNguoiNhanKQId();

		hoSoTTHCCongCacheModel.coQuanTiepNhanId = getCoQuanTiepNhanId();

		hoSoTTHCCongCacheModel.canBoTraKetQuaId = getCanBoTraKetQuaId();

		hoSoTTHCCongCacheModel.canBoTiepNhanId = getCanBoTiepNhanId();

		hoSoTTHCCongCacheModel.diaChiThuongTruNguoiNopId = getDiaChiThuongTruNguoiNopId();

		hoSoTTHCCongCacheModel.soDienThoaiDiDongNguoiNop = getSoDienThoaiDiDongNguoiNop();

		String soDienThoaiDiDongNguoiNop = hoSoTTHCCongCacheModel.soDienThoaiDiDongNguoiNop;

		if ((soDienThoaiDiDongNguoiNop != null) &&
				(soDienThoaiDiDongNguoiNop.length() == 0)) {
			hoSoTTHCCongCacheModel.soDienThoaiDiDongNguoiNop = null;
		}

		hoSoTTHCCongCacheModel.phongBanXuLyHienThoiId = getPhongBanXuLyHienThoiId();

		hoSoTTHCCongCacheModel.tenPhongBanXuLyHienThoi = getTenPhongBanXuLyHienThoi();

		String tenPhongBanXuLyHienThoi = hoSoTTHCCongCacheModel.tenPhongBanXuLyHienThoi;

		if ((tenPhongBanXuLyHienThoi != null) &&
				(tenPhongBanXuLyHienThoi.length() == 0)) {
			hoSoTTHCCongCacheModel.tenPhongBanXuLyHienThoi = null;
		}

		hoSoTTHCCongCacheModel.canBoXuLyHienThoiId = getCanBoXuLyHienThoiId();

		hoSoTTHCCongCacheModel.tenCanBoXuLyHienThoi = getTenCanBoXuLyHienThoi();

		String tenCanBoXuLyHienThoi = hoSoTTHCCongCacheModel.tenCanBoXuLyHienThoi;

		if ((tenCanBoXuLyHienThoi != null) &&
				(tenCanBoXuLyHienThoi.length() == 0)) {
			hoSoTTHCCongCacheModel.tenCanBoXuLyHienThoi = null;
		}

		hoSoTTHCCongCacheModel.danhGiaKetQua = getDanhGiaKetQua();

		hoSoTTHCCongCacheModel.ghiChu = getGhiChu();

		String ghiChu = hoSoTTHCCongCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			hoSoTTHCCongCacheModel.ghiChu = null;
		}

		Date ngayKetThucXuLy = getNgayKetThucXuLy();

		if (ngayKetThucXuLy != null) {
			hoSoTTHCCongCacheModel.ngayKetThucXuLy = ngayKetThucXuLy.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayKetThucXuLy = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.loaiHoSo = getLoaiHoSo();

		hoSoTTHCCongCacheModel.yeuCauHuyHoSo = getYeuCauHuyHoSo();

		hoSoTTHCCongCacheModel.maSoBienNhan = getMaSoBienNhan();

		String maSoBienNhan = hoSoTTHCCongCacheModel.maSoBienNhan;

		if ((maSoBienNhan != null) && (maSoBienNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.maSoBienNhan = null;
		}

		hoSoTTHCCongCacheModel.tenBangChuaHoSo = getTenBangChuaHoSo();

		String tenBangChuaHoSo = hoSoTTHCCongCacheModel.tenBangChuaHoSo;

		if ((tenBangChuaHoSo != null) && (tenBangChuaHoSo.length() == 0)) {
			hoSoTTHCCongCacheModel.tenBangChuaHoSo = null;
		}

		hoSoTTHCCongCacheModel.chuSoHuu = getChuSoHuu();

		String chuSoHuu = hoSoTTHCCongCacheModel.chuSoHuu;

		if ((chuSoHuu != null) && (chuSoHuu.length() == 0)) {
			hoSoTTHCCongCacheModel.chuSoHuu = null;
		}

		hoSoTTHCCongCacheModel.soBoHoSo = getSoBoHoSo();

		hoSoTTHCCongCacheModel.lePhi = getLePhi();

		hoSoTTHCCongCacheModel.phiHoSo = getPhiHoSo();

		hoSoTTHCCongCacheModel.trichYeu = getTrichYeu();

		String trichYeu = hoSoTTHCCongCacheModel.trichYeu;

		if ((trichYeu != null) && (trichYeu.length() == 0)) {
			hoSoTTHCCongCacheModel.trichYeu = null;
		}

		Date ngayHenTBThue = getNgayHenTBThue();

		if (ngayHenTBThue != null) {
			hoSoTTHCCongCacheModel.ngayHenTBThue = ngayHenTBThue.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayHenTBThue = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.emailNguoiNop = getEmailNguoiNop();

		String emailNguoiNop = hoSoTTHCCongCacheModel.emailNguoiNop;

		if ((emailNguoiNop != null) && (emailNguoiNop.length() == 0)) {
			hoSoTTHCCongCacheModel.emailNguoiNop = null;
		}

		hoSoTTHCCongCacheModel.maUngDung = getMaUngDung();

		String maUngDung = hoSoTTHCCongCacheModel.maUngDung;

		if ((maUngDung != null) && (maUngDung.length() == 0)) {
			hoSoTTHCCongCacheModel.maUngDung = null;
		}

		hoSoTTHCCongCacheModel.daGuiGiayHen = getDaGuiGiayHen();

		hoSoTTHCCongCacheModel.nguoiDaiDienPhapLuat = getNguoiDaiDienPhapLuat();

		String nguoiDaiDienPhapLuat = hoSoTTHCCongCacheModel.nguoiDaiDienPhapLuat;

		if ((nguoiDaiDienPhapLuat != null) &&
				(nguoiDaiDienPhapLuat.length() == 0)) {
			hoSoTTHCCongCacheModel.nguoiDaiDienPhapLuat = null;
		}

		hoSoTTHCCongCacheModel.nguoiDaiDienPhapLuatId = getNguoiDaiDienPhapLuatId();

		hoSoTTHCCongCacheModel.chuyenSangMotCua = getChuyenSangMotCua();

		hoSoTTHCCongCacheModel.doiTuongCanXuLyId = getDoiTuongCanXuLyId();

		hoSoTTHCCongCacheModel.lyDo = getLyDo();

		String lyDo = hoSoTTHCCongCacheModel.lyDo;

		if ((lyDo != null) && (lyDo.length() == 0)) {
			hoSoTTHCCongCacheModel.lyDo = null;
		}

		hoSoTTHCCongCacheModel.moTaThanhPhanHoSo = getMoTaThanhPhanHoSo();

		String moTaThanhPhanHoSo = hoSoTTHCCongCacheModel.moTaThanhPhanHoSo;

		if ((moTaThanhPhanHoSo != null) && (moTaThanhPhanHoSo.length() == 0)) {
			hoSoTTHCCongCacheModel.moTaThanhPhanHoSo = null;
		}

		hoSoTTHCCongCacheModel.lienKetThanhPhanHoSo = getLienKetThanhPhanHoSo();

		String lienKetThanhPhanHoSo = hoSoTTHCCongCacheModel.lienKetThanhPhanHoSo;

		if ((lienKetThanhPhanHoSo != null) &&
				(lienKetThanhPhanHoSo.length() == 0)) {
			hoSoTTHCCongCacheModel.lienKetThanhPhanHoSo = null;
		}

		hoSoTTHCCongCacheModel.soNgayXuLy = getSoNgayXuLy();

		hoSoTTHCCongCacheModel.daTraKetQuaTrucTuyen = getDaTraKetQuaTrucTuyen();

		hoSoTTHCCongCacheModel.eMailNguoiNhan = getEMailNguoiNhan();

		String eMailNguoiNhan = hoSoTTHCCongCacheModel.eMailNguoiNhan;

		if ((eMailNguoiNhan != null) && (eMailNguoiNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.eMailNguoiNhan = null;
		}

		Date ngaySinhNguoiNhan = getNgaySinhNguoiNhan();

		if (ngaySinhNguoiNhan != null) {
			hoSoTTHCCongCacheModel.ngaySinhNguoiNhan = ngaySinhNguoiNhan.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngaySinhNguoiNhan = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.dienThoiCoDinhNguoiNhan = getDienThoiCoDinhNguoiNhan();

		String dienThoiCoDinhNguoiNhan = hoSoTTHCCongCacheModel.dienThoiCoDinhNguoiNhan;

		if ((dienThoiCoDinhNguoiNhan != null) &&
				(dienThoiCoDinhNguoiNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.dienThoiCoDinhNguoiNhan = null;
		}

		hoSoTTHCCongCacheModel.cmndNguoiNhan = getCmndNguoiNhan();

		String cmndNguoiNhan = hoSoTTHCCongCacheModel.cmndNguoiNhan;

		if ((cmndNguoiNhan != null) && (cmndNguoiNhan.length() == 0)) {
			hoSoTTHCCongCacheModel.cmndNguoiNhan = null;
		}

		hoSoTTHCCongCacheModel.gioiTinh = getGioiTinh();

		hoSoTTHCCongCacheModel.dungXuLy = getDungXuLy();

		Date ngayBoSung = getNgayBoSung();

		if (ngayBoSung != null) {
			hoSoTTHCCongCacheModel.ngayBoSung = ngayBoSung.getTime();
		}
		else {
			hoSoTTHCCongCacheModel.ngayBoSung = Long.MIN_VALUE;
		}

		hoSoTTHCCongCacheModel.ghiChuGiayToDinhKem = getGhiChuGiayToDinhKem();

		String ghiChuGiayToDinhKem = hoSoTTHCCongCacheModel.ghiChuGiayToDinhKem;

		if ((ghiChuGiayToDinhKem != null) &&
				(ghiChuGiayToDinhKem.length() == 0)) {
			hoSoTTHCCongCacheModel.ghiChuGiayToDinhKem = null;
		}

		hoSoTTHCCongCacheModel.daDangKyNhanSMS = getDaDangKyNhanSMS();

		hoSoTTHCCongCacheModel.daDangKyChuyenPhatNhanh = getDaDangKyChuyenPhatNhanh();

		hoSoTTHCCongCacheModel.diaChiChuHoSo = getDiaChiChuHoSo();

		String diaChiChuHoSo = hoSoTTHCCongCacheModel.diaChiChuHoSo;

		if ((diaChiChuHoSo != null) && (diaChiChuHoSo.length() == 0)) {
			hoSoTTHCCongCacheModel.diaChiChuHoSo = null;
		}

		return hoSoTTHCCongCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(159);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", maSoHoSo=");
		sb.append(getMaSoHoSo());
		sb.append(", ngayNopHoSo=");
		sb.append(getNgayNopHoSo());
		sb.append(", ngayNhanHoSo=");
		sb.append(getNgayNhanHoSo());
		sb.append(", tenCoQuanTiepNhan=");
		sb.append(getTenCoQuanTiepNhan());
		sb.append(", tenThuTucHanhChinh=");
		sb.append(getTenThuTucHanhChinh());
		sb.append(", ngayHenTraKetQua=");
		sb.append(getNgayHenTraKetQua());
		sb.append(", ngayTraKetQua=");
		sb.append(getNgayTraKetQua());
		sb.append(", ngayNopHoSoGoc=");
		sb.append(getNgayNopHoSoGoc());
		sb.append(", ngayHenNopHoSoGoc=");
		sb.append(getNgayHenNopHoSoGoc());
		sb.append(", tenCanBoTiepNhan=");
		sb.append(getTenCanBoTiepNhan());
		sb.append(", chucVuCanBoTiepNhan=");
		sb.append(getChucVuCanBoTiepNhan());
		sb.append(", hoTenNguoiNopHoSo=");
		sb.append(getHoTenNguoiNopHoSo());
		sb.append(", diaChiThuongTruNguoiNop=");
		sb.append(getDiaChiThuongTruNguoiNop());
		sb.append(", soDienThoaiCoDinhNguoiNop=");
		sb.append(getSoDienThoaiCoDinhNguoiNop());
		sb.append(", tenCanBoTraKetQua=");
		sb.append(getTenCanBoTraKetQua());
		sb.append(", chucVuCanBoTraKetQua=");
		sb.append(getChucVuCanBoTraKetQua());
		sb.append(", hoTenNguoiNhanKetQua=");
		sb.append(getHoTenNguoiNhanKetQua());
		sb.append(", diaChiThuongTruNguoiNhanKQ=");
		sb.append(getDiaChiThuongTruNguoiNhanKQ());
		sb.append(", soDienThoaiNguoiNhan=");
		sb.append(getSoDienThoaiNguoiNhan());
		sb.append(", ngayCap=");
		sb.append(getNgayCap());
		sb.append(", lanCap=");
		sb.append(getLanCap());
		sb.append(", tenCoQuanCap=");
		sb.append(getTenCoQuanCap());
		sb.append(", hieuLucTuNgay=");
		sb.append(getHieuLucTuNgay());
		sb.append(", hieuLucDenNgay=");
		sb.append(getHieuLucDenNgay());
		sb.append(", trangThaiHoSo=");
		sb.append(getTrangThaiHoSo());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", thuTucHanhChinhId=");
		sb.append(getThuTucHanhChinhId());
		sb.append(", congDanNopId=");
		sb.append(getCongDanNopId());
		sb.append(", diaChiThuongTruNguoiNhanKQId=");
		sb.append(getDiaChiThuongTruNguoiNhanKQId());
		sb.append(", coQuanTiepNhanId=");
		sb.append(getCoQuanTiepNhanId());
		sb.append(", canBoTraKetQuaId=");
		sb.append(getCanBoTraKetQuaId());
		sb.append(", canBoTiepNhanId=");
		sb.append(getCanBoTiepNhanId());
		sb.append(", diaChiThuongTruNguoiNopId=");
		sb.append(getDiaChiThuongTruNguoiNopId());
		sb.append(", soDienThoaiDiDongNguoiNop=");
		sb.append(getSoDienThoaiDiDongNguoiNop());
		sb.append(", phongBanXuLyHienThoiId=");
		sb.append(getPhongBanXuLyHienThoiId());
		sb.append(", tenPhongBanXuLyHienThoi=");
		sb.append(getTenPhongBanXuLyHienThoi());
		sb.append(", canBoXuLyHienThoiId=");
		sb.append(getCanBoXuLyHienThoiId());
		sb.append(", tenCanBoXuLyHienThoi=");
		sb.append(getTenCanBoXuLyHienThoi());
		sb.append(", danhGiaKetQua=");
		sb.append(getDanhGiaKetQua());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", ngayKetThucXuLy=");
		sb.append(getNgayKetThucXuLy());
		sb.append(", loaiHoSo=");
		sb.append(getLoaiHoSo());
		sb.append(", yeuCauHuyHoSo=");
		sb.append(getYeuCauHuyHoSo());
		sb.append(", maSoBienNhan=");
		sb.append(getMaSoBienNhan());
		sb.append(", tenBangChuaHoSo=");
		sb.append(getTenBangChuaHoSo());
		sb.append(", chuSoHuu=");
		sb.append(getChuSoHuu());
		sb.append(", soBoHoSo=");
		sb.append(getSoBoHoSo());
		sb.append(", lePhi=");
		sb.append(getLePhi());
		sb.append(", phiHoSo=");
		sb.append(getPhiHoSo());
		sb.append(", trichYeu=");
		sb.append(getTrichYeu());
		sb.append(", ngayHenTBThue=");
		sb.append(getNgayHenTBThue());
		sb.append(", emailNguoiNop=");
		sb.append(getEmailNguoiNop());
		sb.append(", maUngDung=");
		sb.append(getMaUngDung());
		sb.append(", daGuiGiayHen=");
		sb.append(getDaGuiGiayHen());
		sb.append(", nguoiDaiDienPhapLuat=");
		sb.append(getNguoiDaiDienPhapLuat());
		sb.append(", nguoiDaiDienPhapLuatId=");
		sb.append(getNguoiDaiDienPhapLuatId());
		sb.append(", chuyenSangMotCua=");
		sb.append(getChuyenSangMotCua());
		sb.append(", doiTuongCanXuLyId=");
		sb.append(getDoiTuongCanXuLyId());
		sb.append(", lyDo=");
		sb.append(getLyDo());
		sb.append(", moTaThanhPhanHoSo=");
		sb.append(getMoTaThanhPhanHoSo());
		sb.append(", lienKetThanhPhanHoSo=");
		sb.append(getLienKetThanhPhanHoSo());
		sb.append(", soNgayXuLy=");
		sb.append(getSoNgayXuLy());
		sb.append(", daTraKetQuaTrucTuyen=");
		sb.append(getDaTraKetQuaTrucTuyen());
		sb.append(", eMailNguoiNhan=");
		sb.append(getEMailNguoiNhan());
		sb.append(", ngaySinhNguoiNhan=");
		sb.append(getNgaySinhNguoiNhan());
		sb.append(", dienThoiCoDinhNguoiNhan=");
		sb.append(getDienThoiCoDinhNguoiNhan());
		sb.append(", cmndNguoiNhan=");
		sb.append(getCmndNguoiNhan());
		sb.append(", gioiTinh=");
		sb.append(getGioiTinh());
		sb.append(", dungXuLy=");
		sb.append(getDungXuLy());
		sb.append(", ngayBoSung=");
		sb.append(getNgayBoSung());
		sb.append(", ghiChuGiayToDinhKem=");
		sb.append(getGhiChuGiayToDinhKem());
		sb.append(", daDangKyNhanSMS=");
		sb.append(getDaDangKyNhanSMS());
		sb.append(", daDangKyChuyenPhatNhanh=");
		sb.append(getDaDangKyChuyenPhatNhanh());
		sb.append(", diaChiChuHoSo=");
		sb.append(getDiaChiChuHoSo());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(241);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.hosohcc.model.HoSoTTHCCong");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaSoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayNopHoSo</column-name><column-value><![CDATA[");
		sb.append(getNgayNopHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayNhanHoSo</column-name><column-value><![CDATA[");
		sb.append(getNgayNhanHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCoQuanTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getTenCoQuanTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenThuTucHanhChinh</column-name><column-value><![CDATA[");
		sb.append(getTenThuTucHanhChinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHenTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getNgayHenTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getNgayTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayNopHoSoGoc</column-name><column-value><![CDATA[");
		sb.append(getNgayNopHoSoGoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHenNopHoSoGoc</column-name><column-value><![CDATA[");
		sb.append(getNgayHenNopHoSoGoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCanBoTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getTenCanBoTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chucVuCanBoTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getChucVuCanBoTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenNguoiNopHoSo</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiNopHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDienThoaiCoDinhNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDienThoaiCoDinhNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCanBoTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getTenCanBoTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chucVuCanBoTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getChucVuCanBoTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenNguoiNhanKetQua</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiNhanKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruNguoiNhanKQ</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruNguoiNhanKQ());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDienThoaiNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getSoDienThoaiNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCap</column-name><column-value><![CDATA[");
		sb.append(getNgayCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lanCap</column-name><column-value><![CDATA[");
		sb.append(getLanCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCoQuanCap</column-name><column-value><![CDATA[");
		sb.append(getTenCoQuanCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hieuLucTuNgay</column-name><column-value><![CDATA[");
		sb.append(getHieuLucTuNgay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hieuLucDenNgay</column-name><column-value><![CDATA[");
		sb.append(getHieuLucDenNgay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiHoSo</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getThuTucHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>congDanNopId</column-name><column-value><![CDATA[");
		sb.append(getCongDanNopId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruNguoiNhanKQId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruNguoiNhanKQId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanTiepNhanId</column-name><column-value><![CDATA[");
		sb.append(getCoQuanTiepNhanId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>canBoTraKetQuaId</column-name><column-value><![CDATA[");
		sb.append(getCanBoTraKetQuaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>canBoTiepNhanId</column-name><column-value><![CDATA[");
		sb.append(getCanBoTiepNhanId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruNguoiNopId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruNguoiNopId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDienThoaiDiDongNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDienThoaiDiDongNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phongBanXuLyHienThoiId</column-name><column-value><![CDATA[");
		sb.append(getPhongBanXuLyHienThoiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenPhongBanXuLyHienThoi</column-name><column-value><![CDATA[");
		sb.append(getTenPhongBanXuLyHienThoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>canBoXuLyHienThoiId</column-name><column-value><![CDATA[");
		sb.append(getCanBoXuLyHienThoiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCanBoXuLyHienThoi</column-name><column-value><![CDATA[");
		sb.append(getTenCanBoXuLyHienThoi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>danhGiaKetQua</column-name><column-value><![CDATA[");
		sb.append(getDanhGiaKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKetThucXuLy</column-name><column-value><![CDATA[");
		sb.append(getNgayKetThucXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHoSo</column-name><column-value><![CDATA[");
		sb.append(getLoaiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yeuCauHuyHoSo</column-name><column-value><![CDATA[");
		sb.append(getYeuCauHuyHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoBienNhan</column-name><column-value><![CDATA[");
		sb.append(getMaSoBienNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenBangChuaHoSo</column-name><column-value><![CDATA[");
		sb.append(getTenBangChuaHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chuSoHuu</column-name><column-value><![CDATA[");
		sb.append(getChuSoHuu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soBoHoSo</column-name><column-value><![CDATA[");
		sb.append(getSoBoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lePhi</column-name><column-value><![CDATA[");
		sb.append(getLePhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phiHoSo</column-name><column-value><![CDATA[");
		sb.append(getPhiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trichYeu</column-name><column-value><![CDATA[");
		sb.append(getTrichYeu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHenTBThue</column-name><column-value><![CDATA[");
		sb.append(getNgayHenTBThue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getEmailNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maUngDung</column-name><column-value><![CDATA[");
		sb.append(getMaUngDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daGuiGiayHen</column-name><column-value><![CDATA[");
		sb.append(getDaGuiGiayHen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiDaiDienPhapLuat</column-name><column-value><![CDATA[");
		sb.append(getNguoiDaiDienPhapLuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiDaiDienPhapLuatId</column-name><column-value><![CDATA[");
		sb.append(getNguoiDaiDienPhapLuatId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chuyenSangMotCua</column-name><column-value><![CDATA[");
		sb.append(getChuyenSangMotCua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>doiTuongCanXuLyId</column-name><column-value><![CDATA[");
		sb.append(getDoiTuongCanXuLyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDo</column-name><column-value><![CDATA[");
		sb.append(getLyDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTaThanhPhanHoSo</column-name><column-value><![CDATA[");
		sb.append(getMoTaThanhPhanHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lienKetThanhPhanHoSo</column-name><column-value><![CDATA[");
		sb.append(getLienKetThanhPhanHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNgayXuLy</column-name><column-value><![CDATA[");
		sb.append(getSoNgayXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daTraKetQuaTrucTuyen</column-name><column-value><![CDATA[");
		sb.append(getDaTraKetQuaTrucTuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eMailNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getEMailNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySinhNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getNgaySinhNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoiCoDinhNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getDienThoiCoDinhNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cmndNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getCmndNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinh</column-name><column-value><![CDATA[");
		sb.append(getGioiTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dungXuLy</column-name><column-value><![CDATA[");
		sb.append(getDungXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayBoSung</column-name><column-value><![CDATA[");
		sb.append(getNgayBoSung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChuGiayToDinhKem</column-name><column-value><![CDATA[");
		sb.append(getGhiChuGiayToDinhKem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daDangKyNhanSMS</column-name><column-value><![CDATA[");
		sb.append(getDaDangKyNhanSMS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daDangKyChuyenPhatNhanh</column-name><column-value><![CDATA[");
		sb.append(getDaDangKyChuyenPhatNhanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiChuHoSo</column-name><column-value><![CDATA[");
		sb.append(getDiaChiChuHoSo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = HoSoTTHCCong.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			HoSoTTHCCong.class
		};
	private long _id;
	private String _maSoHoSo;
	private String _originalMaSoHoSo;
	private Date _ngayNopHoSo;
	private Date _ngayNhanHoSo;
	private String _tenCoQuanTiepNhan;
	private String _originalTenCoQuanTiepNhan;
	private String _tenThuTucHanhChinh;
	private String _originalTenThuTucHanhChinh;
	private Date _ngayHenTraKetQua;
	private Date _ngayTraKetQua;
	private Date _ngayNopHoSoGoc;
	private Date _ngayHenNopHoSoGoc;
	private String _tenCanBoTiepNhan;
	private String _chucVuCanBoTiepNhan;
	private String _hoTenNguoiNopHoSo;
	private String _originalHoTenNguoiNopHoSo;
	private String _diaChiThuongTruNguoiNop;
	private String _soDienThoaiCoDinhNguoiNop;
	private String _originalSoDienThoaiCoDinhNguoiNop;
	private String _tenCanBoTraKetQua;
	private String _chucVuCanBoTraKetQua;
	private String _hoTenNguoiNhanKetQua;
	private String _diaChiThuongTruNguoiNhanKQ;
	private String _soDienThoaiNguoiNhan;
	private Date _ngayCap;
	private long _lanCap;
	private String _tenCoQuanCap;
	private Date _hieuLucTuNgay;
	private Date _hieuLucDenNgay;
	private int _trangThaiHoSo;
	private int _originalTrangThaiHoSo;
	private boolean _setOriginalTrangThaiHoSo;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private String _nguoiTao;
	private Date _ngayTao;
	private String _nguoiSua;
	private Date _ngaySua;
	private Long _thuTucHanhChinhId;
	private Long _originalThuTucHanhChinhId;
	private boolean _setOriginalThuTucHanhChinhId;
	private Long _congDanNopId;
	private Long _originalCongDanNopId;
	private boolean _setOriginalCongDanNopId;
	private Long _diaChiThuongTruNguoiNhanKQId;
	private Long _coQuanTiepNhanId;
	private Long _originalCoQuanTiepNhanId;
	private boolean _setOriginalCoQuanTiepNhanId;
	private Long _canBoTraKetQuaId;
	private Long _canBoTiepNhanId;
	private Long _diaChiThuongTruNguoiNopId;
	private String _soDienThoaiDiDongNguoiNop;
	private String _originalSoDienThoaiDiDongNguoiNop;
	private Long _phongBanXuLyHienThoiId;
	private String _tenPhongBanXuLyHienThoi;
	private String _originalTenPhongBanXuLyHienThoi;
	private Long _canBoXuLyHienThoiId;
	private String _tenCanBoXuLyHienThoi;
	private int _danhGiaKetQua;
	private String _ghiChu;
	private Date _ngayKetThucXuLy;
	private int _loaiHoSo;
	private int _originalLoaiHoSo;
	private boolean _setOriginalLoaiHoSo;
	private int _yeuCauHuyHoSo;
	private String _maSoBienNhan;
	private String _originalMaSoBienNhan;
	private String _tenBangChuaHoSo;
	private String _chuSoHuu;
	private int _soBoHoSo;
	private int _lePhi;
	private int _phiHoSo;
	private String _trichYeu;
	private Date _ngayHenTBThue;
	private String _emailNguoiNop;
	private String _maUngDung;
	private int _daGuiGiayHen;
	private String _nguoiDaiDienPhapLuat;
	private Long _nguoiDaiDienPhapLuatId;
	private int _chuyenSangMotCua;
	private Long _doiTuongCanXuLyId;
	private String _lyDo;
	private String _moTaThanhPhanHoSo;
	private String _lienKetThanhPhanHoSo;
	private Long _soNgayXuLy;
	private Long _daTraKetQuaTrucTuyen;
	private String _eMailNguoiNhan;
	private Date _ngaySinhNguoiNhan;
	private String _dienThoiCoDinhNguoiNhan;
	private String _cmndNguoiNhan;
	private int _gioiTinh;
	private boolean _dungXuLy;
	private Date _ngayBoSung;
	private String _ghiChuGiayToDinhKem;
	private int _daDangKyNhanSMS;
	private int _daDangKyChuyenPhatNhanh;
	private String _diaChiChuHoSo;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private HoSoTTHCCong _escapedModelProxy;
}