/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.dlms.dao.danhmucgiaypheplaixe.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DonViGtvt service. Represents a row in the &quot;DLMS_DONVIGTVT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.DonViGtvtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.DonViGtvtImpl}.
 * </p>
 *
 * @author AnhNT
 * @see DonViGtvt
 * @see org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.DonViGtvtImpl
 * @see org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.DonViGtvtModelImpl
 * @generated
 */
public interface DonViGtvtModel extends BaseModel<DonViGtvt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a don vi gtvt model instance should use the {@link DonViGtvt} interface instead.
	 */

	/**
	 * Returns the primary key of this don vi gtvt.
	 *
	 * @return the primary key of this don vi gtvt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this don vi gtvt.
	 *
	 * @param primaryKey the primary key of this don vi gtvt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this don vi gtvt.
	 *
	 * @return the ID of this don vi gtvt
	 */
	public long getId();

	/**
	 * Sets the ID of this don vi gtvt.
	 *
	 * @param id the ID of this don vi gtvt
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this don vi gtvt.
	 *
	 * @return the ma of this don vi gtvt
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this don vi gtvt.
	 *
	 * @param ma the ma of this don vi gtvt
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this don vi gtvt.
	 *
	 * @return the ten of this don vi gtvt
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this don vi gtvt.
	 *
	 * @param ten the ten of this don vi gtvt
	 */
	public void setTen(String ten);

	/**
	 * Returns the co quan ql of this don vi gtvt.
	 *
	 * @return the co quan ql of this don vi gtvt
	 */
	@AutoEscape
	public String getCoQuanQl();

	/**
	 * Sets the co quan ql of this don vi gtvt.
	 *
	 * @param coQuanQl the co quan ql of this don vi gtvt
	 */
	public void setCoQuanQl(String coQuanQl);

	/**
	 * Returns the dien thoai of this don vi gtvt.
	 *
	 * @return the dien thoai of this don vi gtvt
	 */
	@AutoEscape
	public String getDienThoai();

	/**
	 * Sets the dien thoai of this don vi gtvt.
	 *
	 * @param dienThoai the dien thoai of this don vi gtvt
	 */
	public void setDienThoai(String dienThoai);

	/**
	 * Returns the fax of this don vi gtvt.
	 *
	 * @return the fax of this don vi gtvt
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this don vi gtvt.
	 *
	 * @param fax the fax of this don vi gtvt
	 */
	public void setFax(String fax);

	/**
	 * Returns the dia chi of this don vi gtvt.
	 *
	 * @return the dia chi of this don vi gtvt
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this don vi gtvt.
	 *
	 * @param diaChi the dia chi of this don vi gtvt
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the lanh dao of this don vi gtvt.
	 *
	 * @return the lanh dao of this don vi gtvt
	 */
	@AutoEscape
	public String getLanhDao();

	/**
	 * Sets the lanh dao of this don vi gtvt.
	 *
	 * @param lanhDao the lanh dao of this don vi gtvt
	 */
	public void setLanhDao(String lanhDao);

	/**
	 * Returns the ngay tao of this don vi gtvt.
	 *
	 * @return the ngay tao of this don vi gtvt
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this don vi gtvt.
	 *
	 * @param ngayTao the ngay tao of this don vi gtvt
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this don vi gtvt.
	 *
	 * @return the ngay sua of this don vi gtvt
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this don vi gtvt.
	 *
	 * @param ngaySua the ngay sua of this don vi gtvt
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi tao of this don vi gtvt.
	 *
	 * @return the nguoi tao of this don vi gtvt
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this don vi gtvt.
	 *
	 * @param nguoiTao the nguoi tao of this don vi gtvt
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this don vi gtvt.
	 *
	 * @return the nguoi sua of this don vi gtvt
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this don vi gtvt.
	 *
	 * @param nguoiSua the nguoi sua of this don vi gtvt
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the xoa of this don vi gtvt.
	 *
	 * @return the xoa of this don vi gtvt
	 */
	public int getXoa();

	/**
	 * Sets the xoa of this don vi gtvt.
	 *
	 * @param xoa the xoa of this don vi gtvt
	 */
	public void setXoa(int xoa);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DonViGtvt donViGtvt);

	public int hashCode();

	public CacheModel<DonViGtvt> toCacheModel();

	public DonViGtvt toEscapedModel();

	public String toString();

	public String toXmlString();
}