/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.dlms.dao.danhmucgiaypheplaixe.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LyDoCapDoiCapLaiGPLX service. Represents a row in the &quot;DLMS_LYDOCAPDOICAPLAI&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.LyDoCapDoiCapLaiGPLXModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.LyDoCapDoiCapLaiGPLXImpl}.
 * </p>
 *
 * @author AnhNT
 * @see LyDoCapDoiCapLaiGPLX
 * @see org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.LyDoCapDoiCapLaiGPLXImpl
 * @see org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl.LyDoCapDoiCapLaiGPLXModelImpl
 * @generated
 */
public interface LyDoCapDoiCapLaiGPLXModel extends BaseModel<LyDoCapDoiCapLaiGPLX> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ly do cap doi cap lai g p l x model instance should use the {@link LyDoCapDoiCapLaiGPLX} interface instead.
	 */

	/**
	 * Returns the primary key of this ly do cap doi cap lai g p l x.
	 *
	 * @return the primary key of this ly do cap doi cap lai g p l x
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ly do cap doi cap lai g p l x.
	 *
	 * @param primaryKey the primary key of this ly do cap doi cap lai g p l x
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ly do cap doi cap lai g p l x.
	 *
	 * @return the ID of this ly do cap doi cap lai g p l x
	 */
	public long getId();

	/**
	 * Sets the ID of this ly do cap doi cap lai g p l x.
	 *
	 * @param id the ID of this ly do cap doi cap lai g p l x
	 */
	public void setId(long id);

	/**
	 * Returns the ly do of this ly do cap doi cap lai g p l x.
	 *
	 * @return the ly do of this ly do cap doi cap lai g p l x
	 */
	@AutoEscape
	public String getLyDo();

	/**
	 * Sets the ly do of this ly do cap doi cap lai g p l x.
	 *
	 * @param lyDo the ly do of this ly do cap doi cap lai g p l x
	 */
	public void setLyDo(String lyDo);

	/**
	 * Returns the ngay tao of this ly do cap doi cap lai g p l x.
	 *
	 * @return the ngay tao of this ly do cap doi cap lai g p l x
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ly do cap doi cap lai g p l x.
	 *
	 * @param ngayTao the ngay tao of this ly do cap doi cap lai g p l x
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this ly do cap doi cap lai g p l x.
	 *
	 * @return the ngay sua of this ly do cap doi cap lai g p l x
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this ly do cap doi cap lai g p l x.
	 *
	 * @param ngaySua the ngay sua of this ly do cap doi cap lai g p l x
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi tao of this ly do cap doi cap lai g p l x.
	 *
	 * @return the nguoi tao of this ly do cap doi cap lai g p l x
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this ly do cap doi cap lai g p l x.
	 *
	 * @param nguoiTao the nguoi tao of this ly do cap doi cap lai g p l x
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this ly do cap doi cap lai g p l x.
	 *
	 * @return the nguoi sua of this ly do cap doi cap lai g p l x
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this ly do cap doi cap lai g p l x.
	 *
	 * @param nguoiSua the nguoi sua of this ly do cap doi cap lai g p l x
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the xoa of this ly do cap doi cap lai g p l x.
	 *
	 * @return the xoa of this ly do cap doi cap lai g p l x
	 */
	public int getXoa();

	/**
	 * Sets the xoa of this ly do cap doi cap lai g p l x.
	 *
	 * @param xoa the xoa of this ly do cap doi cap lai g p l x
	 */
	public void setXoa(int xoa);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LyDoCapDoiCapLaiGPLX lyDoCapDoiCapLaiGPLX);

	public int hashCode();

	public CacheModel<LyDoCapDoiCapLaiGPLX> toCacheModel();

	public LyDoCapDoiCapLaiGPLX toEscapedModel();

	public String toString();

	public String toXmlString();
}