/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DoanhNghiep service. Represents a row in the &quot;BRMS_DOANHNGHIEP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.dn.model.impl.DoanhNghiepModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.dn.model.impl.DoanhNghiepImpl}.
 * </p>
 *
 * @author Liemnn
 * @see DoanhNghiep
 * @see org.oep.cmon.dao.dn.model.impl.DoanhNghiepImpl
 * @see org.oep.cmon.dao.dn.model.impl.DoanhNghiepModelImpl
 * @generated
 */
public interface DoanhNghiepModel extends BaseModel<DoanhNghiep> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doanh nghiep model instance should use the {@link DoanhNghiep} interface instead.
	 */

	/**
	 * Returns the primary key of this doanh nghiep.
	 *
	 * @return the primary key of this doanh nghiep
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doanh nghiep.
	 *
	 * @param primaryKey the primary key of this doanh nghiep
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this doanh nghiep.
	 *
	 * @return the ID of this doanh nghiep
	 */
	public long getId();

	/**
	 * Sets the ID of this doanh nghiep.
	 *
	 * @param id the ID of this doanh nghiep
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this doanh nghiep.
	 *
	 * @return the ma of this doanh nghiep
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this doanh nghiep.
	 *
	 * @param ma the ma of this doanh nghiep
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this doanh nghiep.
	 *
	 * @return the ten of this doanh nghiep
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this doanh nghiep.
	 *
	 * @param ten the ten of this doanh nghiep
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma so thue of this doanh nghiep.
	 *
	 * @return the ma so thue of this doanh nghiep
	 */
	@AutoEscape
	public String getMaSoThue();

	/**
	 * Sets the ma so thue of this doanh nghiep.
	 *
	 * @param maSoThue the ma so thue of this doanh nghiep
	 */
	public void setMaSoThue(String maSoThue);

	/**
	 * Returns the ten tieng nuoc ngoai of this doanh nghiep.
	 *
	 * @return the ten tieng nuoc ngoai of this doanh nghiep
	 */
	@AutoEscape
	public String getTenTiengNuocNgoai();

	/**
	 * Sets the ten tieng nuoc ngoai of this doanh nghiep.
	 *
	 * @param tenTiengNuocNgoai the ten tieng nuoc ngoai of this doanh nghiep
	 */
	public void setTenTiengNuocNgoai(String tenTiengNuocNgoai);

	/**
	 * Returns the ten viet tat of this doanh nghiep.
	 *
	 * @return the ten viet tat of this doanh nghiep
	 */
	@AutoEscape
	public String getTenVietTat();

	/**
	 * Sets the ten viet tat of this doanh nghiep.
	 *
	 * @param tenVietTat the ten viet tat of this doanh nghiep
	 */
	public void setTenVietTat(String tenVietTat);

	/**
	 * Returns the dia chi doanh nghiep of this doanh nghiep.
	 *
	 * @return the dia chi doanh nghiep of this doanh nghiep
	 */
	@AutoEscape
	public String getDiaChiDoanhNghiep();

	/**
	 * Sets the dia chi doanh nghiep of this doanh nghiep.
	 *
	 * @param diaChiDoanhNghiep the dia chi doanh nghiep of this doanh nghiep
	 */
	public void setDiaChiDoanhNghiep(String diaChiDoanhNghiep);

	/**
	 * Returns the dien thoai doanh nghiep of this doanh nghiep.
	 *
	 * @return the dien thoai doanh nghiep of this doanh nghiep
	 */
	@AutoEscape
	public String getDienThoaiDoanhNghiep();

	/**
	 * Sets the dien thoai doanh nghiep of this doanh nghiep.
	 *
	 * @param dienThoaiDoanhNghiep the dien thoai doanh nghiep of this doanh nghiep
	 */
	public void setDienThoaiDoanhNghiep(String dienThoaiDoanhNghiep);

	/**
	 * Returns the fax of this doanh nghiep.
	 *
	 * @return the fax of this doanh nghiep
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this doanh nghiep.
	 *
	 * @param fax the fax of this doanh nghiep
	 */
	public void setFax(String fax);

	/**
	 * Returns the email doanh nghiep of this doanh nghiep.
	 *
	 * @return the email doanh nghiep of this doanh nghiep
	 */
	@AutoEscape
	public String getEmailDoanhNghiep();

	/**
	 * Sets the email doanh nghiep of this doanh nghiep.
	 *
	 * @param emailDoanhNghiep the email doanh nghiep of this doanh nghiep
	 */
	public void setEmailDoanhNghiep(String emailDoanhNghiep);

	/**
	 * Returns the website of this doanh nghiep.
	 *
	 * @return the website of this doanh nghiep
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this doanh nghiep.
	 *
	 * @param website the website of this doanh nghiep
	 */
	public void setWebsite(String website);

	/**
	 * Returns the tong so von of this doanh nghiep.
	 *
	 * @return the tong so von of this doanh nghiep
	 */
	public long getTongSoVon();

	/**
	 * Sets the tong so von of this doanh nghiep.
	 *
	 * @param tongSoVon the tong so von of this doanh nghiep
	 */
	public void setTongSoVon(long tongSoVon);

	/**
	 * Returns the mo ta nganh nghe kinh doanh of this doanh nghiep.
	 *
	 * @return the mo ta nganh nghe kinh doanh of this doanh nghiep
	 */
	@AutoEscape
	public String getMoTaNganhNgheKinhDoanh();

	/**
	 * Sets the mo ta nganh nghe kinh doanh of this doanh nghiep.
	 *
	 * @param moTaNganhNgheKinhDoanh the mo ta nganh nghe kinh doanh of this doanh nghiep
	 */
	public void setMoTaNganhNgheKinhDoanh(String moTaNganhNgheKinhDoanh);

	/**
	 * Returns the so g c n d k k d of this doanh nghiep.
	 *
	 * @return the so g c n d k k d of this doanh nghiep
	 */
	@AutoEscape
	public String getSoGCNDKKD();

	/**
	 * Sets the so g c n d k k d of this doanh nghiep.
	 *
	 * @param soGCNDKKD the so g c n d k k d of this doanh nghiep
	 */
	public void setSoGCNDKKD(String soGCNDKKD);

	/**
	 * Returns the ngay cap g c n d k k d of this doanh nghiep.
	 *
	 * @return the ngay cap g c n d k k d of this doanh nghiep
	 */
	public Date getNgayCapGCNDKKD();

	/**
	 * Sets the ngay cap g c n d k k d of this doanh nghiep.
	 *
	 * @param ngayCapGCNDKKD the ngay cap g c n d k k d of this doanh nghiep
	 */
	public void setNgayCapGCNDKKD(Date ngayCapGCNDKKD);

	/**
	 * Returns the noi luu tru ID of this doanh nghiep.
	 *
	 * @return the noi luu tru ID of this doanh nghiep
	 */
	public long getNoiLuuTruId();

	/**
	 * Sets the noi luu tru ID of this doanh nghiep.
	 *
	 * @param noiLuuTruId the noi luu tru ID of this doanh nghiep
	 */
	public void setNoiLuuTruId(long noiLuuTruId);

	/**
	 * Returns the ngay dieu le duoc thong qua of this doanh nghiep.
	 *
	 * @return the ngay dieu le duoc thong qua of this doanh nghiep
	 */
	public Date getNgayDieuLeDuocThongQua();

	/**
	 * Sets the ngay dieu le duoc thong qua of this doanh nghiep.
	 *
	 * @param ngayDieuLeDuocThongQua the ngay dieu le duoc thong qua of this doanh nghiep
	 */
	public void setNgayDieuLeDuocThongQua(Date ngayDieuLeDuocThongQua);

	/**
	 * Returns the ten chi nhanh of this doanh nghiep.
	 *
	 * @return the ten chi nhanh of this doanh nghiep
	 */
	@AutoEscape
	public String getTenChiNhanh();

	/**
	 * Sets the ten chi nhanh of this doanh nghiep.
	 *
	 * @param tenChiNhanh the ten chi nhanh of this doanh nghiep
	 */
	public void setTenChiNhanh(String tenChiNhanh);

	/**
	 * Returns the dia chi chi nhanh of this doanh nghiep.
	 *
	 * @return the dia chi chi nhanh of this doanh nghiep
	 */
	@AutoEscape
	public String getDiaChiChiNhanh();

	/**
	 * Sets the dia chi chi nhanh of this doanh nghiep.
	 *
	 * @param diaChiChiNhanh the dia chi chi nhanh of this doanh nghiep
	 */
	public void setDiaChiChiNhanh(String diaChiChiNhanh);

	/**
	 * Returns the ten van phong dai dien of this doanh nghiep.
	 *
	 * @return the ten van phong dai dien of this doanh nghiep
	 */
	@AutoEscape
	public String getTenVanPhongDaiDien();

	/**
	 * Sets the ten van phong dai dien of this doanh nghiep.
	 *
	 * @param tenVanPhongDaiDien the ten van phong dai dien of this doanh nghiep
	 */
	public void setTenVanPhongDaiDien(String tenVanPhongDaiDien);

	/**
	 * Returns the dia chi van phong dai dien of this doanh nghiep.
	 *
	 * @return the dia chi van phong dai dien of this doanh nghiep
	 */
	@AutoEscape
	public String getDiaChiVanPhongDaiDien();

	/**
	 * Sets the dia chi van phong dai dien of this doanh nghiep.
	 *
	 * @param diaChiVanPhongDaiDien the dia chi van phong dai dien of this doanh nghiep
	 */
	public void setDiaChiVanPhongDaiDien(String diaChiVanPhongDaiDien);

	/**
	 * Returns the ngay bat dau tam ngung of this doanh nghiep.
	 *
	 * @return the ngay bat dau tam ngung of this doanh nghiep
	 */
	public Date getNgayBatDauTamNgung();

	/**
	 * Sets the ngay bat dau tam ngung of this doanh nghiep.
	 *
	 * @param ngayBatDauTamNgung the ngay bat dau tam ngung of this doanh nghiep
	 */
	public void setNgayBatDauTamNgung(Date ngayBatDauTamNgung);

	/**
	 * Returns the ngay ket thuc tam ngung of this doanh nghiep.
	 *
	 * @return the ngay ket thuc tam ngung of this doanh nghiep
	 */
	public Date getNgayKetThucTamNgung();

	/**
	 * Sets the ngay ket thuc tam ngung of this doanh nghiep.
	 *
	 * @param ngayKetThucTamNgung the ngay ket thuc tam ngung of this doanh nghiep
	 */
	public void setNgayKetThucTamNgung(Date ngayKetThucTamNgung);

	/**
	 * Returns the ly do tam ngung of this doanh nghiep.
	 *
	 * @return the ly do tam ngung of this doanh nghiep
	 */
	@AutoEscape
	public String getLyDoTamNgung();

	/**
	 * Sets the ly do tam ngung of this doanh nghiep.
	 *
	 * @param lyDoTamNgung the ly do tam ngung of this doanh nghiep
	 */
	public void setLyDoTamNgung(String lyDoTamNgung);

	/**
	 * Returns the ngay cham dut hoat dong k d of this doanh nghiep.
	 *
	 * @return the ngay cham dut hoat dong k d of this doanh nghiep
	 */
	public Date getNgayChamDutHoatDongKD();

	/**
	 * Sets the ngay cham dut hoat dong k d of this doanh nghiep.
	 *
	 * @param ngayChamDutHoatDongKD the ngay cham dut hoat dong k d of this doanh nghiep
	 */
	public void setNgayChamDutHoatDongKD(Date ngayChamDutHoatDongKD);

	/**
	 * Returns the loai of this doanh nghiep.
	 *
	 * @return the loai of this doanh nghiep
	 */
	public long getLoai();

	/**
	 * Sets the loai of this doanh nghiep.
	 *
	 * @param loai the loai of this doanh nghiep
	 */
	public void setLoai(long loai);

	/**
	 * Returns the dia chi doanh nghiep huyen ID of this doanh nghiep.
	 *
	 * @return the dia chi doanh nghiep huyen ID of this doanh nghiep
	 */
	public Long getDiaChiDoanhNghiepHuyenId();

	/**
	 * Sets the dia chi doanh nghiep huyen ID of this doanh nghiep.
	 *
	 * @param diaChiDoanhNghiepHuyenId the dia chi doanh nghiep huyen ID of this doanh nghiep
	 */
	public void setDiaChiDoanhNghiepHuyenId(Long diaChiDoanhNghiepHuyenId);

	/**
	 * Returns the dia chi doanh nghiep tinh ID of this doanh nghiep.
	 *
	 * @return the dia chi doanh nghiep tinh ID of this doanh nghiep
	 */
	public Long getDiaChiDoanhNghiepTinhId();

	/**
	 * Sets the dia chi doanh nghiep tinh ID of this doanh nghiep.
	 *
	 * @param diaChiDoanhNghiepTinhId the dia chi doanh nghiep tinh ID of this doanh nghiep
	 */
	public void setDiaChiDoanhNghiepTinhId(Long diaChiDoanhNghiepTinhId);

	/**
	 * Returns the dia chi doanh nghiep xa ID of this doanh nghiep.
	 *
	 * @return the dia chi doanh nghiep xa ID of this doanh nghiep
	 */
	public Long getDiaChiDoanhNghiepXaId();

	/**
	 * Sets the dia chi doanh nghiep xa ID of this doanh nghiep.
	 *
	 * @param diaChiDoanhNghiepXaId the dia chi doanh nghiep xa ID of this doanh nghiep
	 */
	public void setDiaChiDoanhNghiepXaId(Long diaChiDoanhNghiepXaId);

	/**
	 * Returns the loai doi tuong ID of this doanh nghiep.
	 *
	 * @return the loai doi tuong ID of this doanh nghiep
	 */
	public Long getLoaiDoiTuongId();

	/**
	 * Sets the loai doi tuong ID of this doanh nghiep.
	 *
	 * @param loaiDoiTuongId the loai doi tuong ID of this doanh nghiep
	 */
	public void setLoaiDoiTuongId(Long loaiDoiTuongId);

	/**
	 * Returns the nguoi dai dien ID of this doanh nghiep.
	 *
	 * @return the nguoi dai dien ID of this doanh nghiep
	 */
	public Long getNguoiDaiDienId();

	/**
	 * Sets the nguoi dai dien ID of this doanh nghiep.
	 *
	 * @param nguoiDaiDienId the nguoi dai dien ID of this doanh nghiep
	 */
	public void setNguoiDaiDienId(Long nguoiDaiDienId);

	/**
	 * Returns the trang thai doanh nghiep ID of this doanh nghiep.
	 *
	 * @return the trang thai doanh nghiep ID of this doanh nghiep
	 */
	public Long getTrangThaiDoanhNghiepId();

	/**
	 * Sets the trang thai doanh nghiep ID of this doanh nghiep.
	 *
	 * @param trangThaiDoanhNghiepId the trang thai doanh nghiep ID of this doanh nghiep
	 */
	public void setTrangThaiDoanhNghiepId(Long trangThaiDoanhNghiepId);

	/**
	 * Returns the von dieu le of this doanh nghiep.
	 *
	 * @return the von dieu le of this doanh nghiep
	 */
	public long getVonDieuLe();

	/**
	 * Sets the von dieu le of this doanh nghiep.
	 *
	 * @param vonDieuLe the von dieu le of this doanh nghiep
	 */
	public void setVonDieuLe(long vonDieuLe);

	/**
	 * Returns the von toi thieu mot xa vien of this doanh nghiep.
	 *
	 * @return the von toi thieu mot xa vien of this doanh nghiep
	 */
	public long getVonToiThieuMotXaVien();

	/**
	 * Sets the von toi thieu mot xa vien of this doanh nghiep.
	 *
	 * @param vonToiThieuMotXaVien the von toi thieu mot xa vien of this doanh nghiep
	 */
	public void setVonToiThieuMotXaVien(long vonToiThieuMotXaVien);

	/**
	 * Returns the ghi chu of this doanh nghiep.
	 *
	 * @return the ghi chu of this doanh nghiep
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this doanh nghiep.
	 *
	 * @param ghiChu the ghi chu of this doanh nghiep
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the quoc gia ID of this doanh nghiep.
	 *
	 * @return the quoc gia ID of this doanh nghiep
	 */
	public Long getQuocGiaId();

	/**
	 * Sets the quoc gia ID of this doanh nghiep.
	 *
	 * @param quocGiaId the quoc gia ID of this doanh nghiep
	 */
	public void setQuocGiaId(Long quocGiaId);

	/**
	 * Returns the co quan cap ID of this doanh nghiep.
	 *
	 * @return the co quan cap ID of this doanh nghiep
	 */
	public Long getCoQuanCapId();

	/**
	 * Sets the co quan cap ID of this doanh nghiep.
	 *
	 * @param coQuanCapId the co quan cap ID of this doanh nghiep
	 */
	public void setCoQuanCapId(Long coQuanCapId);

	/**
	 * Returns the ten co quan cap of this doanh nghiep.
	 *
	 * @return the ten co quan cap of this doanh nghiep
	 */
	public long getTenCoQuanCap();

	/**
	 * Sets the ten co quan cap of this doanh nghiep.
	 *
	 * @param tenCoQuanCap the ten co quan cap of this doanh nghiep
	 */
	public void setTenCoQuanCap(long tenCoQuanCap);

	/**
	 * Returns the so lan dieu chinh of this doanh nghiep.
	 *
	 * @return the so lan dieu chinh of this doanh nghiep
	 */
	@AutoEscape
	public String getSoLanDieuChinh();

	/**
	 * Sets the so lan dieu chinh of this doanh nghiep.
	 *
	 * @param soLanDieuChinh the so lan dieu chinh of this doanh nghiep
	 */
	public void setSoLanDieuChinh(String soLanDieuChinh);

	/**
	 * Returns the ngay dieu chinh of this doanh nghiep.
	 *
	 * @return the ngay dieu chinh of this doanh nghiep
	 */
	public Date getNgayDieuChinh();

	/**
	 * Sets the ngay dieu chinh of this doanh nghiep.
	 *
	 * @param ngayDieuChinh the ngay dieu chinh of this doanh nghiep
	 */
	public void setNgayDieuChinh(Date ngayDieuChinh);

	/**
	 * Returns the chuc vu nguoi dai dien of this doanh nghiep.
	 *
	 * @return the chuc vu nguoi dai dien of this doanh nghiep
	 */
	@AutoEscape
	public String getChucVuNguoiDaiDien();

	/**
	 * Sets the chuc vu nguoi dai dien of this doanh nghiep.
	 *
	 * @param chucVuNguoiDaiDien the chuc vu nguoi dai dien of this doanh nghiep
	 */
	public void setChucVuNguoiDaiDien(String chucVuNguoiDaiDien);

	/**
	 * Returns the ngay tao of this doanh nghiep.
	 *
	 * @return the ngay tao of this doanh nghiep
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this doanh nghiep.
	 *
	 * @param ngayTao the ngay tao of this doanh nghiep
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the da xoa of this doanh nghiep.
	 *
	 * @return the da xoa of this doanh nghiep
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this doanh nghiep.
	 *
	 * @param daXoa the da xoa of this doanh nghiep
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the ngay sua of this doanh nghiep.
	 *
	 * @return the ngay sua of this doanh nghiep
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this doanh nghiep.
	 *
	 * @param ngaySua the ngay sua of this doanh nghiep
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the cha ID of this doanh nghiep.
	 *
	 * @return the cha ID of this doanh nghiep
	 */
	public Long getChaId();

	/**
	 * Sets the cha ID of this doanh nghiep.
	 *
	 * @param chaId the cha ID of this doanh nghiep
	 */
	public void setChaId(Long chaId);

	/**
	 * Returns the nguoi tao of this doanh nghiep.
	 *
	 * @return the nguoi tao of this doanh nghiep
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this doanh nghiep.
	 *
	 * @param nguoiTao the nguoi tao of this doanh nghiep
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this doanh nghiep.
	 *
	 * @return the nguoi sua of this doanh nghiep
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this doanh nghiep.
	 *
	 * @param nguoiSua the nguoi sua of this doanh nghiep
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the tai khoan nguoi dung ID of this doanh nghiep.
	 *
	 * @return the tai khoan nguoi dung ID of this doanh nghiep
	 */
	public Long getTaiKhoanNguoiDungId();

	/**
	 * Sets the tai khoan nguoi dung ID of this doanh nghiep.
	 *
	 * @param taiKhoanNguoiDungId the tai khoan nguoi dung ID of this doanh nghiep
	 */
	public void setTaiKhoanNguoiDungId(Long taiKhoanNguoiDungId);

	/**
	 * Returns the ten dia diem kinh doanh of this doanh nghiep.
	 *
	 * @return the ten dia diem kinh doanh of this doanh nghiep
	 */
	@AutoEscape
	public String getTenDiaDiemKinhDoanh();

	/**
	 * Sets the ten dia diem kinh doanh of this doanh nghiep.
	 *
	 * @param tenDiaDiemKinhDoanh the ten dia diem kinh doanh of this doanh nghiep
	 */
	public void setTenDiaDiemKinhDoanh(String tenDiaDiemKinhDoanh);

	/**
	 * Returns the ngay dang ky kinh doanh of this doanh nghiep.
	 *
	 * @return the ngay dang ky kinh doanh of this doanh nghiep
	 */
	public Date getNgayDangKyKinhDoanh();

	/**
	 * Sets the ngay dang ky kinh doanh of this doanh nghiep.
	 *
	 * @param ngayDangKyKinhDoanh the ngay dang ky kinh doanh of this doanh nghiep
	 */
	public void setNgayDangKyKinhDoanh(Date ngayDangKyKinhDoanh);

	/**
	 * Returns the loai hinh doanh nghiep ID of this doanh nghiep.
	 *
	 * @return the loai hinh doanh nghiep ID of this doanh nghiep
	 */
	public Long getLoaiHinhDoanhNghiepId();

	/**
	 * Sets the loai hinh doanh nghiep ID of this doanh nghiep.
	 *
	 * @param loaiHinhDoanhNghiepId the loai hinh doanh nghiep ID of this doanh nghiep
	 */
	public void setLoaiHinhDoanhNghiepId(Long loaiHinhDoanhNghiepId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DoanhNghiep doanhNghiep);

	public int hashCode();

	public CacheModel<DoanhNghiep> toCacheModel();

	public DoanhNghiep toEscapedModel();

	public String toString();

	public String toXmlString();
}