/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the YeuCauDangKyDN service. Represents a row in the &quot;BRMS_YEUCAUDANGKY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDNModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDNImpl}.
 * </p>
 *
 * @author Liemnn
 * @see YeuCauDangKyDN
 * @see org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDNImpl
 * @see org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDNModelImpl
 * @generated
 */
public interface YeuCauDangKyDNModel extends BaseModel<YeuCauDangKyDN> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yeu cau dang ky d n model instance should use the {@link YeuCauDangKyDN} interface instead.
	 */

	/**
	 * Returns the primary key of this yeu cau dang ky d n.
	 *
	 * @return the primary key of this yeu cau dang ky d n
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yeu cau dang ky d n.
	 *
	 * @param primaryKey the primary key of this yeu cau dang ky d n
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this yeu cau dang ky d n.
	 *
	 * @return the ID of this yeu cau dang ky d n
	 */
	public long getId();

	/**
	 * Sets the ID of this yeu cau dang ky d n.
	 *
	 * @param id the ID of this yeu cau dang ky d n
	 */
	public void setId(long id);

	/**
	 * Returns the ten of this yeu cau dang ky d n.
	 *
	 * @return the ten of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this yeu cau dang ky d n.
	 *
	 * @param ten the ten of this yeu cau dang ky d n
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma so thue of this yeu cau dang ky d n.
	 *
	 * @return the ma so thue of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getMaSoThue();

	/**
	 * Sets the ma so thue of this yeu cau dang ky d n.
	 *
	 * @param maSoThue the ma so thue of this yeu cau dang ky d n
	 */
	public void setMaSoThue(String maSoThue);

	/**
	 * Returns the ma giay phep of this yeu cau dang ky d n.
	 *
	 * @return the ma giay phep of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getMaGiayPhep();

	/**
	 * Sets the ma giay phep of this yeu cau dang ky d n.
	 *
	 * @param maGiayPhep the ma giay phep of this yeu cau dang ky d n
	 */
	public void setMaGiayPhep(String maGiayPhep);

	/**
	 * Returns the ngay cap of this yeu cau dang ky d n.
	 *
	 * @return the ngay cap of this yeu cau dang ky d n
	 */
	public Date getNgayCap();

	/**
	 * Sets the ngay cap of this yeu cau dang ky d n.
	 *
	 * @param ngayCap the ngay cap of this yeu cau dang ky d n
	 */
	public void setNgayCap(Date ngayCap);

	/**
	 * Returns the email of this yeu cau dang ky d n.
	 *
	 * @return the email of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this yeu cau dang ky d n.
	 *
	 * @param email the email of this yeu cau dang ky d n
	 */
	public void setEmail(String email);

	/**
	 * Returns the ho nguoi dai dien of this yeu cau dang ky d n.
	 *
	 * @return the ho nguoi dai dien of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getHoNguoiDaiDien();

	/**
	 * Sets the ho nguoi dai dien of this yeu cau dang ky d n.
	 *
	 * @param hoNguoiDaiDien the ho nguoi dai dien of this yeu cau dang ky d n
	 */
	public void setHoNguoiDaiDien(String hoNguoiDaiDien);

	/**
	 * Returns the ten dem nguoi dai dien of this yeu cau dang ky d n.
	 *
	 * @return the ten dem nguoi dai dien of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getTenDemNguoiDaiDien();

	/**
	 * Sets the ten dem nguoi dai dien of this yeu cau dang ky d n.
	 *
	 * @param tenDemNguoiDaiDien the ten dem nguoi dai dien of this yeu cau dang ky d n
	 */
	public void setTenDemNguoiDaiDien(String tenDemNguoiDaiDien);

	/**
	 * Returns the ten nguoi dai dien of this yeu cau dang ky d n.
	 *
	 * @return the ten nguoi dai dien of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getTenNguoiDaiDien();

	/**
	 * Sets the ten nguoi dai dien of this yeu cau dang ky d n.
	 *
	 * @param tenNguoiDaiDien the ten nguoi dai dien of this yeu cau dang ky d n
	 */
	public void setTenNguoiDaiDien(String tenNguoiDaiDien);

	/**
	 * Returns the so cmnd of this yeu cau dang ky d n.
	 *
	 * @return the so cmnd of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getSoCmnd();

	/**
	 * Sets the so cmnd of this yeu cau dang ky d n.
	 *
	 * @param soCmnd the so cmnd of this yeu cau dang ky d n
	 */
	public void setSoCmnd(String soCmnd);

	/**
	 * Returns the ngay cap cmnd of this yeu cau dang ky d n.
	 *
	 * @return the ngay cap cmnd of this yeu cau dang ky d n
	 */
	public Date getNgayCapCmnd();

	/**
	 * Sets the ngay cap cmnd of this yeu cau dang ky d n.
	 *
	 * @param ngayCapCmnd the ngay cap cmnd of this yeu cau dang ky d n
	 */
	public void setNgayCapCmnd(Date ngayCapCmnd);

	/**
	 * Returns the noi cap cmnd ID of this yeu cau dang ky d n.
	 *
	 * @return the noi cap cmnd ID of this yeu cau dang ky d n
	 */
	public Long getNoiCapCmndId();

	/**
	 * Sets the noi cap cmnd ID of this yeu cau dang ky d n.
	 *
	 * @param noiCapCmndId the noi cap cmnd ID of this yeu cau dang ky d n
	 */
	public void setNoiCapCmndId(Long noiCapCmndId);

	/**
	 * Returns the mo ta of this yeu cau dang ky d n.
	 *
	 * @return the mo ta of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this yeu cau dang ky d n.
	 *
	 * @param moTa the mo ta of this yeu cau dang ky d n
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the loai doi tuong ID of this yeu cau dang ky d n.
	 *
	 * @return the loai doi tuong ID of this yeu cau dang ky d n
	 */
	public Long getLoaiDoiTuongId();

	/**
	 * Sets the loai doi tuong ID of this yeu cau dang ky d n.
	 *
	 * @param loaiDoiTuongId the loai doi tuong ID of this yeu cau dang ky d n
	 */
	public void setLoaiDoiTuongId(Long loaiDoiTuongId);

	/**
	 * Returns the tru so tinh ID of this yeu cau dang ky d n.
	 *
	 * @return the tru so tinh ID of this yeu cau dang ky d n
	 */
	public Long getTruSoTinhId();

	/**
	 * Sets the tru so tinh ID of this yeu cau dang ky d n.
	 *
	 * @param truSoTinhId the tru so tinh ID of this yeu cau dang ky d n
	 */
	public void setTruSoTinhId(Long truSoTinhId);

	/**
	 * Returns the tru so huyen ID of this yeu cau dang ky d n.
	 *
	 * @return the tru so huyen ID of this yeu cau dang ky d n
	 */
	public Long getTruSoHuyenId();

	/**
	 * Sets the tru so huyen ID of this yeu cau dang ky d n.
	 *
	 * @param truSoHuyenId the tru so huyen ID of this yeu cau dang ky d n
	 */
	public void setTruSoHuyenId(Long truSoHuyenId);

	/**
	 * Returns the tru so xa ID of this yeu cau dang ky d n.
	 *
	 * @return the tru so xa ID of this yeu cau dang ky d n
	 */
	public Long getTruSoXaId();

	/**
	 * Sets the tru so xa ID of this yeu cau dang ky d n.
	 *
	 * @param truSoXaId the tru so xa ID of this yeu cau dang ky d n
	 */
	public void setTruSoXaId(Long truSoXaId);

	/**
	 * Returns the tru so of this yeu cau dang ky d n.
	 *
	 * @return the tru so of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getTruSo();

	/**
	 * Sets the tru so of this yeu cau dang ky d n.
	 *
	 * @param truSo the tru so of this yeu cau dang ky d n
	 */
	public void setTruSo(String truSo);

	/**
	 * Returns the da xoa of this yeu cau dang ky d n.
	 *
	 * @return the da xoa of this yeu cau dang ky d n
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this yeu cau dang ky d n.
	 *
	 * @param daXoa the da xoa of this yeu cau dang ky d n
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the ngay tao of this yeu cau dang ky d n.
	 *
	 * @return the ngay tao of this yeu cau dang ky d n
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this yeu cau dang ky d n.
	 *
	 * @param ngayTao the ngay tao of this yeu cau dang ky d n
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the nguoi tao of this yeu cau dang ky d n.
	 *
	 * @return the nguoi tao of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this yeu cau dang ky d n.
	 *
	 * @param nguoiTao the nguoi tao of this yeu cau dang ky d n
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the ngay sua of this yeu cau dang ky d n.
	 *
	 * @return the ngay sua of this yeu cau dang ky d n
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this yeu cau dang ky d n.
	 *
	 * @param ngaySua the ngay sua of this yeu cau dang ky d n
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi sua of this yeu cau dang ky d n.
	 *
	 * @return the nguoi sua of this yeu cau dang ky d n
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this yeu cau dang ky d n.
	 *
	 * @param nguoiSua the nguoi sua of this yeu cau dang ky d n
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the trang thai of this yeu cau dang ky d n.
	 *
	 * @return the trang thai of this yeu cau dang ky d n
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this yeu cau dang ky d n.
	 *
	 * @param trangThai the trang thai of this yeu cau dang ky d n
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the loai hinh doanh nghiep ID of this yeu cau dang ky d n.
	 *
	 * @return the loai hinh doanh nghiep ID of this yeu cau dang ky d n
	 */
	public Long getLoaiHinhDoanhNghiepId();

	/**
	 * Sets the loai hinh doanh nghiep ID of this yeu cau dang ky d n.
	 *
	 * @param loaiHinhDoanhNghiepId the loai hinh doanh nghiep ID of this yeu cau dang ky d n
	 */
	public void setLoaiHinhDoanhNghiepId(Long loaiHinhDoanhNghiepId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(YeuCauDangKyDN yeuCauDangKyDN);

	public int hashCode();

	public CacheModel<YeuCauDangKyDN> toCacheModel();

	public YeuCauDangKyDN toEscapedModel();

	public String toString();

	public String toXmlString();
}