/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the YeuCauDangKyDoanhNghiep service. Represents a row in the &quot;BRMS_YEUCAUDANGKYDOANHNGHIEP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDoanhNghiepModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDoanhNghiepImpl}.
 * </p>
 *
 * @author Liemnn
 * @see YeuCauDangKyDoanhNghiep
 * @see org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDoanhNghiepImpl
 * @see org.oep.cmon.dao.dn.model.impl.YeuCauDangKyDoanhNghiepModelImpl
 * @generated
 */
public interface YeuCauDangKyDoanhNghiepModel extends BaseModel<YeuCauDangKyDoanhNghiep> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yeu cau dang ky doanh nghiep model instance should use the {@link YeuCauDangKyDoanhNghiep} interface instead.
	 */

	/**
	 * Returns the primary key of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the primary key of this yeu cau dang ky doanh nghiep
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yeu cau dang ky doanh nghiep.
	 *
	 * @param primaryKey the primary key of this yeu cau dang ky doanh nghiep
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ID of this yeu cau dang ky doanh nghiep
	 */
	public long getId();

	/**
	 * Sets the ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @param id the ID of this yeu cau dang ky doanh nghiep
	 */
	public void setId(long id);

	/**
	 * Returns the loai doi tuong ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the loai doi tuong ID of this yeu cau dang ky doanh nghiep
	 */
	public long getLoaiDoiTuongId();

	/**
	 * Sets the loai doi tuong ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @param loaiDoiTuongId the loai doi tuong ID of this yeu cau dang ky doanh nghiep
	 */
	public void setLoaiDoiTuongId(long loaiDoiTuongId);

	/**
	 * Returns the ten of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ten of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this yeu cau dang ky doanh nghiep.
	 *
	 * @param ten the ten of this yeu cau dang ky doanh nghiep
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma so thue of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ma so thue of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getMaSoThue();

	/**
	 * Sets the ma so thue of this yeu cau dang ky doanh nghiep.
	 *
	 * @param maSoThue the ma so thue of this yeu cau dang ky doanh nghiep
	 */
	public void setMaSoThue(String maSoThue);

	/**
	 * Returns the ma giay phep of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ma giay phep of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getMaGiayPhep();

	/**
	 * Sets the ma giay phep of this yeu cau dang ky doanh nghiep.
	 *
	 * @param maGiayPhep the ma giay phep of this yeu cau dang ky doanh nghiep
	 */
	public void setMaGiayPhep(String maGiayPhep);

	/**
	 * Returns the ngay cap of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ngay cap of this yeu cau dang ky doanh nghiep
	 */
	public Date getNgayCap();

	/**
	 * Sets the ngay cap of this yeu cau dang ky doanh nghiep.
	 *
	 * @param ngayCap the ngay cap of this yeu cau dang ky doanh nghiep
	 */
	public void setNgayCap(Date ngayCap);

	/**
	 * Returns the email of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the email of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this yeu cau dang ky doanh nghiep.
	 *
	 * @param email the email of this yeu cau dang ky doanh nghiep
	 */
	public void setEmail(String email);

	/**
	 * Returns the ho nguoi dai dien of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ho nguoi dai dien of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getHoNguoiDaiDien();

	/**
	 * Sets the ho nguoi dai dien of this yeu cau dang ky doanh nghiep.
	 *
	 * @param hoNguoiDaiDien the ho nguoi dai dien of this yeu cau dang ky doanh nghiep
	 */
	public void setHoNguoiDaiDien(String hoNguoiDaiDien);

	/**
	 * Returns the ten dem nguoi dai dien of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ten dem nguoi dai dien of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getTenDemNguoiDaiDien();

	/**
	 * Sets the ten dem nguoi dai dien of this yeu cau dang ky doanh nghiep.
	 *
	 * @param tenDemNguoiDaiDien the ten dem nguoi dai dien of this yeu cau dang ky doanh nghiep
	 */
	public void setTenDemNguoiDaiDien(String tenDemNguoiDaiDien);

	/**
	 * Returns the ten nguoi dai dien of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ten nguoi dai dien of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getTenNguoiDaiDien();

	/**
	 * Sets the ten nguoi dai dien of this yeu cau dang ky doanh nghiep.
	 *
	 * @param tenNguoiDaiDien the ten nguoi dai dien of this yeu cau dang ky doanh nghiep
	 */
	public void setTenNguoiDaiDien(String tenNguoiDaiDien);

	/**
	 * Returns the so c m n d of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the so c m n d of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getSoCMND();

	/**
	 * Sets the so c m n d of this yeu cau dang ky doanh nghiep.
	 *
	 * @param soCMND the so c m n d of this yeu cau dang ky doanh nghiep
	 */
	public void setSoCMND(String soCMND);

	/**
	 * Returns the ngay cap c m n d of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the ngay cap c m n d of this yeu cau dang ky doanh nghiep
	 */
	public Date getNgayCapCMND();

	/**
	 * Sets the ngay cap c m n d of this yeu cau dang ky doanh nghiep.
	 *
	 * @param ngayCapCMND the ngay cap c m n d of this yeu cau dang ky doanh nghiep
	 */
	public void setNgayCapCMND(Date ngayCapCMND);

	/**
	 * Returns the noi cap c m n d of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the noi cap c m n d of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getNoiCapCMND();

	/**
	 * Sets the noi cap c m n d of this yeu cau dang ky doanh nghiep.
	 *
	 * @param noiCapCMND the noi cap c m n d of this yeu cau dang ky doanh nghiep
	 */
	public void setNoiCapCMND(String noiCapCMND);

	/**
	 * Returns the mo ta nganh nghe kinh doanh of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the mo ta nganh nghe kinh doanh of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getMoTaNganhNgheKinhDoanh();

	/**
	 * Sets the mo ta nganh nghe kinh doanh of this yeu cau dang ky doanh nghiep.
	 *
	 * @param moTaNganhNgheKinhDoanh the mo ta nganh nghe kinh doanh of this yeu cau dang ky doanh nghiep
	 */
	public void setMoTaNganhNgheKinhDoanh(String moTaNganhNgheKinhDoanh);

	/**
	 * Returns the loai hinh doanh nghiep of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the loai hinh doanh nghiep of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getLoaiHinhDoanhNghiep();

	/**
	 * Sets the loai hinh doanh nghiep of this yeu cau dang ky doanh nghiep.
	 *
	 * @param loaiHinhDoanhNghiep the loai hinh doanh nghiep of this yeu cau dang ky doanh nghiep
	 */
	public void setLoaiHinhDoanhNghiep(String loaiHinhDoanhNghiep);

	/**
	 * Returns the tru so of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the tru so of this yeu cau dang ky doanh nghiep
	 */
	@AutoEscape
	public String getTruSo();

	/**
	 * Sets the tru so of this yeu cau dang ky doanh nghiep.
	 *
	 * @param truSo the tru so of this yeu cau dang ky doanh nghiep
	 */
	public void setTruSo(String truSo);

	/**
	 * Returns the tru so xa ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the tru so xa ID of this yeu cau dang ky doanh nghiep
	 */
	public long getTruSoXaId();

	/**
	 * Sets the tru so xa ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @param truSoXaId the tru so xa ID of this yeu cau dang ky doanh nghiep
	 */
	public void setTruSoXaId(long truSoXaId);

	/**
	 * Returns the tru so huyen ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the tru so huyen ID of this yeu cau dang ky doanh nghiep
	 */
	public long getTruSoHuyenId();

	/**
	 * Sets the tru so huyen ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @param truSoHuyenId the tru so huyen ID of this yeu cau dang ky doanh nghiep
	 */
	public void setTruSoHuyenId(long truSoHuyenId);

	/**
	 * Returns the tru so tinh ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the tru so tinh ID of this yeu cau dang ky doanh nghiep
	 */
	public long getTruSoTinhId();

	/**
	 * Sets the tru so tinh ID of this yeu cau dang ky doanh nghiep.
	 *
	 * @param truSoTinhId the tru so tinh ID of this yeu cau dang ky doanh nghiep
	 */
	public void setTruSoTinhId(long truSoTinhId);

	/**
	 * Returns the trang thai of this yeu cau dang ky doanh nghiep.
	 *
	 * @return the trang thai of this yeu cau dang ky doanh nghiep
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this yeu cau dang ky doanh nghiep.
	 *
	 * @param trangThai the trang thai of this yeu cau dang ky doanh nghiep
	 */
	public void setTrangThai(int trangThai);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(YeuCauDangKyDoanhNghiep yeuCauDangKyDoanhNghiep);

	public int hashCode();

	public CacheModel<YeuCauDangKyDoanhNghiep> toCacheModel();

	public YeuCauDangKyDoanhNghiep toEscapedModel();

	public String toString();

	public String toXmlString();
}