/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.touchscreen.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCong;
import org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCongModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TraCuuHoSoTTHCCong service. Represents a row in the &quot;DNICT_TraCuuHoSoTTHCCong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCongModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TraCuuHoSoTTHCCongImpl}.
 * </p>
 *
 * @author VIENPN
 * @see TraCuuHoSoTTHCCongImpl
 * @see org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCong
 * @see org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCongModel
 * @generated
 */
public class TraCuuHoSoTTHCCongModelImpl extends BaseModelImpl<TraCuuHoSoTTHCCong>
	implements TraCuuHoSoTTHCCongModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tra cuu ho so t t h c cong model instance should use the {@link org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCong} interface instead.
	 */
	public static final String TABLE_NAME = "DNICT_TraCuuHoSoTTHCCong";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "ngayNhanHoSo", Types.TIMESTAMP },
			{ "tenCoQuanTiepNhan", Types.VARCHAR },
			{ "tenThuTucHanhChinh", Types.VARCHAR },
			{ "ngayHenTraKetQua", Types.TIMESTAMP },
			{ "ngayTraKetQua", Types.TIMESTAMP },
			{ "hoTenNguoiNopHoSo", Types.VARCHAR },
			{ "diaChiThuongTruNguoiNop", Types.VARCHAR },
			{ "soDienThoaiDiDongNguoiNop", Types.VARCHAR },
			{ "ngayKetThucXuLy", Types.TIMESTAMP },
			{ "loaiHoSo", Types.INTEGER },
			{ "maSoBienNhan", Types.VARCHAR },
			{ "chuSoHuu", Types.VARCHAR },
			{ "lePhi", Types.INTEGER },
			{ "phiHoSo", Types.INTEGER },
			{ "emailNguoiNop", Types.VARCHAR },
			{ "soDienThoaiCoDinhNguoiNop", Types.VARCHAR },
			{ "nhomThuTucHanhChinhTen", Types.VARCHAR },
			{ "trangThaiHoSoTen", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DNICT_TraCuuHoSoTTHCCong (id_ LONG not null primary key,ngayNhanHoSo DATE null,tenCoQuanTiepNhan VARCHAR(75) null,tenThuTucHanhChinh VARCHAR(75) null,ngayHenTraKetQua DATE null,ngayTraKetQua DATE null,hoTenNguoiNopHoSo VARCHAR(75) null,diaChiThuongTruNguoiNop VARCHAR(75) null,soDienThoaiDiDongNguoiNop VARCHAR(75) null,ngayKetThucXuLy DATE null,loaiHoSo INTEGER,maSoBienNhan VARCHAR(75) null,chuSoHuu VARCHAR(75) null,lePhi INTEGER,phiHoSo INTEGER,emailNguoiNop VARCHAR(75) null,soDienThoaiCoDinhNguoiNop VARCHAR(75) null,nhomThuTucHanhChinhTen VARCHAR(75) null,trangThaiHoSoTen VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DNICT_TraCuuHoSoTTHCCong";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCong"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCong"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCong"));

	public TraCuuHoSoTTHCCongModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TraCuuHoSoTTHCCong.class;
	}

	public String getModelClassName() {
		return TraCuuHoSoTTHCCong.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public Date getNgayNhanHoSo() {
		return _ngayNhanHoSo;
	}

	public void setNgayNhanHoSo(Date ngayNhanHoSo) {
		_ngayNhanHoSo = ngayNhanHoSo;
	}

	public String getTenCoQuanTiepNhan() {
		if (_tenCoQuanTiepNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenCoQuanTiepNhan;
		}
	}

	public void setTenCoQuanTiepNhan(String tenCoQuanTiepNhan) {
		_tenCoQuanTiepNhan = tenCoQuanTiepNhan;
	}

	public String getTenThuTucHanhChinh() {
		if (_tenThuTucHanhChinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenThuTucHanhChinh;
		}
	}

	public void setTenThuTucHanhChinh(String tenThuTucHanhChinh) {
		_tenThuTucHanhChinh = tenThuTucHanhChinh;
	}

	public Date getNgayHenTraKetQua() {
		return _ngayHenTraKetQua;
	}

	public void setNgayHenTraKetQua(Date ngayHenTraKetQua) {
		_ngayHenTraKetQua = ngayHenTraKetQua;
	}

	public Date getNgayTraKetQua() {
		return _ngayTraKetQua;
	}

	public void setNgayTraKetQua(Date ngayTraKetQua) {
		_ngayTraKetQua = ngayTraKetQua;
	}

	public String getHoTenNguoiNopHoSo() {
		if (_hoTenNguoiNopHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoTenNguoiNopHoSo;
		}
	}

	public void setHoTenNguoiNopHoSo(String hoTenNguoiNopHoSo) {
		_hoTenNguoiNopHoSo = hoTenNguoiNopHoSo;
	}

	public String getDiaChiThuongTruNguoiNop() {
		if (_diaChiThuongTruNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiThuongTruNguoiNop;
		}
	}

	public void setDiaChiThuongTruNguoiNop(String diaChiThuongTruNguoiNop) {
		_diaChiThuongTruNguoiNop = diaChiThuongTruNguoiNop;
	}

	public String getSoDienThoaiDiDongNguoiNop() {
		if (_soDienThoaiDiDongNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDienThoaiDiDongNguoiNop;
		}
	}

	public void setSoDienThoaiDiDongNguoiNop(String soDienThoaiDiDongNguoiNop) {
		_soDienThoaiDiDongNguoiNop = soDienThoaiDiDongNguoiNop;
	}

	public Date getNgayKetThucXuLy() {
		return _ngayKetThucXuLy;
	}

	public void setNgayKetThucXuLy(Date ngayKetThucXuLy) {
		_ngayKetThucXuLy = ngayKetThucXuLy;
	}

	public int getLoaiHoSo() {
		return _loaiHoSo;
	}

	public void setLoaiHoSo(int loaiHoSo) {
		_loaiHoSo = loaiHoSo;
	}

	public String getMaSoBienNhan() {
		if (_maSoBienNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoBienNhan;
		}
	}

	public void setMaSoBienNhan(String maSoBienNhan) {
		_maSoBienNhan = maSoBienNhan;
	}

	public String getChuSoHuu() {
		if (_chuSoHuu == null) {
			return StringPool.BLANK;
		}
		else {
			return _chuSoHuu;
		}
	}

	public void setChuSoHuu(String chuSoHuu) {
		_chuSoHuu = chuSoHuu;
	}

	public int getLePhi() {
		return _lePhi;
	}

	public void setLePhi(int lePhi) {
		_lePhi = lePhi;
	}

	public int getPhiHoSo() {
		return _phiHoSo;
	}

	public void setPhiHoSo(int phiHoSo) {
		_phiHoSo = phiHoSo;
	}

	public String getEmailNguoiNop() {
		if (_emailNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailNguoiNop;
		}
	}

	public void setEmailNguoiNop(String emailNguoiNop) {
		_emailNguoiNop = emailNguoiNop;
	}

	public String getSoDienThoaiCoDinhNguoiNop() {
		if (_soDienThoaiCoDinhNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDienThoaiCoDinhNguoiNop;
		}
	}

	public void setSoDienThoaiCoDinhNguoiNop(String soDienThoaiCoDinhNguoiNop) {
		_soDienThoaiCoDinhNguoiNop = soDienThoaiCoDinhNguoiNop;
	}

	public String getNhomThuTucHanhChinhTen() {
		if (_nhomThuTucHanhChinhTen == null) {
			return StringPool.BLANK;
		}
		else {
			return _nhomThuTucHanhChinhTen;
		}
	}

	public void setNhomThuTucHanhChinhTen(String nhomThuTucHanhChinhTen) {
		_nhomThuTucHanhChinhTen = nhomThuTucHanhChinhTen;
	}

	public String getTrangThaiHoSoTen() {
		if (_trangThaiHoSoTen == null) {
			return StringPool.BLANK;
		}
		else {
			return _trangThaiHoSoTen;
		}
	}

	public void setTrangThaiHoSoTen(String trangThaiHoSoTen) {
		_trangThaiHoSoTen = trangThaiHoSoTen;
	}

	@Override
	public TraCuuHoSoTTHCCong toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TraCuuHoSoTTHCCong)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TraCuuHoSoTTHCCong.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TraCuuHoSoTTHCCongImpl traCuuHoSoTTHCCongImpl = new TraCuuHoSoTTHCCongImpl();

		traCuuHoSoTTHCCongImpl.setId(getId());
		traCuuHoSoTTHCCongImpl.setNgayNhanHoSo(getNgayNhanHoSo());
		traCuuHoSoTTHCCongImpl.setTenCoQuanTiepNhan(getTenCoQuanTiepNhan());
		traCuuHoSoTTHCCongImpl.setTenThuTucHanhChinh(getTenThuTucHanhChinh());
		traCuuHoSoTTHCCongImpl.setNgayHenTraKetQua(getNgayHenTraKetQua());
		traCuuHoSoTTHCCongImpl.setNgayTraKetQua(getNgayTraKetQua());
		traCuuHoSoTTHCCongImpl.setHoTenNguoiNopHoSo(getHoTenNguoiNopHoSo());
		traCuuHoSoTTHCCongImpl.setDiaChiThuongTruNguoiNop(getDiaChiThuongTruNguoiNop());
		traCuuHoSoTTHCCongImpl.setSoDienThoaiDiDongNguoiNop(getSoDienThoaiDiDongNguoiNop());
		traCuuHoSoTTHCCongImpl.setNgayKetThucXuLy(getNgayKetThucXuLy());
		traCuuHoSoTTHCCongImpl.setLoaiHoSo(getLoaiHoSo());
		traCuuHoSoTTHCCongImpl.setMaSoBienNhan(getMaSoBienNhan());
		traCuuHoSoTTHCCongImpl.setChuSoHuu(getChuSoHuu());
		traCuuHoSoTTHCCongImpl.setLePhi(getLePhi());
		traCuuHoSoTTHCCongImpl.setPhiHoSo(getPhiHoSo());
		traCuuHoSoTTHCCongImpl.setEmailNguoiNop(getEmailNguoiNop());
		traCuuHoSoTTHCCongImpl.setSoDienThoaiCoDinhNguoiNop(getSoDienThoaiCoDinhNguoiNop());
		traCuuHoSoTTHCCongImpl.setNhomThuTucHanhChinhTen(getNhomThuTucHanhChinhTen());
		traCuuHoSoTTHCCongImpl.setTrangThaiHoSoTen(getTrangThaiHoSoTen());

		traCuuHoSoTTHCCongImpl.resetOriginalValues();

		return traCuuHoSoTTHCCongImpl;
	}

	public int compareTo(TraCuuHoSoTTHCCong traCuuHoSoTTHCCong) {
		long primaryKey = traCuuHoSoTTHCCong.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TraCuuHoSoTTHCCong traCuuHoSoTTHCCong = null;

		try {
			traCuuHoSoTTHCCong = (TraCuuHoSoTTHCCong)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = traCuuHoSoTTHCCong.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TraCuuHoSoTTHCCong> toCacheModel() {
		TraCuuHoSoTTHCCongCacheModel traCuuHoSoTTHCCongCacheModel = new TraCuuHoSoTTHCCongCacheModel();

		traCuuHoSoTTHCCongCacheModel.id = getId();

		Date ngayNhanHoSo = getNgayNhanHoSo();

		if (ngayNhanHoSo != null) {
			traCuuHoSoTTHCCongCacheModel.ngayNhanHoSo = ngayNhanHoSo.getTime();
		}
		else {
			traCuuHoSoTTHCCongCacheModel.ngayNhanHoSo = Long.MIN_VALUE;
		}

		traCuuHoSoTTHCCongCacheModel.tenCoQuanTiepNhan = getTenCoQuanTiepNhan();

		String tenCoQuanTiepNhan = traCuuHoSoTTHCCongCacheModel.tenCoQuanTiepNhan;

		if ((tenCoQuanTiepNhan != null) && (tenCoQuanTiepNhan.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.tenCoQuanTiepNhan = null;
		}

		traCuuHoSoTTHCCongCacheModel.tenThuTucHanhChinh = getTenThuTucHanhChinh();

		String tenThuTucHanhChinh = traCuuHoSoTTHCCongCacheModel.tenThuTucHanhChinh;

		if ((tenThuTucHanhChinh != null) && (tenThuTucHanhChinh.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.tenThuTucHanhChinh = null;
		}

		Date ngayHenTraKetQua = getNgayHenTraKetQua();

		if (ngayHenTraKetQua != null) {
			traCuuHoSoTTHCCongCacheModel.ngayHenTraKetQua = ngayHenTraKetQua.getTime();
		}
		else {
			traCuuHoSoTTHCCongCacheModel.ngayHenTraKetQua = Long.MIN_VALUE;
		}

		Date ngayTraKetQua = getNgayTraKetQua();

		if (ngayTraKetQua != null) {
			traCuuHoSoTTHCCongCacheModel.ngayTraKetQua = ngayTraKetQua.getTime();
		}
		else {
			traCuuHoSoTTHCCongCacheModel.ngayTraKetQua = Long.MIN_VALUE;
		}

		traCuuHoSoTTHCCongCacheModel.hoTenNguoiNopHoSo = getHoTenNguoiNopHoSo();

		String hoTenNguoiNopHoSo = traCuuHoSoTTHCCongCacheModel.hoTenNguoiNopHoSo;

		if ((hoTenNguoiNopHoSo != null) && (hoTenNguoiNopHoSo.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.hoTenNguoiNopHoSo = null;
		}

		traCuuHoSoTTHCCongCacheModel.diaChiThuongTruNguoiNop = getDiaChiThuongTruNguoiNop();

		String diaChiThuongTruNguoiNop = traCuuHoSoTTHCCongCacheModel.diaChiThuongTruNguoiNop;

		if ((diaChiThuongTruNguoiNop != null) &&
				(diaChiThuongTruNguoiNop.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.diaChiThuongTruNguoiNop = null;
		}

		traCuuHoSoTTHCCongCacheModel.soDienThoaiDiDongNguoiNop = getSoDienThoaiDiDongNguoiNop();

		String soDienThoaiDiDongNguoiNop = traCuuHoSoTTHCCongCacheModel.soDienThoaiDiDongNguoiNop;

		if ((soDienThoaiDiDongNguoiNop != null) &&
				(soDienThoaiDiDongNguoiNop.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.soDienThoaiDiDongNguoiNop = null;
		}

		Date ngayKetThucXuLy = getNgayKetThucXuLy();

		if (ngayKetThucXuLy != null) {
			traCuuHoSoTTHCCongCacheModel.ngayKetThucXuLy = ngayKetThucXuLy.getTime();
		}
		else {
			traCuuHoSoTTHCCongCacheModel.ngayKetThucXuLy = Long.MIN_VALUE;
		}

		traCuuHoSoTTHCCongCacheModel.loaiHoSo = getLoaiHoSo();

		traCuuHoSoTTHCCongCacheModel.maSoBienNhan = getMaSoBienNhan();

		String maSoBienNhan = traCuuHoSoTTHCCongCacheModel.maSoBienNhan;

		if ((maSoBienNhan != null) && (maSoBienNhan.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.maSoBienNhan = null;
		}

		traCuuHoSoTTHCCongCacheModel.chuSoHuu = getChuSoHuu();

		String chuSoHuu = traCuuHoSoTTHCCongCacheModel.chuSoHuu;

		if ((chuSoHuu != null) && (chuSoHuu.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.chuSoHuu = null;
		}

		traCuuHoSoTTHCCongCacheModel.lePhi = getLePhi();

		traCuuHoSoTTHCCongCacheModel.phiHoSo = getPhiHoSo();

		traCuuHoSoTTHCCongCacheModel.emailNguoiNop = getEmailNguoiNop();

		String emailNguoiNop = traCuuHoSoTTHCCongCacheModel.emailNguoiNop;

		if ((emailNguoiNop != null) && (emailNguoiNop.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.emailNguoiNop = null;
		}

		traCuuHoSoTTHCCongCacheModel.soDienThoaiCoDinhNguoiNop = getSoDienThoaiCoDinhNguoiNop();

		String soDienThoaiCoDinhNguoiNop = traCuuHoSoTTHCCongCacheModel.soDienThoaiCoDinhNguoiNop;

		if ((soDienThoaiCoDinhNguoiNop != null) &&
				(soDienThoaiCoDinhNguoiNop.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.soDienThoaiCoDinhNguoiNop = null;
		}

		traCuuHoSoTTHCCongCacheModel.nhomThuTucHanhChinhTen = getNhomThuTucHanhChinhTen();

		String nhomThuTucHanhChinhTen = traCuuHoSoTTHCCongCacheModel.nhomThuTucHanhChinhTen;

		if ((nhomThuTucHanhChinhTen != null) &&
				(nhomThuTucHanhChinhTen.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.nhomThuTucHanhChinhTen = null;
		}

		traCuuHoSoTTHCCongCacheModel.trangThaiHoSoTen = getTrangThaiHoSoTen();

		String trangThaiHoSoTen = traCuuHoSoTTHCCongCacheModel.trangThaiHoSoTen;

		if ((trangThaiHoSoTen != null) && (trangThaiHoSoTen.length() == 0)) {
			traCuuHoSoTTHCCongCacheModel.trangThaiHoSoTen = null;
		}

		return traCuuHoSoTTHCCongCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ngayNhanHoSo=");
		sb.append(getNgayNhanHoSo());
		sb.append(", tenCoQuanTiepNhan=");
		sb.append(getTenCoQuanTiepNhan());
		sb.append(", tenThuTucHanhChinh=");
		sb.append(getTenThuTucHanhChinh());
		sb.append(", ngayHenTraKetQua=");
		sb.append(getNgayHenTraKetQua());
		sb.append(", ngayTraKetQua=");
		sb.append(getNgayTraKetQua());
		sb.append(", hoTenNguoiNopHoSo=");
		sb.append(getHoTenNguoiNopHoSo());
		sb.append(", diaChiThuongTruNguoiNop=");
		sb.append(getDiaChiThuongTruNguoiNop());
		sb.append(", soDienThoaiDiDongNguoiNop=");
		sb.append(getSoDienThoaiDiDongNguoiNop());
		sb.append(", ngayKetThucXuLy=");
		sb.append(getNgayKetThucXuLy());
		sb.append(", loaiHoSo=");
		sb.append(getLoaiHoSo());
		sb.append(", maSoBienNhan=");
		sb.append(getMaSoBienNhan());
		sb.append(", chuSoHuu=");
		sb.append(getChuSoHuu());
		sb.append(", lePhi=");
		sb.append(getLePhi());
		sb.append(", phiHoSo=");
		sb.append(getPhiHoSo());
		sb.append(", emailNguoiNop=");
		sb.append(getEmailNguoiNop());
		sb.append(", soDienThoaiCoDinhNguoiNop=");
		sb.append(getSoDienThoaiCoDinhNguoiNop());
		sb.append(", nhomThuTucHanhChinhTen=");
		sb.append(getNhomThuTucHanhChinhTen());
		sb.append(", trangThaiHoSoTen=");
		sb.append(getTrangThaiHoSoTen());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.touchscreen.model.TraCuuHoSoTTHCCong");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayNhanHoSo</column-name><column-value><![CDATA[");
		sb.append(getNgayNhanHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCoQuanTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getTenCoQuanTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenThuTucHanhChinh</column-name><column-value><![CDATA[");
		sb.append(getTenThuTucHanhChinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHenTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getNgayHenTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getNgayTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenNguoiNopHoSo</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiNopHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDienThoaiDiDongNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDienThoaiDiDongNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKetThucXuLy</column-name><column-value><![CDATA[");
		sb.append(getNgayKetThucXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHoSo</column-name><column-value><![CDATA[");
		sb.append(getLoaiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoBienNhan</column-name><column-value><![CDATA[");
		sb.append(getMaSoBienNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chuSoHuu</column-name><column-value><![CDATA[");
		sb.append(getChuSoHuu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lePhi</column-name><column-value><![CDATA[");
		sb.append(getLePhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phiHoSo</column-name><column-value><![CDATA[");
		sb.append(getPhiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getEmailNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDienThoaiCoDinhNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDienThoaiCoDinhNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhomThuTucHanhChinhTen</column-name><column-value><![CDATA[");
		sb.append(getNhomThuTucHanhChinhTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiHoSoTen</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiHoSoTen());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TraCuuHoSoTTHCCong.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TraCuuHoSoTTHCCong.class
		};
	private long _id;
	private Date _ngayNhanHoSo;
	private String _tenCoQuanTiepNhan;
	private String _tenThuTucHanhChinh;
	private Date _ngayHenTraKetQua;
	private Date _ngayTraKetQua;
	private String _hoTenNguoiNopHoSo;
	private String _diaChiThuongTruNguoiNop;
	private String _soDienThoaiDiDongNguoiNop;
	private Date _ngayKetThucXuLy;
	private int _loaiHoSo;
	private String _maSoBienNhan;
	private String _chuSoHuu;
	private int _lePhi;
	private int _phiHoSo;
	private String _emailNguoiNop;
	private String _soDienThoaiCoDinhNguoiNop;
	private String _nhomThuTucHanhChinhTen;
	private String _trangThaiHoSoTen;
	private transient ExpandoBridge _expandoBridge;
	private TraCuuHoSoTTHCCong _escapedModelProxy;
}