/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.touchscreen.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinh;
import org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TraCuuThuTucHanhChinh service. Represents a row in the &quot;DNICT_TraCuuThuTucHanhChinh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TraCuuThuTucHanhChinhImpl}.
 * </p>
 *
 * @author VIENPN
 * @see TraCuuThuTucHanhChinhImpl
 * @see org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinh
 * @see org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinhModel
 * @generated
 */
public class TraCuuThuTucHanhChinhModelImpl extends BaseModelImpl<TraCuuThuTucHanhChinh>
	implements TraCuuThuTucHanhChinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tra cuu thu tuc hanh chinh model instance should use the {@link org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinh} interface instead.
	 */
	public static final String TABLE_NAME = "DNICT_TraCuuThuTucHanhChinh";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "ma", Types.VARCHAR },
			{ "ten", Types.VARCHAR },
			{ "soNgayXuLy", Types.BIGINT },
			{ "ngayTao", Types.TIMESTAMP },
			{ "ngaySua", Types.TIMESTAMP },
			{ "daXoa", Types.INTEGER },
			{ "nguoiTao", Types.VARCHAR },
			{ "nguoiSua", Types.VARCHAR },
			{ "nhomThuTucHanhChinhId", Types.BIGINT },
			{ "nhomThuTucHanhChinhTen", Types.VARCHAR },
			{ "trangThai", Types.INTEGER },
			{ "phienBan", Types.BIGINT },
			{ "canTichHop", Types.INTEGER },
			{ "trinhTuThucHien", Types.VARCHAR },
			{ "cachThucHien", Types.VARCHAR },
			{ "thanhPhanHoSo", Types.VARCHAR },
			{ "lePhi", Types.BIGINT },
			{ "donViLePhi", Types.VARCHAR },
			{ "phi", Types.BIGINT },
			{ "donViPhi", Types.VARCHAR },
			{ "tenMauDonToKhai", Types.VARCHAR },
			{ "yeuCauDieuKienThucHien", Types.VARCHAR },
			{ "canCuPhapLy", Types.VARCHAR },
			{ "capCoQuanQuanLyId", Types.BIGINT },
			{ "linhVucThucHien", Types.VARCHAR },
			{ "maDNG", Types.VARCHAR },
			{ "uengineProcessName", Types.VARCHAR },
			{ "thuTucLienThongId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table DNICT_TraCuuThuTucHanhChinh (id_ LONG not null primary key,ma VARCHAR(75) null,ten VARCHAR(75) null,soNgayXuLy LONG,ngayTao DATE null,ngaySua DATE null,daXoa INTEGER,nguoiTao VARCHAR(75) null,nguoiSua VARCHAR(75) null,nhomThuTucHanhChinhId LONG,nhomThuTucHanhChinhTen VARCHAR(75) null,trangThai INTEGER,phienBan LONG,canTichHop INTEGER,trinhTuThucHien VARCHAR(75) null,cachThucHien VARCHAR(75) null,thanhPhanHoSo VARCHAR(75) null,lePhi LONG,donViLePhi VARCHAR(75) null,phi LONG,donViPhi VARCHAR(75) null,tenMauDonToKhai VARCHAR(75) null,yeuCauDieuKienThucHien VARCHAR(75) null,canCuPhapLy VARCHAR(75) null,capCoQuanQuanLyId LONG,linhVucThucHien VARCHAR(75) null,maDNG VARCHAR(75) null,uengineProcessName VARCHAR(75) null,thuTucLienThongId LONG)";
	public static final String TABLE_SQL_DROP = "drop table DNICT_TraCuuThuTucHanhChinh";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinh"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinh"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinh"));

	public TraCuuThuTucHanhChinhModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TraCuuThuTucHanhChinh.class;
	}

	public String getModelClassName() {
		return TraCuuThuTucHanhChinh.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_ma = ma;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public long getSoNgayXuLy() {
		return _soNgayXuLy;
	}

	public void setSoNgayXuLy(long soNgayXuLy) {
		_soNgayXuLy = soNgayXuLy;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_daXoa = daXoa;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public long getNhomThuTucHanhChinhId() {
		return _nhomThuTucHanhChinhId;
	}

	public void setNhomThuTucHanhChinhId(long nhomThuTucHanhChinhId) {
		_nhomThuTucHanhChinhId = nhomThuTucHanhChinhId;
	}

	public String getNhomThuTucHanhChinhTen() {
		if (_nhomThuTucHanhChinhTen == null) {
			return StringPool.BLANK;
		}
		else {
			return _nhomThuTucHanhChinhTen;
		}
	}

	public void setNhomThuTucHanhChinhTen(String nhomThuTucHanhChinhTen) {
		_nhomThuTucHanhChinhTen = nhomThuTucHanhChinhTen;
	}

	public int getTrangThai() {
		return _trangThai;
	}

	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	public long getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(long phienBan) {
		_phienBan = phienBan;
	}

	public int getCanTichHop() {
		return _canTichHop;
	}

	public void setCanTichHop(int canTichHop) {
		_canTichHop = canTichHop;
	}

	public String getTrinhTuThucHien() {
		if (_trinhTuThucHien == null) {
			return StringPool.BLANK;
		}
		else {
			return _trinhTuThucHien;
		}
	}

	public void setTrinhTuThucHien(String trinhTuThucHien) {
		_trinhTuThucHien = trinhTuThucHien;
	}

	public String getCachThucHien() {
		if (_cachThucHien == null) {
			return StringPool.BLANK;
		}
		else {
			return _cachThucHien;
		}
	}

	public void setCachThucHien(String cachThucHien) {
		_cachThucHien = cachThucHien;
	}

	public String getThanhPhanHoSo() {
		if (_thanhPhanHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _thanhPhanHoSo;
		}
	}

	public void setThanhPhanHoSo(String thanhPhanHoSo) {
		_thanhPhanHoSo = thanhPhanHoSo;
	}

	public long getLePhi() {
		return _lePhi;
	}

	public void setLePhi(long lePhi) {
		_lePhi = lePhi;
	}

	public String getDonViLePhi() {
		if (_donViLePhi == null) {
			return StringPool.BLANK;
		}
		else {
			return _donViLePhi;
		}
	}

	public void setDonViLePhi(String donViLePhi) {
		_donViLePhi = donViLePhi;
	}

	public long getPhi() {
		return _phi;
	}

	public void setPhi(long phi) {
		_phi = phi;
	}

	public String getDonViPhi() {
		if (_donViPhi == null) {
			return StringPool.BLANK;
		}
		else {
			return _donViPhi;
		}
	}

	public void setDonViPhi(String donViPhi) {
		_donViPhi = donViPhi;
	}

	public String getTenMauDonToKhai() {
		if (_tenMauDonToKhai == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenMauDonToKhai;
		}
	}

	public void setTenMauDonToKhai(String tenMauDonToKhai) {
		_tenMauDonToKhai = tenMauDonToKhai;
	}

	public String getYeuCauDieuKienThucHien() {
		if (_yeuCauDieuKienThucHien == null) {
			return StringPool.BLANK;
		}
		else {
			return _yeuCauDieuKienThucHien;
		}
	}

	public void setYeuCauDieuKienThucHien(String yeuCauDieuKienThucHien) {
		_yeuCauDieuKienThucHien = yeuCauDieuKienThucHien;
	}

	public String getCanCuPhapLy() {
		if (_canCuPhapLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _canCuPhapLy;
		}
	}

	public void setCanCuPhapLy(String canCuPhapLy) {
		_canCuPhapLy = canCuPhapLy;
	}

	public Long getCapCoQuanQuanLyId() {
		return _capCoQuanQuanLyId;
	}

	public void setCapCoQuanQuanLyId(Long capCoQuanQuanLyId) {
		_capCoQuanQuanLyId = capCoQuanQuanLyId;
	}

	public String getLinhVucThucHien() {
		if (_linhVucThucHien == null) {
			return StringPool.BLANK;
		}
		else {
			return _linhVucThucHien;
		}
	}

	public void setLinhVucThucHien(String linhVucThucHien) {
		_linhVucThucHien = linhVucThucHien;
	}

	public String getMaDNG() {
		if (_maDNG == null) {
			return StringPool.BLANK;
		}
		else {
			return _maDNG;
		}
	}

	public void setMaDNG(String maDNG) {
		_maDNG = maDNG;
	}

	public String getUengineProcessName() {
		if (_uengineProcessName == null) {
			return StringPool.BLANK;
		}
		else {
			return _uengineProcessName;
		}
	}

	public void setUengineProcessName(String uengineProcessName) {
		_uengineProcessName = uengineProcessName;
	}

	public Long getThuTucLienThongId() {
		return _thuTucLienThongId;
	}

	public void setThuTucLienThongId(Long thuTucLienThongId) {
		_thuTucLienThongId = thuTucLienThongId;
	}

	@Override
	public TraCuuThuTucHanhChinh toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TraCuuThuTucHanhChinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TraCuuThuTucHanhChinh.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TraCuuThuTucHanhChinhImpl traCuuThuTucHanhChinhImpl = new TraCuuThuTucHanhChinhImpl();

		traCuuThuTucHanhChinhImpl.setId(getId());
		traCuuThuTucHanhChinhImpl.setMa(getMa());
		traCuuThuTucHanhChinhImpl.setTen(getTen());
		traCuuThuTucHanhChinhImpl.setSoNgayXuLy(getSoNgayXuLy());
		traCuuThuTucHanhChinhImpl.setNgayTao(getNgayTao());
		traCuuThuTucHanhChinhImpl.setNgaySua(getNgaySua());
		traCuuThuTucHanhChinhImpl.setDaXoa(getDaXoa());
		traCuuThuTucHanhChinhImpl.setNguoiTao(getNguoiTao());
		traCuuThuTucHanhChinhImpl.setNguoiSua(getNguoiSua());
		traCuuThuTucHanhChinhImpl.setNhomThuTucHanhChinhId(getNhomThuTucHanhChinhId());
		traCuuThuTucHanhChinhImpl.setNhomThuTucHanhChinhTen(getNhomThuTucHanhChinhTen());
		traCuuThuTucHanhChinhImpl.setTrangThai(getTrangThai());
		traCuuThuTucHanhChinhImpl.setPhienBan(getPhienBan());
		traCuuThuTucHanhChinhImpl.setCanTichHop(getCanTichHop());
		traCuuThuTucHanhChinhImpl.setTrinhTuThucHien(getTrinhTuThucHien());
		traCuuThuTucHanhChinhImpl.setCachThucHien(getCachThucHien());
		traCuuThuTucHanhChinhImpl.setThanhPhanHoSo(getThanhPhanHoSo());
		traCuuThuTucHanhChinhImpl.setLePhi(getLePhi());
		traCuuThuTucHanhChinhImpl.setDonViLePhi(getDonViLePhi());
		traCuuThuTucHanhChinhImpl.setPhi(getPhi());
		traCuuThuTucHanhChinhImpl.setDonViPhi(getDonViPhi());
		traCuuThuTucHanhChinhImpl.setTenMauDonToKhai(getTenMauDonToKhai());
		traCuuThuTucHanhChinhImpl.setYeuCauDieuKienThucHien(getYeuCauDieuKienThucHien());
		traCuuThuTucHanhChinhImpl.setCanCuPhapLy(getCanCuPhapLy());
		traCuuThuTucHanhChinhImpl.setCapCoQuanQuanLyId(getCapCoQuanQuanLyId());
		traCuuThuTucHanhChinhImpl.setLinhVucThucHien(getLinhVucThucHien());
		traCuuThuTucHanhChinhImpl.setMaDNG(getMaDNG());
		traCuuThuTucHanhChinhImpl.setUengineProcessName(getUengineProcessName());
		traCuuThuTucHanhChinhImpl.setThuTucLienThongId(getThuTucLienThongId());

		traCuuThuTucHanhChinhImpl.resetOriginalValues();

		return traCuuThuTucHanhChinhImpl;
	}

	public int compareTo(TraCuuThuTucHanhChinh traCuuThuTucHanhChinh) {
		long primaryKey = traCuuThuTucHanhChinh.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TraCuuThuTucHanhChinh traCuuThuTucHanhChinh = null;

		try {
			traCuuThuTucHanhChinh = (TraCuuThuTucHanhChinh)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = traCuuThuTucHanhChinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TraCuuThuTucHanhChinh> toCacheModel() {
		TraCuuThuTucHanhChinhCacheModel traCuuThuTucHanhChinhCacheModel = new TraCuuThuTucHanhChinhCacheModel();

		traCuuThuTucHanhChinhCacheModel.id = getId();

		traCuuThuTucHanhChinhCacheModel.ma = getMa();

		String ma = traCuuThuTucHanhChinhCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.ma = null;
		}

		traCuuThuTucHanhChinhCacheModel.ten = getTen();

		String ten = traCuuThuTucHanhChinhCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.ten = null;
		}

		traCuuThuTucHanhChinhCacheModel.soNgayXuLy = getSoNgayXuLy();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			traCuuThuTucHanhChinhCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			traCuuThuTucHanhChinhCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			traCuuThuTucHanhChinhCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			traCuuThuTucHanhChinhCacheModel.ngaySua = Long.MIN_VALUE;
		}

		traCuuThuTucHanhChinhCacheModel.daXoa = getDaXoa();

		traCuuThuTucHanhChinhCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = traCuuThuTucHanhChinhCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.nguoiTao = null;
		}

		traCuuThuTucHanhChinhCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = traCuuThuTucHanhChinhCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.nguoiSua = null;
		}

		traCuuThuTucHanhChinhCacheModel.nhomThuTucHanhChinhId = getNhomThuTucHanhChinhId();

		traCuuThuTucHanhChinhCacheModel.nhomThuTucHanhChinhTen = getNhomThuTucHanhChinhTen();

		String nhomThuTucHanhChinhTen = traCuuThuTucHanhChinhCacheModel.nhomThuTucHanhChinhTen;

		if ((nhomThuTucHanhChinhTen != null) &&
				(nhomThuTucHanhChinhTen.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.nhomThuTucHanhChinhTen = null;
		}

		traCuuThuTucHanhChinhCacheModel.trangThai = getTrangThai();

		traCuuThuTucHanhChinhCacheModel.phienBan = getPhienBan();

		traCuuThuTucHanhChinhCacheModel.canTichHop = getCanTichHop();

		traCuuThuTucHanhChinhCacheModel.trinhTuThucHien = getTrinhTuThucHien();

		String trinhTuThucHien = traCuuThuTucHanhChinhCacheModel.trinhTuThucHien;

		if ((trinhTuThucHien != null) && (trinhTuThucHien.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.trinhTuThucHien = null;
		}

		traCuuThuTucHanhChinhCacheModel.cachThucHien = getCachThucHien();

		String cachThucHien = traCuuThuTucHanhChinhCacheModel.cachThucHien;

		if ((cachThucHien != null) && (cachThucHien.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.cachThucHien = null;
		}

		traCuuThuTucHanhChinhCacheModel.thanhPhanHoSo = getThanhPhanHoSo();

		String thanhPhanHoSo = traCuuThuTucHanhChinhCacheModel.thanhPhanHoSo;

		if ((thanhPhanHoSo != null) && (thanhPhanHoSo.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.thanhPhanHoSo = null;
		}

		traCuuThuTucHanhChinhCacheModel.lePhi = getLePhi();

		traCuuThuTucHanhChinhCacheModel.donViLePhi = getDonViLePhi();

		String donViLePhi = traCuuThuTucHanhChinhCacheModel.donViLePhi;

		if ((donViLePhi != null) && (donViLePhi.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.donViLePhi = null;
		}

		traCuuThuTucHanhChinhCacheModel.phi = getPhi();

		traCuuThuTucHanhChinhCacheModel.donViPhi = getDonViPhi();

		String donViPhi = traCuuThuTucHanhChinhCacheModel.donViPhi;

		if ((donViPhi != null) && (donViPhi.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.donViPhi = null;
		}

		traCuuThuTucHanhChinhCacheModel.tenMauDonToKhai = getTenMauDonToKhai();

		String tenMauDonToKhai = traCuuThuTucHanhChinhCacheModel.tenMauDonToKhai;

		if ((tenMauDonToKhai != null) && (tenMauDonToKhai.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.tenMauDonToKhai = null;
		}

		traCuuThuTucHanhChinhCacheModel.yeuCauDieuKienThucHien = getYeuCauDieuKienThucHien();

		String yeuCauDieuKienThucHien = traCuuThuTucHanhChinhCacheModel.yeuCauDieuKienThucHien;

		if ((yeuCauDieuKienThucHien != null) &&
				(yeuCauDieuKienThucHien.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.yeuCauDieuKienThucHien = null;
		}

		traCuuThuTucHanhChinhCacheModel.canCuPhapLy = getCanCuPhapLy();

		String canCuPhapLy = traCuuThuTucHanhChinhCacheModel.canCuPhapLy;

		if ((canCuPhapLy != null) && (canCuPhapLy.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.canCuPhapLy = null;
		}

		traCuuThuTucHanhChinhCacheModel.capCoQuanQuanLyId = getCapCoQuanQuanLyId();

		traCuuThuTucHanhChinhCacheModel.linhVucThucHien = getLinhVucThucHien();

		String linhVucThucHien = traCuuThuTucHanhChinhCacheModel.linhVucThucHien;

		if ((linhVucThucHien != null) && (linhVucThucHien.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.linhVucThucHien = null;
		}

		traCuuThuTucHanhChinhCacheModel.maDNG = getMaDNG();

		String maDNG = traCuuThuTucHanhChinhCacheModel.maDNG;

		if ((maDNG != null) && (maDNG.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.maDNG = null;
		}

		traCuuThuTucHanhChinhCacheModel.uengineProcessName = getUengineProcessName();

		String uengineProcessName = traCuuThuTucHanhChinhCacheModel.uengineProcessName;

		if ((uengineProcessName != null) && (uengineProcessName.length() == 0)) {
			traCuuThuTucHanhChinhCacheModel.uengineProcessName = null;
		}

		traCuuThuTucHanhChinhCacheModel.thuTucLienThongId = getThuTucLienThongId();

		return traCuuThuTucHanhChinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(59);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", soNgayXuLy=");
		sb.append(getSoNgayXuLy());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", nhomThuTucHanhChinhId=");
		sb.append(getNhomThuTucHanhChinhId());
		sb.append(", nhomThuTucHanhChinhTen=");
		sb.append(getNhomThuTucHanhChinhTen());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", canTichHop=");
		sb.append(getCanTichHop());
		sb.append(", trinhTuThucHien=");
		sb.append(getTrinhTuThucHien());
		sb.append(", cachThucHien=");
		sb.append(getCachThucHien());
		sb.append(", thanhPhanHoSo=");
		sb.append(getThanhPhanHoSo());
		sb.append(", lePhi=");
		sb.append(getLePhi());
		sb.append(", donViLePhi=");
		sb.append(getDonViLePhi());
		sb.append(", phi=");
		sb.append(getPhi());
		sb.append(", donViPhi=");
		sb.append(getDonViPhi());
		sb.append(", tenMauDonToKhai=");
		sb.append(getTenMauDonToKhai());
		sb.append(", yeuCauDieuKienThucHien=");
		sb.append(getYeuCauDieuKienThucHien());
		sb.append(", canCuPhapLy=");
		sb.append(getCanCuPhapLy());
		sb.append(", capCoQuanQuanLyId=");
		sb.append(getCapCoQuanQuanLyId());
		sb.append(", linhVucThucHien=");
		sb.append(getLinhVucThucHien());
		sb.append(", maDNG=");
		sb.append(getMaDNG());
		sb.append(", uengineProcessName=");
		sb.append(getUengineProcessName());
		sb.append(", thuTucLienThongId=");
		sb.append(getThuTucLienThongId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(91);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNgayXuLy</column-name><column-value><![CDATA[");
		sb.append(getSoNgayXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhomThuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getNhomThuTucHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhomThuTucHanhChinhTen</column-name><column-value><![CDATA[");
		sb.append(getNhomThuTucHanhChinhTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>canTichHop</column-name><column-value><![CDATA[");
		sb.append(getCanTichHop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trinhTuThucHien</column-name><column-value><![CDATA[");
		sb.append(getTrinhTuThucHien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cachThucHien</column-name><column-value><![CDATA[");
		sb.append(getCachThucHien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thanhPhanHoSo</column-name><column-value><![CDATA[");
		sb.append(getThanhPhanHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lePhi</column-name><column-value><![CDATA[");
		sb.append(getLePhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>donViLePhi</column-name><column-value><![CDATA[");
		sb.append(getDonViLePhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phi</column-name><column-value><![CDATA[");
		sb.append(getPhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>donViPhi</column-name><column-value><![CDATA[");
		sb.append(getDonViPhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenMauDonToKhai</column-name><column-value><![CDATA[");
		sb.append(getTenMauDonToKhai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yeuCauDieuKienThucHien</column-name><column-value><![CDATA[");
		sb.append(getYeuCauDieuKienThucHien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>canCuPhapLy</column-name><column-value><![CDATA[");
		sb.append(getCanCuPhapLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>capCoQuanQuanLyId</column-name><column-value><![CDATA[");
		sb.append(getCapCoQuanQuanLyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>linhVucThucHien</column-name><column-value><![CDATA[");
		sb.append(getLinhVucThucHien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maDNG</column-name><column-value><![CDATA[");
		sb.append(getMaDNG());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uengineProcessName</column-name><column-value><![CDATA[");
		sb.append(getUengineProcessName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thuTucLienThongId</column-name><column-value><![CDATA[");
		sb.append(getThuTucLienThongId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TraCuuThuTucHanhChinh.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TraCuuThuTucHanhChinh.class
		};
	private long _id;
	private String _ma;
	private String _ten;
	private long _soNgayXuLy;
	private Date _ngayTao;
	private Date _ngaySua;
	private int _daXoa;
	private String _nguoiTao;
	private String _nguoiSua;
	private long _nhomThuTucHanhChinhId;
	private String _nhomThuTucHanhChinhTen;
	private int _trangThai;
	private long _phienBan;
	private int _canTichHop;
	private String _trinhTuThucHien;
	private String _cachThucHien;
	private String _thanhPhanHoSo;
	private long _lePhi;
	private String _donViLePhi;
	private long _phi;
	private String _donViPhi;
	private String _tenMauDonToKhai;
	private String _yeuCauDieuKienThucHien;
	private String _canCuPhapLy;
	private Long _capCoQuanQuanLyId;
	private String _linhVucThucHien;
	private String _maDNG;
	private String _uengineProcessName;
	private Long _thuTucLienThongId;
	private transient ExpandoBridge _expandoBridge;
	private TraCuuThuTucHanhChinh _escapedModelProxy;
}