/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.report.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.oep.cmon.dao.report.model.Baocaochitiet;
import org.oep.cmon.dao.report.model.BaocaochitietModel;

import java.io.Serializable;

import java.sql.Types;

/**
 * The base model implementation for the Baocaochitiet service. Represents a row in the &quot;DNICT_Baocaochitiet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.report.model.BaocaochitietModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BaocaochitietImpl}.
 * </p>
 *
 * @author VIENPN
 * @see BaocaochitietImpl
 * @see org.oep.cmon.dao.report.model.Baocaochitiet
 * @see org.oep.cmon.dao.report.model.BaocaochitietModel
 * @generated
 */
public class BaocaochitietModelImpl extends BaseModelImpl<Baocaochitiet>
	implements BaocaochitietModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a baocaochitiet model instance should use the {@link org.oep.cmon.dao.report.model.Baocaochitiet} interface instead.
	 */
	public static final String TABLE_NAME = "DNICT_Baocaochitiet";
	public static final Object[][] TABLE_COLUMNS = {
			{ "LINHVUCID", Types.BIGINT },
			{ "MASOHOSO", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "TRANGTHAI", Types.VARCHAR },
			{ "DIACHIHIENNAY", Types.VARCHAR },
			{ "DIENTHOAIDIDONG", Types.VARCHAR },
			{ "HOTENNGUOINOPHOSO", Types.VARCHAR },
			{ "NGUOIDAIDIENPHAPLUAT", Types.VARCHAR },
			{ "NGAYNHANHOSO", Types.VARCHAR },
			{ "NGAYTRAKETQUA", Types.VARCHAR },
			{ "NGAYHENTRAKETQUA", Types.VARCHAR },
			{ "LINHVUC", Types.VARCHAR },
			{ "GHICHU", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DNICT_Baocaochitiet (LINHVUCID LONG,MASOHOSO VARCHAR(75) not null primary key,TEN VARCHAR(75) null,TRANGTHAI VARCHAR(75) null,DIACHIHIENNAY VARCHAR(75) null,DIENTHOAIDIDONG VARCHAR(75) null,HOTENNGUOINOPHOSO VARCHAR(75) null,NGUOIDAIDIENPHAPLUAT VARCHAR(75) null,NGAYNHANHOSO VARCHAR(75) null,NGAYTRAKETQUA VARCHAR(75) null,NGAYHENTRAKETQUA VARCHAR(75) null,LINHVUC VARCHAR(75) null,GHICHU VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DNICT_Baocaochitiet";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.report.model.Baocaochitiet"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.report.model.Baocaochitiet"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.report.model.Baocaochitiet"));

	public BaocaochitietModelImpl() {
	}

	public String getPrimaryKey() {
		return _MASOHOSO;
	}

	public void setPrimaryKey(String primaryKey) {
		setMASOHOSO(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _MASOHOSO;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return Baocaochitiet.class;
	}

	public String getModelClassName() {
		return Baocaochitiet.class.getName();
	}

	public long getLINHVUCID() {
		return _LINHVUCID;
	}

	public void setLINHVUCID(long LINHVUCID) {
		_LINHVUCID = LINHVUCID;
	}

	public String getMASOHOSO() {
		if (_MASOHOSO == null) {
			return StringPool.BLANK;
		}
		else {
			return _MASOHOSO;
		}
	}

	public void setMASOHOSO(String MASOHOSO) {
		_MASOHOSO = MASOHOSO;
	}

	public String getTEN() {
		if (_TEN == null) {
			return StringPool.BLANK;
		}
		else {
			return _TEN;
		}
	}

	public void setTEN(String TEN) {
		_TEN = TEN;
	}

	public String getTRANGTHAI() {
		if (_TRANGTHAI == null) {
			return StringPool.BLANK;
		}
		else {
			return _TRANGTHAI;
		}
	}

	public void setTRANGTHAI(String TRANGTHAI) {
		_TRANGTHAI = TRANGTHAI;
	}

	public String getDIACHIHIENNAY() {
		if (_DIACHIHIENNAY == null) {
			return StringPool.BLANK;
		}
		else {
			return _DIACHIHIENNAY;
		}
	}

	public void setDIACHIHIENNAY(String DIACHIHIENNAY) {
		_DIACHIHIENNAY = DIACHIHIENNAY;
	}

	public String getDIENTHOAIDIDONG() {
		if (_DIENTHOAIDIDONG == null) {
			return StringPool.BLANK;
		}
		else {
			return _DIENTHOAIDIDONG;
		}
	}

	public void setDIENTHOAIDIDONG(String DIENTHOAIDIDONG) {
		_DIENTHOAIDIDONG = DIENTHOAIDIDONG;
	}

	public String getHOTENNGUOINOPHOSO() {
		if (_HOTENNGUOINOPHOSO == null) {
			return StringPool.BLANK;
		}
		else {
			return _HOTENNGUOINOPHOSO;
		}
	}

	public void setHOTENNGUOINOPHOSO(String HOTENNGUOINOPHOSO) {
		_HOTENNGUOINOPHOSO = HOTENNGUOINOPHOSO;
	}

	public String getNGUOIDAIDIENPHAPLUAT() {
		if (_NGUOIDAIDIENPHAPLUAT == null) {
			return StringPool.BLANK;
		}
		else {
			return _NGUOIDAIDIENPHAPLUAT;
		}
	}

	public void setNGUOIDAIDIENPHAPLUAT(String NGUOIDAIDIENPHAPLUAT) {
		_NGUOIDAIDIENPHAPLUAT = NGUOIDAIDIENPHAPLUAT;
	}

	public String getNGAYNHANHOSO() {
		if (_NGAYNHANHOSO == null) {
			return StringPool.BLANK;
		}
		else {
			return _NGAYNHANHOSO;
		}
	}

	public void setNGAYNHANHOSO(String NGAYNHANHOSO) {
		_NGAYNHANHOSO = NGAYNHANHOSO;
	}

	public String getNGAYTRAKETQUA() {
		if (_NGAYTRAKETQUA == null) {
			return StringPool.BLANK;
		}
		else {
			return _NGAYTRAKETQUA;
		}
	}

	public void setNGAYTRAKETQUA(String NGAYTRAKETQUA) {
		_NGAYTRAKETQUA = NGAYTRAKETQUA;
	}

	public String getNGAYHENTRAKETQUA() {
		if (_NGAYHENTRAKETQUA == null) {
			return StringPool.BLANK;
		}
		else {
			return _NGAYHENTRAKETQUA;
		}
	}

	public void setNGAYHENTRAKETQUA(String NGAYHENTRAKETQUA) {
		_NGAYHENTRAKETQUA = NGAYHENTRAKETQUA;
	}

	public String getLINHVUC() {
		if (_LINHVUC == null) {
			return StringPool.BLANK;
		}
		else {
			return _LINHVUC;
		}
	}

	public void setLINHVUC(String LINHVUC) {
		_LINHVUC = LINHVUC;
	}

	public String getGHICHU() {
		if (_GHICHU == null) {
			return StringPool.BLANK;
		}
		else {
			return _GHICHU;
		}
	}

	public void setGHICHU(String GHICHU) {
		_GHICHU = GHICHU;
	}

	@Override
	public Baocaochitiet toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Baocaochitiet)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		BaocaochitietImpl baocaochitietImpl = new BaocaochitietImpl();

		baocaochitietImpl.setLINHVUCID(getLINHVUCID());
		baocaochitietImpl.setMASOHOSO(getMASOHOSO());
		baocaochitietImpl.setTEN(getTEN());
		baocaochitietImpl.setTRANGTHAI(getTRANGTHAI());
		baocaochitietImpl.setDIACHIHIENNAY(getDIACHIHIENNAY());
		baocaochitietImpl.setDIENTHOAIDIDONG(getDIENTHOAIDIDONG());
		baocaochitietImpl.setHOTENNGUOINOPHOSO(getHOTENNGUOINOPHOSO());
		baocaochitietImpl.setNGUOIDAIDIENPHAPLUAT(getNGUOIDAIDIENPHAPLUAT());
		baocaochitietImpl.setNGAYNHANHOSO(getNGAYNHANHOSO());
		baocaochitietImpl.setNGAYTRAKETQUA(getNGAYTRAKETQUA());
		baocaochitietImpl.setNGAYHENTRAKETQUA(getNGAYHENTRAKETQUA());
		baocaochitietImpl.setLINHVUC(getLINHVUC());
		baocaochitietImpl.setGHICHU(getGHICHU());

		baocaochitietImpl.resetOriginalValues();

		return baocaochitietImpl;
	}

	public int compareTo(Baocaochitiet baocaochitiet) {
		String primaryKey = baocaochitiet.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Baocaochitiet baocaochitiet = null;

		try {
			baocaochitiet = (Baocaochitiet)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = baocaochitiet.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Baocaochitiet> toCacheModel() {
		BaocaochitietCacheModel baocaochitietCacheModel = new BaocaochitietCacheModel();

		baocaochitietCacheModel.LINHVUCID = getLINHVUCID();

		baocaochitietCacheModel.MASOHOSO = getMASOHOSO();

		String MASOHOSO = baocaochitietCacheModel.MASOHOSO;

		if ((MASOHOSO != null) && (MASOHOSO.length() == 0)) {
			baocaochitietCacheModel.MASOHOSO = null;
		}

		baocaochitietCacheModel.TEN = getTEN();

		String TEN = baocaochitietCacheModel.TEN;

		if ((TEN != null) && (TEN.length() == 0)) {
			baocaochitietCacheModel.TEN = null;
		}

		baocaochitietCacheModel.TRANGTHAI = getTRANGTHAI();

		String TRANGTHAI = baocaochitietCacheModel.TRANGTHAI;

		if ((TRANGTHAI != null) && (TRANGTHAI.length() == 0)) {
			baocaochitietCacheModel.TRANGTHAI = null;
		}

		baocaochitietCacheModel.DIACHIHIENNAY = getDIACHIHIENNAY();

		String DIACHIHIENNAY = baocaochitietCacheModel.DIACHIHIENNAY;

		if ((DIACHIHIENNAY != null) && (DIACHIHIENNAY.length() == 0)) {
			baocaochitietCacheModel.DIACHIHIENNAY = null;
		}

		baocaochitietCacheModel.DIENTHOAIDIDONG = getDIENTHOAIDIDONG();

		String DIENTHOAIDIDONG = baocaochitietCacheModel.DIENTHOAIDIDONG;

		if ((DIENTHOAIDIDONG != null) && (DIENTHOAIDIDONG.length() == 0)) {
			baocaochitietCacheModel.DIENTHOAIDIDONG = null;
		}

		baocaochitietCacheModel.HOTENNGUOINOPHOSO = getHOTENNGUOINOPHOSO();

		String HOTENNGUOINOPHOSO = baocaochitietCacheModel.HOTENNGUOINOPHOSO;

		if ((HOTENNGUOINOPHOSO != null) && (HOTENNGUOINOPHOSO.length() == 0)) {
			baocaochitietCacheModel.HOTENNGUOINOPHOSO = null;
		}

		baocaochitietCacheModel.NGUOIDAIDIENPHAPLUAT = getNGUOIDAIDIENPHAPLUAT();

		String NGUOIDAIDIENPHAPLUAT = baocaochitietCacheModel.NGUOIDAIDIENPHAPLUAT;

		if ((NGUOIDAIDIENPHAPLUAT != null) &&
				(NGUOIDAIDIENPHAPLUAT.length() == 0)) {
			baocaochitietCacheModel.NGUOIDAIDIENPHAPLUAT = null;
		}

		baocaochitietCacheModel.NGAYNHANHOSO = getNGAYNHANHOSO();

		String NGAYNHANHOSO = baocaochitietCacheModel.NGAYNHANHOSO;

		if ((NGAYNHANHOSO != null) && (NGAYNHANHOSO.length() == 0)) {
			baocaochitietCacheModel.NGAYNHANHOSO = null;
		}

		baocaochitietCacheModel.NGAYTRAKETQUA = getNGAYTRAKETQUA();

		String NGAYTRAKETQUA = baocaochitietCacheModel.NGAYTRAKETQUA;

		if ((NGAYTRAKETQUA != null) && (NGAYTRAKETQUA.length() == 0)) {
			baocaochitietCacheModel.NGAYTRAKETQUA = null;
		}

		baocaochitietCacheModel.NGAYHENTRAKETQUA = getNGAYHENTRAKETQUA();

		String NGAYHENTRAKETQUA = baocaochitietCacheModel.NGAYHENTRAKETQUA;

		if ((NGAYHENTRAKETQUA != null) && (NGAYHENTRAKETQUA.length() == 0)) {
			baocaochitietCacheModel.NGAYHENTRAKETQUA = null;
		}

		baocaochitietCacheModel.LINHVUC = getLINHVUC();

		String LINHVUC = baocaochitietCacheModel.LINHVUC;

		if ((LINHVUC != null) && (LINHVUC.length() == 0)) {
			baocaochitietCacheModel.LINHVUC = null;
		}

		baocaochitietCacheModel.GHICHU = getGHICHU();

		String GHICHU = baocaochitietCacheModel.GHICHU;

		if ((GHICHU != null) && (GHICHU.length() == 0)) {
			baocaochitietCacheModel.GHICHU = null;
		}

		return baocaochitietCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{LINHVUCID=");
		sb.append(getLINHVUCID());
		sb.append(", MASOHOSO=");
		sb.append(getMASOHOSO());
		sb.append(", TEN=");
		sb.append(getTEN());
		sb.append(", TRANGTHAI=");
		sb.append(getTRANGTHAI());
		sb.append(", DIACHIHIENNAY=");
		sb.append(getDIACHIHIENNAY());
		sb.append(", DIENTHOAIDIDONG=");
		sb.append(getDIENTHOAIDIDONG());
		sb.append(", HOTENNGUOINOPHOSO=");
		sb.append(getHOTENNGUOINOPHOSO());
		sb.append(", NGUOIDAIDIENPHAPLUAT=");
		sb.append(getNGUOIDAIDIENPHAPLUAT());
		sb.append(", NGAYNHANHOSO=");
		sb.append(getNGAYNHANHOSO());
		sb.append(", NGAYTRAKETQUA=");
		sb.append(getNGAYTRAKETQUA());
		sb.append(", NGAYHENTRAKETQUA=");
		sb.append(getNGAYHENTRAKETQUA());
		sb.append(", LINHVUC=");
		sb.append(getLINHVUC());
		sb.append(", GHICHU=");
		sb.append(getGHICHU());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.report.model.Baocaochitiet");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>LINHVUCID</column-name><column-value><![CDATA[");
		sb.append(getLINHVUCID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MASOHOSO</column-name><column-value><![CDATA[");
		sb.append(getMASOHOSO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TEN</column-name><column-value><![CDATA[");
		sb.append(getTEN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TRANGTHAI</column-name><column-value><![CDATA[");
		sb.append(getTRANGTHAI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DIACHIHIENNAY</column-name><column-value><![CDATA[");
		sb.append(getDIACHIHIENNAY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DIENTHOAIDIDONG</column-name><column-value><![CDATA[");
		sb.append(getDIENTHOAIDIDONG());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HOTENNGUOINOPHOSO</column-name><column-value><![CDATA[");
		sb.append(getHOTENNGUOINOPHOSO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NGUOIDAIDIENPHAPLUAT</column-name><column-value><![CDATA[");
		sb.append(getNGUOIDAIDIENPHAPLUAT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NGAYNHANHOSO</column-name><column-value><![CDATA[");
		sb.append(getNGAYNHANHOSO());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NGAYTRAKETQUA</column-name><column-value><![CDATA[");
		sb.append(getNGAYTRAKETQUA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NGAYHENTRAKETQUA</column-name><column-value><![CDATA[");
		sb.append(getNGAYHENTRAKETQUA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LINHVUC</column-name><column-value><![CDATA[");
		sb.append(getLINHVUC());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GHICHU</column-name><column-value><![CDATA[");
		sb.append(getGHICHU());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Baocaochitiet.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Baocaochitiet.class
		};
	private long _LINHVUCID;
	private String _MASOHOSO;
	private String _TEN;
	private String _TRANGTHAI;
	private String _DIACHIHIENNAY;
	private String _DIENTHOAIDIDONG;
	private String _HOTENNGUOINOPHOSO;
	private String _NGUOIDAIDIENPHAPLUAT;
	private String _NGAYNHANHOSO;
	private String _NGAYTRAKETQUA;
	private String _NGAYHENTRAKETQUA;
	private String _LINHVUC;
	private String _GHICHU;
	private Baocaochitiet _escapedModelProxy;
}