/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.report.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.report.model.DanhMucRole;
import org.oep.cmon.dao.report.model.DanhMucRoleModel;

import java.io.Serializable;

import java.sql.Types;

/**
 * The base model implementation for the DanhMucRole service. Represents a row in the &quot;CMON_RPDANHMUCROLE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.report.model.DanhMucRoleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanhMucRoleImpl}.
 * </p>
 *
 * @author VIENPN
 * @see DanhMucRoleImpl
 * @see org.oep.cmon.dao.report.model.DanhMucRole
 * @see org.oep.cmon.dao.report.model.DanhMucRoleModel
 * @generated
 */
public class DanhMucRoleModelImpl extends BaseModelImpl<DanhMucRole>
	implements DanhMucRoleModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danh muc role model instance should use the {@link org.oep.cmon.dao.report.model.DanhMucRole} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_RPDANHMUCROLE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NAME", Types.VARCHAR },
			{ "ORDERS", Types.INTEGER },
			{ "STATUS", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_RPDANHMUCROLE (ID LONG not null primary key,NAME VARCHAR(75) null,ORDERS INTEGER,STATUS INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_RPDANHMUCROLE";
	public static final String ORDER_BY_JPQL = " ORDER BY danhMucRole.ID DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_RPDANHMUCROLE.ID DESC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.report.model.DanhMucRole"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.report.model.DanhMucRole"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.report.model.DanhMucRole"));

	public DanhMucRoleModelImpl() {
	}

	public long getPrimaryKey() {
		return _ID;
	}

	public void setPrimaryKey(long primaryKey) {
		setID(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_ID);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DanhMucRole.class;
	}

	public String getModelClassName() {
		return DanhMucRole.class.getName();
	}

	public long getID() {
		return _ID;
	}

	public void setID(long ID) {
		_ID = ID;
	}

	public String getNAME() {
		if (_NAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _NAME;
		}
	}

	public void setNAME(String NAME) {
		_NAME = NAME;
	}

	public int getORDERS() {
		return _ORDERS;
	}

	public void setORDERS(int ORDERS) {
		_ORDERS = ORDERS;
	}

	public int getSTATUS() {
		return _STATUS;
	}

	public void setSTATUS(int STATUS) {
		_STATUS = STATUS;
	}

	@Override
	public DanhMucRole toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DanhMucRole)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DanhMucRole.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DanhMucRoleImpl danhMucRoleImpl = new DanhMucRoleImpl();

		danhMucRoleImpl.setID(getID());
		danhMucRoleImpl.setNAME(getNAME());
		danhMucRoleImpl.setORDERS(getORDERS());
		danhMucRoleImpl.setSTATUS(getSTATUS());

		danhMucRoleImpl.resetOriginalValues();

		return danhMucRoleImpl;
	}

	public int compareTo(DanhMucRole danhMucRole) {
		int value = 0;

		if (getID() < danhMucRole.getID()) {
			value = -1;
		}
		else if (getID() > danhMucRole.getID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DanhMucRole danhMucRole = null;

		try {
			danhMucRole = (DanhMucRole)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = danhMucRole.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DanhMucRole> toCacheModel() {
		DanhMucRoleCacheModel danhMucRoleCacheModel = new DanhMucRoleCacheModel();

		danhMucRoleCacheModel.ID = getID();

		danhMucRoleCacheModel.NAME = getNAME();

		String NAME = danhMucRoleCacheModel.NAME;

		if ((NAME != null) && (NAME.length() == 0)) {
			danhMucRoleCacheModel.NAME = null;
		}

		danhMucRoleCacheModel.ORDERS = getORDERS();

		danhMucRoleCacheModel.STATUS = getSTATUS();

		return danhMucRoleCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{ID=");
		sb.append(getID());
		sb.append(", NAME=");
		sb.append(getNAME());
		sb.append(", ORDERS=");
		sb.append(getORDERS());
		sb.append(", STATUS=");
		sb.append(getSTATUS());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.report.model.DanhMucRole");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ID</column-name><column-value><![CDATA[");
		sb.append(getID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NAME</column-name><column-value><![CDATA[");
		sb.append(getNAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ORDERS</column-name><column-value><![CDATA[");
		sb.append(getORDERS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>STATUS</column-name><column-value><![CDATA[");
		sb.append(getSTATUS());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanhMucRole.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DanhMucRole.class
		};
	private long _ID;
	private String _NAME;
	private int _ORDERS;
	private int _STATUS;
	private transient ExpandoBridge _expandoBridge;
	private DanhMucRole _escapedModelProxy;
}