/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.report.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.report.model.Role2DonViBaoCao;
import org.oep.cmon.dao.report.model.Role2DonViBaoCaoModel;

import java.io.Serializable;

import java.sql.Types;

/**
 * The base model implementation for the Role2DonViBaoCao service. Represents a row in the &quot;CMON_RPROLE2DONVIBAOCAO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.report.model.Role2DonViBaoCaoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Role2DonViBaoCaoImpl}.
 * </p>
 *
 * @author VIENPN
 * @see Role2DonViBaoCaoImpl
 * @see org.oep.cmon.dao.report.model.Role2DonViBaoCao
 * @see org.oep.cmon.dao.report.model.Role2DonViBaoCaoModel
 * @generated
 */
public class Role2DonViBaoCaoModelImpl extends BaseModelImpl<Role2DonViBaoCao>
	implements Role2DonViBaoCaoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a role2 don vi bao cao model instance should use the {@link org.oep.cmon.dao.report.model.Role2DonViBaoCao} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_RPROLE2DONVIBAOCAO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "RPDANHMUCROLEID", Types.BIGINT },
			{ "BAOCAOID", Types.BIGINT },
			{ "DONVIID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_RPROLE2DONVIBAOCAO (ID LONG not null primary key,RPDANHMUCROLEID LONG,BAOCAOID LONG,DONVIID LONG)";
	public static final String TABLE_SQL_DROP = "drop table CMON_RPROLE2DONVIBAOCAO";
	public static final String ORDER_BY_JPQL = " ORDER BY role2DonViBaoCao.ID DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_RPROLE2DONVIBAOCAO.ID DESC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.report.model.Role2DonViBaoCao"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.report.model.Role2DonViBaoCao"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.report.model.Role2DonViBaoCao"));

	public Role2DonViBaoCaoModelImpl() {
	}

	public long getPrimaryKey() {
		return _ID;
	}

	public void setPrimaryKey(long primaryKey) {
		setID(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_ID);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Role2DonViBaoCao.class;
	}

	public String getModelClassName() {
		return Role2DonViBaoCao.class.getName();
	}

	public long getID() {
		return _ID;
	}

	public void setID(long ID) {
		_ID = ID;
	}

	public long getRPDANHMUCROLEID() {
		return _RPDANHMUCROLEID;
	}

	public void setRPDANHMUCROLEID(long RPDANHMUCROLEID) {
		_RPDANHMUCROLEID = RPDANHMUCROLEID;
	}

	public long getRPDANHMUCBAOCAOID() {
		return _RPDANHMUCBAOCAOID;
	}

	public void setRPDANHMUCBAOCAOID(long RPDANHMUCBAOCAOID) {
		_RPDANHMUCBAOCAOID = RPDANHMUCBAOCAOID;
	}

	public long getCOQUANQUANLYID() {
		return _COQUANQUANLYID;
	}

	public void setCOQUANQUANLYID(long COQUANQUANLYID) {
		_COQUANQUANLYID = COQUANQUANLYID;
	}

	@Override
	public Role2DonViBaoCao toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Role2DonViBaoCao)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					Role2DonViBaoCao.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		Role2DonViBaoCaoImpl role2DonViBaoCaoImpl = new Role2DonViBaoCaoImpl();

		role2DonViBaoCaoImpl.setID(getID());
		role2DonViBaoCaoImpl.setRPDANHMUCROLEID(getRPDANHMUCROLEID());
		role2DonViBaoCaoImpl.setRPDANHMUCBAOCAOID(getRPDANHMUCBAOCAOID());
		role2DonViBaoCaoImpl.setCOQUANQUANLYID(getCOQUANQUANLYID());

		role2DonViBaoCaoImpl.resetOriginalValues();

		return role2DonViBaoCaoImpl;
	}

	public int compareTo(Role2DonViBaoCao role2DonViBaoCao) {
		int value = 0;

		if (getID() < role2DonViBaoCao.getID()) {
			value = -1;
		}
		else if (getID() > role2DonViBaoCao.getID()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Role2DonViBaoCao role2DonViBaoCao = null;

		try {
			role2DonViBaoCao = (Role2DonViBaoCao)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = role2DonViBaoCao.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Role2DonViBaoCao> toCacheModel() {
		Role2DonViBaoCaoCacheModel role2DonViBaoCaoCacheModel = new Role2DonViBaoCaoCacheModel();

		role2DonViBaoCaoCacheModel.ID = getID();

		role2DonViBaoCaoCacheModel.RPDANHMUCROLEID = getRPDANHMUCROLEID();

		role2DonViBaoCaoCacheModel.RPDANHMUCBAOCAOID = getRPDANHMUCBAOCAOID();

		role2DonViBaoCaoCacheModel.COQUANQUANLYID = getCOQUANQUANLYID();

		return role2DonViBaoCaoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{ID=");
		sb.append(getID());
		sb.append(", RPDANHMUCROLEID=");
		sb.append(getRPDANHMUCROLEID());
		sb.append(", RPDANHMUCBAOCAOID=");
		sb.append(getRPDANHMUCBAOCAOID());
		sb.append(", COQUANQUANLYID=");
		sb.append(getCOQUANQUANLYID());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.report.model.Role2DonViBaoCao");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ID</column-name><column-value><![CDATA[");
		sb.append(getID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RPDANHMUCROLEID</column-name><column-value><![CDATA[");
		sb.append(getRPDANHMUCROLEID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RPDANHMUCBAOCAOID</column-name><column-value><![CDATA[");
		sb.append(getRPDANHMUCBAOCAOID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COQUANQUANLYID</column-name><column-value><![CDATA[");
		sb.append(getCOQUANQUANLYID());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Role2DonViBaoCao.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Role2DonViBaoCao.class
		};
	private long _ID;
	private long _RPDANHMUCROLEID;
	private long _RPDANHMUCBAOCAOID;
	private long _COQUANQUANLYID;
	private transient ExpandoBridge _expandoBridge;
	private Role2DonViBaoCao _escapedModelProxy;
}