/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dn.model.DoanhNghiep;
import org.oep.cmon.dao.dn.model.DoanhNghiepModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the DoanhNghiep service. Represents a row in the &quot;BRMS_DOANHNGHIEP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dn.model.DoanhNghiepModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DoanhNghiepImpl}.
 * </p>
 *
 * @author Liemnn
 * @see DoanhNghiepImpl
 * @see org.oep.cmon.dao.dn.model.DoanhNghiep
 * @see org.oep.cmon.dao.dn.model.DoanhNghiepModel
 * @generated
 */
public class DoanhNghiepModelImpl extends BaseModelImpl<DoanhNghiep>
	implements DoanhNghiepModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a doanh nghiep model instance should use the {@link org.oep.cmon.dao.dn.model.DoanhNghiep} interface instead.
	 */
	public static final String TABLE_NAME = "BRMS_DOANHNGHIEP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "MASOTHUE", Types.VARCHAR },
			{ "TENTIENGNUOCNGOAI", Types.VARCHAR },
			{ "TENVIETTAT", Types.VARCHAR },
			{ "DIACHIDOANHNGHIEP", Types.VARCHAR },
			{ "DIENTHOAIDOANHNGHIEP", Types.VARCHAR },
			{ "FAX", Types.VARCHAR },
			{ "EMAILDOANHNGHIEP", Types.VARCHAR },
			{ "WEBSITE", Types.VARCHAR },
			{ "TONGSOVON", Types.BIGINT },
			{ "MOTANGANHNGHEKINHDOANH", Types.VARCHAR },
			{ "SOGCNDKKD", Types.VARCHAR },
			{ "NGAYCAPGCNDKKD", Types.TIMESTAMP },
			{ "NOILUUTRUID", Types.BIGINT },
			{ "NGAYDIEULEDUOCTHONGQUA", Types.TIMESTAMP },
			{ "TENCHINHANH", Types.VARCHAR },
			{ "DIACHICHINHANH", Types.VARCHAR },
			{ "TENVANPHONGDAIDIEN", Types.VARCHAR },
			{ "DIACHIVANPHONGDAIDIEN", Types.VARCHAR },
			{ "NGAYBATDAUTAMNGUNG", Types.TIMESTAMP },
			{ "NGAYKETTHUCTAMNGUNG", Types.TIMESTAMP },
			{ "LYDOTAMNGUNG", Types.VARCHAR },
			{ "NGAYCHAMDUTHOATDONGKD", Types.TIMESTAMP },
			{ "LOAI", Types.BIGINT },
			{ "DIACHIDOANHNGHIEPHUYENID", Types.BIGINT },
			{ "DIACHIDOANHNGHIEPTINHID", Types.BIGINT },
			{ "DIACHIDOANHNGHIEPXAID", Types.BIGINT },
			{ "LOAIDOITUONGID", Types.BIGINT },
			{ "NGUOIDAIDIENID", Types.BIGINT },
			{ "TRANGTHAIDOANHNGHIEPID", Types.BIGINT },
			{ "VONDIEULE", Types.BIGINT },
			{ "VONTOITHIEUMOTXAVIEN", Types.BIGINT },
			{ "GHICHU", Types.VARCHAR },
			{ "QUOCGIAID", Types.BIGINT },
			{ "COQUANCAPID", Types.BIGINT },
			{ "TENCOQUANCAP", Types.BIGINT },
			{ "SOLANDIEUCHINH", Types.VARCHAR },
			{ "NGAYDIEUCHINH", Types.TIMESTAMP },
			{ "CHUCVUNGUOIDAIDIEN", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "CHAID", Types.BIGINT },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "TAIKHOANNGUOIDUNGID", Types.BIGINT },
			{ "TENDIADIEMKINHDOANH", Types.VARCHAR },
			{ "NGAYDANGKYKINHDOANH", Types.TIMESTAMP },
			{ "LOAIHINHDOANHNGHIEPID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table BRMS_DOANHNGHIEP (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,MASOTHUE VARCHAR(75) null,TENTIENGNUOCNGOAI VARCHAR(75) null,TENVIETTAT VARCHAR(75) null,DIACHIDOANHNGHIEP VARCHAR(75) null,DIENTHOAIDOANHNGHIEP VARCHAR(75) null,FAX VARCHAR(75) null,EMAILDOANHNGHIEP VARCHAR(75) null,WEBSITE VARCHAR(75) null,TONGSOVON LONG,MOTANGANHNGHEKINHDOANH VARCHAR(75) null,SOGCNDKKD VARCHAR(75) null,NGAYCAPGCNDKKD DATE null,NOILUUTRUID LONG,NGAYDIEULEDUOCTHONGQUA DATE null,TENCHINHANH VARCHAR(75) null,DIACHICHINHANH VARCHAR(75) null,TENVANPHONGDAIDIEN VARCHAR(75) null,DIACHIVANPHONGDAIDIEN VARCHAR(75) null,NGAYBATDAUTAMNGUNG DATE null,NGAYKETTHUCTAMNGUNG DATE null,LYDOTAMNGUNG VARCHAR(75) null,NGAYCHAMDUTHOATDONGKD DATE null,LOAI LONG,DIACHIDOANHNGHIEPHUYENID LONG null,DIACHIDOANHNGHIEPTINHID LONG null,DIACHIDOANHNGHIEPXAID LONG null,LOAIDOITUONGID LONG null,NGUOIDAIDIENID LONG null,TRANGTHAIDOANHNGHIEPID LONG null,VONDIEULE LONG,VONTOITHIEUMOTXAVIEN LONG,GHICHU VARCHAR(75) null,QUOCGIAID LONG null,COQUANCAPID LONG null,TENCOQUANCAP LONG,SOLANDIEUCHINH VARCHAR(75) null,NGAYDIEUCHINH DATE null,CHUCVUNGUOIDAIDIEN VARCHAR(75) null,NGAYTAO DATE null,DAXOA INTEGER,NGAYSUA DATE null,CHAID LONG null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,TAIKHOANNGUOIDUNGID LONG,TENDIADIEMKINHDOANH VARCHAR(75) null,NGAYDANGKYKINHDOANH DATE null,LOAIHINHDOANHNGHIEPID LONG null)";
	public static final String TABLE_SQL_DROP = "drop table BRMS_DOANHNGHIEP";
	public static final String ORDER_BY_JPQL = " ORDER BY doanhNghiep.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY BRMS_DOANHNGHIEP.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dn.model.DoanhNghiep"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dn.model.DoanhNghiep"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.dn.model.DoanhNghiep"),
			true);
	public static long CHAID_COLUMN_BITMASK = 1L;
	public static long LOAIDOITUONGID_COLUMN_BITMASK = 2L;
	public static long LOAIHINHDOANHNGHIEPID_COLUMN_BITMASK = 4L;
	public static long MA_COLUMN_BITMASK = 8L;
	public static long MASOTHUE_COLUMN_BITMASK = 16L;
	public static long NGUOIDAIDIENID_COLUMN_BITMASK = 32L;
	public static long SOGCNDKKD_COLUMN_BITMASK = 64L;
	public static long TEN_COLUMN_BITMASK = 128L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dn.model.DoanhNghiep"));

	public DoanhNghiepModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DoanhNghiep.class;
	}

	public String getModelClassName() {
		return DoanhNghiep.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	public String getMaSoThue() {
		if (_maSoThue == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoThue;
		}
	}

	public void setMaSoThue(String maSoThue) {
		_columnBitmask |= MASOTHUE_COLUMN_BITMASK;

		if (_originalMaSoThue == null) {
			_originalMaSoThue = _maSoThue;
		}

		_maSoThue = maSoThue;
	}

	public String getOriginalMaSoThue() {
		return GetterUtil.getString(_originalMaSoThue);
	}

	public String getTenTiengNuocNgoai() {
		if (_tenTiengNuocNgoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenTiengNuocNgoai;
		}
	}

	public void setTenTiengNuocNgoai(String tenTiengNuocNgoai) {
		_tenTiengNuocNgoai = tenTiengNuocNgoai;
	}

	public String getTenVietTat() {
		if (_tenVietTat == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenVietTat;
		}
	}

	public void setTenVietTat(String tenVietTat) {
		_tenVietTat = tenVietTat;
	}

	public String getDiaChiDoanhNghiep() {
		if (_diaChiDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiDoanhNghiep;
		}
	}

	public void setDiaChiDoanhNghiep(String diaChiDoanhNghiep) {
		_diaChiDoanhNghiep = diaChiDoanhNghiep;
	}

	public String getDienThoaiDoanhNghiep() {
		if (_dienThoaiDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoaiDoanhNghiep;
		}
	}

	public void setDienThoaiDoanhNghiep(String dienThoaiDoanhNghiep) {
		_dienThoaiDoanhNghiep = dienThoaiDoanhNghiep;
	}

	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	public void setFax(String fax) {
		_fax = fax;
	}

	public String getEmailDoanhNghiep() {
		if (_emailDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailDoanhNghiep;
		}
	}

	public void setEmailDoanhNghiep(String emailDoanhNghiep) {
		_emailDoanhNghiep = emailDoanhNghiep;
	}

	public String getWebsite() {
		if (_website == null) {
			return StringPool.BLANK;
		}
		else {
			return _website;
		}
	}

	public void setWebsite(String website) {
		_website = website;
	}

	public long getTongSoVon() {
		return _tongSoVon;
	}

	public void setTongSoVon(long tongSoVon) {
		_tongSoVon = tongSoVon;
	}

	public String getMoTaNganhNgheKinhDoanh() {
		if (_moTaNganhNgheKinhDoanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTaNganhNgheKinhDoanh;
		}
	}

	public void setMoTaNganhNgheKinhDoanh(String moTaNganhNgheKinhDoanh) {
		_moTaNganhNgheKinhDoanh = moTaNganhNgheKinhDoanh;
	}

	public String getSoGCNDKKD() {
		if (_soGCNDKKD == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGCNDKKD;
		}
	}

	public void setSoGCNDKKD(String soGCNDKKD) {
		_columnBitmask |= SOGCNDKKD_COLUMN_BITMASK;

		if (_originalSoGCNDKKD == null) {
			_originalSoGCNDKKD = _soGCNDKKD;
		}

		_soGCNDKKD = soGCNDKKD;
	}

	public String getOriginalSoGCNDKKD() {
		return GetterUtil.getString(_originalSoGCNDKKD);
	}

	public Date getNgayCapGCNDKKD() {
		return _ngayCapGCNDKKD;
	}

	public void setNgayCapGCNDKKD(Date ngayCapGCNDKKD) {
		_ngayCapGCNDKKD = ngayCapGCNDKKD;
	}

	public long getNoiLuuTruId() {
		return _noiLuuTruId;
	}

	public void setNoiLuuTruId(long noiLuuTruId) {
		_noiLuuTruId = noiLuuTruId;
	}

	public Date getNgayDieuLeDuocThongQua() {
		return _ngayDieuLeDuocThongQua;
	}

	public void setNgayDieuLeDuocThongQua(Date ngayDieuLeDuocThongQua) {
		_ngayDieuLeDuocThongQua = ngayDieuLeDuocThongQua;
	}

	public String getTenChiNhanh() {
		if (_tenChiNhanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenChiNhanh;
		}
	}

	public void setTenChiNhanh(String tenChiNhanh) {
		_tenChiNhanh = tenChiNhanh;
	}

	public String getDiaChiChiNhanh() {
		if (_diaChiChiNhanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiChiNhanh;
		}
	}

	public void setDiaChiChiNhanh(String diaChiChiNhanh) {
		_diaChiChiNhanh = diaChiChiNhanh;
	}

	public String getTenVanPhongDaiDien() {
		if (_tenVanPhongDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenVanPhongDaiDien;
		}
	}

	public void setTenVanPhongDaiDien(String tenVanPhongDaiDien) {
		_tenVanPhongDaiDien = tenVanPhongDaiDien;
	}

	public String getDiaChiVanPhongDaiDien() {
		if (_diaChiVanPhongDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiVanPhongDaiDien;
		}
	}

	public void setDiaChiVanPhongDaiDien(String diaChiVanPhongDaiDien) {
		_diaChiVanPhongDaiDien = diaChiVanPhongDaiDien;
	}

	public Date getNgayBatDauTamNgung() {
		return _ngayBatDauTamNgung;
	}

	public void setNgayBatDauTamNgung(Date ngayBatDauTamNgung) {
		_ngayBatDauTamNgung = ngayBatDauTamNgung;
	}

	public Date getNgayKetThucTamNgung() {
		return _ngayKetThucTamNgung;
	}

	public void setNgayKetThucTamNgung(Date ngayKetThucTamNgung) {
		_ngayKetThucTamNgung = ngayKetThucTamNgung;
	}

	public String getLyDoTamNgung() {
		if (_lyDoTamNgung == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoTamNgung;
		}
	}

	public void setLyDoTamNgung(String lyDoTamNgung) {
		_lyDoTamNgung = lyDoTamNgung;
	}

	public Date getNgayChamDutHoatDongKD() {
		return _ngayChamDutHoatDongKD;
	}

	public void setNgayChamDutHoatDongKD(Date ngayChamDutHoatDongKD) {
		_ngayChamDutHoatDongKD = ngayChamDutHoatDongKD;
	}

	public long getLoai() {
		return _loai;
	}

	public void setLoai(long loai) {
		_loai = loai;
	}

	public Long getDiaChiDoanhNghiepHuyenId() {
		return _diaChiDoanhNghiepHuyenId;
	}

	public void setDiaChiDoanhNghiepHuyenId(Long diaChiDoanhNghiepHuyenId) {
		_diaChiDoanhNghiepHuyenId = diaChiDoanhNghiepHuyenId;
	}

	public Long getDiaChiDoanhNghiepTinhId() {
		return _diaChiDoanhNghiepTinhId;
	}

	public void setDiaChiDoanhNghiepTinhId(Long diaChiDoanhNghiepTinhId) {
		_diaChiDoanhNghiepTinhId = diaChiDoanhNghiepTinhId;
	}

	public Long getDiaChiDoanhNghiepXaId() {
		return _diaChiDoanhNghiepXaId;
	}

	public void setDiaChiDoanhNghiepXaId(Long diaChiDoanhNghiepXaId) {
		_diaChiDoanhNghiepXaId = diaChiDoanhNghiepXaId;
	}

	public Long getLoaiDoiTuongId() {
		return _loaiDoiTuongId;
	}

	public void setLoaiDoiTuongId(Long loaiDoiTuongId) {
		_columnBitmask |= LOAIDOITUONGID_COLUMN_BITMASK;

		if (!_setOriginalLoaiDoiTuongId) {
			_setOriginalLoaiDoiTuongId = true;

			_originalLoaiDoiTuongId = _loaiDoiTuongId;
		}

		_loaiDoiTuongId = loaiDoiTuongId;
	}

	public Long getOriginalLoaiDoiTuongId() {
		return _originalLoaiDoiTuongId;
	}

	public Long getNguoiDaiDienId() {
		return _nguoiDaiDienId;
	}

	public void setNguoiDaiDienId(Long nguoiDaiDienId) {
		_columnBitmask |= NGUOIDAIDIENID_COLUMN_BITMASK;

		if (!_setOriginalNguoiDaiDienId) {
			_setOriginalNguoiDaiDienId = true;

			_originalNguoiDaiDienId = _nguoiDaiDienId;
		}

		_nguoiDaiDienId = nguoiDaiDienId;
	}

	public Long getOriginalNguoiDaiDienId() {
		return _originalNguoiDaiDienId;
	}

	public Long getTrangThaiDoanhNghiepId() {
		return _trangThaiDoanhNghiepId;
	}

	public void setTrangThaiDoanhNghiepId(Long trangThaiDoanhNghiepId) {
		_trangThaiDoanhNghiepId = trangThaiDoanhNghiepId;
	}

	public long getVonDieuLe() {
		return _vonDieuLe;
	}

	public void setVonDieuLe(long vonDieuLe) {
		_vonDieuLe = vonDieuLe;
	}

	public long getVonToiThieuMotXaVien() {
		return _vonToiThieuMotXaVien;
	}

	public void setVonToiThieuMotXaVien(long vonToiThieuMotXaVien) {
		_vonToiThieuMotXaVien = vonToiThieuMotXaVien;
	}

	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public Long getQuocGiaId() {
		return _quocGiaId;
	}

	public void setQuocGiaId(Long quocGiaId) {
		_quocGiaId = quocGiaId;
	}

	public Long getCoQuanCapId() {
		return _coQuanCapId;
	}

	public void setCoQuanCapId(Long coQuanCapId) {
		_coQuanCapId = coQuanCapId;
	}

	public long getTenCoQuanCap() {
		return _tenCoQuanCap;
	}

	public void setTenCoQuanCap(long tenCoQuanCap) {
		_tenCoQuanCap = tenCoQuanCap;
	}

	public String getSoLanDieuChinh() {
		if (_soLanDieuChinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _soLanDieuChinh;
		}
	}

	public void setSoLanDieuChinh(String soLanDieuChinh) {
		_soLanDieuChinh = soLanDieuChinh;
	}

	public Date getNgayDieuChinh() {
		return _ngayDieuChinh;
	}

	public void setNgayDieuChinh(Date ngayDieuChinh) {
		_ngayDieuChinh = ngayDieuChinh;
	}

	public String getChucVuNguoiDaiDien() {
		if (_chucVuNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _chucVuNguoiDaiDien;
		}
	}

	public void setChucVuNguoiDaiDien(String chucVuNguoiDaiDien) {
		_chucVuNguoiDaiDien = chucVuNguoiDaiDien;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_daXoa = daXoa;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public Long getChaId() {
		return _chaId;
	}

	public void setChaId(Long chaId) {
		_columnBitmask |= CHAID_COLUMN_BITMASK;

		if (!_setOriginalChaId) {
			_setOriginalChaId = true;

			_originalChaId = _chaId;
		}

		_chaId = chaId;
	}

	public Long getOriginalChaId() {
		return _originalChaId;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public Long getTaiKhoanNguoiDungId() {
		return _taiKhoanNguoiDungId;
	}

	public void setTaiKhoanNguoiDungId(Long taiKhoanNguoiDungId) {
		_taiKhoanNguoiDungId = taiKhoanNguoiDungId;
	}

	public String getTenDiaDiemKinhDoanh() {
		if (_tenDiaDiemKinhDoanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDiaDiemKinhDoanh;
		}
	}

	public void setTenDiaDiemKinhDoanh(String tenDiaDiemKinhDoanh) {
		_tenDiaDiemKinhDoanh = tenDiaDiemKinhDoanh;
	}

	public Date getNgayDangKyKinhDoanh() {
		return _ngayDangKyKinhDoanh;
	}

	public void setNgayDangKyKinhDoanh(Date ngayDangKyKinhDoanh) {
		_ngayDangKyKinhDoanh = ngayDangKyKinhDoanh;
	}

	public Long getLoaiHinhDoanhNghiepId() {
		return _loaiHinhDoanhNghiepId;
	}

	public void setLoaiHinhDoanhNghiepId(Long loaiHinhDoanhNghiepId) {
		_columnBitmask |= LOAIHINHDOANHNGHIEPID_COLUMN_BITMASK;

		if (!_setOriginalLoaiHinhDoanhNghiepId) {
			_setOriginalLoaiHinhDoanhNghiepId = true;

			_originalLoaiHinhDoanhNghiepId = _loaiHinhDoanhNghiepId;
		}

		_loaiHinhDoanhNghiepId = loaiHinhDoanhNghiepId;
	}

	public Long getOriginalLoaiHinhDoanhNghiepId() {
		return _originalLoaiHinhDoanhNghiepId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DoanhNghiep toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DoanhNghiep)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DoanhNghiep.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DoanhNghiepImpl doanhNghiepImpl = new DoanhNghiepImpl();

		doanhNghiepImpl.setId(getId());
		doanhNghiepImpl.setMa(getMa());
		doanhNghiepImpl.setTen(getTen());
		doanhNghiepImpl.setMaSoThue(getMaSoThue());
		doanhNghiepImpl.setTenTiengNuocNgoai(getTenTiengNuocNgoai());
		doanhNghiepImpl.setTenVietTat(getTenVietTat());
		doanhNghiepImpl.setDiaChiDoanhNghiep(getDiaChiDoanhNghiep());
		doanhNghiepImpl.setDienThoaiDoanhNghiep(getDienThoaiDoanhNghiep());
		doanhNghiepImpl.setFax(getFax());
		doanhNghiepImpl.setEmailDoanhNghiep(getEmailDoanhNghiep());
		doanhNghiepImpl.setWebsite(getWebsite());
		doanhNghiepImpl.setTongSoVon(getTongSoVon());
		doanhNghiepImpl.setMoTaNganhNgheKinhDoanh(getMoTaNganhNgheKinhDoanh());
		doanhNghiepImpl.setSoGCNDKKD(getSoGCNDKKD());
		doanhNghiepImpl.setNgayCapGCNDKKD(getNgayCapGCNDKKD());
		doanhNghiepImpl.setNoiLuuTruId(getNoiLuuTruId());
		doanhNghiepImpl.setNgayDieuLeDuocThongQua(getNgayDieuLeDuocThongQua());
		doanhNghiepImpl.setTenChiNhanh(getTenChiNhanh());
		doanhNghiepImpl.setDiaChiChiNhanh(getDiaChiChiNhanh());
		doanhNghiepImpl.setTenVanPhongDaiDien(getTenVanPhongDaiDien());
		doanhNghiepImpl.setDiaChiVanPhongDaiDien(getDiaChiVanPhongDaiDien());
		doanhNghiepImpl.setNgayBatDauTamNgung(getNgayBatDauTamNgung());
		doanhNghiepImpl.setNgayKetThucTamNgung(getNgayKetThucTamNgung());
		doanhNghiepImpl.setLyDoTamNgung(getLyDoTamNgung());
		doanhNghiepImpl.setNgayChamDutHoatDongKD(getNgayChamDutHoatDongKD());
		doanhNghiepImpl.setLoai(getLoai());
		doanhNghiepImpl.setDiaChiDoanhNghiepHuyenId(getDiaChiDoanhNghiepHuyenId());
		doanhNghiepImpl.setDiaChiDoanhNghiepTinhId(getDiaChiDoanhNghiepTinhId());
		doanhNghiepImpl.setDiaChiDoanhNghiepXaId(getDiaChiDoanhNghiepXaId());
		doanhNghiepImpl.setLoaiDoiTuongId(getLoaiDoiTuongId());
		doanhNghiepImpl.setNguoiDaiDienId(getNguoiDaiDienId());
		doanhNghiepImpl.setTrangThaiDoanhNghiepId(getTrangThaiDoanhNghiepId());
		doanhNghiepImpl.setVonDieuLe(getVonDieuLe());
		doanhNghiepImpl.setVonToiThieuMotXaVien(getVonToiThieuMotXaVien());
		doanhNghiepImpl.setGhiChu(getGhiChu());
		doanhNghiepImpl.setQuocGiaId(getQuocGiaId());
		doanhNghiepImpl.setCoQuanCapId(getCoQuanCapId());
		doanhNghiepImpl.setTenCoQuanCap(getTenCoQuanCap());
		doanhNghiepImpl.setSoLanDieuChinh(getSoLanDieuChinh());
		doanhNghiepImpl.setNgayDieuChinh(getNgayDieuChinh());
		doanhNghiepImpl.setChucVuNguoiDaiDien(getChucVuNguoiDaiDien());
		doanhNghiepImpl.setNgayTao(getNgayTao());
		doanhNghiepImpl.setDaXoa(getDaXoa());
		doanhNghiepImpl.setNgaySua(getNgaySua());
		doanhNghiepImpl.setChaId(getChaId());
		doanhNghiepImpl.setNguoiTao(getNguoiTao());
		doanhNghiepImpl.setNguoiSua(getNguoiSua());
		doanhNghiepImpl.setTaiKhoanNguoiDungId(getTaiKhoanNguoiDungId());
		doanhNghiepImpl.setTenDiaDiemKinhDoanh(getTenDiaDiemKinhDoanh());
		doanhNghiepImpl.setNgayDangKyKinhDoanh(getNgayDangKyKinhDoanh());
		doanhNghiepImpl.setLoaiHinhDoanhNghiepId(getLoaiHinhDoanhNghiepId());

		doanhNghiepImpl.resetOriginalValues();

		return doanhNghiepImpl;
	}

	public int compareTo(DoanhNghiep doanhNghiep) {
		int value = 0;

		if (getId() < doanhNghiep.getId()) {
			value = -1;
		}
		else if (getId() > doanhNghiep.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DoanhNghiep doanhNghiep = null;

		try {
			doanhNghiep = (DoanhNghiep)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = doanhNghiep.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DoanhNghiepModelImpl doanhNghiepModelImpl = this;

		doanhNghiepModelImpl._originalMa = doanhNghiepModelImpl._ma;

		doanhNghiepModelImpl._originalTen = doanhNghiepModelImpl._ten;

		doanhNghiepModelImpl._originalMaSoThue = doanhNghiepModelImpl._maSoThue;

		doanhNghiepModelImpl._originalSoGCNDKKD = doanhNghiepModelImpl._soGCNDKKD;

		doanhNghiepModelImpl._originalLoaiDoiTuongId = doanhNghiepModelImpl._loaiDoiTuongId;

		doanhNghiepModelImpl._setOriginalLoaiDoiTuongId = false;

		doanhNghiepModelImpl._originalNguoiDaiDienId = doanhNghiepModelImpl._nguoiDaiDienId;

		doanhNghiepModelImpl._setOriginalNguoiDaiDienId = false;

		doanhNghiepModelImpl._originalChaId = doanhNghiepModelImpl._chaId;

		doanhNghiepModelImpl._setOriginalChaId = false;

		doanhNghiepModelImpl._originalLoaiHinhDoanhNghiepId = doanhNghiepModelImpl._loaiHinhDoanhNghiepId;

		doanhNghiepModelImpl._setOriginalLoaiHinhDoanhNghiepId = false;

		doanhNghiepModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DoanhNghiep> toCacheModel() {
		DoanhNghiepCacheModel doanhNghiepCacheModel = new DoanhNghiepCacheModel();

		doanhNghiepCacheModel.id = getId();

		doanhNghiepCacheModel.ma = getMa();

		String ma = doanhNghiepCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			doanhNghiepCacheModel.ma = null;
		}

		doanhNghiepCacheModel.ten = getTen();

		String ten = doanhNghiepCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			doanhNghiepCacheModel.ten = null;
		}

		doanhNghiepCacheModel.maSoThue = getMaSoThue();

		String maSoThue = doanhNghiepCacheModel.maSoThue;

		if ((maSoThue != null) && (maSoThue.length() == 0)) {
			doanhNghiepCacheModel.maSoThue = null;
		}

		doanhNghiepCacheModel.tenTiengNuocNgoai = getTenTiengNuocNgoai();

		String tenTiengNuocNgoai = doanhNghiepCacheModel.tenTiengNuocNgoai;

		if ((tenTiengNuocNgoai != null) && (tenTiengNuocNgoai.length() == 0)) {
			doanhNghiepCacheModel.tenTiengNuocNgoai = null;
		}

		doanhNghiepCacheModel.tenVietTat = getTenVietTat();

		String tenVietTat = doanhNghiepCacheModel.tenVietTat;

		if ((tenVietTat != null) && (tenVietTat.length() == 0)) {
			doanhNghiepCacheModel.tenVietTat = null;
		}

		doanhNghiepCacheModel.diaChiDoanhNghiep = getDiaChiDoanhNghiep();

		String diaChiDoanhNghiep = doanhNghiepCacheModel.diaChiDoanhNghiep;

		if ((diaChiDoanhNghiep != null) && (diaChiDoanhNghiep.length() == 0)) {
			doanhNghiepCacheModel.diaChiDoanhNghiep = null;
		}

		doanhNghiepCacheModel.dienThoaiDoanhNghiep = getDienThoaiDoanhNghiep();

		String dienThoaiDoanhNghiep = doanhNghiepCacheModel.dienThoaiDoanhNghiep;

		if ((dienThoaiDoanhNghiep != null) &&
				(dienThoaiDoanhNghiep.length() == 0)) {
			doanhNghiepCacheModel.dienThoaiDoanhNghiep = null;
		}

		doanhNghiepCacheModel.fax = getFax();

		String fax = doanhNghiepCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			doanhNghiepCacheModel.fax = null;
		}

		doanhNghiepCacheModel.emailDoanhNghiep = getEmailDoanhNghiep();

		String emailDoanhNghiep = doanhNghiepCacheModel.emailDoanhNghiep;

		if ((emailDoanhNghiep != null) && (emailDoanhNghiep.length() == 0)) {
			doanhNghiepCacheModel.emailDoanhNghiep = null;
		}

		doanhNghiepCacheModel.website = getWebsite();

		String website = doanhNghiepCacheModel.website;

		if ((website != null) && (website.length() == 0)) {
			doanhNghiepCacheModel.website = null;
		}

		doanhNghiepCacheModel.tongSoVon = getTongSoVon();

		doanhNghiepCacheModel.moTaNganhNgheKinhDoanh = getMoTaNganhNgheKinhDoanh();

		String moTaNganhNgheKinhDoanh = doanhNghiepCacheModel.moTaNganhNgheKinhDoanh;

		if ((moTaNganhNgheKinhDoanh != null) &&
				(moTaNganhNgheKinhDoanh.length() == 0)) {
			doanhNghiepCacheModel.moTaNganhNgheKinhDoanh = null;
		}

		doanhNghiepCacheModel.soGCNDKKD = getSoGCNDKKD();

		String soGCNDKKD = doanhNghiepCacheModel.soGCNDKKD;

		if ((soGCNDKKD != null) && (soGCNDKKD.length() == 0)) {
			doanhNghiepCacheModel.soGCNDKKD = null;
		}

		Date ngayCapGCNDKKD = getNgayCapGCNDKKD();

		if (ngayCapGCNDKKD != null) {
			doanhNghiepCacheModel.ngayCapGCNDKKD = ngayCapGCNDKKD.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayCapGCNDKKD = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.noiLuuTruId = getNoiLuuTruId();

		Date ngayDieuLeDuocThongQua = getNgayDieuLeDuocThongQua();

		if (ngayDieuLeDuocThongQua != null) {
			doanhNghiepCacheModel.ngayDieuLeDuocThongQua = ngayDieuLeDuocThongQua.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayDieuLeDuocThongQua = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.tenChiNhanh = getTenChiNhanh();

		String tenChiNhanh = doanhNghiepCacheModel.tenChiNhanh;

		if ((tenChiNhanh != null) && (tenChiNhanh.length() == 0)) {
			doanhNghiepCacheModel.tenChiNhanh = null;
		}

		doanhNghiepCacheModel.diaChiChiNhanh = getDiaChiChiNhanh();

		String diaChiChiNhanh = doanhNghiepCacheModel.diaChiChiNhanh;

		if ((diaChiChiNhanh != null) && (diaChiChiNhanh.length() == 0)) {
			doanhNghiepCacheModel.diaChiChiNhanh = null;
		}

		doanhNghiepCacheModel.tenVanPhongDaiDien = getTenVanPhongDaiDien();

		String tenVanPhongDaiDien = doanhNghiepCacheModel.tenVanPhongDaiDien;

		if ((tenVanPhongDaiDien != null) && (tenVanPhongDaiDien.length() == 0)) {
			doanhNghiepCacheModel.tenVanPhongDaiDien = null;
		}

		doanhNghiepCacheModel.diaChiVanPhongDaiDien = getDiaChiVanPhongDaiDien();

		String diaChiVanPhongDaiDien = doanhNghiepCacheModel.diaChiVanPhongDaiDien;

		if ((diaChiVanPhongDaiDien != null) &&
				(diaChiVanPhongDaiDien.length() == 0)) {
			doanhNghiepCacheModel.diaChiVanPhongDaiDien = null;
		}

		Date ngayBatDauTamNgung = getNgayBatDauTamNgung();

		if (ngayBatDauTamNgung != null) {
			doanhNghiepCacheModel.ngayBatDauTamNgung = ngayBatDauTamNgung.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayBatDauTamNgung = Long.MIN_VALUE;
		}

		Date ngayKetThucTamNgung = getNgayKetThucTamNgung();

		if (ngayKetThucTamNgung != null) {
			doanhNghiepCacheModel.ngayKetThucTamNgung = ngayKetThucTamNgung.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayKetThucTamNgung = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.lyDoTamNgung = getLyDoTamNgung();

		String lyDoTamNgung = doanhNghiepCacheModel.lyDoTamNgung;

		if ((lyDoTamNgung != null) && (lyDoTamNgung.length() == 0)) {
			doanhNghiepCacheModel.lyDoTamNgung = null;
		}

		Date ngayChamDutHoatDongKD = getNgayChamDutHoatDongKD();

		if (ngayChamDutHoatDongKD != null) {
			doanhNghiepCacheModel.ngayChamDutHoatDongKD = ngayChamDutHoatDongKD.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayChamDutHoatDongKD = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.loai = getLoai();

		doanhNghiepCacheModel.diaChiDoanhNghiepHuyenId = getDiaChiDoanhNghiepHuyenId();

		doanhNghiepCacheModel.diaChiDoanhNghiepTinhId = getDiaChiDoanhNghiepTinhId();

		doanhNghiepCacheModel.diaChiDoanhNghiepXaId = getDiaChiDoanhNghiepXaId();

		doanhNghiepCacheModel.loaiDoiTuongId = getLoaiDoiTuongId();

		doanhNghiepCacheModel.nguoiDaiDienId = getNguoiDaiDienId();

		doanhNghiepCacheModel.trangThaiDoanhNghiepId = getTrangThaiDoanhNghiepId();

		doanhNghiepCacheModel.vonDieuLe = getVonDieuLe();

		doanhNghiepCacheModel.vonToiThieuMotXaVien = getVonToiThieuMotXaVien();

		doanhNghiepCacheModel.ghiChu = getGhiChu();

		String ghiChu = doanhNghiepCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			doanhNghiepCacheModel.ghiChu = null;
		}

		doanhNghiepCacheModel.quocGiaId = getQuocGiaId();

		doanhNghiepCacheModel.coQuanCapId = getCoQuanCapId();

		doanhNghiepCacheModel.tenCoQuanCap = getTenCoQuanCap();

		doanhNghiepCacheModel.soLanDieuChinh = getSoLanDieuChinh();

		String soLanDieuChinh = doanhNghiepCacheModel.soLanDieuChinh;

		if ((soLanDieuChinh != null) && (soLanDieuChinh.length() == 0)) {
			doanhNghiepCacheModel.soLanDieuChinh = null;
		}

		Date ngayDieuChinh = getNgayDieuChinh();

		if (ngayDieuChinh != null) {
			doanhNghiepCacheModel.ngayDieuChinh = ngayDieuChinh.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayDieuChinh = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.chucVuNguoiDaiDien = getChucVuNguoiDaiDien();

		String chucVuNguoiDaiDien = doanhNghiepCacheModel.chucVuNguoiDaiDien;

		if ((chucVuNguoiDaiDien != null) && (chucVuNguoiDaiDien.length() == 0)) {
			doanhNghiepCacheModel.chucVuNguoiDaiDien = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			doanhNghiepCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayTao = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.daXoa = getDaXoa();

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			doanhNghiepCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			doanhNghiepCacheModel.ngaySua = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.chaId = getChaId();

		doanhNghiepCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = doanhNghiepCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			doanhNghiepCacheModel.nguoiTao = null;
		}

		doanhNghiepCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = doanhNghiepCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			doanhNghiepCacheModel.nguoiSua = null;
		}

		doanhNghiepCacheModel.taiKhoanNguoiDungId = getTaiKhoanNguoiDungId();

		doanhNghiepCacheModel.tenDiaDiemKinhDoanh = getTenDiaDiemKinhDoanh();

		String tenDiaDiemKinhDoanh = doanhNghiepCacheModel.tenDiaDiemKinhDoanh;

		if ((tenDiaDiemKinhDoanh != null) &&
				(tenDiaDiemKinhDoanh.length() == 0)) {
			doanhNghiepCacheModel.tenDiaDiemKinhDoanh = null;
		}

		Date ngayDangKyKinhDoanh = getNgayDangKyKinhDoanh();

		if (ngayDangKyKinhDoanh != null) {
			doanhNghiepCacheModel.ngayDangKyKinhDoanh = ngayDangKyKinhDoanh.getTime();
		}
		else {
			doanhNghiepCacheModel.ngayDangKyKinhDoanh = Long.MIN_VALUE;
		}

		doanhNghiepCacheModel.loaiHinhDoanhNghiepId = getLoaiHinhDoanhNghiepId();

		return doanhNghiepCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(103);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", maSoThue=");
		sb.append(getMaSoThue());
		sb.append(", tenTiengNuocNgoai=");
		sb.append(getTenTiengNuocNgoai());
		sb.append(", tenVietTat=");
		sb.append(getTenVietTat());
		sb.append(", diaChiDoanhNghiep=");
		sb.append(getDiaChiDoanhNghiep());
		sb.append(", dienThoaiDoanhNghiep=");
		sb.append(getDienThoaiDoanhNghiep());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", emailDoanhNghiep=");
		sb.append(getEmailDoanhNghiep());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append(", tongSoVon=");
		sb.append(getTongSoVon());
		sb.append(", moTaNganhNgheKinhDoanh=");
		sb.append(getMoTaNganhNgheKinhDoanh());
		sb.append(", soGCNDKKD=");
		sb.append(getSoGCNDKKD());
		sb.append(", ngayCapGCNDKKD=");
		sb.append(getNgayCapGCNDKKD());
		sb.append(", noiLuuTruId=");
		sb.append(getNoiLuuTruId());
		sb.append(", ngayDieuLeDuocThongQua=");
		sb.append(getNgayDieuLeDuocThongQua());
		sb.append(", tenChiNhanh=");
		sb.append(getTenChiNhanh());
		sb.append(", diaChiChiNhanh=");
		sb.append(getDiaChiChiNhanh());
		sb.append(", tenVanPhongDaiDien=");
		sb.append(getTenVanPhongDaiDien());
		sb.append(", diaChiVanPhongDaiDien=");
		sb.append(getDiaChiVanPhongDaiDien());
		sb.append(", ngayBatDauTamNgung=");
		sb.append(getNgayBatDauTamNgung());
		sb.append(", ngayKetThucTamNgung=");
		sb.append(getNgayKetThucTamNgung());
		sb.append(", lyDoTamNgung=");
		sb.append(getLyDoTamNgung());
		sb.append(", ngayChamDutHoatDongKD=");
		sb.append(getNgayChamDutHoatDongKD());
		sb.append(", loai=");
		sb.append(getLoai());
		sb.append(", diaChiDoanhNghiepHuyenId=");
		sb.append(getDiaChiDoanhNghiepHuyenId());
		sb.append(", diaChiDoanhNghiepTinhId=");
		sb.append(getDiaChiDoanhNghiepTinhId());
		sb.append(", diaChiDoanhNghiepXaId=");
		sb.append(getDiaChiDoanhNghiepXaId());
		sb.append(", loaiDoiTuongId=");
		sb.append(getLoaiDoiTuongId());
		sb.append(", nguoiDaiDienId=");
		sb.append(getNguoiDaiDienId());
		sb.append(", trangThaiDoanhNghiepId=");
		sb.append(getTrangThaiDoanhNghiepId());
		sb.append(", vonDieuLe=");
		sb.append(getVonDieuLe());
		sb.append(", vonToiThieuMotXaVien=");
		sb.append(getVonToiThieuMotXaVien());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", quocGiaId=");
		sb.append(getQuocGiaId());
		sb.append(", coQuanCapId=");
		sb.append(getCoQuanCapId());
		sb.append(", tenCoQuanCap=");
		sb.append(getTenCoQuanCap());
		sb.append(", soLanDieuChinh=");
		sb.append(getSoLanDieuChinh());
		sb.append(", ngayDieuChinh=");
		sb.append(getNgayDieuChinh());
		sb.append(", chucVuNguoiDaiDien=");
		sb.append(getChucVuNguoiDaiDien());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", chaId=");
		sb.append(getChaId());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", taiKhoanNguoiDungId=");
		sb.append(getTaiKhoanNguoiDungId());
		sb.append(", tenDiaDiemKinhDoanh=");
		sb.append(getTenDiaDiemKinhDoanh());
		sb.append(", ngayDangKyKinhDoanh=");
		sb.append(getNgayDangKyKinhDoanh());
		sb.append(", loaiHinhDoanhNghiepId=");
		sb.append(getLoaiHinhDoanhNghiepId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(157);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dn.model.DoanhNghiep");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoThue</column-name><column-value><![CDATA[");
		sb.append(getMaSoThue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenTiengNuocNgoai</column-name><column-value><![CDATA[");
		sb.append(getTenTiengNuocNgoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenVietTat</column-name><column-value><![CDATA[");
		sb.append(getTenVietTat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getDiaChiDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoaiDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getDienThoaiDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getEmailDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoVon</column-name><column-value><![CDATA[");
		sb.append(getTongSoVon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTaNganhNgheKinhDoanh</column-name><column-value><![CDATA[");
		sb.append(getMoTaNganhNgheKinhDoanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGCNDKKD</column-name><column-value><![CDATA[");
		sb.append(getSoGCNDKKD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGCNDKKD</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGCNDKKD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiLuuTruId</column-name><column-value><![CDATA[");
		sb.append(getNoiLuuTruId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDieuLeDuocThongQua</column-name><column-value><![CDATA[");
		sb.append(getNgayDieuLeDuocThongQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenChiNhanh</column-name><column-value><![CDATA[");
		sb.append(getTenChiNhanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiChiNhanh</column-name><column-value><![CDATA[");
		sb.append(getDiaChiChiNhanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenVanPhongDaiDien</column-name><column-value><![CDATA[");
		sb.append(getTenVanPhongDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiVanPhongDaiDien</column-name><column-value><![CDATA[");
		sb.append(getDiaChiVanPhongDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayBatDauTamNgung</column-name><column-value><![CDATA[");
		sb.append(getNgayBatDauTamNgung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayKetThucTamNgung</column-name><column-value><![CDATA[");
		sb.append(getNgayKetThucTamNgung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoTamNgung</column-name><column-value><![CDATA[");
		sb.append(getLyDoTamNgung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayChamDutHoatDongKD</column-name><column-value><![CDATA[");
		sb.append(getNgayChamDutHoatDongKD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loai</column-name><column-value><![CDATA[");
		sb.append(getLoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiDoanhNghiepHuyenId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiDoanhNghiepHuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiDoanhNghiepTinhId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiDoanhNghiepTinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiDoanhNghiepXaId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiDoanhNghiepXaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiDoiTuongId</column-name><column-value><![CDATA[");
		sb.append(getLoaiDoiTuongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiDaiDienId</column-name><column-value><![CDATA[");
		sb.append(getNguoiDaiDienId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiDoanhNghiepId</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiDoanhNghiepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vonDieuLe</column-name><column-value><![CDATA[");
		sb.append(getVonDieuLe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vonToiThieuMotXaVien</column-name><column-value><![CDATA[");
		sb.append(getVonToiThieuMotXaVien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quocGiaId</column-name><column-value><![CDATA[");
		sb.append(getQuocGiaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanCapId</column-name><column-value><![CDATA[");
		sb.append(getCoQuanCapId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCoQuanCap</column-name><column-value><![CDATA[");
		sb.append(getTenCoQuanCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soLanDieuChinh</column-name><column-value><![CDATA[");
		sb.append(getSoLanDieuChinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDieuChinh</column-name><column-value><![CDATA[");
		sb.append(getNgayDieuChinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chucVuNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getChucVuNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chaId</column-name><column-value><![CDATA[");
		sb.append(getChaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoanNguoiDungId</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoanNguoiDungId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDiaDiemKinhDoanh</column-name><column-value><![CDATA[");
		sb.append(getTenDiaDiemKinhDoanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDangKyKinhDoanh</column-name><column-value><![CDATA[");
		sb.append(getNgayDangKyKinhDoanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHinhDoanhNghiepId</column-name><column-value><![CDATA[");
		sb.append(getLoaiHinhDoanhNghiepId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DoanhNghiep.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DoanhNghiep.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private String _originalTen;
	private String _maSoThue;
	private String _originalMaSoThue;
	private String _tenTiengNuocNgoai;
	private String _tenVietTat;
	private String _diaChiDoanhNghiep;
	private String _dienThoaiDoanhNghiep;
	private String _fax;
	private String _emailDoanhNghiep;
	private String _website;
	private long _tongSoVon;
	private String _moTaNganhNgheKinhDoanh;
	private String _soGCNDKKD;
	private String _originalSoGCNDKKD;
	private Date _ngayCapGCNDKKD;
	private long _noiLuuTruId;
	private Date _ngayDieuLeDuocThongQua;
	private String _tenChiNhanh;
	private String _diaChiChiNhanh;
	private String _tenVanPhongDaiDien;
	private String _diaChiVanPhongDaiDien;
	private Date _ngayBatDauTamNgung;
	private Date _ngayKetThucTamNgung;
	private String _lyDoTamNgung;
	private Date _ngayChamDutHoatDongKD;
	private long _loai;
	private Long _diaChiDoanhNghiepHuyenId;
	private Long _diaChiDoanhNghiepTinhId;
	private Long _diaChiDoanhNghiepXaId;
	private Long _loaiDoiTuongId;
	private Long _originalLoaiDoiTuongId;
	private boolean _setOriginalLoaiDoiTuongId;
	private Long _nguoiDaiDienId;
	private Long _originalNguoiDaiDienId;
	private boolean _setOriginalNguoiDaiDienId;
	private Long _trangThaiDoanhNghiepId;
	private long _vonDieuLe;
	private long _vonToiThieuMotXaVien;
	private String _ghiChu;
	private Long _quocGiaId;
	private Long _coQuanCapId;
	private long _tenCoQuanCap;
	private String _soLanDieuChinh;
	private Date _ngayDieuChinh;
	private String _chucVuNguoiDaiDien;
	private Date _ngayTao;
	private int _daXoa;
	private Date _ngaySua;
	private Long _chaId;
	private Long _originalChaId;
	private boolean _setOriginalChaId;
	private String _nguoiTao;
	private String _nguoiSua;
	private Long _taiKhoanNguoiDungId;
	private String _tenDiaDiemKinhDoanh;
	private Date _ngayDangKyKinhDoanh;
	private Long _loaiHinhDoanhNghiepId;
	private Long _originalLoaiHinhDoanhNghiepId;
	private boolean _setOriginalLoaiHinhDoanhNghiepId;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private DoanhNghiep _escapedModelProxy;
}