/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNghe;
import org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNgheModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the DoanhNghiep2NganhNghe service. Represents a row in the &quot;BRMS_DOANHNGHIEP2NGANHNGHE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNgheModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DoanhNghiep2NganhNgheImpl}.
 * </p>
 *
 * @author Liemnn
 * @see DoanhNghiep2NganhNgheImpl
 * @see org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNghe
 * @see org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNgheModel
 * @generated
 */
public class DoanhNghiep2NganhNgheModelImpl extends BaseModelImpl<DoanhNghiep2NganhNghe>
	implements DoanhNghiep2NganhNgheModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a doanh nghiep2 nganh nghe model instance should use the {@link org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNghe} interface instead.
	 */
	public static final String TABLE_NAME = "BRMS_DOANHNGHIEP2NGANHNGHE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "LANGANHCHINH", Types.INTEGER },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "DAXOA", Types.INTEGER },
			{ "DOANHNGHIEPID", Types.BIGINT },
			{ "NGANHNGHEID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table BRMS_DOANHNGHIEP2NGANHNGHE (ID LONG not null primary key,LANGANHCHINH INTEGER,NGAYTAO DATE null,NGAYSUA DATE null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,DAXOA INTEGER,DOANHNGHIEPID LONG,NGANHNGHEID LONG)";
	public static final String TABLE_SQL_DROP = "drop table BRMS_DOANHNGHIEP2NGANHNGHE";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNghe"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNghe"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNghe"));

	public DoanhNghiep2NganhNgheModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DoanhNghiep2NganhNghe.class;
	}

	public String getModelClassName() {
		return DoanhNghiep2NganhNghe.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public int getLaNganhChinh() {
		return _laNganhChinh;
	}

	public void setLaNganhChinh(int laNganhChinh) {
		_laNganhChinh = laNganhChinh;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_daXoa = daXoa;
	}

	public long getDoanhNghiepId() {
		return _doanhNghiepId;
	}

	public void setDoanhNghiepId(long doanhNghiepId) {
		_doanhNghiepId = doanhNghiepId;
	}

	public long getNganhNgheId() {
		return _nganhNgheId;
	}

	public void setNganhNgheId(long nganhNgheId) {
		_nganhNgheId = nganhNgheId;
	}

	@Override
	public DoanhNghiep2NganhNghe toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DoanhNghiep2NganhNghe)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DoanhNghiep2NganhNghe.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DoanhNghiep2NganhNgheImpl doanhNghiep2NganhNgheImpl = new DoanhNghiep2NganhNgheImpl();

		doanhNghiep2NganhNgheImpl.setId(getId());
		doanhNghiep2NganhNgheImpl.setLaNganhChinh(getLaNganhChinh());
		doanhNghiep2NganhNgheImpl.setNgayTao(getNgayTao());
		doanhNghiep2NganhNgheImpl.setNgaySua(getNgaySua());
		doanhNghiep2NganhNgheImpl.setNguoiTao(getNguoiTao());
		doanhNghiep2NganhNgheImpl.setNguoiSua(getNguoiSua());
		doanhNghiep2NganhNgheImpl.setDaXoa(getDaXoa());
		doanhNghiep2NganhNgheImpl.setDoanhNghiepId(getDoanhNghiepId());
		doanhNghiep2NganhNgheImpl.setNganhNgheId(getNganhNgheId());

		doanhNghiep2NganhNgheImpl.resetOriginalValues();

		return doanhNghiep2NganhNgheImpl;
	}

	public int compareTo(DoanhNghiep2NganhNghe doanhNghiep2NganhNghe) {
		long primaryKey = doanhNghiep2NganhNghe.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DoanhNghiep2NganhNghe doanhNghiep2NganhNghe = null;

		try {
			doanhNghiep2NganhNghe = (DoanhNghiep2NganhNghe)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = doanhNghiep2NganhNghe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DoanhNghiep2NganhNghe> toCacheModel() {
		DoanhNghiep2NganhNgheCacheModel doanhNghiep2NganhNgheCacheModel = new DoanhNghiep2NganhNgheCacheModel();

		doanhNghiep2NganhNgheCacheModel.id = getId();

		doanhNghiep2NganhNgheCacheModel.laNganhChinh = getLaNganhChinh();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			doanhNghiep2NganhNgheCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			doanhNghiep2NganhNgheCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			doanhNghiep2NganhNgheCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			doanhNghiep2NganhNgheCacheModel.ngaySua = Long.MIN_VALUE;
		}

		doanhNghiep2NganhNgheCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = doanhNghiep2NganhNgheCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			doanhNghiep2NganhNgheCacheModel.nguoiTao = null;
		}

		doanhNghiep2NganhNgheCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = doanhNghiep2NganhNgheCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			doanhNghiep2NganhNgheCacheModel.nguoiSua = null;
		}

		doanhNghiep2NganhNgheCacheModel.daXoa = getDaXoa();

		doanhNghiep2NganhNgheCacheModel.doanhNghiepId = getDoanhNghiepId();

		doanhNghiep2NganhNgheCacheModel.nganhNgheId = getNganhNgheId();

		return doanhNghiep2NganhNgheCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", laNganhChinh=");
		sb.append(getLaNganhChinh());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", doanhNghiepId=");
		sb.append(getDoanhNghiepId());
		sb.append(", nganhNgheId=");
		sb.append(getNganhNgheId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dn.model.DoanhNghiep2NganhNghe");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laNganhChinh</column-name><column-value><![CDATA[");
		sb.append(getLaNganhChinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>doanhNghiepId</column-name><column-value><![CDATA[");
		sb.append(getDoanhNghiepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nganhNgheId</column-name><column-value><![CDATA[");
		sb.append(getNganhNgheId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DoanhNghiep2NganhNghe.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DoanhNghiep2NganhNghe.class
		};
	private long _id;
	private int _laNganhChinh;
	private Date _ngayTao;
	private Date _ngaySua;
	private String _nguoiTao;
	private String _nguoiSua;
	private int _daXoa;
	private long _doanhNghiepId;
	private long _nganhNgheId;
	private transient ExpandoBridge _expandoBridge;
	private DoanhNghiep2NganhNghe _escapedModelProxy;
}