/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep;
import org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiepModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TrangThaiDoanhNghiep service. Represents a row in the &quot;CMON_TRANGTHAIDOANHNGHIEP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiepModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrangThaiDoanhNghiepImpl}.
 * </p>
 *
 * @author Liemnn
 * @see TrangThaiDoanhNghiepImpl
 * @see org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep
 * @see org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiepModel
 * @generated
 */
public class TrangThaiDoanhNghiepModelImpl extends BaseModelImpl<TrangThaiDoanhNghiep>
	implements TrangThaiDoanhNghiepModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trang thai doanh nghiep model instance should use the {@link org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_TRANGTHAIDOANHNGHIEP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TEN", Types.VARCHAR },
			{ "MOTA", Types.VARCHAR },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_TRANGTHAIDOANHNGHIEP (ID LONG not null primary key,TEN VARCHAR(75) null,MOTA VARCHAR(75) null,NGUOITAO VARCHAR(75) null,NGAYTAO DATE null,NGUOISUA VARCHAR(75) null,NGAYSUA DATE null,DAXOA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_TRANGTHAIDOANHNGHIEP";
	public static final String ORDER_BY_JPQL = " ORDER BY trangThaiDoanhNghiep.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_TRANGTHAIDOANHNGHIEP.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep"));

	public TrangThaiDoanhNghiepModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TrangThaiDoanhNghiep.class;
	}

	public String getModelClassName() {
		return TrangThaiDoanhNghiep.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public String getMoTa() {
		if (_moTa == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTa;
		}
	}

	public void setMoTa(String moTa) {
		_moTa = moTa;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TrangThaiDoanhNghiep toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TrangThaiDoanhNghiep)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TrangThaiDoanhNghiep.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TrangThaiDoanhNghiepImpl trangThaiDoanhNghiepImpl = new TrangThaiDoanhNghiepImpl();

		trangThaiDoanhNghiepImpl.setId(getId());
		trangThaiDoanhNghiepImpl.setTen(getTen());
		trangThaiDoanhNghiepImpl.setMoTa(getMoTa());
		trangThaiDoanhNghiepImpl.setNguoiTao(getNguoiTao());
		trangThaiDoanhNghiepImpl.setNgayTao(getNgayTao());
		trangThaiDoanhNghiepImpl.setNguoiSua(getNguoiSua());
		trangThaiDoanhNghiepImpl.setNgaySua(getNgaySua());
		trangThaiDoanhNghiepImpl.setDaXoa(getDaXoa());

		trangThaiDoanhNghiepImpl.resetOriginalValues();

		return trangThaiDoanhNghiepImpl;
	}

	public int compareTo(TrangThaiDoanhNghiep trangThaiDoanhNghiep) {
		int value = 0;

		if (getId() < trangThaiDoanhNghiep.getId()) {
			value = -1;
		}
		else if (getId() > trangThaiDoanhNghiep.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TrangThaiDoanhNghiep trangThaiDoanhNghiep = null;

		try {
			trangThaiDoanhNghiep = (TrangThaiDoanhNghiep)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = trangThaiDoanhNghiep.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TrangThaiDoanhNghiepModelImpl trangThaiDoanhNghiepModelImpl = this;

		trangThaiDoanhNghiepModelImpl._originalId = trangThaiDoanhNghiepModelImpl._id;

		trangThaiDoanhNghiepModelImpl._setOriginalId = false;

		trangThaiDoanhNghiepModelImpl._originalDaXoa = trangThaiDoanhNghiepModelImpl._daXoa;

		trangThaiDoanhNghiepModelImpl._setOriginalDaXoa = false;

		trangThaiDoanhNghiepModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TrangThaiDoanhNghiep> toCacheModel() {
		TrangThaiDoanhNghiepCacheModel trangThaiDoanhNghiepCacheModel = new TrangThaiDoanhNghiepCacheModel();

		trangThaiDoanhNghiepCacheModel.id = getId();

		trangThaiDoanhNghiepCacheModel.ten = getTen();

		String ten = trangThaiDoanhNghiepCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			trangThaiDoanhNghiepCacheModel.ten = null;
		}

		trangThaiDoanhNghiepCacheModel.moTa = getMoTa();

		String moTa = trangThaiDoanhNghiepCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			trangThaiDoanhNghiepCacheModel.moTa = null;
		}

		trangThaiDoanhNghiepCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = trangThaiDoanhNghiepCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			trangThaiDoanhNghiepCacheModel.nguoiTao = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			trangThaiDoanhNghiepCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			trangThaiDoanhNghiepCacheModel.ngayTao = Long.MIN_VALUE;
		}

		trangThaiDoanhNghiepCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = trangThaiDoanhNghiepCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			trangThaiDoanhNghiepCacheModel.nguoiSua = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			trangThaiDoanhNghiepCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			trangThaiDoanhNghiepCacheModel.ngaySua = Long.MIN_VALUE;
		}

		trangThaiDoanhNghiepCacheModel.daXoa = getDaXoa();

		return trangThaiDoanhNghiepCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", moTa=");
		sb.append(getMoTa());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dn.model.TrangThaiDoanhNghiep");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTa</column-name><column-value><![CDATA[");
		sb.append(getMoTa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TrangThaiDoanhNghiep.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TrangThaiDoanhNghiep.class
		};
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private String _ten;
	private String _moTa;
	private String _nguoiTao;
	private Date _ngayTao;
	private String _nguoiSua;
	private Date _ngaySua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TrangThaiDoanhNghiep _escapedModelProxy;
}