/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dn.model.YeuCauDangKyDN;
import org.oep.cmon.dao.dn.model.YeuCauDangKyDNModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the YeuCauDangKyDN service. Represents a row in the &quot;BRMS_YEUCAUDANGKY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dn.model.YeuCauDangKyDNModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YeuCauDangKyDNImpl}.
 * </p>
 *
 * @author Liemnn
 * @see YeuCauDangKyDNImpl
 * @see org.oep.cmon.dao.dn.model.YeuCauDangKyDN
 * @see org.oep.cmon.dao.dn.model.YeuCauDangKyDNModel
 * @generated
 */
public class YeuCauDangKyDNModelImpl extends BaseModelImpl<YeuCauDangKyDN>
	implements YeuCauDangKyDNModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a yeu cau dang ky d n model instance should use the {@link org.oep.cmon.dao.dn.model.YeuCauDangKyDN} interface instead.
	 */
	public static final String TABLE_NAME = "BRMS_YEUCAUDANGKY";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TEN", Types.VARCHAR },
			{ "MASOTHUE", Types.VARCHAR },
			{ "MAGIAYPHEP", Types.VARCHAR },
			{ "NGAYCAP", Types.TIMESTAMP },
			{ "EMAIL", Types.VARCHAR },
			{ "HONGUOIDAIDIEN", Types.VARCHAR },
			{ "TENDEMNGUOIDAIDIEN", Types.VARCHAR },
			{ "TENNGUOIDAIDIEN", Types.VARCHAR },
			{ "SOCMND", Types.VARCHAR },
			{ "NGAYCAPCMND", Types.TIMESTAMP },
			{ "NOICAPCMNDID", Types.BIGINT },
			{ "MOTANGANHNGHEKINHDOANH", Types.VARCHAR },
			{ "LOAIDOITUONGID", Types.BIGINT },
			{ "TRUSOTINHID", Types.BIGINT },
			{ "TRUSOHUYENID", Types.BIGINT },
			{ "TRUSOXAID", Types.BIGINT },
			{ "TRUSO", Types.VARCHAR },
			{ "DAXOA", Types.INTEGER },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "TRANGTHAI", Types.INTEGER },
			{ "LOAIHINHDOANHNGHIEPID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table BRMS_YEUCAUDANGKY (ID LONG not null primary key,TEN VARCHAR(75) null,MASOTHUE VARCHAR(75) null,MAGIAYPHEP VARCHAR(75) null,NGAYCAP DATE null,EMAIL VARCHAR(75) null,HONGUOIDAIDIEN VARCHAR(75) null,TENDEMNGUOIDAIDIEN VARCHAR(75) null,TENNGUOIDAIDIEN VARCHAR(75) null,SOCMND VARCHAR(75) null,NGAYCAPCMND DATE null,NOICAPCMNDID LONG null,MOTANGANHNGHEKINHDOANH VARCHAR(75) null,LOAIDOITUONGID LONG null,TRUSOTINHID LONG null,TRUSOHUYENID LONG null,TRUSOXAID LONG null,TRUSO VARCHAR(75) null,DAXOA INTEGER,NGAYTAO DATE null,NGUOITAO VARCHAR(75) null,NGAYSUA DATE null,NGUOISUA VARCHAR(75) null,TRANGTHAI INTEGER,LOAIHINHDOANHNGHIEPID LONG null)";
	public static final String TABLE_SQL_DROP = "drop table BRMS_YEUCAUDANGKY";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dn.model.YeuCauDangKyDN"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dn.model.YeuCauDangKyDN"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dn.model.YeuCauDangKyDN"));

	public YeuCauDangKyDNModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return YeuCauDangKyDN.class;
	}

	public String getModelClassName() {
		return YeuCauDangKyDN.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public String getMaSoThue() {
		if (_maSoThue == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoThue;
		}
	}

	public void setMaSoThue(String maSoThue) {
		_maSoThue = maSoThue;
	}

	public String getMaGiayPhep() {
		if (_maGiayPhep == null) {
			return StringPool.BLANK;
		}
		else {
			return _maGiayPhep;
		}
	}

	public void setMaGiayPhep(String maGiayPhep) {
		_maGiayPhep = maGiayPhep;
	}

	public Date getNgayCap() {
		return _ngayCap;
	}

	public void setNgayCap(Date ngayCap) {
		_ngayCap = ngayCap;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public String getHoNguoiDaiDien() {
		if (_hoNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoNguoiDaiDien;
		}
	}

	public void setHoNguoiDaiDien(String hoNguoiDaiDien) {
		_hoNguoiDaiDien = hoNguoiDaiDien;
	}

	public String getTenDemNguoiDaiDien() {
		if (_tenDemNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDemNguoiDaiDien;
		}
	}

	public void setTenDemNguoiDaiDien(String tenDemNguoiDaiDien) {
		_tenDemNguoiDaiDien = tenDemNguoiDaiDien;
	}

	public String getTenNguoiDaiDien() {
		if (_tenNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiDaiDien;
		}
	}

	public void setTenNguoiDaiDien(String tenNguoiDaiDien) {
		_tenNguoiDaiDien = tenNguoiDaiDien;
	}

	public String getSoCmnd() {
		if (_soCmnd == null) {
			return StringPool.BLANK;
		}
		else {
			return _soCmnd;
		}
	}

	public void setSoCmnd(String soCmnd) {
		_soCmnd = soCmnd;
	}

	public Date getNgayCapCmnd() {
		return _ngayCapCmnd;
	}

	public void setNgayCapCmnd(Date ngayCapCmnd) {
		_ngayCapCmnd = ngayCapCmnd;
	}

	public Long getNoiCapCmndId() {
		return _noiCapCmndId;
	}

	public void setNoiCapCmndId(Long noiCapCmndId) {
		_noiCapCmndId = noiCapCmndId;
	}

	public String getMoTa() {
		if (_moTa == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTa;
		}
	}

	public void setMoTa(String moTa) {
		_moTa = moTa;
	}

	public Long getLoaiDoiTuongId() {
		return _loaiDoiTuongId;
	}

	public void setLoaiDoiTuongId(Long loaiDoiTuongId) {
		_loaiDoiTuongId = loaiDoiTuongId;
	}

	public Long getTruSoTinhId() {
		return _truSoTinhId;
	}

	public void setTruSoTinhId(Long truSoTinhId) {
		_truSoTinhId = truSoTinhId;
	}

	public Long getTruSoHuyenId() {
		return _truSoHuyenId;
	}

	public void setTruSoHuyenId(Long truSoHuyenId) {
		_truSoHuyenId = truSoHuyenId;
	}

	public Long getTruSoXaId() {
		return _truSoXaId;
	}

	public void setTruSoXaId(Long truSoXaId) {
		_truSoXaId = truSoXaId;
	}

	public String getTruSo() {
		if (_truSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _truSo;
		}
	}

	public void setTruSo(String truSo) {
		_truSo = truSo;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_daXoa = daXoa;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getTrangThai() {
		return _trangThai;
	}

	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	public Long getLoaiHinhDoanhNghiepId() {
		return _loaiHinhDoanhNghiepId;
	}

	public void setLoaiHinhDoanhNghiepId(Long loaiHinhDoanhNghiepId) {
		_loaiHinhDoanhNghiepId = loaiHinhDoanhNghiepId;
	}

	@Override
	public YeuCauDangKyDN toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (YeuCauDangKyDN)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					YeuCauDangKyDN.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		YeuCauDangKyDNImpl yeuCauDangKyDNImpl = new YeuCauDangKyDNImpl();

		yeuCauDangKyDNImpl.setId(getId());
		yeuCauDangKyDNImpl.setTen(getTen());
		yeuCauDangKyDNImpl.setMaSoThue(getMaSoThue());
		yeuCauDangKyDNImpl.setMaGiayPhep(getMaGiayPhep());
		yeuCauDangKyDNImpl.setNgayCap(getNgayCap());
		yeuCauDangKyDNImpl.setEmail(getEmail());
		yeuCauDangKyDNImpl.setHoNguoiDaiDien(getHoNguoiDaiDien());
		yeuCauDangKyDNImpl.setTenDemNguoiDaiDien(getTenDemNguoiDaiDien());
		yeuCauDangKyDNImpl.setTenNguoiDaiDien(getTenNguoiDaiDien());
		yeuCauDangKyDNImpl.setSoCmnd(getSoCmnd());
		yeuCauDangKyDNImpl.setNgayCapCmnd(getNgayCapCmnd());
		yeuCauDangKyDNImpl.setNoiCapCmndId(getNoiCapCmndId());
		yeuCauDangKyDNImpl.setMoTa(getMoTa());
		yeuCauDangKyDNImpl.setLoaiDoiTuongId(getLoaiDoiTuongId());
		yeuCauDangKyDNImpl.setTruSoTinhId(getTruSoTinhId());
		yeuCauDangKyDNImpl.setTruSoHuyenId(getTruSoHuyenId());
		yeuCauDangKyDNImpl.setTruSoXaId(getTruSoXaId());
		yeuCauDangKyDNImpl.setTruSo(getTruSo());
		yeuCauDangKyDNImpl.setDaXoa(getDaXoa());
		yeuCauDangKyDNImpl.setNgayTao(getNgayTao());
		yeuCauDangKyDNImpl.setNguoiTao(getNguoiTao());
		yeuCauDangKyDNImpl.setNgaySua(getNgaySua());
		yeuCauDangKyDNImpl.setNguoiSua(getNguoiSua());
		yeuCauDangKyDNImpl.setTrangThai(getTrangThai());
		yeuCauDangKyDNImpl.setLoaiHinhDoanhNghiepId(getLoaiHinhDoanhNghiepId());

		yeuCauDangKyDNImpl.resetOriginalValues();

		return yeuCauDangKyDNImpl;
	}

	public int compareTo(YeuCauDangKyDN yeuCauDangKyDN) {
		long primaryKey = yeuCauDangKyDN.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		YeuCauDangKyDN yeuCauDangKyDN = null;

		try {
			yeuCauDangKyDN = (YeuCauDangKyDN)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = yeuCauDangKyDN.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<YeuCauDangKyDN> toCacheModel() {
		YeuCauDangKyDNCacheModel yeuCauDangKyDNCacheModel = new YeuCauDangKyDNCacheModel();

		yeuCauDangKyDNCacheModel.id = getId();

		yeuCauDangKyDNCacheModel.ten = getTen();

		String ten = yeuCauDangKyDNCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			yeuCauDangKyDNCacheModel.ten = null;
		}

		yeuCauDangKyDNCacheModel.maSoThue = getMaSoThue();

		String maSoThue = yeuCauDangKyDNCacheModel.maSoThue;

		if ((maSoThue != null) && (maSoThue.length() == 0)) {
			yeuCauDangKyDNCacheModel.maSoThue = null;
		}

		yeuCauDangKyDNCacheModel.maGiayPhep = getMaGiayPhep();

		String maGiayPhep = yeuCauDangKyDNCacheModel.maGiayPhep;

		if ((maGiayPhep != null) && (maGiayPhep.length() == 0)) {
			yeuCauDangKyDNCacheModel.maGiayPhep = null;
		}

		Date ngayCap = getNgayCap();

		if (ngayCap != null) {
			yeuCauDangKyDNCacheModel.ngayCap = ngayCap.getTime();
		}
		else {
			yeuCauDangKyDNCacheModel.ngayCap = Long.MIN_VALUE;
		}

		yeuCauDangKyDNCacheModel.email = getEmail();

		String email = yeuCauDangKyDNCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			yeuCauDangKyDNCacheModel.email = null;
		}

		yeuCauDangKyDNCacheModel.hoNguoiDaiDien = getHoNguoiDaiDien();

		String hoNguoiDaiDien = yeuCauDangKyDNCacheModel.hoNguoiDaiDien;

		if ((hoNguoiDaiDien != null) && (hoNguoiDaiDien.length() == 0)) {
			yeuCauDangKyDNCacheModel.hoNguoiDaiDien = null;
		}

		yeuCauDangKyDNCacheModel.tenDemNguoiDaiDien = getTenDemNguoiDaiDien();

		String tenDemNguoiDaiDien = yeuCauDangKyDNCacheModel.tenDemNguoiDaiDien;

		if ((tenDemNguoiDaiDien != null) && (tenDemNguoiDaiDien.length() == 0)) {
			yeuCauDangKyDNCacheModel.tenDemNguoiDaiDien = null;
		}

		yeuCauDangKyDNCacheModel.tenNguoiDaiDien = getTenNguoiDaiDien();

		String tenNguoiDaiDien = yeuCauDangKyDNCacheModel.tenNguoiDaiDien;

		if ((tenNguoiDaiDien != null) && (tenNguoiDaiDien.length() == 0)) {
			yeuCauDangKyDNCacheModel.tenNguoiDaiDien = null;
		}

		yeuCauDangKyDNCacheModel.soCmnd = getSoCmnd();

		String soCmnd = yeuCauDangKyDNCacheModel.soCmnd;

		if ((soCmnd != null) && (soCmnd.length() == 0)) {
			yeuCauDangKyDNCacheModel.soCmnd = null;
		}

		Date ngayCapCmnd = getNgayCapCmnd();

		if (ngayCapCmnd != null) {
			yeuCauDangKyDNCacheModel.ngayCapCmnd = ngayCapCmnd.getTime();
		}
		else {
			yeuCauDangKyDNCacheModel.ngayCapCmnd = Long.MIN_VALUE;
		}

		yeuCauDangKyDNCacheModel.noiCapCmndId = getNoiCapCmndId();

		yeuCauDangKyDNCacheModel.moTa = getMoTa();

		String moTa = yeuCauDangKyDNCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			yeuCauDangKyDNCacheModel.moTa = null;
		}

		yeuCauDangKyDNCacheModel.loaiDoiTuongId = getLoaiDoiTuongId();

		yeuCauDangKyDNCacheModel.truSoTinhId = getTruSoTinhId();

		yeuCauDangKyDNCacheModel.truSoHuyenId = getTruSoHuyenId();

		yeuCauDangKyDNCacheModel.truSoXaId = getTruSoXaId();

		yeuCauDangKyDNCacheModel.truSo = getTruSo();

		String truSo = yeuCauDangKyDNCacheModel.truSo;

		if ((truSo != null) && (truSo.length() == 0)) {
			yeuCauDangKyDNCacheModel.truSo = null;
		}

		yeuCauDangKyDNCacheModel.daXoa = getDaXoa();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			yeuCauDangKyDNCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			yeuCauDangKyDNCacheModel.ngayTao = Long.MIN_VALUE;
		}

		yeuCauDangKyDNCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = yeuCauDangKyDNCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			yeuCauDangKyDNCacheModel.nguoiTao = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			yeuCauDangKyDNCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			yeuCauDangKyDNCacheModel.ngaySua = Long.MIN_VALUE;
		}

		yeuCauDangKyDNCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = yeuCauDangKyDNCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			yeuCauDangKyDNCacheModel.nguoiSua = null;
		}

		yeuCauDangKyDNCacheModel.trangThai = getTrangThai();

		yeuCauDangKyDNCacheModel.loaiHinhDoanhNghiepId = getLoaiHinhDoanhNghiepId();

		return yeuCauDangKyDNCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(51);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", maSoThue=");
		sb.append(getMaSoThue());
		sb.append(", maGiayPhep=");
		sb.append(getMaGiayPhep());
		sb.append(", ngayCap=");
		sb.append(getNgayCap());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", hoNguoiDaiDien=");
		sb.append(getHoNguoiDaiDien());
		sb.append(", tenDemNguoiDaiDien=");
		sb.append(getTenDemNguoiDaiDien());
		sb.append(", tenNguoiDaiDien=");
		sb.append(getTenNguoiDaiDien());
		sb.append(", soCmnd=");
		sb.append(getSoCmnd());
		sb.append(", ngayCapCmnd=");
		sb.append(getNgayCapCmnd());
		sb.append(", noiCapCmndId=");
		sb.append(getNoiCapCmndId());
		sb.append(", moTa=");
		sb.append(getMoTa());
		sb.append(", loaiDoiTuongId=");
		sb.append(getLoaiDoiTuongId());
		sb.append(", truSoTinhId=");
		sb.append(getTruSoTinhId());
		sb.append(", truSoHuyenId=");
		sb.append(getTruSoHuyenId());
		sb.append(", truSoXaId=");
		sb.append(getTruSoXaId());
		sb.append(", truSo=");
		sb.append(getTruSo());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", loaiHinhDoanhNghiepId=");
		sb.append(getLoaiHinhDoanhNghiepId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(79);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dn.model.YeuCauDangKyDN");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoThue</column-name><column-value><![CDATA[");
		sb.append(getMaSoThue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maGiayPhep</column-name><column-value><![CDATA[");
		sb.append(getMaGiayPhep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCap</column-name><column-value><![CDATA[");
		sb.append(getNgayCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getHoNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDemNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getTenDemNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCmnd</column-name><column-value><![CDATA[");
		sb.append(getSoCmnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapCmnd</column-name><column-value><![CDATA[");
		sb.append(getNgayCapCmnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapCmndId</column-name><column-value><![CDATA[");
		sb.append(getNoiCapCmndId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTa</column-name><column-value><![CDATA[");
		sb.append(getMoTa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiDoiTuongId</column-name><column-value><![CDATA[");
		sb.append(getLoaiDoiTuongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSoTinhId</column-name><column-value><![CDATA[");
		sb.append(getTruSoTinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSoHuyenId</column-name><column-value><![CDATA[");
		sb.append(getTruSoHuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSoXaId</column-name><column-value><![CDATA[");
		sb.append(getTruSoXaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSo</column-name><column-value><![CDATA[");
		sb.append(getTruSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHinhDoanhNghiepId</column-name><column-value><![CDATA[");
		sb.append(getLoaiHinhDoanhNghiepId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = YeuCauDangKyDN.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			YeuCauDangKyDN.class
		};
	private long _id;
	private String _ten;
	private String _maSoThue;
	private String _maGiayPhep;
	private Date _ngayCap;
	private String _email;
	private String _hoNguoiDaiDien;
	private String _tenDemNguoiDaiDien;
	private String _tenNguoiDaiDien;
	private String _soCmnd;
	private Date _ngayCapCmnd;
	private Long _noiCapCmndId;
	private String _moTa;
	private Long _loaiDoiTuongId;
	private Long _truSoTinhId;
	private Long _truSoHuyenId;
	private Long _truSoXaId;
	private String _truSo;
	private int _daXoa;
	private Date _ngayTao;
	private String _nguoiTao;
	private Date _ngaySua;
	private String _nguoiSua;
	private int _trangThai;
	private Long _loaiHinhDoanhNghiepId;
	private transient ExpandoBridge _expandoBridge;
	private YeuCauDangKyDN _escapedModelProxy;
}