/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.dn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiep;
import org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiepModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the YeuCauDangKyDoanhNghiep service. Represents a row in the &quot;BRMS_YEUCAUDANGKYDOANHNGHIEP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiepModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YeuCauDangKyDoanhNghiepImpl}.
 * </p>
 *
 * @author Liemnn
 * @see YeuCauDangKyDoanhNghiepImpl
 * @see org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiep
 * @see org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiepModel
 * @generated
 */
public class YeuCauDangKyDoanhNghiepModelImpl extends BaseModelImpl<YeuCauDangKyDoanhNghiep>
	implements YeuCauDangKyDoanhNghiepModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a yeu cau dang ky doanh nghiep model instance should use the {@link org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiep} interface instead.
	 */
	public static final String TABLE_NAME = "BRMS_YEUCAUDANGKYDOANHNGHIEP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "LOAIDOITUONGID", Types.BIGINT },
			{ "TEN", Types.VARCHAR },
			{ "MASOTHUE", Types.VARCHAR },
			{ "MAGIAYPHEP", Types.VARCHAR },
			{ "NGAYCAP", Types.TIMESTAMP },
			{ "EMAIL", Types.VARCHAR },
			{ "HONGUOIDAIDIEN", Types.VARCHAR },
			{ "TENDEMNGUOIDAIDIEN", Types.VARCHAR },
			{ "TENNGUOIDAIDIEN", Types.VARCHAR },
			{ "SOCMND", Types.VARCHAR },
			{ "NGAYCAPCMND", Types.TIMESTAMP },
			{ "NOICAPCMND", Types.VARCHAR },
			{ "MOTANGANHNGHEKINHDOANH", Types.VARCHAR },
			{ "LOAIHINHDOANHNGHIEP", Types.VARCHAR },
			{ "TRUSO", Types.VARCHAR },
			{ "TRUSOXAID", Types.BIGINT },
			{ "TRUSOHUYENID", Types.BIGINT },
			{ "TRUSOTINHID", Types.BIGINT },
			{ "TRANGTHAI", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table BRMS_YEUCAUDANGKYDOANHNGHIEP (ID LONG not null primary key,LOAIDOITUONGID LONG,TEN VARCHAR(75) null,MASOTHUE VARCHAR(75) null,MAGIAYPHEP VARCHAR(75) null,NGAYCAP DATE null,EMAIL VARCHAR(75) null,HONGUOIDAIDIEN VARCHAR(75) null,TENDEMNGUOIDAIDIEN VARCHAR(75) null,TENNGUOIDAIDIEN VARCHAR(75) null,SOCMND VARCHAR(75) null,NGAYCAPCMND DATE null,NOICAPCMND VARCHAR(75) null,MOTANGANHNGHEKINHDOANH VARCHAR(75) null,LOAIHINHDOANHNGHIEP VARCHAR(75) null,TRUSO VARCHAR(75) null,TRUSOXAID LONG,TRUSOHUYENID LONG,TRUSOTINHID LONG,TRANGTHAI INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table BRMS_YEUCAUDANGKYDOANHNGHIEP";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiep"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiep"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiep"));

	public YeuCauDangKyDoanhNghiepModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return YeuCauDangKyDoanhNghiep.class;
	}

	public String getModelClassName() {
		return YeuCauDangKyDoanhNghiep.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public long getLoaiDoiTuongId() {
		return _loaiDoiTuongId;
	}

	public void setLoaiDoiTuongId(long loaiDoiTuongId) {
		_loaiDoiTuongId = loaiDoiTuongId;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public String getMaSoThue() {
		if (_maSoThue == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoThue;
		}
	}

	public void setMaSoThue(String maSoThue) {
		_maSoThue = maSoThue;
	}

	public String getMaGiayPhep() {
		if (_maGiayPhep == null) {
			return StringPool.BLANK;
		}
		else {
			return _maGiayPhep;
		}
	}

	public void setMaGiayPhep(String maGiayPhep) {
		_maGiayPhep = maGiayPhep;
	}

	public Date getNgayCap() {
		return _ngayCap;
	}

	public void setNgayCap(Date ngayCap) {
		_ngayCap = ngayCap;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public String getHoNguoiDaiDien() {
		if (_hoNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoNguoiDaiDien;
		}
	}

	public void setHoNguoiDaiDien(String hoNguoiDaiDien) {
		_hoNguoiDaiDien = hoNguoiDaiDien;
	}

	public String getTenDemNguoiDaiDien() {
		if (_tenDemNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDemNguoiDaiDien;
		}
	}

	public void setTenDemNguoiDaiDien(String tenDemNguoiDaiDien) {
		_tenDemNguoiDaiDien = tenDemNguoiDaiDien;
	}

	public String getTenNguoiDaiDien() {
		if (_tenNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiDaiDien;
		}
	}

	public void setTenNguoiDaiDien(String tenNguoiDaiDien) {
		_tenNguoiDaiDien = tenNguoiDaiDien;
	}

	public String getSoCMND() {
		if (_soCMND == null) {
			return StringPool.BLANK;
		}
		else {
			return _soCMND;
		}
	}

	public void setSoCMND(String soCMND) {
		_soCMND = soCMND;
	}

	public Date getNgayCapCMND() {
		return _ngayCapCMND;
	}

	public void setNgayCapCMND(Date ngayCapCMND) {
		_ngayCapCMND = ngayCapCMND;
	}

	public String getNoiCapCMND() {
		if (_noiCapCMND == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiCapCMND;
		}
	}

	public void setNoiCapCMND(String noiCapCMND) {
		_noiCapCMND = noiCapCMND;
	}

	public String getMoTaNganhNgheKinhDoanh() {
		if (_moTaNganhNgheKinhDoanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTaNganhNgheKinhDoanh;
		}
	}

	public void setMoTaNganhNgheKinhDoanh(String moTaNganhNgheKinhDoanh) {
		_moTaNganhNgheKinhDoanh = moTaNganhNgheKinhDoanh;
	}

	public String getLoaiHinhDoanhNghiep() {
		if (_loaiHinhDoanhNghiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiHinhDoanhNghiep;
		}
	}

	public void setLoaiHinhDoanhNghiep(String loaiHinhDoanhNghiep) {
		_loaiHinhDoanhNghiep = loaiHinhDoanhNghiep;
	}

	public String getTruSo() {
		if (_truSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _truSo;
		}
	}

	public void setTruSo(String truSo) {
		_truSo = truSo;
	}

	public long getTruSoXaId() {
		return _truSoXaId;
	}

	public void setTruSoXaId(long truSoXaId) {
		_truSoXaId = truSoXaId;
	}

	public long getTruSoHuyenId() {
		return _truSoHuyenId;
	}

	public void setTruSoHuyenId(long truSoHuyenId) {
		_truSoHuyenId = truSoHuyenId;
	}

	public long getTruSoTinhId() {
		return _truSoTinhId;
	}

	public void setTruSoTinhId(long truSoTinhId) {
		_truSoTinhId = truSoTinhId;
	}

	public int getTrangThai() {
		return _trangThai;
	}

	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	@Override
	public YeuCauDangKyDoanhNghiep toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (YeuCauDangKyDoanhNghiep)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					YeuCauDangKyDoanhNghiep.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		YeuCauDangKyDoanhNghiepImpl yeuCauDangKyDoanhNghiepImpl = new YeuCauDangKyDoanhNghiepImpl();

		yeuCauDangKyDoanhNghiepImpl.setId(getId());
		yeuCauDangKyDoanhNghiepImpl.setLoaiDoiTuongId(getLoaiDoiTuongId());
		yeuCauDangKyDoanhNghiepImpl.setTen(getTen());
		yeuCauDangKyDoanhNghiepImpl.setMaSoThue(getMaSoThue());
		yeuCauDangKyDoanhNghiepImpl.setMaGiayPhep(getMaGiayPhep());
		yeuCauDangKyDoanhNghiepImpl.setNgayCap(getNgayCap());
		yeuCauDangKyDoanhNghiepImpl.setEmail(getEmail());
		yeuCauDangKyDoanhNghiepImpl.setHoNguoiDaiDien(getHoNguoiDaiDien());
		yeuCauDangKyDoanhNghiepImpl.setTenDemNguoiDaiDien(getTenDemNguoiDaiDien());
		yeuCauDangKyDoanhNghiepImpl.setTenNguoiDaiDien(getTenNguoiDaiDien());
		yeuCauDangKyDoanhNghiepImpl.setSoCMND(getSoCMND());
		yeuCauDangKyDoanhNghiepImpl.setNgayCapCMND(getNgayCapCMND());
		yeuCauDangKyDoanhNghiepImpl.setNoiCapCMND(getNoiCapCMND());
		yeuCauDangKyDoanhNghiepImpl.setMoTaNganhNgheKinhDoanh(getMoTaNganhNgheKinhDoanh());
		yeuCauDangKyDoanhNghiepImpl.setLoaiHinhDoanhNghiep(getLoaiHinhDoanhNghiep());
		yeuCauDangKyDoanhNghiepImpl.setTruSo(getTruSo());
		yeuCauDangKyDoanhNghiepImpl.setTruSoXaId(getTruSoXaId());
		yeuCauDangKyDoanhNghiepImpl.setTruSoHuyenId(getTruSoHuyenId());
		yeuCauDangKyDoanhNghiepImpl.setTruSoTinhId(getTruSoTinhId());
		yeuCauDangKyDoanhNghiepImpl.setTrangThai(getTrangThai());

		yeuCauDangKyDoanhNghiepImpl.resetOriginalValues();

		return yeuCauDangKyDoanhNghiepImpl;
	}

	public int compareTo(YeuCauDangKyDoanhNghiep yeuCauDangKyDoanhNghiep) {
		long primaryKey = yeuCauDangKyDoanhNghiep.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		YeuCauDangKyDoanhNghiep yeuCauDangKyDoanhNghiep = null;

		try {
			yeuCauDangKyDoanhNghiep = (YeuCauDangKyDoanhNghiep)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = yeuCauDangKyDoanhNghiep.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<YeuCauDangKyDoanhNghiep> toCacheModel() {
		YeuCauDangKyDoanhNghiepCacheModel yeuCauDangKyDoanhNghiepCacheModel = new YeuCauDangKyDoanhNghiepCacheModel();

		yeuCauDangKyDoanhNghiepCacheModel.id = getId();

		yeuCauDangKyDoanhNghiepCacheModel.loaiDoiTuongId = getLoaiDoiTuongId();

		yeuCauDangKyDoanhNghiepCacheModel.ten = getTen();

		String ten = yeuCauDangKyDoanhNghiepCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.ten = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.maSoThue = getMaSoThue();

		String maSoThue = yeuCauDangKyDoanhNghiepCacheModel.maSoThue;

		if ((maSoThue != null) && (maSoThue.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.maSoThue = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.maGiayPhep = getMaGiayPhep();

		String maGiayPhep = yeuCauDangKyDoanhNghiepCacheModel.maGiayPhep;

		if ((maGiayPhep != null) && (maGiayPhep.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.maGiayPhep = null;
		}

		Date ngayCap = getNgayCap();

		if (ngayCap != null) {
			yeuCauDangKyDoanhNghiepCacheModel.ngayCap = ngayCap.getTime();
		}
		else {
			yeuCauDangKyDoanhNghiepCacheModel.ngayCap = Long.MIN_VALUE;
		}

		yeuCauDangKyDoanhNghiepCacheModel.email = getEmail();

		String email = yeuCauDangKyDoanhNghiepCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.email = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.hoNguoiDaiDien = getHoNguoiDaiDien();

		String hoNguoiDaiDien = yeuCauDangKyDoanhNghiepCacheModel.hoNguoiDaiDien;

		if ((hoNguoiDaiDien != null) && (hoNguoiDaiDien.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.hoNguoiDaiDien = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.tenDemNguoiDaiDien = getTenDemNguoiDaiDien();

		String tenDemNguoiDaiDien = yeuCauDangKyDoanhNghiepCacheModel.tenDemNguoiDaiDien;

		if ((tenDemNguoiDaiDien != null) && (tenDemNguoiDaiDien.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.tenDemNguoiDaiDien = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.tenNguoiDaiDien = getTenNguoiDaiDien();

		String tenNguoiDaiDien = yeuCauDangKyDoanhNghiepCacheModel.tenNguoiDaiDien;

		if ((tenNguoiDaiDien != null) && (tenNguoiDaiDien.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.tenNguoiDaiDien = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.soCMND = getSoCMND();

		String soCMND = yeuCauDangKyDoanhNghiepCacheModel.soCMND;

		if ((soCMND != null) && (soCMND.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.soCMND = null;
		}

		Date ngayCapCMND = getNgayCapCMND();

		if (ngayCapCMND != null) {
			yeuCauDangKyDoanhNghiepCacheModel.ngayCapCMND = ngayCapCMND.getTime();
		}
		else {
			yeuCauDangKyDoanhNghiepCacheModel.ngayCapCMND = Long.MIN_VALUE;
		}

		yeuCauDangKyDoanhNghiepCacheModel.noiCapCMND = getNoiCapCMND();

		String noiCapCMND = yeuCauDangKyDoanhNghiepCacheModel.noiCapCMND;

		if ((noiCapCMND != null) && (noiCapCMND.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.noiCapCMND = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.moTaNganhNgheKinhDoanh = getMoTaNganhNgheKinhDoanh();

		String moTaNganhNgheKinhDoanh = yeuCauDangKyDoanhNghiepCacheModel.moTaNganhNgheKinhDoanh;

		if ((moTaNganhNgheKinhDoanh != null) &&
				(moTaNganhNgheKinhDoanh.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.moTaNganhNgheKinhDoanh = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.loaiHinhDoanhNghiep = getLoaiHinhDoanhNghiep();

		String loaiHinhDoanhNghiep = yeuCauDangKyDoanhNghiepCacheModel.loaiHinhDoanhNghiep;

		if ((loaiHinhDoanhNghiep != null) &&
				(loaiHinhDoanhNghiep.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.loaiHinhDoanhNghiep = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.truSo = getTruSo();

		String truSo = yeuCauDangKyDoanhNghiepCacheModel.truSo;

		if ((truSo != null) && (truSo.length() == 0)) {
			yeuCauDangKyDoanhNghiepCacheModel.truSo = null;
		}

		yeuCauDangKyDoanhNghiepCacheModel.truSoXaId = getTruSoXaId();

		yeuCauDangKyDoanhNghiepCacheModel.truSoHuyenId = getTruSoHuyenId();

		yeuCauDangKyDoanhNghiepCacheModel.truSoTinhId = getTruSoTinhId();

		yeuCauDangKyDoanhNghiepCacheModel.trangThai = getTrangThai();

		return yeuCauDangKyDoanhNghiepCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(41);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", loaiDoiTuongId=");
		sb.append(getLoaiDoiTuongId());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", maSoThue=");
		sb.append(getMaSoThue());
		sb.append(", maGiayPhep=");
		sb.append(getMaGiayPhep());
		sb.append(", ngayCap=");
		sb.append(getNgayCap());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", hoNguoiDaiDien=");
		sb.append(getHoNguoiDaiDien());
		sb.append(", tenDemNguoiDaiDien=");
		sb.append(getTenDemNguoiDaiDien());
		sb.append(", tenNguoiDaiDien=");
		sb.append(getTenNguoiDaiDien());
		sb.append(", soCMND=");
		sb.append(getSoCMND());
		sb.append(", ngayCapCMND=");
		sb.append(getNgayCapCMND());
		sb.append(", noiCapCMND=");
		sb.append(getNoiCapCMND());
		sb.append(", moTaNganhNgheKinhDoanh=");
		sb.append(getMoTaNganhNgheKinhDoanh());
		sb.append(", loaiHinhDoanhNghiep=");
		sb.append(getLoaiHinhDoanhNghiep());
		sb.append(", truSo=");
		sb.append(getTruSo());
		sb.append(", truSoXaId=");
		sb.append(getTruSoXaId());
		sb.append(", truSoHuyenId=");
		sb.append(getTruSoHuyenId());
		sb.append(", truSoTinhId=");
		sb.append(getTruSoTinhId());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(64);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.dn.model.YeuCauDangKyDoanhNghiep");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiDoiTuongId</column-name><column-value><![CDATA[");
		sb.append(getLoaiDoiTuongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoThue</column-name><column-value><![CDATA[");
		sb.append(getMaSoThue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maGiayPhep</column-name><column-value><![CDATA[");
		sb.append(getMaGiayPhep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCap</column-name><column-value><![CDATA[");
		sb.append(getNgayCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getHoNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDemNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getTenDemNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCMND</column-name><column-value><![CDATA[");
		sb.append(getSoCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapCMND</column-name><column-value><![CDATA[");
		sb.append(getNgayCapCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapCMND</column-name><column-value><![CDATA[");
		sb.append(getNoiCapCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTaNganhNgheKinhDoanh</column-name><column-value><![CDATA[");
		sb.append(getMoTaNganhNgheKinhDoanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiHinhDoanhNghiep</column-name><column-value><![CDATA[");
		sb.append(getLoaiHinhDoanhNghiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSo</column-name><column-value><![CDATA[");
		sb.append(getTruSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSoXaId</column-name><column-value><![CDATA[");
		sb.append(getTruSoXaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSoHuyenId</column-name><column-value><![CDATA[");
		sb.append(getTruSoHuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>truSoTinhId</column-name><column-value><![CDATA[");
		sb.append(getTruSoTinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = YeuCauDangKyDoanhNghiep.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			YeuCauDangKyDoanhNghiep.class
		};
	private long _id;
	private long _loaiDoiTuongId;
	private String _ten;
	private String _maSoThue;
	private String _maGiayPhep;
	private Date _ngayCap;
	private String _email;
	private String _hoNguoiDaiDien;
	private String _tenDemNguoiDaiDien;
	private String _tenNguoiDaiDien;
	private String _soCMND;
	private Date _ngayCapCMND;
	private String _noiCapCMND;
	private String _moTaNganhNgheKinhDoanh;
	private String _loaiHinhDoanhNghiep;
	private String _truSo;
	private long _truSoXaId;
	private long _truSoHuyenId;
	private long _truSoTinhId;
	private int _trangThai;
	private transient ExpandoBridge _expandoBridge;
	private YeuCauDangKyDoanhNghiep _escapedModelProxy;
}