/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.thamso.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AnhXa service. Represents a row in the &quot;CMON_DANHMUCANHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.thamso.model.impl.AnhXaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.thamso.model.impl.AnhXaImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see AnhXa
 * @see org.oep.cmon.dao.thamso.model.impl.AnhXaImpl
 * @see org.oep.cmon.dao.thamso.model.impl.AnhXaModelImpl
 * @generated
 */
public interface AnhXaModel extends BaseModel<AnhXa> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a anh xa model instance should use the {@link AnhXa} interface instead.
	 */

	/**
	 * Returns the primary key of this anh xa.
	 *
	 * @return the primary key of this anh xa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this anh xa.
	 *
	 * @param primaryKey the primary key of this anh xa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this anh xa.
	 *
	 * @return the ID of this anh xa
	 */
	public long getId();

	/**
	 * Sets the ID of this anh xa.
	 *
	 * @param Id the ID of this anh xa
	 */
	public void setId(long Id);

	/**
	 * Returns the ma d n g of this anh xa.
	 *
	 * @return the ma d n g of this anh xa
	 */
	@AutoEscape
	public String getMaDNG();

	/**
	 * Sets the ma d n g of this anh xa.
	 *
	 * @param maDNG the ma d n g of this anh xa
	 */
	public void setMaDNG(String maDNG);

	/**
	 * Returns the ten d n g of this anh xa.
	 *
	 * @return the ten d n g of this anh xa
	 */
	@AutoEscape
	public String getTenDNG();

	/**
	 * Sets the ten d n g of this anh xa.
	 *
	 * @param tenDNG the ten d n g of this anh xa
	 */
	public void setTenDNG(String tenDNG);

	/**
	 * Returns the ma khac of this anh xa.
	 *
	 * @return the ma khac of this anh xa
	 */
	@AutoEscape
	public String getMaKhac();

	/**
	 * Sets the ma khac of this anh xa.
	 *
	 * @param maKhac the ma khac of this anh xa
	 */
	public void setMaKhac(String maKhac);

	/**
	 * Returns the ten khac of this anh xa.
	 *
	 * @return the ten khac of this anh xa
	 */
	@AutoEscape
	public String getTenKhac();

	/**
	 * Sets the ten khac of this anh xa.
	 *
	 * @param tenKhac the ten khac of this anh xa
	 */
	public void setTenKhac(String tenKhac);

	/**
	 * Returns the ten bang of this anh xa.
	 *
	 * @return the ten bang of this anh xa
	 */
	@AutoEscape
	public String getTenBang();

	/**
	 * Sets the ten bang of this anh xa.
	 *
	 * @param tenBang the ten bang of this anh xa
	 */
	public void setTenBang(String tenBang);

	/**
	 * Returns the ung dung ID of this anh xa.
	 *
	 * @return the ung dung ID of this anh xa
	 */
	public long getUngDungId();

	/**
	 * Sets the ung dung ID of this anh xa.
	 *
	 * @param UngDungId the ung dung ID of this anh xa
	 */
	public void setUngDungId(long UngDungId);

	/**
	 * Returns the ngay tao of this anh xa.
	 *
	 * @return the ngay tao of this anh xa
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this anh xa.
	 *
	 * @param NgayTao the ngay tao of this anh xa
	 */
	public void setNgayTao(Date NgayTao);

	/**
	 * Returns the nguoi tao of this anh xa.
	 *
	 * @return the nguoi tao of this anh xa
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this anh xa.
	 *
	 * @param NguoiTao the nguoi tao of this anh xa
	 */
	public void setNguoiTao(String NguoiTao);

	/**
	 * Returns the ngay sua of this anh xa.
	 *
	 * @return the ngay sua of this anh xa
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this anh xa.
	 *
	 * @param NgaySua the ngay sua of this anh xa
	 */
	public void setNgaySua(Date NgaySua);

	/**
	 * Returns the nguoi sua of this anh xa.
	 *
	 * @return the nguoi sua of this anh xa
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this anh xa.
	 *
	 * @param NguoiSua the nguoi sua of this anh xa
	 */
	public void setNguoiSua(String NguoiSua);

	/**
	 * Returns the da xoa of this anh xa.
	 *
	 * @return the da xoa of this anh xa
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this anh xa.
	 *
	 * @param DaXoa the da xoa of this anh xa
	 */
	public void setDaXoa(int DaXoa);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AnhXa anhXa);

	public int hashCode();

	public CacheModel<AnhXa> toCacheModel();

	public AnhXa toEscapedModel();

	public String toString();

	public String toXmlString();
}