/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.thamso.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ThamSo service. Represents a row in the &quot;CMON_THAMSO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.thamso.model.impl.ThamSoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.thamso.model.impl.ThamSoImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see ThamSo
 * @see org.oep.cmon.dao.thamso.model.impl.ThamSoImpl
 * @see org.oep.cmon.dao.thamso.model.impl.ThamSoModelImpl
 * @generated
 */
public interface ThamSoModel extends BaseModel<ThamSo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tham so model instance should use the {@link ThamSo} interface instead.
	 */

	/**
	 * Returns the primary key of this tham so.
	 *
	 * @return the primary key of this tham so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tham so.
	 *
	 * @param primaryKey the primary key of this tham so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tham so.
	 *
	 * @return the ID of this tham so
	 */
	public long getId();

	/**
	 * Sets the ID of this tham so.
	 *
	 * @param Id the ID of this tham so
	 */
	public void setId(long Id);

	/**
	 * Returns the ten of this tham so.
	 *
	 * @return the ten of this tham so
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this tham so.
	 *
	 * @param Ten the ten of this tham so
	 */
	public void setTen(String Ten);

	/**
	 * Returns the gia tri of this tham so.
	 *
	 * @return the gia tri of this tham so
	 */
	@AutoEscape
	public String getGiaTri();

	/**
	 * Sets the gia tri of this tham so.
	 *
	 * @param giaTri the gia tri of this tham so
	 */
	public void setGiaTri(String giaTri);

	/**
	 * Returns the kieu du lieu of this tham so.
	 *
	 * @return the kieu du lieu of this tham so
	 */
	public int getKieuDuLieu();

	/**
	 * Sets the kieu du lieu of this tham so.
	 *
	 * @param kieuDuLieu the kieu du lieu of this tham so
	 */
	public void setKieuDuLieu(int kieuDuLieu);

	/**
	 * Returns the mota of this tham so.
	 *
	 * @return the mota of this tham so
	 */
	@AutoEscape
	public String getMota();

	/**
	 * Sets the mota of this tham so.
	 *
	 * @param Mota the mota of this tham so
	 */
	public void setMota(String Mota);

	/**
	 * Returns the ung dung ID of this tham so.
	 *
	 * @return the ung dung ID of this tham so
	 */
	public Long getUngDungId();

	/**
	 * Sets the ung dung ID of this tham so.
	 *
	 * @param UngDungId the ung dung ID of this tham so
	 */
	public void setUngDungId(Long UngDungId);

	/**
	 * Returns the he thong ID of this tham so.
	 *
	 * @return the he thong ID of this tham so
	 */
	public Long getHeThongId();

	/**
	 * Sets the he thong ID of this tham so.
	 *
	 * @param HeThongId the he thong ID of this tham so
	 */
	public void setHeThongId(Long HeThongId);

	/**
	 * Returns the ngay tao of this tham so.
	 *
	 * @return the ngay tao of this tham so
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this tham so.
	 *
	 * @param NgayTao the ngay tao of this tham so
	 */
	public void setNgayTao(Date NgayTao);

	/**
	 * Returns the nguoi tao of this tham so.
	 *
	 * @return the nguoi tao of this tham so
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this tham so.
	 *
	 * @param NguoiTao the nguoi tao of this tham so
	 */
	public void setNguoiTao(String NguoiTao);

	/**
	 * Returns the ngay sua of this tham so.
	 *
	 * @return the ngay sua of this tham so
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this tham so.
	 *
	 * @param NgaySua the ngay sua of this tham so
	 */
	public void setNgaySua(Date NgaySua);

	/**
	 * Returns the nguoi sua of this tham so.
	 *
	 * @return the nguoi sua of this tham so
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this tham so.
	 *
	 * @param NguoiSua the nguoi sua of this tham so
	 */
	public void setNguoiSua(String NguoiSua);

	/**
	 * Returns the da xoa of this tham so.
	 *
	 * @return the da xoa of this tham so
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this tham so.
	 *
	 * @param DaXoa the da xoa of this tham so
	 */
	public void setDaXoa(int DaXoa);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ThamSo thamSo);

	public int hashCode();

	public CacheModel<ThamSo> toCacheModel();

	public ThamSo toEscapedModel();

	public String toString();

	public String toXmlString();
}