/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.ttthanhtoan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan;
import org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToanModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the ThongTinThanhToan service. Represents a row in the &quot;CMON_THONGTINTHANHTOAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThongTinThanhToanImpl}.
 * </p>
 *
 * @author Thanhdd
 * @see ThongTinThanhToanImpl
 * @see org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan
 * @see org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToanModel
 * @generated
 */
public class ThongTinThanhToanModelImpl extends BaseModelImpl<ThongTinThanhToan>
	implements ThongTinThanhToanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thong tin thanh toan model instance should use the {@link org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_THONGTINTHANHTOAN";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "HOSOTTHCCONGID", Types.BIGINT },
			{ "TAIKHOANNGUOIDUNGNOPID", Types.BIGINT },
			{ "TAIKHOANNGUOIDUNGNHANID", Types.BIGINT },
			{ "LOAITHANHTOAN ", Types.BIGINT },
			{ "TENNGUOINOPTIEN ", Types.VARCHAR },
			{ "TENCANBONHANTIEN ", Types.VARCHAR },
			{ "XACNHAN", Types.BIGINT },
			{ "LOAIPHI", Types.BIGINT },
			{ "SOTIEN ", Types.BIGINT },
			{ "NGAYTHUTIEN", Types.TIMESTAMP },
			{ "NGAYXACNHAN ", Types.TIMESTAMP },
			{ "NGAYCHUYENTIEN ", Types.TIMESTAMP },
			{ "YKIEN ", Types.VARCHAR },
			{ "NOILUUTRUID ", Types.BIGINT },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_THONGTINTHANHTOAN (ID LONG not null primary key,HOSOTTHCCONGID LONG,TAIKHOANNGUOIDUNGNOPID LONG null,TAIKHOANNGUOIDUNGNHANID LONG null,LOAITHANHTOAN  LONG,TENNGUOINOPTIEN  VARCHAR(75) null,TENCANBONHANTIEN  VARCHAR(75) null,XACNHAN LONG,LOAIPHI LONG,SOTIEN  LONG,NGAYTHUTIEN DATE null,NGAYXACNHAN  DATE null,NGAYCHUYENTIEN  DATE null,YKIEN  VARCHAR(75) null,NOILUUTRUID  LONG,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,NGAYTAO DATE null,NGAYSUA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_THONGTINTHANHTOAN";
	public static final String ORDER_BY_JPQL = " ORDER BY thongTinThanhToan.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_THONGTINTHANHTOAN.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan"),
			true);
	public static long HOSOTTHCCONGID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan"));

	public ThongTinThanhToanModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ThongTinThanhToan.class;
	}

	public String getModelClassName() {
		return ThongTinThanhToan.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public long getHoSoTTHCCongId() {
		return _hoSoTTHCCongId;
	}

	public void setHoSoTTHCCongId(long hoSoTTHCCongId) {
		_columnBitmask |= HOSOTTHCCONGID_COLUMN_BITMASK;

		if (!_setOriginalHoSoTTHCCongId) {
			_setOriginalHoSoTTHCCongId = true;

			_originalHoSoTTHCCongId = _hoSoTTHCCongId;
		}

		_hoSoTTHCCongId = hoSoTTHCCongId;
	}

	public long getOriginalHoSoTTHCCongId() {
		return _originalHoSoTTHCCongId;
	}

	public Long getTaiKhoanNguoiDungNopId() {
		return _taiKhoanNguoiDungNopId;
	}

	public void setTaiKhoanNguoiDungNopId(Long taiKhoanNguoiDungNopId) {
		_taiKhoanNguoiDungNopId = taiKhoanNguoiDungNopId;
	}

	public Long getTaiKhoanNguoiDungNhanId() {
		return _taiKhoanNguoiDungNhanId;
	}

	public void setTaiKhoanNguoiDungNhanId(Long taiKhoanNguoiDungNhanId) {
		_taiKhoanNguoiDungNhanId = taiKhoanNguoiDungNhanId;
	}

	public long getLoaiThanhToan() {
		return _loaiThanhToan;
	}

	public void setLoaiThanhToan(long loaiThanhToan) {
		_loaiThanhToan = loaiThanhToan;
	}

	public String getTenNguoiNopTien() {
		if (_tenNguoiNopTien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiNopTien;
		}
	}

	public void setTenNguoiNopTien(String tenNguoiNopTien) {
		_tenNguoiNopTien = tenNguoiNopTien;
	}

	public String getTenCanBoNhanTien() {
		if (_tenCanBoNhanTien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenCanBoNhanTien;
		}
	}

	public void setTenCanBoNhanTien(String tenCanBoNhanTien) {
		_tenCanBoNhanTien = tenCanBoNhanTien;
	}

	public long getXacNhan() {
		return _xacNhan;
	}

	public void setXacNhan(long xacNhan) {
		_xacNhan = xacNhan;
	}

	public long getLoaiPhi() {
		return _loaiPhi;
	}

	public void setLoaiPhi(long loaiPhi) {
		_loaiPhi = loaiPhi;
	}

	public long getSoTien() {
		return _soTien;
	}

	public void setSoTien(long soTien) {
		_soTien = soTien;
	}

	public Date getNgayThuTien() {
		return _ngayThuTien;
	}

	public void setNgayThuTien(Date ngayThuTien) {
		_ngayThuTien = ngayThuTien;
	}

	public Date getNgayXacNhan() {
		return _ngayXacNhan;
	}

	public void setNgayXacNhan(Date ngayXacNhan) {
		_ngayXacNhan = ngayXacNhan;
	}

	public Date getNgayChuyenTien() {
		return _ngayChuyenTien;
	}

	public void setNgayChuyenTien(Date ngayChuyenTien) {
		_ngayChuyenTien = ngayChuyenTien;
	}

	public String getYKien() {
		if (_yKien == null) {
			return StringPool.BLANK;
		}
		else {
			return _yKien;
		}
	}

	public void setYKien(String yKien) {
		_yKien = yKien;
	}

	public long getNoiLuuTruId() {
		return _noiLuuTruId;
	}

	public void setNoiLuuTruId(long noiLuuTruId) {
		_noiLuuTruId = noiLuuTruId;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ThongTinThanhToan toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ThongTinThanhToan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					ThongTinThanhToan.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		ThongTinThanhToanImpl thongTinThanhToanImpl = new ThongTinThanhToanImpl();

		thongTinThanhToanImpl.setId(getId());
		thongTinThanhToanImpl.setHoSoTTHCCongId(getHoSoTTHCCongId());
		thongTinThanhToanImpl.setTaiKhoanNguoiDungNopId(getTaiKhoanNguoiDungNopId());
		thongTinThanhToanImpl.setTaiKhoanNguoiDungNhanId(getTaiKhoanNguoiDungNhanId());
		thongTinThanhToanImpl.setLoaiThanhToan(getLoaiThanhToan());
		thongTinThanhToanImpl.setTenNguoiNopTien(getTenNguoiNopTien());
		thongTinThanhToanImpl.setTenCanBoNhanTien(getTenCanBoNhanTien());
		thongTinThanhToanImpl.setXacNhan(getXacNhan());
		thongTinThanhToanImpl.setLoaiPhi(getLoaiPhi());
		thongTinThanhToanImpl.setSoTien(getSoTien());
		thongTinThanhToanImpl.setNgayThuTien(getNgayThuTien());
		thongTinThanhToanImpl.setNgayXacNhan(getNgayXacNhan());
		thongTinThanhToanImpl.setNgayChuyenTien(getNgayChuyenTien());
		thongTinThanhToanImpl.setYKien(getYKien());
		thongTinThanhToanImpl.setNoiLuuTruId(getNoiLuuTruId());
		thongTinThanhToanImpl.setNguoiTao(getNguoiTao());
		thongTinThanhToanImpl.setNguoiSua(getNguoiSua());
		thongTinThanhToanImpl.setNgayTao(getNgayTao());
		thongTinThanhToanImpl.setNgaySua(getNgaySua());

		thongTinThanhToanImpl.resetOriginalValues();

		return thongTinThanhToanImpl;
	}

	public int compareTo(ThongTinThanhToan thongTinThanhToan) {
		int value = 0;

		if (getId() < thongTinThanhToan.getId()) {
			value = -1;
		}
		else if (getId() > thongTinThanhToan.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ThongTinThanhToan thongTinThanhToan = null;

		try {
			thongTinThanhToan = (ThongTinThanhToan)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = thongTinThanhToan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ThongTinThanhToanModelImpl thongTinThanhToanModelImpl = this;

		thongTinThanhToanModelImpl._originalHoSoTTHCCongId = thongTinThanhToanModelImpl._hoSoTTHCCongId;

		thongTinThanhToanModelImpl._setOriginalHoSoTTHCCongId = false;

		thongTinThanhToanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ThongTinThanhToan> toCacheModel() {
		ThongTinThanhToanCacheModel thongTinThanhToanCacheModel = new ThongTinThanhToanCacheModel();

		thongTinThanhToanCacheModel.id = getId();

		thongTinThanhToanCacheModel.hoSoTTHCCongId = getHoSoTTHCCongId();

		thongTinThanhToanCacheModel.taiKhoanNguoiDungNopId = getTaiKhoanNguoiDungNopId();

		thongTinThanhToanCacheModel.taiKhoanNguoiDungNhanId = getTaiKhoanNguoiDungNhanId();

		thongTinThanhToanCacheModel.loaiThanhToan = getLoaiThanhToan();

		thongTinThanhToanCacheModel.tenNguoiNopTien = getTenNguoiNopTien();

		String tenNguoiNopTien = thongTinThanhToanCacheModel.tenNguoiNopTien;

		if ((tenNguoiNopTien != null) && (tenNguoiNopTien.length() == 0)) {
			thongTinThanhToanCacheModel.tenNguoiNopTien = null;
		}

		thongTinThanhToanCacheModel.tenCanBoNhanTien = getTenCanBoNhanTien();

		String tenCanBoNhanTien = thongTinThanhToanCacheModel.tenCanBoNhanTien;

		if ((tenCanBoNhanTien != null) && (tenCanBoNhanTien.length() == 0)) {
			thongTinThanhToanCacheModel.tenCanBoNhanTien = null;
		}

		thongTinThanhToanCacheModel.xacNhan = getXacNhan();

		thongTinThanhToanCacheModel.loaiPhi = getLoaiPhi();

		thongTinThanhToanCacheModel.soTien = getSoTien();

		Date ngayThuTien = getNgayThuTien();

		if (ngayThuTien != null) {
			thongTinThanhToanCacheModel.ngayThuTien = ngayThuTien.getTime();
		}
		else {
			thongTinThanhToanCacheModel.ngayThuTien = Long.MIN_VALUE;
		}

		Date ngayXacNhan = getNgayXacNhan();

		if (ngayXacNhan != null) {
			thongTinThanhToanCacheModel.ngayXacNhan = ngayXacNhan.getTime();
		}
		else {
			thongTinThanhToanCacheModel.ngayXacNhan = Long.MIN_VALUE;
		}

		Date ngayChuyenTien = getNgayChuyenTien();

		if (ngayChuyenTien != null) {
			thongTinThanhToanCacheModel.ngayChuyenTien = ngayChuyenTien.getTime();
		}
		else {
			thongTinThanhToanCacheModel.ngayChuyenTien = Long.MIN_VALUE;
		}

		thongTinThanhToanCacheModel.yKien = getYKien();

		String yKien = thongTinThanhToanCacheModel.yKien;

		if ((yKien != null) && (yKien.length() == 0)) {
			thongTinThanhToanCacheModel.yKien = null;
		}

		thongTinThanhToanCacheModel.noiLuuTruId = getNoiLuuTruId();

		thongTinThanhToanCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = thongTinThanhToanCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			thongTinThanhToanCacheModel.nguoiTao = null;
		}

		thongTinThanhToanCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = thongTinThanhToanCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			thongTinThanhToanCacheModel.nguoiSua = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			thongTinThanhToanCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			thongTinThanhToanCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			thongTinThanhToanCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			thongTinThanhToanCacheModel.ngaySua = Long.MIN_VALUE;
		}

		return thongTinThanhToanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", hoSoTTHCCongId=");
		sb.append(getHoSoTTHCCongId());
		sb.append(", taiKhoanNguoiDungNopId=");
		sb.append(getTaiKhoanNguoiDungNopId());
		sb.append(", taiKhoanNguoiDungNhanId=");
		sb.append(getTaiKhoanNguoiDungNhanId());
		sb.append(", loaiThanhToan=");
		sb.append(getLoaiThanhToan());
		sb.append(", tenNguoiNopTien=");
		sb.append(getTenNguoiNopTien());
		sb.append(", tenCanBoNhanTien=");
		sb.append(getTenCanBoNhanTien());
		sb.append(", xacNhan=");
		sb.append(getXacNhan());
		sb.append(", loaiPhi=");
		sb.append(getLoaiPhi());
		sb.append(", soTien=");
		sb.append(getSoTien());
		sb.append(", ngayThuTien=");
		sb.append(getNgayThuTien());
		sb.append(", ngayXacNhan=");
		sb.append(getNgayXacNhan());
		sb.append(", ngayChuyenTien=");
		sb.append(getNgayChuyenTien());
		sb.append(", yKien=");
		sb.append(getYKien());
		sb.append(", noiLuuTruId=");
		sb.append(getNoiLuuTruId());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.ttthanhtoan.model.ThongTinThanhToan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoSoTTHCCongId</column-name><column-value><![CDATA[");
		sb.append(getHoSoTTHCCongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoanNguoiDungNopId</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoanNguoiDungNopId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoanNguoiDungNhanId</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoanNguoiDungNhanId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiThanhToan</column-name><column-value><![CDATA[");
		sb.append(getLoaiThanhToan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiNopTien</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiNopTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenCanBoNhanTien</column-name><column-value><![CDATA[");
		sb.append(getTenCanBoNhanTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xacNhan</column-name><column-value><![CDATA[");
		sb.append(getXacNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiPhi</column-name><column-value><![CDATA[");
		sb.append(getLoaiPhi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soTien</column-name><column-value><![CDATA[");
		sb.append(getSoTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayThuTien</column-name><column-value><![CDATA[");
		sb.append(getNgayThuTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayXacNhan</column-name><column-value><![CDATA[");
		sb.append(getNgayXacNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayChuyenTien</column-name><column-value><![CDATA[");
		sb.append(getNgayChuyenTien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yKien</column-name><column-value><![CDATA[");
		sb.append(getYKien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiLuuTruId</column-name><column-value><![CDATA[");
		sb.append(getNoiLuuTruId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ThongTinThanhToan.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ThongTinThanhToan.class
		};
	private long _id;
	private long _hoSoTTHCCongId;
	private long _originalHoSoTTHCCongId;
	private boolean _setOriginalHoSoTTHCCongId;
	private Long _taiKhoanNguoiDungNopId;
	private Long _taiKhoanNguoiDungNhanId;
	private long _loaiThanhToan;
	private String _tenNguoiNopTien;
	private String _tenCanBoNhanTien;
	private long _xacNhan;
	private long _loaiPhi;
	private long _soTien;
	private Date _ngayThuTien;
	private Date _ngayXacNhan;
	private Date _ngayChuyenTien;
	private String _yKien;
	private long _noiLuuTruId;
	private String _nguoiTao;
	private String _nguoiSua;
	private Date _ngayTao;
	private Date _ngaySua;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private ThongTinThanhToan _escapedModelProxy;
}