/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.ttthanhtoan.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.ttthanhtoan.model.TienTe;
import org.oep.cmon.dao.ttthanhtoan.model.TienTeModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TienTe service. Represents a row in the &quot;CMON_NGOAITE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.ttthanhtoan.model.TienTeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TienTeImpl}.
 * </p>
 *
 * @author Thanhdd
 * @see TienTeImpl
 * @see org.oep.cmon.dao.ttthanhtoan.model.TienTe
 * @see org.oep.cmon.dao.ttthanhtoan.model.TienTeModel
 * @generated
 */
public class TienTeModelImpl extends BaseModelImpl<TienTe>
	implements TienTeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tien te model instance should use the {@link org.oep.cmon.dao.ttthanhtoan.model.TienTe} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_NGOAITE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "TYGIA", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "TRANGTHAI", Types.INTEGER },
			{ "PHIENBAN", Types.INTEGER },
			{ "DAXOA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_NGOAITE (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,TYGIA LONG,NGAYTAO DATE null,NGUOITAO VARCHAR(75) null,NGAYSUA DATE null,NGUOISUA VARCHAR(75) null,TRANGTHAI INTEGER,PHIENBAN INTEGER,DAXOA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_NGOAITE";
	public static final String ORDER_BY_JPQL = " ORDER BY tienTe.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_NGOAITE.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.ttthanhtoan.model.TienTe"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.ttthanhtoan.model.TienTe"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.ttthanhtoan.model.TienTe"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long MA_COLUMN_BITMASK = 2L;
	public static long TEN_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.ttthanhtoan.model.TienTe"));

	public TienTeModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TienTe.class;
	}

	public String getModelClassName() {
		return TienTe.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	public long getTyGia() {
		return _tyGia;
	}

	public void setTyGia(long tyGia) {
		_tyGia = tyGia;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getTrangThai() {
		return _trangThai;
	}

	public void setTrangThai(int trangThai) {
		_trangThai = trangThai;
	}

	public int getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(int phienBan) {
		_phienBan = phienBan;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TienTe toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TienTe)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TienTe.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TienTeImpl tienTeImpl = new TienTeImpl();

		tienTeImpl.setId(getId());
		tienTeImpl.setMa(getMa());
		tienTeImpl.setTen(getTen());
		tienTeImpl.setTyGia(getTyGia());
		tienTeImpl.setNgayTao(getNgayTao());
		tienTeImpl.setNguoiTao(getNguoiTao());
		tienTeImpl.setNgaySua(getNgaySua());
		tienTeImpl.setNguoiSua(getNguoiSua());
		tienTeImpl.setTrangThai(getTrangThai());
		tienTeImpl.setPhienBan(getPhienBan());
		tienTeImpl.setDaXoa(getDaXoa());

		tienTeImpl.resetOriginalValues();

		return tienTeImpl;
	}

	public int compareTo(TienTe tienTe) {
		int value = 0;

		if (getId() < tienTe.getId()) {
			value = -1;
		}
		else if (getId() > tienTe.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TienTe tienTe = null;

		try {
			tienTe = (TienTe)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tienTe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TienTeModelImpl tienTeModelImpl = this;

		tienTeModelImpl._originalMa = tienTeModelImpl._ma;

		tienTeModelImpl._originalTen = tienTeModelImpl._ten;

		tienTeModelImpl._originalDaXoa = tienTeModelImpl._daXoa;

		tienTeModelImpl._setOriginalDaXoa = false;

		tienTeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TienTe> toCacheModel() {
		TienTeCacheModel tienTeCacheModel = new TienTeCacheModel();

		tienTeCacheModel.id = getId();

		tienTeCacheModel.ma = getMa();

		String ma = tienTeCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			tienTeCacheModel.ma = null;
		}

		tienTeCacheModel.ten = getTen();

		String ten = tienTeCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			tienTeCacheModel.ten = null;
		}

		tienTeCacheModel.tyGia = getTyGia();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			tienTeCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			tienTeCacheModel.ngayTao = Long.MIN_VALUE;
		}

		tienTeCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = tienTeCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			tienTeCacheModel.nguoiTao = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			tienTeCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			tienTeCacheModel.ngaySua = Long.MIN_VALUE;
		}

		tienTeCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = tienTeCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			tienTeCacheModel.nguoiSua = null;
		}

		tienTeCacheModel.trangThai = getTrangThai();

		tienTeCacheModel.phienBan = getPhienBan();

		tienTeCacheModel.daXoa = getDaXoa();

		return tienTeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", tyGia=");
		sb.append(getTyGia());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", trangThai=");
		sb.append(getTrangThai());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.ttthanhtoan.model.TienTe");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tyGia</column-name><column-value><![CDATA[");
		sb.append(getTyGia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TienTe.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TienTe.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private String _originalTen;
	private long _tyGia;
	private Date _ngayTao;
	private String _nguoiTao;
	private Date _ngaySua;
	private String _nguoiSua;
	private int _trangThai;
	private int _phienBan;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TienTe _escapedModelProxy;
}