/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.cd.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChuyenMon service. Represents a row in the &quot;CMON_CHUYENMON&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.cd.model.impl.ChuyenMonModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.cd.model.impl.ChuyenMonImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see ChuyenMon
 * @see org.oep.cmon.dao.cd.model.impl.ChuyenMonImpl
 * @see org.oep.cmon.dao.cd.model.impl.ChuyenMonModelImpl
 * @generated
 */
public interface ChuyenMonModel extends BaseModel<ChuyenMon> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chuyen mon model instance should use the {@link ChuyenMon} interface instead.
	 */

	/**
	 * Returns the primary key of this chuyen mon.
	 *
	 * @return the primary key of this chuyen mon
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chuyen mon.
	 *
	 * @param primaryKey the primary key of this chuyen mon
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chuyen mon.
	 *
	 * @return the ID of this chuyen mon
	 */
	public long getId();

	/**
	 * Sets the ID of this chuyen mon.
	 *
	 * @param id the ID of this chuyen mon
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this chuyen mon.
	 *
	 * @return the ma of this chuyen mon
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this chuyen mon.
	 *
	 * @param ma the ma of this chuyen mon
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this chuyen mon.
	 *
	 * @return the ten of this chuyen mon
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this chuyen mon.
	 *
	 * @param ten the ten of this chuyen mon
	 */
	public void setTen(String ten);

	/**
	 * Returns the phienban of this chuyen mon.
	 *
	 * @return the phienban of this chuyen mon
	 */
	public long getPhienban();

	/**
	 * Sets the phienban of this chuyen mon.
	 *
	 * @param phienban the phienban of this chuyen mon
	 */
	public void setPhienban(long phienban);

	/**
	 * Returns the ngaytao of this chuyen mon.
	 *
	 * @return the ngaytao of this chuyen mon
	 */
	public Date getNgaytao();

	/**
	 * Sets the ngaytao of this chuyen mon.
	 *
	 * @param ngaytao the ngaytao of this chuyen mon
	 */
	public void setNgaytao(Date ngaytao);

	/**
	 * Returns the nguoitao of this chuyen mon.
	 *
	 * @return the nguoitao of this chuyen mon
	 */
	@AutoEscape
	public String getNguoitao();

	/**
	 * Sets the nguoitao of this chuyen mon.
	 *
	 * @param nguoitao the nguoitao of this chuyen mon
	 */
	public void setNguoitao(String nguoitao);

	/**
	 * Returns the ngaysua of this chuyen mon.
	 *
	 * @return the ngaysua of this chuyen mon
	 */
	public Date getNgaysua();

	/**
	 * Sets the ngaysua of this chuyen mon.
	 *
	 * @param ngaysua the ngaysua of this chuyen mon
	 */
	public void setNgaysua(Date ngaysua);

	/**
	 * Returns the nguoisua of this chuyen mon.
	 *
	 * @return the nguoisua of this chuyen mon
	 */
	@AutoEscape
	public String getNguoisua();

	/**
	 * Sets the nguoisua of this chuyen mon.
	 *
	 * @param nguoisua the nguoisua of this chuyen mon
	 */
	public void setNguoisua(String nguoisua);

	/**
	 * Returns the daxoa of this chuyen mon.
	 *
	 * @return the daxoa of this chuyen mon
	 */
	public long getDaxoa();

	/**
	 * Sets the daxoa of this chuyen mon.
	 *
	 * @param daxoa the daxoa of this chuyen mon
	 */
	public void setDaxoa(long daxoa);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ChuyenMon chuyenMon);

	public int hashCode();

	public CacheModel<ChuyenMon> toCacheModel();

	public ChuyenMon toEscapedModel();

	public String toString();

	public String toXmlString();
}