/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.cd.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HoChieuCMND service. Represents a row in the &quot;CSMS_HOCHIEUCMND&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.cd.model.impl.HoChieuCMNDModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.cd.model.impl.HoChieuCMNDImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see HoChieuCMND
 * @see org.oep.cmon.dao.cd.model.impl.HoChieuCMNDImpl
 * @see org.oep.cmon.dao.cd.model.impl.HoChieuCMNDModelImpl
 * @generated
 */
public interface HoChieuCMNDModel extends BaseModel<HoChieuCMND> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ho chieu c m n d model instance should use the {@link HoChieuCMND} interface instead.
	 */

	/**
	 * Returns the primary key of this ho chieu c m n d.
	 *
	 * @return the primary key of this ho chieu c m n d
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ho chieu c m n d.
	 *
	 * @param primaryKey the primary key of this ho chieu c m n d
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ho chieu c m n d.
	 *
	 * @return the ID of this ho chieu c m n d
	 */
	public long getId();

	/**
	 * Sets the ID of this ho chieu c m n d.
	 *
	 * @param id the ID of this ho chieu c m n d
	 */
	public void setId(long id);

	/**
	 * Returns the so of this ho chieu c m n d.
	 *
	 * @return the so of this ho chieu c m n d
	 */
	@AutoEscape
	public String getSo();

	/**
	 * Sets the so of this ho chieu c m n d.
	 *
	 * @param so the so of this ho chieu c m n d
	 */
	public void setSo(String so);

	/**
	 * Returns the ngay cap of this ho chieu c m n d.
	 *
	 * @return the ngay cap of this ho chieu c m n d
	 */
	public Date getNgayCap();

	/**
	 * Sets the ngay cap of this ho chieu c m n d.
	 *
	 * @param ngayCap the ngay cap of this ho chieu c m n d
	 */
	public void setNgayCap(Date ngayCap);

	/**
	 * Returns the ngay het han of this ho chieu c m n d.
	 *
	 * @return the ngay het han of this ho chieu c m n d
	 */
	public Date getNgayHetHan();

	/**
	 * Sets the ngay het han of this ho chieu c m n d.
	 *
	 * @param ngayHetHan the ngay het han of this ho chieu c m n d
	 */
	public void setNgayHetHan(Date ngayHetHan);

	/**
	 * Returns the noi cap ID of this ho chieu c m n d.
	 *
	 * @return the noi cap ID of this ho chieu c m n d
	 */
	public Long getNoiCapId();

	/**
	 * Sets the noi cap ID of this ho chieu c m n d.
	 *
	 * @param noiCapId the noi cap ID of this ho chieu c m n d
	 */
	public void setNoiCapId(Long noiCapId);

	/**
	 * Returns the noi cap of this ho chieu c m n d.
	 *
	 * @return the noi cap of this ho chieu c m n d
	 */
	@AutoEscape
	public String getNoiCap();

	/**
	 * Sets the noi cap of this ho chieu c m n d.
	 *
	 * @param noiCap the noi cap of this ho chieu c m n d
	 */
	public void setNoiCap(String noiCap);

	/**
	 * Returns the gi chu of this ho chieu c m n d.
	 *
	 * @return the gi chu of this ho chieu c m n d
	 */
	@AutoEscape
	public String getGiChu();

	/**
	 * Sets the gi chu of this ho chieu c m n d.
	 *
	 * @param giChu the gi chu of this ho chieu c m n d
	 */
	public void setGiChu(String giChu);

	/**
	 * Returns the loai of this ho chieu c m n d.
	 *
	 * @return the loai of this ho chieu c m n d
	 */
	public int getLoai();

	/**
	 * Sets the loai of this ho chieu c m n d.
	 *
	 * @param loai the loai of this ho chieu c m n d
	 */
	public void setLoai(int loai);

	/**
	 * Returns the trang thai of this ho chieu c m n d.
	 *
	 * @return the trang thai of this ho chieu c m n d
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this ho chieu c m n d.
	 *
	 * @param trangThai the trang thai of this ho chieu c m n d
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the nguoi tao of this ho chieu c m n d.
	 *
	 * @return the nguoi tao of this ho chieu c m n d
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this ho chieu c m n d.
	 *
	 * @param nguoiTao the nguoi tao of this ho chieu c m n d
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the ngay tao of this ho chieu c m n d.
	 *
	 * @return the ngay tao of this ho chieu c m n d
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ho chieu c m n d.
	 *
	 * @param ngayTao the ngay tao of this ho chieu c m n d
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the nguoi sua of this ho chieu c m n d.
	 *
	 * @return the nguoi sua of this ho chieu c m n d
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this ho chieu c m n d.
	 *
	 * @param nguoiSua the nguoi sua of this ho chieu c m n d
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the ngay sua of this ho chieu c m n d.
	 *
	 * @return the ngay sua of this ho chieu c m n d
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this ho chieu c m n d.
	 *
	 * @param ngaySua the ngay sua of this ho chieu c m n d
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the cong dan i d of this ho chieu c m n d.
	 *
	 * @return the cong dan i d of this ho chieu c m n d
	 */
	public Long getCongDanID();

	/**
	 * Sets the cong dan i d of this ho chieu c m n d.
	 *
	 * @param congDanID the cong dan i d of this ho chieu c m n d
	 */
	public void setCongDanID(Long congDanID);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HoChieuCMND hoChieuCMND);

	public int hashCode();

	public CacheModel<HoChieuCMND> toCacheModel();

	public HoChieuCMND toEscapedModel();

	public String toString();

	public String toXmlString();
}