/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.qlhc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy;
import org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLyModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the CapCoQuanQuanLy service. Represents a row in the &quot;CMON_CAPCOQUANQUANLY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CapCoQuanQuanLyImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see CapCoQuanQuanLyImpl
 * @see org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy
 * @see org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLyModel
 * @generated
 */
public class CapCoQuanQuanLyModelImpl extends BaseModelImpl<CapCoQuanQuanLy>
	implements CapCoQuanQuanLyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cap co quan quan ly model instance should use the {@link org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_CAPCOQUANQUANLY";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "CAP", Types.BIGINT },
			{ "CHAID", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "PHIENBAN", Types.INTEGER },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_CAPCOQUANQUANLY (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,CAP LONG,CHAID LONG null,NGAYTAO DATE null,NGAYSUA DATE null,DAXOA INTEGER,PHIENBAN INTEGER,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_CAPCOQUANQUANLY";
	public static final String ORDER_BY_JPQL = " ORDER BY capCoQuanQuanLy.ten ASC, capCoQuanQuanLy.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_CAPCOQUANQUANLY.TEN ASC, CMON_CAPCOQUANQUANLY.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long MA_COLUMN_BITMASK = 2L;
	public static long TEN_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy"));

	public CapCoQuanQuanLyModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CapCoQuanQuanLy.class;
	}

	public String getModelClassName() {
		return CapCoQuanQuanLy.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_columnBitmask = -1L;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	public long getCap() {
		return _cap;
	}

	public void setCap(long cap) {
		_cap = cap;
	}

	public Long getChaId() {
		return _chaId;
	}

	public void setChaId(Long chaId) {
		_chaId = chaId;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public int getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(int phienBan) {
		_phienBan = phienBan;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CapCoQuanQuanLy toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CapCoQuanQuanLy)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CapCoQuanQuanLy.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CapCoQuanQuanLyImpl capCoQuanQuanLyImpl = new CapCoQuanQuanLyImpl();

		capCoQuanQuanLyImpl.setId(getId());
		capCoQuanQuanLyImpl.setMa(getMa());
		capCoQuanQuanLyImpl.setTen(getTen());
		capCoQuanQuanLyImpl.setCap(getCap());
		capCoQuanQuanLyImpl.setChaId(getChaId());
		capCoQuanQuanLyImpl.setNgayTao(getNgayTao());
		capCoQuanQuanLyImpl.setNgaySua(getNgaySua());
		capCoQuanQuanLyImpl.setDaXoa(getDaXoa());
		capCoQuanQuanLyImpl.setPhienBan(getPhienBan());
		capCoQuanQuanLyImpl.setNguoiTao(getNguoiTao());
		capCoQuanQuanLyImpl.setNguoiSua(getNguoiSua());

		capCoQuanQuanLyImpl.resetOriginalValues();

		return capCoQuanQuanLyImpl;
	}

	public int compareTo(CapCoQuanQuanLy capCoQuanQuanLy) {
		int value = 0;

		value = getTen().compareTo(capCoQuanQuanLy.getTen());

		if (value != 0) {
			return value;
		}

		if (getId() < capCoQuanQuanLy.getId()) {
			value = -1;
		}
		else if (getId() > capCoQuanQuanLy.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CapCoQuanQuanLy capCoQuanQuanLy = null;

		try {
			capCoQuanQuanLy = (CapCoQuanQuanLy)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = capCoQuanQuanLy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CapCoQuanQuanLyModelImpl capCoQuanQuanLyModelImpl = this;

		capCoQuanQuanLyModelImpl._originalMa = capCoQuanQuanLyModelImpl._ma;

		capCoQuanQuanLyModelImpl._originalTen = capCoQuanQuanLyModelImpl._ten;

		capCoQuanQuanLyModelImpl._originalDaXoa = capCoQuanQuanLyModelImpl._daXoa;

		capCoQuanQuanLyModelImpl._setOriginalDaXoa = false;

		capCoQuanQuanLyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CapCoQuanQuanLy> toCacheModel() {
		CapCoQuanQuanLyCacheModel capCoQuanQuanLyCacheModel = new CapCoQuanQuanLyCacheModel();

		capCoQuanQuanLyCacheModel.id = getId();

		capCoQuanQuanLyCacheModel.ma = getMa();

		String ma = capCoQuanQuanLyCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			capCoQuanQuanLyCacheModel.ma = null;
		}

		capCoQuanQuanLyCacheModel.ten = getTen();

		String ten = capCoQuanQuanLyCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			capCoQuanQuanLyCacheModel.ten = null;
		}

		capCoQuanQuanLyCacheModel.cap = getCap();

		capCoQuanQuanLyCacheModel.chaId = getChaId();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			capCoQuanQuanLyCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			capCoQuanQuanLyCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			capCoQuanQuanLyCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			capCoQuanQuanLyCacheModel.ngaySua = Long.MIN_VALUE;
		}

		capCoQuanQuanLyCacheModel.daXoa = getDaXoa();

		capCoQuanQuanLyCacheModel.phienBan = getPhienBan();

		capCoQuanQuanLyCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = capCoQuanQuanLyCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			capCoQuanQuanLyCacheModel.nguoiTao = null;
		}

		capCoQuanQuanLyCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = capCoQuanQuanLyCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			capCoQuanQuanLyCacheModel.nguoiSua = null;
		}

		return capCoQuanQuanLyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", cap=");
		sb.append(getCap());
		sb.append(", chaId=");
		sb.append(getChaId());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.qlhc.model.CapCoQuanQuanLy");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cap</column-name><column-value><![CDATA[");
		sb.append(getCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chaId</column-name><column-value><![CDATA[");
		sb.append(getChaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CapCoQuanQuanLy.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CapCoQuanQuanLy.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private String _originalTen;
	private long _cap;
	private Long _chaId;
	private Date _ngayTao;
	private Date _ngaySua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private int _phienBan;
	private String _nguoiTao;
	private String _nguoiSua;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private CapCoQuanQuanLy _escapedModelProxy;
}