/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.qlhc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh;
import org.oep.cmon.dao.qlhc.model.CapDonViHanhChinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the CapDonViHanhChinh service. Represents a row in the &quot;CMON_CAPDONVIHANHCHINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.qlhc.model.CapDonViHanhChinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CapDonViHanhChinhImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see CapDonViHanhChinhImpl
 * @see org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh
 * @see org.oep.cmon.dao.qlhc.model.CapDonViHanhChinhModel
 * @generated
 */
public class CapDonViHanhChinhModelImpl extends BaseModelImpl<CapDonViHanhChinh>
	implements CapDonViHanhChinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cap don vi hanh chinh model instance should use the {@link org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_CAPDONVIHANHCHINH";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "CAP", Types.BIGINT },
			{ "PHIENBAN", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "MOTA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_CAPDONVIHANHCHINH (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,CAP LONG,PHIENBAN LONG,NGAYTAO DATE null,NGAYSUA DATE null,DAXOA INTEGER,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,MOTA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_CAPDONVIHANHCHINH";
	public static final String ORDER_BY_JPQL = " ORDER BY capDonViHanhChinh.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_CAPDONVIHANHCHINH.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh"),
			true);
	public static long CAP_COLUMN_BITMASK = 1L;
	public static long DAXOA_COLUMN_BITMASK = 2L;
	public static long MA_COLUMN_BITMASK = 4L;
	public static long TEN_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh"));

	public CapDonViHanhChinhModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CapDonViHanhChinh.class;
	}

	public String getModelClassName() {
		return CapDonViHanhChinh.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	public long getCap() {
		return _cap;
	}

	public void setCap(long cap) {
		_columnBitmask |= CAP_COLUMN_BITMASK;

		if (!_setOriginalCap) {
			_setOriginalCap = true;

			_originalCap = _cap;
		}

		_cap = cap;
	}

	public long getOriginalCap() {
		return _originalCap;
	}

	public long getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(long phienBan) {
		_phienBan = phienBan;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public String getMota() {
		if (_mota == null) {
			return StringPool.BLANK;
		}
		else {
			return _mota;
		}
	}

	public void setMota(String mota) {
		_mota = mota;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CapDonViHanhChinh toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CapDonViHanhChinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CapDonViHanhChinh.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CapDonViHanhChinhImpl capDonViHanhChinhImpl = new CapDonViHanhChinhImpl();

		capDonViHanhChinhImpl.setId(getId());
		capDonViHanhChinhImpl.setMa(getMa());
		capDonViHanhChinhImpl.setTen(getTen());
		capDonViHanhChinhImpl.setCap(getCap());
		capDonViHanhChinhImpl.setPhienBan(getPhienBan());
		capDonViHanhChinhImpl.setNgayTao(getNgayTao());
		capDonViHanhChinhImpl.setNgaySua(getNgaySua());
		capDonViHanhChinhImpl.setDaXoa(getDaXoa());
		capDonViHanhChinhImpl.setNguoiTao(getNguoiTao());
		capDonViHanhChinhImpl.setNguoiSua(getNguoiSua());
		capDonViHanhChinhImpl.setMota(getMota());

		capDonViHanhChinhImpl.resetOriginalValues();

		return capDonViHanhChinhImpl;
	}

	public int compareTo(CapDonViHanhChinh capDonViHanhChinh) {
		int value = 0;

		if (getId() < capDonViHanhChinh.getId()) {
			value = -1;
		}
		else if (getId() > capDonViHanhChinh.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CapDonViHanhChinh capDonViHanhChinh = null;

		try {
			capDonViHanhChinh = (CapDonViHanhChinh)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = capDonViHanhChinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CapDonViHanhChinhModelImpl capDonViHanhChinhModelImpl = this;

		capDonViHanhChinhModelImpl._originalMa = capDonViHanhChinhModelImpl._ma;

		capDonViHanhChinhModelImpl._originalTen = capDonViHanhChinhModelImpl._ten;

		capDonViHanhChinhModelImpl._originalCap = capDonViHanhChinhModelImpl._cap;

		capDonViHanhChinhModelImpl._setOriginalCap = false;

		capDonViHanhChinhModelImpl._originalDaXoa = capDonViHanhChinhModelImpl._daXoa;

		capDonViHanhChinhModelImpl._setOriginalDaXoa = false;

		capDonViHanhChinhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CapDonViHanhChinh> toCacheModel() {
		CapDonViHanhChinhCacheModel capDonViHanhChinhCacheModel = new CapDonViHanhChinhCacheModel();

		capDonViHanhChinhCacheModel.id = getId();

		capDonViHanhChinhCacheModel.ma = getMa();

		String ma = capDonViHanhChinhCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			capDonViHanhChinhCacheModel.ma = null;
		}

		capDonViHanhChinhCacheModel.ten = getTen();

		String ten = capDonViHanhChinhCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			capDonViHanhChinhCacheModel.ten = null;
		}

		capDonViHanhChinhCacheModel.cap = getCap();

		capDonViHanhChinhCacheModel.phienBan = getPhienBan();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			capDonViHanhChinhCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			capDonViHanhChinhCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			capDonViHanhChinhCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			capDonViHanhChinhCacheModel.ngaySua = Long.MIN_VALUE;
		}

		capDonViHanhChinhCacheModel.daXoa = getDaXoa();

		capDonViHanhChinhCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = capDonViHanhChinhCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			capDonViHanhChinhCacheModel.nguoiTao = null;
		}

		capDonViHanhChinhCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = capDonViHanhChinhCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			capDonViHanhChinhCacheModel.nguoiSua = null;
		}

		capDonViHanhChinhCacheModel.mota = getMota();

		String mota = capDonViHanhChinhCacheModel.mota;

		if ((mota != null) && (mota.length() == 0)) {
			capDonViHanhChinhCacheModel.mota = null;
		}

		return capDonViHanhChinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", cap=");
		sb.append(getCap());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", mota=");
		sb.append(getMota());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.qlhc.model.CapDonViHanhChinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cap</column-name><column-value><![CDATA[");
		sb.append(getCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mota</column-name><column-value><![CDATA[");
		sb.append(getMota());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CapDonViHanhChinh.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CapDonViHanhChinh.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private String _originalTen;
	private long _cap;
	private long _originalCap;
	private boolean _setOriginalCap;
	private long _phienBan;
	private Date _ngayTao;
	private Date _ngaySua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private String _nguoiTao;
	private String _nguoiSua;
	private String _mota;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private CapDonViHanhChinh _escapedModelProxy;
}