/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.qlhc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiep;
import org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiepModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the CoQuanHanhChinhSuNghiep service. Represents a row in the &quot;CMON_COQUANHANHCHINHSUNGHIEP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiepModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoQuanHanhChinhSuNghiepImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see CoQuanHanhChinhSuNghiepImpl
 * @see org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiep
 * @see org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiepModel
 * @generated
 */
public class CoQuanHanhChinhSuNghiepModelImpl extends BaseModelImpl<CoQuanHanhChinhSuNghiep>
	implements CoQuanHanhChinhSuNghiepModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a co quan hanh chinh su nghiep model instance should use the {@link org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiep} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_COQUANHANHCHINHSUNGHIEP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "SDTDUONGDAYNONG", Types.VARCHAR },
			{ "NOIBO", Types.BIGINT },
			{ "CHUCNANG", Types.VARCHAR },
			{ "TONGSOCBNV", Types.BIGINT },
			{ "SODIENTHOAI", Types.VARCHAR },
			{ "FAX", Types.VARCHAR },
			{ "EMAIL", Types.VARCHAR },
			{ "TONGSOGIUONGBENH", Types.BIGINT },
			{ "VIDO", Types.VARCHAR },
			{ "KINHDO", Types.VARCHAR },
			{ "DIACHICOQUANHCSNXAID", Types.BIGINT },
			{ "TUYENID", Types.BIGINT },
			{ "DIACHICOQUANHCSNTINHID", Types.BIGINT },
			{ "NGUOIDAIDIENID", Types.BIGINT },
			{ "DIACHICOQUANHCSNHUYENID", Types.BIGINT },
			{ "HANGID", Types.BIGINT },
			{ "COQUANQUANLYID", Types.VARCHAR },
			{ "LOAIID", Types.VARCHAR },
			{ "SOQDTHANHLAP", Types.VARCHAR },
			{ "MOTADIACHI", Types.VARCHAR },
			{ "TENNGUOIDAIDIEN", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "CHAID", Types.BIGINT },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_COQUANHANHCHINHSUNGHIEP (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,SDTDUONGDAYNONG VARCHAR(75) null,NOIBO LONG,CHUCNANG VARCHAR(75) null,TONGSOCBNV LONG,SODIENTHOAI VARCHAR(75) null,FAX VARCHAR(75) null,EMAIL VARCHAR(75) null,TONGSOGIUONGBENH LONG,VIDO VARCHAR(75) null,KINHDO VARCHAR(75) null,DIACHICOQUANHCSNXAID LONG,TUYENID LONG,DIACHICOQUANHCSNTINHID LONG,NGUOIDAIDIENID LONG,DIACHICOQUANHCSNHUYENID LONG,HANGID LONG,COQUANQUANLYID VARCHAR(75) null,LOAIID VARCHAR(75) null,SOQDTHANHLAP VARCHAR(75) null,MOTADIACHI VARCHAR(75) null,TENNGUOIDAIDIEN VARCHAR(75) null,NGAYTAO DATE null,DAXOA INTEGER,NGAYSUA DATE null,CHAID LONG null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_COQUANHANHCHINHSUNGHIEP";
	public static final String ORDER_BY_JPQL = " ORDER BY coQuanHanhChinhSuNghiep.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_COQUANHANHCHINHSUNGHIEP.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiep"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiep"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiep"));

	public CoQuanHanhChinhSuNghiepModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CoQuanHanhChinhSuNghiep.class;
	}

	public String getModelClassName() {
		return CoQuanHanhChinhSuNghiep.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_ma = ma;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public String getSoDTDuongDayNong() {
		if (_soDTDuongDayNong == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDTDuongDayNong;
		}
	}

	public void setSoDTDuongDayNong(String soDTDuongDayNong) {
		_soDTDuongDayNong = soDTDuongDayNong;
	}

	public long getNoiBo() {
		return _noiBo;
	}

	public void setNoiBo(long noiBo) {
		_noiBo = noiBo;
	}

	public String getChucNang() {
		if (_chucNang == null) {
			return StringPool.BLANK;
		}
		else {
			return _chucNang;
		}
	}

	public void setChucNang(String chucNang) {
		_chucNang = chucNang;
	}

	public long getTongSoCBNV() {
		return _tongSoCBNV;
	}

	public void setTongSoCBNV(long tongSoCBNV) {
		_tongSoCBNV = tongSoCBNV;
	}

	public String getSoDT() {
		if (_soDT == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDT;
		}
	}

	public void setSoDT(String soDT) {
		_soDT = soDT;
	}

	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	public void setFax(String fax) {
		_fax = fax;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public long getTongSoGiuongBenh() {
		return _tongSoGiuongBenh;
	}

	public void setTongSoGiuongBenh(long tongSoGiuongBenh) {
		_tongSoGiuongBenh = tongSoGiuongBenh;
	}

	public String getViDo() {
		if (_viDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _viDo;
		}
	}

	public void setViDo(String viDo) {
		_viDo = viDo;
	}

	public String getKinhDo() {
		if (_kinhDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _kinhDo;
		}
	}

	public void setKinhDo(String kinhDo) {
		_kinhDo = kinhDo;
	}

	public long getDiaChiCoQuanHCSNXaId() {
		return _diaChiCoQuanHCSNXaId;
	}

	public void setDiaChiCoQuanHCSNXaId(long diaChiCoQuanHCSNXaId) {
		_diaChiCoQuanHCSNXaId = diaChiCoQuanHCSNXaId;
	}

	public long getTuyenId() {
		return _tuyenId;
	}

	public void setTuyenId(long tuyenId) {
		_tuyenId = tuyenId;
	}

	public long getDiaChiCoQuanHCSNTinhId() {
		return _diaChiCoQuanHCSNTinhId;
	}

	public void setDiaChiCoQuanHCSNTinhId(long diaChiCoQuanHCSNTinhId) {
		_diaChiCoQuanHCSNTinhId = diaChiCoQuanHCSNTinhId;
	}

	public long getNguoiDaiDienId() {
		return _nguoiDaiDienId;
	}

	public void setNguoiDaiDienId(long nguoiDaiDienId) {
		_nguoiDaiDienId = nguoiDaiDienId;
	}

	public long getDiaChiCoQuanHCSNHuyenId() {
		return _diaChiCoQuanHCSNHuyenId;
	}

	public void setDiaChiCoQuanHCSNHuyenId(long diaChiCoQuanHCSNHuyenId) {
		_diaChiCoQuanHCSNHuyenId = diaChiCoQuanHCSNHuyenId;
	}

	public long getHangId() {
		return _hangId;
	}

	public void setHangId(long hangId) {
		_hangId = hangId;
	}

	public String getCoQuanQuanLyId() {
		if (_coQuanQuanLyId == null) {
			return StringPool.BLANK;
		}
		else {
			return _coQuanQuanLyId;
		}
	}

	public void setCoQuanQuanLyId(String coQuanQuanLyId) {
		_coQuanQuanLyId = coQuanQuanLyId;
	}

	public String getLoaiId() {
		if (_loaiId == null) {
			return StringPool.BLANK;
		}
		else {
			return _loaiId;
		}
	}

	public void setLoaiId(String loaiId) {
		_loaiId = loaiId;
	}

	public String getSoQdThanhLap() {
		if (_soQdThanhLap == null) {
			return StringPool.BLANK;
		}
		else {
			return _soQdThanhLap;
		}
	}

	public void setSoQdThanhLap(String soQdThanhLap) {
		_soQdThanhLap = soQdThanhLap;
	}

	public String getMoTaDiaChi() {
		if (_moTaDiaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _moTaDiaChi;
		}
	}

	public void setMoTaDiaChi(String moTaDiaChi) {
		_moTaDiaChi = moTaDiaChi;
	}

	public String getTenNguoiDaiDien() {
		if (_tenNguoiDaiDien == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiDaiDien;
		}
	}

	public void setTenNguoiDaiDien(String tenNguoiDaiDien) {
		_tenNguoiDaiDien = tenNguoiDaiDien;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_daXoa = daXoa;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public Long getChaId() {
		return _chaId;
	}

	public void setChaId(Long chaId) {
		_chaId = chaId;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	@Override
	public CoQuanHanhChinhSuNghiep toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CoQuanHanhChinhSuNghiep)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CoQuanHanhChinhSuNghiep.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CoQuanHanhChinhSuNghiepImpl coQuanHanhChinhSuNghiepImpl = new CoQuanHanhChinhSuNghiepImpl();

		coQuanHanhChinhSuNghiepImpl.setId(getId());
		coQuanHanhChinhSuNghiepImpl.setMa(getMa());
		coQuanHanhChinhSuNghiepImpl.setTen(getTen());
		coQuanHanhChinhSuNghiepImpl.setSoDTDuongDayNong(getSoDTDuongDayNong());
		coQuanHanhChinhSuNghiepImpl.setNoiBo(getNoiBo());
		coQuanHanhChinhSuNghiepImpl.setChucNang(getChucNang());
		coQuanHanhChinhSuNghiepImpl.setTongSoCBNV(getTongSoCBNV());
		coQuanHanhChinhSuNghiepImpl.setSoDT(getSoDT());
		coQuanHanhChinhSuNghiepImpl.setFax(getFax());
		coQuanHanhChinhSuNghiepImpl.setEmail(getEmail());
		coQuanHanhChinhSuNghiepImpl.setTongSoGiuongBenh(getTongSoGiuongBenh());
		coQuanHanhChinhSuNghiepImpl.setViDo(getViDo());
		coQuanHanhChinhSuNghiepImpl.setKinhDo(getKinhDo());
		coQuanHanhChinhSuNghiepImpl.setDiaChiCoQuanHCSNXaId(getDiaChiCoQuanHCSNXaId());
		coQuanHanhChinhSuNghiepImpl.setTuyenId(getTuyenId());
		coQuanHanhChinhSuNghiepImpl.setDiaChiCoQuanHCSNTinhId(getDiaChiCoQuanHCSNTinhId());
		coQuanHanhChinhSuNghiepImpl.setNguoiDaiDienId(getNguoiDaiDienId());
		coQuanHanhChinhSuNghiepImpl.setDiaChiCoQuanHCSNHuyenId(getDiaChiCoQuanHCSNHuyenId());
		coQuanHanhChinhSuNghiepImpl.setHangId(getHangId());
		coQuanHanhChinhSuNghiepImpl.setCoQuanQuanLyId(getCoQuanQuanLyId());
		coQuanHanhChinhSuNghiepImpl.setLoaiId(getLoaiId());
		coQuanHanhChinhSuNghiepImpl.setSoQdThanhLap(getSoQdThanhLap());
		coQuanHanhChinhSuNghiepImpl.setMoTaDiaChi(getMoTaDiaChi());
		coQuanHanhChinhSuNghiepImpl.setTenNguoiDaiDien(getTenNguoiDaiDien());
		coQuanHanhChinhSuNghiepImpl.setNgayTao(getNgayTao());
		coQuanHanhChinhSuNghiepImpl.setDaXoa(getDaXoa());
		coQuanHanhChinhSuNghiepImpl.setNgaySua(getNgaySua());
		coQuanHanhChinhSuNghiepImpl.setChaId(getChaId());
		coQuanHanhChinhSuNghiepImpl.setNguoiTao(getNguoiTao());
		coQuanHanhChinhSuNghiepImpl.setNguoiSua(getNguoiSua());

		coQuanHanhChinhSuNghiepImpl.resetOriginalValues();

		return coQuanHanhChinhSuNghiepImpl;
	}

	public int compareTo(CoQuanHanhChinhSuNghiep coQuanHanhChinhSuNghiep) {
		int value = 0;

		if (getId() < coQuanHanhChinhSuNghiep.getId()) {
			value = -1;
		}
		else if (getId() > coQuanHanhChinhSuNghiep.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CoQuanHanhChinhSuNghiep coQuanHanhChinhSuNghiep = null;

		try {
			coQuanHanhChinhSuNghiep = (CoQuanHanhChinhSuNghiep)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = coQuanHanhChinhSuNghiep.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CoQuanHanhChinhSuNghiep> toCacheModel() {
		CoQuanHanhChinhSuNghiepCacheModel coQuanHanhChinhSuNghiepCacheModel = new CoQuanHanhChinhSuNghiepCacheModel();

		coQuanHanhChinhSuNghiepCacheModel.id = getId();

		coQuanHanhChinhSuNghiepCacheModel.ma = getMa();

		String ma = coQuanHanhChinhSuNghiepCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.ma = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.ten = getTen();

		String ten = coQuanHanhChinhSuNghiepCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.ten = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.soDTDuongDayNong = getSoDTDuongDayNong();

		String soDTDuongDayNong = coQuanHanhChinhSuNghiepCacheModel.soDTDuongDayNong;

		if ((soDTDuongDayNong != null) && (soDTDuongDayNong.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.soDTDuongDayNong = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.noiBo = getNoiBo();

		coQuanHanhChinhSuNghiepCacheModel.chucNang = getChucNang();

		String chucNang = coQuanHanhChinhSuNghiepCacheModel.chucNang;

		if ((chucNang != null) && (chucNang.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.chucNang = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.tongSoCBNV = getTongSoCBNV();

		coQuanHanhChinhSuNghiepCacheModel.soDT = getSoDT();

		String soDT = coQuanHanhChinhSuNghiepCacheModel.soDT;

		if ((soDT != null) && (soDT.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.soDT = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.fax = getFax();

		String fax = coQuanHanhChinhSuNghiepCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.fax = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.email = getEmail();

		String email = coQuanHanhChinhSuNghiepCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.email = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.tongSoGiuongBenh = getTongSoGiuongBenh();

		coQuanHanhChinhSuNghiepCacheModel.viDo = getViDo();

		String viDo = coQuanHanhChinhSuNghiepCacheModel.viDo;

		if ((viDo != null) && (viDo.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.viDo = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.kinhDo = getKinhDo();

		String kinhDo = coQuanHanhChinhSuNghiepCacheModel.kinhDo;

		if ((kinhDo != null) && (kinhDo.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.kinhDo = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.diaChiCoQuanHCSNXaId = getDiaChiCoQuanHCSNXaId();

		coQuanHanhChinhSuNghiepCacheModel.tuyenId = getTuyenId();

		coQuanHanhChinhSuNghiepCacheModel.diaChiCoQuanHCSNTinhId = getDiaChiCoQuanHCSNTinhId();

		coQuanHanhChinhSuNghiepCacheModel.nguoiDaiDienId = getNguoiDaiDienId();

		coQuanHanhChinhSuNghiepCacheModel.diaChiCoQuanHCSNHuyenId = getDiaChiCoQuanHCSNHuyenId();

		coQuanHanhChinhSuNghiepCacheModel.hangId = getHangId();

		coQuanHanhChinhSuNghiepCacheModel.coQuanQuanLyId = getCoQuanQuanLyId();

		String coQuanQuanLyId = coQuanHanhChinhSuNghiepCacheModel.coQuanQuanLyId;

		if ((coQuanQuanLyId != null) && (coQuanQuanLyId.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.coQuanQuanLyId = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.loaiId = getLoaiId();

		String loaiId = coQuanHanhChinhSuNghiepCacheModel.loaiId;

		if ((loaiId != null) && (loaiId.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.loaiId = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.soQdThanhLap = getSoQdThanhLap();

		String soQdThanhLap = coQuanHanhChinhSuNghiepCacheModel.soQdThanhLap;

		if ((soQdThanhLap != null) && (soQdThanhLap.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.soQdThanhLap = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.moTaDiaChi = getMoTaDiaChi();

		String moTaDiaChi = coQuanHanhChinhSuNghiepCacheModel.moTaDiaChi;

		if ((moTaDiaChi != null) && (moTaDiaChi.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.moTaDiaChi = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.tenNguoiDaiDien = getTenNguoiDaiDien();

		String tenNguoiDaiDien = coQuanHanhChinhSuNghiepCacheModel.tenNguoiDaiDien;

		if ((tenNguoiDaiDien != null) && (tenNguoiDaiDien.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.tenNguoiDaiDien = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			coQuanHanhChinhSuNghiepCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			coQuanHanhChinhSuNghiepCacheModel.ngayTao = Long.MIN_VALUE;
		}

		coQuanHanhChinhSuNghiepCacheModel.daXoa = getDaXoa();

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			coQuanHanhChinhSuNghiepCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			coQuanHanhChinhSuNghiepCacheModel.ngaySua = Long.MIN_VALUE;
		}

		coQuanHanhChinhSuNghiepCacheModel.chaId = getChaId();

		coQuanHanhChinhSuNghiepCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = coQuanHanhChinhSuNghiepCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.nguoiTao = null;
		}

		coQuanHanhChinhSuNghiepCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = coQuanHanhChinhSuNghiepCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			coQuanHanhChinhSuNghiepCacheModel.nguoiSua = null;
		}

		return coQuanHanhChinhSuNghiepCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(61);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", soDTDuongDayNong=");
		sb.append(getSoDTDuongDayNong());
		sb.append(", noiBo=");
		sb.append(getNoiBo());
		sb.append(", chucNang=");
		sb.append(getChucNang());
		sb.append(", tongSoCBNV=");
		sb.append(getTongSoCBNV());
		sb.append(", soDT=");
		sb.append(getSoDT());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", tongSoGiuongBenh=");
		sb.append(getTongSoGiuongBenh());
		sb.append(", viDo=");
		sb.append(getViDo());
		sb.append(", kinhDo=");
		sb.append(getKinhDo());
		sb.append(", diaChiCoQuanHCSNXaId=");
		sb.append(getDiaChiCoQuanHCSNXaId());
		sb.append(", tuyenId=");
		sb.append(getTuyenId());
		sb.append(", diaChiCoQuanHCSNTinhId=");
		sb.append(getDiaChiCoQuanHCSNTinhId());
		sb.append(", nguoiDaiDienId=");
		sb.append(getNguoiDaiDienId());
		sb.append(", diaChiCoQuanHCSNHuyenId=");
		sb.append(getDiaChiCoQuanHCSNHuyenId());
		sb.append(", hangId=");
		sb.append(getHangId());
		sb.append(", coQuanQuanLyId=");
		sb.append(getCoQuanQuanLyId());
		sb.append(", loaiId=");
		sb.append(getLoaiId());
		sb.append(", soQdThanhLap=");
		sb.append(getSoQdThanhLap());
		sb.append(", moTaDiaChi=");
		sb.append(getMoTaDiaChi());
		sb.append(", tenNguoiDaiDien=");
		sb.append(getTenNguoiDaiDien());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", chaId=");
		sb.append(getChaId());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(94);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.qlhc.model.CoQuanHanhChinhSuNghiep");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDTDuongDayNong</column-name><column-value><![CDATA[");
		sb.append(getSoDTDuongDayNong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiBo</column-name><column-value><![CDATA[");
		sb.append(getNoiBo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chucNang</column-name><column-value><![CDATA[");
		sb.append(getChucNang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoCBNV</column-name><column-value><![CDATA[");
		sb.append(getTongSoCBNV());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDT</column-name><column-value><![CDATA[");
		sb.append(getSoDT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tongSoGiuongBenh</column-name><column-value><![CDATA[");
		sb.append(getTongSoGiuongBenh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viDo</column-name><column-value><![CDATA[");
		sb.append(getViDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kinhDo</column-name><column-value><![CDATA[");
		sb.append(getKinhDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiCoQuanHCSNXaId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiCoQuanHCSNXaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tuyenId</column-name><column-value><![CDATA[");
		sb.append(getTuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiCoQuanHCSNTinhId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiCoQuanHCSNTinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiDaiDienId</column-name><column-value><![CDATA[");
		sb.append(getNguoiDaiDienId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiCoQuanHCSNHuyenId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiCoQuanHCSNHuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hangId</column-name><column-value><![CDATA[");
		sb.append(getHangId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coQuanQuanLyId</column-name><column-value><![CDATA[");
		sb.append(getCoQuanQuanLyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loaiId</column-name><column-value><![CDATA[");
		sb.append(getLoaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soQdThanhLap</column-name><column-value><![CDATA[");
		sb.append(getSoQdThanhLap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moTaDiaChi</column-name><column-value><![CDATA[");
		sb.append(getMoTaDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiDaiDien</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiDaiDien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chaId</column-name><column-value><![CDATA[");
		sb.append(getChaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CoQuanHanhChinhSuNghiep.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CoQuanHanhChinhSuNghiep.class
		};
	private long _id;
	private String _ma;
	private String _ten;
	private String _soDTDuongDayNong;
	private long _noiBo;
	private String _chucNang;
	private long _tongSoCBNV;
	private String _soDT;
	private String _fax;
	private String _email;
	private long _tongSoGiuongBenh;
	private String _viDo;
	private String _kinhDo;
	private long _diaChiCoQuanHCSNXaId;
	private long _tuyenId;
	private long _diaChiCoQuanHCSNTinhId;
	private long _nguoiDaiDienId;
	private long _diaChiCoQuanHCSNHuyenId;
	private long _hangId;
	private String _coQuanQuanLyId;
	private String _loaiId;
	private String _soQdThanhLap;
	private String _moTaDiaChi;
	private String _tenNguoiDaiDien;
	private Date _ngayTao;
	private int _daXoa;
	private Date _ngaySua;
	private Long _chaId;
	private String _nguoiTao;
	private String _nguoiSua;
	private transient ExpandoBridge _expandoBridge;
	private CoQuanHanhChinhSuNghiep _escapedModelProxy;
}