/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.qlhc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.qlhc.model.CoQuanQuanLy;
import org.oep.cmon.dao.qlhc.model.CoQuanQuanLyModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the CoQuanQuanLy service. Represents a row in the &quot;CMON_COQUANQUANLY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.qlhc.model.CoQuanQuanLyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoQuanQuanLyImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see CoQuanQuanLyImpl
 * @see org.oep.cmon.dao.qlhc.model.CoQuanQuanLy
 * @see org.oep.cmon.dao.qlhc.model.CoQuanQuanLyModel
 * @generated
 */
public class CoQuanQuanLyModelImpl extends BaseModelImpl<CoQuanQuanLy>
	implements CoQuanQuanLyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a co quan quan ly model instance should use the {@link org.oep.cmon.dao.qlhc.model.CoQuanQuanLy} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_COQUANQUANLY";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "DIACHI", Types.VARCHAR },
			{ "DIENTHOAI", Types.VARCHAR },
			{ "EMAIL", Types.VARCHAR },
			{ "FAX", Types.VARCHAR },
			{ "WEBSITE", Types.VARCHAR },
			{ "NOIBO", Types.INTEGER },
			{ "PHIENBAN", Types.BIGINT },
			{ "DAXOA", Types.INTEGER },
			{ "DONVIHANHCHINHID", Types.BIGINT },
			{ "CAPCOQUANQUANLYID", Types.BIGINT },
			{ "CHAID", Types.BIGINT },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "MERCHANT", Types.VARCHAR },
			{ "ACCESSCODE", Types.VARCHAR },
			{ "SECURE_SECRET", Types.VARCHAR },
			{ "MACAPSOBIENNHAN", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_COQUANQUANLY (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,DIACHI VARCHAR(75) null,DIENTHOAI VARCHAR(75) null,EMAIL VARCHAR(75) null,FAX VARCHAR(75) null,WEBSITE VARCHAR(75) null,NOIBO INTEGER,PHIENBAN LONG,DAXOA INTEGER,DONVIHANHCHINHID LONG null,CAPCOQUANQUANLYID LONG null,CHAID LONG null,NGUOITAO VARCHAR(75) null,NGAYTAO DATE null,NGUOISUA VARCHAR(75) null,NGAYSUA DATE null,MERCHANT VARCHAR(75) null,ACCESSCODE VARCHAR(75) null,SECURE_SECRET VARCHAR(75) null,MACAPSOBIENNHAN VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_COQUANQUANLY";
	public static final String ORDER_BY_JPQL = " ORDER BY coQuanQuanLy.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_COQUANQUANLY.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.qlhc.model.CoQuanQuanLy"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.qlhc.model.CoQuanQuanLy"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.qlhc.model.CoQuanQuanLy"),
			true);
	public static long CAPCOQUANQUANLYID_COLUMN_BITMASK = 1L;
	public static long CHAID_COLUMN_BITMASK = 2L;
	public static long DAXOA_COLUMN_BITMASK = 4L;
	public static long DONVIHANHCHINHID_COLUMN_BITMASK = 8L;
	public static long MA_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.qlhc.model.CoQuanQuanLy"));

	public CoQuanQuanLyModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CoQuanQuanLy.class;
	}

	public String getModelClassName() {
		return CoQuanQuanLy.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public String getDiaChi() {
		if (_diaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChi;
		}
	}

	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	public String getDienThoai() {
		if (_dienThoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoai;
		}
	}

	public void setDienThoai(String dienThoai) {
		_dienThoai = dienThoai;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	public void setFax(String fax) {
		_fax = fax;
	}

	public String getWebsite() {
		if (_website == null) {
			return StringPool.BLANK;
		}
		else {
			return _website;
		}
	}

	public void setWebsite(String website) {
		_website = website;
	}

	public int getNoiBo() {
		return _noiBo;
	}

	public void setNoiBo(int noiBo) {
		_noiBo = noiBo;
	}

	public long getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(long phienBan) {
		_phienBan = phienBan;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public Long getDonViHanhChinhId() {
		return _donViHanhChinhId;
	}

	public void setDonViHanhChinhId(Long donViHanhChinhId) {
		_columnBitmask |= DONVIHANHCHINHID_COLUMN_BITMASK;

		if (!_setOriginalDonViHanhChinhId) {
			_setOriginalDonViHanhChinhId = true;

			_originalDonViHanhChinhId = _donViHanhChinhId;
		}

		_donViHanhChinhId = donViHanhChinhId;
	}

	public Long getOriginalDonViHanhChinhId() {
		return _originalDonViHanhChinhId;
	}

	public Long getCapCoQuanQuanlyId() {
		return _capCoQuanQuanlyId;
	}

	public void setCapCoQuanQuanlyId(Long capCoQuanQuanlyId) {
		_columnBitmask |= CAPCOQUANQUANLYID_COLUMN_BITMASK;

		if (!_setOriginalCapCoQuanQuanlyId) {
			_setOriginalCapCoQuanQuanlyId = true;

			_originalCapCoQuanQuanlyId = _capCoQuanQuanlyId;
		}

		_capCoQuanQuanlyId = capCoQuanQuanlyId;
	}

	public Long getOriginalCapCoQuanQuanlyId() {
		return _originalCapCoQuanQuanlyId;
	}

	public Long getChaId() {
		return _chaId;
	}

	public void setChaId(Long chaId) {
		_columnBitmask |= CHAID_COLUMN_BITMASK;

		if (!_setOriginalChaId) {
			_setOriginalChaId = true;

			_originalChaId = _chaId;
		}

		_chaId = chaId;
	}

	public Long getOriginalChaId() {
		return _originalChaId;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getMerchant() {
		if (_merchant == null) {
			return StringPool.BLANK;
		}
		else {
			return _merchant;
		}
	}

	public void setMerchant(String merchant) {
		_merchant = merchant;
	}

	public String getAccessCode() {
		if (_accessCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _accessCode;
		}
	}

	public void setAccessCode(String accessCode) {
		_accessCode = accessCode;
	}

	public String getSecureSecret() {
		if (_secureSecret == null) {
			return StringPool.BLANK;
		}
		else {
			return _secureSecret;
		}
	}

	public void setSecureSecret(String secureSecret) {
		_secureSecret = secureSecret;
	}

	public String getMaCapSoBienNhan() {
		if (_maCapSoBienNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _maCapSoBienNhan;
		}
	}

	public void setMaCapSoBienNhan(String maCapSoBienNhan) {
		_maCapSoBienNhan = maCapSoBienNhan;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CoQuanQuanLy toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CoQuanQuanLy)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CoQuanQuanLy.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CoQuanQuanLyImpl coQuanQuanLyImpl = new CoQuanQuanLyImpl();

		coQuanQuanLyImpl.setId(getId());
		coQuanQuanLyImpl.setMa(getMa());
		coQuanQuanLyImpl.setTen(getTen());
		coQuanQuanLyImpl.setDiaChi(getDiaChi());
		coQuanQuanLyImpl.setDienThoai(getDienThoai());
		coQuanQuanLyImpl.setEmail(getEmail());
		coQuanQuanLyImpl.setFax(getFax());
		coQuanQuanLyImpl.setWebsite(getWebsite());
		coQuanQuanLyImpl.setNoiBo(getNoiBo());
		coQuanQuanLyImpl.setPhienBan(getPhienBan());
		coQuanQuanLyImpl.setDaXoa(getDaXoa());
		coQuanQuanLyImpl.setDonViHanhChinhId(getDonViHanhChinhId());
		coQuanQuanLyImpl.setCapCoQuanQuanlyId(getCapCoQuanQuanlyId());
		coQuanQuanLyImpl.setChaId(getChaId());
		coQuanQuanLyImpl.setNguoiTao(getNguoiTao());
		coQuanQuanLyImpl.setNgayTao(getNgayTao());
		coQuanQuanLyImpl.setNguoiSua(getNguoiSua());
		coQuanQuanLyImpl.setNgaySua(getNgaySua());
		coQuanQuanLyImpl.setMerchant(getMerchant());
		coQuanQuanLyImpl.setAccessCode(getAccessCode());
		coQuanQuanLyImpl.setSecureSecret(getSecureSecret());
		coQuanQuanLyImpl.setMaCapSoBienNhan(getMaCapSoBienNhan());

		coQuanQuanLyImpl.resetOriginalValues();

		return coQuanQuanLyImpl;
	}

	public int compareTo(CoQuanQuanLy coQuanQuanLy) {
		int value = 0;

		if (getId() < coQuanQuanLy.getId()) {
			value = -1;
		}
		else if (getId() > coQuanQuanLy.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CoQuanQuanLy coQuanQuanLy = null;

		try {
			coQuanQuanLy = (CoQuanQuanLy)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = coQuanQuanLy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CoQuanQuanLyModelImpl coQuanQuanLyModelImpl = this;

		coQuanQuanLyModelImpl._originalMa = coQuanQuanLyModelImpl._ma;

		coQuanQuanLyModelImpl._originalDaXoa = coQuanQuanLyModelImpl._daXoa;

		coQuanQuanLyModelImpl._setOriginalDaXoa = false;

		coQuanQuanLyModelImpl._originalDonViHanhChinhId = coQuanQuanLyModelImpl._donViHanhChinhId;

		coQuanQuanLyModelImpl._setOriginalDonViHanhChinhId = false;

		coQuanQuanLyModelImpl._originalCapCoQuanQuanlyId = coQuanQuanLyModelImpl._capCoQuanQuanlyId;

		coQuanQuanLyModelImpl._setOriginalCapCoQuanQuanlyId = false;

		coQuanQuanLyModelImpl._originalChaId = coQuanQuanLyModelImpl._chaId;

		coQuanQuanLyModelImpl._setOriginalChaId = false;

		coQuanQuanLyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CoQuanQuanLy> toCacheModel() {
		CoQuanQuanLyCacheModel coQuanQuanLyCacheModel = new CoQuanQuanLyCacheModel();

		coQuanQuanLyCacheModel.id = getId();

		coQuanQuanLyCacheModel.ma = getMa();

		String ma = coQuanQuanLyCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			coQuanQuanLyCacheModel.ma = null;
		}

		coQuanQuanLyCacheModel.ten = getTen();

		String ten = coQuanQuanLyCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			coQuanQuanLyCacheModel.ten = null;
		}

		coQuanQuanLyCacheModel.diaChi = getDiaChi();

		String diaChi = coQuanQuanLyCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			coQuanQuanLyCacheModel.diaChi = null;
		}

		coQuanQuanLyCacheModel.dienThoai = getDienThoai();

		String dienThoai = coQuanQuanLyCacheModel.dienThoai;

		if ((dienThoai != null) && (dienThoai.length() == 0)) {
			coQuanQuanLyCacheModel.dienThoai = null;
		}

		coQuanQuanLyCacheModel.email = getEmail();

		String email = coQuanQuanLyCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			coQuanQuanLyCacheModel.email = null;
		}

		coQuanQuanLyCacheModel.fax = getFax();

		String fax = coQuanQuanLyCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			coQuanQuanLyCacheModel.fax = null;
		}

		coQuanQuanLyCacheModel.website = getWebsite();

		String website = coQuanQuanLyCacheModel.website;

		if ((website != null) && (website.length() == 0)) {
			coQuanQuanLyCacheModel.website = null;
		}

		coQuanQuanLyCacheModel.noiBo = getNoiBo();

		coQuanQuanLyCacheModel.phienBan = getPhienBan();

		coQuanQuanLyCacheModel.daXoa = getDaXoa();

		coQuanQuanLyCacheModel.donViHanhChinhId = getDonViHanhChinhId();

		coQuanQuanLyCacheModel.capCoQuanQuanlyId = getCapCoQuanQuanlyId();

		coQuanQuanLyCacheModel.chaId = getChaId();

		coQuanQuanLyCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = coQuanQuanLyCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			coQuanQuanLyCacheModel.nguoiTao = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			coQuanQuanLyCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			coQuanQuanLyCacheModel.ngayTao = Long.MIN_VALUE;
		}

		coQuanQuanLyCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = coQuanQuanLyCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			coQuanQuanLyCacheModel.nguoiSua = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			coQuanQuanLyCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			coQuanQuanLyCacheModel.ngaySua = Long.MIN_VALUE;
		}

		coQuanQuanLyCacheModel.merchant = getMerchant();

		String merchant = coQuanQuanLyCacheModel.merchant;

		if ((merchant != null) && (merchant.length() == 0)) {
			coQuanQuanLyCacheModel.merchant = null;
		}

		coQuanQuanLyCacheModel.accessCode = getAccessCode();

		String accessCode = coQuanQuanLyCacheModel.accessCode;

		if ((accessCode != null) && (accessCode.length() == 0)) {
			coQuanQuanLyCacheModel.accessCode = null;
		}

		coQuanQuanLyCacheModel.secureSecret = getSecureSecret();

		String secureSecret = coQuanQuanLyCacheModel.secureSecret;

		if ((secureSecret != null) && (secureSecret.length() == 0)) {
			coQuanQuanLyCacheModel.secureSecret = null;
		}

		coQuanQuanLyCacheModel.maCapSoBienNhan = getMaCapSoBienNhan();

		String maCapSoBienNhan = coQuanQuanLyCacheModel.maCapSoBienNhan;

		if ((maCapSoBienNhan != null) && (maCapSoBienNhan.length() == 0)) {
			coQuanQuanLyCacheModel.maCapSoBienNhan = null;
		}

		return coQuanQuanLyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", diaChi=");
		sb.append(getDiaChi());
		sb.append(", dienThoai=");
		sb.append(getDienThoai());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append(", noiBo=");
		sb.append(getNoiBo());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", donViHanhChinhId=");
		sb.append(getDonViHanhChinhId());
		sb.append(", capCoQuanQuanlyId=");
		sb.append(getCapCoQuanQuanlyId());
		sb.append(", chaId=");
		sb.append(getChaId());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", merchant=");
		sb.append(getMerchant());
		sb.append(", accessCode=");
		sb.append(getAccessCode());
		sb.append(", secureSecret=");
		sb.append(getSecureSecret());
		sb.append(", maCapSoBienNhan=");
		sb.append(getMaCapSoBienNhan());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.qlhc.model.CoQuanQuanLy");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoai</column-name><column-value><![CDATA[");
		sb.append(getDienThoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiBo</column-name><column-value><![CDATA[");
		sb.append(getNoiBo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>donViHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getDonViHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>capCoQuanQuanlyId</column-name><column-value><![CDATA[");
		sb.append(getCapCoQuanQuanlyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chaId</column-name><column-value><![CDATA[");
		sb.append(getChaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>merchant</column-name><column-value><![CDATA[");
		sb.append(getMerchant());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accessCode</column-name><column-value><![CDATA[");
		sb.append(getAccessCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secureSecret</column-name><column-value><![CDATA[");
		sb.append(getSecureSecret());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maCapSoBienNhan</column-name><column-value><![CDATA[");
		sb.append(getMaCapSoBienNhan());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CoQuanQuanLy.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CoQuanQuanLy.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private String _diaChi;
	private String _dienThoai;
	private String _email;
	private String _fax;
	private String _website;
	private int _noiBo;
	private long _phienBan;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private Long _donViHanhChinhId;
	private Long _originalDonViHanhChinhId;
	private boolean _setOriginalDonViHanhChinhId;
	private Long _capCoQuanQuanlyId;
	private Long _originalCapCoQuanQuanlyId;
	private boolean _setOriginalCapCoQuanQuanlyId;
	private Long _chaId;
	private Long _originalChaId;
	private boolean _setOriginalChaId;
	private String _nguoiTao;
	private Date _ngayTao;
	private String _nguoiSua;
	private Date _ngaySua;
	private String _merchant;
	private String _accessCode;
	private String _secureSecret;
	private String _maCapSoBienNhan;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private CoQuanQuanLy _escapedModelProxy;
}