
package org.oep.sharedservice.cmon.provider.document.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Tue Jul 16 16:14:21 ICT 2013
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "getTailieuDinhKemBoiId", namespace = "http://document.provider.cmon.sharedservice.dtt.vn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTailieuDinhKemBoiId", namespace = "http://document.provider.cmon.sharedservice.dtt.vn/")

public class GetTailieuDinhKemBoiId {

    @XmlElement(name = "arg0")
    private java.lang.Long arg0;

    public java.lang.Long getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Long newArg0)  {
        this.arg0 = newArg0;
    }

}

