/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.dlms.dao.chitietgplx.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChiTietGPLX service. Represents a row in the &quot;DLMS_CHITIETGPLX&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.dlms.dao.chitietgplx.model.impl.ChiTietGPLXModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.dlms.dao.chitietgplx.model.impl.ChiTietGPLXImpl}.
 * </p>
 *
 * @author hunghq
 * @see ChiTietGPLX
 * @see org.oep.dlms.dao.chitietgplx.model.impl.ChiTietGPLXImpl
 * @see org.oep.dlms.dao.chitietgplx.model.impl.ChiTietGPLXModelImpl
 * @generated
 */
public interface ChiTietGPLXModel extends BaseModel<ChiTietGPLX> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chi tiet g p l x model instance should use the {@link ChiTietGPLX} interface instead.
	 */

	/**
	 * Returns the primary key of this chi tiet g p l x.
	 *
	 * @return the primary key of this chi tiet g p l x
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chi tiet g p l x.
	 *
	 * @param primaryKey the primary key of this chi tiet g p l x
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chi tiet g p l x.
	 *
	 * @return the ID of this chi tiet g p l x
	 */
	public long getId();

	/**
	 * Sets the ID of this chi tiet g p l x.
	 *
	 * @param id the ID of this chi tiet g p l x
	 */
	public void setId(long id);

	/**
	 * Returns the id g p l x of this chi tiet g p l x.
	 *
	 * @return the id g p l x of this chi tiet g p l x
	 */
	public long getIdGPLX();

	/**
	 * Sets the id g p l x of this chi tiet g p l x.
	 *
	 * @param idGPLX the id g p l x of this chi tiet g p l x
	 */
	public void setIdGPLX(long idGPLX);

	/**
	 * Returns the so g p l x of this chi tiet g p l x.
	 *
	 * @return the so g p l x of this chi tiet g p l x
	 */
	@AutoEscape
	public String getSoGPLX();

	/**
	 * Sets the so g p l x of this chi tiet g p l x.
	 *
	 * @param soGPLX the so g p l x of this chi tiet g p l x
	 */
	public void setSoGPLX(String soGPLX);

	/**
	 * Returns the id hang g p l x of this chi tiet g p l x.
	 *
	 * @return the id hang g p l x of this chi tiet g p l x
	 */
	public long getIdHangGPLX();

	/**
	 * Sets the id hang g p l x of this chi tiet g p l x.
	 *
	 * @param idHangGPLX the id hang g p l x of this chi tiet g p l x
	 */
	public void setIdHangGPLX(long idHangGPLX);

	/**
	 * Returns the id noi cap g p l x of this chi tiet g p l x.
	 *
	 * @return the id noi cap g p l x of this chi tiet g p l x
	 */
	public long getIdNoiCapGPLX();

	/**
	 * Sets the id noi cap g p l x of this chi tiet g p l x.
	 *
	 * @param idNoiCapGPLX the id noi cap g p l x of this chi tiet g p l x
	 */
	public void setIdNoiCapGPLX(long idNoiCapGPLX);

	/**
	 * Returns the id noi cap g p l x nuoc ngoai of this chi tiet g p l x.
	 *
	 * @return the id noi cap g p l x nuoc ngoai of this chi tiet g p l x
	 */
	public long getIdNoiCapGPLXNuocNgoai();

	/**
	 * Sets the id noi cap g p l x nuoc ngoai of this chi tiet g p l x.
	 *
	 * @param idNoiCapGPLXNuocNgoai the id noi cap g p l x nuoc ngoai of this chi tiet g p l x
	 */
	public void setIdNoiCapGPLXNuocNgoai(long idNoiCapGPLXNuocNgoai);

	/**
	 * Returns the ngay cap g p l x of this chi tiet g p l x.
	 *
	 * @return the ngay cap g p l x of this chi tiet g p l x
	 */
	public Date getNgayCapGPLX();

	/**
	 * Sets the ngay cap g p l x of this chi tiet g p l x.
	 *
	 * @param ngayCapGPLX the ngay cap g p l x of this chi tiet g p l x
	 */
	public void setNgayCapGPLX(Date ngayCapGPLX);

	/**
	 * Returns the ngay trung tuyen of this chi tiet g p l x.
	 *
	 * @return the ngay trung tuyen of this chi tiet g p l x
	 */
	public Date getNgayTrungTuyen();

	/**
	 * Sets the ngay trung tuyen of this chi tiet g p l x.
	 *
	 * @param ngayTrungTuyen the ngay trung tuyen of this chi tiet g p l x
	 */
	public void setNgayTrungTuyen(Date ngayTrungTuyen);

	/**
	 * Returns the ngay het han of this chi tiet g p l x.
	 *
	 * @return the ngay het han of this chi tiet g p l x
	 */
	public Date getNgayHetHan();

	/**
	 * Sets the ngay het han of this chi tiet g p l x.
	 *
	 * @param ngayHetHan the ngay het han of this chi tiet g p l x
	 */
	public void setNgayHetHan(Date ngayHetHan);

	/**
	 * Returns the id noi hoc lai xe of this chi tiet g p l x.
	 *
	 * @return the id noi hoc lai xe of this chi tiet g p l x
	 */
	public long getIdNoiHocLaiXe();

	/**
	 * Sets the id noi hoc lai xe of this chi tiet g p l x.
	 *
	 * @param idNoiHocLaiXe the id noi hoc lai xe of this chi tiet g p l x
	 */
	public void setIdNoiHocLaiXe(long idNoiHocLaiXe);

	/**
	 * Returns the id noi hoc lai xe nuoc ngoai of this chi tiet g p l x.
	 *
	 * @return the id noi hoc lai xe nuoc ngoai of this chi tiet g p l x
	 */
	public long getIdNoiHocLaiXeNuocNgoai();

	/**
	 * Sets the id noi hoc lai xe nuoc ngoai of this chi tiet g p l x.
	 *
	 * @param idNoiHocLaiXeNuocNgoai the id noi hoc lai xe nuoc ngoai of this chi tiet g p l x
	 */
	public void setIdNoiHocLaiXeNuocNgoai(long idNoiHocLaiXeNuocNgoai);

	/**
	 * Returns the nam hoc lai xe of this chi tiet g p l x.
	 *
	 * @return the nam hoc lai xe of this chi tiet g p l x
	 */
	public long getNamHocLaiXe();

	/**
	 * Sets the nam hoc lai xe of this chi tiet g p l x.
	 *
	 * @param namHocLaiXe the nam hoc lai xe of this chi tiet g p l x
	 */
	public void setNamHocLaiXe(long namHocLaiXe);

	/**
	 * Returns the noi hoc lai xe nuoc ngoai of this chi tiet g p l x.
	 *
	 * @return the noi hoc lai xe nuoc ngoai of this chi tiet g p l x
	 */
	@AutoEscape
	public String getNoiHocLaiXeNuocNgoai();

	/**
	 * Sets the noi hoc lai xe nuoc ngoai of this chi tiet g p l x.
	 *
	 * @param noiHocLaiXeNuocNgoai the noi hoc lai xe nuoc ngoai of this chi tiet g p l x
	 */
	public void setNoiHocLaiXeNuocNgoai(String noiHocLaiXeNuocNgoai);

	/**
	 * Returns the noi hoc lai xe of this chi tiet g p l x.
	 *
	 * @return the noi hoc lai xe of this chi tiet g p l x
	 */
	@AutoEscape
	public String getNoiHocLaiXe();

	/**
	 * Sets the noi hoc lai xe of this chi tiet g p l x.
	 *
	 * @param noiHocLaiXe the noi hoc lai xe of this chi tiet g p l x
	 */
	public void setNoiHocLaiXe(String noiHocLaiXe);

	/**
	 * Returns the noi cap g p l x nuoc ngoai of this chi tiet g p l x.
	 *
	 * @return the noi cap g p l x nuoc ngoai of this chi tiet g p l x
	 */
	@AutoEscape
	public String getNoiCapGPLXNuocNgoai();

	/**
	 * Sets the noi cap g p l x nuoc ngoai of this chi tiet g p l x.
	 *
	 * @param noiCapGPLXNuocNgoai the noi cap g p l x nuoc ngoai of this chi tiet g p l x
	 */
	public void setNoiCapGPLXNuocNgoai(String noiCapGPLXNuocNgoai);

	/**
	 * Returns the noi cap g p l x of this chi tiet g p l x.
	 *
	 * @return the noi cap g p l x of this chi tiet g p l x
	 */
	@AutoEscape
	public String getNoiCapGPLX();

	/**
	 * Sets the noi cap g p l x of this chi tiet g p l x.
	 *
	 * @param noiCapGPLX the noi cap g p l x of this chi tiet g p l x
	 */
	public void setNoiCapGPLX(String noiCapGPLX);

	/**
	 * Returns the ngay tao of this chi tiet g p l x.
	 *
	 * @return the ngay tao of this chi tiet g p l x
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this chi tiet g p l x.
	 *
	 * @param ngayTao the ngay tao of this chi tiet g p l x
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this chi tiet g p l x.
	 *
	 * @return the ngay sua of this chi tiet g p l x
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this chi tiet g p l x.
	 *
	 * @param ngaySua the ngay sua of this chi tiet g p l x
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi tao of this chi tiet g p l x.
	 *
	 * @return the nguoi tao of this chi tiet g p l x
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this chi tiet g p l x.
	 *
	 * @param nguoiTao the nguoi tao of this chi tiet g p l x
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this chi tiet g p l x.
	 *
	 * @return the nguoi sua of this chi tiet g p l x
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this chi tiet g p l x.
	 *
	 * @param nguoiSua the nguoi sua of this chi tiet g p l x
	 */
	public void setNguoiSua(String nguoiSua);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ChiTietGPLX chiTietGPLX);

	public int hashCode();

	public CacheModel<ChiTietGPLX> toCacheModel();

	public ChiTietGPLX toEscapedModel();

	public String toString();

	public String toXmlString();
}