
package org.oep.sharedservice.cmon.provider.officer.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Wed Jul 17 10:41:56 ICT 2013
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "upload", namespace = "http://officer.provider.cmon.sharedservice.dtt.vn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "upload", namespace = "http://officer.provider.cmon.sharedservice.dtt.vn/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4", "arg5", "arg6", "arg7"})

public class Upload {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private int arg1;
    @XmlElement(name = "arg2")
    private java.lang.Long arg2;
    @XmlElement(name = "arg3")
    private java.lang.Long arg3;
    @XmlElement(name = "arg4")
    private java.lang.String arg4;
    @XmlElement(name = "arg5")
    private java.lang.String arg5;
    @XmlElement(name = "arg6")
    private byte[] arg6;
    @XmlElement(name = "arg7")
    private java.lang.String arg7;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.Long getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.Long newArg2)  {
        this.arg2 = newArg2;
    }

    public java.lang.Long getArg3() {
        return this.arg3;
    }

    public void setArg3(java.lang.Long newArg3)  {
        this.arg3 = newArg3;
    }

    public java.lang.String getArg4() {
        return this.arg4;
    }

    public void setArg4(java.lang.String newArg4)  {
        this.arg4 = newArg4;
    }

    public java.lang.String getArg5() {
        return this.arg5;
    }

    public void setArg5(java.lang.String newArg5)  {
        this.arg5 = newArg5;
    }

    public byte[] getArg6() {
        return this.arg6;
    }

    public void setArg6(byte[] newArg6)  {
        this.arg6 = newArg6;
    }

    public java.lang.String getArg7() {
        return this.arg7;
    }

    public void setArg7(java.lang.String newArg7)  {
        this.arg7 = newArg7;
    }

}

