/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.job.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.oep.cmon.dao.job.model.LogMail;
import org.oep.cmon.dao.job.service.LogMailLocalServiceUtil;

/**
 * The extended model base implementation for the LogMail service. Represents a row in the &quot;JOB_LOGMAIL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LogMailImpl}.
 * </p>
 *
 * @author BinhNT
 * @see LogMailImpl
 * @see org.oep.cmon.dao.job.model.LogMail
 * @generated
 */
public abstract class LogMailBaseImpl extends LogMailModelImpl
	implements LogMail {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a log mail model instance should use the {@link LogMail} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			LogMailLocalServiceUtil.addLogMail(this);
		}
		else {
			LogMailLocalServiceUtil.updateLogMail(this);
		}
	}
}