/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.cc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc;
import org.oep.cmon.dao.cc.model.CongChuc2NhomThuTucModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the CongChuc2NhomThuTuc service. Represents a row in the &quot;CMON_CONGCHUC2NHOMTHUTUC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.cc.model.CongChuc2NhomThuTucModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CongChuc2NhomThuTucImpl}.
 * </p>
 *
 * @author Liemnn
 * @see CongChuc2NhomThuTucImpl
 * @see org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc
 * @see org.oep.cmon.dao.cc.model.CongChuc2NhomThuTucModel
 * @generated
 */
public class CongChuc2NhomThuTucModelImpl extends BaseModelImpl<CongChuc2NhomThuTuc>
	implements CongChuc2NhomThuTucModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cong chuc2 nhom thu tuc model instance should use the {@link org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_CONGCHUC2NHOMTHUTUC";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "CONGCHUCID", Types.BIGINT },
			{ "NHOMTHUTUCID", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOISUA", Types.VARCHAR },
			{ "DAXOA", Types.INTEGER },
			{ "DUOCPHEPEDITCONGDAN", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_CONGCHUC2NHOMTHUTUC (ID LONG not null primary key,CONGCHUCID LONG,NHOMTHUTUCID LONG,NGAYTAO DATE null,NGUOITAO VARCHAR(75) null,NGAYSUA DATE null,NGUOISUA VARCHAR(75) null,DAXOA INTEGER,DUOCPHEPEDITCONGDAN INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CMON_CONGCHUC2NHOMTHUTUC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc"),
			true);
	public static long CONGCHUCID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static long NHOMTHUTUCID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc"));

	public CongChuc2NhomThuTucModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CongChuc2NhomThuTuc.class;
	}

	public String getModelClassName() {
		return CongChuc2NhomThuTuc.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask |= ID_COLUMN_BITMASK;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	public long getCongChucId() {
		return _congChucId;
	}

	public void setCongChucId(long congChucId) {
		_columnBitmask |= CONGCHUCID_COLUMN_BITMASK;

		if (!_setOriginalCongChucId) {
			_setOriginalCongChucId = true;

			_originalCongChucId = _congChucId;
		}

		_congChucId = congChucId;
	}

	public long getOriginalCongChucId() {
		return _originalCongChucId;
	}

	public long getNhomThuTucId() {
		return _nhomThuTucId;
	}

	public void setNhomThuTucId(long nhomThuTucId) {
		_columnBitmask |= NHOMTHUTUCID_COLUMN_BITMASK;

		if (!_setOriginalNhomThuTucId) {
			_setOriginalNhomThuTucId = true;

			_originalNhomThuTucId = _nhomThuTucId;
		}

		_nhomThuTucId = nhomThuTucId;
	}

	public long getOriginalNhomThuTucId() {
		return _originalNhomThuTucId;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_daXoa = daXoa;
	}

	public int getDuocPhepEditCongDan() {
		return _duocPhepEditCongDan;
	}

	public void setDuocPhepEditCongDan(int duocPhepEditCongDan) {
		_duocPhepEditCongDan = duocPhepEditCongDan;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CongChuc2NhomThuTuc toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CongChuc2NhomThuTuc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CongChuc2NhomThuTuc.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CongChuc2NhomThuTucImpl congChuc2NhomThuTucImpl = new CongChuc2NhomThuTucImpl();

		congChuc2NhomThuTucImpl.setId(getId());
		congChuc2NhomThuTucImpl.setCongChucId(getCongChucId());
		congChuc2NhomThuTucImpl.setNhomThuTucId(getNhomThuTucId());
		congChuc2NhomThuTucImpl.setNgayTao(getNgayTao());
		congChuc2NhomThuTucImpl.setNguoiTao(getNguoiTao());
		congChuc2NhomThuTucImpl.setNgaySua(getNgaySua());
		congChuc2NhomThuTucImpl.setNguoiSua(getNguoiSua());
		congChuc2NhomThuTucImpl.setDaXoa(getDaXoa());
		congChuc2NhomThuTucImpl.setDuocPhepEditCongDan(getDuocPhepEditCongDan());

		congChuc2NhomThuTucImpl.resetOriginalValues();

		return congChuc2NhomThuTucImpl;
	}

	public int compareTo(CongChuc2NhomThuTuc congChuc2NhomThuTuc) {
		long primaryKey = congChuc2NhomThuTuc.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CongChuc2NhomThuTuc congChuc2NhomThuTuc = null;

		try {
			congChuc2NhomThuTuc = (CongChuc2NhomThuTuc)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = congChuc2NhomThuTuc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CongChuc2NhomThuTucModelImpl congChuc2NhomThuTucModelImpl = this;

		congChuc2NhomThuTucModelImpl._originalId = congChuc2NhomThuTucModelImpl._id;

		congChuc2NhomThuTucModelImpl._setOriginalId = false;

		congChuc2NhomThuTucModelImpl._originalCongChucId = congChuc2NhomThuTucModelImpl._congChucId;

		congChuc2NhomThuTucModelImpl._setOriginalCongChucId = false;

		congChuc2NhomThuTucModelImpl._originalNhomThuTucId = congChuc2NhomThuTucModelImpl._nhomThuTucId;

		congChuc2NhomThuTucModelImpl._setOriginalNhomThuTucId = false;

		congChuc2NhomThuTucModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CongChuc2NhomThuTuc> toCacheModel() {
		CongChuc2NhomThuTucCacheModel congChuc2NhomThuTucCacheModel = new CongChuc2NhomThuTucCacheModel();

		congChuc2NhomThuTucCacheModel.id = getId();

		congChuc2NhomThuTucCacheModel.congChucId = getCongChucId();

		congChuc2NhomThuTucCacheModel.nhomThuTucId = getNhomThuTucId();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			congChuc2NhomThuTucCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			congChuc2NhomThuTucCacheModel.ngayTao = Long.MIN_VALUE;
		}

		congChuc2NhomThuTucCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = congChuc2NhomThuTucCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			congChuc2NhomThuTucCacheModel.nguoiTao = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			congChuc2NhomThuTucCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			congChuc2NhomThuTucCacheModel.ngaySua = Long.MIN_VALUE;
		}

		congChuc2NhomThuTucCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = congChuc2NhomThuTucCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			congChuc2NhomThuTucCacheModel.nguoiSua = null;
		}

		congChuc2NhomThuTucCacheModel.daXoa = getDaXoa();

		congChuc2NhomThuTucCacheModel.duocPhepEditCongDan = getDuocPhepEditCongDan();

		return congChuc2NhomThuTucCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", congChucId=");
		sb.append(getCongChucId());
		sb.append(", nhomThuTucId=");
		sb.append(getNhomThuTucId());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", duocPhepEditCongDan=");
		sb.append(getDuocPhepEditCongDan());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.cc.model.CongChuc2NhomThuTuc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>congChucId</column-name><column-value><![CDATA[");
		sb.append(getCongChucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhomThuTucId</column-name><column-value><![CDATA[");
		sb.append(getNhomThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duocPhepEditCongDan</column-name><column-value><![CDATA[");
		sb.append(getDuocPhepEditCongDan());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CongChuc2NhomThuTuc.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CongChuc2NhomThuTuc.class
		};
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private long _congChucId;
	private long _originalCongChucId;
	private boolean _setOriginalCongChucId;
	private long _nhomThuTucId;
	private long _originalNhomThuTucId;
	private boolean _setOriginalNhomThuTucId;
	private Date _ngayTao;
	private String _nguoiTao;
	private Date _ngaySua;
	private String _nguoiSua;
	private int _daXoa;
	private int _duocPhepEditCongDan;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private CongChuc2NhomThuTuc _escapedModelProxy;
}