/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.dlms.dao.danhmucgiaypheplaixe.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;


import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

import org.oep.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXe;
import org.oep.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXeModel;

/**
 * The base model implementation for the HangGiayPhepLaiXe service. Represents a row in the &quot;DLMS_HANGGPLX&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HangGiayPhepLaiXeImpl}.
 * </p>
 *
 * @author AnhNT
 * @see HangGiayPhepLaiXeImpl
 * @see org.oep.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXe
 * @see org.oep.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXeModel
 * @generated
 */
public class HangGiayPhepLaiXeModelImpl extends BaseModelImpl<HangGiayPhepLaiXe>
	implements HangGiayPhepLaiXeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hang giay phep lai xe model instance should use the {@link vn.dtt.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXe} interface instead.
	 */
	public static final String TABLE_NAME = "DLMS_HANGGPLX";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TEN", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "DAXOA", Types.INTEGER },
			{ "MA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DLMS_HANGGPLX (ID LONG not null primary key,TEN VARCHAR(75) null,NGAYTAO DATE null,NGAYSUA DATE null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,DAXOA INTEGER,MA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DLMS_HANGGPLX";
	public static final String ORDER_BY_JPQL = " ORDER BY hangGiayPhepLaiXe.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DLMS_HANGGPLX.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXe"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXe"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXe"));

	public HangGiayPhepLaiXeModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return HangGiayPhepLaiXe.class;
	}

	public String getModelClassName() {
		return HangGiayPhepLaiXe.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getTenHang() {
		if (_tenHang == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenHang;
		}
	}

	public void setTenHang(String tenHang) {
		_tenHang = tenHang;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getXoa() {
		return _xoa;
	}

	public void setXoa(int xoa) {
		_xoa = xoa;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_ma = ma;
	}

	@Override
	public HangGiayPhepLaiXe toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (HangGiayPhepLaiXe)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					HangGiayPhepLaiXe.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		HangGiayPhepLaiXeImpl hangGiayPhepLaiXeImpl = new HangGiayPhepLaiXeImpl();

		hangGiayPhepLaiXeImpl.setId(getId());
		hangGiayPhepLaiXeImpl.setTenHang(getTenHang());
		hangGiayPhepLaiXeImpl.setNgayTao(getNgayTao());
		hangGiayPhepLaiXeImpl.setNgaySua(getNgaySua());
		hangGiayPhepLaiXeImpl.setNguoiTao(getNguoiTao());
		hangGiayPhepLaiXeImpl.setNguoiSua(getNguoiSua());
		hangGiayPhepLaiXeImpl.setXoa(getXoa());
		hangGiayPhepLaiXeImpl.setMa(getMa());

		hangGiayPhepLaiXeImpl.resetOriginalValues();

		return hangGiayPhepLaiXeImpl;
	}

	public int compareTo(HangGiayPhepLaiXe hangGiayPhepLaiXe) {
		int value = 0;

		if (getId() < hangGiayPhepLaiXe.getId()) {
			value = -1;
		}
		else if (getId() > hangGiayPhepLaiXe.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		HangGiayPhepLaiXe hangGiayPhepLaiXe = null;

		try {
			hangGiayPhepLaiXe = (HangGiayPhepLaiXe)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = hangGiayPhepLaiXe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<HangGiayPhepLaiXe> toCacheModel() {
		HangGiayPhepLaiXeCacheModel hangGiayPhepLaiXeCacheModel = new HangGiayPhepLaiXeCacheModel();

		hangGiayPhepLaiXeCacheModel.id = getId();

		hangGiayPhepLaiXeCacheModel.tenHang = getTenHang();

		String tenHang = hangGiayPhepLaiXeCacheModel.tenHang;

		if ((tenHang != null) && (tenHang.length() == 0)) {
			hangGiayPhepLaiXeCacheModel.tenHang = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			hangGiayPhepLaiXeCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			hangGiayPhepLaiXeCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			hangGiayPhepLaiXeCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			hangGiayPhepLaiXeCacheModel.ngaySua = Long.MIN_VALUE;
		}

		hangGiayPhepLaiXeCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = hangGiayPhepLaiXeCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			hangGiayPhepLaiXeCacheModel.nguoiTao = null;
		}

		hangGiayPhepLaiXeCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = hangGiayPhepLaiXeCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			hangGiayPhepLaiXeCacheModel.nguoiSua = null;
		}

		hangGiayPhepLaiXeCacheModel.xoa = getXoa();

		hangGiayPhepLaiXeCacheModel.ma = getMa();

		String ma = hangGiayPhepLaiXeCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			hangGiayPhepLaiXeCacheModel.ma = null;
		}

		return hangGiayPhepLaiXeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", tenHang=");
		sb.append(getTenHang());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", xoa=");
		sb.append(getXoa());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append(
			"vn.dtt.dlms.dao.danhmucgiaypheplaixe.model.HangGiayPhepLaiXe");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenHang</column-name><column-value><![CDATA[");
		sb.append(getTenHang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xoa</column-name><column-value><![CDATA[");
		sb.append(getXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = HangGiayPhepLaiXe.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			HangGiayPhepLaiXe.class
		};
	private long _id;
	private String _tenHang;
	private Date _ngayTao;
	private Date _ngaySua;
	private String _nguoiTao;
	private String _nguoiSua;
	private int _xoa;
	private String _ma;
	private transient ExpandoBridge _expandoBridge;
	private HangGiayPhepLaiXe _escapedModelProxy;
}