/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.cd.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.cd.model.CongDan;
import org.oep.cmon.dao.cd.model.CongDanModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the CongDan service. Represents a row in the &quot;CSMS_CONGDAN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.cd.model.CongDanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CongDanImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see CongDanImpl
 * @see org.oep.cmon.dao.cd.model.CongDan
 * @see org.oep.cmon.dao.cd.model.CongDanModel
 * @generated
 */
public class CongDanModelImpl extends BaseModelImpl<CongDan>
	implements CongDanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cong dan model instance should use the {@link org.oep.cmon.dao.cd.model.CongDan} interface instead.
	 */
	public static final String TABLE_NAME = "CSMS_CONGDAN";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "HO", Types.VARCHAR },
			{ "DEM", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "NGAYSINH", Types.TIMESTAMP },
			{ "SOCMND", Types.VARCHAR },
			{ "NGAYCAPCMND", Types.TIMESTAMP },
			{ "GHICHUCMND", Types.VARCHAR },
			{ "SOHOCHIEU", Types.VARCHAR },
			{ "NGAYCAPHOCHIEU", Types.TIMESTAMP },
			{ "NGAYHETHANHOCHIEU", Types.TIMESTAMP },
			{ "NOICAPHOCHIEUID", Types.BIGINT },
			{ "GHICHUHOCHIEU", Types.VARCHAR },
			{ "SOBAOHIEMYTE", Types.VARCHAR },
			{ "MASOTHUECANHAN", Types.VARCHAR },
			{ "DIACHITHUONGTRU", Types.VARCHAR },
			{ "DIACHIHIENNAY", Types.VARCHAR },
			{ "DIENTHOAICODINH", Types.VARCHAR },
			{ "DIENTHOAIDIDONG", Types.VARCHAR },
			{ "HOTENCHA", Types.VARCHAR },
			{ "HOTENME", Types.VARCHAR },
			{ "HOTENVOHOACCHONG", Types.VARCHAR },
			{ "SOHOKHAU", Types.VARCHAR },
			{ "LACHUHO", Types.INTEGER },
			{ "TINHTRANGHONNHANID", Types.BIGINT },
			{ "EMAIL", Types.VARCHAR },
			{ "TRINHDOCHUYENMONID", Types.BIGINT },
			{ "SODINHDANHCHAID", Types.BIGINT },
			{ "SODINHDANHVOHOACCHONGID", Types.BIGINT },
			{ "DANTOCID", Types.BIGINT },
			{ "DIACHIHIENNAYHUYENID", Types.BIGINT },
			{ "DIACHIHIENNAYTINHID", Types.BIGINT },
			{ "DIACHIHIENNAYXAID", Types.BIGINT },
			{ "DIACHITHUONGTRUHUYENID", Types.BIGINT },
			{ "DIACHITHUONGTRUTINHID", Types.BIGINT },
			{ "DIACHITHUONGTRUXAID", Types.BIGINT },
			{ "GIOITINHID", Types.INTEGER },
			{ "NGHENGHIEPID", Types.BIGINT },
			{ "NOISINHHUYENID", Types.BIGINT },
			{ "NOISINHTINHID", Types.BIGINT },
			{ "NOISINHXAID", Types.BIGINT },
			{ "NOISINHCHITIET", Types.VARCHAR },
			{ "NOICAPCMNDID", Types.BIGINT },
			{ "TONGIAOID", Types.BIGINT },
			{ "SODINHDANHMEID", Types.BIGINT },
			{ "TRINHDOHOCVANID", Types.BIGINT },
			{ "TAIKHOANNGUOIDUNGID", Types.BIGINT },
			{ "QUANHECHUHOID", Types.BIGINT },
			{ "QUOCTICHID", Types.BIGINT },
			{ "DOANHNGHIEPID", Types.BIGINT },
			{ "TENDAYDU", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "DAXOA", Types.INTEGER },
			{ "FAX", Types.VARCHAR },
			{ "WEBSITE", Types.VARCHAR },
			{ "TINHTRANG", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table CSMS_CONGDAN (ID LONG not null primary key,MA VARCHAR(75) null,HO VARCHAR(75) null,DEM VARCHAR(75) null,TEN VARCHAR(75) null,NGAYSINH DATE null,SOCMND VARCHAR(75) null,NGAYCAPCMND DATE null,GHICHUCMND VARCHAR(75) null,SOHOCHIEU VARCHAR(75) null,NGAYCAPHOCHIEU DATE null,NGAYHETHANHOCHIEU DATE null,NOICAPHOCHIEUID LONG null,GHICHUHOCHIEU VARCHAR(75) null,SOBAOHIEMYTE VARCHAR(75) null,MASOTHUECANHAN VARCHAR(75) null,DIACHITHUONGTRU VARCHAR(75) null,DIACHIHIENNAY VARCHAR(75) null,DIENTHOAICODINH VARCHAR(75) null,DIENTHOAIDIDONG VARCHAR(75) null,HOTENCHA VARCHAR(75) null,HOTENME VARCHAR(75) null,HOTENVOHOACCHONG VARCHAR(75) null,SOHOKHAU VARCHAR(75) null,LACHUHO INTEGER,TINHTRANGHONNHANID LONG null,EMAIL VARCHAR(75) null,TRINHDOCHUYENMONID LONG null,SODINHDANHCHAID LONG null,SODINHDANHVOHOACCHONGID LONG null,DANTOCID LONG null,DIACHIHIENNAYHUYENID LONG null,DIACHIHIENNAYTINHID LONG null,DIACHIHIENNAYXAID LONG null,DIACHITHUONGTRUHUYENID LONG null,DIACHITHUONGTRUTINHID LONG null,DIACHITHUONGTRUXAID LONG null,GIOITINHID INTEGER,NGHENGHIEPID LONG null,NOISINHHUYENID LONG null,NOISINHTINHID LONG null,NOISINHXAID LONG null,NOISINHCHITIET VARCHAR(75) null,NOICAPCMNDID LONG null,TONGIAOID LONG null,SODINHDANHMEID LONG null,TRINHDOHOCVANID LONG null,TAIKHOANNGUOIDUNGID LONG null,QUANHECHUHOID LONG null,QUOCTICHID LONG null,DOANHNGHIEPID LONG null,TENDAYDU VARCHAR(75) null,NGAYTAO DATE null,NGAYSUA DATE null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,DAXOA INTEGER,FAX VARCHAR(75) null,WEBSITE VARCHAR(75) null,TINHTRANG INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table CSMS_CONGDAN";
	public static final String ORDER_BY_JPQL = " ORDER BY congDan.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CSMS_CONGDAN.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.cd.model.CongDan"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.cd.model.CongDan"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.cd.model.CongDan"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static long EMAIL_COLUMN_BITMASK = 2L;
	public static long MA_COLUMN_BITMASK = 4L;
	public static long NGAYSINH_COLUMN_BITMASK = 8L;
	public static long SOCMND_COLUMN_BITMASK = 16L;
	public static long TEN_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.cd.model.CongDan"));

	public CongDanModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CongDan.class;
	}

	public String getModelClassName() {
		return CongDan.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	public String getHo() {
		if (_ho == null) {
			return StringPool.BLANK;
		}
		else {
			return _ho;
		}
	}

	public void setHo(String ho) {
		_ho = ho;
	}

	public String getDem() {
		if (_dem == null) {
			return StringPool.BLANK;
		}
		else {
			return _dem;
		}
	}

	public void setDem(String dem) {
		_dem = dem;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	public Date getNgaySinh() {
		return _ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		_columnBitmask |= NGAYSINH_COLUMN_BITMASK;

		if (_originalNgaySinh == null) {
			_originalNgaySinh = _ngaySinh;
		}

		_ngaySinh = ngaySinh;
	}

	public Date getOriginalNgaySinh() {
		return _originalNgaySinh;
	}

	public String getSoCmnd() {
		if (_soCmnd == null) {
			return StringPool.BLANK;
		}
		else {
			return _soCmnd;
		}
	}

	public void setSoCmnd(String soCmnd) {
		_columnBitmask |= SOCMND_COLUMN_BITMASK;

		if (_originalSoCmnd == null) {
			_originalSoCmnd = _soCmnd;
		}

		_soCmnd = soCmnd;
	}

	public String getOriginalSoCmnd() {
		return GetterUtil.getString(_originalSoCmnd);
	}

	public Date getNgayCapCmnd() {
		return _ngayCapCmnd;
	}

	public void setNgayCapCmnd(Date ngayCapCmnd) {
		_ngayCapCmnd = ngayCapCmnd;
	}

	public String getGhiChuCmnd() {
		if (_ghiChuCmnd == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChuCmnd;
		}
	}

	public void setGhiChuCmnd(String ghiChuCmnd) {
		_ghiChuCmnd = ghiChuCmnd;
	}

	public String getSoHoChieu() {
		if (_soHoChieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _soHoChieu;
		}
	}

	public void setSoHoChieu(String soHoChieu) {
		_soHoChieu = soHoChieu;
	}

	public Date getNgayCapHoChieu() {
		return _ngayCapHoChieu;
	}

	public void setNgayCapHoChieu(Date ngayCapHoChieu) {
		_ngayCapHoChieu = ngayCapHoChieu;
	}

	public Date getNgayHetHanHoChieu() {
		return _ngayHetHanHoChieu;
	}

	public void setNgayHetHanHoChieu(Date ngayHetHanHoChieu) {
		_ngayHetHanHoChieu = ngayHetHanHoChieu;
	}

	public Long getNoiCapHoChieuId() {
		return _noiCapHoChieuId;
	}

	public void setNoiCapHoChieuId(Long noiCapHoChieuId) {
		_noiCapHoChieuId = noiCapHoChieuId;
	}

	public String getGhiChuHoChieu() {
		if (_ghiChuHoChieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChuHoChieu;
		}
	}

	public void setGhiChuHoChieu(String ghiChuHoChieu) {
		_ghiChuHoChieu = ghiChuHoChieu;
	}

	public String getSoBaoHiemYTe() {
		if (_soBaoHiemYTe == null) {
			return StringPool.BLANK;
		}
		else {
			return _soBaoHiemYTe;
		}
	}

	public void setSoBaoHiemYTe(String soBaoHiemYTe) {
		_soBaoHiemYTe = soBaoHiemYTe;
	}

	public String getMaSoThueCaNhan() {
		if (_maSoThueCaNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoThueCaNhan;
		}
	}

	public void setMaSoThueCaNhan(String maSoThueCaNhan) {
		_maSoThueCaNhan = maSoThueCaNhan;
	}

	public String getDiaChiThuongTru() {
		if (_diaChiThuongTru == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiThuongTru;
		}
	}

	public void setDiaChiThuongTru(String diaChiThuongTru) {
		_diaChiThuongTru = diaChiThuongTru;
	}

	public String getDiaChiHienNay() {
		if (_diaChiHienNay == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiHienNay;
		}
	}

	public void setDiaChiHienNay(String diaChiHienNay) {
		_diaChiHienNay = diaChiHienNay;
	}

	public String getDienThoaiCoDinh() {
		if (_dienThoaiCoDinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoaiCoDinh;
		}
	}

	public void setDienThoaiCoDinh(String dienThoaiCoDinh) {
		_dienThoaiCoDinh = dienThoaiCoDinh;
	}

	public String getDienThoaiDiDong() {
		if (_dienThoaiDiDong == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoaiDiDong;
		}
	}

	public void setDienThoaiDiDong(String dienThoaiDiDong) {
		_dienThoaiDiDong = dienThoaiDiDong;
	}

	public String getHoTenCha() {
		if (_hoTenCha == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoTenCha;
		}
	}

	public void setHoTenCha(String hoTenCha) {
		_hoTenCha = hoTenCha;
	}

	public String getHoTenMe() {
		if (_hoTenMe == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoTenMe;
		}
	}

	public void setHoTenMe(String hoTenMe) {
		_hoTenMe = hoTenMe;
	}

	public String getHoTenVoHoacChong() {
		if (_hoTenVoHoacChong == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoTenVoHoacChong;
		}
	}

	public void setHoTenVoHoacChong(String hoTenVoHoacChong) {
		_hoTenVoHoacChong = hoTenVoHoacChong;
	}

	public String getSoHoKhau() {
		if (_soHoKhau == null) {
			return StringPool.BLANK;
		}
		else {
			return _soHoKhau;
		}
	}

	public void setSoHoKhau(String soHoKhau) {
		_soHoKhau = soHoKhau;
	}

	public int getLaChuHo() {
		return _laChuHo;
	}

	public void setLaChuHo(int laChuHo) {
		_laChuHo = laChuHo;
	}

	public Long getTinhTrangHonNhanId() {
		return _tinhTrangHonNhanId;
	}

	public void setTinhTrangHonNhanId(Long tinhTrangHonNhanId) {
		_tinhTrangHonNhanId = tinhTrangHonNhanId;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_columnBitmask |= EMAIL_COLUMN_BITMASK;

		if (_originalEmail == null) {
			_originalEmail = _email;
		}

		_email = email;
	}

	public String getOriginalEmail() {
		return GetterUtil.getString(_originalEmail);
	}

	public Long getTrinhDoChuyenMonId() {
		return _trinhDoChuyenMonId;
	}

	public void setTrinhDoChuyenMonId(Long trinhDoChuyenMonId) {
		_trinhDoChuyenMonId = trinhDoChuyenMonId;
	}

	public Long getSoDinhDanhChaId() {
		return _soDinhDanhChaId;
	}

	public void setSoDinhDanhChaId(Long soDinhDanhChaId) {
		_soDinhDanhChaId = soDinhDanhChaId;
	}

	public Long getSoDinhDanhVoHoacChongId() {
		return _soDinhDanhVoHoacChongId;
	}

	public void setSoDinhDanhVoHoacChongId(Long soDinhDanhVoHoacChongId) {
		_soDinhDanhVoHoacChongId = soDinhDanhVoHoacChongId;
	}

	public Long getDanTocId() {
		return _danTocId;
	}

	public void setDanTocId(Long danTocId) {
		_danTocId = danTocId;
	}

	public Long getDiaChiHienNayHuyenId() {
		return _diaChiHienNayHuyenId;
	}

	public void setDiaChiHienNayHuyenId(Long diaChiHienNayHuyenId) {
		_diaChiHienNayHuyenId = diaChiHienNayHuyenId;
	}

	public Long getDiaChiHienNayTinhId() {
		return _diaChiHienNayTinhId;
	}

	public void setDiaChiHienNayTinhId(Long diaChiHienNayTinhId) {
		_diaChiHienNayTinhId = diaChiHienNayTinhId;
	}

	public Long getDiaChiHienNayXaId() {
		return _diaChiHienNayXaId;
	}

	public void setDiaChiHienNayXaId(Long diaChiHienNayXaId) {
		_diaChiHienNayXaId = diaChiHienNayXaId;
	}

	public Long getDiaChiThuongTruHuyenId() {
		return _diaChiThuongTruHuyenId;
	}

	public void setDiaChiThuongTruHuyenId(Long diaChiThuongTruHuyenId) {
		_diaChiThuongTruHuyenId = diaChiThuongTruHuyenId;
	}

	public Long getDiaChiThuongTruTinhId() {
		return _diaChiThuongTruTinhId;
	}

	public void setDiaChiThuongTruTinhId(Long diaChiThuongTruTinhId) {
		_diaChiThuongTruTinhId = diaChiThuongTruTinhId;
	}

	public Long getDiaChiThuongTruXaId() {
		return _diaChiThuongTruXaId;
	}

	public void setDiaChiThuongTruXaId(Long diaChiThuongTruXaId) {
		_diaChiThuongTruXaId = diaChiThuongTruXaId;
	}

	public int getGioiTinh() {
		return _gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		_gioiTinh = gioiTinh;
	}

	public Long getNgheNghiepId() {
		return _ngheNghiepId;
	}

	public void setNgheNghiepId(Long ngheNghiepId) {
		_ngheNghiepId = ngheNghiepId;
	}

	public Long getNoiSinhHuyenId() {
		return _noiSinhHuyenId;
	}

	public void setNoiSinhHuyenId(Long noiSinhHuyenId) {
		_noiSinhHuyenId = noiSinhHuyenId;
	}

	public Long getNoiSinhTinhId() {
		return _noiSinhTinhId;
	}

	public void setNoiSinhTinhId(Long noiSinhTinhId) {
		_noiSinhTinhId = noiSinhTinhId;
	}

	public Long getNoiSinhXaId() {
		return _noiSinhXaId;
	}

	public void setNoiSinhXaId(Long noiSinhXaId) {
		_noiSinhXaId = noiSinhXaId;
	}

	public String getNoiSinhChiTiet() {
		if (_noiSinhChiTiet == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiSinhChiTiet;
		}
	}

	public void setNoiSinhChiTiet(String noiSinhChiTiet) {
		_noiSinhChiTiet = noiSinhChiTiet;
	}

	public Long getNoiCapCmndId() {
		return _noiCapCmndId;
	}

	public void setNoiCapCmndId(Long noiCapCmndId) {
		_noiCapCmndId = noiCapCmndId;
	}

	public Long getTonGiaoId() {
		return _tonGiaoId;
	}

	public void setTonGiaoId(Long tonGiaoId) {
		_tonGiaoId = tonGiaoId;
	}

	public Long getSoDinhDanhMeId() {
		return _soDinhDanhMeId;
	}

	public void setSoDinhDanhMeId(Long soDinhDanhMeId) {
		_soDinhDanhMeId = soDinhDanhMeId;
	}

	public Long getTrinhDoHocVanId() {
		return _trinhDoHocVanId;
	}

	public void setTrinhDoHocVanId(Long trinhDoHocVanId) {
		_trinhDoHocVanId = trinhDoHocVanId;
	}

	public Long getTaiKhoanNguoiDungId() {
		return _taiKhoanNguoiDungId;
	}

	public void setTaiKhoanNguoiDungId(Long taiKhoanNguoiDungId) {
		_taiKhoanNguoiDungId = taiKhoanNguoiDungId;
	}

	public Long getQuanHeChuHoId() {
		return _quanHeChuHoId;
	}

	public void setQuanHeChuHoId(Long quanHeChuHoId) {
		_quanHeChuHoId = quanHeChuHoId;
	}

	public Long getQuocTichId() {
		return _quocTichId;
	}

	public void setQuocTichId(Long quocTichId) {
		_quocTichId = quocTichId;
	}

	public Long getDoanhNghiepId() {
		return _doanhNghiepId;
	}

	public void setDoanhNghiepId(Long doanhNghiepId) {
		_doanhNghiepId = doanhNghiepId;
	}

	public String getTenDayDu() {
		if (_tenDayDu == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDayDu;
		}
	}

	public void setTenDayDu(String tenDayDu) {
		_tenDayDu = tenDayDu;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	public void setFax(String fax) {
		_fax = fax;
	}

	public String getWebsite() {
		if (_website == null) {
			return StringPool.BLANK;
		}
		else {
			return _website;
		}
	}

	public void setWebsite(String website) {
		_website = website;
	}

	public int getTinhtrang() {
		return _tinhtrang;
	}

	public void setTinhtrang(int tinhtrang) {
		_tinhtrang = tinhtrang;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CongDan toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CongDan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CongDan.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CongDanImpl congDanImpl = new CongDanImpl();

		congDanImpl.setId(getId());
		congDanImpl.setMa(getMa());
		congDanImpl.setHo(getHo());
		congDanImpl.setDem(getDem());
		congDanImpl.setTen(getTen());
		congDanImpl.setNgaySinh(getNgaySinh());
		congDanImpl.setSoCmnd(getSoCmnd());
		congDanImpl.setNgayCapCmnd(getNgayCapCmnd());
		congDanImpl.setGhiChuCmnd(getGhiChuCmnd());
		congDanImpl.setSoHoChieu(getSoHoChieu());
		congDanImpl.setNgayCapHoChieu(getNgayCapHoChieu());
		congDanImpl.setNgayHetHanHoChieu(getNgayHetHanHoChieu());
		congDanImpl.setNoiCapHoChieuId(getNoiCapHoChieuId());
		congDanImpl.setGhiChuHoChieu(getGhiChuHoChieu());
		congDanImpl.setSoBaoHiemYTe(getSoBaoHiemYTe());
		congDanImpl.setMaSoThueCaNhan(getMaSoThueCaNhan());
		congDanImpl.setDiaChiThuongTru(getDiaChiThuongTru());
		congDanImpl.setDiaChiHienNay(getDiaChiHienNay());
		congDanImpl.setDienThoaiCoDinh(getDienThoaiCoDinh());
		congDanImpl.setDienThoaiDiDong(getDienThoaiDiDong());
		congDanImpl.setHoTenCha(getHoTenCha());
		congDanImpl.setHoTenMe(getHoTenMe());
		congDanImpl.setHoTenVoHoacChong(getHoTenVoHoacChong());
		congDanImpl.setSoHoKhau(getSoHoKhau());
		congDanImpl.setLaChuHo(getLaChuHo());
		congDanImpl.setTinhTrangHonNhanId(getTinhTrangHonNhanId());
		congDanImpl.setEmail(getEmail());
		congDanImpl.setTrinhDoChuyenMonId(getTrinhDoChuyenMonId());
		congDanImpl.setSoDinhDanhChaId(getSoDinhDanhChaId());
		congDanImpl.setSoDinhDanhVoHoacChongId(getSoDinhDanhVoHoacChongId());
		congDanImpl.setDanTocId(getDanTocId());
		congDanImpl.setDiaChiHienNayHuyenId(getDiaChiHienNayHuyenId());
		congDanImpl.setDiaChiHienNayTinhId(getDiaChiHienNayTinhId());
		congDanImpl.setDiaChiHienNayXaId(getDiaChiHienNayXaId());
		congDanImpl.setDiaChiThuongTruHuyenId(getDiaChiThuongTruHuyenId());
		congDanImpl.setDiaChiThuongTruTinhId(getDiaChiThuongTruTinhId());
		congDanImpl.setDiaChiThuongTruXaId(getDiaChiThuongTruXaId());
		congDanImpl.setGioiTinh(getGioiTinh());
		congDanImpl.setNgheNghiepId(getNgheNghiepId());
		congDanImpl.setNoiSinhHuyenId(getNoiSinhHuyenId());
		congDanImpl.setNoiSinhTinhId(getNoiSinhTinhId());
		congDanImpl.setNoiSinhXaId(getNoiSinhXaId());
		congDanImpl.setNoiSinhChiTiet(getNoiSinhChiTiet());
		congDanImpl.setNoiCapCmndId(getNoiCapCmndId());
		congDanImpl.setTonGiaoId(getTonGiaoId());
		congDanImpl.setSoDinhDanhMeId(getSoDinhDanhMeId());
		congDanImpl.setTrinhDoHocVanId(getTrinhDoHocVanId());
		congDanImpl.setTaiKhoanNguoiDungId(getTaiKhoanNguoiDungId());
		congDanImpl.setQuanHeChuHoId(getQuanHeChuHoId());
		congDanImpl.setQuocTichId(getQuocTichId());
		congDanImpl.setDoanhNghiepId(getDoanhNghiepId());
		congDanImpl.setTenDayDu(getTenDayDu());
		congDanImpl.setNgayTao(getNgayTao());
		congDanImpl.setNgaySua(getNgaySua());
		congDanImpl.setNguoiTao(getNguoiTao());
		congDanImpl.setNguoiSua(getNguoiSua());
		congDanImpl.setDaXoa(getDaXoa());
		congDanImpl.setFax(getFax());
		congDanImpl.setWebsite(getWebsite());
		congDanImpl.setTinhtrang(getTinhtrang());

		congDanImpl.resetOriginalValues();

		return congDanImpl;
	}

	public int compareTo(CongDan congDan) {
		int value = 0;

		if (getId() < congDan.getId()) {
			value = -1;
		}
		else if (getId() > congDan.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CongDan congDan = null;

		try {
			congDan = (CongDan)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = congDan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CongDanModelImpl congDanModelImpl = this;

		congDanModelImpl._originalMa = congDanModelImpl._ma;

		congDanModelImpl._originalTen = congDanModelImpl._ten;

		congDanModelImpl._originalNgaySinh = congDanModelImpl._ngaySinh;

		congDanModelImpl._originalSoCmnd = congDanModelImpl._soCmnd;

		congDanModelImpl._originalEmail = congDanModelImpl._email;

		congDanModelImpl._originalDaXoa = congDanModelImpl._daXoa;

		congDanModelImpl._setOriginalDaXoa = false;

		congDanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CongDan> toCacheModel() {
		CongDanCacheModel congDanCacheModel = new CongDanCacheModel();

		congDanCacheModel.id = getId();

		congDanCacheModel.ma = getMa();

		String ma = congDanCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			congDanCacheModel.ma = null;
		}

		congDanCacheModel.ho = getHo();

		String ho = congDanCacheModel.ho;

		if ((ho != null) && (ho.length() == 0)) {
			congDanCacheModel.ho = null;
		}

		congDanCacheModel.dem = getDem();

		String dem = congDanCacheModel.dem;

		if ((dem != null) && (dem.length() == 0)) {
			congDanCacheModel.dem = null;
		}

		congDanCacheModel.ten = getTen();

		String ten = congDanCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			congDanCacheModel.ten = null;
		}

		Date ngaySinh = getNgaySinh();

		if (ngaySinh != null) {
			congDanCacheModel.ngaySinh = ngaySinh.getTime();
		}
		else {
			congDanCacheModel.ngaySinh = Long.MIN_VALUE;
		}

		congDanCacheModel.soCmnd = getSoCmnd();

		String soCmnd = congDanCacheModel.soCmnd;

		if ((soCmnd != null) && (soCmnd.length() == 0)) {
			congDanCacheModel.soCmnd = null;
		}

		Date ngayCapCmnd = getNgayCapCmnd();

		if (ngayCapCmnd != null) {
			congDanCacheModel.ngayCapCmnd = ngayCapCmnd.getTime();
		}
		else {
			congDanCacheModel.ngayCapCmnd = Long.MIN_VALUE;
		}

		congDanCacheModel.ghiChuCmnd = getGhiChuCmnd();

		String ghiChuCmnd = congDanCacheModel.ghiChuCmnd;

		if ((ghiChuCmnd != null) && (ghiChuCmnd.length() == 0)) {
			congDanCacheModel.ghiChuCmnd = null;
		}

		congDanCacheModel.soHoChieu = getSoHoChieu();

		String soHoChieu = congDanCacheModel.soHoChieu;

		if ((soHoChieu != null) && (soHoChieu.length() == 0)) {
			congDanCacheModel.soHoChieu = null;
		}

		Date ngayCapHoChieu = getNgayCapHoChieu();

		if (ngayCapHoChieu != null) {
			congDanCacheModel.ngayCapHoChieu = ngayCapHoChieu.getTime();
		}
		else {
			congDanCacheModel.ngayCapHoChieu = Long.MIN_VALUE;
		}

		Date ngayHetHanHoChieu = getNgayHetHanHoChieu();

		if (ngayHetHanHoChieu != null) {
			congDanCacheModel.ngayHetHanHoChieu = ngayHetHanHoChieu.getTime();
		}
		else {
			congDanCacheModel.ngayHetHanHoChieu = Long.MIN_VALUE;
		}

		congDanCacheModel.noiCapHoChieuId = getNoiCapHoChieuId();

		congDanCacheModel.ghiChuHoChieu = getGhiChuHoChieu();

		String ghiChuHoChieu = congDanCacheModel.ghiChuHoChieu;

		if ((ghiChuHoChieu != null) && (ghiChuHoChieu.length() == 0)) {
			congDanCacheModel.ghiChuHoChieu = null;
		}

		congDanCacheModel.soBaoHiemYTe = getSoBaoHiemYTe();

		String soBaoHiemYTe = congDanCacheModel.soBaoHiemYTe;

		if ((soBaoHiemYTe != null) && (soBaoHiemYTe.length() == 0)) {
			congDanCacheModel.soBaoHiemYTe = null;
		}

		congDanCacheModel.maSoThueCaNhan = getMaSoThueCaNhan();

		String maSoThueCaNhan = congDanCacheModel.maSoThueCaNhan;

		if ((maSoThueCaNhan != null) && (maSoThueCaNhan.length() == 0)) {
			congDanCacheModel.maSoThueCaNhan = null;
		}

		congDanCacheModel.diaChiThuongTru = getDiaChiThuongTru();

		String diaChiThuongTru = congDanCacheModel.diaChiThuongTru;

		if ((diaChiThuongTru != null) && (diaChiThuongTru.length() == 0)) {
			congDanCacheModel.diaChiThuongTru = null;
		}

		congDanCacheModel.diaChiHienNay = getDiaChiHienNay();

		String diaChiHienNay = congDanCacheModel.diaChiHienNay;

		if ((diaChiHienNay != null) && (diaChiHienNay.length() == 0)) {
			congDanCacheModel.diaChiHienNay = null;
		}

		congDanCacheModel.dienThoaiCoDinh = getDienThoaiCoDinh();

		String dienThoaiCoDinh = congDanCacheModel.dienThoaiCoDinh;

		if ((dienThoaiCoDinh != null) && (dienThoaiCoDinh.length() == 0)) {
			congDanCacheModel.dienThoaiCoDinh = null;
		}

		congDanCacheModel.dienThoaiDiDong = getDienThoaiDiDong();

		String dienThoaiDiDong = congDanCacheModel.dienThoaiDiDong;

		if ((dienThoaiDiDong != null) && (dienThoaiDiDong.length() == 0)) {
			congDanCacheModel.dienThoaiDiDong = null;
		}

		congDanCacheModel.hoTenCha = getHoTenCha();

		String hoTenCha = congDanCacheModel.hoTenCha;

		if ((hoTenCha != null) && (hoTenCha.length() == 0)) {
			congDanCacheModel.hoTenCha = null;
		}

		congDanCacheModel.hoTenMe = getHoTenMe();

		String hoTenMe = congDanCacheModel.hoTenMe;

		if ((hoTenMe != null) && (hoTenMe.length() == 0)) {
			congDanCacheModel.hoTenMe = null;
		}

		congDanCacheModel.hoTenVoHoacChong = getHoTenVoHoacChong();

		String hoTenVoHoacChong = congDanCacheModel.hoTenVoHoacChong;

		if ((hoTenVoHoacChong != null) && (hoTenVoHoacChong.length() == 0)) {
			congDanCacheModel.hoTenVoHoacChong = null;
		}

		congDanCacheModel.soHoKhau = getSoHoKhau();

		String soHoKhau = congDanCacheModel.soHoKhau;

		if ((soHoKhau != null) && (soHoKhau.length() == 0)) {
			congDanCacheModel.soHoKhau = null;
		}

		congDanCacheModel.laChuHo = getLaChuHo();

		congDanCacheModel.tinhTrangHonNhanId = getTinhTrangHonNhanId();

		congDanCacheModel.email = getEmail();

		String email = congDanCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			congDanCacheModel.email = null;
		}

		congDanCacheModel.trinhDoChuyenMonId = getTrinhDoChuyenMonId();

		congDanCacheModel.soDinhDanhChaId = getSoDinhDanhChaId();

		congDanCacheModel.soDinhDanhVoHoacChongId = getSoDinhDanhVoHoacChongId();

		congDanCacheModel.danTocId = getDanTocId();

		congDanCacheModel.diaChiHienNayHuyenId = getDiaChiHienNayHuyenId();

		congDanCacheModel.diaChiHienNayTinhId = getDiaChiHienNayTinhId();

		congDanCacheModel.diaChiHienNayXaId = getDiaChiHienNayXaId();

		congDanCacheModel.diaChiThuongTruHuyenId = getDiaChiThuongTruHuyenId();

		congDanCacheModel.diaChiThuongTruTinhId = getDiaChiThuongTruTinhId();

		congDanCacheModel.diaChiThuongTruXaId = getDiaChiThuongTruXaId();

		congDanCacheModel.gioiTinh = getGioiTinh();

		congDanCacheModel.ngheNghiepId = getNgheNghiepId();

		congDanCacheModel.noiSinhHuyenId = getNoiSinhHuyenId();

		congDanCacheModel.noiSinhTinhId = getNoiSinhTinhId();

		congDanCacheModel.noiSinhXaId = getNoiSinhXaId();

		congDanCacheModel.noiSinhChiTiet = getNoiSinhChiTiet();

		String noiSinhChiTiet = congDanCacheModel.noiSinhChiTiet;

		if ((noiSinhChiTiet != null) && (noiSinhChiTiet.length() == 0)) {
			congDanCacheModel.noiSinhChiTiet = null;
		}

		congDanCacheModel.noiCapCmndId = getNoiCapCmndId();

		congDanCacheModel.tonGiaoId = getTonGiaoId();

		congDanCacheModel.soDinhDanhMeId = getSoDinhDanhMeId();

		congDanCacheModel.trinhDoHocVanId = getTrinhDoHocVanId();

		congDanCacheModel.taiKhoanNguoiDungId = getTaiKhoanNguoiDungId();

		congDanCacheModel.quanHeChuHoId = getQuanHeChuHoId();

		congDanCacheModel.quocTichId = getQuocTichId();

		congDanCacheModel.doanhNghiepId = getDoanhNghiepId();

		congDanCacheModel.tenDayDu = getTenDayDu();

		String tenDayDu = congDanCacheModel.tenDayDu;

		if ((tenDayDu != null) && (tenDayDu.length() == 0)) {
			congDanCacheModel.tenDayDu = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			congDanCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			congDanCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			congDanCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			congDanCacheModel.ngaySua = Long.MIN_VALUE;
		}

		congDanCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = congDanCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			congDanCacheModel.nguoiTao = null;
		}

		congDanCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = congDanCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			congDanCacheModel.nguoiSua = null;
		}

		congDanCacheModel.daXoa = getDaXoa();

		congDanCacheModel.fax = getFax();

		String fax = congDanCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			congDanCacheModel.fax = null;
		}

		congDanCacheModel.website = getWebsite();

		String website = congDanCacheModel.website;

		if ((website != null) && (website.length() == 0)) {
			congDanCacheModel.website = null;
		}

		congDanCacheModel.tinhtrang = getTinhtrang();

		return congDanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(121);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ho=");
		sb.append(getHo());
		sb.append(", dem=");
		sb.append(getDem());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", ngaySinh=");
		sb.append(getNgaySinh());
		sb.append(", soCmnd=");
		sb.append(getSoCmnd());
		sb.append(", ngayCapCmnd=");
		sb.append(getNgayCapCmnd());
		sb.append(", ghiChuCmnd=");
		sb.append(getGhiChuCmnd());
		sb.append(", soHoChieu=");
		sb.append(getSoHoChieu());
		sb.append(", ngayCapHoChieu=");
		sb.append(getNgayCapHoChieu());
		sb.append(", ngayHetHanHoChieu=");
		sb.append(getNgayHetHanHoChieu());
		sb.append(", noiCapHoChieuId=");
		sb.append(getNoiCapHoChieuId());
		sb.append(", ghiChuHoChieu=");
		sb.append(getGhiChuHoChieu());
		sb.append(", soBaoHiemYTe=");
		sb.append(getSoBaoHiemYTe());
		sb.append(", maSoThueCaNhan=");
		sb.append(getMaSoThueCaNhan());
		sb.append(", diaChiThuongTru=");
		sb.append(getDiaChiThuongTru());
		sb.append(", diaChiHienNay=");
		sb.append(getDiaChiHienNay());
		sb.append(", dienThoaiCoDinh=");
		sb.append(getDienThoaiCoDinh());
		sb.append(", dienThoaiDiDong=");
		sb.append(getDienThoaiDiDong());
		sb.append(", hoTenCha=");
		sb.append(getHoTenCha());
		sb.append(", hoTenMe=");
		sb.append(getHoTenMe());
		sb.append(", hoTenVoHoacChong=");
		sb.append(getHoTenVoHoacChong());
		sb.append(", soHoKhau=");
		sb.append(getSoHoKhau());
		sb.append(", laChuHo=");
		sb.append(getLaChuHo());
		sb.append(", tinhTrangHonNhanId=");
		sb.append(getTinhTrangHonNhanId());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", trinhDoChuyenMonId=");
		sb.append(getTrinhDoChuyenMonId());
		sb.append(", soDinhDanhChaId=");
		sb.append(getSoDinhDanhChaId());
		sb.append(", soDinhDanhVoHoacChongId=");
		sb.append(getSoDinhDanhVoHoacChongId());
		sb.append(", danTocId=");
		sb.append(getDanTocId());
		sb.append(", diaChiHienNayHuyenId=");
		sb.append(getDiaChiHienNayHuyenId());
		sb.append(", diaChiHienNayTinhId=");
		sb.append(getDiaChiHienNayTinhId());
		sb.append(", diaChiHienNayXaId=");
		sb.append(getDiaChiHienNayXaId());
		sb.append(", diaChiThuongTruHuyenId=");
		sb.append(getDiaChiThuongTruHuyenId());
		sb.append(", diaChiThuongTruTinhId=");
		sb.append(getDiaChiThuongTruTinhId());
		sb.append(", diaChiThuongTruXaId=");
		sb.append(getDiaChiThuongTruXaId());
		sb.append(", gioiTinh=");
		sb.append(getGioiTinh());
		sb.append(", ngheNghiepId=");
		sb.append(getNgheNghiepId());
		sb.append(", noiSinhHuyenId=");
		sb.append(getNoiSinhHuyenId());
		sb.append(", noiSinhTinhId=");
		sb.append(getNoiSinhTinhId());
		sb.append(", noiSinhXaId=");
		sb.append(getNoiSinhXaId());
		sb.append(", noiSinhChiTiet=");
		sb.append(getNoiSinhChiTiet());
		sb.append(", noiCapCmndId=");
		sb.append(getNoiCapCmndId());
		sb.append(", tonGiaoId=");
		sb.append(getTonGiaoId());
		sb.append(", soDinhDanhMeId=");
		sb.append(getSoDinhDanhMeId());
		sb.append(", trinhDoHocVanId=");
		sb.append(getTrinhDoHocVanId());
		sb.append(", taiKhoanNguoiDungId=");
		sb.append(getTaiKhoanNguoiDungId());
		sb.append(", quanHeChuHoId=");
		sb.append(getQuanHeChuHoId());
		sb.append(", quocTichId=");
		sb.append(getQuocTichId());
		sb.append(", doanhNghiepId=");
		sb.append(getDoanhNghiepId());
		sb.append(", tenDayDu=");
		sb.append(getTenDayDu());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append(", tinhtrang=");
		sb.append(getTinhtrang());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(184);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.cd.model.CongDan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ho</column-name><column-value><![CDATA[");
		sb.append(getHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dem</column-name><column-value><![CDATA[");
		sb.append(getDem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySinh</column-name><column-value><![CDATA[");
		sb.append(getNgaySinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCmnd</column-name><column-value><![CDATA[");
		sb.append(getSoCmnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapCmnd</column-name><column-value><![CDATA[");
		sb.append(getNgayCapCmnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChuCmnd</column-name><column-value><![CDATA[");
		sb.append(getGhiChuCmnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHoChieu</column-name><column-value><![CDATA[");
		sb.append(getSoHoChieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapHoChieu</column-name><column-value><![CDATA[");
		sb.append(getNgayCapHoChieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHanHoChieu</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHanHoChieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapHoChieuId</column-name><column-value><![CDATA[");
		sb.append(getNoiCapHoChieuId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChuHoChieu</column-name><column-value><![CDATA[");
		sb.append(getGhiChuHoChieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soBaoHiemYTe</column-name><column-value><![CDATA[");
		sb.append(getSoBaoHiemYTe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoThueCaNhan</column-name><column-value><![CDATA[");
		sb.append(getMaSoThueCaNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTru</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiHienNay</column-name><column-value><![CDATA[");
		sb.append(getDiaChiHienNay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoaiCoDinh</column-name><column-value><![CDATA[");
		sb.append(getDienThoaiCoDinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoaiDiDong</column-name><column-value><![CDATA[");
		sb.append(getDienThoaiDiDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenCha</column-name><column-value><![CDATA[");
		sb.append(getHoTenCha());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenMe</column-name><column-value><![CDATA[");
		sb.append(getHoTenMe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoTenVoHoacChong</column-name><column-value><![CDATA[");
		sb.append(getHoTenVoHoacChong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHoKhau</column-name><column-value><![CDATA[");
		sb.append(getSoHoKhau());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laChuHo</column-name><column-value><![CDATA[");
		sb.append(getLaChuHo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tinhTrangHonNhanId</column-name><column-value><![CDATA[");
		sb.append(getTinhTrangHonNhanId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trinhDoChuyenMonId</column-name><column-value><![CDATA[");
		sb.append(getTrinhDoChuyenMonId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDinhDanhChaId</column-name><column-value><![CDATA[");
		sb.append(getSoDinhDanhChaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDinhDanhVoHoacChongId</column-name><column-value><![CDATA[");
		sb.append(getSoDinhDanhVoHoacChongId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>danTocId</column-name><column-value><![CDATA[");
		sb.append(getDanTocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiHienNayHuyenId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiHienNayHuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiHienNayTinhId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiHienNayTinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiHienNayXaId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiHienNayXaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruHuyenId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruHuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruTinhId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruTinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTruXaId</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTruXaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gioiTinh</column-name><column-value><![CDATA[");
		sb.append(getGioiTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngheNghiepId</column-name><column-value><![CDATA[");
		sb.append(getNgheNghiepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiSinhHuyenId</column-name><column-value><![CDATA[");
		sb.append(getNoiSinhHuyenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiSinhTinhId</column-name><column-value><![CDATA[");
		sb.append(getNoiSinhTinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiSinhXaId</column-name><column-value><![CDATA[");
		sb.append(getNoiSinhXaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiSinhChiTiet</column-name><column-value><![CDATA[");
		sb.append(getNoiSinhChiTiet());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapCmndId</column-name><column-value><![CDATA[");
		sb.append(getNoiCapCmndId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tonGiaoId</column-name><column-value><![CDATA[");
		sb.append(getTonGiaoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDinhDanhMeId</column-name><column-value><![CDATA[");
		sb.append(getSoDinhDanhMeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trinhDoHocVanId</column-name><column-value><![CDATA[");
		sb.append(getTrinhDoHocVanId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taiKhoanNguoiDungId</column-name><column-value><![CDATA[");
		sb.append(getTaiKhoanNguoiDungId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quanHeChuHoId</column-name><column-value><![CDATA[");
		sb.append(getQuanHeChuHoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quocTichId</column-name><column-value><![CDATA[");
		sb.append(getQuocTichId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>doanhNghiepId</column-name><column-value><![CDATA[");
		sb.append(getDoanhNghiepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDayDu</column-name><column-value><![CDATA[");
		sb.append(getTenDayDu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tinhtrang</column-name><column-value><![CDATA[");
		sb.append(getTinhtrang());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CongDan.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CongDan.class
		};
	private long _id;
	private String _ma;
	private String _originalMa;
	private String _ho;
	private String _dem;
	private String _ten;
	private String _originalTen;
	private Date _ngaySinh;
	private Date _originalNgaySinh;
	private String _soCmnd;
	private String _originalSoCmnd;
	private Date _ngayCapCmnd;
	private String _ghiChuCmnd;
	private String _soHoChieu;
	private Date _ngayCapHoChieu;
	private Date _ngayHetHanHoChieu;
	private Long _noiCapHoChieuId;
	private String _ghiChuHoChieu;
	private String _soBaoHiemYTe;
	private String _maSoThueCaNhan;
	private String _diaChiThuongTru;
	private String _diaChiHienNay;
	private String _dienThoaiCoDinh;
	private String _dienThoaiDiDong;
	private String _hoTenCha;
	private String _hoTenMe;
	private String _hoTenVoHoacChong;
	private String _soHoKhau;
	private int _laChuHo;
	private Long _tinhTrangHonNhanId;
	private String _email;
	private String _originalEmail;
	private Long _trinhDoChuyenMonId;
	private Long _soDinhDanhChaId;
	private Long _soDinhDanhVoHoacChongId;
	private Long _danTocId;
	private Long _diaChiHienNayHuyenId;
	private Long _diaChiHienNayTinhId;
	private Long _diaChiHienNayXaId;
	private Long _diaChiThuongTruHuyenId;
	private Long _diaChiThuongTruTinhId;
	private Long _diaChiThuongTruXaId;
	private int _gioiTinh;
	private Long _ngheNghiepId;
	private Long _noiSinhHuyenId;
	private Long _noiSinhTinhId;
	private Long _noiSinhXaId;
	private String _noiSinhChiTiet;
	private Long _noiCapCmndId;
	private Long _tonGiaoId;
	private Long _soDinhDanhMeId;
	private Long _trinhDoHocVanId;
	private Long _taiKhoanNguoiDungId;
	private Long _quanHeChuHoId;
	private Long _quocTichId;
	private Long _doanhNghiepId;
	private String _tenDayDu;
	private Date _ngayTao;
	private Date _ngaySua;
	private String _nguoiTao;
	private String _nguoiSua;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private String _fax;
	private String _website;
	private int _tinhtrang;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private CongDan _escapedModelProxy;
}