/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.cd.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.cmon.dao.cd.model.DanToc;
import org.oep.cmon.dao.cd.model.DanTocModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the DanToc service. Represents a row in the &quot;CMON_DANTOC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.cmon.dao.cd.model.DanTocModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DanTocImpl}.
 * </p>
 *
 * @author LIEMNN
 * @see DanTocImpl
 * @see org.oep.cmon.dao.cd.model.DanToc
 * @see org.oep.cmon.dao.cd.model.DanTocModel
 * @generated
 */
public class DanTocModelImpl extends BaseModelImpl<DanToc>
	implements DanTocModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dan toc model instance should use the {@link org.oep.cmon.dao.cd.model.DanToc} interface instead.
	 */
	public static final String TABLE_NAME = "CMON_DANTOC";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "MA", Types.VARCHAR },
			{ "TEN", Types.VARCHAR },
			{ "PHIENBAN", Types.BIGINT },
			{ "LATHIEUSO", Types.BIGINT },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "DAXOA", Types.INTEGER },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "TENKHAC", Types.VARCHAR },
			{ "NGAYSUA", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table CMON_DANTOC (ID LONG not null primary key,MA VARCHAR(75) null,TEN VARCHAR(75) null,PHIENBAN LONG,LATHIEUSO LONG,NGAYTAO DATE null,DAXOA INTEGER,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,TENKHAC VARCHAR(75) null,NGAYSUA DATE null)";
	public static final String TABLE_SQL_DROP = "drop table CMON_DANTOC";
	public static final String ORDER_BY_JPQL = " ORDER BY danToc.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMON_DANTOC.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.cmon.dao.cd.model.DanToc"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.cmon.dao.cd.model.DanToc"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.cmon.dao.cd.model.DanToc"),
			true);
	public static long DAXOA_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.cmon.dao.cd.model.DanToc"));

	public DanTocModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DanToc.class;
	}

	public String getModelClassName() {
		return DanToc.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getMa() {
		if (_ma == null) {
			return StringPool.BLANK;
		}
		else {
			return _ma;
		}
	}

	public void setMa(String ma) {
		_ma = ma;
	}

	public String getTen() {
		if (_ten == null) {
			return StringPool.BLANK;
		}
		else {
			return _ten;
		}
	}

	public void setTen(String ten) {
		_ten = ten;
	}

	public long getPhienBan() {
		return _phienBan;
	}

	public void setPhienBan(long phienBan) {
		_phienBan = phienBan;
	}

	public long getLaThieuSo() {
		return _laThieuSo;
	}

	public void setLaThieuSo(long laThieuSo) {
		_laThieuSo = laThieuSo;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public int getDaXoa() {
		return _daXoa;
	}

	public void setDaXoa(int daXoa) {
		_columnBitmask |= DAXOA_COLUMN_BITMASK;

		if (!_setOriginalDaXoa) {
			_setOriginalDaXoa = true;

			_originalDaXoa = _daXoa;
		}

		_daXoa = daXoa;
	}

	public int getOriginalDaXoa() {
		return _originalDaXoa;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public String getTenKhac() {
		if (_tenKhac == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenKhac;
		}
	}

	public void setTenKhac(String tenKhac) {
		_tenKhac = tenKhac;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DanToc toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DanToc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DanToc.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DanTocImpl danTocImpl = new DanTocImpl();

		danTocImpl.setId(getId());
		danTocImpl.setMa(getMa());
		danTocImpl.setTen(getTen());
		danTocImpl.setPhienBan(getPhienBan());
		danTocImpl.setLaThieuSo(getLaThieuSo());
		danTocImpl.setNgayTao(getNgayTao());
		danTocImpl.setDaXoa(getDaXoa());
		danTocImpl.setNguoiTao(getNguoiTao());
		danTocImpl.setNguoiSua(getNguoiSua());
		danTocImpl.setTenKhac(getTenKhac());
		danTocImpl.setNgaySua(getNgaySua());

		danTocImpl.resetOriginalValues();

		return danTocImpl;
	}

	public int compareTo(DanToc danToc) {
		int value = 0;

		if (getId() < danToc.getId()) {
			value = -1;
		}
		else if (getId() > danToc.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DanToc danToc = null;

		try {
			danToc = (DanToc)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = danToc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DanTocModelImpl danTocModelImpl = this;

		danTocModelImpl._originalDaXoa = danTocModelImpl._daXoa;

		danTocModelImpl._setOriginalDaXoa = false;

		danTocModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DanToc> toCacheModel() {
		DanTocCacheModel danTocCacheModel = new DanTocCacheModel();

		danTocCacheModel.id = getId();

		danTocCacheModel.ma = getMa();

		String ma = danTocCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			danTocCacheModel.ma = null;
		}

		danTocCacheModel.ten = getTen();

		String ten = danTocCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			danTocCacheModel.ten = null;
		}

		danTocCacheModel.phienBan = getPhienBan();

		danTocCacheModel.laThieuSo = getLaThieuSo();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			danTocCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			danTocCacheModel.ngayTao = Long.MIN_VALUE;
		}

		danTocCacheModel.daXoa = getDaXoa();

		danTocCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = danTocCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			danTocCacheModel.nguoiTao = null;
		}

		danTocCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = danTocCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			danTocCacheModel.nguoiSua = null;
		}

		danTocCacheModel.tenKhac = getTenKhac();

		String tenKhac = danTocCacheModel.tenKhac;

		if ((tenKhac != null) && (tenKhac.length() == 0)) {
			danTocCacheModel.tenKhac = null;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			danTocCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			danTocCacheModel.ngaySua = Long.MIN_VALUE;
		}

		return danTocCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", ma=");
		sb.append(getMa());
		sb.append(", ten=");
		sb.append(getTen());
		sb.append(", phienBan=");
		sb.append(getPhienBan());
		sb.append(", laThieuSo=");
		sb.append(getLaThieuSo());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", daXoa=");
		sb.append(getDaXoa());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", tenKhac=");
		sb.append(getTenKhac());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("org.oep.cmon.dao.cd.model.DanToc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ma</column-name><column-value><![CDATA[");
		sb.append(getMa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ten</column-name><column-value><![CDATA[");
		sb.append(getTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phienBan</column-name><column-value><![CDATA[");
		sb.append(getPhienBan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>laThieuSo</column-name><column-value><![CDATA[");
		sb.append(getLaThieuSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>daXoa</column-name><column-value><![CDATA[");
		sb.append(getDaXoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenKhac</column-name><column-value><![CDATA[");
		sb.append(getTenKhac());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DanToc.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DanToc.class
		};
	private long _id;
	private String _ma;
	private String _ten;
	private long _phienBan;
	private long _laThieuSo;
	private Date _ngayTao;
	private int _daXoa;
	private int _originalDaXoa;
	private boolean _setOriginalDaXoa;
	private String _nguoiTao;
	private String _nguoiSua;
	private String _tenKhac;
	private Date _ngaySua;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private DanToc _escapedModelProxy;
}