/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.dlms.dao.chitietgplx.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;


import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

import org.oep.dlms.dao.chitietgplx.model.ChiTietGPLX;
import org.oep.dlms.dao.chitietgplx.model.ChiTietGPLXModel;

/**
 * The base model implementation for the ChiTietGPLX service. Represents a row in the &quot;DLMS_CHITIETGPLX&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.dlms.dao.chitietgplx.model.ChiTietGPLXModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChiTietGPLXImpl}.
 * </p>
 *
 * @author hunghq
 * @see ChiTietGPLXImpl
 * @see org.oep.dlms.dao.chitietgplx.model.ChiTietGPLX
 * @see org.oep.dlms.dao.chitietgplx.model.ChiTietGPLXModel
 * @generated
 */
public class ChiTietGPLXModelImpl extends BaseModelImpl<ChiTietGPLX>
	implements ChiTietGPLXModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chi tiet g p l x model instance should use the {@link vn.dtt.dlms.dao.chitietgplx.model.ChiTietGPLX} interface instead.
	 */
	public static final String TABLE_NAME = "DLMS_CHITIETGPLX";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "GPLXID", Types.BIGINT },
			{ "SOGIAYPHEPLAIXE", Types.VARCHAR },
			{ "HANGGIAYPHEPLAIXEID", Types.BIGINT },
			{ "NOICAPGPLXID", Types.BIGINT },
			{ "NOICAPGPLXNUOCNGOAIID", Types.BIGINT },
			{ "NGAYCAPGPLX", Types.TIMESTAMP },
			{ "NGAYTRUNGTUYEN", Types.TIMESTAMP },
			{ "NGAYHETHAN", Types.TIMESTAMP },
			{ "NOIHOCLAIXEID", Types.BIGINT },
			{ "NOIHOCLAIXENUOCNGOAIID", Types.BIGINT },
			{ "NAMHOCLAIXE", Types.BIGINT },
			{ "NOIHOCLAIXENUOCNGOAI", Types.VARCHAR },
			{ "NOIHOCLAIXE", Types.VARCHAR },
			{ "NOICAPGPLXNUOCNGOAI", Types.VARCHAR },
			{ "NOICAPGPLX", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DLMS_CHITIETGPLX (ID LONG not null primary key,GPLXID LONG,SOGIAYPHEPLAIXE VARCHAR(75) null,HANGGIAYPHEPLAIXEID LONG,NOICAPGPLXID LONG,NOICAPGPLXNUOCNGOAIID LONG,NGAYCAPGPLX DATE null,NGAYTRUNGTUYEN DATE null,NGAYHETHAN DATE null,NOIHOCLAIXEID LONG,NOIHOCLAIXENUOCNGOAIID LONG,NAMHOCLAIXE LONG,NOIHOCLAIXENUOCNGOAI VARCHAR(75) null,NOIHOCLAIXE VARCHAR(75) null,NOICAPGPLXNUOCNGOAI VARCHAR(75) null,NOICAPGPLX VARCHAR(75) null,NGAYTAO DATE null,NGAYSUA DATE null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DLMS_CHITIETGPLX";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.dlms.dao.chitietgplx.model.ChiTietGPLX"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.dlms.dao.chitietgplx.model.ChiTietGPLX"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.dlms.dao.chitietgplx.model.ChiTietGPLX"),
			true);
	public static long IDGPLX_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.dlms.dao.chitietgplx.model.ChiTietGPLX"));

	public ChiTietGPLXModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ChiTietGPLX.class;
	}

	public String getModelClassName() {
		return ChiTietGPLX.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public long getIdGPLX() {
		return _idGPLX;
	}

	public void setIdGPLX(long idGPLX) {
		_columnBitmask |= IDGPLX_COLUMN_BITMASK;

		if (!_setOriginalIdGPLX) {
			_setOriginalIdGPLX = true;

			_originalIdGPLX = _idGPLX;
		}

		_idGPLX = idGPLX;
	}

	public long getOriginalIdGPLX() {
		return _originalIdGPLX;
	}

	public String getSoGPLX() {
		if (_soGPLX == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGPLX;
		}
	}

	public void setSoGPLX(String soGPLX) {
		_soGPLX = soGPLX;
	}

	public long getIdHangGPLX() {
		return _idHangGPLX;
	}

	public void setIdHangGPLX(long idHangGPLX) {
		_idHangGPLX = idHangGPLX;
	}

	public long getIdNoiCapGPLX() {
		return _idNoiCapGPLX;
	}

	public void setIdNoiCapGPLX(long idNoiCapGPLX) {
		_idNoiCapGPLX = idNoiCapGPLX;
	}

	public long getIdNoiCapGPLXNuocNgoai() {
		return _idNoiCapGPLXNuocNgoai;
	}

	public void setIdNoiCapGPLXNuocNgoai(long idNoiCapGPLXNuocNgoai) {
		_idNoiCapGPLXNuocNgoai = idNoiCapGPLXNuocNgoai;
	}

	public Date getNgayCapGPLX() {
		return _ngayCapGPLX;
	}

	public void setNgayCapGPLX(Date ngayCapGPLX) {
		_ngayCapGPLX = ngayCapGPLX;
	}

	public Date getNgayTrungTuyen() {
		return _ngayTrungTuyen;
	}

	public void setNgayTrungTuyen(Date ngayTrungTuyen) {
		_ngayTrungTuyen = ngayTrungTuyen;
	}

	public Date getNgayHetHan() {
		return _ngayHetHan;
	}

	public void setNgayHetHan(Date ngayHetHan) {
		_ngayHetHan = ngayHetHan;
	}

	public long getIdNoiHocLaiXe() {
		return _idNoiHocLaiXe;
	}

	public void setIdNoiHocLaiXe(long idNoiHocLaiXe) {
		_idNoiHocLaiXe = idNoiHocLaiXe;
	}

	public long getIdNoiHocLaiXeNuocNgoai() {
		return _idNoiHocLaiXeNuocNgoai;
	}

	public void setIdNoiHocLaiXeNuocNgoai(long idNoiHocLaiXeNuocNgoai) {
		_idNoiHocLaiXeNuocNgoai = idNoiHocLaiXeNuocNgoai;
	}

	public long getNamHocLaiXe() {
		return _namHocLaiXe;
	}

	public void setNamHocLaiXe(long namHocLaiXe) {
		_namHocLaiXe = namHocLaiXe;
	}

	public String getNoiHocLaiXeNuocNgoai() {
		if (_noiHocLaiXeNuocNgoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiHocLaiXeNuocNgoai;
		}
	}

	public void setNoiHocLaiXeNuocNgoai(String noiHocLaiXeNuocNgoai) {
		_noiHocLaiXeNuocNgoai = noiHocLaiXeNuocNgoai;
	}

	public String getNoiHocLaiXe() {
		if (_noiHocLaiXe == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiHocLaiXe;
		}
	}

	public void setNoiHocLaiXe(String noiHocLaiXe) {
		_noiHocLaiXe = noiHocLaiXe;
	}

	public String getNoiCapGPLXNuocNgoai() {
		if (_noiCapGPLXNuocNgoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiCapGPLXNuocNgoai;
		}
	}

	public void setNoiCapGPLXNuocNgoai(String noiCapGPLXNuocNgoai) {
		_noiCapGPLXNuocNgoai = noiCapGPLXNuocNgoai;
	}

	public String getNoiCapGPLX() {
		if (_noiCapGPLX == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiCapGPLX;
		}
	}

	public void setNoiCapGPLX(String noiCapGPLX) {
		_noiCapGPLX = noiCapGPLX;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ChiTietGPLX toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ChiTietGPLX)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					ChiTietGPLX.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		ChiTietGPLXImpl chiTietGPLXImpl = new ChiTietGPLXImpl();

		chiTietGPLXImpl.setId(getId());
		chiTietGPLXImpl.setIdGPLX(getIdGPLX());
		chiTietGPLXImpl.setSoGPLX(getSoGPLX());
		chiTietGPLXImpl.setIdHangGPLX(getIdHangGPLX());
		chiTietGPLXImpl.setIdNoiCapGPLX(getIdNoiCapGPLX());
		chiTietGPLXImpl.setIdNoiCapGPLXNuocNgoai(getIdNoiCapGPLXNuocNgoai());
		chiTietGPLXImpl.setNgayCapGPLX(getNgayCapGPLX());
		chiTietGPLXImpl.setNgayTrungTuyen(getNgayTrungTuyen());
		chiTietGPLXImpl.setNgayHetHan(getNgayHetHan());
		chiTietGPLXImpl.setIdNoiHocLaiXe(getIdNoiHocLaiXe());
		chiTietGPLXImpl.setIdNoiHocLaiXeNuocNgoai(getIdNoiHocLaiXeNuocNgoai());
		chiTietGPLXImpl.setNamHocLaiXe(getNamHocLaiXe());
		chiTietGPLXImpl.setNoiHocLaiXeNuocNgoai(getNoiHocLaiXeNuocNgoai());
		chiTietGPLXImpl.setNoiHocLaiXe(getNoiHocLaiXe());
		chiTietGPLXImpl.setNoiCapGPLXNuocNgoai(getNoiCapGPLXNuocNgoai());
		chiTietGPLXImpl.setNoiCapGPLX(getNoiCapGPLX());
		chiTietGPLXImpl.setNgayTao(getNgayTao());
		chiTietGPLXImpl.setNgaySua(getNgaySua());
		chiTietGPLXImpl.setNguoiTao(getNguoiTao());
		chiTietGPLXImpl.setNguoiSua(getNguoiSua());

		chiTietGPLXImpl.resetOriginalValues();

		return chiTietGPLXImpl;
	}

	public int compareTo(ChiTietGPLX chiTietGPLX) {
		long primaryKey = chiTietGPLX.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ChiTietGPLX chiTietGPLX = null;

		try {
			chiTietGPLX = (ChiTietGPLX)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = chiTietGPLX.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ChiTietGPLXModelImpl chiTietGPLXModelImpl = this;

		chiTietGPLXModelImpl._originalIdGPLX = chiTietGPLXModelImpl._idGPLX;

		chiTietGPLXModelImpl._setOriginalIdGPLX = false;

		chiTietGPLXModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChiTietGPLX> toCacheModel() {
		ChiTietGPLXCacheModel chiTietGPLXCacheModel = new ChiTietGPLXCacheModel();

		chiTietGPLXCacheModel.id = getId();

		chiTietGPLXCacheModel.idGPLX = getIdGPLX();

		chiTietGPLXCacheModel.soGPLX = getSoGPLX();

		String soGPLX = chiTietGPLXCacheModel.soGPLX;

		if ((soGPLX != null) && (soGPLX.length() == 0)) {
			chiTietGPLXCacheModel.soGPLX = null;
		}

		chiTietGPLXCacheModel.idHangGPLX = getIdHangGPLX();

		chiTietGPLXCacheModel.idNoiCapGPLX = getIdNoiCapGPLX();

		chiTietGPLXCacheModel.idNoiCapGPLXNuocNgoai = getIdNoiCapGPLXNuocNgoai();

		Date ngayCapGPLX = getNgayCapGPLX();

		if (ngayCapGPLX != null) {
			chiTietGPLXCacheModel.ngayCapGPLX = ngayCapGPLX.getTime();
		}
		else {
			chiTietGPLXCacheModel.ngayCapGPLX = Long.MIN_VALUE;
		}

		Date ngayTrungTuyen = getNgayTrungTuyen();

		if (ngayTrungTuyen != null) {
			chiTietGPLXCacheModel.ngayTrungTuyen = ngayTrungTuyen.getTime();
		}
		else {
			chiTietGPLXCacheModel.ngayTrungTuyen = Long.MIN_VALUE;
		}

		Date ngayHetHan = getNgayHetHan();

		if (ngayHetHan != null) {
			chiTietGPLXCacheModel.ngayHetHan = ngayHetHan.getTime();
		}
		else {
			chiTietGPLXCacheModel.ngayHetHan = Long.MIN_VALUE;
		}

		chiTietGPLXCacheModel.idNoiHocLaiXe = getIdNoiHocLaiXe();

		chiTietGPLXCacheModel.idNoiHocLaiXeNuocNgoai = getIdNoiHocLaiXeNuocNgoai();

		chiTietGPLXCacheModel.namHocLaiXe = getNamHocLaiXe();

		chiTietGPLXCacheModel.noiHocLaiXeNuocNgoai = getNoiHocLaiXeNuocNgoai();

		String noiHocLaiXeNuocNgoai = chiTietGPLXCacheModel.noiHocLaiXeNuocNgoai;

		if ((noiHocLaiXeNuocNgoai != null) &&
				(noiHocLaiXeNuocNgoai.length() == 0)) {
			chiTietGPLXCacheModel.noiHocLaiXeNuocNgoai = null;
		}

		chiTietGPLXCacheModel.noiHocLaiXe = getNoiHocLaiXe();

		String noiHocLaiXe = chiTietGPLXCacheModel.noiHocLaiXe;

		if ((noiHocLaiXe != null) && (noiHocLaiXe.length() == 0)) {
			chiTietGPLXCacheModel.noiHocLaiXe = null;
		}

		chiTietGPLXCacheModel.noiCapGPLXNuocNgoai = getNoiCapGPLXNuocNgoai();

		String noiCapGPLXNuocNgoai = chiTietGPLXCacheModel.noiCapGPLXNuocNgoai;

		if ((noiCapGPLXNuocNgoai != null) &&
				(noiCapGPLXNuocNgoai.length() == 0)) {
			chiTietGPLXCacheModel.noiCapGPLXNuocNgoai = null;
		}

		chiTietGPLXCacheModel.noiCapGPLX = getNoiCapGPLX();

		String noiCapGPLX = chiTietGPLXCacheModel.noiCapGPLX;

		if ((noiCapGPLX != null) && (noiCapGPLX.length() == 0)) {
			chiTietGPLXCacheModel.noiCapGPLX = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			chiTietGPLXCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			chiTietGPLXCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			chiTietGPLXCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			chiTietGPLXCacheModel.ngaySua = Long.MIN_VALUE;
		}

		chiTietGPLXCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = chiTietGPLXCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			chiTietGPLXCacheModel.nguoiTao = null;
		}

		chiTietGPLXCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = chiTietGPLXCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			chiTietGPLXCacheModel.nguoiSua = null;
		}

		return chiTietGPLXCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(41);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", idGPLX=");
		sb.append(getIdGPLX());
		sb.append(", soGPLX=");
		sb.append(getSoGPLX());
		sb.append(", idHangGPLX=");
		sb.append(getIdHangGPLX());
		sb.append(", idNoiCapGPLX=");
		sb.append(getIdNoiCapGPLX());
		sb.append(", idNoiCapGPLXNuocNgoai=");
		sb.append(getIdNoiCapGPLXNuocNgoai());
		sb.append(", ngayCapGPLX=");
		sb.append(getNgayCapGPLX());
		sb.append(", ngayTrungTuyen=");
		sb.append(getNgayTrungTuyen());
		sb.append(", ngayHetHan=");
		sb.append(getNgayHetHan());
		sb.append(", idNoiHocLaiXe=");
		sb.append(getIdNoiHocLaiXe());
		sb.append(", idNoiHocLaiXeNuocNgoai=");
		sb.append(getIdNoiHocLaiXeNuocNgoai());
		sb.append(", namHocLaiXe=");
		sb.append(getNamHocLaiXe());
		sb.append(", noiHocLaiXeNuocNgoai=");
		sb.append(getNoiHocLaiXeNuocNgoai());
		sb.append(", noiHocLaiXe=");
		sb.append(getNoiHocLaiXe());
		sb.append(", noiCapGPLXNuocNgoai=");
		sb.append(getNoiCapGPLXNuocNgoai());
		sb.append(", noiCapGPLX=");
		sb.append(getNoiCapGPLX());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(64);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.dlms.dao.chitietgplx.model.ChiTietGPLX");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idGPLX</column-name><column-value><![CDATA[");
		sb.append(getIdGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGPLX</column-name><column-value><![CDATA[");
		sb.append(getSoGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idHangGPLX</column-name><column-value><![CDATA[");
		sb.append(getIdHangGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNoiCapGPLX</column-name><column-value><![CDATA[");
		sb.append(getIdNoiCapGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNoiCapGPLXNuocNgoai</column-name><column-value><![CDATA[");
		sb.append(getIdNoiCapGPLXNuocNgoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGPLX</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTrungTuyen</column-name><column-value><![CDATA[");
		sb.append(getNgayTrungTuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayHetHan</column-name><column-value><![CDATA[");
		sb.append(getNgayHetHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNoiHocLaiXe</column-name><column-value><![CDATA[");
		sb.append(getIdNoiHocLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNoiHocLaiXeNuocNgoai</column-name><column-value><![CDATA[");
		sb.append(getIdNoiHocLaiXeNuocNgoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namHocLaiXe</column-name><column-value><![CDATA[");
		sb.append(getNamHocLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiHocLaiXeNuocNgoai</column-name><column-value><![CDATA[");
		sb.append(getNoiHocLaiXeNuocNgoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiHocLaiXe</column-name><column-value><![CDATA[");
		sb.append(getNoiHocLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapGPLXNuocNgoai</column-name><column-value><![CDATA[");
		sb.append(getNoiCapGPLXNuocNgoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapGPLX</column-name><column-value><![CDATA[");
		sb.append(getNoiCapGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ChiTietGPLX.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ChiTietGPLX.class
		};
	private long _id;
	private long _idGPLX;
	private long _originalIdGPLX;
	private boolean _setOriginalIdGPLX;
	private String _soGPLX;
	private long _idHangGPLX;
	private long _idNoiCapGPLX;
	private long _idNoiCapGPLXNuocNgoai;
	private Date _ngayCapGPLX;
	private Date _ngayTrungTuyen;
	private Date _ngayHetHan;
	private long _idNoiHocLaiXe;
	private long _idNoiHocLaiXeNuocNgoai;
	private long _namHocLaiXe;
	private String _noiHocLaiXeNuocNgoai;
	private String _noiHocLaiXe;
	private String _noiCapGPLXNuocNgoai;
	private String _noiCapGPLX;
	private Date _ngayTao;
	private Date _ngaySua;
	private String _nguoiTao;
	private String _nguoiSua;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private ChiTietGPLX _escapedModelProxy;
}