/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.csms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AnhChanDungYeuCauDangKyCongDan service. Represents a row in the &quot;csms_yeucaudangkycongdan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.csms.model.impl.AnhChanDungYeuCauDangKyCongDanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.csms.model.impl.AnhChanDungYeuCauDangKyCongDanImpl}.
 * </p>
 *
 * @author NAM
 * @see AnhChanDungYeuCauDangKyCongDan
 * @see org.oep.cmon.dao.csms.model.impl.AnhChanDungYeuCauDangKyCongDanImpl
 * @see org.oep.cmon.dao.csms.model.impl.AnhChanDungYeuCauDangKyCongDanModelImpl
 * @generated
 */
public interface AnhChanDungYeuCauDangKyCongDanModel extends BaseModel<AnhChanDungYeuCauDangKyCongDan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a anh chan dung yeu cau dang ky cong dan model instance should use the {@link AnhChanDungYeuCauDangKyCongDan} interface instead.
	 */

	/**
	 * Returns the primary key of this anh chan dung yeu cau dang ky cong dan.
	 *
	 * @return the primary key of this anh chan dung yeu cau dang ky cong dan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this anh chan dung yeu cau dang ky cong dan.
	 *
	 * @param primaryKey the primary key of this anh chan dung yeu cau dang ky cong dan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this anh chan dung yeu cau dang ky cong dan.
	 *
	 * @return the ID of this anh chan dung yeu cau dang ky cong dan
	 */
	public long getId();

	/**
	 * Sets the ID of this anh chan dung yeu cau dang ky cong dan.
	 *
	 * @param id the ID of this anh chan dung yeu cau dang ky cong dan
	 */
	public void setId(long id);

	/**
	 * Returns the anh chan dung of this anh chan dung yeu cau dang ky cong dan.
	 *
	 * @return the anh chan dung of this anh chan dung yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getAnhChanDung();

	/**
	 * Sets the anh chan dung of this anh chan dung yeu cau dang ky cong dan.
	 *
	 * @param AnhChanDung the anh chan dung of this anh chan dung yeu cau dang ky cong dan
	 */
	public void setAnhChanDung(String AnhChanDung);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		AnhChanDungYeuCauDangKyCongDan anhChanDungYeuCauDangKyCongDan);

	public int hashCode();

	public CacheModel<AnhChanDungYeuCauDangKyCongDan> toCacheModel();

	public AnhChanDungYeuCauDangKyCongDan toEscapedModel();

	public String toString();

	public String toXmlString();
}