/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.csms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the YeuCauDangKyCongDan service. Represents a row in the &quot;csms_yeucaudangkycongdan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.csms.model.impl.YeuCauDangKyCongDanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.csms.model.impl.YeuCauDangKyCongDanImpl}.
 * </p>
 *
 * @author NAM
 * @see YeuCauDangKyCongDan
 * @see org.oep.cmon.dao.csms.model.impl.YeuCauDangKyCongDanImpl
 * @see org.oep.cmon.dao.csms.model.impl.YeuCauDangKyCongDanModelImpl
 * @generated
 */
public interface YeuCauDangKyCongDanModel extends BaseModel<YeuCauDangKyCongDan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yeu cau dang ky cong dan model instance should use the {@link YeuCauDangKyCongDan} interface instead.
	 */

	/**
	 * Returns the primary key of this yeu cau dang ky cong dan.
	 *
	 * @return the primary key of this yeu cau dang ky cong dan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yeu cau dang ky cong dan.
	 *
	 * @param primaryKey the primary key of this yeu cau dang ky cong dan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this yeu cau dang ky cong dan.
	 *
	 * @return the ID of this yeu cau dang ky cong dan
	 */
	public long getId();

	/**
	 * Sets the ID of this yeu cau dang ky cong dan.
	 *
	 * @param id the ID of this yeu cau dang ky cong dan
	 */
	public void setId(long id);

	/**
	 * Returns the ngay yeu cau of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay yeu cau of this yeu cau dang ky cong dan
	 */
	public Date getNgayYeuCau();

	/**
	 * Sets the ngay yeu cau of this yeu cau dang ky cong dan.
	 *
	 * @param NgayYeuCau the ngay yeu cau of this yeu cau dang ky cong dan
	 */
	public void setNgayYeuCau(Date NgayYeuCau);

	/**
	 * Returns the so cmnd of this yeu cau dang ky cong dan.
	 *
	 * @return the so cmnd of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getSoCmnd();

	/**
	 * Sets the so cmnd of this yeu cau dang ky cong dan.
	 *
	 * @param SoCmnd the so cmnd of this yeu cau dang ky cong dan
	 */
	public void setSoCmnd(String SoCmnd);

	/**
	 * Returns the ngay cap cmnd of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay cap cmnd of this yeu cau dang ky cong dan
	 */
	public Date getNgayCapCmnd();

	/**
	 * Sets the ngay cap cmnd of this yeu cau dang ky cong dan.
	 *
	 * @param NgayCapCmnd the ngay cap cmnd of this yeu cau dang ky cong dan
	 */
	public void setNgayCapCmnd(Date NgayCapCmnd);

	/**
	 * Returns the i d noi cap cmnd of this yeu cau dang ky cong dan.
	 *
	 * @return the i d noi cap cmnd of this yeu cau dang ky cong dan
	 */
	public Long getIDNoiCapCmnd();

	/**
	 * Sets the i d noi cap cmnd of this yeu cau dang ky cong dan.
	 *
	 * @param IDNoiCapCmnd the i d noi cap cmnd of this yeu cau dang ky cong dan
	 */
	public void setIDNoiCapCmnd(Long IDNoiCapCmnd);

	/**
	 * Returns the ghi chu cmnd of this yeu cau dang ky cong dan.
	 *
	 * @return the ghi chu cmnd of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getGhiChuCmnd();

	/**
	 * Sets the ghi chu cmnd of this yeu cau dang ky cong dan.
	 *
	 * @param GhiChuCmnd the ghi chu cmnd of this yeu cau dang ky cong dan
	 */
	public void setGhiChuCmnd(String GhiChuCmnd);

	/**
	 * Returns the email of this yeu cau dang ky cong dan.
	 *
	 * @return the email of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this yeu cau dang ky cong dan.
	 *
	 * @param Email the email of this yeu cau dang ky cong dan
	 */
	public void setEmail(String Email);

	/**
	 * Returns the ho cong dan of this yeu cau dang ky cong dan.
	 *
	 * @return the ho cong dan of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getHoCongDan();

	/**
	 * Sets the ho cong dan of this yeu cau dang ky cong dan.
	 *
	 * @param HoCongDan the ho cong dan of this yeu cau dang ky cong dan
	 */
	public void setHoCongDan(String HoCongDan);

	/**
	 * Returns the ho va ten of this yeu cau dang ky cong dan.
	 *
	 * @return the ho va ten of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getHoVaTen();

	/**
	 * Sets the ho va ten of this yeu cau dang ky cong dan.
	 *
	 * @param HoVaTen the ho va ten of this yeu cau dang ky cong dan
	 */
	public void setHoVaTen(String HoVaTen);

	/**
	 * Returns the ten dem of this yeu cau dang ky cong dan.
	 *
	 * @return the ten dem of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getTenDem();

	/**
	 * Sets the ten dem of this yeu cau dang ky cong dan.
	 *
	 * @param TenDem the ten dem of this yeu cau dang ky cong dan
	 */
	public void setTenDem(String TenDem);

	/**
	 * Returns the ten cong dan of this yeu cau dang ky cong dan.
	 *
	 * @return the ten cong dan of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getTenCongDan();

	/**
	 * Sets the ten cong dan of this yeu cau dang ky cong dan.
	 *
	 * @param TenCongDan the ten cong dan of this yeu cau dang ky cong dan
	 */
	public void setTenCongDan(String TenCongDan);

	/**
	 * Returns the ngay sinh of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay sinh of this yeu cau dang ky cong dan
	 */
	public Date getNgaySinh();

	/**
	 * Sets the ngay sinh of this yeu cau dang ky cong dan.
	 *
	 * @param NgaySinh the ngay sinh of this yeu cau dang ky cong dan
	 */
	public void setNgaySinh(Date NgaySinh);

	/**
	 * Returns the gioi tinh of this yeu cau dang ky cong dan.
	 *
	 * @return the gioi tinh of this yeu cau dang ky cong dan
	 */
	public int getGioiTinh();

	/**
	 * Sets the gioi tinh of this yeu cau dang ky cong dan.
	 *
	 * @param GioiTinh the gioi tinh of this yeu cau dang ky cong dan
	 */
	public void setGioiTinh(int GioiTinh);

	/**
	 * Returns the i d dan toc of this yeu cau dang ky cong dan.
	 *
	 * @return the i d dan toc of this yeu cau dang ky cong dan
	 */
	public Long getIDDanToc();

	/**
	 * Sets the i d dan toc of this yeu cau dang ky cong dan.
	 *
	 * @param IDDanToc the i d dan toc of this yeu cau dang ky cong dan
	 */
	public void setIDDanToc(Long IDDanToc);

	/**
	 * Returns the i d quoc tich of this yeu cau dang ky cong dan.
	 *
	 * @return the i d quoc tich of this yeu cau dang ky cong dan
	 */
	public Long getIDQuocTich();

	/**
	 * Sets the i d quoc tich of this yeu cau dang ky cong dan.
	 *
	 * @param IDQuocTich the i d quoc tich of this yeu cau dang ky cong dan
	 */
	public void setIDQuocTich(Long IDQuocTich);

	/**
	 * Returns the i d ton giao of this yeu cau dang ky cong dan.
	 *
	 * @return the i d ton giao of this yeu cau dang ky cong dan
	 */
	public Long getIDTonGiao();

	/**
	 * Sets the i d ton giao of this yeu cau dang ky cong dan.
	 *
	 * @param IDTonGiao the i d ton giao of this yeu cau dang ky cong dan
	 */
	public void setIDTonGiao(Long IDTonGiao);

	/**
	 * Returns the dien thoai co dinh of this yeu cau dang ky cong dan.
	 *
	 * @return the dien thoai co dinh of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getDienThoaiCoDinh();

	/**
	 * Sets the dien thoai co dinh of this yeu cau dang ky cong dan.
	 *
	 * @param DienThoaiCoDinh the dien thoai co dinh of this yeu cau dang ky cong dan
	 */
	public void setDienThoaiCoDinh(String DienThoaiCoDinh);

	/**
	 * Returns the dien thoai di dong of this yeu cau dang ky cong dan.
	 *
	 * @return the dien thoai di dong of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getDienThoaiDiDong();

	/**
	 * Sets the dien thoai di dong of this yeu cau dang ky cong dan.
	 *
	 * @param DienThoaiDiDong the dien thoai di dong of this yeu cau dang ky cong dan
	 */
	public void setDienThoaiDiDong(String DienThoaiDiDong);

	/**
	 * Returns the i d trinh do hoc van of this yeu cau dang ky cong dan.
	 *
	 * @return the i d trinh do hoc van of this yeu cau dang ky cong dan
	 */
	public Long getIDTrinhDoHocVan();

	/**
	 * Sets the i d trinh do hoc van of this yeu cau dang ky cong dan.
	 *
	 * @param IDTrinhDoHocVan the i d trinh do hoc van of this yeu cau dang ky cong dan
	 */
	public void setIDTrinhDoHocVan(Long IDTrinhDoHocVan);

	/**
	 * Returns the so ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @return the so ho chieu of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getSoHoChieu();

	/**
	 * Sets the so ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @param SoHoChieu the so ho chieu of this yeu cau dang ky cong dan
	 */
	public void setSoHoChieu(String SoHoChieu);

	/**
	 * Returns the ngay cap ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay cap ho chieu of this yeu cau dang ky cong dan
	 */
	public Date getNgayCapHoChieu();

	/**
	 * Sets the ngay cap ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @param NgayCapHoChieu the ngay cap ho chieu of this yeu cau dang ky cong dan
	 */
	public void setNgayCapHoChieu(Date NgayCapHoChieu);

	/**
	 * Returns the i d noi cap ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @return the i d noi cap ho chieu of this yeu cau dang ky cong dan
	 */
	public Long getIDNoiCapHoChieu();

	/**
	 * Sets the i d noi cap ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @param IDNoiCapHoChieu the i d noi cap ho chieu of this yeu cau dang ky cong dan
	 */
	public void setIDNoiCapHoChieu(Long IDNoiCapHoChieu);

	/**
	 * Returns the ngay het han ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay het han ho chieu of this yeu cau dang ky cong dan
	 */
	public Date getNgayHetHanHoChieu();

	/**
	 * Sets the ngay het han ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @param NgayHetHanHoChieu the ngay het han ho chieu of this yeu cau dang ky cong dan
	 */
	public void setNgayHetHanHoChieu(Date NgayHetHanHoChieu);

	/**
	 * Returns the ghi chu ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @return the ghi chu ho chieu of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getGhiChuHoChieu();

	/**
	 * Sets the ghi chu ho chieu of this yeu cau dang ky cong dan.
	 *
	 * @param GhiChuHoChieu the ghi chu ho chieu of this yeu cau dang ky cong dan
	 */
	public void setGhiChuHoChieu(String GhiChuHoChieu);

	/**
	 * Returns the so bao hiem yte of this yeu cau dang ky cong dan.
	 *
	 * @return the so bao hiem yte of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getSoBaoHiemYte();

	/**
	 * Sets the so bao hiem yte of this yeu cau dang ky cong dan.
	 *
	 * @param SoBaoHiemYte the so bao hiem yte of this yeu cau dang ky cong dan
	 */
	public void setSoBaoHiemYte(String SoBaoHiemYte);

	/**
	 * Returns the ma so thue ca nhan of this yeu cau dang ky cong dan.
	 *
	 * @return the ma so thue ca nhan of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMaSoThueCaNhan();

	/**
	 * Sets the ma so thue ca nhan of this yeu cau dang ky cong dan.
	 *
	 * @param MaSoThueCaNhan the ma so thue ca nhan of this yeu cau dang ky cong dan
	 */
	public void setMaSoThueCaNhan(String MaSoThueCaNhan);

	/**
	 * Returns the i d nghe nghiep of this yeu cau dang ky cong dan.
	 *
	 * @return the i d nghe nghiep of this yeu cau dang ky cong dan
	 */
	public Long getIDNgheNghiep();

	/**
	 * Sets the i d nghe nghiep of this yeu cau dang ky cong dan.
	 *
	 * @param IDNgheNghiep the i d nghe nghiep of this yeu cau dang ky cong dan
	 */
	public void setIDNgheNghiep(Long IDNgheNghiep);

	/**
	 * Returns the i d trinh do chuyen mon of this yeu cau dang ky cong dan.
	 *
	 * @return the i d trinh do chuyen mon of this yeu cau dang ky cong dan
	 */
	public Long getIDTrinhDoChuyenMon();

	/**
	 * Sets the i d trinh do chuyen mon of this yeu cau dang ky cong dan.
	 *
	 * @param IDTrinhDoChuyenMon the i d trinh do chuyen mon of this yeu cau dang ky cong dan
	 */
	public void setIDTrinhDoChuyenMon(Long IDTrinhDoChuyenMon);

	/**
	 * Returns the tinh trang hon nhan of this yeu cau dang ky cong dan.
	 *
	 * @return the tinh trang hon nhan of this yeu cau dang ky cong dan
	 */
	public Long getTinhTrangHonNhan();

	/**
	 * Sets the tinh trang hon nhan of this yeu cau dang ky cong dan.
	 *
	 * @param TinhTrangHonNhan the tinh trang hon nhan of this yeu cau dang ky cong dan
	 */
	public void setTinhTrangHonNhan(Long TinhTrangHonNhan);

	/**
	 * Returns the ho va ten cha of this yeu cau dang ky cong dan.
	 *
	 * @return the ho va ten cha of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getHoVaTenCha();

	/**
	 * Sets the ho va ten cha of this yeu cau dang ky cong dan.
	 *
	 * @param HoVaTenCha the ho va ten cha of this yeu cau dang ky cong dan
	 */
	public void setHoVaTenCha(String HoVaTenCha);

	/**
	 * Returns the ho va ten me of this yeu cau dang ky cong dan.
	 *
	 * @return the ho va ten me of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getHoVaTenMe();

	/**
	 * Sets the ho va ten me of this yeu cau dang ky cong dan.
	 *
	 * @param HoVaTenMe the ho va ten me of this yeu cau dang ky cong dan
	 */
	public void setHoVaTenMe(String HoVaTenMe);

	/**
	 * Returns the ho va ten vo chong of this yeu cau dang ky cong dan.
	 *
	 * @return the ho va ten vo chong of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getHoVaTenVoChong();

	/**
	 * Sets the ho va ten vo chong of this yeu cau dang ky cong dan.
	 *
	 * @param HoVaTenVoChong the ho va ten vo chong of this yeu cau dang ky cong dan
	 */
	public void setHoVaTenVoChong(String HoVaTenVoChong);

	/**
	 * Returns the so ho khau of this yeu cau dang ky cong dan.
	 *
	 * @return the so ho khau of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getSoHoKhau();

	/**
	 * Sets the so ho khau of this yeu cau dang ky cong dan.
	 *
	 * @param SoHoKhau the so ho khau of this yeu cau dang ky cong dan
	 */
	public void setSoHoKhau(String SoHoKhau);

	/**
	 * Returns the chu ho of this yeu cau dang ky cong dan.
	 *
	 * @return the chu ho of this yeu cau dang ky cong dan
	 */
	public int getChuHo();

	/**
	 * Sets the chu ho of this yeu cau dang ky cong dan.
	 *
	 * @param ChuHo the chu ho of this yeu cau dang ky cong dan
	 */
	public void setChuHo(int ChuHo);

	/**
	 * Returns the i d quan he of this yeu cau dang ky cong dan.
	 *
	 * @return the i d quan he of this yeu cau dang ky cong dan
	 */
	public Long getIDQuanHe();

	/**
	 * Sets the i d quan he of this yeu cau dang ky cong dan.
	 *
	 * @param IDQuanHe the i d quan he of this yeu cau dang ky cong dan
	 */
	public void setIDQuanHe(Long IDQuanHe);

	/**
	 * Returns the i d tinh thanh noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @return the i d tinh thanh noi sinh of this yeu cau dang ky cong dan
	 */
	public Long getIDTinhThanhNoiSinh();

	/**
	 * Sets the i d tinh thanh noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @param IDTinhThanhNoiSinh the i d tinh thanh noi sinh of this yeu cau dang ky cong dan
	 */
	public void setIDTinhThanhNoiSinh(Long IDTinhThanhNoiSinh);

	/**
	 * Returns the i d quan huyen noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @return the i d quan huyen noi sinh of this yeu cau dang ky cong dan
	 */
	public Long getIDQuanHuyenNoiSinh();

	/**
	 * Sets the i d quan huyen noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @param IDQuanHuyenNoiSinh the i d quan huyen noi sinh of this yeu cau dang ky cong dan
	 */
	public void setIDQuanHuyenNoiSinh(Long IDQuanHuyenNoiSinh);

	/**
	 * Returns the i d phuong xa noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @return the i d phuong xa noi sinh of this yeu cau dang ky cong dan
	 */
	public Long getIDPhuongXaNoiSinh();

	/**
	 * Sets the i d phuong xa noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @param IDPhuongXaNoiSinh the i d phuong xa noi sinh of this yeu cau dang ky cong dan
	 */
	public void setIDPhuongXaNoiSinh(Long IDPhuongXaNoiSinh);

	/**
	 * Returns the mo ta dia chi noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @return the mo ta dia chi noi sinh of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMoTaDiaChiNoiSinh();

	/**
	 * Sets the mo ta dia chi noi sinh of this yeu cau dang ky cong dan.
	 *
	 * @param MoTaDiaChiNoiSinh the mo ta dia chi noi sinh of this yeu cau dang ky cong dan
	 */
	public void setMoTaDiaChiNoiSinh(String MoTaDiaChiNoiSinh);

	/**
	 * Returns the i d tinh thanh thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @return the i d tinh thanh thuong tru of this yeu cau dang ky cong dan
	 */
	public Long getIDTinhThanhThuongTru();

	/**
	 * Sets the i d tinh thanh thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @param IDTinhThanhThuongTru the i d tinh thanh thuong tru of this yeu cau dang ky cong dan
	 */
	public void setIDTinhThanhThuongTru(Long IDTinhThanhThuongTru);

	/**
	 * Returns the i d quan huyen thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @return the i d quan huyen thuong tru of this yeu cau dang ky cong dan
	 */
	public Long getIDQuanHuyenThuongTru();

	/**
	 * Sets the i d quan huyen thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @param IDQuanHuyenThuongTru the i d quan huyen thuong tru of this yeu cau dang ky cong dan
	 */
	public void setIDQuanHuyenThuongTru(Long IDQuanHuyenThuongTru);

	/**
	 * Returns the i d phuong xa thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @return the i d phuong xa thuong tru of this yeu cau dang ky cong dan
	 */
	public Long getIDPhuongXaThuongTru();

	/**
	 * Sets the i d phuong xa thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @param IDPhuongXaThuongTru the i d phuong xa thuong tru of this yeu cau dang ky cong dan
	 */
	public void setIDPhuongXaThuongTru(Long IDPhuongXaThuongTru);

	/**
	 * Returns the mo ta dia chi thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @return the mo ta dia chi thuong tru of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMoTaDiaChiThuongTru();

	/**
	 * Sets the mo ta dia chi thuong tru of this yeu cau dang ky cong dan.
	 *
	 * @param MoTaDiaChiThuongTru the mo ta dia chi thuong tru of this yeu cau dang ky cong dan
	 */
	public void setMoTaDiaChiThuongTru(String MoTaDiaChiThuongTru);

	/**
	 * Returns the i d tinh thanh hien tai of this yeu cau dang ky cong dan.
	 *
	 * @return the i d tinh thanh hien tai of this yeu cau dang ky cong dan
	 */
	public Long getIDTinhThanhHienTai();

	/**
	 * Sets the i d tinh thanh hien tai of this yeu cau dang ky cong dan.
	 *
	 * @param IDTinhThanhHienTai the i d tinh thanh hien tai of this yeu cau dang ky cong dan
	 */
	public void setIDTinhThanhHienTai(Long IDTinhThanhHienTai);

	/**
	 * Returns the i d quan huyen hien tai of this yeu cau dang ky cong dan.
	 *
	 * @return the i d quan huyen hien tai of this yeu cau dang ky cong dan
	 */
	public Long getIDQuanHuyenHienTai();

	/**
	 * Sets the i d quan huyen hien tai of this yeu cau dang ky cong dan.
	 *
	 * @param IDQuanHuyenHienTai the i d quan huyen hien tai of this yeu cau dang ky cong dan
	 */
	public void setIDQuanHuyenHienTai(Long IDQuanHuyenHienTai);

	/**
	 * Returns the i d phuong xa hien tai of this yeu cau dang ky cong dan.
	 *
	 * @return the i d phuong xa hien tai of this yeu cau dang ky cong dan
	 */
	public Long getIDPhuongXaHienTai();

	/**
	 * Sets the i d phuong xa hien tai of this yeu cau dang ky cong dan.
	 *
	 * @param IDPhuongXaHienTai the i d phuong xa hien tai of this yeu cau dang ky cong dan
	 */
	public void setIDPhuongXaHienTai(Long IDPhuongXaHienTai);

	/**
	 * Returns the mo ta dia chi hien tai of this yeu cau dang ky cong dan.
	 *
	 * @return the mo ta dia chi hien tai of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMoTaDiaChiHienTai();

	/**
	 * Sets the mo ta dia chi hien tai of this yeu cau dang ky cong dan.
	 *
	 * @param MoTaDiaChiHienTai the mo ta dia chi hien tai of this yeu cau dang ky cong dan
	 */
	public void setMoTaDiaChiHienTai(String MoTaDiaChiHienTai);

	/**
	 * Returns the ma xac nhan of this yeu cau dang ky cong dan.
	 *
	 * @return the ma xac nhan of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMaXacNhan();

	/**
	 * Sets the ma xac nhan of this yeu cau dang ky cong dan.
	 *
	 * @param MaXacNhan the ma xac nhan of this yeu cau dang ky cong dan
	 */
	public void setMaXacNhan(String MaXacNhan);

	/**
	 * Returns the ngay chung thuc of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay chung thuc of this yeu cau dang ky cong dan
	 */
	public Date getNgayChungThuc();

	/**
	 * Sets the ngay chung thuc of this yeu cau dang ky cong dan.
	 *
	 * @param NgayChungThuc the ngay chung thuc of this yeu cau dang ky cong dan
	 */
	public void setNgayChungThuc(Date NgayChungThuc);

	/**
	 * Returns the nguoi chung thuc of this yeu cau dang ky cong dan.
	 *
	 * @return the nguoi chung thuc of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getNguoiChungThuc();

	/**
	 * Sets the nguoi chung thuc of this yeu cau dang ky cong dan.
	 *
	 * @param NguoiChungThuc the nguoi chung thuc of this yeu cau dang ky cong dan
	 */
	public void setNguoiChungThuc(String NguoiChungThuc);

	/**
	 * Returns the ma cong dan cha of this yeu cau dang ky cong dan.
	 *
	 * @return the ma cong dan cha of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMaCongDanCha();

	/**
	 * Sets the ma cong dan cha of this yeu cau dang ky cong dan.
	 *
	 * @param MaCongDanCha the ma cong dan cha of this yeu cau dang ky cong dan
	 */
	public void setMaCongDanCha(String MaCongDanCha);

	/**
	 * Returns the ma cong dan me of this yeu cau dang ky cong dan.
	 *
	 * @return the ma cong dan me of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMaCongDanMe();

	/**
	 * Sets the ma cong dan me of this yeu cau dang ky cong dan.
	 *
	 * @param MaCongDanMe the ma cong dan me of this yeu cau dang ky cong dan
	 */
	public void setMaCongDanMe(String MaCongDanMe);

	/**
	 * Returns the ma cong dan vo chong of this yeu cau dang ky cong dan.
	 *
	 * @return the ma cong dan vo chong of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMaCongDanVoChong();

	/**
	 * Sets the ma cong dan vo chong of this yeu cau dang ky cong dan.
	 *
	 * @param MaCongDanVoChong the ma cong dan vo chong of this yeu cau dang ky cong dan
	 */
	public void setMaCongDanVoChong(String MaCongDanVoChong);

	/**
	 * Returns the ma cong dan of this yeu cau dang ky cong dan.
	 *
	 * @return the ma cong dan of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getMaCongDan();

	/**
	 * Sets the ma cong dan of this yeu cau dang ky cong dan.
	 *
	 * @param MaCongDan the ma cong dan of this yeu cau dang ky cong dan
	 */
	public void setMaCongDan(String MaCongDan);

	/**
	 * Returns the loai yeu cau of this yeu cau dang ky cong dan.
	 *
	 * @return the loai yeu cau of this yeu cau dang ky cong dan
	 */
	public int getLoaiYeuCau();

	/**
	 * Sets the loai yeu cau of this yeu cau dang ky cong dan.
	 *
	 * @param LoaiYeuCau the loai yeu cau of this yeu cau dang ky cong dan
	 */
	public void setLoaiYeuCau(int LoaiYeuCau);

	/**
	 * Returns the trang thai yeu cau of this yeu cau dang ky cong dan.
	 *
	 * @return the trang thai yeu cau of this yeu cau dang ky cong dan
	 */
	public int getTrangThaiYeuCau();

	/**
	 * Sets the trang thai yeu cau of this yeu cau dang ky cong dan.
	 *
	 * @param TrangThaiYeuCau the trang thai yeu cau of this yeu cau dang ky cong dan
	 */
	public void setTrangThaiYeuCau(int TrangThaiYeuCau);

	/**
	 * Returns the ngay tao of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay tao of this yeu cau dang ky cong dan
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this yeu cau dang ky cong dan.
	 *
	 * @param NgayTao the ngay tao of this yeu cau dang ky cong dan
	 */
	public void setNgayTao(Date NgayTao);

	/**
	 * Returns the ngay sua of this yeu cau dang ky cong dan.
	 *
	 * @return the ngay sua of this yeu cau dang ky cong dan
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this yeu cau dang ky cong dan.
	 *
	 * @param NgaySua the ngay sua of this yeu cau dang ky cong dan
	 */
	public void setNgaySua(Date NgaySua);

	/**
	 * Returns the nguoi tao of this yeu cau dang ky cong dan.
	 *
	 * @return the nguoi tao of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this yeu cau dang ky cong dan.
	 *
	 * @param NguoiTao the nguoi tao of this yeu cau dang ky cong dan
	 */
	public void setNguoiTao(String NguoiTao);

	/**
	 * Returns the nguoi sua of this yeu cau dang ky cong dan.
	 *
	 * @return the nguoi sua of this yeu cau dang ky cong dan
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this yeu cau dang ky cong dan.
	 *
	 * @param NguoiSua the nguoi sua of this yeu cau dang ky cong dan
	 */
	public void setNguoiSua(String NguoiSua);

	/**
	 * Returns the xoa of this yeu cau dang ky cong dan.
	 *
	 * @return the xoa of this yeu cau dang ky cong dan
	 */
	public int getXoa();

	/**
	 * Sets the xoa of this yeu cau dang ky cong dan.
	 *
	 * @param Xoa the xoa of this yeu cau dang ky cong dan
	 */
	public void setXoa(int Xoa);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(YeuCauDangKyCongDan yeuCauDangKyCongDan);

	public int hashCode();

	public CacheModel<YeuCauDangKyCongDan> toCacheModel();

	public YeuCauDangKyCongDan toEscapedModel();

	public String toString();

	public String toXmlString();
}