
package org.oep.sharedservice.touchscreen.tracuutthc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Mon Jul 21 12:17:29 ICT 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "getTTHCByIdTTHCResponse", namespace = "http://tracuutthc.touchscreen.sharedservice.dtt.vn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTTHCByIdTTHCResponse", namespace = "http://tracuutthc.touchscreen.sharedservice.dtt.vn/")

public class GetTTHCByIdTTHCResponse {

    @XmlElement(name = "return")
    private vn.dtt.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinhSoap _return;

    public vn.dtt.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinhSoap getReturn() {
        return this._return;
    }

    public void setReturn(vn.dtt.cmon.dao.touchscreen.model.TraCuuThuTucHanhChinhSoap new_return)  {
        this._return = new_return;
    }

}

