/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ExchFileDinhKem service. Represents a row in the &quot;exch_filedinhkem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.exch.dao.hoso.model.impl.ExchFileDinhKemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.exch.dao.hoso.model.impl.ExchFileDinhKemImpl}.
 * </p>
 *
 * @author NAM
 * @see ExchFileDinhKem
 * @see org.oep.exch.dao.hoso.model.impl.ExchFileDinhKemImpl
 * @see org.oep.exch.dao.hoso.model.impl.ExchFileDinhKemModelImpl
 * @generated
 */
public interface ExchFileDinhKemModel extends BaseModel<ExchFileDinhKem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a exch file dinh kem model instance should use the {@link ExchFileDinhKem} interface instead.
	 */

	/**
	 * Returns the primary key of this exch file dinh kem.
	 *
	 * @return the primary key of this exch file dinh kem
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this exch file dinh kem.
	 *
	 * @param primaryKey the primary key of this exch file dinh kem
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this exch file dinh kem.
	 *
	 * @return the ID of this exch file dinh kem
	 */
	public long getId();

	/**
	 * Sets the ID of this exch file dinh kem.
	 *
	 * @param id the ID of this exch file dinh kem
	 */
	public void setId(long id);

	/**
	 * Returns the online ID of this exch file dinh kem.
	 *
	 * @return the online ID of this exch file dinh kem
	 */
	public long getOnlineId();

	/**
	 * Sets the online ID of this exch file dinh kem.
	 *
	 * @param OnlineId the online ID of this exch file dinh kem
	 */
	public void setOnlineId(long OnlineId);

	/**
	 * Returns the ten tai lieu dinh kem of this exch file dinh kem.
	 *
	 * @return the ten tai lieu dinh kem of this exch file dinh kem
	 */
	@AutoEscape
	public String getTenTaiLieuDinhKem();

	/**
	 * Sets the ten tai lieu dinh kem of this exch file dinh kem.
	 *
	 * @param TenTaiLieuDinhKem the ten tai lieu dinh kem of this exch file dinh kem
	 */
	public void setTenTaiLieuDinhKem(String TenTaiLieuDinhKem);

	/**
	 * Returns the url tai lieu dinh kem of this exch file dinh kem.
	 *
	 * @return the url tai lieu dinh kem of this exch file dinh kem
	 */
	@AutoEscape
	public String getUrlTaiLieuDinhKem();

	/**
	 * Sets the url tai lieu dinh kem of this exch file dinh kem.
	 *
	 * @param UrlTaiLieuDinhKem the url tai lieu dinh kem of this exch file dinh kem
	 */
	public void setUrlTaiLieuDinhKem(String UrlTaiLieuDinhKem);

	/**
	 * Returns the ten file of this exch file dinh kem.
	 *
	 * @return the ten file of this exch file dinh kem
	 */
	@AutoEscape
	public String getTenFile();

	/**
	 * Sets the ten file of this exch file dinh kem.
	 *
	 * @param TenFile the ten file of this exch file dinh kem
	 */
	public void setTenFile(String TenFile);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ExchFileDinhKem exchFileDinhKem);

	public int hashCode();

	public CacheModel<ExchFileDinhKem> toCacheModel();

	public ExchFileDinhKem toEscapedModel();

	public String toString();

	public String toXmlString();
}