/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HoSoMotCua service. Represents a row in the &quot;exch_hosomotcua&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.exch.dao.hoso.model.impl.HoSoMotCuaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.exch.dao.hoso.model.impl.HoSoMotCuaImpl}.
 * </p>
 *
 * @author NAM
 * @see HoSoMotCua
 * @see org.oep.exch.dao.hoso.model.impl.HoSoMotCuaImpl
 * @see org.oep.exch.dao.hoso.model.impl.HoSoMotCuaModelImpl
 * @generated
 */
public interface HoSoMotCuaModel extends BaseModel<HoSoMotCua> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ho so mot cua model instance should use the {@link HoSoMotCua} interface instead.
	 */

	/**
	 * Returns the primary key of this ho so mot cua.
	 *
	 * @return the primary key of this ho so mot cua
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ho so mot cua.
	 *
	 * @param primaryKey the primary key of this ho so mot cua
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ho so mot cua.
	 *
	 * @return the ID of this ho so mot cua
	 */
	public long getId();

	/**
	 * Sets the ID of this ho so mot cua.
	 *
	 * @param id the ID of this ho so mot cua
	 */
	public void setId(long id);

	/**
	 * Returns the ngay chuyen of this ho so mot cua.
	 *
	 * @return the ngay chuyen of this ho so mot cua
	 */
	public Date getNgayChuyen();

	/**
	 * Sets the ngay chuyen of this ho so mot cua.
	 *
	 * @param NgayChuyen the ngay chuyen of this ho so mot cua
	 */
	public void setNgayChuyen(Date NgayChuyen);

	/**
	 * Returns the ma so ho so of this ho so mot cua.
	 *
	 * @return the ma so ho so of this ho so mot cua
	 */
	@AutoEscape
	public String getMaSoHoSo();

	/**
	 * Sets the ma so ho so of this ho so mot cua.
	 *
	 * @param MaSoHoSo the ma so ho so of this ho so mot cua
	 */
	public void setMaSoHoSo(String MaSoHoSo);

	/**
	 * Returns the ma loai ho so of this ho so mot cua.
	 *
	 * @return the ma loai ho so of this ho so mot cua
	 */
	@AutoEscape
	public String getMaLoaiHoSo();

	/**
	 * Sets the ma loai ho so of this ho so mot cua.
	 *
	 * @param MaLoaiHoSo the ma loai ho so of this ho so mot cua
	 */
	public void setMaLoaiHoSo(String MaLoaiHoSo);

	/**
	 * Returns the ma don vi tiep nhan of this ho so mot cua.
	 *
	 * @return the ma don vi tiep nhan of this ho so mot cua
	 */
	@AutoEscape
	public String getMaDonViTiepNhan();

	/**
	 * Sets the ma don vi tiep nhan of this ho so mot cua.
	 *
	 * @param MaDonViTiepNhan the ma don vi tiep nhan of this ho so mot cua
	 */
	public void setMaDonViTiepNhan(String MaDonViTiepNhan);

	/**
	 * Returns the ngay nop ho so of this ho so mot cua.
	 *
	 * @return the ngay nop ho so of this ho so mot cua
	 */
	@AutoEscape
	public String getNgayNopHoSo();

	/**
	 * Sets the ngay nop ho so of this ho so mot cua.
	 *
	 * @param NgayNopHoSo the ngay nop ho so of this ho so mot cua
	 */
	public void setNgayNopHoSo(String NgayNopHoSo);

	/**
	 * Returns the ngay hen tra of this ho so mot cua.
	 *
	 * @return the ngay hen tra of this ho so mot cua
	 */
	@AutoEscape
	public String getNgayHenTra();

	/**
	 * Sets the ngay hen tra of this ho so mot cua.
	 *
	 * @param NgayHenTra the ngay hen tra of this ho so mot cua
	 */
	public void setNgayHenTra(String NgayHenTra);

	/**
	 * Returns the ho ten nguoi nop of this ho so mot cua.
	 *
	 * @return the ho ten nguoi nop of this ho so mot cua
	 */
	@AutoEscape
	public String getHoTenNguoiNop();

	/**
	 * Sets the ho ten nguoi nop of this ho so mot cua.
	 *
	 * @param HoTenNguoiNop the ho ten nguoi nop of this ho so mot cua
	 */
	public void setHoTenNguoiNop(String HoTenNguoiNop);

	/**
	 * Returns the so cmnd of this ho so mot cua.
	 *
	 * @return the so cmnd of this ho so mot cua
	 */
	@AutoEscape
	public String getSoCmnd();

	/**
	 * Sets the so cmnd of this ho so mot cua.
	 *
	 * @param SoCmnd the so cmnd of this ho so mot cua
	 */
	public void setSoCmnd(String SoCmnd);

	/**
	 * Returns the ngay sinh of this ho so mot cua.
	 *
	 * @return the ngay sinh of this ho so mot cua
	 */
	@AutoEscape
	public String getNgaySinh();

	/**
	 * Sets the ngay sinh of this ho so mot cua.
	 *
	 * @param NgaySinh the ngay sinh of this ho so mot cua
	 */
	public void setNgaySinh(String NgaySinh);

	/**
	 * Returns the ma tinh thuong tru of this ho so mot cua.
	 *
	 * @return the ma tinh thuong tru of this ho so mot cua
	 */
	@AutoEscape
	public String getMaTinhThuongTru();

	/**
	 * Sets the ma tinh thuong tru of this ho so mot cua.
	 *
	 * @param MaTinhThuongTru the ma tinh thuong tru of this ho so mot cua
	 */
	public void setMaTinhThuongTru(String MaTinhThuongTru);

	/**
	 * Returns the mo ta dia chi thuong tru of this ho so mot cua.
	 *
	 * @return the mo ta dia chi thuong tru of this ho so mot cua
	 */
	@AutoEscape
	public String getMoTaDiaChiThuongTru();

	/**
	 * Sets the mo ta dia chi thuong tru of this ho so mot cua.
	 *
	 * @param MoTaDiaChiThuongTru the mo ta dia chi thuong tru of this ho so mot cua
	 */
	public void setMoTaDiaChiThuongTru(String MoTaDiaChiThuongTru);

	/**
	 * Returns the gioi tinh of this ho so mot cua.
	 *
	 * @return the gioi tinh of this ho so mot cua
	 */
	public int getGioiTinh();

	/**
	 * Sets the gioi tinh of this ho so mot cua.
	 *
	 * @param GioiTinh the gioi tinh of this ho so mot cua
	 */
	public void setGioiTinh(int GioiTinh);

	/**
	 * Returns the ma nguoi tiep nhan of this ho so mot cua.
	 *
	 * @return the ma nguoi tiep nhan of this ho so mot cua
	 */
	@AutoEscape
	public String getMaNguoiTiepNhan();

	/**
	 * Sets the ma nguoi tiep nhan of this ho so mot cua.
	 *
	 * @param MaNguoiTiepNhan the ma nguoi tiep nhan of this ho so mot cua
	 */
	public void setMaNguoiTiepNhan(String MaNguoiTiepNhan);

	/**
	 * Returns the ten nguoi tiep nhan of this ho so mot cua.
	 *
	 * @return the ten nguoi tiep nhan of this ho so mot cua
	 */
	@AutoEscape
	public String getTenNguoiTiepNhan();

	/**
	 * Sets the ten nguoi tiep nhan of this ho so mot cua.
	 *
	 * @param TenNguoiTiepNhan the ten nguoi tiep nhan of this ho so mot cua
	 */
	public void setTenNguoiTiepNhan(String TenNguoiTiepNhan);

	/**
	 * Returns the don vi cung cap of this ho so mot cua.
	 *
	 * @return the don vi cung cap of this ho so mot cua
	 */
	@AutoEscape
	public String getDonViCungCap();

	/**
	 * Sets the don vi cung cap of this ho so mot cua.
	 *
	 * @param DonViCungCap the don vi cung cap of this ho so mot cua
	 */
	public void setDonViCungCap(String DonViCungCap);

	/**
	 * Returns the trang thai xu ly of this ho so mot cua.
	 *
	 * @return the trang thai xu ly of this ho so mot cua
	 */
	public int getTrangThaiXuLy();

	/**
	 * Sets the trang thai xu ly of this ho so mot cua.
	 *
	 * @param TrangThaiXuLy the trang thai xu ly of this ho so mot cua
	 */
	public void setTrangThaiXuLy(int TrangThaiXuLy);

	/**
	 * Returns the ngay xu ly of this ho so mot cua.
	 *
	 * @return the ngay xu ly of this ho so mot cua
	 */
	public Date getNgayXuLy();

	/**
	 * Sets the ngay xu ly of this ho so mot cua.
	 *
	 * @param NgayXuLy the ngay xu ly of this ho so mot cua
	 */
	public void setNgayXuLy(Date NgayXuLy);

	/**
	 * Returns the loi khi xu ly of this ho so mot cua.
	 *
	 * @return the loi khi xu ly of this ho so mot cua
	 */
	@AutoEscape
	public String getLoiKhiXuLy();

	/**
	 * Sets the loi khi xu ly of this ho so mot cua.
	 *
	 * @param LoiKhiXuLy the loi khi xu ly of this ho so mot cua
	 */
	public void setLoiKhiXuLy(String LoiKhiXuLy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HoSoMotCua hoSoMotCua);

	public int hashCode();

	public CacheModel<HoSoMotCua> toCacheModel();

	public HoSoMotCua toEscapedModel();

	public String toString();

	public String toXmlString();
}