/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HoSoTrucTuyen service. Represents a row in the &quot;exch_hosotructuyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.exch.dao.hoso.model.impl.HoSoTrucTuyenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.exch.dao.hoso.model.impl.HoSoTrucTuyenImpl}.
 * </p>
 *
 * @author NAM
 * @see HoSoTrucTuyen
 * @see org.oep.exch.dao.hoso.model.impl.HoSoTrucTuyenImpl
 * @see org.oep.exch.dao.hoso.model.impl.HoSoTrucTuyenModelImpl
 * @generated
 */
public interface HoSoTrucTuyenModel extends BaseModel<HoSoTrucTuyen> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ho so truc tuyen model instance should use the {@link HoSoTrucTuyen} interface instead.
	 */

	/**
	 * Returns the primary key of this ho so truc tuyen.
	 *
	 * @return the primary key of this ho so truc tuyen
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ho so truc tuyen.
	 *
	 * @param primaryKey the primary key of this ho so truc tuyen
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ho so truc tuyen.
	 *
	 * @return the ID of this ho so truc tuyen
	 */
	public long getId();

	/**
	 * Sets the ID of this ho so truc tuyen.
	 *
	 * @param id the ID of this ho so truc tuyen
	 */
	public void setId(long id);

	/**
	 * Returns the ngay trich xuat of this ho so truc tuyen.
	 *
	 * @return the ngay trich xuat of this ho so truc tuyen
	 */
	public Date getNgayTrichXuat();

	/**
	 * Sets the ngay trich xuat of this ho so truc tuyen.
	 *
	 * @param NgayTrichXuat the ngay trich xuat of this ho so truc tuyen
	 */
	public void setNgayTrichXuat(Date NgayTrichXuat);

	/**
	 * Returns the online ID of this ho so truc tuyen.
	 *
	 * @return the online ID of this ho so truc tuyen
	 */
	public long getOnlineId();

	/**
	 * Sets the online ID of this ho so truc tuyen.
	 *
	 * @param OnlineId the online ID of this ho so truc tuyen
	 */
	public void setOnlineId(long OnlineId);

	/**
	 * Returns the ma loai ho so of this ho so truc tuyen.
	 *
	 * @return the ma loai ho so of this ho so truc tuyen
	 */
	@AutoEscape
	public String getMaLoaiHoSo();

	/**
	 * Sets the ma loai ho so of this ho so truc tuyen.
	 *
	 * @param MaLoaiHoSo the ma loai ho so of this ho so truc tuyen
	 */
	public void setMaLoaiHoSo(String MaLoaiHoSo);

	/**
	 * Returns the ma don vi tiep nhan of this ho so truc tuyen.
	 *
	 * @return the ma don vi tiep nhan of this ho so truc tuyen
	 */
	@AutoEscape
	public String getMaDonViTiepNhan();

	/**
	 * Sets the ma don vi tiep nhan of this ho so truc tuyen.
	 *
	 * @param MaDonViTiepNhan the ma don vi tiep nhan of this ho so truc tuyen
	 */
	public void setMaDonViTiepNhan(String MaDonViTiepNhan);

	/**
	 * Returns the ho ten nguoi nop of this ho so truc tuyen.
	 *
	 * @return the ho ten nguoi nop of this ho so truc tuyen
	 */
	@AutoEscape
	public String getHoTenNguoiNop();

	/**
	 * Sets the ho ten nguoi nop of this ho so truc tuyen.
	 *
	 * @param HoTenNguoiNop the ho ten nguoi nop of this ho so truc tuyen
	 */
	public void setHoTenNguoiNop(String HoTenNguoiNop);

	/**
	 * Returns the dia chi nguoi nop of this ho so truc tuyen.
	 *
	 * @return the dia chi nguoi nop of this ho so truc tuyen
	 */
	@AutoEscape
	public String getDiaChiNguoiNop();

	/**
	 * Sets the dia chi nguoi nop of this ho so truc tuyen.
	 *
	 * @param DiaChiNguoiNop the dia chi nguoi nop of this ho so truc tuyen
	 */
	public void setDiaChiNguoiNop(String DiaChiNguoiNop);

	/**
	 * Returns the ngay sinh of this ho so truc tuyen.
	 *
	 * @return the ngay sinh of this ho so truc tuyen
	 */
	public Date getNgaySinh();

	/**
	 * Sets the ngay sinh of this ho so truc tuyen.
	 *
	 * @param NgaySinh the ngay sinh of this ho so truc tuyen
	 */
	public void setNgaySinh(Date NgaySinh);

	/**
	 * Returns the so cmnd of this ho so truc tuyen.
	 *
	 * @return the so cmnd of this ho so truc tuyen
	 */
	@AutoEscape
	public String getSoCmnd();

	/**
	 * Sets the so cmnd of this ho so truc tuyen.
	 *
	 * @param SoCmnd the so cmnd of this ho so truc tuyen
	 */
	public void setSoCmnd(String SoCmnd);

	/**
	 * Returns the email of this ho so truc tuyen.
	 *
	 * @return the email of this ho so truc tuyen
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this ho so truc tuyen.
	 *
	 * @param Email the email of this ho so truc tuyen
	 */
	public void setEmail(String Email);

	/**
	 * Returns the so dt di dong of this ho so truc tuyen.
	 *
	 * @return the so dt di dong of this ho so truc tuyen
	 */
	@AutoEscape
	public String getSoDtDiDong();

	/**
	 * Sets the so dt di dong of this ho so truc tuyen.
	 *
	 * @param SoDtDiDong the so dt di dong of this ho so truc tuyen
	 */
	public void setSoDtDiDong(String SoDtDiDong);

	/**
	 * Returns the so dt co dinh of this ho so truc tuyen.
	 *
	 * @return the so dt co dinh of this ho so truc tuyen
	 */
	@AutoEscape
	public String getSoDtCoDinh();

	/**
	 * Sets the so dt co dinh of this ho so truc tuyen.
	 *
	 * @param SoDtCoDinh the so dt co dinh of this ho so truc tuyen
	 */
	public void setSoDtCoDinh(String SoDtCoDinh);

	/**
	 * Returns the ngay dang ky ho so of this ho so truc tuyen.
	 *
	 * @return the ngay dang ky ho so of this ho so truc tuyen
	 */
	public Date getNgayDangKyHoSo();

	/**
	 * Sets the ngay dang ky ho so of this ho so truc tuyen.
	 *
	 * @param NgayDangKyHoSo the ngay dang ky ho so of this ho so truc tuyen
	 */
	public void setNgayDangKyHoSo(Date NgayDangKyHoSo);

	/**
	 * Returns the noi chuyen ho so of this ho so truc tuyen.
	 *
	 * @return the noi chuyen ho so of this ho so truc tuyen
	 */
	@AutoEscape
	public String getNoiChuyenHoSo();

	/**
	 * Sets the noi chuyen ho so of this ho so truc tuyen.
	 *
	 * @param NoiChuyenHoSo the noi chuyen ho so of this ho so truc tuyen
	 */
	public void setNoiChuyenHoSo(String NoiChuyenHoSo);

	/**
	 * Returns the trang thai xu ly of this ho so truc tuyen.
	 *
	 * @return the trang thai xu ly of this ho so truc tuyen
	 */
	public int getTrangThaiXuLy();

	/**
	 * Sets the trang thai xu ly of this ho so truc tuyen.
	 *
	 * @param TrangThaiXuLy the trang thai xu ly of this ho so truc tuyen
	 */
	public void setTrangThaiXuLy(int TrangThaiXuLy);

	/**
	 * Returns the ngay chuyen of this ho so truc tuyen.
	 *
	 * @return the ngay chuyen of this ho so truc tuyen
	 */
	public Date getNgayChuyen();

	/**
	 * Sets the ngay chuyen of this ho so truc tuyen.
	 *
	 * @param NgayChuyen the ngay chuyen of this ho so truc tuyen
	 */
	public void setNgayChuyen(Date NgayChuyen);

	/**
	 * Returns the gioi tinh of this ho so truc tuyen.
	 *
	 * @return the gioi tinh of this ho so truc tuyen
	 */
	public int getGioiTinh();

	/**
	 * Sets the gioi tinh of this ho so truc tuyen.
	 *
	 * @param GioiTinh the gioi tinh of this ho so truc tuyen
	 */
	public void setGioiTinh(int GioiTinh);

	/**
	 * Returns the chu so huu ho so of this ho so truc tuyen.
	 *
	 * @return the chu so huu ho so of this ho so truc tuyen
	 */
	@AutoEscape
	public String getChuSoHuuHoSo();

	/**
	 * Sets the chu so huu ho so of this ho so truc tuyen.
	 *
	 * @param ChuSoHuuHoSo the chu so huu ho so of this ho so truc tuyen
	 */
	public void setChuSoHuuHoSo(String ChuSoHuuHoSo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HoSoTrucTuyen hoSoTrucTuyen);

	public int hashCode();

	public CacheModel<HoSoTrucTuyen> toCacheModel();

	public HoSoTrucTuyen toEscapedModel();

	public String toString();

	public String toXmlString();
}