/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KetQuaHoso service. Represents a row in the &quot;exch_ketquahoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.exch.dao.hoso.model.impl.KetQuaHosoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.exch.dao.hoso.model.impl.KetQuaHosoImpl}.
 * </p>
 *
 * @author NAM
 * @see KetQuaHoso
 * @see org.oep.exch.dao.hoso.model.impl.KetQuaHosoImpl
 * @see org.oep.exch.dao.hoso.model.impl.KetQuaHosoModelImpl
 * @generated
 */
public interface KetQuaHosoModel extends BaseModel<KetQuaHoso> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ket qua hoso model instance should use the {@link KetQuaHoso} interface instead.
	 */

	/**
	 * Returns the primary key of this ket qua hoso.
	 *
	 * @return the primary key of this ket qua hoso
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ket qua hoso.
	 *
	 * @param primaryKey the primary key of this ket qua hoso
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ket qua hoso.
	 *
	 * @return the ID of this ket qua hoso
	 */
	public long getId();

	/**
	 * Sets the ID of this ket qua hoso.
	 *
	 * @param id the ID of this ket qua hoso
	 */
	public void setId(long id);

	/**
	 * Returns the ngay chuyen of this ket qua hoso.
	 *
	 * @return the ngay chuyen of this ket qua hoso
	 */
	public Date getNgayChuyen();

	/**
	 * Sets the ngay chuyen of this ket qua hoso.
	 *
	 * @param NgayChuyen the ngay chuyen of this ket qua hoso
	 */
	public void setNgayChuyen(Date NgayChuyen);

	/**
	 * Returns the ma so ho so of this ket qua hoso.
	 *
	 * @return the ma so ho so of this ket qua hoso
	 */
	@AutoEscape
	public String getMaSoHoSo();

	/**
	 * Sets the ma so ho so of this ket qua hoso.
	 *
	 * @param MaSoHoSo the ma so ho so of this ket qua hoso
	 */
	public void setMaSoHoSo(String MaSoHoSo);

	/**
	 * Returns the ten nguoi nhan ket qua of this ket qua hoso.
	 *
	 * @return the ten nguoi nhan ket qua of this ket qua hoso
	 */
	@AutoEscape
	public String getTenNguoiNhanKetQua();

	/**
	 * Sets the ten nguoi nhan ket qua of this ket qua hoso.
	 *
	 * @param TenNguoiNhanKetQua the ten nguoi nhan ket qua of this ket qua hoso
	 */
	public void setTenNguoiNhanKetQua(String TenNguoiNhanKetQua);

	/**
	 * Returns the ngay nhan ket qua of this ket qua hoso.
	 *
	 * @return the ngay nhan ket qua of this ket qua hoso
	 */
	@AutoEscape
	public String getNgayNhanKetQua();

	/**
	 * Sets the ngay nhan ket qua of this ket qua hoso.
	 *
	 * @param NgayNhanKetQua the ngay nhan ket qua of this ket qua hoso
	 */
	public void setNgayNhanKetQua(String NgayNhanKetQua);

	/**
	 * Returns the le phi ho so of this ket qua hoso.
	 *
	 * @return the le phi ho so of this ket qua hoso
	 */
	public int getLePhiHoSo();

	/**
	 * Sets the le phi ho so of this ket qua hoso.
	 *
	 * @param LePhiHoSo the le phi ho so of this ket qua hoso
	 */
	public void setLePhiHoSo(int LePhiHoSo);

	/**
	 * Returns the phi xu ly ho so of this ket qua hoso.
	 *
	 * @return the phi xu ly ho so of this ket qua hoso
	 */
	public int getPhiXuLyHoSo();

	/**
	 * Sets the phi xu ly ho so of this ket qua hoso.
	 *
	 * @param PhiXuLyHoSo the phi xu ly ho so of this ket qua hoso
	 */
	public void setPhiXuLyHoSo(int PhiXuLyHoSo);

	/**
	 * Returns the ngay hoan thanh of this ket qua hoso.
	 *
	 * @return the ngay hoan thanh of this ket qua hoso
	 */
	@AutoEscape
	public String getNgayHoanThanh();

	/**
	 * Sets the ngay hoan thanh of this ket qua hoso.
	 *
	 * @param NgayHoanThanh the ngay hoan thanh of this ket qua hoso
	 */
	public void setNgayHoanThanh(String NgayHoanThanh);

	/**
	 * Returns the ma can bo tra ket qua of this ket qua hoso.
	 *
	 * @return the ma can bo tra ket qua of this ket qua hoso
	 */
	@AutoEscape
	public String getMaCanBoTraKetQua();

	/**
	 * Sets the ma can bo tra ket qua of this ket qua hoso.
	 *
	 * @param MaCanBoTraKetQua the ma can bo tra ket qua of this ket qua hoso
	 */
	public void setMaCanBoTraKetQua(String MaCanBoTraKetQua);

	/**
	 * Returns the ten can bo tra ket qua of this ket qua hoso.
	 *
	 * @return the ten can bo tra ket qua of this ket qua hoso
	 */
	@AutoEscape
	public String getTenCanBoTraKetQua();

	/**
	 * Sets the ten can bo tra ket qua of this ket qua hoso.
	 *
	 * @param TenCanBoTraKetQua the ten can bo tra ket qua of this ket qua hoso
	 */
	public void setTenCanBoTraKetQua(String TenCanBoTraKetQua);

	/**
	 * Returns the don vi cung cap of this ket qua hoso.
	 *
	 * @return the don vi cung cap of this ket qua hoso
	 */
	@AutoEscape
	public String getDonViCungCap();

	/**
	 * Sets the don vi cung cap of this ket qua hoso.
	 *
	 * @param DonViCungCap the don vi cung cap of this ket qua hoso
	 */
	public void setDonViCungCap(String DonViCungCap);

	/**
	 * Returns the trang thai xu ly of this ket qua hoso.
	 *
	 * @return the trang thai xu ly of this ket qua hoso
	 */
	public int getTrangThaiXuLy();

	/**
	 * Sets the trang thai xu ly of this ket qua hoso.
	 *
	 * @param TrangThaiXuLy the trang thai xu ly of this ket qua hoso
	 */
	public void setTrangThaiXuLy(int TrangThaiXuLy);

	/**
	 * Returns the ngay xu ly of this ket qua hoso.
	 *
	 * @return the ngay xu ly of this ket qua hoso
	 */
	public Date getNgayXuLy();

	/**
	 * Sets the ngay xu ly of this ket qua hoso.
	 *
	 * @param NgayXuLy the ngay xu ly of this ket qua hoso
	 */
	public void setNgayXuLy(Date NgayXuLy);

	/**
	 * Returns the loi khi xu ly of this ket qua hoso.
	 *
	 * @return the loi khi xu ly of this ket qua hoso
	 */
	@AutoEscape
	public String getLoiKhiXuLy();

	/**
	 * Sets the loi khi xu ly of this ket qua hoso.
	 *
	 * @param LoiKhiXuLy the loi khi xu ly of this ket qua hoso
	 */
	public void setLoiKhiXuLy(String LoiKhiXuLy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(KetQuaHoso ketQuaHoso);

	public int hashCode();

	public CacheModel<KetQuaHoso> toCacheModel();

	public KetQuaHoso toEscapedModel();

	public String toString();

	public String toXmlString();
}