/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.cc.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.oep.cmon.dao.cc.model.CongChuc;
import org.oep.cmon.dao.cc.service.ChucVuLocalService;
import org.oep.cmon.dao.cc.service.CongChuc2NhomThuTucLocalService;
import org.oep.cmon.dao.cc.service.CongChucLocalService;
import org.oep.cmon.dao.cc.service.persistence.ChucVuFinder;
import org.oep.cmon.dao.cc.service.persistence.ChucVuPersistence;
import org.oep.cmon.dao.cc.service.persistence.CongChuc2NhomThuTucPersistence;
import org.oep.cmon.dao.cc.service.persistence.CongChucFinder;
import org.oep.cmon.dao.cc.service.persistence.CongChucPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the cong chuc local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.oep.cmon.dao.cc.service.impl.CongChucLocalServiceImpl}.
 * </p>
 *
 * @author Liemnn
 * @see org.oep.cmon.dao.cc.service.impl.CongChucLocalServiceImpl
 * @see org.oep.cmon.dao.cc.service.CongChucLocalServiceUtil
 * @generated
 */
public abstract class CongChucLocalServiceBaseImpl
	implements CongChucLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.oep.cmon.dao.cc.service.CongChucLocalServiceUtil} to access the cong chuc local service.
	 */

	/**
	 * Adds the cong chuc to the database. Also notifies the appropriate model listeners.
	 *
	 * @param congChuc the cong chuc
	 * @return the cong chuc that was added
	 * @throws SystemException if a system exception occurred
	 */
	public CongChuc addCongChuc(CongChuc congChuc) throws SystemException {
		congChuc.setNew(true);

		congChuc = congChucPersistence.update(congChuc, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(congChuc);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return congChuc;
	}

	/**
	 * Creates a new cong chuc with the primary key. Does not add the cong chuc to the database.
	 *
	 * @param id the primary key for the new cong chuc
	 * @return the new cong chuc
	 */
	public CongChuc createCongChuc(long id) {
		return congChucPersistence.create(id);
	}

	/**
	 * Deletes the cong chuc with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the cong chuc
	 * @throws PortalException if a cong chuc with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteCongChuc(long id) throws PortalException, SystemException {
		CongChuc congChuc = congChucPersistence.remove(id);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(congChuc);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the cong chuc from the database. Also notifies the appropriate model listeners.
	 *
	 * @param congChuc the cong chuc
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteCongChuc(CongChuc congChuc) throws SystemException {
		congChucPersistence.remove(congChuc);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(congChuc);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return congChucPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return congChucPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return congChucPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return congChucPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public CongChuc fetchCongChuc(long id) throws SystemException {
		return congChucPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the cong chuc with the primary key.
	 *
	 * @param id the primary key of the cong chuc
	 * @return the cong chuc
	 * @throws PortalException if a cong chuc with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public CongChuc getCongChuc(long id)
		throws PortalException, SystemException {
		return congChucPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return congChucPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the cong chucs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of cong chucs
	 * @param end the upper bound of the range of cong chucs (not inclusive)
	 * @return the range of cong chucs
	 * @throws SystemException if a system exception occurred
	 */
	public List<CongChuc> getCongChucs(int start, int end)
		throws SystemException {
		return congChucPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cong chucs.
	 *
	 * @return the number of cong chucs
	 * @throws SystemException if a system exception occurred
	 */
	public int getCongChucsCount() throws SystemException {
		return congChucPersistence.countAll();
	}

	/**
	 * Updates the cong chuc in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param congChuc the cong chuc
	 * @return the cong chuc that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public CongChuc updateCongChuc(CongChuc congChuc) throws SystemException {
		return updateCongChuc(congChuc, true);
	}

	/**
	 * Updates the cong chuc in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param congChuc the cong chuc
	 * @param merge whether to merge the cong chuc with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the cong chuc that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public CongChuc updateCongChuc(CongChuc congChuc, boolean merge)
		throws SystemException {
		congChuc.setNew(false);

		congChuc = congChucPersistence.update(congChuc, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(congChuc);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return congChuc;
	}

	/**
	 * Returns the chuc vu local service.
	 *
	 * @return the chuc vu local service
	 */
	public ChucVuLocalService getChucVuLocalService() {
		return chucVuLocalService;
	}

	/**
	 * Sets the chuc vu local service.
	 *
	 * @param chucVuLocalService the chuc vu local service
	 */
	public void setChucVuLocalService(ChucVuLocalService chucVuLocalService) {
		this.chucVuLocalService = chucVuLocalService;
	}

	/**
	 * Returns the chuc vu persistence.
	 *
	 * @return the chuc vu persistence
	 */
	public ChucVuPersistence getChucVuPersistence() {
		return chucVuPersistence;
	}

	/**
	 * Sets the chuc vu persistence.
	 *
	 * @param chucVuPersistence the chuc vu persistence
	 */
	public void setChucVuPersistence(ChucVuPersistence chucVuPersistence) {
		this.chucVuPersistence = chucVuPersistence;
	}

	/**
	 * Returns the chuc vu finder.
	 *
	 * @return the chuc vu finder
	 */
	public ChucVuFinder getChucVuFinder() {
		return chucVuFinder;
	}

	/**
	 * Sets the chuc vu finder.
	 *
	 * @param chucVuFinder the chuc vu finder
	 */
	public void setChucVuFinder(ChucVuFinder chucVuFinder) {
		this.chucVuFinder = chucVuFinder;
	}

	/**
	 * Returns the cong chuc local service.
	 *
	 * @return the cong chuc local service
	 */
	public CongChucLocalService getCongChucLocalService() {
		return congChucLocalService;
	}

	/**
	 * Sets the cong chuc local service.
	 *
	 * @param congChucLocalService the cong chuc local service
	 */
	public void setCongChucLocalService(
		CongChucLocalService congChucLocalService) {
		this.congChucLocalService = congChucLocalService;
	}

	/**
	 * Returns the cong chuc persistence.
	 *
	 * @return the cong chuc persistence
	 */
	public CongChucPersistence getCongChucPersistence() {
		return congChucPersistence;
	}

	/**
	 * Sets the cong chuc persistence.
	 *
	 * @param congChucPersistence the cong chuc persistence
	 */
	public void setCongChucPersistence(CongChucPersistence congChucPersistence) {
		this.congChucPersistence = congChucPersistence;
	}

	/**
	 * Returns the cong chuc finder.
	 *
	 * @return the cong chuc finder
	 */
	public CongChucFinder getCongChucFinder() {
		return congChucFinder;
	}

	/**
	 * Sets the cong chuc finder.
	 *
	 * @param congChucFinder the cong chuc finder
	 */
	public void setCongChucFinder(CongChucFinder congChucFinder) {
		this.congChucFinder = congChucFinder;
	}

	/**
	 * Returns the cong chuc2 nhom thu tuc local service.
	 *
	 * @return the cong chuc2 nhom thu tuc local service
	 */
	public CongChuc2NhomThuTucLocalService getCongChuc2NhomThuTucLocalService() {
		return congChuc2NhomThuTucLocalService;
	}

	/**
	 * Sets the cong chuc2 nhom thu tuc local service.
	 *
	 * @param congChuc2NhomThuTucLocalService the cong chuc2 nhom thu tuc local service
	 */
	public void setCongChuc2NhomThuTucLocalService(
		CongChuc2NhomThuTucLocalService congChuc2NhomThuTucLocalService) {
		this.congChuc2NhomThuTucLocalService = congChuc2NhomThuTucLocalService;
	}

	/**
	 * Returns the cong chuc2 nhom thu tuc persistence.
	 *
	 * @return the cong chuc2 nhom thu tuc persistence
	 */
	public CongChuc2NhomThuTucPersistence getCongChuc2NhomThuTucPersistence() {
		return congChuc2NhomThuTucPersistence;
	}

	/**
	 * Sets the cong chuc2 nhom thu tuc persistence.
	 *
	 * @param congChuc2NhomThuTucPersistence the cong chuc2 nhom thu tuc persistence
	 */
	public void setCongChuc2NhomThuTucPersistence(
		CongChuc2NhomThuTucPersistence congChuc2NhomThuTucPersistence) {
		this.congChuc2NhomThuTucPersistence = congChuc2NhomThuTucPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.oep.cmon.dao.cc.model.CongChuc",
			congChucLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.oep.cmon.dao.cc.model.CongChuc");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return CongChuc.class;
	}

	protected String getModelClassName() {
		return CongChuc.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = congChucPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ChucVuLocalService.class)
	protected ChucVuLocalService chucVuLocalService;
	@BeanReference(type = ChucVuPersistence.class)
	protected ChucVuPersistence chucVuPersistence;
	@BeanReference(type = ChucVuFinder.class)
	protected ChucVuFinder chucVuFinder;
	@BeanReference(type = CongChucLocalService.class)
	protected CongChucLocalService congChucLocalService;
	@BeanReference(type = CongChucPersistence.class)
	protected CongChucPersistence congChucPersistence;
	@BeanReference(type = CongChucFinder.class)
	protected CongChucFinder congChucFinder;
	@BeanReference(type = CongChuc2NhomThuTucLocalService.class)
	protected CongChuc2NhomThuTucLocalService congChuc2NhomThuTucLocalService;
	@BeanReference(type = CongChuc2NhomThuTucPersistence.class)
	protected CongChuc2NhomThuTucPersistence congChuc2NhomThuTucPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(CongChucLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}