/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.job.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DanhSachJob service. Represents a row in the &quot;JOB_DANHSACHJOB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.job.model.impl.DanhSachJobModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.job.model.impl.DanhSachJobImpl}.
 * </p>
 *
 * @author BinhNT
 * @see DanhSachJob
 * @see org.oep.cmon.dao.job.model.impl.DanhSachJobImpl
 * @see org.oep.cmon.dao.job.model.impl.DanhSachJobModelImpl
 * @generated
 */
public interface DanhSachJobModel extends BaseModel<DanhSachJob> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danh sach job model instance should use the {@link DanhSachJob} interface instead.
	 */

	/**
	 * Returns the primary key of this danh sach job.
	 *
	 * @return the primary key of this danh sach job
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this danh sach job.
	 *
	 * @param primaryKey the primary key of this danh sach job
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the i d of this danh sach job.
	 *
	 * @return the i d of this danh sach job
	 */
	public long getID();

	/**
	 * Sets the i d of this danh sach job.
	 *
	 * @param ID the i d of this danh sach job
	 */
	public void setID(long ID);

	/**
	 * Returns the job class of this danh sach job.
	 *
	 * @return the job class of this danh sach job
	 */
	@AutoEscape
	public String getJobClass();

	/**
	 * Sets the job class of this danh sach job.
	 *
	 * @param JobClass the job class of this danh sach job
	 */
	public void setJobClass(String JobClass);

	/**
	 * Returns the job ID of this danh sach job.
	 *
	 * @return the job ID of this danh sach job
	 */
	public int getJobId();

	/**
	 * Sets the job ID of this danh sach job.
	 *
	 * @param JobId the job ID of this danh sach job
	 */
	public void setJobId(int JobId);

	/**
	 * Returns the job name of this danh sach job.
	 *
	 * @return the job name of this danh sach job
	 */
	@AutoEscape
	public String getJobName();

	/**
	 * Sets the job name of this danh sach job.
	 *
	 * @param JobName the job name of this danh sach job
	 */
	public void setJobName(String JobName);

	/**
	 * Returns the description of this danh sach job.
	 *
	 * @return the description of this danh sach job
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this danh sach job.
	 *
	 * @param Description the description of this danh sach job
	 */
	public void setDescription(String Description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DanhSachJob danhSachJob);

	public int hashCode();

	public CacheModel<DanhSachJob> toCacheModel();

	public DanhSachJob toEscapedModel();

	public String toString();

	public String toXmlString();
}