/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.job.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TrangThaiJob service. Represents a row in the &quot;JOB_TRANGTHAIJOB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.job.model.impl.TrangThaiJobModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.job.model.impl.TrangThaiJobImpl}.
 * </p>
 *
 * @author BinhNT
 * @see TrangThaiJob
 * @see org.oep.cmon.dao.job.model.impl.TrangThaiJobImpl
 * @see org.oep.cmon.dao.job.model.impl.TrangThaiJobModelImpl
 * @generated
 */
public interface TrangThaiJobModel extends BaseModel<TrangThaiJob> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trang thai job model instance should use the {@link TrangThaiJob} interface instead.
	 */

	/**
	 * Returns the primary key of this trang thai job.
	 *
	 * @return the primary key of this trang thai job
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trang thai job.
	 *
	 * @param primaryKey the primary key of this trang thai job
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the i d of this trang thai job.
	 *
	 * @return the i d of this trang thai job
	 */
	public long getID();

	/**
	 * Sets the i d of this trang thai job.
	 *
	 * @param ID the i d of this trang thai job
	 */
	public void setID(long ID);

	/**
	 * Returns the job ID of this trang thai job.
	 *
	 * @return the job ID of this trang thai job
	 */
	public int getJobId();

	/**
	 * Sets the job ID of this trang thai job.
	 *
	 * @param JobId the job ID of this trang thai job
	 */
	public void setJobId(int JobId);

	/**
	 * Returns the job name of this trang thai job.
	 *
	 * @return the job name of this trang thai job
	 */
	@AutoEscape
	public String getJobName();

	/**
	 * Sets the job name of this trang thai job.
	 *
	 * @param JobName the job name of this trang thai job
	 */
	public void setJobName(String JobName);

	/**
	 * Returns the start time of this trang thai job.
	 *
	 * @return the start time of this trang thai job
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this trang thai job.
	 *
	 * @param StartTime the start time of this trang thai job
	 */
	public void setStartTime(Date StartTime);

	/**
	 * Returns the end time of this trang thai job.
	 *
	 * @return the end time of this trang thai job
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this trang thai job.
	 *
	 * @param EndTime the end time of this trang thai job
	 */
	public void setEndTime(Date EndTime);

	/**
	 * Returns the status of this trang thai job.
	 *
	 * @return the status of this trang thai job
	 */
	public int getStatus();

	/**
	 * Sets the status of this trang thai job.
	 *
	 * @param Status the status of this trang thai job
	 */
	public void setStatus(int Status);

	/**
	 * Returns the run mode of this trang thai job.
	 *
	 * @return the run mode of this trang thai job
	 */
	public int getRunMode();

	/**
	 * Sets the run mode of this trang thai job.
	 *
	 * @param RunMode the run mode of this trang thai job
	 */
	public void setRunMode(int RunMode);

	/**
	 * Returns the message of this trang thai job.
	 *
	 * @return the message of this trang thai job
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this trang thai job.
	 *
	 * @param Message the message of this trang thai job
	 */
	public void setMessage(String Message);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TrangThaiJob trangThaiJob);

	public int hashCode();

	public CacheModel<TrangThaiJob> toCacheModel();

	public TrangThaiJob toEscapedModel();

	public String toString();

	public String toXmlString();
}