
package org.oep.sharedservice.touchscreen.tracuutthc;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-07-21T12:17:29.513+07:00
 * Generated source version: 2.6.1
 * 
 */
 
public class TraCuuTTHCServiceServer{

    protected TraCuuTTHCServiceServer() throws Exception {
        Object implementor = new org.oep.sharedservice.touchscreen.tracuutthc.TraCuuTTHCImpl();
        String address = "http://localhost:9090/TraCuuTTHCImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new TraCuuTTHCServiceServer();
        
        Thread.sleep(5 * 60 * 1000); 
        System.exit(0);
    }
}
 
 