/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.hosohcc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FileDinhKem service. Represents a row in the &quot;CMON_GIAYTODINHKEMHOSO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.hosohcc.model.impl.FileDinhKemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.hosohcc.model.impl.FileDinhKemImpl}.
 * </p>
 *
 * @author LIEMNn
 * @see FileDinhKem
 * @see org.oep.cmon.dao.hosohcc.model.impl.FileDinhKemImpl
 * @see org.oep.cmon.dao.hosohcc.model.impl.FileDinhKemModelImpl
 * @generated
 */
public interface FileDinhKemModel extends BaseModel<FileDinhKem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file dinh kem model instance should use the {@link FileDinhKem} interface instead.
	 */

	/**
	 * Returns the primary key of this file dinh kem.
	 *
	 * @return the primary key of this file dinh kem
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file dinh kem.
	 *
	 * @param primaryKey the primary key of this file dinh kem
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this file dinh kem.
	 *
	 * @return the ID of this file dinh kem
	 */
	public long getId();

	/**
	 * Sets the ID of this file dinh kem.
	 *
	 * @param id the ID of this file dinh kem
	 */
	public void setId(long id);

	/**
	 * Returns the so ban giay of this file dinh kem.
	 *
	 * @return the so ban giay of this file dinh kem
	 */
	public long getSoBanGiay();

	/**
	 * Sets the so ban giay of this file dinh kem.
	 *
	 * @param soBanGiay the so ban giay of this file dinh kem
	 */
	public void setSoBanGiay(long soBanGiay);

	/**
	 * Returns the da doi chieu of this file dinh kem.
	 *
	 * @return the da doi chieu of this file dinh kem
	 */
	public int getDaDoiChieu();

	/**
	 * Sets the da doi chieu of this file dinh kem.
	 *
	 * @param daDoiChieu the da doi chieu of this file dinh kem
	 */
	public void setDaDoiChieu(int daDoiChieu);

	/**
	 * Returns the trang thai ho so tai thoi diem dinh kem of this file dinh kem.
	 *
	 * @return the trang thai ho so tai thoi diem dinh kem of this file dinh kem
	 */
	public int getTrangThaiHoSoTaiThoiDiemDinhKem();

	/**
	 * Sets the trang thai ho so tai thoi diem dinh kem of this file dinh kem.
	 *
	 * @param trangThaiHoSoTaiThoiDiemDinhKem the trang thai ho so tai thoi diem dinh kem of this file dinh kem
	 */
	public void setTrangThaiHoSoTaiThoiDiemDinhKem(
		int trangThaiHoSoTaiThoiDiemDinhKem);

	/**
	 * Returns the noi luu tru tai lieu ID of this file dinh kem.
	 *
	 * @return the noi luu tru tai lieu ID of this file dinh kem
	 */
	public Long getNoiLuuTruTaiLieuId();

	/**
	 * Sets the noi luu tru tai lieu ID of this file dinh kem.
	 *
	 * @param noiLuuTruTaiLieuId the noi luu tru tai lieu ID of this file dinh kem
	 */
	public void setNoiLuuTruTaiLieuId(Long noiLuuTruTaiLieuId);

	/**
	 * Returns the can bo ID of this file dinh kem.
	 *
	 * @return the can bo ID of this file dinh kem
	 */
	public Long getCanBoId();

	/**
	 * Sets the can bo ID of this file dinh kem.
	 *
	 * @param canBoId the can bo ID of this file dinh kem
	 */
	public void setCanBoId(Long canBoId);

	/**
	 * Returns the ho so t t h c cong ID of this file dinh kem.
	 *
	 * @return the ho so t t h c cong ID of this file dinh kem
	 */
	public Long getHoSoTTHCCongId();

	/**
	 * Sets the ho so t t h c cong ID of this file dinh kem.
	 *
	 * @param hoSoTTHCCongId the ho so t t h c cong ID of this file dinh kem
	 */
	public void setHoSoTTHCCongId(Long hoSoTTHCCongId);

	/**
	 * Returns the thu tuc2 giay to ID of this file dinh kem.
	 *
	 * @return the thu tuc2 giay to ID of this file dinh kem
	 */
	public Long getThuTuc2GiayToId();

	/**
	 * Sets the thu tuc2 giay to ID of this file dinh kem.
	 *
	 * @param thuTuc2GiayToId the thu tuc2 giay to ID of this file dinh kem
	 */
	public void setThuTuc2GiayToId(Long thuTuc2GiayToId);

	/**
	 * Returns the danh muc giay to ID of this file dinh kem.
	 *
	 * @return the danh muc giay to ID of this file dinh kem
	 */
	public Long getDanhMucGiayToId();

	/**
	 * Sets the danh muc giay to ID of this file dinh kem.
	 *
	 * @param danhMucGiayToId the danh muc giay to ID of this file dinh kem
	 */
	public void setDanhMucGiayToId(Long danhMucGiayToId);

	/**
	 * Returns the ngay upload of this file dinh kem.
	 *
	 * @return the ngay upload of this file dinh kem
	 */
	public Date getNgayUpload();

	/**
	 * Sets the ngay upload of this file dinh kem.
	 *
	 * @param ngayUpload the ngay upload of this file dinh kem
	 */
	public void setNgayUpload(Date ngayUpload);

	/**
	 * Returns the ngay sua of this file dinh kem.
	 *
	 * @return the ngay sua of this file dinh kem
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this file dinh kem.
	 *
	 * @param ngaySua the ngay sua of this file dinh kem
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi upload of this file dinh kem.
	 *
	 * @return the nguoi upload of this file dinh kem
	 */
	@AutoEscape
	public String getNguoiUpload();

	/**
	 * Sets the nguoi upload of this file dinh kem.
	 *
	 * @param nguoiUpload the nguoi upload of this file dinh kem
	 */
	public void setNguoiUpload(String nguoiUpload);

	/**
	 * Returns the ma loai tai lieu duoc thay the of this file dinh kem.
	 *
	 * @return the ma loai tai lieu duoc thay the of this file dinh kem
	 */
	@AutoEscape
	public String getMaLoaiTaiLieuDuocThayThe();

	/**
	 * Sets the ma loai tai lieu duoc thay the of this file dinh kem.
	 *
	 * @param maLoaiTaiLieuDuocThayThe the ma loai tai lieu duoc thay the of this file dinh kem
	 */
	public void setMaLoaiTaiLieuDuocThayThe(String maLoaiTaiLieuDuocThayThe);

	/**
	 * Returns the nguoi sua of this file dinh kem.
	 *
	 * @return the nguoi sua of this file dinh kem
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this file dinh kem.
	 *
	 * @param nguoiSua the nguoi sua of this file dinh kem
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the xoa of this file dinh kem.
	 *
	 * @return the xoa of this file dinh kem
	 */
	public int getXoa();

	/**
	 * Sets the xoa of this file dinh kem.
	 *
	 * @param xoa the xoa of this file dinh kem
	 */
	public void setXoa(int xoa);

	/**
	 * Returns the da tra of this file dinh kem.
	 *
	 * @return the da tra of this file dinh kem
	 */
	public int getDaTra();

	/**
	 * Sets the da tra of this file dinh kem.
	 *
	 * @param daTra the da tra of this file dinh kem
	 */
	public void setDaTra(int daTra);

	/**
	 * Returns the ban chinh of this file dinh kem.
	 *
	 * @return the ban chinh of this file dinh kem
	 */
	public long getBanChinh();

	/**
	 * Sets the ban chinh of this file dinh kem.
	 *
	 * @param banChinh the ban chinh of this file dinh kem
	 */
	public void setBanChinh(long banChinh);

	/**
	 * Returns the ghi chu of this file dinh kem.
	 *
	 * @return the ghi chu of this file dinh kem
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this file dinh kem.
	 *
	 * @param ghiChu the ghi chu of this file dinh kem
	 */
	public void setGhiChu(String ghiChu);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FileDinhKem fileDinhKem);

	public int hashCode();

	public CacheModel<FileDinhKem> toCacheModel();

	public FileDinhKem toEscapedModel();

	public String toString();

	public String toXmlString();
}