/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.hosohcc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HoSoAnhXa service. Represents a row in the &quot;CMON_HOSOANHXA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.hosohcc.model.impl.HoSoAnhXaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.hosohcc.model.impl.HoSoAnhXaImpl}.
 * </p>
 *
 * @author LIEMNn
 * @see HoSoAnhXa
 * @see org.oep.cmon.dao.hosohcc.model.impl.HoSoAnhXaImpl
 * @see org.oep.cmon.dao.hosohcc.model.impl.HoSoAnhXaModelImpl
 * @generated
 */
public interface HoSoAnhXaModel extends BaseModel<HoSoAnhXa> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ho so anh xa model instance should use the {@link HoSoAnhXa} interface instead.
	 */

	/**
	 * Returns the primary key of this ho so anh xa.
	 *
	 * @return the primary key of this ho so anh xa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ho so anh xa.
	 *
	 * @param primaryKey the primary key of this ho so anh xa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ho so anh xa.
	 *
	 * @return the ID of this ho so anh xa
	 */
	public long getId();

	/**
	 * Sets the ID of this ho so anh xa.
	 *
	 * @param id the ID of this ho so anh xa
	 */
	public void setId(long id);

	/**
	 * Returns the ho so t t h c cong ID of this ho so anh xa.
	 *
	 * @return the ho so t t h c cong ID of this ho so anh xa
	 */
	public long getHoSoTTHCCongId();

	/**
	 * Sets the ho so t t h c cong ID of this ho so anh xa.
	 *
	 * @param hoSoTTHCCongId the ho so t t h c cong ID of this ho so anh xa
	 */
	public void setHoSoTTHCCongId(long hoSoTTHCCongId);

	/**
	 * Returns the ma ho so of this ho so anh xa.
	 *
	 * @return the ma ho so of this ho so anh xa
	 */
	@AutoEscape
	public String getMaHoSo();

	/**
	 * Sets the ma ho so of this ho so anh xa.
	 *
	 * @param maHoSo the ma ho so of this ho so anh xa
	 */
	public void setMaHoSo(String maHoSo);

	/**
	 * Returns the trang thai of this ho so anh xa.
	 *
	 * @return the trang thai of this ho so anh xa
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this ho so anh xa.
	 *
	 * @param trangThai the trang thai of this ho so anh xa
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the ngay sua of this ho so anh xa.
	 *
	 * @return the ngay sua of this ho so anh xa
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this ho so anh xa.
	 *
	 * @param ngaySua the ngay sua of this ho so anh xa
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the ngay tao of this ho so anh xa.
	 *
	 * @return the ngay tao of this ho so anh xa
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this ho so anh xa.
	 *
	 * @param ngayTao the ngay tao of this ho so anh xa
	 */
	public void setNgayTao(Date ngayTao);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HoSoAnhXa hoSoAnhXa);

	public int hashCode();

	public CacheModel<HoSoAnhXa> toCacheModel();

	public HoSoAnhXa toEscapedModel();

	public String toString();

	public String toXmlString();
}