/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.hosohcc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TrangThaiHoSo service. Represents a row in the &quot;CMON_TRANGTHAIHOSO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.hosohcc.model.impl.TrangThaiHoSoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.hosohcc.model.impl.TrangThaiHoSoImpl}.
 * </p>
 *
 * @author LIEMNn
 * @see TrangThaiHoSo
 * @see org.oep.cmon.dao.hosohcc.model.impl.TrangThaiHoSoImpl
 * @see org.oep.cmon.dao.hosohcc.model.impl.TrangThaiHoSoModelImpl
 * @generated
 */
public interface TrangThaiHoSoModel extends BaseModel<TrangThaiHoSo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trang thai ho so model instance should use the {@link TrangThaiHoSo} interface instead.
	 */

	/**
	 * Returns the primary key of this trang thai ho so.
	 *
	 * @return the primary key of this trang thai ho so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trang thai ho so.
	 *
	 * @param primaryKey the primary key of this trang thai ho so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this trang thai ho so.
	 *
	 * @return the ID of this trang thai ho so
	 */
	public long getId();

	/**
	 * Sets the ID of this trang thai ho so.
	 *
	 * @param id the ID of this trang thai ho so
	 */
	public void setId(long id);

	/**
	 * Returns the trang thai of this trang thai ho so.
	 *
	 * @return the trang thai of this trang thai ho so
	 */
	@AutoEscape
	public String getTrangThai();

	/**
	 * Sets the trang thai of this trang thai ho so.
	 *
	 * @param trangThai the trang thai of this trang thai ho so
	 */
	public void setTrangThai(String trangThai);

	/**
	 * Returns the nguoi tao of this trang thai ho so.
	 *
	 * @return the nguoi tao of this trang thai ho so
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this trang thai ho so.
	 *
	 * @param nguoiTao the nguoi tao of this trang thai ho so
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the ngay tao of this trang thai ho so.
	 *
	 * @return the ngay tao of this trang thai ho so
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this trang thai ho so.
	 *
	 * @param ngayTao the ngay tao of this trang thai ho so
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the nguoi sua of this trang thai ho so.
	 *
	 * @return the nguoi sua of this trang thai ho so
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this trang thai ho so.
	 *
	 * @param nguoiSua the nguoi sua of this trang thai ho so
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the ngay sua of this trang thai ho so.
	 *
	 * @return the ngay sua of this trang thai ho so
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this trang thai ho so.
	 *
	 * @param ngaySua the ngay sua of this trang thai ho so
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the da xoa of this trang thai ho so.
	 *
	 * @return the da xoa of this trang thai ho so
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this trang thai ho so.
	 *
	 * @param daXoa the da xoa of this trang thai ho so
	 */
	public void setDaXoa(int daXoa);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TrangThaiHoSo trangThaiHoSo);

	public int hashCode();

	public CacheModel<TrangThaiHoSo> toCacheModel();

	public TrangThaiHoSo toEscapedModel();

	public String toString();

	public String toXmlString();
}