/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.exch.dao.hoso.model.HoSoMotCua;
import org.oep.exch.dao.hoso.model.HoSoMotCuaModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the HoSoMotCua service. Represents a row in the &quot;exch_hosomotcua&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.exch.dao.hoso.model.HoSoMotCuaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HoSoMotCuaImpl}.
 * </p>
 *
 * @author NAM
 * @see HoSoMotCuaImpl
 * @see org.oep.exch.dao.hoso.model.HoSoMotCua
 * @see org.oep.exch.dao.hoso.model.HoSoMotCuaModel
 * @generated
 */
public class HoSoMotCuaModelImpl extends BaseModelImpl<HoSoMotCua>
	implements HoSoMotCuaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ho so mot cua model instance should use the {@link org.oep.exch.dao.hoso.model.HoSoMotCua} interface instead.
	 */
	public static final String TABLE_NAME = "exch_hosomotcua";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NgayChuyen", Types.TIMESTAMP },
			{ "MaSoHoSo", Types.VARCHAR },
			{ "MaLoaiHoSo", Types.VARCHAR },
			{ "MaDonViTiepNhan", Types.VARCHAR },
			{ "NgayNopHoSo", Types.VARCHAR },
			{ "NgayHenTra", Types.VARCHAR },
			{ "HoTenNguoiNop", Types.VARCHAR },
			{ "SoCmnd", Types.VARCHAR },
			{ "NgaySinh", Types.VARCHAR },
			{ "MaTinhThuongTru", Types.VARCHAR },
			{ "MoTaDiaChiThuongTru", Types.VARCHAR },
			{ "GioiTinh", Types.INTEGER },
			{ "MaNguoiTiepNhan", Types.VARCHAR },
			{ "TenNguoiTiepNhan", Types.VARCHAR },
			{ "DonViCungCap", Types.VARCHAR },
			{ "TrangThaiXuLy", Types.INTEGER },
			{ "NgayXuLy", Types.TIMESTAMP },
			{ "LoiKhiXuLy", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table exch_hosomotcua (ID LONG not null primary key,NgayChuyen DATE null,MaSoHoSo VARCHAR(75) null,MaLoaiHoSo VARCHAR(75) null,MaDonViTiepNhan VARCHAR(75) null,NgayNopHoSo VARCHAR(75) null,NgayHenTra VARCHAR(75) null,HoTenNguoiNop VARCHAR(75) null,SoCmnd VARCHAR(75) null,NgaySinh VARCHAR(75) null,MaTinhThuongTru VARCHAR(75) null,MoTaDiaChiThuongTru VARCHAR(75) null,GioiTinh INTEGER,MaNguoiTiepNhan VARCHAR(75) null,TenNguoiTiepNhan VARCHAR(75) null,DonViCungCap VARCHAR(75) null,TrangThaiXuLy INTEGER,NgayXuLy DATE null,LoiKhiXuLy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table exch_hosomotcua";
	public static final String ORDER_BY_JPQL = " ORDER BY hoSoMotCua.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY exch_hosomotcua.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.exch.dao.hoso.model.HoSoMotCua"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.exch.dao.hoso.model.HoSoMotCua"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.exch.dao.hoso.model.HoSoMotCua"),
			true);
	public static long MASOHOSO_COLUMN_BITMASK = 1L;
	public static long TRANGTHAIXULY_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.exch.dao.hoso.model.HoSoMotCua"));

	public HoSoMotCuaModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return HoSoMotCua.class;
	}

	public String getModelClassName() {
		return HoSoMotCua.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public Date getNgayChuyen() {
		return _NgayChuyen;
	}

	public void setNgayChuyen(Date NgayChuyen) {
		_NgayChuyen = NgayChuyen;
	}

	public String getMaSoHoSo() {
		if (_MaSoHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaSoHoSo;
		}
	}

	public void setMaSoHoSo(String MaSoHoSo) {
		_columnBitmask |= MASOHOSO_COLUMN_BITMASK;

		if (_originalMaSoHoSo == null) {
			_originalMaSoHoSo = _MaSoHoSo;
		}

		_MaSoHoSo = MaSoHoSo;
	}

	public String getOriginalMaSoHoSo() {
		return GetterUtil.getString(_originalMaSoHoSo);
	}

	public String getMaLoaiHoSo() {
		if (_MaLoaiHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaLoaiHoSo;
		}
	}

	public void setMaLoaiHoSo(String MaLoaiHoSo) {
		_MaLoaiHoSo = MaLoaiHoSo;
	}

	public String getMaDonViTiepNhan() {
		if (_MaDonViTiepNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaDonViTiepNhan;
		}
	}

	public void setMaDonViTiepNhan(String MaDonViTiepNhan) {
		_MaDonViTiepNhan = MaDonViTiepNhan;
	}

	public String getNgayNopHoSo() {
		if (_NgayNopHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _NgayNopHoSo;
		}
	}

	public void setNgayNopHoSo(String NgayNopHoSo) {
		_NgayNopHoSo = NgayNopHoSo;
	}

	public String getNgayHenTra() {
		if (_NgayHenTra == null) {
			return StringPool.BLANK;
		}
		else {
			return _NgayHenTra;
		}
	}

	public void setNgayHenTra(String NgayHenTra) {
		_NgayHenTra = NgayHenTra;
	}

	public String getHoTenNguoiNop() {
		if (_HoTenNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _HoTenNguoiNop;
		}
	}

	public void setHoTenNguoiNop(String HoTenNguoiNop) {
		_HoTenNguoiNop = HoTenNguoiNop;
	}

	public String getSoCmnd() {
		if (_SoCmnd == null) {
			return StringPool.BLANK;
		}
		else {
			return _SoCmnd;
		}
	}

	public void setSoCmnd(String SoCmnd) {
		_SoCmnd = SoCmnd;
	}

	public String getNgaySinh() {
		if (_NgaySinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _NgaySinh;
		}
	}

	public void setNgaySinh(String NgaySinh) {
		_NgaySinh = NgaySinh;
	}

	public String getMaTinhThuongTru() {
		if (_MaTinhThuongTru == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaTinhThuongTru;
		}
	}

	public void setMaTinhThuongTru(String MaTinhThuongTru) {
		_MaTinhThuongTru = MaTinhThuongTru;
	}

	public String getMoTaDiaChiThuongTru() {
		if (_MoTaDiaChiThuongTru == null) {
			return StringPool.BLANK;
		}
		else {
			return _MoTaDiaChiThuongTru;
		}
	}

	public void setMoTaDiaChiThuongTru(String MoTaDiaChiThuongTru) {
		_MoTaDiaChiThuongTru = MoTaDiaChiThuongTru;
	}

	public int getGioiTinh() {
		return _GioiTinh;
	}

	public void setGioiTinh(int GioiTinh) {
		_GioiTinh = GioiTinh;
	}

	public String getMaNguoiTiepNhan() {
		if (_MaNguoiTiepNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaNguoiTiepNhan;
		}
	}

	public void setMaNguoiTiepNhan(String MaNguoiTiepNhan) {
		_MaNguoiTiepNhan = MaNguoiTiepNhan;
	}

	public String getTenNguoiTiepNhan() {
		if (_TenNguoiTiepNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenNguoiTiepNhan;
		}
	}

	public void setTenNguoiTiepNhan(String TenNguoiTiepNhan) {
		_TenNguoiTiepNhan = TenNguoiTiepNhan;
	}

	public String getDonViCungCap() {
		if (_DonViCungCap == null) {
			return StringPool.BLANK;
		}
		else {
			return _DonViCungCap;
		}
	}

	public void setDonViCungCap(String DonViCungCap) {
		_DonViCungCap = DonViCungCap;
	}

	public int getTrangThaiXuLy() {
		return _TrangThaiXuLy;
	}

	public void setTrangThaiXuLy(int TrangThaiXuLy) {
		_columnBitmask |= TRANGTHAIXULY_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiXuLy) {
			_setOriginalTrangThaiXuLy = true;

			_originalTrangThaiXuLy = _TrangThaiXuLy;
		}

		_TrangThaiXuLy = TrangThaiXuLy;
	}

	public int getOriginalTrangThaiXuLy() {
		return _originalTrangThaiXuLy;
	}

	public Date getNgayXuLy() {
		return _NgayXuLy;
	}

	public void setNgayXuLy(Date NgayXuLy) {
		_NgayXuLy = NgayXuLy;
	}

	public String getLoiKhiXuLy() {
		if (_LoiKhiXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _LoiKhiXuLy;
		}
	}

	public void setLoiKhiXuLy(String LoiKhiXuLy) {
		_LoiKhiXuLy = LoiKhiXuLy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public HoSoMotCua toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (HoSoMotCua)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					HoSoMotCua.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		HoSoMotCuaImpl hoSoMotCuaImpl = new HoSoMotCuaImpl();

		hoSoMotCuaImpl.setId(getId());
		hoSoMotCuaImpl.setNgayChuyen(getNgayChuyen());
		hoSoMotCuaImpl.setMaSoHoSo(getMaSoHoSo());
		hoSoMotCuaImpl.setMaLoaiHoSo(getMaLoaiHoSo());
		hoSoMotCuaImpl.setMaDonViTiepNhan(getMaDonViTiepNhan());
		hoSoMotCuaImpl.setNgayNopHoSo(getNgayNopHoSo());
		hoSoMotCuaImpl.setNgayHenTra(getNgayHenTra());
		hoSoMotCuaImpl.setHoTenNguoiNop(getHoTenNguoiNop());
		hoSoMotCuaImpl.setSoCmnd(getSoCmnd());
		hoSoMotCuaImpl.setNgaySinh(getNgaySinh());
		hoSoMotCuaImpl.setMaTinhThuongTru(getMaTinhThuongTru());
		hoSoMotCuaImpl.setMoTaDiaChiThuongTru(getMoTaDiaChiThuongTru());
		hoSoMotCuaImpl.setGioiTinh(getGioiTinh());
		hoSoMotCuaImpl.setMaNguoiTiepNhan(getMaNguoiTiepNhan());
		hoSoMotCuaImpl.setTenNguoiTiepNhan(getTenNguoiTiepNhan());
		hoSoMotCuaImpl.setDonViCungCap(getDonViCungCap());
		hoSoMotCuaImpl.setTrangThaiXuLy(getTrangThaiXuLy());
		hoSoMotCuaImpl.setNgayXuLy(getNgayXuLy());
		hoSoMotCuaImpl.setLoiKhiXuLy(getLoiKhiXuLy());

		hoSoMotCuaImpl.resetOriginalValues();

		return hoSoMotCuaImpl;
	}

	public int compareTo(HoSoMotCua hoSoMotCua) {
		int value = 0;

		if (getId() < hoSoMotCua.getId()) {
			value = -1;
		}
		else if (getId() > hoSoMotCua.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		HoSoMotCua hoSoMotCua = null;

		try {
			hoSoMotCua = (HoSoMotCua)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = hoSoMotCua.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		HoSoMotCuaModelImpl hoSoMotCuaModelImpl = this;

		hoSoMotCuaModelImpl._originalMaSoHoSo = hoSoMotCuaModelImpl._MaSoHoSo;

		hoSoMotCuaModelImpl._originalTrangThaiXuLy = hoSoMotCuaModelImpl._TrangThaiXuLy;

		hoSoMotCuaModelImpl._setOriginalTrangThaiXuLy = false;

		hoSoMotCuaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<HoSoMotCua> toCacheModel() {
		HoSoMotCuaCacheModel hoSoMotCuaCacheModel = new HoSoMotCuaCacheModel();

		hoSoMotCuaCacheModel.id = getId();

		Date NgayChuyen = getNgayChuyen();

		if (NgayChuyen != null) {
			hoSoMotCuaCacheModel.NgayChuyen = NgayChuyen.getTime();
		}
		else {
			hoSoMotCuaCacheModel.NgayChuyen = Long.MIN_VALUE;
		}

		hoSoMotCuaCacheModel.MaSoHoSo = getMaSoHoSo();

		String MaSoHoSo = hoSoMotCuaCacheModel.MaSoHoSo;

		if ((MaSoHoSo != null) && (MaSoHoSo.length() == 0)) {
			hoSoMotCuaCacheModel.MaSoHoSo = null;
		}

		hoSoMotCuaCacheModel.MaLoaiHoSo = getMaLoaiHoSo();

		String MaLoaiHoSo = hoSoMotCuaCacheModel.MaLoaiHoSo;

		if ((MaLoaiHoSo != null) && (MaLoaiHoSo.length() == 0)) {
			hoSoMotCuaCacheModel.MaLoaiHoSo = null;
		}

		hoSoMotCuaCacheModel.MaDonViTiepNhan = getMaDonViTiepNhan();

		String MaDonViTiepNhan = hoSoMotCuaCacheModel.MaDonViTiepNhan;

		if ((MaDonViTiepNhan != null) && (MaDonViTiepNhan.length() == 0)) {
			hoSoMotCuaCacheModel.MaDonViTiepNhan = null;
		}

		hoSoMotCuaCacheModel.NgayNopHoSo = getNgayNopHoSo();

		String NgayNopHoSo = hoSoMotCuaCacheModel.NgayNopHoSo;

		if ((NgayNopHoSo != null) && (NgayNopHoSo.length() == 0)) {
			hoSoMotCuaCacheModel.NgayNopHoSo = null;
		}

		hoSoMotCuaCacheModel.NgayHenTra = getNgayHenTra();

		String NgayHenTra = hoSoMotCuaCacheModel.NgayHenTra;

		if ((NgayHenTra != null) && (NgayHenTra.length() == 0)) {
			hoSoMotCuaCacheModel.NgayHenTra = null;
		}

		hoSoMotCuaCacheModel.HoTenNguoiNop = getHoTenNguoiNop();

		String HoTenNguoiNop = hoSoMotCuaCacheModel.HoTenNguoiNop;

		if ((HoTenNguoiNop != null) && (HoTenNguoiNop.length() == 0)) {
			hoSoMotCuaCacheModel.HoTenNguoiNop = null;
		}

		hoSoMotCuaCacheModel.SoCmnd = getSoCmnd();

		String SoCmnd = hoSoMotCuaCacheModel.SoCmnd;

		if ((SoCmnd != null) && (SoCmnd.length() == 0)) {
			hoSoMotCuaCacheModel.SoCmnd = null;
		}

		hoSoMotCuaCacheModel.NgaySinh = getNgaySinh();

		String NgaySinh = hoSoMotCuaCacheModel.NgaySinh;

		if ((NgaySinh != null) && (NgaySinh.length() == 0)) {
			hoSoMotCuaCacheModel.NgaySinh = null;
		}

		hoSoMotCuaCacheModel.MaTinhThuongTru = getMaTinhThuongTru();

		String MaTinhThuongTru = hoSoMotCuaCacheModel.MaTinhThuongTru;

		if ((MaTinhThuongTru != null) && (MaTinhThuongTru.length() == 0)) {
			hoSoMotCuaCacheModel.MaTinhThuongTru = null;
		}

		hoSoMotCuaCacheModel.MoTaDiaChiThuongTru = getMoTaDiaChiThuongTru();

		String MoTaDiaChiThuongTru = hoSoMotCuaCacheModel.MoTaDiaChiThuongTru;

		if ((MoTaDiaChiThuongTru != null) &&
				(MoTaDiaChiThuongTru.length() == 0)) {
			hoSoMotCuaCacheModel.MoTaDiaChiThuongTru = null;
		}

		hoSoMotCuaCacheModel.GioiTinh = getGioiTinh();

		hoSoMotCuaCacheModel.MaNguoiTiepNhan = getMaNguoiTiepNhan();

		String MaNguoiTiepNhan = hoSoMotCuaCacheModel.MaNguoiTiepNhan;

		if ((MaNguoiTiepNhan != null) && (MaNguoiTiepNhan.length() == 0)) {
			hoSoMotCuaCacheModel.MaNguoiTiepNhan = null;
		}

		hoSoMotCuaCacheModel.TenNguoiTiepNhan = getTenNguoiTiepNhan();

		String TenNguoiTiepNhan = hoSoMotCuaCacheModel.TenNguoiTiepNhan;

		if ((TenNguoiTiepNhan != null) && (TenNguoiTiepNhan.length() == 0)) {
			hoSoMotCuaCacheModel.TenNguoiTiepNhan = null;
		}

		hoSoMotCuaCacheModel.DonViCungCap = getDonViCungCap();

		String DonViCungCap = hoSoMotCuaCacheModel.DonViCungCap;

		if ((DonViCungCap != null) && (DonViCungCap.length() == 0)) {
			hoSoMotCuaCacheModel.DonViCungCap = null;
		}

		hoSoMotCuaCacheModel.TrangThaiXuLy = getTrangThaiXuLy();

		Date NgayXuLy = getNgayXuLy();

		if (NgayXuLy != null) {
			hoSoMotCuaCacheModel.NgayXuLy = NgayXuLy.getTime();
		}
		else {
			hoSoMotCuaCacheModel.NgayXuLy = Long.MIN_VALUE;
		}

		hoSoMotCuaCacheModel.LoiKhiXuLy = getLoiKhiXuLy();

		String LoiKhiXuLy = hoSoMotCuaCacheModel.LoiKhiXuLy;

		if ((LoiKhiXuLy != null) && (LoiKhiXuLy.length() == 0)) {
			hoSoMotCuaCacheModel.LoiKhiXuLy = null;
		}

		return hoSoMotCuaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", NgayChuyen=");
		sb.append(getNgayChuyen());
		sb.append(", MaSoHoSo=");
		sb.append(getMaSoHoSo());
		sb.append(", MaLoaiHoSo=");
		sb.append(getMaLoaiHoSo());
		sb.append(", MaDonViTiepNhan=");
		sb.append(getMaDonViTiepNhan());
		sb.append(", NgayNopHoSo=");
		sb.append(getNgayNopHoSo());
		sb.append(", NgayHenTra=");
		sb.append(getNgayHenTra());
		sb.append(", HoTenNguoiNop=");
		sb.append(getHoTenNguoiNop());
		sb.append(", SoCmnd=");
		sb.append(getSoCmnd());
		sb.append(", NgaySinh=");
		sb.append(getNgaySinh());
		sb.append(", MaTinhThuongTru=");
		sb.append(getMaTinhThuongTru());
		sb.append(", MoTaDiaChiThuongTru=");
		sb.append(getMoTaDiaChiThuongTru());
		sb.append(", GioiTinh=");
		sb.append(getGioiTinh());
		sb.append(", MaNguoiTiepNhan=");
		sb.append(getMaNguoiTiepNhan());
		sb.append(", TenNguoiTiepNhan=");
		sb.append(getTenNguoiTiepNhan());
		sb.append(", DonViCungCap=");
		sb.append(getDonViCungCap());
		sb.append(", TrangThaiXuLy=");
		sb.append(getTrangThaiXuLy());
		sb.append(", NgayXuLy=");
		sb.append(getNgayXuLy());
		sb.append(", LoiKhiXuLy=");
		sb.append(getLoiKhiXuLy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("org.oep.exch.dao.hoso.model.HoSoMotCua");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayChuyen</column-name><column-value><![CDATA[");
		sb.append(getNgayChuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaSoHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaSoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaLoaiHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaLoaiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaDonViTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getMaDonViTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayNopHoSo</column-name><column-value><![CDATA[");
		sb.append(getNgayNopHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayHenTra</column-name><column-value><![CDATA[");
		sb.append(getNgayHenTra());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HoTenNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoCmnd</column-name><column-value><![CDATA[");
		sb.append(getSoCmnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgaySinh</column-name><column-value><![CDATA[");
		sb.append(getNgaySinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaTinhThuongTru</column-name><column-value><![CDATA[");
		sb.append(getMaTinhThuongTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MoTaDiaChiThuongTru</column-name><column-value><![CDATA[");
		sb.append(getMoTaDiaChiThuongTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GioiTinh</column-name><column-value><![CDATA[");
		sb.append(getGioiTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaNguoiTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getMaNguoiTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenNguoiTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DonViCungCap</column-name><column-value><![CDATA[");
		sb.append(getDonViCungCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThaiXuLy</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayXuLy</column-name><column-value><![CDATA[");
		sb.append(getNgayXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LoiKhiXuLy</column-name><column-value><![CDATA[");
		sb.append(getLoiKhiXuLy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = HoSoMotCua.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			HoSoMotCua.class
		};
	private long _id;
	private Date _NgayChuyen;
	private String _MaSoHoSo;
	private String _originalMaSoHoSo;
	private String _MaLoaiHoSo;
	private String _MaDonViTiepNhan;
	private String _NgayNopHoSo;
	private String _NgayHenTra;
	private String _HoTenNguoiNop;
	private String _SoCmnd;
	private String _NgaySinh;
	private String _MaTinhThuongTru;
	private String _MoTaDiaChiThuongTru;
	private int _GioiTinh;
	private String _MaNguoiTiepNhan;
	private String _TenNguoiTiepNhan;
	private String _DonViCungCap;
	private int _TrangThaiXuLy;
	private int _originalTrangThaiXuLy;
	private boolean _setOriginalTrangThaiXuLy;
	private Date _NgayXuLy;
	private String _LoiKhiXuLy;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private HoSoMotCua _escapedModelProxy;
}