/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.exch.dao.hoso.model.HoSoTrucTuyen;
import org.oep.exch.dao.hoso.model.HoSoTrucTuyenModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the HoSoTrucTuyen service. Represents a row in the &quot;exch_hosotructuyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.exch.dao.hoso.model.HoSoTrucTuyenModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HoSoTrucTuyenImpl}.
 * </p>
 *
 * @author NAM
 * @see HoSoTrucTuyenImpl
 * @see org.oep.exch.dao.hoso.model.HoSoTrucTuyen
 * @see org.oep.exch.dao.hoso.model.HoSoTrucTuyenModel
 * @generated
 */
public class HoSoTrucTuyenModelImpl extends BaseModelImpl<HoSoTrucTuyen>
	implements HoSoTrucTuyenModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ho so truc tuyen model instance should use the {@link org.oep.exch.dao.hoso.model.HoSoTrucTuyen} interface instead.
	 */
	public static final String TABLE_NAME = "exch_hosotructuyen";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NgayTrichXuat", Types.TIMESTAMP },
			{ "HOSOTTHCCONGID", Types.BIGINT },
			{ "MaLoaiHoSo", Types.VARCHAR },
			{ "MaDonViTiepNhan", Types.VARCHAR },
			{ "HoTenNguoiNop", Types.VARCHAR },
			{ "DiaChiNguoiNop", Types.VARCHAR },
			{ "NgaySinh", Types.TIMESTAMP },
			{ "SoCmnd", Types.VARCHAR },
			{ "Email", Types.VARCHAR },
			{ "SoDtDiDong", Types.VARCHAR },
			{ "SoDtCoDinh", Types.VARCHAR },
			{ "NgayDangKyHoSo", Types.TIMESTAMP },
			{ "NoiChuyenHoSo", Types.VARCHAR },
			{ "TrangThaiXuLy", Types.INTEGER },
			{ "NgayChuyen", Types.TIMESTAMP },
			{ "GioiTinh", Types.INTEGER },
			{ "ChuSoHuuHoSo", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table exch_hosotructuyen (ID LONG not null primary key,NgayTrichXuat DATE null,HOSOTTHCCONGID LONG,MaLoaiHoSo VARCHAR(75) null,MaDonViTiepNhan VARCHAR(75) null,HoTenNguoiNop VARCHAR(75) null,DiaChiNguoiNop VARCHAR(75) null,NgaySinh DATE null,SoCmnd VARCHAR(75) null,Email VARCHAR(75) null,SoDtDiDong VARCHAR(75) null,SoDtCoDinh VARCHAR(75) null,NgayDangKyHoSo DATE null,NoiChuyenHoSo VARCHAR(75) null,TrangThaiXuLy INTEGER,NgayChuyen DATE null,GioiTinh INTEGER,ChuSoHuuHoSo VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table exch_hosotructuyen";
	public static final String ORDER_BY_JPQL = " ORDER BY hoSoTrucTuyen.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY exch_hosotructuyen.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.exch.dao.hoso.model.HoSoTrucTuyen"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.exch.dao.hoso.model.HoSoTrucTuyen"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.exch.dao.hoso.model.HoSoTrucTuyen"),
			true);
	public static long MADONVITIEPNHAN_COLUMN_BITMASK = 1L;
	public static long NOICHUYENHOSO_COLUMN_BITMASK = 2L;
	public static long TRANGTHAIXULY_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.exch.dao.hoso.model.HoSoTrucTuyen"));

	public HoSoTrucTuyenModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return HoSoTrucTuyen.class;
	}

	public String getModelClassName() {
		return HoSoTrucTuyen.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public Date getNgayTrichXuat() {
		return _NgayTrichXuat;
	}

	public void setNgayTrichXuat(Date NgayTrichXuat) {
		_NgayTrichXuat = NgayTrichXuat;
	}

	public long getOnlineId() {
		return _OnlineId;
	}

	public void setOnlineId(long OnlineId) {
		_OnlineId = OnlineId;
	}

	public String getMaLoaiHoSo() {
		if (_MaLoaiHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaLoaiHoSo;
		}
	}

	public void setMaLoaiHoSo(String MaLoaiHoSo) {
		_MaLoaiHoSo = MaLoaiHoSo;
	}

	public String getMaDonViTiepNhan() {
		if (_MaDonViTiepNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaDonViTiepNhan;
		}
	}

	public void setMaDonViTiepNhan(String MaDonViTiepNhan) {
		_columnBitmask |= MADONVITIEPNHAN_COLUMN_BITMASK;

		if (_originalMaDonViTiepNhan == null) {
			_originalMaDonViTiepNhan = _MaDonViTiepNhan;
		}

		_MaDonViTiepNhan = MaDonViTiepNhan;
	}

	public String getOriginalMaDonViTiepNhan() {
		return GetterUtil.getString(_originalMaDonViTiepNhan);
	}

	public String getHoTenNguoiNop() {
		if (_HoTenNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _HoTenNguoiNop;
		}
	}

	public void setHoTenNguoiNop(String HoTenNguoiNop) {
		_HoTenNguoiNop = HoTenNguoiNop;
	}

	public String getDiaChiNguoiNop() {
		if (_DiaChiNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _DiaChiNguoiNop;
		}
	}

	public void setDiaChiNguoiNop(String DiaChiNguoiNop) {
		_DiaChiNguoiNop = DiaChiNguoiNop;
	}

	public Date getNgaySinh() {
		return _NgaySinh;
	}

	public void setNgaySinh(Date NgaySinh) {
		_NgaySinh = NgaySinh;
	}

	public String getSoCmnd() {
		if (_SoCmnd == null) {
			return StringPool.BLANK;
		}
		else {
			return _SoCmnd;
		}
	}

	public void setSoCmnd(String SoCmnd) {
		_SoCmnd = SoCmnd;
	}

	public String getEmail() {
		if (_Email == null) {
			return StringPool.BLANK;
		}
		else {
			return _Email;
		}
	}

	public void setEmail(String Email) {
		_Email = Email;
	}

	public String getSoDtDiDong() {
		if (_SoDtDiDong == null) {
			return StringPool.BLANK;
		}
		else {
			return _SoDtDiDong;
		}
	}

	public void setSoDtDiDong(String SoDtDiDong) {
		_SoDtDiDong = SoDtDiDong;
	}

	public String getSoDtCoDinh() {
		if (_SoDtCoDinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _SoDtCoDinh;
		}
	}

	public void setSoDtCoDinh(String SoDtCoDinh) {
		_SoDtCoDinh = SoDtCoDinh;
	}

	public Date getNgayDangKyHoSo() {
		return _NgayDangKyHoSo;
	}

	public void setNgayDangKyHoSo(Date NgayDangKyHoSo) {
		_NgayDangKyHoSo = NgayDangKyHoSo;
	}

	public String getNoiChuyenHoSo() {
		if (_NoiChuyenHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _NoiChuyenHoSo;
		}
	}

	public void setNoiChuyenHoSo(String NoiChuyenHoSo) {
		_columnBitmask |= NOICHUYENHOSO_COLUMN_BITMASK;

		if (_originalNoiChuyenHoSo == null) {
			_originalNoiChuyenHoSo = _NoiChuyenHoSo;
		}

		_NoiChuyenHoSo = NoiChuyenHoSo;
	}

	public String getOriginalNoiChuyenHoSo() {
		return GetterUtil.getString(_originalNoiChuyenHoSo);
	}

	public int getTrangThaiXuLy() {
		return _TrangThaiXuLy;
	}

	public void setTrangThaiXuLy(int TrangThaiXuLy) {
		_columnBitmask |= TRANGTHAIXULY_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiXuLy) {
			_setOriginalTrangThaiXuLy = true;

			_originalTrangThaiXuLy = _TrangThaiXuLy;
		}

		_TrangThaiXuLy = TrangThaiXuLy;
	}

	public int getOriginalTrangThaiXuLy() {
		return _originalTrangThaiXuLy;
	}

	public Date getNgayChuyen() {
		return _NgayChuyen;
	}

	public void setNgayChuyen(Date NgayChuyen) {
		_NgayChuyen = NgayChuyen;
	}

	public int getGioiTinh() {
		return _GioiTinh;
	}

	public void setGioiTinh(int GioiTinh) {
		_GioiTinh = GioiTinh;
	}

	public String getChuSoHuuHoSo() {
		if (_ChuSoHuuHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _ChuSoHuuHoSo;
		}
	}

	public void setChuSoHuuHoSo(String ChuSoHuuHoSo) {
		_ChuSoHuuHoSo = ChuSoHuuHoSo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public HoSoTrucTuyen toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (HoSoTrucTuyen)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					HoSoTrucTuyen.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		HoSoTrucTuyenImpl hoSoTrucTuyenImpl = new HoSoTrucTuyenImpl();

		hoSoTrucTuyenImpl.setId(getId());
		hoSoTrucTuyenImpl.setNgayTrichXuat(getNgayTrichXuat());
		hoSoTrucTuyenImpl.setOnlineId(getOnlineId());
		hoSoTrucTuyenImpl.setMaLoaiHoSo(getMaLoaiHoSo());
		hoSoTrucTuyenImpl.setMaDonViTiepNhan(getMaDonViTiepNhan());
		hoSoTrucTuyenImpl.setHoTenNguoiNop(getHoTenNguoiNop());
		hoSoTrucTuyenImpl.setDiaChiNguoiNop(getDiaChiNguoiNop());
		hoSoTrucTuyenImpl.setNgaySinh(getNgaySinh());
		hoSoTrucTuyenImpl.setSoCmnd(getSoCmnd());
		hoSoTrucTuyenImpl.setEmail(getEmail());
		hoSoTrucTuyenImpl.setSoDtDiDong(getSoDtDiDong());
		hoSoTrucTuyenImpl.setSoDtCoDinh(getSoDtCoDinh());
		hoSoTrucTuyenImpl.setNgayDangKyHoSo(getNgayDangKyHoSo());
		hoSoTrucTuyenImpl.setNoiChuyenHoSo(getNoiChuyenHoSo());
		hoSoTrucTuyenImpl.setTrangThaiXuLy(getTrangThaiXuLy());
		hoSoTrucTuyenImpl.setNgayChuyen(getNgayChuyen());
		hoSoTrucTuyenImpl.setGioiTinh(getGioiTinh());
		hoSoTrucTuyenImpl.setChuSoHuuHoSo(getChuSoHuuHoSo());

		hoSoTrucTuyenImpl.resetOriginalValues();

		return hoSoTrucTuyenImpl;
	}

	public int compareTo(HoSoTrucTuyen hoSoTrucTuyen) {
		int value = 0;

		if (getId() < hoSoTrucTuyen.getId()) {
			value = -1;
		}
		else if (getId() > hoSoTrucTuyen.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		HoSoTrucTuyen hoSoTrucTuyen = null;

		try {
			hoSoTrucTuyen = (HoSoTrucTuyen)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = hoSoTrucTuyen.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		HoSoTrucTuyenModelImpl hoSoTrucTuyenModelImpl = this;

		hoSoTrucTuyenModelImpl._originalMaDonViTiepNhan = hoSoTrucTuyenModelImpl._MaDonViTiepNhan;

		hoSoTrucTuyenModelImpl._originalNoiChuyenHoSo = hoSoTrucTuyenModelImpl._NoiChuyenHoSo;

		hoSoTrucTuyenModelImpl._originalTrangThaiXuLy = hoSoTrucTuyenModelImpl._TrangThaiXuLy;

		hoSoTrucTuyenModelImpl._setOriginalTrangThaiXuLy = false;

		hoSoTrucTuyenModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<HoSoTrucTuyen> toCacheModel() {
		HoSoTrucTuyenCacheModel hoSoTrucTuyenCacheModel = new HoSoTrucTuyenCacheModel();

		hoSoTrucTuyenCacheModel.id = getId();

		Date NgayTrichXuat = getNgayTrichXuat();

		if (NgayTrichXuat != null) {
			hoSoTrucTuyenCacheModel.NgayTrichXuat = NgayTrichXuat.getTime();
		}
		else {
			hoSoTrucTuyenCacheModel.NgayTrichXuat = Long.MIN_VALUE;
		}

		hoSoTrucTuyenCacheModel.OnlineId = getOnlineId();

		hoSoTrucTuyenCacheModel.MaLoaiHoSo = getMaLoaiHoSo();

		String MaLoaiHoSo = hoSoTrucTuyenCacheModel.MaLoaiHoSo;

		if ((MaLoaiHoSo != null) && (MaLoaiHoSo.length() == 0)) {
			hoSoTrucTuyenCacheModel.MaLoaiHoSo = null;
		}

		hoSoTrucTuyenCacheModel.MaDonViTiepNhan = getMaDonViTiepNhan();

		String MaDonViTiepNhan = hoSoTrucTuyenCacheModel.MaDonViTiepNhan;

		if ((MaDonViTiepNhan != null) && (MaDonViTiepNhan.length() == 0)) {
			hoSoTrucTuyenCacheModel.MaDonViTiepNhan = null;
		}

		hoSoTrucTuyenCacheModel.HoTenNguoiNop = getHoTenNguoiNop();

		String HoTenNguoiNop = hoSoTrucTuyenCacheModel.HoTenNguoiNop;

		if ((HoTenNguoiNop != null) && (HoTenNguoiNop.length() == 0)) {
			hoSoTrucTuyenCacheModel.HoTenNguoiNop = null;
		}

		hoSoTrucTuyenCacheModel.DiaChiNguoiNop = getDiaChiNguoiNop();

		String DiaChiNguoiNop = hoSoTrucTuyenCacheModel.DiaChiNguoiNop;

		if ((DiaChiNguoiNop != null) && (DiaChiNguoiNop.length() == 0)) {
			hoSoTrucTuyenCacheModel.DiaChiNguoiNop = null;
		}

		Date NgaySinh = getNgaySinh();

		if (NgaySinh != null) {
			hoSoTrucTuyenCacheModel.NgaySinh = NgaySinh.getTime();
		}
		else {
			hoSoTrucTuyenCacheModel.NgaySinh = Long.MIN_VALUE;
		}

		hoSoTrucTuyenCacheModel.SoCmnd = getSoCmnd();

		String SoCmnd = hoSoTrucTuyenCacheModel.SoCmnd;

		if ((SoCmnd != null) && (SoCmnd.length() == 0)) {
			hoSoTrucTuyenCacheModel.SoCmnd = null;
		}

		hoSoTrucTuyenCacheModel.Email = getEmail();

		String Email = hoSoTrucTuyenCacheModel.Email;

		if ((Email != null) && (Email.length() == 0)) {
			hoSoTrucTuyenCacheModel.Email = null;
		}

		hoSoTrucTuyenCacheModel.SoDtDiDong = getSoDtDiDong();

		String SoDtDiDong = hoSoTrucTuyenCacheModel.SoDtDiDong;

		if ((SoDtDiDong != null) && (SoDtDiDong.length() == 0)) {
			hoSoTrucTuyenCacheModel.SoDtDiDong = null;
		}

		hoSoTrucTuyenCacheModel.SoDtCoDinh = getSoDtCoDinh();

		String SoDtCoDinh = hoSoTrucTuyenCacheModel.SoDtCoDinh;

		if ((SoDtCoDinh != null) && (SoDtCoDinh.length() == 0)) {
			hoSoTrucTuyenCacheModel.SoDtCoDinh = null;
		}

		Date NgayDangKyHoSo = getNgayDangKyHoSo();

		if (NgayDangKyHoSo != null) {
			hoSoTrucTuyenCacheModel.NgayDangKyHoSo = NgayDangKyHoSo.getTime();
		}
		else {
			hoSoTrucTuyenCacheModel.NgayDangKyHoSo = Long.MIN_VALUE;
		}

		hoSoTrucTuyenCacheModel.NoiChuyenHoSo = getNoiChuyenHoSo();

		String NoiChuyenHoSo = hoSoTrucTuyenCacheModel.NoiChuyenHoSo;

		if ((NoiChuyenHoSo != null) && (NoiChuyenHoSo.length() == 0)) {
			hoSoTrucTuyenCacheModel.NoiChuyenHoSo = null;
		}

		hoSoTrucTuyenCacheModel.TrangThaiXuLy = getTrangThaiXuLy();

		Date NgayChuyen = getNgayChuyen();

		if (NgayChuyen != null) {
			hoSoTrucTuyenCacheModel.NgayChuyen = NgayChuyen.getTime();
		}
		else {
			hoSoTrucTuyenCacheModel.NgayChuyen = Long.MIN_VALUE;
		}

		hoSoTrucTuyenCacheModel.GioiTinh = getGioiTinh();

		hoSoTrucTuyenCacheModel.ChuSoHuuHoSo = getChuSoHuuHoSo();

		String ChuSoHuuHoSo = hoSoTrucTuyenCacheModel.ChuSoHuuHoSo;

		if ((ChuSoHuuHoSo != null) && (ChuSoHuuHoSo.length() == 0)) {
			hoSoTrucTuyenCacheModel.ChuSoHuuHoSo = null;
		}

		return hoSoTrucTuyenCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", NgayTrichXuat=");
		sb.append(getNgayTrichXuat());
		sb.append(", OnlineId=");
		sb.append(getOnlineId());
		sb.append(", MaLoaiHoSo=");
		sb.append(getMaLoaiHoSo());
		sb.append(", MaDonViTiepNhan=");
		sb.append(getMaDonViTiepNhan());
		sb.append(", HoTenNguoiNop=");
		sb.append(getHoTenNguoiNop());
		sb.append(", DiaChiNguoiNop=");
		sb.append(getDiaChiNguoiNop());
		sb.append(", NgaySinh=");
		sb.append(getNgaySinh());
		sb.append(", SoCmnd=");
		sb.append(getSoCmnd());
		sb.append(", Email=");
		sb.append(getEmail());
		sb.append(", SoDtDiDong=");
		sb.append(getSoDtDiDong());
		sb.append(", SoDtCoDinh=");
		sb.append(getSoDtCoDinh());
		sb.append(", NgayDangKyHoSo=");
		sb.append(getNgayDangKyHoSo());
		sb.append(", NoiChuyenHoSo=");
		sb.append(getNoiChuyenHoSo());
		sb.append(", TrangThaiXuLy=");
		sb.append(getTrangThaiXuLy());
		sb.append(", NgayChuyen=");
		sb.append(getNgayChuyen());
		sb.append(", GioiTinh=");
		sb.append(getGioiTinh());
		sb.append(", ChuSoHuuHoSo=");
		sb.append(getChuSoHuuHoSo());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("org.oep.exch.dao.hoso.model.HoSoTrucTuyen");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayTrichXuat</column-name><column-value><![CDATA[");
		sb.append(getNgayTrichXuat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OnlineId</column-name><column-value><![CDATA[");
		sb.append(getOnlineId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaLoaiHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaLoaiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaDonViTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getMaDonViTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HoTenNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getHoTenNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DiaChiNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getDiaChiNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgaySinh</column-name><column-value><![CDATA[");
		sb.append(getNgaySinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoCmnd</column-name><column-value><![CDATA[");
		sb.append(getSoCmnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoDtDiDong</column-name><column-value><![CDATA[");
		sb.append(getSoDtDiDong());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoDtCoDinh</column-name><column-value><![CDATA[");
		sb.append(getSoDtCoDinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayDangKyHoSo</column-name><column-value><![CDATA[");
		sb.append(getNgayDangKyHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NoiChuyenHoSo</column-name><column-value><![CDATA[");
		sb.append(getNoiChuyenHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThaiXuLy</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayChuyen</column-name><column-value><![CDATA[");
		sb.append(getNgayChuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GioiTinh</column-name><column-value><![CDATA[");
		sb.append(getGioiTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ChuSoHuuHoSo</column-name><column-value><![CDATA[");
		sb.append(getChuSoHuuHoSo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = HoSoTrucTuyen.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			HoSoTrucTuyen.class
		};
	private long _id;
	private Date _NgayTrichXuat;
	private long _OnlineId;
	private String _MaLoaiHoSo;
	private String _MaDonViTiepNhan;
	private String _originalMaDonViTiepNhan;
	private String _HoTenNguoiNop;
	private String _DiaChiNguoiNop;
	private Date _NgaySinh;
	private String _SoCmnd;
	private String _Email;
	private String _SoDtDiDong;
	private String _SoDtCoDinh;
	private Date _NgayDangKyHoSo;
	private String _NoiChuyenHoSo;
	private String _originalNoiChuyenHoSo;
	private int _TrangThaiXuLy;
	private int _originalTrangThaiXuLy;
	private boolean _setOriginalTrangThaiXuLy;
	private Date _NgayChuyen;
	private int _GioiTinh;
	private String _ChuSoHuuHoSo;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private HoSoTrucTuyen _escapedModelProxy;
}