/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.exch.dao.hoso.model.KetQuaHoso;
import org.oep.exch.dao.hoso.model.KetQuaHosoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the KetQuaHoso service. Represents a row in the &quot;exch_ketquahoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.exch.dao.hoso.model.KetQuaHosoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KetQuaHosoImpl}.
 * </p>
 *
 * @author NAM
 * @see KetQuaHosoImpl
 * @see org.oep.exch.dao.hoso.model.KetQuaHoso
 * @see org.oep.exch.dao.hoso.model.KetQuaHosoModel
 * @generated
 */
public class KetQuaHosoModelImpl extends BaseModelImpl<KetQuaHoso>
	implements KetQuaHosoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ket qua hoso model instance should use the {@link org.oep.exch.dao.hoso.model.KetQuaHoso} interface instead.
	 */
	public static final String TABLE_NAME = "exch_ketquahoso";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NgayChuyen", Types.TIMESTAMP },
			{ "MaSoHoSo", Types.VARCHAR },
			{ "TenNguoiNhanKetQua", Types.VARCHAR },
			{ "NgayNhanKetQua", Types.VARCHAR },
			{ "LePhiHoSo", Types.INTEGER },
			{ "PhiXuLyHoSo", Types.INTEGER },
			{ "NgayHoanThanh", Types.VARCHAR },
			{ "MaCanBoTraKetQua", Types.VARCHAR },
			{ "TenCanBoTraKetQua", Types.VARCHAR },
			{ "DonViCungCap", Types.VARCHAR },
			{ "TrangThaiXuLy", Types.INTEGER },
			{ "NgayXuLy", Types.TIMESTAMP },
			{ "LoiKhiXuLy", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table exch_ketquahoso (ID LONG not null primary key,NgayChuyen DATE null,MaSoHoSo VARCHAR(75) null,TenNguoiNhanKetQua VARCHAR(75) null,NgayNhanKetQua VARCHAR(75) null,LePhiHoSo INTEGER,PhiXuLyHoSo INTEGER,NgayHoanThanh VARCHAR(75) null,MaCanBoTraKetQua VARCHAR(75) null,TenCanBoTraKetQua VARCHAR(75) null,DonViCungCap VARCHAR(75) null,TrangThaiXuLy INTEGER,NgayXuLy DATE null,LoiKhiXuLy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table exch_ketquahoso";
	public static final String ORDER_BY_JPQL = " ORDER BY ketQuaHoso.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY exch_ketquahoso.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.exch.dao.hoso.model.KetQuaHoso"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.exch.dao.hoso.model.KetQuaHoso"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.exch.dao.hoso.model.KetQuaHoso"),
			true);
	public static long TRANGTHAIXULY_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.exch.dao.hoso.model.KetQuaHoso"));

	public KetQuaHosoModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return KetQuaHoso.class;
	}

	public String getModelClassName() {
		return KetQuaHoso.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public Date getNgayChuyen() {
		return _NgayChuyen;
	}

	public void setNgayChuyen(Date NgayChuyen) {
		_NgayChuyen = NgayChuyen;
	}

	public String getMaSoHoSo() {
		if (_MaSoHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaSoHoSo;
		}
	}

	public void setMaSoHoSo(String MaSoHoSo) {
		_MaSoHoSo = MaSoHoSo;
	}

	public String getTenNguoiNhanKetQua() {
		if (_TenNguoiNhanKetQua == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenNguoiNhanKetQua;
		}
	}

	public void setTenNguoiNhanKetQua(String TenNguoiNhanKetQua) {
		_TenNguoiNhanKetQua = TenNguoiNhanKetQua;
	}

	public String getNgayNhanKetQua() {
		if (_NgayNhanKetQua == null) {
			return StringPool.BLANK;
		}
		else {
			return _NgayNhanKetQua;
		}
	}

	public void setNgayNhanKetQua(String NgayNhanKetQua) {
		_NgayNhanKetQua = NgayNhanKetQua;
	}

	public int getLePhiHoSo() {
		return _LePhiHoSo;
	}

	public void setLePhiHoSo(int LePhiHoSo) {
		_LePhiHoSo = LePhiHoSo;
	}

	public int getPhiXuLyHoSo() {
		return _PhiXuLyHoSo;
	}

	public void setPhiXuLyHoSo(int PhiXuLyHoSo) {
		_PhiXuLyHoSo = PhiXuLyHoSo;
	}

	public String getNgayHoanThanh() {
		if (_NgayHoanThanh == null) {
			return StringPool.BLANK;
		}
		else {
			return _NgayHoanThanh;
		}
	}

	public void setNgayHoanThanh(String NgayHoanThanh) {
		_NgayHoanThanh = NgayHoanThanh;
	}

	public String getMaCanBoTraKetQua() {
		if (_MaCanBoTraKetQua == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaCanBoTraKetQua;
		}
	}

	public void setMaCanBoTraKetQua(String MaCanBoTraKetQua) {
		_MaCanBoTraKetQua = MaCanBoTraKetQua;
	}

	public String getTenCanBoTraKetQua() {
		if (_TenCanBoTraKetQua == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenCanBoTraKetQua;
		}
	}

	public void setTenCanBoTraKetQua(String TenCanBoTraKetQua) {
		_TenCanBoTraKetQua = TenCanBoTraKetQua;
	}

	public String getDonViCungCap() {
		if (_DonViCungCap == null) {
			return StringPool.BLANK;
		}
		else {
			return _DonViCungCap;
		}
	}

	public void setDonViCungCap(String DonViCungCap) {
		_DonViCungCap = DonViCungCap;
	}

	public int getTrangThaiXuLy() {
		return _TrangThaiXuLy;
	}

	public void setTrangThaiXuLy(int TrangThaiXuLy) {
		_columnBitmask |= TRANGTHAIXULY_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiXuLy) {
			_setOriginalTrangThaiXuLy = true;

			_originalTrangThaiXuLy = _TrangThaiXuLy;
		}

		_TrangThaiXuLy = TrangThaiXuLy;
	}

	public int getOriginalTrangThaiXuLy() {
		return _originalTrangThaiXuLy;
	}

	public Date getNgayXuLy() {
		return _NgayXuLy;
	}

	public void setNgayXuLy(Date NgayXuLy) {
		_NgayXuLy = NgayXuLy;
	}

	public String getLoiKhiXuLy() {
		if (_LoiKhiXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _LoiKhiXuLy;
		}
	}

	public void setLoiKhiXuLy(String LoiKhiXuLy) {
		_LoiKhiXuLy = LoiKhiXuLy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public KetQuaHoso toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (KetQuaHoso)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					KetQuaHoso.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		KetQuaHosoImpl ketQuaHosoImpl = new KetQuaHosoImpl();

		ketQuaHosoImpl.setId(getId());
		ketQuaHosoImpl.setNgayChuyen(getNgayChuyen());
		ketQuaHosoImpl.setMaSoHoSo(getMaSoHoSo());
		ketQuaHosoImpl.setTenNguoiNhanKetQua(getTenNguoiNhanKetQua());
		ketQuaHosoImpl.setNgayNhanKetQua(getNgayNhanKetQua());
		ketQuaHosoImpl.setLePhiHoSo(getLePhiHoSo());
		ketQuaHosoImpl.setPhiXuLyHoSo(getPhiXuLyHoSo());
		ketQuaHosoImpl.setNgayHoanThanh(getNgayHoanThanh());
		ketQuaHosoImpl.setMaCanBoTraKetQua(getMaCanBoTraKetQua());
		ketQuaHosoImpl.setTenCanBoTraKetQua(getTenCanBoTraKetQua());
		ketQuaHosoImpl.setDonViCungCap(getDonViCungCap());
		ketQuaHosoImpl.setTrangThaiXuLy(getTrangThaiXuLy());
		ketQuaHosoImpl.setNgayXuLy(getNgayXuLy());
		ketQuaHosoImpl.setLoiKhiXuLy(getLoiKhiXuLy());

		ketQuaHosoImpl.resetOriginalValues();

		return ketQuaHosoImpl;
	}

	public int compareTo(KetQuaHoso ketQuaHoso) {
		int value = 0;

		if (getId() < ketQuaHoso.getId()) {
			value = -1;
		}
		else if (getId() > ketQuaHoso.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		KetQuaHoso ketQuaHoso = null;

		try {
			ketQuaHoso = (KetQuaHoso)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = ketQuaHoso.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		KetQuaHosoModelImpl ketQuaHosoModelImpl = this;

		ketQuaHosoModelImpl._originalTrangThaiXuLy = ketQuaHosoModelImpl._TrangThaiXuLy;

		ketQuaHosoModelImpl._setOriginalTrangThaiXuLy = false;

		ketQuaHosoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<KetQuaHoso> toCacheModel() {
		KetQuaHosoCacheModel ketQuaHosoCacheModel = new KetQuaHosoCacheModel();

		ketQuaHosoCacheModel.id = getId();

		Date NgayChuyen = getNgayChuyen();

		if (NgayChuyen != null) {
			ketQuaHosoCacheModel.NgayChuyen = NgayChuyen.getTime();
		}
		else {
			ketQuaHosoCacheModel.NgayChuyen = Long.MIN_VALUE;
		}

		ketQuaHosoCacheModel.MaSoHoSo = getMaSoHoSo();

		String MaSoHoSo = ketQuaHosoCacheModel.MaSoHoSo;

		if ((MaSoHoSo != null) && (MaSoHoSo.length() == 0)) {
			ketQuaHosoCacheModel.MaSoHoSo = null;
		}

		ketQuaHosoCacheModel.TenNguoiNhanKetQua = getTenNguoiNhanKetQua();

		String TenNguoiNhanKetQua = ketQuaHosoCacheModel.TenNguoiNhanKetQua;

		if ((TenNguoiNhanKetQua != null) && (TenNguoiNhanKetQua.length() == 0)) {
			ketQuaHosoCacheModel.TenNguoiNhanKetQua = null;
		}

		ketQuaHosoCacheModel.NgayNhanKetQua = getNgayNhanKetQua();

		String NgayNhanKetQua = ketQuaHosoCacheModel.NgayNhanKetQua;

		if ((NgayNhanKetQua != null) && (NgayNhanKetQua.length() == 0)) {
			ketQuaHosoCacheModel.NgayNhanKetQua = null;
		}

		ketQuaHosoCacheModel.LePhiHoSo = getLePhiHoSo();

		ketQuaHosoCacheModel.PhiXuLyHoSo = getPhiXuLyHoSo();

		ketQuaHosoCacheModel.NgayHoanThanh = getNgayHoanThanh();

		String NgayHoanThanh = ketQuaHosoCacheModel.NgayHoanThanh;

		if ((NgayHoanThanh != null) && (NgayHoanThanh.length() == 0)) {
			ketQuaHosoCacheModel.NgayHoanThanh = null;
		}

		ketQuaHosoCacheModel.MaCanBoTraKetQua = getMaCanBoTraKetQua();

		String MaCanBoTraKetQua = ketQuaHosoCacheModel.MaCanBoTraKetQua;

		if ((MaCanBoTraKetQua != null) && (MaCanBoTraKetQua.length() == 0)) {
			ketQuaHosoCacheModel.MaCanBoTraKetQua = null;
		}

		ketQuaHosoCacheModel.TenCanBoTraKetQua = getTenCanBoTraKetQua();

		String TenCanBoTraKetQua = ketQuaHosoCacheModel.TenCanBoTraKetQua;

		if ((TenCanBoTraKetQua != null) && (TenCanBoTraKetQua.length() == 0)) {
			ketQuaHosoCacheModel.TenCanBoTraKetQua = null;
		}

		ketQuaHosoCacheModel.DonViCungCap = getDonViCungCap();

		String DonViCungCap = ketQuaHosoCacheModel.DonViCungCap;

		if ((DonViCungCap != null) && (DonViCungCap.length() == 0)) {
			ketQuaHosoCacheModel.DonViCungCap = null;
		}

		ketQuaHosoCacheModel.TrangThaiXuLy = getTrangThaiXuLy();

		Date NgayXuLy = getNgayXuLy();

		if (NgayXuLy != null) {
			ketQuaHosoCacheModel.NgayXuLy = NgayXuLy.getTime();
		}
		else {
			ketQuaHosoCacheModel.NgayXuLy = Long.MIN_VALUE;
		}

		ketQuaHosoCacheModel.LoiKhiXuLy = getLoiKhiXuLy();

		String LoiKhiXuLy = ketQuaHosoCacheModel.LoiKhiXuLy;

		if ((LoiKhiXuLy != null) && (LoiKhiXuLy.length() == 0)) {
			ketQuaHosoCacheModel.LoiKhiXuLy = null;
		}

		return ketQuaHosoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", NgayChuyen=");
		sb.append(getNgayChuyen());
		sb.append(", MaSoHoSo=");
		sb.append(getMaSoHoSo());
		sb.append(", TenNguoiNhanKetQua=");
		sb.append(getTenNguoiNhanKetQua());
		sb.append(", NgayNhanKetQua=");
		sb.append(getNgayNhanKetQua());
		sb.append(", LePhiHoSo=");
		sb.append(getLePhiHoSo());
		sb.append(", PhiXuLyHoSo=");
		sb.append(getPhiXuLyHoSo());
		sb.append(", NgayHoanThanh=");
		sb.append(getNgayHoanThanh());
		sb.append(", MaCanBoTraKetQua=");
		sb.append(getMaCanBoTraKetQua());
		sb.append(", TenCanBoTraKetQua=");
		sb.append(getTenCanBoTraKetQua());
		sb.append(", DonViCungCap=");
		sb.append(getDonViCungCap());
		sb.append(", TrangThaiXuLy=");
		sb.append(getTrangThaiXuLy());
		sb.append(", NgayXuLy=");
		sb.append(getNgayXuLy());
		sb.append(", LoiKhiXuLy=");
		sb.append(getLoiKhiXuLy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("org.oep.exch.dao.hoso.model.KetQuaHoso");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayChuyen</column-name><column-value><![CDATA[");
		sb.append(getNgayChuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaSoHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaSoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenNguoiNhanKetQua</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiNhanKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayNhanKetQua</column-name><column-value><![CDATA[");
		sb.append(getNgayNhanKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LePhiHoSo</column-name><column-value><![CDATA[");
		sb.append(getLePhiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PhiXuLyHoSo</column-name><column-value><![CDATA[");
		sb.append(getPhiXuLyHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayHoanThanh</column-name><column-value><![CDATA[");
		sb.append(getNgayHoanThanh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaCanBoTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getMaCanBoTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenCanBoTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getTenCanBoTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DonViCungCap</column-name><column-value><![CDATA[");
		sb.append(getDonViCungCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThaiXuLy</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayXuLy</column-name><column-value><![CDATA[");
		sb.append(getNgayXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LoiKhiXuLy</column-name><column-value><![CDATA[");
		sb.append(getLoiKhiXuLy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = KetQuaHoso.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			KetQuaHoso.class
		};
	private long _id;
	private Date _NgayChuyen;
	private String _MaSoHoSo;
	private String _TenNguoiNhanKetQua;
	private String _NgayNhanKetQua;
	private int _LePhiHoSo;
	private int _PhiXuLyHoSo;
	private String _NgayHoanThanh;
	private String _MaCanBoTraKetQua;
	private String _TenCanBoTraKetQua;
	private String _DonViCungCap;
	private int _TrangThaiXuLy;
	private int _originalTrangThaiXuLy;
	private boolean _setOriginalTrangThaiXuLy;
	private Date _NgayXuLy;
	private String _LoiKhiXuLy;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private KetQuaHoso _escapedModelProxy;
}