/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.oep.exch.dao.hoso.model.KetQuaHoso;
import org.oep.exch.dao.hoso.service.KetQuaHosoLocalServiceUtil;

/**
 * The extended model base implementation for the KetQuaHoso service. Represents a row in the &quot;exch_ketquahoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KetQuaHosoImpl}.
 * </p>
 *
 * @author NAM
 * @see KetQuaHosoImpl
 * @see org.oep.exch.dao.hoso.model.KetQuaHoso
 * @generated
 */
public abstract class KetQuaHosoBaseImpl extends KetQuaHosoModelImpl
	implements KetQuaHoso {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ket qua hoso model instance should use the {@link KetQuaHoso} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			KetQuaHosoLocalServiceUtil.addKetQuaHoso(this);
		}
		else {
			KetQuaHosoLocalServiceUtil.updateKetQuaHoso(this);
		}
	}
}