/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.exch.dao.hoso.model.TrangThaiHoso;
import org.oep.exch.dao.hoso.model.TrangThaiHosoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TrangThaiHoso service. Represents a row in the &quot;exch_trangthaihoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.exch.dao.hoso.model.TrangThaiHosoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrangThaiHosoImpl}.
 * </p>
 *
 * @author NAM
 * @see TrangThaiHosoImpl
 * @see org.oep.exch.dao.hoso.model.TrangThaiHoso
 * @see org.oep.exch.dao.hoso.model.TrangThaiHosoModel
 * @generated
 */
public class TrangThaiHosoModelImpl extends BaseModelImpl<TrangThaiHoso>
	implements TrangThaiHosoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trang thai hoso model instance should use the {@link org.oep.exch.dao.hoso.model.TrangThaiHoso} interface instead.
	 */
	public static final String TABLE_NAME = "exch_trangthaihoso";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "NgayChuyen", Types.TIMESTAMP },
			{ "HOSOTTHCCONGID", Types.BIGINT },
			{ "MaSoHoSo", Types.VARCHAR },
			{ "NgayHenTra", Types.VARCHAR },
			{ "MaNguoiXuLyHienTai", Types.VARCHAR },
			{ "TenNguoiXuLyHienTai", Types.VARCHAR },
			{ "TenPhongBanXuLyHienTai", Types.VARCHAR },
			{ "NgayGioLuanChuyen", Types.VARCHAR },
			{ "SoGioYeuCauXuLy", Types.INTEGER },
			{ "NoiDungYeuCauXuLy", Types.VARCHAR },
			{ "SoGioThucHien", Types.INTEGER },
			{ "TrangThaiHienTai", Types.INTEGER },
			{ "MaNguoiXuLyKeTiep", Types.VARCHAR },
			{ "TenNguoiXuLyKeTiep", Types.VARCHAR },
			{ "TenPhongBanXuLyKeTiep", Types.VARCHAR },
			{ "TrangThaiKeTiep", Types.INTEGER },
			{ "DonViCungCap", Types.VARCHAR },
			{ "TrangThaiXuLy", Types.INTEGER },
			{ "NgayXuLy", Types.TIMESTAMP },
			{ "LoiKhiXuLy", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table exch_trangthaihoso (ID LONG not null primary key,NgayChuyen DATE null,HOSOTTHCCONGID LONG,MaSoHoSo VARCHAR(75) null,NgayHenTra VARCHAR(75) null,MaNguoiXuLyHienTai VARCHAR(75) null,TenNguoiXuLyHienTai VARCHAR(75) null,TenPhongBanXuLyHienTai VARCHAR(75) null,NgayGioLuanChuyen VARCHAR(75) null,SoGioYeuCauXuLy INTEGER,NoiDungYeuCauXuLy VARCHAR(75) null,SoGioThucHien INTEGER,TrangThaiHienTai INTEGER,MaNguoiXuLyKeTiep VARCHAR(75) null,TenNguoiXuLyKeTiep VARCHAR(75) null,TenPhongBanXuLyKeTiep VARCHAR(75) null,TrangThaiKeTiep INTEGER,DonViCungCap VARCHAR(75) null,TrangThaiXuLy INTEGER,NgayXuLy DATE null,LoiKhiXuLy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table exch_trangthaihoso";
	public static final String ORDER_BY_JPQL = " ORDER BY trangThaiHoso.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY exch_trangthaihoso.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.exch.dao.hoso.model.TrangThaiHoso"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.exch.dao.hoso.model.TrangThaiHoso"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.exch.dao.hoso.model.TrangThaiHoso"),
			true);
	public static long TRANGTHAIXULY_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.exch.dao.hoso.model.TrangThaiHoso"));

	public TrangThaiHosoModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TrangThaiHoso.class;
	}

	public String getModelClassName() {
		return TrangThaiHoso.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public Date getNgayChuyen() {
		return _NgayChuyen;
	}

	public void setNgayChuyen(Date NgayChuyen) {
		_NgayChuyen = NgayChuyen;
	}

	public long getOnlineId() {
		return _OnlineId;
	}

	public void setOnlineId(long OnlineId) {
		_OnlineId = OnlineId;
	}

	public String getMaSoHoSo() {
		if (_MaSoHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaSoHoSo;
		}
	}

	public void setMaSoHoSo(String MaSoHoSo) {
		_MaSoHoSo = MaSoHoSo;
	}

	public String getNgayHenTra() {
		if (_NgayHenTra == null) {
			return StringPool.BLANK;
		}
		else {
			return _NgayHenTra;
		}
	}

	public void setNgayHenTra(String NgayHenTra) {
		_NgayHenTra = NgayHenTra;
	}

	public String getMaNguoiXuLyHienTai() {
		if (_MaNguoiXuLyHienTai == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaNguoiXuLyHienTai;
		}
	}

	public void setMaNguoiXuLyHienTai(String MaNguoiXuLyHienTai) {
		_MaNguoiXuLyHienTai = MaNguoiXuLyHienTai;
	}

	public String getTenNguoiXuLyHienTai() {
		if (_TenNguoiXuLyHienTai == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenNguoiXuLyHienTai;
		}
	}

	public void setTenNguoiXuLyHienTai(String TenNguoiXuLyHienTai) {
		_TenNguoiXuLyHienTai = TenNguoiXuLyHienTai;
	}

	public String getTenPhongBanXuLyHienTai() {
		if (_TenPhongBanXuLyHienTai == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenPhongBanXuLyHienTai;
		}
	}

	public void setTenPhongBanXuLyHienTai(String TenPhongBanXuLyHienTai) {
		_TenPhongBanXuLyHienTai = TenPhongBanXuLyHienTai;
	}

	public String getNgayGioLuanChuyen() {
		if (_NgayGioLuanChuyen == null) {
			return StringPool.BLANK;
		}
		else {
			return _NgayGioLuanChuyen;
		}
	}

	public void setNgayGioLuanChuyen(String NgayGioLuanChuyen) {
		_NgayGioLuanChuyen = NgayGioLuanChuyen;
	}

	public int getSoGioYeuCauXuLy() {
		return _SoGioYeuCauXuLy;
	}

	public void setSoGioYeuCauXuLy(int SoGioYeuCauXuLy) {
		_SoGioYeuCauXuLy = SoGioYeuCauXuLy;
	}

	public String getNoiDungYeuCauXuLy() {
		if (_NoiDungYeuCauXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _NoiDungYeuCauXuLy;
		}
	}

	public void setNoiDungYeuCauXuLy(String NoiDungYeuCauXuLy) {
		_NoiDungYeuCauXuLy = NoiDungYeuCauXuLy;
	}

	public int getSoGioThucHien() {
		return _SoGioThucHien;
	}

	public void setSoGioThucHien(int SoGioThucHien) {
		_SoGioThucHien = SoGioThucHien;
	}

	public int getTrangThaiHienTai() {
		return _TrangThaiHienTai;
	}

	public void setTrangThaiHienTai(int TrangThaiHienTai) {
		_TrangThaiHienTai = TrangThaiHienTai;
	}

	public String getMaNguoiXuLyKeTiep() {
		if (_MaNguoiXuLyKeTiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaNguoiXuLyKeTiep;
		}
	}

	public void setMaNguoiXuLyKeTiep(String MaNguoiXuLyKeTiep) {
		_MaNguoiXuLyKeTiep = MaNguoiXuLyKeTiep;
	}

	public String getTenNguoiXuLyKeTiep() {
		if (_TenNguoiXuLyKeTiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenNguoiXuLyKeTiep;
		}
	}

	public void setTenNguoiXuLyKeTiep(String TenNguoiXuLyKeTiep) {
		_TenNguoiXuLyKeTiep = TenNguoiXuLyKeTiep;
	}

	public String getTenPhongBanXuLyKeTiep() {
		if (_TenPhongBanXuLyKeTiep == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenPhongBanXuLyKeTiep;
		}
	}

	public void setTenPhongBanXuLyKeTiep(String TenPhongBanXuLyKeTiep) {
		_TenPhongBanXuLyKeTiep = TenPhongBanXuLyKeTiep;
	}

	public int getTrangThaiKeTiep() {
		return _TrangThaiKeTiep;
	}

	public void setTrangThaiKeTiep(int TrangThaiKeTiep) {
		_TrangThaiKeTiep = TrangThaiKeTiep;
	}

	public String getDonViCungCap() {
		if (_DonViCungCap == null) {
			return StringPool.BLANK;
		}
		else {
			return _DonViCungCap;
		}
	}

	public void setDonViCungCap(String DonViCungCap) {
		_DonViCungCap = DonViCungCap;
	}

	public int getTrangThaiXuLy() {
		return _TrangThaiXuLy;
	}

	public void setTrangThaiXuLy(int TrangThaiXuLy) {
		_columnBitmask |= TRANGTHAIXULY_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiXuLy) {
			_setOriginalTrangThaiXuLy = true;

			_originalTrangThaiXuLy = _TrangThaiXuLy;
		}

		_TrangThaiXuLy = TrangThaiXuLy;
	}

	public int getOriginalTrangThaiXuLy() {
		return _originalTrangThaiXuLy;
	}

	public Date getNgayXuLy() {
		return _NgayXuLy;
	}

	public void setNgayXuLy(Date NgayXuLy) {
		_NgayXuLy = NgayXuLy;
	}

	public String getLoiKhiXuLy() {
		if (_LoiKhiXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _LoiKhiXuLy;
		}
	}

	public void setLoiKhiXuLy(String LoiKhiXuLy) {
		_LoiKhiXuLy = LoiKhiXuLy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TrangThaiHoso toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TrangThaiHoso)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TrangThaiHoso.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TrangThaiHosoImpl trangThaiHosoImpl = new TrangThaiHosoImpl();

		trangThaiHosoImpl.setId(getId());
		trangThaiHosoImpl.setNgayChuyen(getNgayChuyen());
		trangThaiHosoImpl.setOnlineId(getOnlineId());
		trangThaiHosoImpl.setMaSoHoSo(getMaSoHoSo());
		trangThaiHosoImpl.setNgayHenTra(getNgayHenTra());
		trangThaiHosoImpl.setMaNguoiXuLyHienTai(getMaNguoiXuLyHienTai());
		trangThaiHosoImpl.setTenNguoiXuLyHienTai(getTenNguoiXuLyHienTai());
		trangThaiHosoImpl.setTenPhongBanXuLyHienTai(getTenPhongBanXuLyHienTai());
		trangThaiHosoImpl.setNgayGioLuanChuyen(getNgayGioLuanChuyen());
		trangThaiHosoImpl.setSoGioYeuCauXuLy(getSoGioYeuCauXuLy());
		trangThaiHosoImpl.setNoiDungYeuCauXuLy(getNoiDungYeuCauXuLy());
		trangThaiHosoImpl.setSoGioThucHien(getSoGioThucHien());
		trangThaiHosoImpl.setTrangThaiHienTai(getTrangThaiHienTai());
		trangThaiHosoImpl.setMaNguoiXuLyKeTiep(getMaNguoiXuLyKeTiep());
		trangThaiHosoImpl.setTenNguoiXuLyKeTiep(getTenNguoiXuLyKeTiep());
		trangThaiHosoImpl.setTenPhongBanXuLyKeTiep(getTenPhongBanXuLyKeTiep());
		trangThaiHosoImpl.setTrangThaiKeTiep(getTrangThaiKeTiep());
		trangThaiHosoImpl.setDonViCungCap(getDonViCungCap());
		trangThaiHosoImpl.setTrangThaiXuLy(getTrangThaiXuLy());
		trangThaiHosoImpl.setNgayXuLy(getNgayXuLy());
		trangThaiHosoImpl.setLoiKhiXuLy(getLoiKhiXuLy());

		trangThaiHosoImpl.resetOriginalValues();

		return trangThaiHosoImpl;
	}

	public int compareTo(TrangThaiHoso trangThaiHoso) {
		int value = 0;

		if (getId() < trangThaiHoso.getId()) {
			value = -1;
		}
		else if (getId() > trangThaiHoso.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TrangThaiHoso trangThaiHoso = null;

		try {
			trangThaiHoso = (TrangThaiHoso)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = trangThaiHoso.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TrangThaiHosoModelImpl trangThaiHosoModelImpl = this;

		trangThaiHosoModelImpl._originalTrangThaiXuLy = trangThaiHosoModelImpl._TrangThaiXuLy;

		trangThaiHosoModelImpl._setOriginalTrangThaiXuLy = false;

		trangThaiHosoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TrangThaiHoso> toCacheModel() {
		TrangThaiHosoCacheModel trangThaiHosoCacheModel = new TrangThaiHosoCacheModel();

		trangThaiHosoCacheModel.id = getId();

		Date NgayChuyen = getNgayChuyen();

		if (NgayChuyen != null) {
			trangThaiHosoCacheModel.NgayChuyen = NgayChuyen.getTime();
		}
		else {
			trangThaiHosoCacheModel.NgayChuyen = Long.MIN_VALUE;
		}

		trangThaiHosoCacheModel.OnlineId = getOnlineId();

		trangThaiHosoCacheModel.MaSoHoSo = getMaSoHoSo();

		String MaSoHoSo = trangThaiHosoCacheModel.MaSoHoSo;

		if ((MaSoHoSo != null) && (MaSoHoSo.length() == 0)) {
			trangThaiHosoCacheModel.MaSoHoSo = null;
		}

		trangThaiHosoCacheModel.NgayHenTra = getNgayHenTra();

		String NgayHenTra = trangThaiHosoCacheModel.NgayHenTra;

		if ((NgayHenTra != null) && (NgayHenTra.length() == 0)) {
			trangThaiHosoCacheModel.NgayHenTra = null;
		}

		trangThaiHosoCacheModel.MaNguoiXuLyHienTai = getMaNguoiXuLyHienTai();

		String MaNguoiXuLyHienTai = trangThaiHosoCacheModel.MaNguoiXuLyHienTai;

		if ((MaNguoiXuLyHienTai != null) && (MaNguoiXuLyHienTai.length() == 0)) {
			trangThaiHosoCacheModel.MaNguoiXuLyHienTai = null;
		}

		trangThaiHosoCacheModel.TenNguoiXuLyHienTai = getTenNguoiXuLyHienTai();

		String TenNguoiXuLyHienTai = trangThaiHosoCacheModel.TenNguoiXuLyHienTai;

		if ((TenNguoiXuLyHienTai != null) &&
				(TenNguoiXuLyHienTai.length() == 0)) {
			trangThaiHosoCacheModel.TenNguoiXuLyHienTai = null;
		}

		trangThaiHosoCacheModel.TenPhongBanXuLyHienTai = getTenPhongBanXuLyHienTai();

		String TenPhongBanXuLyHienTai = trangThaiHosoCacheModel.TenPhongBanXuLyHienTai;

		if ((TenPhongBanXuLyHienTai != null) &&
				(TenPhongBanXuLyHienTai.length() == 0)) {
			trangThaiHosoCacheModel.TenPhongBanXuLyHienTai = null;
		}

		trangThaiHosoCacheModel.NgayGioLuanChuyen = getNgayGioLuanChuyen();

		String NgayGioLuanChuyen = trangThaiHosoCacheModel.NgayGioLuanChuyen;

		if ((NgayGioLuanChuyen != null) && (NgayGioLuanChuyen.length() == 0)) {
			trangThaiHosoCacheModel.NgayGioLuanChuyen = null;
		}

		trangThaiHosoCacheModel.SoGioYeuCauXuLy = getSoGioYeuCauXuLy();

		trangThaiHosoCacheModel.NoiDungYeuCauXuLy = getNoiDungYeuCauXuLy();

		String NoiDungYeuCauXuLy = trangThaiHosoCacheModel.NoiDungYeuCauXuLy;

		if ((NoiDungYeuCauXuLy != null) && (NoiDungYeuCauXuLy.length() == 0)) {
			trangThaiHosoCacheModel.NoiDungYeuCauXuLy = null;
		}

		trangThaiHosoCacheModel.SoGioThucHien = getSoGioThucHien();

		trangThaiHosoCacheModel.TrangThaiHienTai = getTrangThaiHienTai();

		trangThaiHosoCacheModel.MaNguoiXuLyKeTiep = getMaNguoiXuLyKeTiep();

		String MaNguoiXuLyKeTiep = trangThaiHosoCacheModel.MaNguoiXuLyKeTiep;

		if ((MaNguoiXuLyKeTiep != null) && (MaNguoiXuLyKeTiep.length() == 0)) {
			trangThaiHosoCacheModel.MaNguoiXuLyKeTiep = null;
		}

		trangThaiHosoCacheModel.TenNguoiXuLyKeTiep = getTenNguoiXuLyKeTiep();

		String TenNguoiXuLyKeTiep = trangThaiHosoCacheModel.TenNguoiXuLyKeTiep;

		if ((TenNguoiXuLyKeTiep != null) && (TenNguoiXuLyKeTiep.length() == 0)) {
			trangThaiHosoCacheModel.TenNguoiXuLyKeTiep = null;
		}

		trangThaiHosoCacheModel.TenPhongBanXuLyKeTiep = getTenPhongBanXuLyKeTiep();

		String TenPhongBanXuLyKeTiep = trangThaiHosoCacheModel.TenPhongBanXuLyKeTiep;

		if ((TenPhongBanXuLyKeTiep != null) &&
				(TenPhongBanXuLyKeTiep.length() == 0)) {
			trangThaiHosoCacheModel.TenPhongBanXuLyKeTiep = null;
		}

		trangThaiHosoCacheModel.TrangThaiKeTiep = getTrangThaiKeTiep();

		trangThaiHosoCacheModel.DonViCungCap = getDonViCungCap();

		String DonViCungCap = trangThaiHosoCacheModel.DonViCungCap;

		if ((DonViCungCap != null) && (DonViCungCap.length() == 0)) {
			trangThaiHosoCacheModel.DonViCungCap = null;
		}

		trangThaiHosoCacheModel.TrangThaiXuLy = getTrangThaiXuLy();

		Date NgayXuLy = getNgayXuLy();

		if (NgayXuLy != null) {
			trangThaiHosoCacheModel.NgayXuLy = NgayXuLy.getTime();
		}
		else {
			trangThaiHosoCacheModel.NgayXuLy = Long.MIN_VALUE;
		}

		trangThaiHosoCacheModel.LoiKhiXuLy = getLoiKhiXuLy();

		String LoiKhiXuLy = trangThaiHosoCacheModel.LoiKhiXuLy;

		if ((LoiKhiXuLy != null) && (LoiKhiXuLy.length() == 0)) {
			trangThaiHosoCacheModel.LoiKhiXuLy = null;
		}

		return trangThaiHosoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(43);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", NgayChuyen=");
		sb.append(getNgayChuyen());
		sb.append(", OnlineId=");
		sb.append(getOnlineId());
		sb.append(", MaSoHoSo=");
		sb.append(getMaSoHoSo());
		sb.append(", NgayHenTra=");
		sb.append(getNgayHenTra());
		sb.append(", MaNguoiXuLyHienTai=");
		sb.append(getMaNguoiXuLyHienTai());
		sb.append(", TenNguoiXuLyHienTai=");
		sb.append(getTenNguoiXuLyHienTai());
		sb.append(", TenPhongBanXuLyHienTai=");
		sb.append(getTenPhongBanXuLyHienTai());
		sb.append(", NgayGioLuanChuyen=");
		sb.append(getNgayGioLuanChuyen());
		sb.append(", SoGioYeuCauXuLy=");
		sb.append(getSoGioYeuCauXuLy());
		sb.append(", NoiDungYeuCauXuLy=");
		sb.append(getNoiDungYeuCauXuLy());
		sb.append(", SoGioThucHien=");
		sb.append(getSoGioThucHien());
		sb.append(", TrangThaiHienTai=");
		sb.append(getTrangThaiHienTai());
		sb.append(", MaNguoiXuLyKeTiep=");
		sb.append(getMaNguoiXuLyKeTiep());
		sb.append(", TenNguoiXuLyKeTiep=");
		sb.append(getTenNguoiXuLyKeTiep());
		sb.append(", TenPhongBanXuLyKeTiep=");
		sb.append(getTenPhongBanXuLyKeTiep());
		sb.append(", TrangThaiKeTiep=");
		sb.append(getTrangThaiKeTiep());
		sb.append(", DonViCungCap=");
		sb.append(getDonViCungCap());
		sb.append(", TrangThaiXuLy=");
		sb.append(getTrangThaiXuLy());
		sb.append(", NgayXuLy=");
		sb.append(getNgayXuLy());
		sb.append(", LoiKhiXuLy=");
		sb.append(getLoiKhiXuLy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(67);

		sb.append("<model><model-name>");
		sb.append("org.oep.exch.dao.hoso.model.TrangThaiHoso");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayChuyen</column-name><column-value><![CDATA[");
		sb.append(getNgayChuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OnlineId</column-name><column-value><![CDATA[");
		sb.append(getOnlineId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaSoHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaSoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayHenTra</column-name><column-value><![CDATA[");
		sb.append(getNgayHenTra());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaNguoiXuLyHienTai</column-name><column-value><![CDATA[");
		sb.append(getMaNguoiXuLyHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenNguoiXuLyHienTai</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiXuLyHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenPhongBanXuLyHienTai</column-name><column-value><![CDATA[");
		sb.append(getTenPhongBanXuLyHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayGioLuanChuyen</column-name><column-value><![CDATA[");
		sb.append(getNgayGioLuanChuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoGioYeuCauXuLy</column-name><column-value><![CDATA[");
		sb.append(getSoGioYeuCauXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NoiDungYeuCauXuLy</column-name><column-value><![CDATA[");
		sb.append(getNoiDungYeuCauXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoGioThucHien</column-name><column-value><![CDATA[");
		sb.append(getSoGioThucHien());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThaiHienTai</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiHienTai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaNguoiXuLyKeTiep</column-name><column-value><![CDATA[");
		sb.append(getMaNguoiXuLyKeTiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenNguoiXuLyKeTiep</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiXuLyKeTiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenPhongBanXuLyKeTiep</column-name><column-value><![CDATA[");
		sb.append(getTenPhongBanXuLyKeTiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThaiKeTiep</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiKeTiep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DonViCungCap</column-name><column-value><![CDATA[");
		sb.append(getDonViCungCap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThaiXuLy</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayXuLy</column-name><column-value><![CDATA[");
		sb.append(getNgayXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LoiKhiXuLy</column-name><column-value><![CDATA[");
		sb.append(getLoiKhiXuLy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TrangThaiHoso.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TrangThaiHoso.class
		};
	private long _id;
	private Date _NgayChuyen;
	private long _OnlineId;
	private String _MaSoHoSo;
	private String _NgayHenTra;
	private String _MaNguoiXuLyHienTai;
	private String _TenNguoiXuLyHienTai;
	private String _TenPhongBanXuLyHienTai;
	private String _NgayGioLuanChuyen;
	private int _SoGioYeuCauXuLy;
	private String _NoiDungYeuCauXuLy;
	private int _SoGioThucHien;
	private int _TrangThaiHienTai;
	private String _MaNguoiXuLyKeTiep;
	private String _TenNguoiXuLyKeTiep;
	private String _TenPhongBanXuLyKeTiep;
	private int _TrangThaiKeTiep;
	private String _DonViCungCap;
	private int _TrangThaiXuLy;
	private int _originalTrangThaiXuLy;
	private boolean _setOriginalTrangThaiXuLy;
	private Date _NgayXuLy;
	private String _LoiKhiXuLy;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TrangThaiHoso _escapedModelProxy;
}