/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.oep.exch.dao.hoso.model.TrangThaiHoso;
import org.oep.exch.dao.hoso.service.TrangThaiHosoLocalServiceUtil;

/**
 * The extended model base implementation for the TrangThaiHoso service. Represents a row in the &quot;exch_trangthaihoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrangThaiHosoImpl}.
 * </p>
 *
 * @author NAM
 * @see TrangThaiHosoImpl
 * @see org.oep.exch.dao.hoso.model.TrangThaiHoso
 * @generated
 */
public abstract class TrangThaiHosoBaseImpl extends TrangThaiHosoModelImpl
	implements TrangThaiHoso {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trang thai hoso model instance should use the {@link TrangThaiHoso} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			TrangThaiHosoLocalServiceUtil.addTrangThaiHoso(this);
		}
		else {
			TrangThaiHosoLocalServiceUtil.updateTrangThaiHoso(this);
		}
	}
}