/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen;
import org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyenModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the UpdateHoSoTrucTuyen service. Represents a row in the &quot;exch_hosotructuyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyenModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UpdateHoSoTrucTuyenImpl}.
 * </p>
 *
 * @author NAM
 * @see UpdateHoSoTrucTuyenImpl
 * @see org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen
 * @see org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyenModel
 * @generated
 */
public class UpdateHoSoTrucTuyenModelImpl extends BaseModelImpl<UpdateHoSoTrucTuyen>
	implements UpdateHoSoTrucTuyenModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a update ho so truc tuyen model instance should use the {@link org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen} interface instead.
	 */
	public static final String TABLE_NAME = "exch_hosotructuyen";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "TrangThaiXuLy", Types.INTEGER },
			{ "NgayChuyen", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table exch_hosotructuyen (ID LONG not null primary key,TrangThaiXuLy INTEGER,NgayChuyen DATE null)";
	public static final String TABLE_SQL_DROP = "drop table exch_hosotructuyen";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen"));

	public UpdateHoSoTrucTuyenModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return UpdateHoSoTrucTuyen.class;
	}

	public String getModelClassName() {
		return UpdateHoSoTrucTuyen.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public int getTrangThaiXuLy() {
		return _TrangThaiXuLy;
	}

	public void setTrangThaiXuLy(int TrangThaiXuLy) {
		_TrangThaiXuLy = TrangThaiXuLy;
	}

	public Date getNgayChuyen() {
		return _NgayChuyen;
	}

	public void setNgayChuyen(Date NgayChuyen) {
		_NgayChuyen = NgayChuyen;
	}

	@Override
	public UpdateHoSoTrucTuyen toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (UpdateHoSoTrucTuyen)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					UpdateHoSoTrucTuyen.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		UpdateHoSoTrucTuyenImpl updateHoSoTrucTuyenImpl = new UpdateHoSoTrucTuyenImpl();

		updateHoSoTrucTuyenImpl.setId(getId());
		updateHoSoTrucTuyenImpl.setTrangThaiXuLy(getTrangThaiXuLy());
		updateHoSoTrucTuyenImpl.setNgayChuyen(getNgayChuyen());

		updateHoSoTrucTuyenImpl.resetOriginalValues();

		return updateHoSoTrucTuyenImpl;
	}

	public int compareTo(UpdateHoSoTrucTuyen updateHoSoTrucTuyen) {
		long primaryKey = updateHoSoTrucTuyen.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		UpdateHoSoTrucTuyen updateHoSoTrucTuyen = null;

		try {
			updateHoSoTrucTuyen = (UpdateHoSoTrucTuyen)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = updateHoSoTrucTuyen.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UpdateHoSoTrucTuyen> toCacheModel() {
		UpdateHoSoTrucTuyenCacheModel updateHoSoTrucTuyenCacheModel = new UpdateHoSoTrucTuyenCacheModel();

		updateHoSoTrucTuyenCacheModel.id = getId();

		updateHoSoTrucTuyenCacheModel.TrangThaiXuLy = getTrangThaiXuLy();

		Date NgayChuyen = getNgayChuyen();

		if (NgayChuyen != null) {
			updateHoSoTrucTuyenCacheModel.NgayChuyen = NgayChuyen.getTime();
		}
		else {
			updateHoSoTrucTuyenCacheModel.NgayChuyen = Long.MIN_VALUE;
		}

		return updateHoSoTrucTuyenCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", TrangThaiXuLy=");
		sb.append(getTrangThaiXuLy());
		sb.append(", NgayChuyen=");
		sb.append(getNgayChuyen());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThaiXuLy</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayChuyen</column-name><column-value><![CDATA[");
		sb.append(getNgayChuyen());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UpdateHoSoTrucTuyen.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			UpdateHoSoTrucTuyen.class
		};
	private long _id;
	private int _TrangThaiXuLy;
	private Date _NgayChuyen;
	private transient ExpandoBridge _expandoBridge;
	private UpdateHoSoTrucTuyen _escapedModelProxy;
}