/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.exch.dao.hoso.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen;
import org.oep.exch.dao.hoso.service.UpdateHoSoTrucTuyenLocalServiceUtil;

/**
 * The extended model base implementation for the UpdateHoSoTrucTuyen service. Represents a row in the &quot;exch_hosotructuyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UpdateHoSoTrucTuyenImpl}.
 * </p>
 *
 * @author NAM
 * @see UpdateHoSoTrucTuyenImpl
 * @see org.oep.exch.dao.hoso.model.UpdateHoSoTrucTuyen
 * @generated
 */
public abstract class UpdateHoSoTrucTuyenBaseImpl
	extends UpdateHoSoTrucTuyenModelImpl implements UpdateHoSoTrucTuyen {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a update ho so truc tuyen model instance should use the {@link UpdateHoSoTrucTuyen} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			UpdateHoSoTrucTuyenLocalServiceUtil.addUpdateHoSoTrucTuyen(this);
		}
		else {
			UpdateHoSoTrucTuyenLocalServiceUtil.updateUpdateHoSoTrucTuyen(this);
		}
	}
}