/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.report.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.oep.cmon.dao.report.service.persistence.ReportTongHopPK;

import java.io.Serializable;

/**
 * The base model interface for the ReportTongHop service. Represents a row in the &quot;CMON_RPTONGHOP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.report.model.impl.ReportTongHopModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.report.model.impl.ReportTongHopImpl}.
 * </p>
 *
 * @author VIENPN
 * @see ReportTongHop
 * @see org.oep.cmon.dao.report.model.impl.ReportTongHopImpl
 * @see org.oep.cmon.dao.report.model.impl.ReportTongHopModelImpl
 * @generated
 */
public interface ReportTongHopModel extends BaseModel<ReportTongHop> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a report tong hop model instance should use the {@link ReportTongHop} interface instead.
	 */

	/**
	 * Returns the primary key of this report tong hop.
	 *
	 * @return the primary key of this report tong hop
	 */
	public ReportTongHopPK getPrimaryKey();

	/**
	 * Sets the primary key of this report tong hop.
	 *
	 * @param primaryKey the primary key of this report tong hop
	 */
	public void setPrimaryKey(ReportTongHopPK primaryKey);

	/**
	 * Returns the c o q u a n q u a n l y i d of this report tong hop.
	 *
	 * @return the c o q u a n q u a n l y i d of this report tong hop
	 */
	public long getCOQUANQUANLYID();

	/**
	 * Sets the c o q u a n q u a n l y i d of this report tong hop.
	 *
	 * @param COQUANQUANLYID the c o q u a n q u a n l y i d of this report tong hop
	 */
	public void setCOQUANQUANLYID(long COQUANQUANLYID);

	/**
	 * Returns the n h o m t h u t u c h a n h c h i n h i d of this report tong hop.
	 *
	 * @return the n h o m t h u t u c h a n h c h i n h i d of this report tong hop
	 */
	public long getNHOMTHUTUCHANHCHINHID();

	/**
	 * Sets the n h o m t h u t u c h a n h c h i n h i d of this report tong hop.
	 *
	 * @param NHOMTHUTUCHANHCHINHID the n h o m t h u t u c h a n h c h i n h i d of this report tong hop
	 */
	public void setNHOMTHUTUCHANHCHINHID(long NHOMTHUTUCHANHCHINHID);

	/**
	 * Returns the t h a n g of this report tong hop.
	 *
	 * @return the t h a n g of this report tong hop
	 */
	public int getTHANG();

	/**
	 * Sets the t h a n g of this report tong hop.
	 *
	 * @param THANG the t h a n g of this report tong hop
	 */
	public void setTHANG(int THANG);

	/**
	 * Returns the n a m of this report tong hop.
	 *
	 * @return the n a m of this report tong hop
	 */
	public int getNAM();

	/**
	 * Sets the n a m of this report tong hop.
	 *
	 * @param NAM the n a m of this report tong hop
	 */
	public void setNAM(int NAM);

	/**
	 * Returns the t o n g n h a n of this report tong hop.
	 *
	 * @return the t o n g n h a n of this report tong hop
	 */
	public long getTONGNHAN();

	/**
	 * Sets the t o n g n h a n of this report tong hop.
	 *
	 * @param TONGNHAN the t o n g n h a n of this report tong hop
	 */
	public void setTONGNHAN(long TONGNHAN);

	/**
	 * Returns the t i e p n h a n of this report tong hop.
	 *
	 * @return the t i e p n h a n of this report tong hop
	 */
	public long getTIEPNHAN();

	/**
	 * Sets the t i e p n h a n of this report tong hop.
	 *
	 * @param TIEPNHAN the t i e p n h a n of this report tong hop
	 */
	public void setTIEPNHAN(long TIEPNHAN);

	/**
	 * Returns the t o n d a u of this report tong hop.
	 *
	 * @return the t o n d a u of this report tong hop
	 */
	public long getTONDAU();

	/**
	 * Sets the t o n d a u of this report tong hop.
	 *
	 * @param TONDAU the t o n d a u of this report tong hop
	 */
	public void setTONDAU(long TONDAU);

	/**
	 * Returns the t o n g d a g i a i q u y e t of this report tong hop.
	 *
	 * @return the t o n g d a g i a i q u y e t of this report tong hop
	 */
	public long getTONGDAGIAIQUYET();

	/**
	 * Sets the t o n g d a g i a i q u y e t of this report tong hop.
	 *
	 * @param TONGDAGIAIQUYET the t o n g d a g i a i q u y e t of this report tong hop
	 */
	public void setTONGDAGIAIQUYET(long TONGDAGIAIQUYET);

	/**
	 * Returns the s o m of this report tong hop.
	 *
	 * @return the s o m of this report tong hop
	 */
	public long getSOM();

	/**
	 * Sets the s o m of this report tong hop.
	 *
	 * @param SOM the s o m of this report tong hop
	 */
	public void setSOM(long SOM);

	/**
	 * Returns the d u n g of this report tong hop.
	 *
	 * @return the d u n g of this report tong hop
	 */
	public long getDUNG();

	/**
	 * Sets the d u n g of this report tong hop.
	 *
	 * @param DUNG the d u n g of this report tong hop
	 */
	public void setDUNG(long DUNG);

	/**
	 * Returns the t r e of this report tong hop.
	 *
	 * @return the t r e of this report tong hop
	 */
	public long getTRE();

	/**
	 * Sets the t r e of this report tong hop.
	 *
	 * @param TRE the t r e of this report tong hop
	 */
	public void setTRE(long TRE);

	/**
	 * Returns the t o n g d a n g g i a i q u y e t of this report tong hop.
	 *
	 * @return the t o n g d a n g g i a i q u y e t of this report tong hop
	 */
	public long getTONGDANGGIAIQUYET();

	/**
	 * Sets the t o n g d a n g g i a i q u y e t of this report tong hop.
	 *
	 * @param TONGDANGGIAIQUYET the t o n g d a n g g i a i q u y e t of this report tong hop
	 */
	public void setTONGDANGGIAIQUYET(long TONGDANGGIAIQUYET);

	/**
	 * Returns the c h u a d e n h a n of this report tong hop.
	 *
	 * @return the c h u a d e n h a n of this report tong hop
	 */
	public long getCHUADENHAN();

	/**
	 * Sets the c h u a d e n h a n of this report tong hop.
	 *
	 * @param CHUADENHAN the c h u a d e n h a n of this report tong hop
	 */
	public void setCHUADENHAN(long CHUADENHAN);

	/**
	 * Returns the q u a h a n of this report tong hop.
	 *
	 * @return the q u a h a n of this report tong hop
	 */
	public long getQUAHAN();

	/**
	 * Sets the q u a h a n of this report tong hop.
	 *
	 * @param QUAHAN the q u a h a n of this report tong hop
	 */
	public void setQUAHAN(long QUAHAN);

	/**
	 * Returns the r u t h o s o of this report tong hop.
	 *
	 * @return the r u t h o s o of this report tong hop
	 */
	public long getRUTHOSO();

	/**
	 * Sets the r u t h o s o of this report tong hop.
	 *
	 * @param RUTHOSO the r u t h o s o of this report tong hop
	 */
	public void setRUTHOSO(long RUTHOSO);

	/**
	 * Returns the k h o n g h o p l e of this report tong hop.
	 *
	 * @return the k h o n g h o p l e of this report tong hop
	 */
	public long getKHONGHOPLE();

	/**
	 * Sets the k h o n g h o p l e of this report tong hop.
	 *
	 * @param KHONGHOPLE the k h o n g h o p l e of this report tong hop
	 */
	public void setKHONGHOPLE(long KHONGHOPLE);

	/**
	 * Returns the t y l e of this report tong hop.
	 *
	 * @return the t y l e of this report tong hop
	 */
	public double getTYLE();

	/**
	 * Sets the t y l e of this report tong hop.
	 *
	 * @param TYLE the t y l e of this report tong hop
	 */
	public void setTYLE(double TYLE);

	/**
	 * Returns the t o n c u o i of this report tong hop.
	 *
	 * @return the t o n c u o i of this report tong hop
	 */
	public long getTONCUOI();

	/**
	 * Sets the t o n c u o i of this report tong hop.
	 *
	 * @param TONCUOI the t o n c u o i of this report tong hop
	 */
	public void setTONCUOI(long TONCUOI);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ReportTongHop reportTongHop);

	public int hashCode();

	public CacheModel<ReportTongHop> toCacheModel();

	public ReportTongHop toEscapedModel();

	public String toString();

	public String toXmlString();
}