/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.report.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Role2DonViBaoCao service. Represents a row in the &quot;CMON_RPROLE2DONVIBAOCAO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.report.model.impl.Role2DonViBaoCaoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.report.model.impl.Role2DonViBaoCaoImpl}.
 * </p>
 *
 * @author VIENPN
 * @see Role2DonViBaoCao
 * @see org.oep.cmon.dao.report.model.impl.Role2DonViBaoCaoImpl
 * @see org.oep.cmon.dao.report.model.impl.Role2DonViBaoCaoModelImpl
 * @generated
 */
public interface Role2DonViBaoCaoModel extends BaseModel<Role2DonViBaoCao> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a role2 don vi bao cao model instance should use the {@link Role2DonViBaoCao} interface instead.
	 */

	/**
	 * Returns the primary key of this role2 don vi bao cao.
	 *
	 * @return the primary key of this role2 don vi bao cao
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this role2 don vi bao cao.
	 *
	 * @param primaryKey the primary key of this role2 don vi bao cao
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the i d of this role2 don vi bao cao.
	 *
	 * @return the i d of this role2 don vi bao cao
	 */
	public long getID();

	/**
	 * Sets the i d of this role2 don vi bao cao.
	 *
	 * @param ID the i d of this role2 don vi bao cao
	 */
	public void setID(long ID);

	/**
	 * Returns the r p d a n h m u c r o l e i d of this role2 don vi bao cao.
	 *
	 * @return the r p d a n h m u c r o l e i d of this role2 don vi bao cao
	 */
	public long getRPDANHMUCROLEID();

	/**
	 * Sets the r p d a n h m u c r o l e i d of this role2 don vi bao cao.
	 *
	 * @param RPDANHMUCROLEID the r p d a n h m u c r o l e i d of this role2 don vi bao cao
	 */
	public void setRPDANHMUCROLEID(long RPDANHMUCROLEID);

	/**
	 * Returns the r p d a n h m u c b a o c a o i d of this role2 don vi bao cao.
	 *
	 * @return the r p d a n h m u c b a o c a o i d of this role2 don vi bao cao
	 */
	public long getRPDANHMUCBAOCAOID();

	/**
	 * Sets the r p d a n h m u c b a o c a o i d of this role2 don vi bao cao.
	 *
	 * @param RPDANHMUCBAOCAOID the r p d a n h m u c b a o c a o i d of this role2 don vi bao cao
	 */
	public void setRPDANHMUCBAOCAOID(long RPDANHMUCBAOCAOID);

	/**
	 * Returns the c o q u a n q u a n l y i d of this role2 don vi bao cao.
	 *
	 * @return the c o q u a n q u a n l y i d of this role2 don vi bao cao
	 */
	public long getCOQUANQUANLYID();

	/**
	 * Sets the c o q u a n q u a n l y i d of this role2 don vi bao cao.
	 *
	 * @param COQUANQUANLYID the c o q u a n q u a n l y i d of this role2 don vi bao cao
	 */
	public void setCOQUANQUANLYID(long COQUANQUANLYID);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Role2DonViBaoCao role2DonViBaoCao);

	public int hashCode();

	public CacheModel<Role2DonViBaoCao> toCacheModel();

	public Role2DonViBaoCao toEscapedModel();

	public String toString();

	public String toXmlString();
}