/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.report.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Role2TTHC service. Represents a row in the &quot;CMON_RPROLE2THUTUCHANHCHINH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.report.model.impl.Role2TTHCModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.report.model.impl.Role2TTHCImpl}.
 * </p>
 *
 * @author VIENPN
 * @see Role2TTHC
 * @see org.oep.cmon.dao.report.model.impl.Role2TTHCImpl
 * @see org.oep.cmon.dao.report.model.impl.Role2TTHCModelImpl
 * @generated
 */
public interface Role2TTHCModel extends BaseModel<Role2TTHC> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a role2 t t h c model instance should use the {@link Role2TTHC} interface instead.
	 */

	/**
	 * Returns the primary key of this role2 t t h c.
	 *
	 * @return the primary key of this role2 t t h c
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this role2 t t h c.
	 *
	 * @param primaryKey the primary key of this role2 t t h c
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the i d of this role2 t t h c.
	 *
	 * @return the i d of this role2 t t h c
	 */
	public long getID();

	/**
	 * Sets the i d of this role2 t t h c.
	 *
	 * @param ID the i d of this role2 t t h c
	 */
	public void setID(long ID);

	/**
	 * Returns the r p d a n h m u c r o l e i d of this role2 t t h c.
	 *
	 * @return the r p d a n h m u c r o l e i d of this role2 t t h c
	 */
	public long getRPDANHMUCROLEID();

	/**
	 * Sets the r p d a n h m u c r o l e i d of this role2 t t h c.
	 *
	 * @param RPDANHMUCROLEID the r p d a n h m u c r o l e i d of this role2 t t h c
	 */
	public void setRPDANHMUCROLEID(long RPDANHMUCROLEID);

	/**
	 * Returns the r p d a n h m u c b a o c a o i d of this role2 t t h c.
	 *
	 * @return the r p d a n h m u c b a o c a o i d of this role2 t t h c
	 */
	public long getRPDANHMUCBAOCAOID();

	/**
	 * Sets the r p d a n h m u c b a o c a o i d of this role2 t t h c.
	 *
	 * @param RPDANHMUCBAOCAOID the r p d a n h m u c b a o c a o i d of this role2 t t h c
	 */
	public void setRPDANHMUCBAOCAOID(long RPDANHMUCBAOCAOID);

	/**
	 * Returns the t h u t u c h a n h c h i n h i d of this role2 t t h c.
	 *
	 * @return the t h u t u c h a n h c h i n h i d of this role2 t t h c
	 */
	public long getTHUTUCHANHCHINHID();

	/**
	 * Sets the t h u t u c h a n h c h i n h i d of this role2 t t h c.
	 *
	 * @param THUTUCHANHCHINHID the t h u t u c h a n h c h i n h i d of this role2 t t h c
	 */
	public void setTHUTUCHANHCHINHID(long THUTUCHANHCHINHID);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Role2TTHC role2TTHC);

	public int hashCode();

	public CacheModel<Role2TTHC> toCacheModel();

	public Role2TTHC toEscapedModel();

	public String toString();

	public String toXmlString();
}