/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.nsd.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaiKhoanNguoiDung service. Represents a row in the &quot;CMON_TAIKHOANNGUOIDUNG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.cmon.dao.nsd.model.impl.TaiKhoanNguoiDungModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.cmon.dao.nsd.model.impl.TaiKhoanNguoiDungImpl}.
 * </p>
 *
 * @author Liemnn
 * @see TaiKhoanNguoiDung
 * @see org.oep.cmon.dao.nsd.model.impl.TaiKhoanNguoiDungImpl
 * @see org.oep.cmon.dao.nsd.model.impl.TaiKhoanNguoiDungModelImpl
 * @generated
 */
public interface TaiKhoanNguoiDungModel extends BaseModel<TaiKhoanNguoiDung> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tai khoan nguoi dung model instance should use the {@link TaiKhoanNguoiDung} interface instead.
	 */

	/**
	 * Returns the primary key of this tai khoan nguoi dung.
	 *
	 * @return the primary key of this tai khoan nguoi dung
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tai khoan nguoi dung.
	 *
	 * @param primaryKey the primary key of this tai khoan nguoi dung
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tai khoan nguoi dung.
	 *
	 * @return the ID of this tai khoan nguoi dung
	 */
	public long getId();

	/**
	 * Sets the ID of this tai khoan nguoi dung.
	 *
	 * @param id the ID of this tai khoan nguoi dung
	 */
	public void setId(long id);

	/**
	 * Returns the ten dang nhap of this tai khoan nguoi dung.
	 *
	 * @return the ten dang nhap of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getTenDangNhap();

	/**
	 * Sets the ten dang nhap of this tai khoan nguoi dung.
	 *
	 * @param tenDangNhap the ten dang nhap of this tai khoan nguoi dung
	 */
	public void setTenDangNhap(String tenDangNhap);

	/**
	 * Returns the mat khau of this tai khoan nguoi dung.
	 *
	 * @return the mat khau of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getMatKhau();

	/**
	 * Sets the mat khau of this tai khoan nguoi dung.
	 *
	 * @param matKhau the mat khau of this tai khoan nguoi dung
	 */
	public void setMatKhau(String matKhau);

	/**
	 * Returns the ten nguoi dung of this tai khoan nguoi dung.
	 *
	 * @return the ten nguoi dung of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getTenNguoiDung();

	/**
	 * Sets the ten nguoi dung of this tai khoan nguoi dung.
	 *
	 * @param tenNguoiDung the ten nguoi dung of this tai khoan nguoi dung
	 */
	public void setTenNguoiDung(String tenNguoiDung);

	/**
	 * Returns the cau hoi mat khau of this tai khoan nguoi dung.
	 *
	 * @return the cau hoi mat khau of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getCauHoiMatKhau();

	/**
	 * Sets the cau hoi mat khau of this tai khoan nguoi dung.
	 *
	 * @param cauHoiMatKhau the cau hoi mat khau of this tai khoan nguoi dung
	 */
	public void setCauHoiMatKhau(String cauHoiMatKhau);

	/**
	 * Returns the cau tra loi mat khau of this tai khoan nguoi dung.
	 *
	 * @return the cau tra loi mat khau of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getCauTraLoiMatKhau();

	/**
	 * Sets the cau tra loi mat khau of this tai khoan nguoi dung.
	 *
	 * @param cauTraLoiMatKhau the cau tra loi mat khau of this tai khoan nguoi dung
	 */
	public void setCauTraLoiMatKhau(String cauTraLoiMatKhau);

	/**
	 * Returns the email of this tai khoan nguoi dung.
	 *
	 * @return the email of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this tai khoan nguoi dung.
	 *
	 * @param email the email of this tai khoan nguoi dung
	 */
	public void setEmail(String email);

	/**
	 * Returns the ngay tao of this tai khoan nguoi dung.
	 *
	 * @return the ngay tao of this tai khoan nguoi dung
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this tai khoan nguoi dung.
	 *
	 * @param ngayTao the ngay tao of this tai khoan nguoi dung
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the da xoa of this tai khoan nguoi dung.
	 *
	 * @return the da xoa of this tai khoan nguoi dung
	 */
	public int getDaXoa();

	/**
	 * Sets the da xoa of this tai khoan nguoi dung.
	 *
	 * @param daXoa the da xoa of this tai khoan nguoi dung
	 */
	public void setDaXoa(int daXoa);

	/**
	 * Returns the ngay sua of this tai khoan nguoi dung.
	 *
	 * @return the ngay sua of this tai khoan nguoi dung
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this tai khoan nguoi dung.
	 *
	 * @param ngaySua the ngay sua of this tai khoan nguoi dung
	 */
	public void setNgaySua(Date ngaySua);

	/**
	 * Returns the nguoi tao of this tai khoan nguoi dung.
	 *
	 * @return the nguoi tao of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getNguoiTao();

	/**
	 * Sets the nguoi tao of this tai khoan nguoi dung.
	 *
	 * @param nguoiTao the nguoi tao of this tai khoan nguoi dung
	 */
	public void setNguoiTao(String nguoiTao);

	/**
	 * Returns the nguoi sua of this tai khoan nguoi dung.
	 *
	 * @return the nguoi sua of this tai khoan nguoi dung
	 */
	@AutoEscape
	public String getNguoiSua();

	/**
	 * Sets the nguoi sua of this tai khoan nguoi dung.
	 *
	 * @param nguoiSua the nguoi sua of this tai khoan nguoi dung
	 */
	public void setNguoiSua(String nguoiSua);

	/**
	 * Returns the trang thai of this tai khoan nguoi dung.
	 *
	 * @return the trang thai of this tai khoan nguoi dung
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this tai khoan nguoi dung.
	 *
	 * @param trangThai the trang thai of this tai khoan nguoi dung
	 */
	public void setTrangThai(int trangThai);

	/**
	 * Returns the loai doi tuong ID of this tai khoan nguoi dung.
	 *
	 * @return the loai doi tuong ID of this tai khoan nguoi dung
	 */
	public Long getLoaiDoiTuongId();

	/**
	 * Sets the loai doi tuong ID of this tai khoan nguoi dung.
	 *
	 * @param loaiDoiTuongId the loai doi tuong ID of this tai khoan nguoi dung
	 */
	public void setLoaiDoiTuongId(Long loaiDoiTuongId);

	/**
	 * Returns the tai khoan nguoi dung ID of this tai khoan nguoi dung.
	 *
	 * @return the tai khoan nguoi dung ID of this tai khoan nguoi dung
	 */
	public Long getTaiKhoanNguoiDungId();

	/**
	 * Sets the tai khoan nguoi dung ID of this tai khoan nguoi dung.
	 *
	 * @param taiKhoanNguoiDungId the tai khoan nguoi dung ID of this tai khoan nguoi dung
	 */
	public void setTaiKhoanNguoiDungId(Long taiKhoanNguoiDungId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TaiKhoanNguoiDung taiKhoanNguoiDung);

	public int hashCode();

	public CacheModel<TaiKhoanNguoiDung> toCacheModel();

	public TaiKhoanNguoiDung toEscapedModel();

	public String toString();

	public String toXmlString();
}