
package org.oep.sharedservice.exch.provider.hoso.jaxws;

import javax.ws.rs.Produces;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Thu Jun 27 00:23:19 ICT 2013
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "pushDocument", namespace = "http://hoso.provider.exch.sharedservice.dtt.vn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pushDocument", namespace = "http://hoso.provider.exch.sharedservice.dtt.vn/")
@Produces("text/xml;charset=UTF-8")
public class PushDocument {

    @XmlElement(name = "arg0")
    private org.oep.sharedservice.exch.provider.soap.OSSDocumentSoapList arg0;

    public org.oep.sharedservice.exch.provider.soap.OSSDocumentSoapList getArg0() {
        return this.arg0;
    }

    public void setArg0(org.oep.sharedservice.exch.provider.soap.OSSDocumentSoapList newArg0)  {
        this.arg0 = newArg0;
    }

}

