/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.dlms.dao.capgiaypheplaixe.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;


import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

import org.oep.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXe;
import org.oep.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXeModel;

/**
 * The base model implementation for the CapGiayPhepLaiXe service. Represents a row in the &quot;DLMS_CAPGIAYPHEPLAIXE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CapGiayPhepLaiXeImpl}.
 * </p>
 *
 * @author AnhNT
 * @see CapGiayPhepLaiXeImpl
 * @see org.oep.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXe
 * @see org.oep.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXeModel
 * @generated
 */
public class CapGiayPhepLaiXeModelImpl extends BaseModelImpl<CapGiayPhepLaiXe>
	implements CapGiayPhepLaiXeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cap giay phep lai xe model instance should use the {@link vn.dtt.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXe} interface instead.
	 */
	public static final String TABLE_NAME = "DLMS_CAPGIAYPHEPLAIXE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "COQUANQUANLYID", Types.BIGINT },
			{ "CONGDANID", Types.BIGINT },
			{ "LOAIHOSOID", Types.BIGINT },
			{ "SOHOSO", Types.BIGINT },
			{ "HOVATEN", Types.VARCHAR },
			{ "NGAYSINH", Types.TIMESTAMP },
			{ "GIOITINHID", Types.BIGINT },
			{ "QUOCTICHID", Types.BIGINT },
			{ "SOCMND", Types.VARCHAR },
			{ "NGAYCAPCMND", Types.TIMESTAMP },
			{ "NOICAPCMNDID", Types.BIGINT },
			{ "SOHOCHIEU", Types.VARCHAR },
			{ "NGAYCAPHOCHIEU", Types.TIMESTAMP },
			{ "NOICAPHOCHIEU", Types.BIGINT },
			{ "DIENTHOAI", Types.VARCHAR },
			{ "EMAIL", Types.VARCHAR },
			{ "GHICHU", Types.VARCHAR },
			{ "TINHTHUONGTRUID", Types.BIGINT },
			{ "HUYENTHUONGTRUID", Types.BIGINT },
			{ "XATHUONGTRUID", Types.BIGINT },
			{ "DIACHITHUONGTRU", Types.VARCHAR },
			{ "TINHCUTRUID", Types.BIGINT },
			{ "HUYENCUTRUID", Types.BIGINT },
			{ "XACUTRUID", Types.BIGINT },
			{ "DIACHICUTRU", Types.VARCHAR },
			{ "SOGIAYPHEPLAIXE", Types.VARCHAR },
			{ "HANGGIAYPHEPLAIXEID", Types.BIGINT },
			{ "DONVICAPGPLXID", Types.BIGINT },
			{ "NGAYCAPGPLX", Types.TIMESTAMP },
			{ "NOICAPGPLXID", Types.BIGINT },
			{ "NGAYDAUSATHACH", Types.TIMESTAMP },
			{ "NOIHOCLAIXEID", Types.BIGINT },
			{ "NAMHOCLAIXE", Types.INTEGER },
			{ "NAMTRUNGTUYENHANGCAONHAT", Types.INTEGER },
			{ "LYDOHOC", Types.VARCHAR },
			{ "MUCDICHHOC", Types.VARCHAR },
			{ "SONAMLAIXE", Types.DOUBLE },
			{ "SOKMLAIXE", Types.DOUBLE },
			{ "NGAYTRAGPLX", Types.TIMESTAMP },
			{ "LYDOCAPDOILAIGPLXID", Types.BIGINT },
			{ "LYDO", Types.VARCHAR },
			{ "NGAYTAO", Types.TIMESTAMP },
			{ "NGAYSUA", Types.TIMESTAMP },
			{ "NGUOITAO", Types.VARCHAR },
			{ "NGUOISUA", Types.VARCHAR },
			{ "XOA", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table DLMS_CAPGIAYPHEPLAIXE (ID LONG not null primary key,COQUANQUANLYID LONG,CONGDANID LONG,LOAIHOSOID LONG,SOHOSO LONG,HOVATEN VARCHAR(75) null,NGAYSINH DATE null,GIOITINHID LONG,QUOCTICHID LONG,SOCMND VARCHAR(75) null,NGAYCAPCMND DATE null,NOICAPCMNDID LONG,SOHOCHIEU VARCHAR(75) null,NGAYCAPHOCHIEU DATE null,NOICAPHOCHIEU LONG,DIENTHOAI VARCHAR(75) null,EMAIL VARCHAR(75) null,GHICHU VARCHAR(75) null,TINHTHUONGTRUID LONG,HUYENTHUONGTRUID LONG,XATHUONGTRUID LONG,DIACHITHUONGTRU VARCHAR(75) null,TINHCUTRUID LONG,HUYENCUTRUID LONG,XACUTRUID LONG,DIACHICUTRU VARCHAR(75) null,SOGIAYPHEPLAIXE VARCHAR(75) null,HANGGIAYPHEPLAIXEID LONG,DONVICAPGPLXID LONG,NGAYCAPGPLX DATE null,NOICAPGPLXID LONG,NGAYDAUSATHACH DATE null,NOIHOCLAIXEID LONG,NAMHOCLAIXE INTEGER,NAMTRUNGTUYENHANGCAONHAT INTEGER,LYDOHOC VARCHAR(75) null,MUCDICHHOC VARCHAR(75) null,SONAMLAIXE DOUBLE,SOKMLAIXE DOUBLE,NGAYTRAGPLX DATE null,LYDOCAPDOILAIGPLXID LONG,LYDO VARCHAR(75) null,NGAYTAO DATE null,NGAYSUA DATE null,NGUOITAO VARCHAR(75) null,NGUOISUA VARCHAR(75) null,XOA INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table DLMS_CAPGIAYPHEPLAIXE";
	public static final String ORDER_BY_JPQL = " ORDER BY capGiayPhepLaiXe.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DLMS_CAPGIAYPHEPLAIXE.ID ASC";
	public static final String DATA_SOURCE = "egovDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXe"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXe"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXe"));

	public CapGiayPhepLaiXeModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CapGiayPhepLaiXe.class;
	}

	public String getModelClassName() {
		return CapGiayPhepLaiXe.class.getName();
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public long getIdCoQuanQuanLy() {
		return _idCoQuanQuanLy;
	}

	public void setIdCoQuanQuanLy(long idCoQuanQuanLy) {
		_idCoQuanQuanLy = idCoQuanQuanLy;
	}

	public long getIdCongDan() {
		return _idCongDan;
	}

	public void setIdCongDan(long idCongDan) {
		_idCongDan = idCongDan;
	}

	public long getIdLoaiHoSo() {
		return _idLoaiHoSo;
	}

	public void setIdLoaiHoSo(long idLoaiHoSo) {
		_idLoaiHoSo = idLoaiHoSo;
	}

	public long getSoHoSo() {
		return _soHoSo;
	}

	public void setSoHoSo(long soHoSo) {
		_soHoSo = soHoSo;
	}

	public String getHoVaTen() {
		if (_hoVaTen == null) {
			return StringPool.BLANK;
		}
		else {
			return _hoVaTen;
		}
	}

	public void setHoVaTen(String hoVaTen) {
		_hoVaTen = hoVaTen;
	}

	public Date getNgaySinh() {
		return _ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		_ngaySinh = ngaySinh;
	}

	public long getIdGioiTinh() {
		return _idGioiTinh;
	}

	public void setIdGioiTinh(long idGioiTinh) {
		_idGioiTinh = idGioiTinh;
	}

	public long getIdQuocTich() {
		return _idQuocTich;
	}

	public void setIdQuocTich(long idQuocTich) {
		_idQuocTich = idQuocTich;
	}

	public String getSoCMND() {
		if (_soCMND == null) {
			return StringPool.BLANK;
		}
		else {
			return _soCMND;
		}
	}

	public void setSoCMND(String soCMND) {
		_soCMND = soCMND;
	}

	public Date getNgayCapCMND() {
		return _ngayCapCMND;
	}

	public void setNgayCapCMND(Date ngayCapCMND) {
		_ngayCapCMND = ngayCapCMND;
	}

	public long getIdNoiCapCMND() {
		return _idNoiCapCMND;
	}

	public void setIdNoiCapCMND(long idNoiCapCMND) {
		_idNoiCapCMND = idNoiCapCMND;
	}

	public String getSoHoChieu() {
		if (_soHoChieu == null) {
			return StringPool.BLANK;
		}
		else {
			return _soHoChieu;
		}
	}

	public void setSoHoChieu(String soHoChieu) {
		_soHoChieu = soHoChieu;
	}

	public Date getNgayCapHoChieu() {
		return _ngayCapHoChieu;
	}

	public void setNgayCapHoChieu(Date ngayCapHoChieu) {
		_ngayCapHoChieu = ngayCapHoChieu;
	}

	public long getNoiCapHoChieu() {
		return _noiCapHoChieu;
	}

	public void setNoiCapHoChieu(long noiCapHoChieu) {
		_noiCapHoChieu = noiCapHoChieu;
	}

	public String getDienThoai() {
		if (_dienThoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoai;
		}
	}

	public void setDienThoai(String dienThoai) {
		_dienThoai = dienThoai;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public long getIdTinhThuongTru() {
		return _idTinhThuongTru;
	}

	public void setIdTinhThuongTru(long idTinhThuongTru) {
		_idTinhThuongTru = idTinhThuongTru;
	}

	public long getIdHuyenThuongTru() {
		return _idHuyenThuongTru;
	}

	public void setIdHuyenThuongTru(long idHuyenThuongTru) {
		_idHuyenThuongTru = idHuyenThuongTru;
	}

	public long getIdXaThuongTru() {
		return _idXaThuongTru;
	}

	public void setIdXaThuongTru(long idXaThuongTru) {
		_idXaThuongTru = idXaThuongTru;
	}

	public String getDiaChiThuongTru() {
		if (_diaChiThuongTru == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiThuongTru;
		}
	}

	public void setDiaChiThuongTru(String diaChiThuongTru) {
		_diaChiThuongTru = diaChiThuongTru;
	}

	public long getIdTinhCuTru() {
		return _idTinhCuTru;
	}

	public void setIdTinhCuTru(long idTinhCuTru) {
		_idTinhCuTru = idTinhCuTru;
	}

	public long getIdHuyenCuTru() {
		return _idHuyenCuTru;
	}

	public void setIdHuyenCuTru(long idHuyenCuTru) {
		_idHuyenCuTru = idHuyenCuTru;
	}

	public long getIdXaCuTru() {
		return _idXaCuTru;
	}

	public void setIdXaCuTru(long idXaCuTru) {
		_idXaCuTru = idXaCuTru;
	}

	public String getDiaChiCuTru() {
		if (_diaChiCuTru == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiCuTru;
		}
	}

	public void setDiaChiCuTru(String diaChiCuTru) {
		_diaChiCuTru = diaChiCuTru;
	}

	public String getSoGiayPhepLaiXe() {
		if (_soGiayPhepLaiXe == null) {
			return StringPool.BLANK;
		}
		else {
			return _soGiayPhepLaiXe;
		}
	}

	public void setSoGiayPhepLaiXe(String soGiayPhepLaiXe) {
		_soGiayPhepLaiXe = soGiayPhepLaiXe;
	}

	public long getIdHangGiayPhepLaiXe() {
		return _idHangGiayPhepLaiXe;
	}

	public void setIdHangGiayPhepLaiXe(long idHangGiayPhepLaiXe) {
		_idHangGiayPhepLaiXe = idHangGiayPhepLaiXe;
	}

	public long getIdDonViCapGPLX() {
		return _idDonViCapGPLX;
	}

	public void setIdDonViCapGPLX(long idDonViCapGPLX) {
		_idDonViCapGPLX = idDonViCapGPLX;
	}

	public Date getNgayCapGPLX() {
		return _ngayCapGPLX;
	}

	public void setNgayCapGPLX(Date ngayCapGPLX) {
		_ngayCapGPLX = ngayCapGPLX;
	}

	public long getIdNoiCapGPLX() {
		return _idNoiCapGPLX;
	}

	public void setIdNoiCapGPLX(long idNoiCapGPLX) {
		_idNoiCapGPLX = idNoiCapGPLX;
	}

	public Date getNgayDauSatHach() {
		return _ngayDauSatHach;
	}

	public void setNgayDauSatHach(Date ngayDauSatHach) {
		_ngayDauSatHach = ngayDauSatHach;
	}

	public long getIdNoiHocLaiXe() {
		return _idNoiHocLaiXe;
	}

	public void setIdNoiHocLaiXe(long idNoiHocLaiXe) {
		_idNoiHocLaiXe = idNoiHocLaiXe;
	}

	public int getNamHocLaiXe() {
		return _namHocLaiXe;
	}

	public void setNamHocLaiXe(int namHocLaiXe) {
		_namHocLaiXe = namHocLaiXe;
	}

	public int getNamTrungTuyenHangCaoNhat() {
		return _namTrungTuyenHangCaoNhat;
	}

	public void setNamTrungTuyenHangCaoNhat(int namTrungTuyenHangCaoNhat) {
		_namTrungTuyenHangCaoNhat = namTrungTuyenHangCaoNhat;
	}

	public String getLyDoHoc() {
		if (_lyDoHoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDoHoc;
		}
	}

	public void setLyDoHoc(String lyDoHoc) {
		_lyDoHoc = lyDoHoc;
	}

	public String getMucDichHoc() {
		if (_mucDichHoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _mucDichHoc;
		}
	}

	public void setMucDichHoc(String mucDichHoc) {
		_mucDichHoc = mucDichHoc;
	}

	public double getSoNamLaiXe() {
		return _soNamLaiXe;
	}

	public void setSoNamLaiXe(double soNamLaiXe) {
		_soNamLaiXe = soNamLaiXe;
	}

	public double getSoKmLaiXe() {
		return _soKmLaiXe;
	}

	public void setSoKmLaiXe(double soKmLaiXe) {
		_soKmLaiXe = soKmLaiXe;
	}

	public Date getNgayTraGPLX() {
		return _ngayTraGPLX;
	}

	public void setNgayTraGPLX(Date ngayTraGPLX) {
		_ngayTraGPLX = ngayTraGPLX;
	}

	public long getIdLyDoCapDoiLaiGPLX() {
		return _idLyDoCapDoiLaiGPLX;
	}

	public void setIdLyDoCapDoiLaiGPLX(long idLyDoCapDoiLaiGPLX) {
		_idLyDoCapDoiLaiGPLX = idLyDoCapDoiLaiGPLX;
	}

	public String getLyDo() {
		if (_lyDo == null) {
			return StringPool.BLANK;
		}
		else {
			return _lyDo;
		}
	}

	public void setLyDo(String lyDo) {
		_lyDo = lyDo;
	}

	public Date getNgayTao() {
		return _ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		_ngayTao = ngayTao;
	}

	public Date getNgaySua() {
		return _ngaySua;
	}

	public void setNgaySua(Date ngaySua) {
		_ngaySua = ngaySua;
	}

	public String getNguoiTao() {
		if (_nguoiTao == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiTao;
		}
	}

	public void setNguoiTao(String nguoiTao) {
		_nguoiTao = nguoiTao;
	}

	public String getNguoiSua() {
		if (_nguoiSua == null) {
			return StringPool.BLANK;
		}
		else {
			return _nguoiSua;
		}
	}

	public void setNguoiSua(String nguoiSua) {
		_nguoiSua = nguoiSua;
	}

	public int getXoa() {
		return _xoa;
	}

	public void setXoa(int xoa) {
		_xoa = xoa;
	}

	@Override
	public CapGiayPhepLaiXe toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CapGiayPhepLaiXe)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					CapGiayPhepLaiXe.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		CapGiayPhepLaiXeImpl capGiayPhepLaiXeImpl = new CapGiayPhepLaiXeImpl();

		capGiayPhepLaiXeImpl.setId(getId());
		capGiayPhepLaiXeImpl.setIdCoQuanQuanLy(getIdCoQuanQuanLy());
		capGiayPhepLaiXeImpl.setIdCongDan(getIdCongDan());
		capGiayPhepLaiXeImpl.setIdLoaiHoSo(getIdLoaiHoSo());
		capGiayPhepLaiXeImpl.setSoHoSo(getSoHoSo());
		capGiayPhepLaiXeImpl.setHoVaTen(getHoVaTen());
		capGiayPhepLaiXeImpl.setNgaySinh(getNgaySinh());
		capGiayPhepLaiXeImpl.setIdGioiTinh(getIdGioiTinh());
		capGiayPhepLaiXeImpl.setIdQuocTich(getIdQuocTich());
		capGiayPhepLaiXeImpl.setSoCMND(getSoCMND());
		capGiayPhepLaiXeImpl.setNgayCapCMND(getNgayCapCMND());
		capGiayPhepLaiXeImpl.setIdNoiCapCMND(getIdNoiCapCMND());
		capGiayPhepLaiXeImpl.setSoHoChieu(getSoHoChieu());
		capGiayPhepLaiXeImpl.setNgayCapHoChieu(getNgayCapHoChieu());
		capGiayPhepLaiXeImpl.setNoiCapHoChieu(getNoiCapHoChieu());
		capGiayPhepLaiXeImpl.setDienThoai(getDienThoai());
		capGiayPhepLaiXeImpl.setEmail(getEmail());
		capGiayPhepLaiXeImpl.setGhiChu(getGhiChu());
		capGiayPhepLaiXeImpl.setIdTinhThuongTru(getIdTinhThuongTru());
		capGiayPhepLaiXeImpl.setIdHuyenThuongTru(getIdHuyenThuongTru());
		capGiayPhepLaiXeImpl.setIdXaThuongTru(getIdXaThuongTru());
		capGiayPhepLaiXeImpl.setDiaChiThuongTru(getDiaChiThuongTru());
		capGiayPhepLaiXeImpl.setIdTinhCuTru(getIdTinhCuTru());
		capGiayPhepLaiXeImpl.setIdHuyenCuTru(getIdHuyenCuTru());
		capGiayPhepLaiXeImpl.setIdXaCuTru(getIdXaCuTru());
		capGiayPhepLaiXeImpl.setDiaChiCuTru(getDiaChiCuTru());
		capGiayPhepLaiXeImpl.setSoGiayPhepLaiXe(getSoGiayPhepLaiXe());
		capGiayPhepLaiXeImpl.setIdHangGiayPhepLaiXe(getIdHangGiayPhepLaiXe());
		capGiayPhepLaiXeImpl.setIdDonViCapGPLX(getIdDonViCapGPLX());
		capGiayPhepLaiXeImpl.setNgayCapGPLX(getNgayCapGPLX());
		capGiayPhepLaiXeImpl.setIdNoiCapGPLX(getIdNoiCapGPLX());
		capGiayPhepLaiXeImpl.setNgayDauSatHach(getNgayDauSatHach());
		capGiayPhepLaiXeImpl.setIdNoiHocLaiXe(getIdNoiHocLaiXe());
		capGiayPhepLaiXeImpl.setNamHocLaiXe(getNamHocLaiXe());
		capGiayPhepLaiXeImpl.setNamTrungTuyenHangCaoNhat(getNamTrungTuyenHangCaoNhat());
		capGiayPhepLaiXeImpl.setLyDoHoc(getLyDoHoc());
		capGiayPhepLaiXeImpl.setMucDichHoc(getMucDichHoc());
		capGiayPhepLaiXeImpl.setSoNamLaiXe(getSoNamLaiXe());
		capGiayPhepLaiXeImpl.setSoKmLaiXe(getSoKmLaiXe());
		capGiayPhepLaiXeImpl.setNgayTraGPLX(getNgayTraGPLX());
		capGiayPhepLaiXeImpl.setIdLyDoCapDoiLaiGPLX(getIdLyDoCapDoiLaiGPLX());
		capGiayPhepLaiXeImpl.setLyDo(getLyDo());
		capGiayPhepLaiXeImpl.setNgayTao(getNgayTao());
		capGiayPhepLaiXeImpl.setNgaySua(getNgaySua());
		capGiayPhepLaiXeImpl.setNguoiTao(getNguoiTao());
		capGiayPhepLaiXeImpl.setNguoiSua(getNguoiSua());
		capGiayPhepLaiXeImpl.setXoa(getXoa());

		capGiayPhepLaiXeImpl.resetOriginalValues();

		return capGiayPhepLaiXeImpl;
	}

	public int compareTo(CapGiayPhepLaiXe capGiayPhepLaiXe) {
		int value = 0;

		if (getId() < capGiayPhepLaiXe.getId()) {
			value = -1;
		}
		else if (getId() > capGiayPhepLaiXe.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CapGiayPhepLaiXe capGiayPhepLaiXe = null;

		try {
			capGiayPhepLaiXe = (CapGiayPhepLaiXe)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = capGiayPhepLaiXe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CapGiayPhepLaiXe> toCacheModel() {
		CapGiayPhepLaiXeCacheModel capGiayPhepLaiXeCacheModel = new CapGiayPhepLaiXeCacheModel();

		capGiayPhepLaiXeCacheModel.id = getId();

		capGiayPhepLaiXeCacheModel.idCoQuanQuanLy = getIdCoQuanQuanLy();

		capGiayPhepLaiXeCacheModel.idCongDan = getIdCongDan();

		capGiayPhepLaiXeCacheModel.idLoaiHoSo = getIdLoaiHoSo();

		capGiayPhepLaiXeCacheModel.soHoSo = getSoHoSo();

		capGiayPhepLaiXeCacheModel.hoVaTen = getHoVaTen();

		String hoVaTen = capGiayPhepLaiXeCacheModel.hoVaTen;

		if ((hoVaTen != null) && (hoVaTen.length() == 0)) {
			capGiayPhepLaiXeCacheModel.hoVaTen = null;
		}

		Date ngaySinh = getNgaySinh();

		if (ngaySinh != null) {
			capGiayPhepLaiXeCacheModel.ngaySinh = ngaySinh.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngaySinh = Long.MIN_VALUE;
		}

		capGiayPhepLaiXeCacheModel.idGioiTinh = getIdGioiTinh();

		capGiayPhepLaiXeCacheModel.idQuocTich = getIdQuocTich();

		capGiayPhepLaiXeCacheModel.soCMND = getSoCMND();

		String soCMND = capGiayPhepLaiXeCacheModel.soCMND;

		if ((soCMND != null) && (soCMND.length() == 0)) {
			capGiayPhepLaiXeCacheModel.soCMND = null;
		}

		Date ngayCapCMND = getNgayCapCMND();

		if (ngayCapCMND != null) {
			capGiayPhepLaiXeCacheModel.ngayCapCMND = ngayCapCMND.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngayCapCMND = Long.MIN_VALUE;
		}

		capGiayPhepLaiXeCacheModel.idNoiCapCMND = getIdNoiCapCMND();

		capGiayPhepLaiXeCacheModel.soHoChieu = getSoHoChieu();

		String soHoChieu = capGiayPhepLaiXeCacheModel.soHoChieu;

		if ((soHoChieu != null) && (soHoChieu.length() == 0)) {
			capGiayPhepLaiXeCacheModel.soHoChieu = null;
		}

		Date ngayCapHoChieu = getNgayCapHoChieu();

		if (ngayCapHoChieu != null) {
			capGiayPhepLaiXeCacheModel.ngayCapHoChieu = ngayCapHoChieu.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngayCapHoChieu = Long.MIN_VALUE;
		}

		capGiayPhepLaiXeCacheModel.noiCapHoChieu = getNoiCapHoChieu();

		capGiayPhepLaiXeCacheModel.dienThoai = getDienThoai();

		String dienThoai = capGiayPhepLaiXeCacheModel.dienThoai;

		if ((dienThoai != null) && (dienThoai.length() == 0)) {
			capGiayPhepLaiXeCacheModel.dienThoai = null;
		}

		capGiayPhepLaiXeCacheModel.email = getEmail();

		String email = capGiayPhepLaiXeCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			capGiayPhepLaiXeCacheModel.email = null;
		}

		capGiayPhepLaiXeCacheModel.ghiChu = getGhiChu();

		String ghiChu = capGiayPhepLaiXeCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			capGiayPhepLaiXeCacheModel.ghiChu = null;
		}

		capGiayPhepLaiXeCacheModel.idTinhThuongTru = getIdTinhThuongTru();

		capGiayPhepLaiXeCacheModel.idHuyenThuongTru = getIdHuyenThuongTru();

		capGiayPhepLaiXeCacheModel.idXaThuongTru = getIdXaThuongTru();

		capGiayPhepLaiXeCacheModel.diaChiThuongTru = getDiaChiThuongTru();

		String diaChiThuongTru = capGiayPhepLaiXeCacheModel.diaChiThuongTru;

		if ((diaChiThuongTru != null) && (diaChiThuongTru.length() == 0)) {
			capGiayPhepLaiXeCacheModel.diaChiThuongTru = null;
		}

		capGiayPhepLaiXeCacheModel.idTinhCuTru = getIdTinhCuTru();

		capGiayPhepLaiXeCacheModel.idHuyenCuTru = getIdHuyenCuTru();

		capGiayPhepLaiXeCacheModel.idXaCuTru = getIdXaCuTru();

		capGiayPhepLaiXeCacheModel.diaChiCuTru = getDiaChiCuTru();

		String diaChiCuTru = capGiayPhepLaiXeCacheModel.diaChiCuTru;

		if ((diaChiCuTru != null) && (diaChiCuTru.length() == 0)) {
			capGiayPhepLaiXeCacheModel.diaChiCuTru = null;
		}

		capGiayPhepLaiXeCacheModel.soGiayPhepLaiXe = getSoGiayPhepLaiXe();

		String soGiayPhepLaiXe = capGiayPhepLaiXeCacheModel.soGiayPhepLaiXe;

		if ((soGiayPhepLaiXe != null) && (soGiayPhepLaiXe.length() == 0)) {
			capGiayPhepLaiXeCacheModel.soGiayPhepLaiXe = null;
		}

		capGiayPhepLaiXeCacheModel.idHangGiayPhepLaiXe = getIdHangGiayPhepLaiXe();

		capGiayPhepLaiXeCacheModel.idDonViCapGPLX = getIdDonViCapGPLX();

		Date ngayCapGPLX = getNgayCapGPLX();

		if (ngayCapGPLX != null) {
			capGiayPhepLaiXeCacheModel.ngayCapGPLX = ngayCapGPLX.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngayCapGPLX = Long.MIN_VALUE;
		}

		capGiayPhepLaiXeCacheModel.idNoiCapGPLX = getIdNoiCapGPLX();

		Date ngayDauSatHach = getNgayDauSatHach();

		if (ngayDauSatHach != null) {
			capGiayPhepLaiXeCacheModel.ngayDauSatHach = ngayDauSatHach.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngayDauSatHach = Long.MIN_VALUE;
		}

		capGiayPhepLaiXeCacheModel.idNoiHocLaiXe = getIdNoiHocLaiXe();

		capGiayPhepLaiXeCacheModel.namHocLaiXe = getNamHocLaiXe();

		capGiayPhepLaiXeCacheModel.namTrungTuyenHangCaoNhat = getNamTrungTuyenHangCaoNhat();

		capGiayPhepLaiXeCacheModel.lyDoHoc = getLyDoHoc();

		String lyDoHoc = capGiayPhepLaiXeCacheModel.lyDoHoc;

		if ((lyDoHoc != null) && (lyDoHoc.length() == 0)) {
			capGiayPhepLaiXeCacheModel.lyDoHoc = null;
		}

		capGiayPhepLaiXeCacheModel.mucDichHoc = getMucDichHoc();

		String mucDichHoc = capGiayPhepLaiXeCacheModel.mucDichHoc;

		if ((mucDichHoc != null) && (mucDichHoc.length() == 0)) {
			capGiayPhepLaiXeCacheModel.mucDichHoc = null;
		}

		capGiayPhepLaiXeCacheModel.soNamLaiXe = getSoNamLaiXe();

		capGiayPhepLaiXeCacheModel.soKmLaiXe = getSoKmLaiXe();

		Date ngayTraGPLX = getNgayTraGPLX();

		if (ngayTraGPLX != null) {
			capGiayPhepLaiXeCacheModel.ngayTraGPLX = ngayTraGPLX.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngayTraGPLX = Long.MIN_VALUE;
		}

		capGiayPhepLaiXeCacheModel.idLyDoCapDoiLaiGPLX = getIdLyDoCapDoiLaiGPLX();

		capGiayPhepLaiXeCacheModel.lyDo = getLyDo();

		String lyDo = capGiayPhepLaiXeCacheModel.lyDo;

		if ((lyDo != null) && (lyDo.length() == 0)) {
			capGiayPhepLaiXeCacheModel.lyDo = null;
		}

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			capGiayPhepLaiXeCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			capGiayPhepLaiXeCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			capGiayPhepLaiXeCacheModel.ngaySua = Long.MIN_VALUE;
		}

		capGiayPhepLaiXeCacheModel.nguoiTao = getNguoiTao();

		String nguoiTao = capGiayPhepLaiXeCacheModel.nguoiTao;

		if ((nguoiTao != null) && (nguoiTao.length() == 0)) {
			capGiayPhepLaiXeCacheModel.nguoiTao = null;
		}

		capGiayPhepLaiXeCacheModel.nguoiSua = getNguoiSua();

		String nguoiSua = capGiayPhepLaiXeCacheModel.nguoiSua;

		if ((nguoiSua != null) && (nguoiSua.length() == 0)) {
			capGiayPhepLaiXeCacheModel.nguoiSua = null;
		}

		capGiayPhepLaiXeCacheModel.xoa = getXoa();

		return capGiayPhepLaiXeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(95);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", idCoQuanQuanLy=");
		sb.append(getIdCoQuanQuanLy());
		sb.append(", idCongDan=");
		sb.append(getIdCongDan());
		sb.append(", idLoaiHoSo=");
		sb.append(getIdLoaiHoSo());
		sb.append(", soHoSo=");
		sb.append(getSoHoSo());
		sb.append(", hoVaTen=");
		sb.append(getHoVaTen());
		sb.append(", ngaySinh=");
		sb.append(getNgaySinh());
		sb.append(", idGioiTinh=");
		sb.append(getIdGioiTinh());
		sb.append(", idQuocTich=");
		sb.append(getIdQuocTich());
		sb.append(", soCMND=");
		sb.append(getSoCMND());
		sb.append(", ngayCapCMND=");
		sb.append(getNgayCapCMND());
		sb.append(", idNoiCapCMND=");
		sb.append(getIdNoiCapCMND());
		sb.append(", soHoChieu=");
		sb.append(getSoHoChieu());
		sb.append(", ngayCapHoChieu=");
		sb.append(getNgayCapHoChieu());
		sb.append(", noiCapHoChieu=");
		sb.append(getNoiCapHoChieu());
		sb.append(", dienThoai=");
		sb.append(getDienThoai());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", idTinhThuongTru=");
		sb.append(getIdTinhThuongTru());
		sb.append(", idHuyenThuongTru=");
		sb.append(getIdHuyenThuongTru());
		sb.append(", idXaThuongTru=");
		sb.append(getIdXaThuongTru());
		sb.append(", diaChiThuongTru=");
		sb.append(getDiaChiThuongTru());
		sb.append(", idTinhCuTru=");
		sb.append(getIdTinhCuTru());
		sb.append(", idHuyenCuTru=");
		sb.append(getIdHuyenCuTru());
		sb.append(", idXaCuTru=");
		sb.append(getIdXaCuTru());
		sb.append(", diaChiCuTru=");
		sb.append(getDiaChiCuTru());
		sb.append(", soGiayPhepLaiXe=");
		sb.append(getSoGiayPhepLaiXe());
		sb.append(", idHangGiayPhepLaiXe=");
		sb.append(getIdHangGiayPhepLaiXe());
		sb.append(", idDonViCapGPLX=");
		sb.append(getIdDonViCapGPLX());
		sb.append(", ngayCapGPLX=");
		sb.append(getNgayCapGPLX());
		sb.append(", idNoiCapGPLX=");
		sb.append(getIdNoiCapGPLX());
		sb.append(", ngayDauSatHach=");
		sb.append(getNgayDauSatHach());
		sb.append(", idNoiHocLaiXe=");
		sb.append(getIdNoiHocLaiXe());
		sb.append(", namHocLaiXe=");
		sb.append(getNamHocLaiXe());
		sb.append(", namTrungTuyenHangCaoNhat=");
		sb.append(getNamTrungTuyenHangCaoNhat());
		sb.append(", lyDoHoc=");
		sb.append(getLyDoHoc());
		sb.append(", mucDichHoc=");
		sb.append(getMucDichHoc());
		sb.append(", soNamLaiXe=");
		sb.append(getSoNamLaiXe());
		sb.append(", soKmLaiXe=");
		sb.append(getSoKmLaiXe());
		sb.append(", ngayTraGPLX=");
		sb.append(getNgayTraGPLX());
		sb.append(", idLyDoCapDoiLaiGPLX=");
		sb.append(getIdLyDoCapDoiLaiGPLX());
		sb.append(", lyDo=");
		sb.append(getLyDo());
		sb.append(", ngayTao=");
		sb.append(getNgayTao());
		sb.append(", ngaySua=");
		sb.append(getNgaySua());
		sb.append(", nguoiTao=");
		sb.append(getNguoiTao());
		sb.append(", nguoiSua=");
		sb.append(getNguoiSua());
		sb.append(", xoa=");
		sb.append(getXoa());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(145);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.dlms.dao.capgiaypheplaixe.model.CapGiayPhepLaiXe");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idCoQuanQuanLy</column-name><column-value><![CDATA[");
		sb.append(getIdCoQuanQuanLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idCongDan</column-name><column-value><![CDATA[");
		sb.append(getIdCongDan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idLoaiHoSo</column-name><column-value><![CDATA[");
		sb.append(getIdLoaiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHoSo</column-name><column-value><![CDATA[");
		sb.append(getSoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoVaTen</column-name><column-value><![CDATA[");
		sb.append(getHoVaTen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySinh</column-name><column-value><![CDATA[");
		sb.append(getNgaySinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idGioiTinh</column-name><column-value><![CDATA[");
		sb.append(getIdGioiTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idQuocTich</column-name><column-value><![CDATA[");
		sb.append(getIdQuocTich());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soCMND</column-name><column-value><![CDATA[");
		sb.append(getSoCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapCMND</column-name><column-value><![CDATA[");
		sb.append(getNgayCapCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNoiCapCMND</column-name><column-value><![CDATA[");
		sb.append(getIdNoiCapCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soHoChieu</column-name><column-value><![CDATA[");
		sb.append(getSoHoChieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapHoChieu</column-name><column-value><![CDATA[");
		sb.append(getNgayCapHoChieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiCapHoChieu</column-name><column-value><![CDATA[");
		sb.append(getNoiCapHoChieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoai</column-name><column-value><![CDATA[");
		sb.append(getDienThoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idTinhThuongTru</column-name><column-value><![CDATA[");
		sb.append(getIdTinhThuongTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idHuyenThuongTru</column-name><column-value><![CDATA[");
		sb.append(getIdHuyenThuongTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idXaThuongTru</column-name><column-value><![CDATA[");
		sb.append(getIdXaThuongTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiThuongTru</column-name><column-value><![CDATA[");
		sb.append(getDiaChiThuongTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idTinhCuTru</column-name><column-value><![CDATA[");
		sb.append(getIdTinhCuTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idHuyenCuTru</column-name><column-value><![CDATA[");
		sb.append(getIdHuyenCuTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idXaCuTru</column-name><column-value><![CDATA[");
		sb.append(getIdXaCuTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiCuTru</column-name><column-value><![CDATA[");
		sb.append(getDiaChiCuTru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soGiayPhepLaiXe</column-name><column-value><![CDATA[");
		sb.append(getSoGiayPhepLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idHangGiayPhepLaiXe</column-name><column-value><![CDATA[");
		sb.append(getIdHangGiayPhepLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idDonViCapGPLX</column-name><column-value><![CDATA[");
		sb.append(getIdDonViCapGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayCapGPLX</column-name><column-value><![CDATA[");
		sb.append(getNgayCapGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNoiCapGPLX</column-name><column-value><![CDATA[");
		sb.append(getIdNoiCapGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayDauSatHach</column-name><column-value><![CDATA[");
		sb.append(getNgayDauSatHach());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNoiHocLaiXe</column-name><column-value><![CDATA[");
		sb.append(getIdNoiHocLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namHocLaiXe</column-name><column-value><![CDATA[");
		sb.append(getNamHocLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>namTrungTuyenHangCaoNhat</column-name><column-value><![CDATA[");
		sb.append(getNamTrungTuyenHangCaoNhat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDoHoc</column-name><column-value><![CDATA[");
		sb.append(getLyDoHoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mucDichHoc</column-name><column-value><![CDATA[");
		sb.append(getMucDichHoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNamLaiXe</column-name><column-value><![CDATA[");
		sb.append(getSoNamLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soKmLaiXe</column-name><column-value><![CDATA[");
		sb.append(getSoKmLaiXe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTraGPLX</column-name><column-value><![CDATA[");
		sb.append(getNgayTraGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idLyDoCapDoiLaiGPLX</column-name><column-value><![CDATA[");
		sb.append(getIdLyDoCapDoiLaiGPLX());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lyDo</column-name><column-value><![CDATA[");
		sb.append(getLyDo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTao</column-name><column-value><![CDATA[");
		sb.append(getNgayTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngaySua</column-name><column-value><![CDATA[");
		sb.append(getNgaySua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTao</column-name><column-value><![CDATA[");
		sb.append(getNguoiTao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiSua</column-name><column-value><![CDATA[");
		sb.append(getNguoiSua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xoa</column-name><column-value><![CDATA[");
		sb.append(getXoa());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CapGiayPhepLaiXe.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CapGiayPhepLaiXe.class
		};
	private long _id;
	private long _idCoQuanQuanLy;
	private long _idCongDan;
	private long _idLoaiHoSo;
	private long _soHoSo;
	private String _hoVaTen;
	private Date _ngaySinh;
	private long _idGioiTinh;
	private long _idQuocTich;
	private String _soCMND;
	private Date _ngayCapCMND;
	private long _idNoiCapCMND;
	private String _soHoChieu;
	private Date _ngayCapHoChieu;
	private long _noiCapHoChieu;
	private String _dienThoai;
	private String _email;
	private String _ghiChu;
	private long _idTinhThuongTru;
	private long _idHuyenThuongTru;
	private long _idXaThuongTru;
	private String _diaChiThuongTru;
	private long _idTinhCuTru;
	private long _idHuyenCuTru;
	private long _idXaCuTru;
	private String _diaChiCuTru;
	private String _soGiayPhepLaiXe;
	private long _idHangGiayPhepLaiXe;
	private long _idDonViCapGPLX;
	private Date _ngayCapGPLX;
	private long _idNoiCapGPLX;
	private Date _ngayDauSatHach;
	private long _idNoiHocLaiXe;
	private int _namHocLaiXe;
	private int _namTrungTuyenHangCaoNhat;
	private String _lyDoHoc;
	private String _mucDichHoc;
	private double _soNamLaiXe;
	private double _soKmLaiXe;
	private Date _ngayTraGPLX;
	private long _idLyDoCapDoiLaiGPLX;
	private String _lyDo;
	private Date _ngayTao;
	private Date _ngaySua;
	private String _nguoiTao;
	private String _nguoiSua;
	private int _xoa;
	private transient ExpandoBridge _expandoBridge;
	private CapGiayPhepLaiXe _escapedModelProxy;
}