/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.cmon.dao.kios.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.oep.cmon.dao.kios.model.DanhSachHoSo;
import org.oep.cmon.dao.kios.service.DanhSachCoQuanLocalService;
import org.oep.cmon.dao.kios.service.DanhSachHoSoLocalService;
import org.oep.cmon.dao.kios.service.DanhSachThongKeLocalService;
import org.oep.cmon.dao.kios.service.persistence.DanhSachCoQuanPersistence;
import org.oep.cmon.dao.kios.service.persistence.DanhSachHoSoFinder;
import org.oep.cmon.dao.kios.service.persistence.DanhSachHoSoPersistence;
import org.oep.cmon.dao.kios.service.persistence.DanhSachThongKePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the danh sach ho so local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.oep.cmon.dao.kios.service.impl.DanhSachHoSoLocalServiceImpl}.
 * </p>
 *
 * @author VIENPN
 * @see org.oep.cmon.dao.kios.service.impl.DanhSachHoSoLocalServiceImpl
 * @see org.oep.cmon.dao.kios.service.DanhSachHoSoLocalServiceUtil
 * @generated
 */
public abstract class DanhSachHoSoLocalServiceBaseImpl
	implements DanhSachHoSoLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.oep.cmon.dao.kios.service.DanhSachHoSoLocalServiceUtil} to access the danh sach ho so local service.
	 */

	/**
	 * Adds the danh sach ho so to the database. Also notifies the appropriate model listeners.
	 *
	 * @param danhSachHoSo the danh sach ho so
	 * @return the danh sach ho so that was added
	 * @throws SystemException if a system exception occurred
	 */
	public DanhSachHoSo addDanhSachHoSo(DanhSachHoSo danhSachHoSo)
		throws SystemException {
		danhSachHoSo.setNew(true);

		danhSachHoSo = danhSachHoSoPersistence.update(danhSachHoSo, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(danhSachHoSo);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return danhSachHoSo;
	}

	/**
	 * Creates a new danh sach ho so with the primary key. Does not add the danh sach ho so to the database.
	 *
	 * @param id the primary key for the new danh sach ho so
	 * @return the new danh sach ho so
	 */
	public DanhSachHoSo createDanhSachHoSo(long id) {
		return danhSachHoSoPersistence.create(id);
	}

	/**
	 * Deletes the danh sach ho so with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the danh sach ho so
	 * @throws PortalException if a danh sach ho so with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteDanhSachHoSo(long id)
		throws PortalException, SystemException {
		DanhSachHoSo danhSachHoSo = danhSachHoSoPersistence.remove(id);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(danhSachHoSo);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the danh sach ho so from the database. Also notifies the appropriate model listeners.
	 *
	 * @param danhSachHoSo the danh sach ho so
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteDanhSachHoSo(DanhSachHoSo danhSachHoSo)
		throws SystemException {
		danhSachHoSoPersistence.remove(danhSachHoSo);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(danhSachHoSo);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return danhSachHoSoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return danhSachHoSoPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return danhSachHoSoPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return danhSachHoSoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public DanhSachHoSo fetchDanhSachHoSo(long id) throws SystemException {
		return danhSachHoSoPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the danh sach ho so with the primary key.
	 *
	 * @param id the primary key of the danh sach ho so
	 * @return the danh sach ho so
	 * @throws PortalException if a danh sach ho so with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public DanhSachHoSo getDanhSachHoSo(long id)
		throws PortalException, SystemException {
		return danhSachHoSoPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return danhSachHoSoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the danh sach ho sos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of danh sach ho sos
	 * @param end the upper bound of the range of danh sach ho sos (not inclusive)
	 * @return the range of danh sach ho sos
	 * @throws SystemException if a system exception occurred
	 */
	public List<DanhSachHoSo> getDanhSachHoSos(int start, int end)
		throws SystemException {
		return danhSachHoSoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of danh sach ho sos.
	 *
	 * @return the number of danh sach ho sos
	 * @throws SystemException if a system exception occurred
	 */
	public int getDanhSachHoSosCount() throws SystemException {
		return danhSachHoSoPersistence.countAll();
	}

	/**
	 * Updates the danh sach ho so in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param danhSachHoSo the danh sach ho so
	 * @return the danh sach ho so that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public DanhSachHoSo updateDanhSachHoSo(DanhSachHoSo danhSachHoSo)
		throws SystemException {
		return updateDanhSachHoSo(danhSachHoSo, true);
	}

	/**
	 * Updates the danh sach ho so in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param danhSachHoSo the danh sach ho so
	 * @param merge whether to merge the danh sach ho so with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the danh sach ho so that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public DanhSachHoSo updateDanhSachHoSo(DanhSachHoSo danhSachHoSo,
		boolean merge) throws SystemException {
		danhSachHoSo.setNew(false);

		danhSachHoSo = danhSachHoSoPersistence.update(danhSachHoSo, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(danhSachHoSo);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return danhSachHoSo;
	}

	/**
	 * Returns the danh sach co quan local service.
	 *
	 * @return the danh sach co quan local service
	 */
	public DanhSachCoQuanLocalService getDanhSachCoQuanLocalService() {
		return danhSachCoQuanLocalService;
	}

	/**
	 * Sets the danh sach co quan local service.
	 *
	 * @param danhSachCoQuanLocalService the danh sach co quan local service
	 */
	public void setDanhSachCoQuanLocalService(
		DanhSachCoQuanLocalService danhSachCoQuanLocalService) {
		this.danhSachCoQuanLocalService = danhSachCoQuanLocalService;
	}

	/**
	 * Returns the danh sach co quan persistence.
	 *
	 * @return the danh sach co quan persistence
	 */
	public DanhSachCoQuanPersistence getDanhSachCoQuanPersistence() {
		return danhSachCoQuanPersistence;
	}

	/**
	 * Sets the danh sach co quan persistence.
	 *
	 * @param danhSachCoQuanPersistence the danh sach co quan persistence
	 */
	public void setDanhSachCoQuanPersistence(
		DanhSachCoQuanPersistence danhSachCoQuanPersistence) {
		this.danhSachCoQuanPersistence = danhSachCoQuanPersistence;
	}

	/**
	 * Returns the danh sach ho so local service.
	 *
	 * @return the danh sach ho so local service
	 */
	public DanhSachHoSoLocalService getDanhSachHoSoLocalService() {
		return danhSachHoSoLocalService;
	}

	/**
	 * Sets the danh sach ho so local service.
	 *
	 * @param danhSachHoSoLocalService the danh sach ho so local service
	 */
	public void setDanhSachHoSoLocalService(
		DanhSachHoSoLocalService danhSachHoSoLocalService) {
		this.danhSachHoSoLocalService = danhSachHoSoLocalService;
	}

	/**
	 * Returns the danh sach ho so persistence.
	 *
	 * @return the danh sach ho so persistence
	 */
	public DanhSachHoSoPersistence getDanhSachHoSoPersistence() {
		return danhSachHoSoPersistence;
	}

	/**
	 * Sets the danh sach ho so persistence.
	 *
	 * @param danhSachHoSoPersistence the danh sach ho so persistence
	 */
	public void setDanhSachHoSoPersistence(
		DanhSachHoSoPersistence danhSachHoSoPersistence) {
		this.danhSachHoSoPersistence = danhSachHoSoPersistence;
	}

	/**
	 * Returns the danh sach ho so finder.
	 *
	 * @return the danh sach ho so finder
	 */
	public DanhSachHoSoFinder getDanhSachHoSoFinder() {
		return danhSachHoSoFinder;
	}

	/**
	 * Sets the danh sach ho so finder.
	 *
	 * @param danhSachHoSoFinder the danh sach ho so finder
	 */
	public void setDanhSachHoSoFinder(DanhSachHoSoFinder danhSachHoSoFinder) {
		this.danhSachHoSoFinder = danhSachHoSoFinder;
	}

	/**
	 * Returns the danh sach thong ke local service.
	 *
	 * @return the danh sach thong ke local service
	 */
	public DanhSachThongKeLocalService getDanhSachThongKeLocalService() {
		return danhSachThongKeLocalService;
	}

	/**
	 * Sets the danh sach thong ke local service.
	 *
	 * @param danhSachThongKeLocalService the danh sach thong ke local service
	 */
	public void setDanhSachThongKeLocalService(
		DanhSachThongKeLocalService danhSachThongKeLocalService) {
		this.danhSachThongKeLocalService = danhSachThongKeLocalService;
	}

	/**
	 * Returns the danh sach thong ke persistence.
	 *
	 * @return the danh sach thong ke persistence
	 */
	public DanhSachThongKePersistence getDanhSachThongKePersistence() {
		return danhSachThongKePersistence;
	}

	/**
	 * Sets the danh sach thong ke persistence.
	 *
	 * @param danhSachThongKePersistence the danh sach thong ke persistence
	 */
	public void setDanhSachThongKePersistence(
		DanhSachThongKePersistence danhSachThongKePersistence) {
		this.danhSachThongKePersistence = danhSachThongKePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.oep.cmon.dao.kios.model.DanhSachHoSo",
			danhSachHoSoLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.oep.cmon.dao.kios.model.DanhSachHoSo");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return DanhSachHoSo.class;
	}

	protected String getModelClassName() {
		return DanhSachHoSo.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = danhSachHoSoPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = DanhSachCoQuanLocalService.class)
	protected DanhSachCoQuanLocalService danhSachCoQuanLocalService;
	@BeanReference(type = DanhSachCoQuanPersistence.class)
	protected DanhSachCoQuanPersistence danhSachCoQuanPersistence;
	@BeanReference(type = DanhSachHoSoLocalService.class)
	protected DanhSachHoSoLocalService danhSachHoSoLocalService;
	@BeanReference(type = DanhSachHoSoPersistence.class)
	protected DanhSachHoSoPersistence danhSachHoSoPersistence;
	@BeanReference(type = DanhSachHoSoFinder.class)
	protected DanhSachHoSoFinder danhSachHoSoFinder;
	@BeanReference(type = DanhSachThongKeLocalService.class)
	protected DanhSachThongKeLocalService danhSachThongKeLocalService;
	@BeanReference(type = DanhSachThongKePersistence.class)
	protected DanhSachThongKePersistence danhSachThongKePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(DanhSachHoSoLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}